import type { StepProblem } from '../types';

/** Step-Through problems for topic "antiderivatives". Authored by content-author; verified by math-verifier. */
export const steps: StepProblem[] = [
  // ───────────────────────── ad-s-01: ∫ x/√(4 − x²) dx ─────────────────────────
  {
    id: 'ad-s-01',
    topic: 'antiderivatives',
    title: 'Numerator is the inner derivative',
    difficulty: 1,
    statement: { text: 'Find', latex: '\\int \\frac{x}{\\sqrt{4-x^2}}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution works directly?',
        options: [
          { text: '$u = 4 - x^2$' },
          { text: '$u = x$', mistake: 'u-choice-wrong', why: 'This changes nothing: du = dx and the integral is exactly as hard as before.' },
          {
            text: '$u = 4 - x$',
            mistake: 'u-choice-wrong',
            why: 'du = −dx, so the x in the numerator and the x² under the root both remain.',
          },
          {
            text: '$u = \\frac{x}{2}$, to get an arcsine',
            mistake: 'technique-wrong',
            why: 'The arcsine form needs a constant numerator; here the numerator x is (up to −1/2) the derivative of 4 − x².',
          },
          {
            text: 'Integration by parts with $u = x$, $dv = \\frac{dx}{\\sqrt{4-x^2}}$',
            mistake: 'ibp-when-usub',
            why: 'This leads to ∫arcsin(x/2)dx, which is harder; the integrand already has the form f(g(x))g′(x).',
          },
        ],
        correct: 0,
        explanation: 'The numerator $x$ is, up to the constant $-\\frac{1}{2}$, the derivative of the inner function $4 - x^2$.',
        result: { latex: 'u = 4 - x^2' },
      },
      {
        prompt: 'With $u = 4 - x^2$, what is $du$?',
        options: [
          { latex: 'du = -2x\\,dx', expr: '-2*x*dx' },
          { latex: 'du = 2x\\,dx', expr: '2*x*dx', mistake: 'u-cos-sign-missing', why: 'd/dx(4 − x²) = −2x; the minus sign was dropped.' },
          { latex: 'du = -x\\,dx', expr: '-x*dx', mistake: 'du-constant-wrong', why: 'd/dx(x²) = 2x, so the factor 2 is needed.' },
          { latex: 'du = (4 - 2x)\\,dx', expr: '(4 - 2*x)*dx', mistake: 'constant-derivative', why: 'The derivative of the constant 4 is 0, not 4.' },
          { latex: 'du = -2x', expr: '-2*x', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(4 - x^2) = -2x$, so $du = -2x\\,dx$ and $x\\,dx = -\\frac{1}{2}\\,du$.',
        result: { latex: 'du = -2x\\,dx \\;\\Rightarrow\\; x\\,dx = -\\frac{1}{2}\\,du' },
        check: { kind: 'value', expected: '-2*x*dx' },
      },
      {
        prompt: 'Rewrite the integral in terms of $u$.',
        options: [
          { latex: '-\\frac{1}{2}\\int u^{-1/2}\\,du', expr: 'indefinite(-u^(-1/2)/2, u)' },
          {
            latex: '\\frac{1}{2}\\int u^{-1/2}\\,du',
            expr: 'indefinite(u^(-1/2)/2, u)',
            mistake: 'u-cos-sign-missing',
            why: 'x dx = −du/2 carries the minus sign from du = −2x dx.',
          },
          {
            latex: '-2\\int u^{-1/2}\\,du',
            expr: 'indefinite(-2*u^(-1/2), u)',
            mistake: 'du-constant-wrong',
            why: 'x dx = −du/2, not −2 du.',
          },
          {
            latex: '-\\frac{1}{2}\\int x\\,u^{-1/2}\\,du',
            expr: 'indefinite(-x*u^(-1/2)/2, u)',
            mistake: 'leftover-x-in-u-integral',
            why: 'The x was absorbed into du; no x may remain inside a u-integral.',
          },
          {
            latex: '-\\frac{1}{2}\\int u^{1/2}\\,du',
            expr: 'indefinite(-u^(1/2)/2, u)',
            mistake: 'algebra-error',
            why: '1/√u = u^{−1/2}; the root is in the denominator, so the exponent is negative.',
          },
        ],
        correct: 0,
        explanation: '$x\\,dx = -\\frac{1}{2}\\,du$ and $\\frac{1}{\\sqrt{4-x^2}} = u^{-1/2}$.',
        result: { latex: '\\int \\frac{x}{\\sqrt{4-x^2}}\\,dx = -\\frac{1}{2}\\int u^{-1/2}\\,du' },
        check: { kind: 'identity', lhs: '-u^(-1/2)/2' },
      },
      {
        prompt: 'Integrate $-\\frac{1}{2}\\int u^{-1/2}\\,du$.',
        variable: 'u',
        options: [
          { latex: '-u^{1/2} + C', expr: '-u^(1/2)' },
          {
            latex: '-\\frac{1}{2}u^{1/2} + C',
            expr: '-u^(1/2)/2',
            mistake: 'power-rule-int-coefficient',
            why: 'After raising the exponent to 1/2 you must divide by 1/2 (multiply by 2); that step was skipped.',
          },
          {
            latex: '-\\frac{1}{4}u^{1/2} + C',
            expr: '-u^(1/2)/4',
            mistake: 'power-rule-int-coefficient',
            why: 'Multiplied by the new exponent 1/2 instead of dividing by it.',
          },
          {
            latex: '\\frac{1}{4}u^{-3/2} + C',
            expr: 'u^(-3/2)/4',
            mistake: 'differentiated-instead',
            why: 'This is the derivative of −½u^{−1/2}: the exponent went down instead of up.',
          },
          {
            latex: '-\\frac{1}{2}\\ln|u| + C',
            expr: '-log(abs(u))/2',
            mistake: 'ln-misapplied',
            why: 'Only u^{−1} integrates to ln|u|; u^{−1/2} uses the power rule.',
          },
        ],
        correct: 0,
        explanation: '$\\int u^{-1/2}\\,du = \\frac{u^{1/2}}{1/2} = 2u^{1/2}$, and $-\\frac{1}{2}\\cdot 2u^{1/2} = -u^{1/2}$.',
        result: { latex: '= -\\frac{1}{2}\\cdot 2u^{1/2} + C = -u^{1/2} + C' },
        check: { kind: 'antiderivative', integrand: '-u^(-1/2)/2' },
      },
      {
        prompt: 'Return to $x$.',
        options: [
          { latex: '-\\sqrt{4-x^2} + C', expr: '-sqrt(4-x^2)' },
          { latex: '\\sqrt{4-x^2} + C', expr: 'sqrt(4-x^2)', mistake: 'sign-error', why: 'The minus sign from x dx = −du/2 carries through to the answer.' },
          { latex: '-\\sqrt{u} + C', expr: '-sqrt(u)', mistake: 'not-back-substituted', why: 'The answer must be in x: replace u by 4 − x².' },
          {
            latex: '-x\\sqrt{4-x^2} + C',
            expr: '-x*sqrt(4-x^2)',
            mistake: 'leftover-x-in-u-integral',
            why: 'The x was absorbed into du; it must not reappear in the answer.',
          },
          { latex: '-\\sqrt{4-x} + C', expr: '-sqrt(4-x)', mistake: 'back-substitution-wrong', why: 'u was 4 − x², not 4 − x.' },
        ],
        correct: 0,
        explanation: 'Replace $u$ by $4 - x^2$: $-u^{1/2} = -\\sqrt{4 - x^2}$.',
        result: { latex: '= -\\sqrt{4-x^2} + C' },
        check: { kind: 'antiderivative', integrand: 'x/sqrt(4-x^2)' },
      },
    ],
    final: {
      latex: '-\\sqrt{4-x^2} + C',
      expr: '-sqrt(4-x^2)',
      check: { kind: 'antiderivative', integrand: 'x/sqrt(4-x^2)' },
      recap: 'The numerator $x$ is a constant multiple of the derivative of $4 - x^2$, so $u = 4 - x^2$ with $x\\,dx = -\\frac{1}{2}du$ turns the integral into a power of $u$.',
    },
  },

  // ───────────────────────── ad-s-02: ∫ x²/(x³ + 1) dx ─────────────────────────
  {
    id: 'ad-s-02',
    topic: 'antiderivatives',
    title: 'Numerator is a multiple of the denominator’s derivative',
    difficulty: 1,
    statement: { text: 'Find', latex: '\\int \\frac{x^2}{x^3+1}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution works directly?',
        options: [
          { text: '$u = x^3 + 1$' },
          { text: '$u = x^2$', mistake: 'u-choice-wrong', why: 'du = 2x dx is not in the integrand, and the denominator does not simplify.' },
          { text: '$u = 3x^2$', mistake: 'u-choice-wrong', why: '3x² is du/dx for the right choice of u, not an inner function of the integrand.' },
          {
            text: 'Split into $\\int x^2\\,dx \\cdot \\int \\frac{dx}{x^3+1}$',
            mistake: 'product-rule-integral',
            why: 'There is no product rule for integrals.',
          },
          {
            text: 'Integration by parts with $u = x^2$, $dv = \\frac{dx}{x^3+1}$',
            mistake: 'ibp-when-usub',
            why: 'v = ∫dx/(x³ + 1) is much harder; the numerator is already (up to 1/3) the derivative of the denominator.',
          },
        ],
        correct: 0,
        explanation: 'The numerator $x^2$ is, up to the factor $\\frac{1}{3}$, the derivative of the denominator $x^3 + 1$.',
        result: { latex: 'u = x^3 + 1' },
      },
      {
        prompt: 'What is $du$?',
        options: [
          { latex: 'du = 3x^2\\,dx', expr: '3*x^2*dx' },
          { latex: 'du = x^2\\,dx', expr: 'x^2*dx', mistake: 'du-constant-wrong', why: 'd/dx(x³) = 3x²; the factor 3 was dropped.' },
          { latex: 'du = 3x^3\\,dx', expr: '3*x^3*dx', mistake: 'power-rule-exponent', why: 'Differentiating x³ lowers the exponent to 2.' },
          { latex: 'du = (3x^2 + 1)\\,dx', expr: '(3*x^2 + 1)*dx', mistake: 'constant-derivative', why: 'The derivative of the constant 1 is 0.' },
          { latex: 'du = 3x^2', expr: '3*x^2', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(x^3 + 1) = 3x^2$, so $du = 3x^2\\,dx$.',
        result: { latex: 'du = 3x^2\\,dx \\;\\Rightarrow\\; x^2\\,dx = \\frac{1}{3}\\,du' },
        check: { kind: 'value', expected: '3*x^2*dx' },
      },
      {
        prompt: 'Rewrite the integral in terms of $u$.',
        options: [
          { latex: '\\frac{1}{3}\\int \\frac{1}{u}\\,du', expr: 'indefinite(1/(3*u), u)' },
          { latex: '3\\int \\frac{1}{u}\\,du', expr: 'indefinite(3/u, u)', mistake: 'du-constant-wrong', why: 'x² dx = du/3, not 3 du.' },
          {
            latex: '\\int \\frac{1}{u}\\,du',
            expr: 'indefinite(1/u, u)',
            mistake: 'du-constant-wrong',
            why: 'du = 3x² dx, so x² dx = du/3; the factor 1/3 was dropped.',
          },
          {
            latex: '\\frac{1}{3}\\int \\frac{x^2}{u}\\,du',
            expr: 'indefinite(x^2/(3*u), u)',
            mistake: 'leftover-x-in-u-integral',
            why: 'x² dx was absorbed into du/3; no x may remain inside a u-integral.',
          },
          {
            latex: '\\frac{1}{3}\\int \\frac{1}{u+1}\\,du',
            expr: 'indefinite(1/(3*(u+1)), u)',
            mistake: 'back-substitution-wrong',
            why: 'u = x³ + 1 replaces the whole denominator, so it becomes u, not u + 1.',
          },
        ],
        correct: 0,
        explanation: 'The denominator becomes $u$ and $x^2\\,dx = \\frac{1}{3}\\,du$.',
        result: { latex: '= \\frac{1}{3}\\int \\frac{du}{u}' },
        check: { kind: 'identity', lhs: '1/(3*u)' },
      },
      {
        prompt: 'Integrate and return to $x$.',
        options: [
          { latex: '\\frac{1}{3}\\ln|x^3+1| + C', expr: 'log(abs(x^3+1))/3' },
          { latex: '\\ln|x^3+1| + C', expr: 'log(abs(x^3+1))', mistake: 'du-constant-wrong', why: 'The factor 1/3 from x² dx = du/3 was lost.' },
          {
            latex: '-\\frac{1}{6(x^3+1)^2} + C',
            expr: '-1/(6*(x^3+1)^2)',
            mistake: 'ln-misapplied',
            why: 'Used a power rule on u^{−1} (as u^{−2}/(−2)); the power −1 integrates to ln|u|.',
          },
          { latex: '\\frac{1}{3}\\ln|x^3| + C', expr: 'log(abs(x^3))/3', mistake: 'ln-argument-wrong', why: 'The argument is u = x³ + 1; the +1 was lost.' },
          { latex: '\\frac{1}{3}\\ln|u| + C', expr: 'log(abs(u))/3', mistake: 'not-back-substituted', why: 'The answer must be in x: replace u by x³ + 1.' },
        ],
        correct: 0,
        explanation: '$\\frac{1}{3}\\int\\frac{du}{u} = \\frac{1}{3}\\ln|u| + C$ with $u = x^3 + 1$.',
        result: { latex: '= \\frac{1}{3}\\ln|u| + C = \\frac{1}{3}\\ln|x^3+1| + C' },
        check: { kind: 'antiderivative', integrand: 'x^2/(x^3+1)' },
      },
    ],
    final: {
      latex: '\\frac{1}{3}\\ln|x^3+1| + C',
      expr: 'log(abs(x^3+1))/3',
      check: { kind: 'antiderivative', integrand: 'x^2/(x^3+1)' },
      recap: 'The numerator $x^2$ is $\\frac{1}{3}$ of the derivative of the denominator, so $u = x^3 + 1$ turns the integral into $\\frac{1}{3}\\int\\frac{du}{u}$.',
    },
  },

  // ───────────────────────── ad-s-03: ∫₁ᵉ ln x / x dx ─────────────────────────
  {
    id: 'ad-s-03',
    topic: 'antiderivatives',
    title: 'Definite integral with u = ln x',
    difficulty: 1,
    statement: { text: 'Evaluate', latex: '\\int_1^e \\frac{\\ln x}{x}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution works directly?',
        options: [
          { text: '$u = \\ln x$' },
          { text: '$u = \\frac{1}{x}$', mistake: 'u-choice-wrong', why: 'du = −dx/x² does not match dx/x, and ln x would remain.' },
          { text: '$u = x\\ln x$', mistake: 'u-choice-wrong', why: 'du = (ln x + 1)dx is not in the integrand.' },
          {
            text: '$u = \\frac{\\ln x}{x}$, the whole integrand',
            mistake: 'u-choice-wrong',
            why: 'Its derivative (1 − ln x)/x² does not appear; u should be an inner function whose derivative is present.',
          },
          {
            text: 'Split into $\\int_1^e \\ln x\\,dx \\cdot \\int_1^e \\frac{dx}{x}$',
            mistake: 'product-rule-integral',
            why: 'There is no product rule for integrals.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}\\ln x = \\frac{1}{x}$, and $\\frac{dx}{x}$ is exactly the other factor.',
        result: { latex: 'u = \\ln x,\\quad du = \\frac{dx}{x}' },
      },
      {
        prompt: 'What are the new limits of integration?',
        options: [
          { latex: 'u(1) = 0,\\ u(e) = 1', expr: '[0, 1]' },
          {
            latex: 'u(1) = 1,\\ u(e) = e',
            expr: '[1, e]',
            mistake: 'bounds-not-converted',
            why: 'These are the x-limits; they must be pushed through u = ln x.',
          },
          { latex: 'u(1) = 0,\\ u(e) = e', expr: '[0, e]', mistake: 'arithmetic-error', why: 'ln e = 1, not e.' },
          { latex: 'u(1) = 1,\\ u(e) = 1', expr: '[1, 1]', mistake: 'arithmetic-error', why: 'ln 1 = 0, because e⁰ = 1.' },
          {
            latex: 'u(1) = 1,\\ u(e) = \\frac{1}{e}',
            expr: '[1, 1/e]',
            mistake: 'algebra-error',
            why: 'Those are values of 1/x = du/dx; the limits come from u = ln x itself.',
          },
        ],
        correct: 0,
        explanation: 'Plug the x-limits into $u = \\ln x$: $\\ln 1 = 0$ and $\\ln e = 1$.',
        result: { latex: 'x = 1 \\Rightarrow u = 0,\\quad x = e \\Rightarrow u = 1' },
        check: { kind: 'value', expected: '[0, 1]' },
      },
      {
        prompt: 'Rewrite the integral entirely in $u$.',
        options: [
          { latex: '\\int_0^1 u\\,du', expr: 'integral(u, u, 0, 1)' },
          { latex: '\\int_1^e u\\,du', expr: 'integral(u, u, 1, e)', mistake: 'bounds-not-converted', why: 'The limits were left as x-values.' },
          {
            latex: '\\int_0^1 \\frac{u}{x}\\,du',
            expr: 'integral(u/x, u, 0, 1)',
            mistake: 'leftover-x-in-u-integral',
            why: 'dx/x is exactly du; the 1/x must not remain.',
          },
          { latex: '\\int_0^1 u\\,dx', expr: 'integral(u, x, 0, 1)', mistake: 'dx-not-replaced', why: 'The differential must be du after the substitution.' },
          { latex: '\\int_0^1 \\ln u\\,du', expr: 'integral(log(u), u, 0, 1)', mistake: 'back-substitution-wrong', why: 'ln x becomes u itself, not ln u.' },
        ],
        correct: 0,
        explanation: 'The integrand, the differential, and the limits are all in terms of $u$ now.',
        result: { latex: '= \\int_0^1 u\\,du' },
        check: { kind: 'value', expected: 'integral(log(x)/x, x, 1, e)' },
      },
      {
        prompt: 'Evaluate $\\int_0^1 u\\,du$.',
        options: [
          { latex: '\\frac{1}{2}', expr: '1/2' },
          {
            latex: '\\frac{e^2 - 1}{2}',
            expr: '(e^2 - 1)/2',
            mistake: 'bounds-not-converted',
            why: 'Evaluated u²/2 at the x-limits 1 and e instead of the u-limits 0 and 1.',
          },
          { latex: '1', expr: '1', mistake: 'power-rule-int-coefficient', why: '∫u du = u²/2; the division by 2 was skipped.' },
          { latex: '-\\frac{1}{2}', expr: '-1/2', mistake: 'ftc-order-swapped', why: 'Computed F(0) − F(1) instead of F(1) − F(0).' },
          {
            latex: '0',
            expr: '0',
            mistake: 'differentiated-instead',
            why: 'Used the derivative of u (the constant 1) instead of the antiderivative u²/2: 1 − 1 = 0.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{u^2}{2}\\Big|_0^1 = \\frac{1}{2} - 0$.',
        result: { latex: '= \\frac{u^2}{2}\\Big|_0^1 = \\frac{1}{2}' },
        check: { kind: 'value', expected: '1/2' },
      },
    ],
    final: {
      latex: '\\frac{1}{2}',
      expr: '1/2',
      check: { kind: 'definite-integral', integrand: 'log(x)/x', lower: '1', upper: 'e' },
      recap: 'With $u = \\ln x$, $\\frac{dx}{x}$ becomes $du$ and the limits become $\\ln 1 = 0$ and $\\ln e = 1$, leaving $\\int_0^1 u\\,du$.',
    },
  },

  // ───────────────────────── ad-s-04: ∫ x³/√(9 + x⁴) dx ─────────────────────────
  {
    id: 'ad-s-04',
    topic: 'antiderivatives',
    title: 'A root with its inner derivative outside',
    difficulty: 1,
    statement: { text: 'Find', latex: '\\int \\frac{x^3}{\\sqrt{9+x^4}}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution turns the integral into a constant times $\\int u^{-1/2}\\,du$?',
        options: [
          { text: '$u = 9 + x^4$' },
          { text: '$u = x^3$', mistake: 'u-choice-wrong', why: 'du = 3x² dx is not in the integrand.' },
          { text: '$u = x^2$', mistake: 'u-choice-wrong', why: 'du = 2x dx leaves ∫u/(2√(9 + u²))du, which is not a power of u.' },
          {
            text: 'Trigonometric substitution $x^2 = 3\\tan\\theta$',
            mistake: 'trig-sub-when-usub',
            why: 'The derivative 4x³ of the radicand is already in the numerator, so a plain u-substitution works.',
          },
          {
            text: 'Split into $\\int x^3\\,dx \\cdot \\int\\frac{dx}{\\sqrt{9+x^4}}$',
            mistake: 'product-rule-integral',
            why: 'There is no product rule for integrals.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(9 + x^4) = 4x^3$, so $x^3\\,dx$ is $\\frac{1}{4}du$ and the root becomes $u^{1/2}$.',
        result: { latex: 'u = 9 + x^4' },
      },
      {
        prompt: 'What is $du$?',
        options: [
          { latex: 'du = 4x^3\\,dx', expr: '4*x^3*dx' },
          { latex: 'du = x^3\\,dx', expr: 'x^3*dx', mistake: 'du-constant-wrong', why: 'd/dx(x⁴) = 4x³; the factor 4 was dropped.' },
          { latex: 'du = 4x^4\\,dx', expr: '4*x^4*dx', mistake: 'power-rule-exponent', why: 'Differentiating x⁴ lowers the exponent to 3.' },
          {
            latex: 'du = \\left(9x + \\frac{x^5}{5}\\right)dx',
            expr: '(9*x + x^5/5)*dx',
            mistake: 'integrated-instead',
            why: 'du uses the derivative of u, not an antiderivative.',
          },
          { latex: 'du = 4x^3', expr: '4*x^3', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(9 + x^4) = 4x^3$, so $du = 4x^3\\,dx$.',
        result: { latex: 'du = 4x^3\\,dx \\;\\Rightarrow\\; x^3\\,dx = \\frac{1}{4}\\,du' },
        check: { kind: 'value', expected: '4*x^3*dx' },
      },
      {
        prompt: 'Now $\\int\\frac{x^3}{\\sqrt{9+x^4}}\\,dx = \\frac{1}{4}\\int u^{-1/2}\\,du$. Integrate.',
        variable: 'u',
        options: [
          { latex: '\\frac{1}{2}u^{1/2} + C', expr: 'u^(1/2)/2' },
          {
            latex: '\\frac{1}{8}u^{1/2} + C',
            expr: 'u^(1/2)/8',
            mistake: 'power-rule-int-coefficient',
            why: 'Multiplied by the new exponent 1/2 instead of dividing by it: ¼ · ½.',
          },
          {
            latex: '\\frac{1}{4}u^{1/2} + C',
            expr: 'u^(1/2)/4',
            mistake: 'power-rule-int-coefficient',
            why: 'The exponent was raised, but the division by the new exponent 1/2 was skipped.',
          },
          {
            latex: '-\\frac{1}{8}u^{-3/2} + C',
            expr: '-u^(-3/2)/8',
            mistake: 'differentiated-instead',
            why: 'This is the derivative of ¼u^{−1/2}; integrating raises the exponent.',
          },
          { latex: '\\frac{1}{4}\\ln|u| + C', expr: 'log(abs(u))/4', mistake: 'ln-misapplied', why: 'Only u^{−1} integrates to ln|u|.' },
        ],
        correct: 0,
        explanation: '$\\frac{1}{4}\\cdot\\frac{u^{1/2}}{1/2} = \\frac{1}{2}u^{1/2}$.',
        result: { latex: '= \\frac{1}{4}\\cdot 2u^{1/2} + C = \\frac{1}{2}u^{1/2} + C' },
        check: { kind: 'antiderivative', integrand: 'u^(-1/2)/4' },
      },
      {
        prompt: 'Return to $x$.',
        options: [
          { latex: '\\frac{1}{2}\\sqrt{9+x^4} + C', expr: 'sqrt(9+x^4)/2' },
          { latex: '\\frac{1}{2}\\sqrt{u} + C', expr: 'sqrt(u)/2', mistake: 'not-back-substituted', why: 'The answer must be in x: replace u by 9 + x⁴.' },
          {
            latex: '\\frac{x^3}{2}\\sqrt{9+x^4} + C',
            expr: 'x^3*sqrt(9+x^4)/2',
            mistake: 'leftover-x-in-u-integral',
            why: 'x³ dx became du/4; the x³ must not reappear.',
          },
          {
            latex: '\\frac{1}{2}\\left(3 + x^2\\right) + C',
            expr: '(3 + x^2)/2',
            mistake: 'sqrt-of-sum-split',
            why: '√(9 + x⁴) is not 3 + x²; a square root does not split over a sum.',
          },
          { latex: '2\\sqrt{9+x^4} + C', expr: '2*sqrt(9+x^4)', mistake: 'du-constant-wrong', why: 'Used x³ dx = du instead of du/4, giving 2√u.' },
        ],
        correct: 0,
        explanation: 'Replace $u$ by $9 + x^4$: $\\frac{1}{2}u^{1/2} = \\frac{1}{2}\\sqrt{9+x^4}$.',
        result: { latex: '= \\frac{1}{2}\\sqrt{9+x^4} + C' },
        check: { kind: 'antiderivative', integrand: 'x^3/sqrt(9+x^4)' },
      },
    ],
    final: {
      latex: '\\frac{1}{2}\\sqrt{9+x^4} + C',
      expr: 'sqrt(9+x^4)/2',
      check: { kind: 'antiderivative', integrand: 'x^3/sqrt(9+x^4)' },
      recap: 'Since $x^3$ is $\\frac{1}{4}$ of the derivative of $9 + x^4$, $u = 9 + x^4$ gives $\\frac{1}{4}\\int u^{-1/2}\\,du = \\frac{1}{2}\\sqrt{u}$.',
    },
  },

  // ───────────────────────── ad-s-05: ∫ −4eˣ(6eˣ + 6)⁵ dx ─────────────────────────
  {
    id: 'ad-s-05',
    topic: 'antiderivatives',
    title: 'An exponential inside a power',
    difficulty: 1,
    statement: { text: 'Find', latex: '\\int -4e^x\\left(6e^x+6\\right)^5\\,dx' },
    domain: [-1.5, 0.5],
    steps: [
      {
        prompt: 'With $u = 6e^x + 6$, what is $du$?',
        options: [
          { latex: 'du = 6e^x\\,dx', expr: '6*exp(x)*dx' },
          { latex: 'du = (6e^x + 6)\\,dx', expr: '(6*exp(x) + 6)*dx', mistake: 'constant-derivative', why: 'The derivative of the constant 6 is 0.' },
          { latex: 'du = e^x\\,dx', expr: 'exp(x)*dx', mistake: 'du-constant-wrong', why: 'The coefficient stays: d/dx(6eˣ) = 6eˣ.' },
          {
            latex: 'du = 6xe^{x-1}\\,dx',
            expr: '6*x*exp(x-1)*dx',
            mistake: 'exponential-as-power',
            why: 'eˣ is its own derivative; the power rule does not apply to an exponential.',
          },
          { latex: 'du = 6e^x', expr: '6*exp(x)', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(6e^x + 6) = 6e^x$, so $du = 6e^x\\,dx$.',
        result: { latex: 'u = 6e^x + 6,\\quad du = 6e^x\\,dx \\;\\Rightarrow\\; e^x\\,dx = \\frac{1}{6}\\,du' },
        check: { kind: 'value', expected: '6*exp(x)*dx' },
      },
      {
        prompt: 'Rewrite the integral in terms of $u$.',
        options: [
          { latex: '-\\frac{2}{3}\\int u^5\\,du', expr: 'indefinite(-2*u^5/3, u)' },
          {
            latex: '-4\\int u^5\\,du',
            expr: 'indefinite(-4*u^5, u)',
            mistake: 'du-constant-wrong',
            why: 'eˣ dx = du/6, so −4eˣ dx = −(4/6)du; the 1/6 was dropped.',
          },
          {
            latex: '-24\\int u^5\\,du',
            expr: 'indefinite(-24*u^5, u)',
            mistake: 'du-constant-wrong',
            why: 'Multiplied by 6 instead of dividing: −4eˣ dx = −(2/3)du.',
          },
          {
            latex: '-\\frac{2}{3}\\int e^x u^5\\,du',
            expr: 'indefinite(-2*exp(x)*u^5/3, u)',
            mistake: 'leftover-x-in-u-integral',
            why: 'eˣ dx was absorbed into du/6; no eˣ may remain inside the u-integral.',
          },
          {
            latex: '\\frac{2}{3}\\int u^5\\,du',
            expr: 'indefinite(2*u^5/3, u)',
            mistake: 'sign-error',
            why: 'The factor −4 keeps its minus sign: −4/6 = −2/3.',
          },
        ],
        correct: 0,
        explanation: '$-4e^x\\,dx = -\\frac{4}{6}\\,du = -\\frac{2}{3}\\,du$ and $(6e^x + 6)^5 = u^5$.',
        result: { latex: '= -\\frac{4}{6}\\int u^5\\,du = -\\frac{2}{3}\\int u^5\\,du' },
        check: { kind: 'identity', lhs: '-2*u^5/3' },
      },
      {
        prompt: 'Integrate and return to $x$.',
        options: [
          { latex: '-\\frac{1}{9}\\left(6e^x+6\\right)^6 + C', expr: '-(6*exp(x)+6)^6/9' },
          {
            latex: '-\\frac{2}{3}\\left(6e^x+6\\right)^6 + C',
            expr: '-2*(6*exp(x)+6)^6/3',
            mistake: 'power-rule-int-coefficient',
            why: '∫u⁵du = u⁶/6; the division by 6 was skipped.',
          },
          {
            latex: '-\\frac{2}{15}\\left(6e^x+6\\right)^6 + C',
            expr: '-2*(6*exp(x)+6)^6/15',
            mistake: 'power-rule-int-coefficient',
            why: 'Divided by the old exponent 5 instead of the new exponent 6.',
          },
          {
            latex: '-\\frac{10}{3}\\left(6e^x+6\\right)^4 + C',
            expr: '-10*(6*exp(x)+6)^4/3',
            mistake: 'differentiated-instead',
            why: 'Differentiated u⁵ (giving 5u⁴) instead of integrating it.',
          },
          { latex: '-\\frac{1}{9}u^6 + C', expr: '-u^6/9', mistake: 'not-back-substituted', why: 'The answer must be in x: replace u by 6eˣ + 6.' },
          {
            latex: '-\\frac{1}{9}\\left(6e^x\\right)^6 + C',
            expr: '-(6*exp(x))^6/9',
            mistake: 'back-substitution-wrong',
            why: 'u is 6eˣ + 6; the + 6 was lost when substituting back.',
          },
        ],
        correct: 0,
        explanation: '$-\\frac{2}{3}\\cdot\\frac{u^6}{6} = -\\frac{1}{9}u^6$ with $u = 6e^x + 6$.',
        result: { latex: '= -\\frac{2}{3}\\cdot\\frac{u^6}{6} + C = -\\frac{1}{9}\\left(6e^x+6\\right)^6 + C' },
        check: { kind: 'antiderivative', integrand: '-4*exp(x)*(6*exp(x)+6)^5' },
      },
    ],
    final: {
      latex: '-\\frac{1}{9}\\left(6e^x+6\\right)^6 + C',
      expr: '-(6*exp(x)+6)^6/9',
      check: { kind: 'antiderivative', integrand: '-4*exp(x)*(6*exp(x)+6)^5' },
      recap: 'The outside factor $-4e^x$ is $-\\frac{2}{3}$ times the derivative $6e^x$ of the inner function, so $u = 6e^x + 6$ reduces the integral to $-\\frac{2}{3}\\int u^5\\,du$.',
    },
  },

  // ───────────────────────── ad-s-06: ∫ 1/√(1 − 16x²) dx ─────────────────────────
  {
    id: 'ad-s-06',
    topic: 'antiderivatives',
    title: 'Matching the arcsine form',
    difficulty: 1,
    statement: { text: 'Find', latex: '\\int \\frac{1}{\\sqrt{1-16x^2}}\\,dx' },
    domain: [-0.2, 0.2],
    steps: [
      {
        prompt: 'Which substitution matches a basic antiderivative formula?',
        options: [
          { text: '$u = 4x$, to match $\\int\\frac{du}{\\sqrt{1-u^2}}$' },
          {
            text: '$u = 16x$, to match $\\int\\frac{du}{\\sqrt{1-u^2}}$',
            mistake: 'u-choice-wrong',
            why: '(16x)² = 256x², not 16x²; since (4x)² = 16x², the right choice is u = 4x.',
          },
          {
            text: '$u = 4x$, to match $\\int\\frac{du}{1+u^2}$',
            mistake: 'inverse-trig-confused',
            why: 'The radical √(1 − u²) signals the arcsine formula; 1/(1 + u²) is the arctangent form.',
          },
          {
            text: '$u = 1 - 16x^2$, to use the power rule',
            mistake: 'u-choice-wrong',
            why: 'du = −32x dx, but there is no x in the numerator.',
          },
          {
            text: '$u = \\sqrt{1-16x^2}$',
            mistake: 'u-choice-wrong',
            why: 'du = −16x/√(1 − 16x²) dx needs a factor x in the numerator, which is missing.',
          },
        ],
        correct: 0,
        explanation: 'Since $16x^2 = (4x)^2$, $u = 4x$ turns the radicand into $1 - u^2$.',
        result: { latex: 'u = 4x,\\quad 16x^2 = u^2' },
      },
      {
        prompt: 'With $u = 4x$, what is $du$?',
        options: [
          { latex: 'du = 4\\,dx', expr: '4*dx' },
          {
            latex: 'du = 16\\,dx',
            expr: '16*dx',
            mistake: 'du-constant-wrong',
            why: 'u = 4x, so du = 4 dx; 16 is the coefficient of x², not the derivative of u.',
          },
          { latex: 'du = 32x\\,dx', expr: '32*x*dx', mistake: 'du-derivative-wrong', why: 'That is d(16x²); with u = 4x, du = 4 dx.' },
          { latex: 'du = dx', expr: 'dx', mistake: 'inner-constant-factor-missing', why: 'd/dx(4x) = 4; the factor 4 was lost.' },
          { latex: 'du = 4', expr: '4', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(4x) = 4$, so $du = 4\\,dx$ and $dx = \\frac{1}{4}\\,du$.',
        result: { latex: 'du = 4\\,dx \\;\\Rightarrow\\; dx = \\frac{1}{4}\\,du' },
        check: { kind: 'value', expected: '4*dx' },
      },
      {
        prompt: 'Rewrite the integral in terms of $u$.',
        options: [
          { latex: '\\frac{1}{4}\\int \\frac{1}{\\sqrt{1-u^2}}\\,du', expr: 'indefinite(1/(4*sqrt(1-u^2)), u)' },
          {
            latex: '4\\int \\frac{1}{\\sqrt{1-u^2}}\\,du',
            expr: 'indefinite(4/sqrt(1-u^2), u)',
            mistake: 'du-constant-wrong',
            why: 'dx = du/4, not 4 du.',
          },
          {
            latex: '\\int \\frac{1}{\\sqrt{1-u^2}}\\,du',
            expr: 'indefinite(1/sqrt(1-u^2), u)',
            mistake: 'inner-constant-factor-missing',
            why: 'dx = du/4; the factor 1/4 was dropped.',
          },
          {
            latex: '\\frac{1}{4}\\int \\frac{1}{\\sqrt{1-u}}\\,du',
            expr: 'indefinite(1/(4*sqrt(1-u)), u)',
            mistake: 'algebra-error',
            why: 'With u = 4x, 16x² = u², not u.',
          },
          {
            latex: '\\frac{1}{4}\\int \\frac{1}{\\sqrt{1-16u^2}}\\,du',
            expr: 'indefinite(1/(4*sqrt(1-16*u^2)), u)',
            mistake: 'coefficient-mishandled',
            why: '16x² = (4x)² = u²; the 16 is already absorbed into u and must not be kept.',
          },
        ],
        correct: 0,
        explanation: '$16x^2 = u^2$ and $dx = \\frac{1}{4}\\,du$.',
        result: { latex: '= \\frac{1}{4}\\int \\frac{du}{\\sqrt{1-u^2}}' },
        check: { kind: 'identity', lhs: '1/(4*sqrt(1-u^2))' },
      },
      {
        prompt: 'Integrate and return to $x$.',
        options: [
          { latex: '\\frac{1}{4}\\sin^{-1}(4x) + C', expr: 'asin(4*x)/4' },
          { latex: '\\sin^{-1}(4x) + C', expr: 'asin(4*x)', mistake: 'inner-constant-factor-missing', why: 'The factor 1/4 from dx = du/4 was lost.' },
          { latex: '4\\sin^{-1}(4x) + C', expr: '4*asin(4*x)', mistake: 'du-constant-wrong', why: 'Multiplied by 4 instead of dividing by 4.' },
          {
            latex: '\\frac{1}{16}\\sin^{-1}(4x) + C',
            expr: 'asin(4*x)/16',
            mistake: 'du-constant-wrong',
            why: 'Divided by 16, the coefficient of x², instead of by 4, the derivative of u = 4x.',
          },
          {
            latex: '\\frac{1}{4}\\tan^{-1}(4x) + C',
            expr: 'atan(4*x)/4',
            mistake: 'inverse-trig-confused',
            why: 'tan⁻¹ belongs to 1/(1 + u²); 1/√(1 − u²) integrates to sin⁻¹u.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{1}{4}\\int\\frac{du}{\\sqrt{1-u^2}} = \\frac{1}{4}\\sin^{-1}u + C$ with $u = 4x$.',
        result: { latex: '= \\frac{1}{4}\\sin^{-1}u + C = \\frac{1}{4}\\sin^{-1}(4x) + C' },
        check: { kind: 'antiderivative', integrand: '1/sqrt(1-16*x^2)' },
      },
    ],
    final: {
      latex: '\\frac{1}{4}\\sin^{-1}(4x) + C',
      expr: 'asin(4*x)/4',
      check: { kind: 'antiderivative', integrand: '1/sqrt(1-16*x^2)' },
      recap: 'Write $16x^2 = (4x)^2$ so that $u = 4x$ matches $\\int\\frac{du}{\\sqrt{1-u^2}} = \\sin^{-1}u$; $du = 4\\,dx$ contributes the factor $\\frac{1}{4}$.',
    },
  },

  // ───────────────────────── ad-s-07: ∫₄¹⁶ e^{−√x}/√(2x) dx ─────────────────────────
  {
    id: 'ad-s-07',
    topic: 'antiderivatives',
    title: 'Changing the limits with u = √x',
    difficulty: 2,
    statement: { text: 'Evaluate', latex: '\\int_4^{16} \\frac{e^{-\\sqrt{x}}}{\\sqrt{2x}}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution works directly?',
        options: [
          { text: '$u = \\sqrt{x}$' },
          { text: '$u = 2x$', mistake: 'u-choice-wrong', why: 'du = 2 dx only rescales; e^{−√(u/2)} and √u remain.' },
          { text: '$u = \\frac{1}{\\sqrt{2x}}$', mistake: 'u-choice-wrong', why: 'du = −(2x)^{−3/2} dx does not appear in the integrand.' },
          {
            text: 'Split into $\\int_4^{16} e^{-\\sqrt{x}}\\,dx \\cdot \\int_4^{16}\\frac{dx}{\\sqrt{2x}}$',
            mistake: 'product-rule-integral',
            why: 'There is no product rule for integrals.',
          },
          {
            text: 'Integration by parts with $u = e^{-\\sqrt{x}}$, $dv = \\frac{dx}{\\sqrt{2x}}$',
            mistake: 'ibp-when-usub',
            why: 'This gives an integral at least as hard; the integrand already has the form f(g(x))g′(x) with g(x) = √x.',
          },
        ],
        correct: 0,
        explanation: 'The inner function is $\\sqrt{x}$, and its derivative $\\frac{1}{2\\sqrt{x}}$ appears up to a constant, since $\\sqrt{2x} = \\sqrt{2}\\sqrt{x}$.',
        result: { latex: 'u = \\sqrt{x}' },
      },
      {
        prompt: 'What is $du$?',
        options: [
          { latex: 'du = \\frac{1}{2\\sqrt{x}}\\,dx', expr: 'dx/(2*sqrt(x))' },
          { latex: 'du = \\frac{1}{\\sqrt{x}}\\,dx', expr: 'dx/sqrt(x)', mistake: 'du-constant-wrong', why: 'd/dx x^{1/2} = ½x^{−1/2}; the 1/2 was dropped.' },
          {
            latex: 'du = \\frac{2}{3}x^{3/2}\\,dx',
            expr: '2/3*x^(3/2)*dx',
            mistake: 'integrated-instead',
            why: 'That is an antiderivative of √x; du uses its derivative.',
          },
          {
            latex: 'du = \\frac{1}{2}x^{-3/2}\\,dx',
            expr: 'x^(-3/2)/2*dx',
            mistake: 'power-rule-exponent',
            why: 'The new exponent is ½ − 1 = −½, not −3/2.',
          },
          { latex: 'du = \\frac{1}{2\\sqrt{x}}', expr: '1/(2*sqrt(x))', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}x^{1/2} = \\frac{1}{2}x^{-1/2}$, so $du = \\frac{dx}{2\\sqrt{x}}$ and $\\frac{dx}{\\sqrt{x}} = 2\\,du$.',
        result: { latex: 'du = \\frac{dx}{2\\sqrt{x}} \\;\\Rightarrow\\; \\frac{dx}{\\sqrt{x}} = 2\\,du' },
        check: { kind: 'value', expected: 'dx/(2*sqrt(x))' },
      },
      {
        prompt: 'What are the new limits of integration?',
        options: [
          { latex: 'u(4) = 2,\\ u(16) = 4', expr: '[2, 4]' },
          {
            latex: 'u(4) = 4,\\ u(16) = 16',
            expr: '[4, 16]',
            mistake: 'bounds-not-converted',
            why: 'These are the x-limits; they must be pushed through u = √x.',
          },
          {
            latex: 'u(4) = 16,\\ u(16) = 256',
            expr: '[16, 256]',
            mistake: 'algebra-error',
            why: 'u = √x takes square roots of the limits; these values are squares.',
          },
          {
            latex: 'u(4) = 2\\sqrt{2},\\ u(16) = 4\\sqrt{2}',
            expr: '[2*sqrt(2), 4*sqrt(2)]',
            mistake: 'back-substitution-wrong',
            why: 'These are values of √(2x); the substitution is u = √x.',
          },
          { latex: 'u(4) = -2,\\ u(16) = -4', expr: '[-2, -4]', mistake: 'sign-error', why: 'u = √x is positive: √4 = 2 and √16 = 4.' },
        ],
        correct: 0,
        explanation: 'Plug the x-limits into $u = \\sqrt{x}$: $\\sqrt{4} = 2$ and $\\sqrt{16} = 4$.',
        result: { latex: 'x = 4 \\Rightarrow u = 2,\\quad x = 16 \\Rightarrow u = 4' },
        check: { kind: 'value', expected: '[2, 4]' },
      },
      {
        prompt: 'Rewrite the integral entirely in $u$ (use $\\sqrt{2x} = \\sqrt{2}\\,\\sqrt{x}$).',
        options: [
          { latex: '\\sqrt{2}\\int_2^4 e^{-u}\\,du', expr: 'sqrt(2)*integral(exp(-u), u, 2, 4)' },
          {
            latex: '\\frac{1}{\\sqrt{2}}\\int_2^4 e^{-u}\\,du',
            expr: 'integral(exp(-u), u, 2, 4)/sqrt(2)',
            mistake: 'du-constant-wrong',
            why: 'dx/√x = 2 du; the factor 2 was dropped (2/√2 = √2).',
          },
          {
            latex: '\\sqrt{2}\\int_4^{16} e^{-u}\\,du',
            expr: 'sqrt(2)*integral(exp(-u), u, 4, 16)',
            mistake: 'bounds-not-converted',
            why: 'The limits were left as x-values.',
          },
          {
            latex: '2\\int_2^4 e^{-u}\\,du',
            expr: '2*integral(exp(-u), u, 2, 4)',
            mistake: 'algebra-error',
            why: '√(2x) = √2 · √x; the factor 1/√2 was dropped.',
          },
          {
            latex: '\\sqrt{2}\\int_2^4 \\frac{e^{-u}}{\\sqrt{x}}\\,du',
            expr: 'sqrt(2)*integral(exp(-u)/sqrt(x), u, 2, 4)',
            mistake: 'leftover-x-in-u-integral',
            why: 'The 1/√x is part of dx/√x = 2 du; no x may remain.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{e^{-\\sqrt{x}}}{\\sqrt{2}\\sqrt{x}}\\,dx = \\frac{e^{-u}}{\\sqrt{2}}\\cdot 2\\,du = \\sqrt{2}\\,e^{-u}\\,du$, with limits 2 and 4.',
        result: { latex: '= \\frac{1}{\\sqrt{2}}\\int_2^4 e^{-u}\\cdot 2\\,du = \\sqrt{2}\\int_2^4 e^{-u}\\,du' },
        check: { kind: 'value', expected: 'integral(exp(-sqrt(x))/sqrt(2*x), x, 4, 16)' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '\\sqrt{2}\\left(e^{-2} - e^{-4}\\right)', expr: 'sqrt(2)*(exp(-2) - exp(-4))' },
          {
            latex: '\\sqrt{2}\\left(e^{-4} - e^{-2}\\right)',
            expr: 'sqrt(2)*(exp(-4) - exp(-2))',
            mistake: 'inner-constant-factor-missing',
            why: '∫e^{−u}du = −e^{−u}; the factor 1/(−1) from the inner −u was dropped.',
          },
          {
            latex: '\\sqrt{2}\\left(e^{-4} - e^{-16}\\right)',
            expr: 'sqrt(2)*(exp(-4) - exp(-16))',
            mistake: 'bounds-not-converted',
            why: 'Evaluated −√2e^{−u} at the x-limits 4 and 16.',
          },
          {
            latex: '\\sqrt{2}\\left(e^{-\\sqrt{2}} - e^{-2}\\right)',
            expr: 'sqrt(2)*(exp(-sqrt(2)) - exp(-2))',
            mistake: 'mixed-limits-variable',
            why: 'The u-limits 2 and 4 were plugged into −√2e^{−√x}, an x-expression.',
          },
          {
            latex: '-\\sqrt{2}\\,e^{-4}',
            expr: '-sqrt(2)*exp(-4)',
            mistake: 'ftc-not-subtracted',
            why: 'Only F(4) = −√2e^{−4} was computed; F(2) = −√2e^{−2} must be subtracted.',
          },
        ],
        correct: 0,
        explanation: '$-\\sqrt{2}\\,e^{-u}\\Big|_2^4 = -\\sqrt{2}\\,e^{-4} + \\sqrt{2}\\,e^{-2}$.',
        result: { latex: '= -\\sqrt{2}\\,e^{-u}\\Big|_2^4 = \\sqrt{2}\\left(e^{-2} - e^{-4}\\right)' },
        check: { kind: 'value', expected: 'sqrt(2)*(exp(-2) - exp(-4))' },
      },
    ],
    final: {
      latex: '\\sqrt{2}\\left(e^{-2} - e^{-4}\\right)',
      expr: 'sqrt(2)*(exp(-2) - exp(-4))',
      check: { kind: 'definite-integral', integrand: 'exp(-sqrt(x))/sqrt(2*x)', lower: '4', upper: '16' },
      recap: 'With $u = \\sqrt{x}$, $\\frac{dx}{\\sqrt{x}} = 2\\,du$ and the limits become $\\sqrt{4} = 2$ and $\\sqrt{16} = 4$; once in $u$, evaluate in $u$ without returning to $x$.',
    },
  },

  // ───────────────────────── ad-s-08: ∫₀^{2π} sin x cos x dx ─────────────────────────
  {
    id: 'ad-s-08',
    topic: 'antiderivatives',
    title: 'When the new limits coincide',
    difficulty: 1,
    statement: { text: 'Evaluate', latex: '\\int_0^{2\\pi} \\sin x\\cos x\\,dx' },
    steps: [
      {
        prompt: 'We take $u = \\sin x$. What is $du$?',
        options: [
          { latex: 'du = \\cos x\\,dx', expr: 'cos(x)*dx' },
          {
            latex: 'du = -\\cos x\\,dx',
            expr: '-cos(x)*dx',
            mistake: 'sign-error-derivative',
            why: 'd/dx sin x = +cos x; the minus sign belongs to d/dx cos x = −sin x.',
          },
          { latex: 'du = -\\sin x\\,dx', expr: '-sin(x)*dx', mistake: 'trig-derivative-swapped', why: 'That is d(cos x); the derivative of sin x is cos x.' },
          { latex: 'du = \\sin x\\,dx', expr: 'sin(x)*dx', mistake: 'trig-derivative-swapped', why: 'sin x is not its own derivative; d/dx sin x = cos x.' },
          { latex: 'du = \\cos x', expr: 'cos(x)', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}\\sin x = \\cos x$, so $du = \\cos x\\,dx$.',
        result: { latex: 'u = \\sin x,\\quad du = \\cos x\\,dx' },
        check: { kind: 'value', expected: 'cos(x)*dx' },
      },
      {
        prompt: 'What are the new limits of integration?',
        options: [
          { latex: 'u(0) = 0,\\ u(2\\pi) = 0', expr: '[0, 0]' },
          {
            latex: 'u(0) = 0,\\ u(2\\pi) = 2\\pi',
            expr: '[0, 2*pi]',
            mistake: 'bounds-not-converted',
            why: 'These are the x-limits; they must be pushed through u = sin x.',
          },
          {
            latex: 'u(0) = 1,\\ u(2\\pi) = 1',
            expr: '[1, 1]',
            mistake: 'back-substitution-wrong',
            why: 'Those are values of cos x; the substitution is u = sin x.',
          },
          { latex: 'u(0) = 0,\\ u(2\\pi) = 1', expr: '[0, 1]', mistake: 'arithmetic-error', why: 'sin(2π) = 0 (a full turn); 1 is sin(π/2).' },
          { latex: 'u(0) = 0,\\ u(2\\pi) = -1', expr: '[0, -1]', mistake: 'arithmetic-error', why: 'sin(2π) = 0; −1 is sin(3π/2).' },
        ],
        correct: 0,
        explanation: '$\\sin 0 = 0$ and $\\sin 2\\pi = 0$: both limits become $u = 0$.',
        result: { latex: 'x = 0 \\Rightarrow u = 0,\\quad x = 2\\pi \\Rightarrow u = 0' },
        check: { kind: 'value', expected: '[0, 0]' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: '0', expr: '0' },
          {
            latex: '2\\pi^2',
            expr: '2*pi^2',
            mistake: 'bounds-not-converted',
            why: 'Evaluated u²/2 at the x-limits 0 and 2π; the u-limits are both 0.',
          },
          {
            latex: '2',
            expr: '2',
            mistake: 'signed-area-confusion',
            why: '2 is the total area between the curve and the x-axis; in the integral the parts below the axis cancel the parts above.',
          },
          {
            latex: '\\frac{1}{2}',
            expr: '1/2',
            mistake: 'arithmetic-error',
            why: 'Used sin(2π) = 1, giving u²/2 from 0 to 1; in fact both u-limits are 0.',
          },
          {
            latex: '-2\\pi^2',
            expr: '-2*pi^2',
            mistake: 'bounds-not-converted',
            why: 'This is −u²/2 (from u = cos x) evaluated at the x-limits 0 and 2π; converted, those limits would both be 1.',
          },
        ],
        correct: 0,
        explanation: 'An integral whose limits are equal is 0: $\\int_0^0 u\\,du = 0$.',
        result: { latex: '= \\int_0^0 u\\,du = 0' },
        check: { kind: 'value', expected: '0' },
      },
    ],
    final: {
      latex: '0',
      expr: '0',
      check: { kind: 'definite-integral', integrand: 'sin(x)*cos(x)', lower: '0', upper: '2*pi' },
      recap: 'Converting the limits sends both $x = 0$ and $x = 2\\pi$ to $u = 0$, and $\\int_a^a f = 0$; keeping the x-limits would give the wrong value $2\\pi^2$.',
    },
  },

  // ───────────────────────── ad-s-09: ∫₀¹ e^{2t}/(eᵗ + 1) dt ─────────────────────────
  {
    id: 'ad-s-09',
    topic: 'antiderivatives',
    title: 'Substitution with a leftover factor',
    difficulty: 2,
    variable: 't',
    statement: { text: 'Evaluate', latex: '\\int_0^1 \\frac{e^{2t}}{e^t+1}\\,dt' },
    steps: [
      {
        prompt: 'Which first step works directly?',
        options: [
          { text: '$u = e^t + 1$, writing $e^{2t} = e^t\\cdot e^t$' },
          {
            text: '$u = e^{2t}$',
            mistake: 'u-choice-wrong',
            why: 'du = 2e^{2t} dt, but then eᵗ + 1 = √u + 1 and dt = du/(2u); the integral is not simpler.',
          },
          { text: '$u = 2t$', mistake: 'u-choice-wrong', why: 'This only rescales t; the exponentials stay as they are.' },
          {
            text: 'Split the fraction: $\\frac{e^{2t}}{e^t} + \\frac{e^{2t}}{1}$',
            mistake: 'algebra-error',
            why: 'A fraction does not split over a sum in the denominator: a/(b + c) ≠ a/b + a/c.',
          },
          {
            text: 'Integrate top and bottom separately: $\\frac{\\int e^{2t}\\,dt}{\\int (e^t+1)\\,dt}$',
            mistake: 'product-rule-integral',
            why: 'Integrals do not split over quotients.',
          },
        ],
        correct: 0,
        explanation: 'With $u = e^t + 1$, one factor $e^t\\,dt$ becomes $du$ and the other $e^t$ becomes $u - 1$.',
        result: { latex: 'u = e^t + 1,\\quad du = e^t\\,dt,\\quad e^t = u - 1' },
      },
      {
        prompt: 'In terms of $u$, the integrand $\\frac{e^t\\cdot e^t}{e^t+1}\\,dt$ becomes',
        options: [
          { latex: '\\frac{u-1}{u}\\,du', expr: '(u-1)/u*du' },
          { latex: '\\frac{u+1}{u}\\,du', expr: '(u+1)/u*du', mistake: 'sign-error', why: 'From u = eᵗ + 1, eᵗ = u − 1 (not u + 1).' },
          {
            latex: '\\frac{(u-1)^2}{u}\\,du',
            expr: '(u-1)^2/u*du',
            mistake: 'exponent-arithmetic',
            why: 'Only one factor eᵗ becomes u − 1; the other eᵗ dt is du.',
          },
          {
            latex: '\\frac{e^t}{u}\\,du',
            expr: 'exp(t)/u*du',
            mistake: 'leftover-x-in-u-integral',
            why: 'The remaining eᵗ must be written in u: eᵗ = u − 1.',
          },
          {
            latex: '\\frac{e^{2t}}{u}\\,du',
            expr: 'exp(2*t)/u*du',
            mistake: 'du-derivative-wrong',
            why: 'Treated du as dt; since du = eᵗ dt, one factor eᵗ is used up by du.',
          },
        ],
        correct: 0,
        explanation: '$e^t\\,dt = du$, the other $e^t = u - 1$, and the denominator is $u$.',
        result: { latex: '\\frac{e^t\\cdot e^t\\,dt}{e^t+1} = \\frac{(u-1)\\,du}{u}' },
        check: { kind: 'value', expected: '(u-1)/u*du' },
      },
      {
        prompt: 'What are the new limits of integration?',
        options: [
          { latex: 'u(0) = 2,\\ u(1) = e+1', expr: '[2, e+1]' },
          {
            latex: 'u(0) = 0,\\ u(1) = 1',
            expr: '[0, 1]',
            mistake: 'bounds-not-converted',
            why: 'These are the t-limits; they must be pushed through u = eᵗ + 1.',
          },
          { latex: 'u(0) = 1,\\ u(1) = e+1', expr: '[1, e+1]', mistake: 'arithmetic-error', why: 'e⁰ = 1, so u(0) = 1 + 1 = 2.' },
          {
            latex: 'u(0) = 2,\\ u(1) = e^2+1',
            expr: '[2, e^2+1]',
            mistake: 'back-substitution-wrong',
            why: 'u = eᵗ + 1, not e^{2t} + 1.',
          },
          { latex: 'u(0) = 2,\\ u(1) = e', expr: '[2, e]', mistake: 'algebra-error', why: 'u(1) = e¹ + 1 = e + 1; the +1 was dropped.' },
        ],
        correct: 0,
        explanation: '$u(0) = e^0 + 1 = 2$ and $u(1) = e + 1$.',
        result: { latex: 't = 0 \\Rightarrow u = 2,\\quad t = 1 \\Rightarrow u = e + 1' },
        check: { kind: 'value', expected: '[2, e+1]' },
      },
      {
        prompt: 'Since $\\frac{u-1}{u} = 1 - \\frac{1}{u}$, which function is an antiderivative in $u$?',
        variable: 'u',
        domain: { u: [2, 3.7] },
        options: [
          { latex: 'u - \\ln|u|', expr: 'u - log(abs(u))' },
          { latex: 'u + \\ln|u|', expr: 'u + log(abs(u))', mistake: 'sign-error', why: '1 − 1/u integrates to u − ln|u|; the minus sign was lost.' },
          {
            latex: '\\left(\\frac{u^2}{2} - u\\right)\\ln|u|',
            expr: '(u^2/2 - u)*log(abs(u))',
            mistake: 'product-rule-integral',
            why: 'Integrated u − 1 and 1/u separately and multiplied; there is no product rule for integrals.',
          },
          { latex: '\\frac{1}{u^2}', expr: '1/u^2', mistake: 'differentiated-instead', why: 'This is the derivative of 1 − 1/u, not an antiderivative.' },
          {
            latex: '1 - \\ln|u|',
            expr: '1 - log(abs(u))',
            mistake: 'power-rule-int-exponent',
            why: '∫1 du = u, not 1: the power u⁰ must be raised to u¹.',
          },
        ],
        correct: 0,
        explanation: '$\\int\\left(1 - \\frac{1}{u}\\right)du = u - \\ln|u|$.',
        result: { latex: '\\int_2^{e+1}\\left(1 - \\frac{1}{u}\\right)du = \\Big[u - \\ln|u|\\Big]_2^{e+1}' },
        check: { kind: 'antiderivative', integrand: '(u-1)/u' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: 'e - 1 + \\ln 2 - \\ln(e+1)', expr: 'e - 1 + log(2) - log(e+1)' },
          {
            latex: 'e - 1 - \\ln 2 + \\ln(e+1)',
            expr: 'e - 1 - log(2) + log(e+1)',
            mistake: 'sign-error',
            why: 'This comes from u + ln|u|; the antiderivative of −1/u is −ln|u|.',
          },
          {
            latex: 'e + 1 - \\ln(e+1)',
            expr: 'e + 1 - log(e+1)',
            mistake: 'ftc-not-subtracted',
            why: 'Only F(e + 1) was computed; F(2) = 2 − ln 2 must be subtracted.',
          },
          {
            latex: 'e - 1',
            expr: 'e - 1',
            mistake: 'algebra-error',
            why: '(u − 1)/u = 1 − 1/u; the −1/u term, which produces the logarithms, was dropped.',
          },
          {
            latex: 'e^{e+1} - e^2 + \\ln\\left(\\frac{e^2+1}{e^{e+1}+1}\\right)',
            expr: 'exp(e+1) - e^2 + log((e^2+1)/(exp(e+1)+1))',
            mistake: 'mixed-limits-variable',
            why: 'The u-limits 2 and e + 1 were plugged into eᵗ + 1 − ln(eᵗ + 1), an expression in t.',
          },
        ],
        correct: 0,
        explanation: '$\\big(e + 1 - \\ln(e+1)\\big) - (2 - \\ln 2) = e - 1 + \\ln 2 - \\ln(e+1)$.',
        result: { latex: '= \\big(e + 1 - \\ln(e+1)\\big) - (2 - \\ln 2) = e - 1 + \\ln 2 - \\ln(e+1)' },
        check: { kind: 'value', expected: 'e - 1 + log(2) - log(e+1)' },
      },
    ],
    final: {
      latex: 'e - 1 + \\ln 2 - \\ln(e+1)',
      expr: 'e - 1 + log(2) - log(e+1)',
      check: { kind: 'definite-integral', integrand: 'exp(2*t)/(exp(t)+1)', lower: '0', upper: '1' },
      recap: 'With $u = e^t + 1$, one factor $e^t\\,dt$ is $du$ and the other $e^t$ is $u - 1$; split $\\frac{u-1}{u} = 1 - \\frac{1}{u}$ and evaluate between $u = 2$ and $u = e + 1$.',
    },
  },

  // ───────────────────────── ad-s-10: ∫₋₈^{−6} 4x/(x + 4) dx ─────────────────────────
  {
    id: 'ad-s-10',
    topic: 'antiderivatives',
    title: 'Shift substitution on a negative interval',
    difficulty: 2,
    statement: { text: 'Evaluate', latex: '\\int_{-8}^{-6} \\frac{4x}{x+4}\\,dx' },
    steps: [
      {
        prompt: 'Which first step works directly?',
        options: [
          { text: '$u = x + 4$, so $x = u - 4$ and $du = dx$' },
          {
            text: '$u = 4x$',
            mistake: 'u-choice-wrong',
            why: 'du = 4 dx only rescales; the denominator becomes u/4 + 4, which is no simpler.',
          },
          { text: '$u = x^2 + 4x$', mistake: 'u-choice-wrong', why: 'du = (2x + 4)dx does not match the integrand.' },
          {
            text: 'Split the fraction: $\\frac{4x}{x} + \\frac{4x}{4}$',
            mistake: 'algebra-error',
            why: 'A fraction does not split over a sum in the denominator.',
          },
          {
            text: 'Answer directly: $4x\\ln|x+4|$',
            mistake: 'product-rule-integral',
            why: 'The numerator 4x is not a constant, so it cannot be pulled out of the integral.',
          },
        ],
        correct: 0,
        explanation: 'With $u = x + 4$ the denominator becomes $u$ and the numerator $4x = 4(u - 4)$ is a polynomial in $u$.',
        result: { latex: 'u = x + 4,\\quad x = u - 4,\\quad du = dx' },
      },
      {
        prompt: 'Rewrite $\\frac{4x}{x+4}\\,dx$ in terms of $u$.',
        options: [
          { latex: '\\frac{4(u-4)}{u}\\,du', expr: '4*(u-4)/u*du' },
          {
            latex: '\\frac{4x}{u}\\,du',
            expr: '4*x/u*du',
            mistake: 'leftover-x-in-u-integral',
            why: 'The numerator must also be written in u: 4x = 4(u − 4).',
          },
          { latex: '\\frac{4(u+4)}{u}\\,du', expr: '4*(u+4)/u*du', mistake: 'sign-error', why: 'u = x + 4 gives x = u − 4.' },
          { latex: '\\frac{4u}{u}\\,du', expr: '4*u/u*du', mistake: 'back-substitution-wrong', why: 'x is not u; since u = x + 4, x = u − 4.' },
          { latex: '\\frac{u-4}{u}\\,du', expr: '(u-4)/u*du', mistake: 'coefficient-mishandled', why: 'The factor 4 in 4x was lost.' },
        ],
        correct: 0,
        explanation: '$4x = 4(u - 4)$, $x + 4 = u$, and $dx = du$.',
        result: { latex: '\\frac{4x}{x+4}\\,dx = \\frac{4(u-4)}{u}\\,du = \\left(4 - \\frac{16}{u}\\right)du' },
        check: { kind: 'value', expected: '4*(u-4)/u*du' },
      },
      {
        prompt: 'What are the new limits of integration?',
        options: [
          { latex: 'u(-8) = -4,\\ u(-6) = -2', expr: '[-4, -2]' },
          {
            latex: 'u(-8) = -8,\\ u(-6) = -6',
            expr: '[-8, -6]',
            mistake: 'bounds-not-converted',
            why: 'These are the x-limits; they must be pushed through u = x + 4.',
          },
          { latex: 'u(-8) = -12,\\ u(-6) = -10', expr: '[-12, -10]', mistake: 'sign-error', why: 'u = x + 4: add 4 to each limit, do not subtract it.' },
          { latex: 'u(-8) = 4,\\ u(-6) = 2', expr: '[4, 2]', mistake: 'arithmetic-error', why: '−8 + 4 = −4 and −6 + 4 = −2; the signs were lost.' },
          {
            latex: 'u(-8) = -2,\\ u(-6) = -4',
            expr: '[-2, -4]',
            mistake: 'bounds-swapped',
            why: 'x = −8 is the lower limit, so u(−8) = −4 is the lower u-limit.',
          },
        ],
        correct: 0,
        explanation: '$u(-8) = -8 + 4 = -4$ and $u(-6) = -6 + 4 = -2$.',
        result: { latex: 'x = -8 \\Rightarrow u = -4,\\quad x = -6 \\Rightarrow u = -2' },
        check: { kind: 'value', expected: '[-4, -2]' },
      },
      {
        prompt: 'Which function is an antiderivative of $4 - \\frac{16}{u}$ on $[-4, -2]$?',
        variable: 'u',
        domain: { u: [-4, -2] },
        options: [
          { latex: '4u - 16\\ln|u|', expr: '4*u - 16*log(abs(u))' },
          {
            latex: '4u - 16\\ln u',
            expr: '4*u - 16*log(u)',
            mistake: 'abs-dropped',
            why: 'u is negative on [−4, −2], where ln u is undefined; the antiderivative of 1/u is ln|u|.',
          },
          { latex: '4u + 16\\ln|u|', expr: '4*u + 16*log(abs(u))', mistake: 'sign-error', why: '∫(−16/u)du = −16 ln|u|; the minus sign was lost.' },
          {
            latex: '4u - 4\\ln|u|',
            expr: '4*u - 4*log(abs(u))',
            mistake: 'coefficient-mishandled',
            why: '4(u − 4)/u = 4 − 16/u; the constant 16 became 4.',
          },
          {
            latex: '(4u - 16)\\ln|u|',
            expr: '(4*u - 16)*log(abs(u))',
            mistake: 'product-rule-integral',
            why: 'The non-constant numerator 4u − 16 was pulled out of the integral.',
          },
        ],
        correct: 0,
        explanation: '$\\int 4\\,du = 4u$ and $\\int\\frac{16}{u}\\,du = 16\\ln|u|$; the absolute value matters because $u < 0$ here.',
        result: { latex: '\\int_{-4}^{-2}\\left(4 - \\frac{16}{u}\\right)du = \\Big[4u - 16\\ln|u|\\Big]_{-4}^{-2}' },
        check: { kind: 'antiderivative', integrand: '4 - 16/u' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '8 + 16\\ln 2', expr: '8 + 16*log(2)' },
          {
            latex: '8 - 16\\ln 2',
            expr: '8 - 16*log(2)',
            mistake: 'sign-error',
            why: 'This comes from 4u + 16 ln|u|; the antiderivative of −16/u is −16 ln|u|.',
          },
          {
            latex: '-8 - 16\\ln 2',
            expr: '-8 - 16*log(2)',
            mistake: 'ftc-order-swapped',
            why: 'Computed F(−4) − F(−2) instead of F(−2) − F(−4).',
          },
          {
            latex: '8 + 16\\ln\\left(\\frac{4}{3}\\right)',
            expr: '8 + 16*log(4/3)',
            mistake: 'bounds-not-converted',
            why: 'Evaluated 4u − 16 ln|u| at the x-limits −8 and −6.',
          },
          {
            latex: '8 + 4\\ln 2',
            expr: '8 + 4*log(2)',
            mistake: 'coefficient-mishandled',
            why: 'This comes from 4u − 4 ln|u|; the logarithm term has coefficient 16.',
          },
        ],
        correct: 0,
        explanation: '$(-8 - 16\\ln 2) - (-16 - 16\\ln 4) = 8 - 16\\ln 2 + 32\\ln 2 = 8 + 16\\ln 2$.',
        result: { latex: '= (-8 - 16\\ln 2) - (-16 - 16\\ln 4) = 8 + 16\\ln 2' },
        check: { kind: 'value', expected: '8 + 16*log(2)' },
      },
    ],
    final: {
      latex: '8 + 16\\ln 2',
      expr: '8 + 16*log(2)',
      check: { kind: 'definite-integral', integrand: '4*x/(x+4)', lower: '-8', upper: '-6' },
      recap: 'With $u = x + 4$, write $x = u - 4$ so that $\\frac{4x}{x+4} = 4 - \\frac{16}{u}$; the $u$-interval $[-4, -2]$ is negative, so the absolute value in $\\ln|u|$ matters.',
    },
  },

  // ───────────────────────── ad-s-11: ∫₀^{√(π/2)} t cos(t²) sin(t²) dt ─────────────────────────
  {
    id: 'ad-s-11',
    topic: 'antiderivatives',
    title: 'A composite inside a composite',
    difficulty: 2,
    variable: 't',
    statement: { text: 'Evaluate', latex: '\\int_0^{\\sqrt{\\pi/2}} t\\cos(t^2)\\sin(t^2)\\,dt' },
    steps: [
      {
        prompt: 'Which single substitution turns the integrand into a constant times $u\\,du$?',
        options: [
          { text: '$u = \\sin(t^2)$' },
          { text: '$u = \\sin t$', mistake: 'u-choice-wrong', why: 'The inner function is t², not t; du = cos t dt does not appear.' },
          {
            text: '$u = t\\cos(t^2)$',
            mistake: 'u-choice-wrong',
            why: 'Its derivative, cos(t²) − 2t²sin(t²), is not in the integrand.',
          },
          {
            text: 'Split into $\\int t\\,dt\\cdot\\int\\cos(t^2)\\sin(t^2)\\,dt$',
            mistake: 'product-rule-integral',
            why: 'There is no product rule for integrals.',
          },
          {
            text: 'Integration by parts with $u = t$',
            mistake: 'ibp-when-usub',
            why: 'Then dv = cos(t²)sin(t²)dt has no elementary antiderivative on its own; the factor t is exactly what a substitution needs.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dt}\\sin(t^2) = 2t\\cos(t^2)$, which is (up to $\\frac{1}{2}$) the rest of the integrand.',
        result: { latex: 'u = \\sin(t^2)' },
      },
      {
        prompt: 'What is $du$?',
        options: [
          { latex: 'du = 2t\\cos(t^2)\\,dt', expr: '2*t*cos(t^2)*dt' },
          { latex: 'du = \\cos(t^2)\\,dt', expr: 'cos(t^2)*dt', mistake: 'chain-rule-missing', why: 'The chain rule adds the inner derivative 2t.' },
          {
            latex: 'du = -2t\\cos(t^2)\\,dt',
            expr: '-2*t*cos(t^2)*dt',
            mistake: 'sign-error-derivative',
            why: 'The derivative of sine is +cosine; there is no minus sign.',
          },
          { latex: 'du = t\\cos(t^2)\\,dt', expr: 't*cos(t^2)*dt', mistake: 'du-constant-wrong', why: 'd/dt(t²) = 2t; the factor 2 was dropped.' },
          { latex: 'du = 2t\\cos(t^2)', expr: '2*t*cos(t^2)', mistake: 'dx-not-replaced', why: 'du = u′(t) dt; the dt is part of du.' },
        ],
        correct: 0,
        explanation: 'Chain rule: $\\frac{d}{dt}\\sin(t^2) = \\cos(t^2)\\cdot 2t$.',
        result: { latex: 'du = 2t\\cos(t^2)\\,dt \\;\\Rightarrow\\; t\\cos(t^2)\\,dt = \\frac{1}{2}\\,du' },
        check: { kind: 'value', expected: '2*t*cos(t^2)*dt' },
      },
      {
        prompt: 'What are the new limits of integration?',
        options: [
          { latex: 'u(0) = 0,\\ u\\left(\\sqrt{\\pi/2}\\right) = 1', expr: '[0, 1]' },
          {
            latex: 'u(0) = 0,\\ u\\left(\\sqrt{\\pi/2}\\right) = \\sqrt{\\pi/2}',
            expr: '[0, sqrt(pi/2)]',
            mistake: 'bounds-not-converted',
            why: 'These are the t-limits; they must be pushed through u = sin(t²).',
          },
          {
            latex: 'u(0) = 0,\\ u\\left(\\sqrt{\\pi/2}\\right) = \\frac{\\pi}{2}',
            expr: '[0, pi/2]',
            mistake: 'back-substitution-wrong',
            why: 'π/2 is the value of the inner function t²; u = sin(t²) = sin(π/2) = 1.',
          },
          {
            latex: 'u(0) = 0,\\ u\\left(\\sqrt{\\pi/2}\\right) = \\sin\\sqrt{\\pi/2}',
            expr: '[0, sin(sqrt(pi/2))]',
            mistake: 'algebra-error',
            why: 'At t = √(π/2), t² = π/2; the square was forgotten.',
          },
          { latex: 'u(0) = 1,\\ u\\left(\\sqrt{\\pi/2}\\right) = 1', expr: '[1, 1]', mistake: 'arithmetic-error', why: 'sin 0 = 0, not 1.' },
        ],
        correct: 0,
        explanation: '$u(0) = \\sin 0 = 0$ and $u\\left(\\sqrt{\\pi/2}\\right) = \\sin\\frac{\\pi}{2} = 1$.',
        result: { latex: 't = 0 \\Rightarrow u = 0,\\quad t = \\sqrt{\\pi/2} \\Rightarrow u = \\sin\\frac{\\pi}{2} = 1' },
        check: { kind: 'value', expected: '[0, 1]' },
      },
      {
        prompt: 'Rewrite the integral entirely in $u$.',
        options: [
          { latex: '\\frac{1}{2}\\int_0^1 u\\,du', expr: 'integral(u, u, 0, 1)/2' },
          { latex: '2\\int_0^1 u\\,du', expr: '2*integral(u, u, 0, 1)', mistake: 'du-constant-wrong', why: 't cos(t²) dt = du/2, not 2 du.' },
          {
            latex: '\\int_0^1 u\\,du',
            expr: 'integral(u, u, 0, 1)',
            mistake: 'du-constant-wrong',
            why: 'du = 2t cos(t²) dt; the factor 1/2 was dropped.',
          },
          {
            latex: '\\frac{1}{2}\\int_0^{\\sqrt{\\pi/2}} u\\,du',
            expr: 'integral(u, u, 0, sqrt(pi/2))/2',
            mistake: 'bounds-not-converted',
            why: 'The limits were left as t-values.',
          },
          {
            latex: '\\frac{1}{2}\\int_0^1 t\\,u\\,du',
            expr: 'integral(t*u, u, 0, 1)/2',
            mistake: 'leftover-x-in-u-integral',
            why: 't dt is part of du/2; no t may remain inside the u-integral.',
          },
        ],
        correct: 0,
        explanation: '$\\sin(t^2) = u$, $t\\cos(t^2)\\,dt = \\frac{1}{2}\\,du$, and the limits are 0 and 1.',
        result: { latex: '= \\frac{1}{2}\\int_0^1 u\\,du' },
        check: { kind: 'value', expected: 'integral(t*cos(t^2)*sin(t^2), t, 0, sqrt(pi/2))' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '\\frac{1}{4}', expr: '1/4' },
          {
            latex: '\\frac{1}{2}',
            expr: '1/2',
            mistake: 'power-rule-int-coefficient',
            why: '∫u du = u²/2; the division by 2 was skipped, giving ½ · 1.',
          },
          {
            latex: '\\frac{\\pi}{8}',
            expr: 'pi/8',
            mistake: 'bounds-not-converted',
            why: 'Evaluated ½ · u²/2 at the t-limits: ¼ · (√(π/2))² = π/8.',
          },
          {
            latex: '\\frac{\\sin^2(1)}{4}',
            expr: 'sin(1)^2/4',
            mistake: 'mixed-limits-variable',
            why: 'The u-limits 0 and 1 were plugged into sin²(t²)/4, an expression in t.',
          },
          { latex: '-\\frac{1}{4}', expr: '-1/4', mistake: 'ftc-order-swapped', why: 'Computed F(0) − F(1) instead of F(1) − F(0).' },
        ],
        correct: 0,
        explanation: '$\\frac{1}{2}\\cdot\\frac{u^2}{2}\\Big|_0^1 = \\frac{1}{4}$.',
        result: { latex: '= \\frac{1}{2}\\cdot\\frac{u^2}{2}\\Big|_0^1 = \\frac{1}{4}' },
        check: { kind: 'value', expected: '1/4' },
      },
    ],
    final: {
      latex: '\\frac{1}{4}',
      expr: '1/4',
      check: { kind: 'definite-integral', integrand: 't*cos(t^2)*sin(t^2)', lower: '0', upper: 'sqrt(pi/2)' },
      recap: '$u = \\sin(t^2)$ has $du = 2t\\cos(t^2)\\,dt$, which absorbs $t\\cos(t^2)\\,dt$ up to $\\frac{1}{2}$; the limits become $\\sin 0 = 0$ and $\\sin\\frac{\\pi}{2} = 1$.',
    },
  },

  // ───────────────────────── ad-s-12: ∫ (8 − 36x²) sec(3x³ − 2x) tan(3x³ − 2x) dx ─────────────────────────
  {
    id: 'ad-s-12',
    topic: 'antiderivatives',
    title: 'Matching a constant multiple of du',
    difficulty: 2,
    statement: { text: 'Find', latex: '\\int (8-36x^2)\\sec(3x^3-2x)\\tan(3x^3-2x)\\,dx' },
    domain: [-0.8, 1],
    steps: [
      {
        prompt: 'Which substitution works directly?',
        options: [
          { text: '$u = 3x^3 - 2x$' },
          {
            text: '$u = \\tan(3x^3 - 2x)$',
            mistake: 'u-choice-wrong',
            why: 'du = (9x² − 2)sec²(3x³ − 2x)dx; the integrand has sec·tan, not sec².',
          },
          {
            text: '$u = 8 - 36x^2$',
            mistake: 'u-choice-wrong',
            why: 'du = −72x dx does not appear, and the trigonometric factors do not simplify.',
          },
          {
            text: '$u = 3x^3$',
            mistake: 'u-choice-wrong',
            why: 'The inner function is all of 3x³ − 2x; with u = 3x³ the −2x is left over.',
          },
          {
            text: 'Integration by parts with $u = 8 - 36x^2$',
            mistake: 'ibp-when-usub',
            why: 'The factor 8 − 36x² is already a constant multiple of the inner derivative 9x² − 2; substitute instead.',
          },
        ],
        correct: 0,
        explanation: 'The factor $8 - 36x^2$ is a constant multiple of the derivative $9x^2 - 2$ of the inner function $3x^3 - 2x$.',
        result: { latex: 'u = 3x^3 - 2x' },
      },
      {
        prompt: 'What is $du$?',
        options: [
          { latex: 'du = (9x^2 - 2)\\,dx', expr: '(9*x^2 - 2)*dx' },
          {
            latex: 'du = (9x^2 - 2x)\\,dx',
            expr: '(9*x^2 - 2*x)*dx',
            mistake: 'power-rule-exponent',
            why: 'd/dx(2x) = 2: the exponent of x drops from 1 to 0.',
          },
          {
            latex: 'du = (3x^2 - 2)\\,dx',
            expr: '(3*x^2 - 2)*dx',
            mistake: 'power-rule-coefficient',
            why: 'd/dx(3x³) = 9x²: the exponent 3 multiplies the coefficient 3.',
          },
          {
            latex: 'du = \\left(\\frac{3}{4}x^4 - x^2\\right)dx',
            expr: '(3/4*x^4 - x^2)*dx',
            mistake: 'integrated-instead',
            why: 'du uses the derivative of u, not an antiderivative.',
          },
          { latex: 'du = 9x^2 - 2', expr: '9*x^2 - 2', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(3x^3 - 2x) = 9x^2 - 2$.',
        result: { latex: 'du = (9x^2 - 2)\\,dx' },
        check: { kind: 'value', expected: '(9*x^2 - 2)*dx' },
      },
      {
        prompt: 'Since $8 - 36x^2 = -4(9x^2 - 2)$, the integral becomes',
        options: [
          { latex: '-4\\int \\sec u\\tan u\\,du', expr: 'indefinite(-4*sec(u)*tan(u), u)' },
          {
            latex: '4\\int \\sec u\\tan u\\,du',
            expr: 'indefinite(4*sec(u)*tan(u), u)',
            mistake: 'sign-error',
            why: '8 − 36x² = −4(9x² − 2); the factor is −4, with its minus sign.',
          },
          {
            latex: '-\\frac{1}{4}\\int \\sec u\\tan u\\,du',
            expr: 'indefinite(-sec(u)*tan(u)/4, u)',
            mistake: 'du-constant-wrong',
            why: 'The factor −4 was inverted to −1/4.',
          },
          {
            latex: '-36\\int \\sec u\\tan u\\,du',
            expr: 'indefinite(-36*sec(u)*tan(u), u)',
            mistake: 'coefficient-mishandled',
            why: '−36x² = −4 · 9x², so the factor is −4, not −36.',
          },
          {
            latex: '-4\\int x^2\\sec u\\tan u\\,du',
            expr: 'indefinite(-4*x^2*sec(u)*tan(u), u)',
            mistake: 'leftover-x-in-u-integral',
            why: 'All of (8 − 36x²)dx became −4 du; no x may remain.',
          },
        ],
        correct: 0,
        explanation: '$(8 - 36x^2)\\,dx = -4(9x^2 - 2)\\,dx = -4\\,du$.',
        result: { latex: '= -4\\int \\sec u\\tan u\\,du' },
        check: { kind: 'identity', lhs: '-4*sec(u)*tan(u)' },
      },
      {
        prompt: 'Integrate and return to $x$.',
        options: [
          { latex: '-4\\sec(3x^3-2x) + C', expr: '-4*sec(3*x^3-2*x)' },
          {
            latex: '4\\sec(3x^3-2x) + C',
            expr: '4*sec(3*x^3-2*x)',
            mistake: 'trig-antiderivative-sign',
            why: '∫sec u tan u du = +sec u (since d/du sec u = sec u tan u); no extra minus sign.',
          },
          {
            latex: '-4\\tan(3x^3-2x) + C',
            expr: '-4*tan(3*x^3-2*x)',
            mistake: 'trig-antiderivative-swapped',
            why: 'tan u is the antiderivative of sec²u; ∫sec u tan u du = sec u.',
          },
          { latex: '-4\\sec u + C', expr: '-4*sec(u)', mistake: 'not-back-substituted', why: 'The answer must be in x: replace u by 3x³ − 2x.' },
          {
            latex: '-4\\sec(9x^2-2) + C',
            expr: '-4*sec(9*x^2-2)',
            mistake: 'back-substitution-wrong',
            why: 'u is 3x³ − 2x; 9x² − 2 is its derivative, not u.',
          },
        ],
        correct: 0,
        explanation: '$-4\\int\\sec u\\tan u\\,du = -4\\sec u + C$ with $u = 3x^3 - 2x$.',
        result: { latex: '= -4\\sec u + C = -4\\sec(3x^3 - 2x) + C' },
        check: { kind: 'antiderivative', integrand: '(8-36*x^2)*sec(3*x^3-2*x)*tan(3*x^3-2*x)' },
      },
    ],
    final: {
      latex: '-4\\sec(3x^3-2x) + C',
      expr: '-4*sec(3*x^3-2*x)',
      check: { kind: 'antiderivative', integrand: '(8-36*x^2)*sec(3*x^3-2*x)*tan(3*x^3-2*x)' },
      recap: 'The factor $8 - 36x^2$ is $-4$ times the derivative of the inner function $3x^3 - 2x$, so $u = 3x^3 - 2x$ gives $-4\\int\\sec u\\tan u\\,du = -4\\sec u$.',
    },
  },

  // ───────────────────────── ad-s-13: ∫₀² 1/(√x (2 + √x)²) dx ─────────────────────────
  {
    id: 'ad-s-13',
    topic: 'antiderivatives',
    title: 'Root inside and outside',
    difficulty: 2,
    statement: { text: 'Evaluate', latex: '\\int_0^2 \\frac{1}{\\sqrt{x}\\,(2+\\sqrt{x})^2}\\,dx' },
    steps: [
      {
        prompt: 'Which first step works directly?',
        options: [
          { text: '$u = 2 + \\sqrt{x}$' },
          { text: '$u = 2 + x$', mistake: 'u-choice-wrong', why: 'du = dx; the √x terms remain.' },
          {
            text: '$u = \\sqrt{x}\\,(2+\\sqrt{x})^2$, the whole denominator',
            mistake: 'u-choice-wrong',
            why: 'Its derivative does not appear in the numerator.',
          },
          {
            text: 'Expand $(2+\\sqrt{x})^2 = 4 + x$ first',
            mistake: 'algebra-error',
            why: '(a + b)² = a² + 2ab + b²; the middle term 4√x is missing.',
          },
          {
            text: 'Split into $\\int_0^2\\frac{dx}{\\sqrt{x}}\\cdot\\int_0^2\\frac{dx}{(2+\\sqrt{x})^2}$',
            mistake: 'product-rule-integral',
            why: 'There is no product rule for integrals.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(2 + \\sqrt{x}) = \\frac{1}{2\\sqrt{x}}$, and $\\frac{1}{\\sqrt{x}}$ is a factor of the integrand.',
        result: { latex: 'u = 2 + \\sqrt{x}' },
      },
      {
        prompt: 'What is $du$?',
        options: [
          { latex: 'du = \\frac{1}{2\\sqrt{x}}\\,dx', expr: 'dx/(2*sqrt(x))' },
          { latex: 'du = \\frac{1}{\\sqrt{x}}\\,dx', expr: 'dx/sqrt(x)', mistake: 'du-constant-wrong', why: 'd/dx √x = 1/(2√x); the 1/2 was dropped.' },
          {
            latex: 'du = \\left(2 + \\frac{1}{2\\sqrt{x}}\\right)dx',
            expr: '(2 + 1/(2*sqrt(x)))*dx',
            mistake: 'constant-derivative',
            why: 'The derivative of the constant 2 is 0.',
          },
          {
            latex: 'du = \\frac{2}{3}x^{3/2}\\,dx',
            expr: '2/3*x^(3/2)*dx',
            mistake: 'integrated-instead',
            why: 'That is an antiderivative of √x; du uses its derivative.',
          },
          { latex: 'du = \\frac{1}{2\\sqrt{x}}', expr: '1/(2*sqrt(x))', mistake: 'dx-not-replaced', why: 'du = u′(x) dx; the dx is part of du.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{dx}(2 + x^{1/2}) = \\frac{1}{2}x^{-1/2}$, so $du = \\frac{dx}{2\\sqrt{x}}$.',
        result: { latex: 'du = \\frac{dx}{2\\sqrt{x}} \\;\\Rightarrow\\; \\frac{dx}{\\sqrt{x}} = 2\\,du' },
        check: { kind: 'value', expected: 'dx/(2*sqrt(x))' },
      },
      {
        prompt: 'What are the new limits of integration?',
        options: [
          { latex: 'u(0) = 2,\\ u(2) = 2 + \\sqrt{2}', expr: '[2, 2 + sqrt(2)]' },
          {
            latex: 'u(0) = 0,\\ u(2) = 2',
            expr: '[0, 2]',
            mistake: 'bounds-not-converted',
            why: 'These are the x-limits; they must be pushed through u = 2 + √x.',
          },
          { latex: 'u(0) = 2,\\ u(2) = 4', expr: '[2, 4]', mistake: 'algebra-error', why: 'u(2) = 2 + √2; the square root was forgotten.' },
          {
            latex: 'u(0) = 0,\\ u(2) = \\sqrt{2}',
            expr: '[0, sqrt(2)]',
            mistake: 'back-substitution-wrong',
            why: 'These are values of √x; the substitution is u = 2 + √x.',
          },
          {
            latex: 'u(0) = 2 + \\sqrt{2},\\ u(2) = 2',
            expr: '[2 + sqrt(2), 2]',
            mistake: 'bounds-swapped',
            why: 'x = 0 is the lower limit, so u(0) = 2 is the lower u-limit.',
          },
        ],
        correct: 0,
        explanation: '$u(0) = 2 + \\sqrt{0} = 2$ and $u(2) = 2 + \\sqrt{2}$.',
        result: { latex: 'x = 0 \\Rightarrow u = 2,\\quad x = 2 \\Rightarrow u = 2 + \\sqrt{2}' },
        check: { kind: 'value', expected: '[2, 2 + sqrt(2)]' },
      },
      {
        prompt: 'Rewrite the integral entirely in $u$.',
        options: [
          { latex: '2\\int_2^{2+\\sqrt{2}} u^{-2}\\,du', expr: '2*integral(u^(-2), u, 2, 2 + sqrt(2))' },
          {
            latex: '\\frac{1}{2}\\int_2^{2+\\sqrt{2}} u^{-2}\\,du',
            expr: 'integral(u^(-2), u, 2, 2 + sqrt(2))/2',
            mistake: 'du-constant-wrong',
            why: 'dx/√x = 2 du, not du/2.',
          },
          {
            latex: '\\int_2^{2+\\sqrt{2}} u^{-2}\\,du',
            expr: 'integral(u^(-2), u, 2, 2 + sqrt(2))',
            mistake: 'du-constant-wrong',
            why: 'dx/√x = 2 du; the factor 2 was dropped.',
          },
          {
            latex: '2\\int_2^{2+\\sqrt{2}} u^{2}\\,du',
            expr: '2*integral(u^2, u, 2, 2 + sqrt(2))',
            mistake: 'algebra-error',
            why: '1/u² = u^{−2}, not u².',
          },
          {
            latex: '2\\int_2^{2+\\sqrt{2}} \\frac{u^{-2}}{\\sqrt{x}}\\,du',
            expr: '2*integral(u^(-2)/sqrt(x), u, 2, 2 + sqrt(2))',
            mistake: 'leftover-x-in-u-integral',
            why: 'The 1/√x is part of dx/√x = 2 du; no x may remain.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{dx}{\\sqrt{x}} = 2\\,du$ and $\\frac{1}{(2+\\sqrt{x})^2} = u^{-2}$, with limits $2$ and $2 + \\sqrt{2}$.',
        result: { latex: '= 2\\int_2^{2+\\sqrt{2}} \\frac{du}{u^2}' },
        check: { kind: 'value', expected: 'integral(1/(sqrt(x)*(2+sqrt(x))^2), x, 0, 2)' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '\\sqrt{2} - 1', expr: 'sqrt(2) - 1' },
          {
            latex: '1 - \\sqrt{2}',
            expr: '1 - sqrt(2)',
            mistake: 'ftc-order-swapped',
            why: 'Computed F(2) − F(2 + √2) instead of F(2 + √2) − F(2).',
          },
          {
            latex: '\\frac{\\sqrt{2} - 1}{4}',
            expr: '(sqrt(2) - 1)/4',
            mistake: 'du-constant-wrong',
            why: 'Used dx/√x = du/2 instead of 2 du, which divides the answer by 4.',
          },
          {
            latex: '\\frac{2}{2+\\sqrt{2}} - \\frac{2}{2+\\sqrt{2+\\sqrt{2}}}',
            expr: '2/(2 + sqrt(2)) - 2/(2 + sqrt(2 + sqrt(2)))',
            mistake: 'mixed-limits-variable',
            why: 'The u-limits 2 and 2 + √2 were plugged into −2/(2 + √x), an x-expression.',
          },
          {
            latex: '2\\ln\\left(1 + \\frac{\\sqrt{2}}{2}\\right)',
            expr: '2*log(1 + sqrt(2)/2)',
            mistake: 'ln-misapplied',
            why: 'Only u^{−1} integrates to ln|u|; ∫u^{−2}du = −u^{−1}.',
          },
        ],
        correct: 0,
        explanation: '$-\\frac{2}{u}\\Big|_2^{2+\\sqrt{2}} = 1 - \\frac{2}{2+\\sqrt{2}} = 1 - (2 - \\sqrt{2}) = \\sqrt{2} - 1$.',
        result: { latex: '= -\\frac{2}{u}\\Big|_2^{2+\\sqrt{2}} = 1 - \\frac{2}{2+\\sqrt{2}} = \\sqrt{2} - 1' },
        check: { kind: 'value', expected: 'sqrt(2) - 1' },
      },
    ],
    final: {
      latex: '\\sqrt{2} - 1',
      expr: 'sqrt(2) - 1',
      check: { kind: 'definite-integral', integrand: '1/(sqrt(x)*(2+sqrt(x))^2)', lower: '0', upper: '2' },
      recap: '$u = 2 + \\sqrt{x}$ has $du = \\frac{dx}{2\\sqrt{x}}$, which absorbs the $\\frac{1}{\\sqrt{x}}$; the limits become 2 and $2 + \\sqrt{2}$, and $2\\int u^{-2}\\,du = -\\frac{2}{u}$.',
    },
  },
];
