import type { StepProblem } from '../types';

/** Step-Through problems for topic "arc-length". Authored by content-author; verified by math-verifier. */
export const steps: StepProblem[] = [
  {
    id: 'al-s-01',
    topic: 'arc-length',
    title: 'A perfect-square arc length',
    difficulty: 1,
    statement: { text: 'Find the exact length of the curve', latex: 'y = \\frac{x^3}{6} + \\frac{1}{2x},\\quad 1 \\le x \\le 2' },
    steps: [
      {
        prompt: "Find $f'(x)$.",
        options: [
          { latex: '\\frac{x^2}{2} - \\frac{1}{2x^2}', expr: 'x^2/2 - 1/(2*x^2)' },
          { latex: '\\frac{x^2}{2} + \\frac{1}{2x^2}', expr: 'x^2/2 + 1/(2*x^2)', mistake: 'negative-exponent-sign', why: 'd/dx(½x^{−1}) = −½x^{−2}; the minus sign was lost.' },
          { latex: '\\frac{x^2}{6} - \\frac{1}{2x^2}', expr: 'x^2/6 - 1/(2*x^2)', mistake: 'power-rule-coefficient', why: 'd/dx(x³/6) = 3x²/6 = x²/2; the exponent 3 was not brought down.' },
          { latex: '\\frac{x^2}{2} - \\frac{1}{2x}', expr: 'x^2/2 - 1/(2*x)', mistake: 'power-rule-exponent', why: 'The exponent of ½x^{−1} must drop to −2; keeping −1 gives 1/(2x).' },
          { latex: '\\frac{x^2}{2} - \\frac{1}{4x^2}', expr: 'x^2/2 - 1/(4*x^2)', mistake: 'chain-rule-missing', why: 'Writing 1/(2x) = (2x)^{−1}, its derivative is −(2x)^{−2}·2; the inner factor 2 was dropped.' },
          { latex: '\\frac{x^4}{24} + \\frac{1}{2}\\ln x', expr: 'x^4/24 + log(x)/2', mistake: 'integrated-instead', why: 'This is an antiderivative of f, not its derivative.' },
        ],
        correct: 0,
        explanation: 'Power rule on each term: $\\frac{3x^2}{6} = \\frac{x^2}{2}$ and $\\frac{1}{2}\\cdot(-1)x^{-2} = -\\frac{1}{2x^2}$.',
        result: { latex: "f'(x) = \\frac{x^2}{2} - \\frac{1}{2x^2}" },
        check: { kind: 'derivative', of: 'x^3/6 + 1/(2*x)' },
      },
      {
        prompt: "Simplify $1 + (f'(x))^2$.",
        options: [
          { latex: '\\frac{x^4}{4} + \\frac{1}{2} + \\frac{1}{4x^4}', expr: 'x^4/4 + 1/2 + 1/(4*x^4)' },
          { latex: '\\frac{x^4}{4} - \\frac{1}{2} + \\frac{1}{4x^4}', expr: 'x^4/4 - 1/2 + 1/(4*x^4)', mistake: 'arclength-missing-one', why: 'That is (f′)² alone; adding the 1 turns −½ into +½.' },
          { latex: '\\frac{x^4}{4} + 1 + \\frac{1}{4x^4}', expr: 'x^4/4 + 1 + 1/(4*x^4)', mistake: 'algebra-error', why: 'The cross term 2·(x²/2)·(−1/(2x²)) = −½ was dropped when squaring.' },
          { latex: '\\frac{x^4}{4} + \\frac{3}{2} + \\frac{1}{4x^4}', expr: 'x^4/4 + 3/2 + 1/(4*x^4)', mistake: 'sign-error', why: 'The cross term of (a − b)² is −2ab = −½, not +½.' },
          { latex: '\\frac{x^4}{2} + \\frac{1}{2} + \\frac{1}{2x^4}', expr: 'x^4/2 + 1/2 + 1/(2*x^4)', mistake: 'coefficient-mishandled', why: '(x²/2)² = x⁴/4; the coefficients ½ were not squared.' },
          { latex: '1 + \\frac{x^2}{2} - \\frac{1}{2x^2}', expr: '1 + x^2/2 - 1/(2*x^2)', mistake: 'arclength-not-squared', why: 'f′ was added to 1 without being squared.' },
        ],
        correct: 0,
        explanation: '$(f\')^2 = \\frac{x^4}{4} - \\frac{1}{2} + \\frac{1}{4x^4}$, and adding 1 turns $-\\frac{1}{2}$ into $+\\frac{1}{2}$.',
        result: { latex: "1 + (f'(x))^2 = 1 + \\frac{x^4}{4} - \\frac{1}{2} + \\frac{1}{4x^4} = \\frac{x^4}{4} + \\frac{1}{2} + \\frac{1}{4x^4}" },
        check: { kind: 'identity', lhs: '1 + (x^2/2 - 1/(2*x^2))^2' },
      },
      {
        prompt: 'Write $\\frac{x^4}{4} + \\frac{1}{2} + \\frac{1}{4x^4}$ as a perfect square.',
        options: [
          { latex: '\\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)^2', expr: '(x^2/2 + 1/(2*x^2))^2' },
          { latex: '\\left(\\frac{x^2}{2} - \\frac{1}{2x^2}\\right)^2', expr: '(x^2/2 - 1/(2*x^2))^2', mistake: 'sign-error', why: 'That square has middle term −½, not +½.' },
          { latex: '\\left(\\frac{x^2}{2} - \\frac{1}{2x}\\right)^2', expr: '(x^2/2 - 1/(2*x))^2', mistake: 'formula-wrong-power', why: 'This expands to x⁴/4 − x/2 + 1/(4x²); matching 1/(4x⁴) needs 1/(2x²), and matching +½ needs a + sign.' },
          { latex: '\\left(\\frac{x}{2} - \\frac{1}{2x}\\right)^2', expr: '(x/2 - 1/(2*x))^2', mistake: 'formula-wrong-power', why: 'This expands to x²/4 − ½ + 1/(4x²); √(x⁴/4) = x²/2, not x/2, and the middle sign must be +.' },
          { latex: '\\left(\\frac{x^2}{4} - \\frac{1}{4x^2}\\right)^2', expr: '(x^2/4 - 1/(4*x^2))^2', mistake: 'sqrt-constant-not-rooted', why: 'The constants were not square-rooted (√(1/4) = 1/2), and the middle term needs a + sign.' },
          { latex: '\\left(\\frac{x}{2} + \\frac{1}{2x}\\right)^2', expr: '(x/2 + 1/(2*x))^2', mistake: 'formula-wrong-power', why: '√(x⁴) = x², not x; this square only produces x²/4.' },
        ],
        correct: 0,
        explanation: '$\\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)^2 = \\frac{x^4}{4} + 2\\cdot\\frac{1}{4} + \\frac{1}{4x^4}$ matches term by term.',
        result: { latex: "1 + (f'(x))^2 = \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)^2" },
        check: { kind: 'identity', lhs: 'x^4/4 + 1/2 + 1/(4*x^4)' },
      },
      {
        prompt: 'Set up the arc length with the square root removed.',
        options: [
          { latex: 'L = \\int_1^2 \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)dx', expr: 'integral(x^2/2 + 1/(2*x^2), x, 1, 2)' },
          { latex: 'L = \\int_1^2 \\left(\\frac{x^2}{2} - \\frac{1}{2x^2}\\right)dx', expr: 'integral(x^2/2 - 1/(2*x^2), x, 1, 2)', mistake: 'arclength-missing-one', why: 'This is √((f′)²) = f′: the 1 was dropped, so the middle sign never flipped.' },
          { latex: 'L = \\int_1^2 \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)^2 dx', expr: 'integral((x^2/2 + 1/(2*x^2))^2, x, 1, 2)', mistake: 'arclength-no-root', why: 'The square root of the perfect square was never taken.' },
          { latex: 'L = \\int_1^2 \\left(1 + \\frac{x^2}{2} - \\frac{1}{2x^2}\\right)dx', expr: 'integral(1 + x^2/2 - 1/(2*x^2), x, 1, 2)', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √((f′)²); a square root does not split over a sum.' },
          { latex: 'L = \\int_{2/3}^{19/12} \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)dx', expr: 'integral(x^2/2 + 1/(2*x^2), x, 2/3, 19/12)', mistake: 'arclength-variable-mismatch', why: '2/3 and 19/12 are the y-values at the endpoints; a dx integral runs from x = 1 to x = 2.' },
        ],
        correct: 0,
        explanation: 'The base $\\frac{x^2}{2} + \\frac{1}{2x^2}$ is positive, so $\\sqrt{(\\cdot)^2} = |\\cdot|$ is the base itself.',
        result: { latex: 'L = \\int_1^2 \\sqrt{\\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)^2}\\,dx = \\int_1^2 \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)dx' },
        check: { kind: 'value', expected: '17/12' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: '\\frac{17}{12}', expr: '17/12' },
          { latex: '\\frac{11}{12}', expr: '11/12', mistake: 'sign-error', why: '∫x^{−2}dx = −x^{−1}; using +1/(2x) as the antiderivative of 1/(2x²) flips that term.' },
          { latex: '\\frac{13}{12}', expr: '13/12', mistake: 'ftc-not-subtracted', why: 'F(2) = 4/3 − 1/4 = 13/12 alone; F(1) = −1/3 must still be subtracted.' },
          { latex: '\\frac{3}{4}', expr: '3/4', mistake: 'arithmetic-error', why: 'F(1) = 1/6 − 1/2 = −1/3; subtracting +1/3 instead gives 3/4.' },
          { latex: '\\frac{15}{4}', expr: '15/4', mistake: 'power-rule-int-coefficient', why: '∫(x²/2)dx = x³/6; without dividing by 3 the result is 15/4.' },
        ],
        correct: 0,
        explanation: '$F(x) = \\frac{x^3}{6} - \\frac{1}{2x}$ gives $F(2) - F(1) = \\frac{13}{12} + \\frac{1}{3} = \\frac{17}{12}$.',
        result: { latex: 'L = \\left[\\frac{x^3}{6} - \\frac{1}{2x}\\right]_1^2 = \\left(\\frac{4}{3} - \\frac{1}{4}\\right) - \\left(\\frac{1}{6} - \\frac{1}{2}\\right) = \\frac{17}{12}' },
        check: { kind: 'value', expected: '17/12' },
      },
    ],
    final: {
      latex: 'L = \\frac{17}{12}',
      expr: '17/12',
      check: { kind: 'definite-integral', integrand: 'sqrt(1 + (x^2/2 - 1/(2*x^2))^2)', lower: '1', upper: '2' },
      recap: "Adding 1 to $(f')^2$ flips the middle sign, so $1 + (f')^2 = \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)^2$ and the square root disappears.",
    },
  },
  {
    id: 'al-s-02',
    topic: 'arc-length',
    title: 'Semicubical parabola, integrating in x',
    difficulty: 1,
    statement: { text: 'Find the length of the semicubical parabola $y^2 = x^3$ between the points $(1, 1)$ and $(4, 8)$.' },
    steps: [
      {
        prompt: 'Write the part of the curve between the two points as $y = f(x)$.',
        options: [
          { text: '$y = x^{3/2}$, the upper branch ($y > 0$)' },
          { text: '$y = -x^{3/2}$, the lower branch of the curve', mistake: 'wrong-branch-chosen', why: 'Both endpoints have positive y, so the arc lies on the upper branch y = +x^{3/2}.' },
          { text: '$y = x^{2/3}$, from taking the root of both sides', mistake: 'inverse-function-wrong', why: 'Taking the square root of y² = x³ gives |y| = x^{3/2}; the exponent 2/3 solves for x instead.' },
          { text: '$y = x^3$, reading the equation as $y = x^3$', mistake: 'algebra-error', why: 'y² = x³ means |y| = √(x³) = x^{3/2}; the square root was not taken.' },
          { text: '$y = \\pm x^{3/2}$, both branches at once', mistake: 'wrong-branch-chosen', why: 'A function gives one y per x; the arc from (1, 1) to (4, 8) lies on the upper branch only.' },
        ],
        correct: 0,
        explanation: '$y^2 = x^3$ gives $|y| = x^{3/2}$; both given points have $y > 0$, so $f(x) = x^{3/2}$.',
        result: { text: 'Both points have $y > 0$, so the arc is $y = f(x) = x^{3/2}$ for $1 \\le x \\le 4$.' },
      },
      {
        prompt: "Compute $(f'(x))^2$.",
        options: [
          { latex: '\\frac{9}{4}x', expr: '9/4*x' },
          { latex: 'x^3', expr: 'x^3', mistake: 'arclength-f-instead-of-fprime', why: '(x^{3/2})² = x³ is f(x)², not the square of the derivative.' },
          { latex: '\\frac{3}{2}x^{1/2}', expr: '3/2*x^(1/2)', mistake: 'arclength-not-squared', why: 'That is f′(x) itself; it still has to be squared.' },
          { latex: '\\frac{9}{4}x^2', expr: '9/4*x^2', mistake: 'power-rule-exponent', why: 'f′ was taken as (3/2)x (exponent lowered by ½); the correct f′ = (3/2)x^{1/2}.' },
          { latex: '\\frac{3}{2}x', expr: '3/2*x', mistake: 'coefficient-mishandled', why: '((3/2)x^{1/2})² = (9/4)x; the coefficient 3/2 was not squared.' },
          { latex: '\\frac{9}{4}x^3', expr: '9/4*x^3', mistake: 'power-rule-exponent', why: 'The exponent 3/2 was not lowered at all: f′ = (3/2)x^{3/2} is wrong.' },
        ],
        correct: 0,
        explanation: "$f'(x) = \\frac{3}{2}x^{1/2}$, and squaring gives $\\frac{9}{4}x$.",
        result: { latex: "f'(x) = \\frac{3}{2}x^{1/2},\\qquad (f'(x))^2 = \\frac{9}{4}x" },
        check: { kind: 'identity', lhs: '(3/2*x^(1/2))^2' },
      },
      {
        prompt: 'Set up the arc-length integral.',
        options: [
          { latex: 'L = \\int_1^4 \\sqrt{1 + \\frac{9}{4}x}\\,dx', expr: 'integral(sqrt(1 + 9/4*x), x, 1, 4)' },
          { latex: 'L = \\int_1^8 \\sqrt{1 + \\frac{9}{4}x}\\,dx', expr: 'integral(sqrt(1 + 9/4*x), x, 1, 8)', mistake: 'arclength-variable-mismatch', why: '1 and 8 are the y-coordinates; a dx integral runs from x = 1 to x = 4.' },
          { latex: 'L = \\int_1^4 \\left(1 + \\frac{9}{4}x\\right)dx', expr: 'integral(1 + 9/4*x, x, 1, 4)', mistake: 'arclength-no-root', why: 'The square root around 1 + (f′)² is missing.' },
          { latex: 'L = \\int_1^4 \\left(1 + \\frac{3}{2}\\sqrt{x}\\right)dx', expr: 'integral(1 + 3/2*sqrt(x), x, 1, 4)', mistake: 'sqrt-of-sum-split', why: '√(1 + (9/4)x) was split into 1 + (3/2)√x; a root does not split over a sum.' },
          { latex: 'L = \\int_1^4 \\frac{3}{2}\\sqrt{x}\\,dx', expr: 'integral(3/2*sqrt(x), x, 1, 4)', mistake: 'arclength-missing-one', why: 'Without the 1, √((f′)²) = f′ only measures the vertical change.' },
          { latex: 'L = \\int_1^4 \\sqrt{1 + x^3}\\,dx', expr: 'integral(sqrt(1 + x^3), x, 1, 4)', mistake: 'arclength-f-instead-of-fprime', why: 'This squares f(x) = x^{3/2} instead of f′(x).' },
        ],
        correct: 0,
        explanation: 'Theorem 5.1 with $(f\')^2 = \\frac{9}{4}x$ and the $x$-values 1 and 4 of the endpoints.',
        result: { latex: 'L = \\int_1^4 \\sqrt{1 + \\frac{9}{4}x}\\,dx' },
        check: { kind: 'value', expected: '(80*sqrt(10) - 13*sqrt(13))/27' },
      },
      {
        prompt: 'Substitute $u = 1 + \\frac{9}{4}x$. What does the integral become?',
        options: [
          { latex: '\\frac{4}{9}\\int_{13/4}^{10} \\sqrt{u}\\,du', expr: '4/9*integral(sqrt(u), u, 13/4, 10)' },
          { latex: '\\frac{4}{9}\\int_1^4 \\sqrt{u}\\,du', expr: '4/9*integral(sqrt(u), u, 1, 4)', mistake: 'bounds-not-converted', why: 'The x-limits were kept; they become u(1) = 13/4 and u(4) = 10.' },
          { latex: '\\frac{9}{4}\\int_{13/4}^{10} \\sqrt{u}\\,du', expr: '9/4*integral(sqrt(u), u, 13/4, 10)', mistake: 'du-constant-wrong', why: 'du = (9/4)dx means dx = (4/9)du, not (9/4)du.' },
          { latex: '\\int_{13/4}^{10} \\sqrt{u}\\,du', expr: 'integral(sqrt(u), u, 13/4, 10)', mistake: 'inner-constant-factor-missing', why: 'dx = (4/9)du; the factor 4/9 was dropped.' },
          { latex: '\\frac{4}{9}\\int_{13/4}^{10} \\sqrt{u}\\,dx', expr: '4/9*integral(sqrt(u), x, 13/4, 10)', mistake: 'dx-not-replaced', why: 'The differential must become du; dx was left in place.' },
          { latex: '\\frac{4}{9}\\int_{9/4}^{10} \\sqrt{u}\\,du', expr: '4/9*integral(sqrt(u), u, 9/4, 10)', mistake: 'arithmetic-error', why: 'u(1) = 1 + 9/4 = 13/4; the 1 was forgotten.' },
        ],
        correct: 0,
        explanation: '$du = \\frac{9}{4}\\,dx$, so $dx = \\frac{4}{9}\\,du$; $x = 1 \\mapsto u = \\frac{13}{4}$ and $x = 4 \\mapsto u = 10$.',
        result: { latex: 'u = 1 + \\frac{9}{4}x,\\ du = \\frac{9}{4}\\,dx:\\quad L = \\frac{4}{9}\\int_{13/4}^{10} \\sqrt{u}\\,du' },
        check: { kind: 'value', expected: '(80*sqrt(10) - 13*sqrt(13))/27' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '\\frac{80\\sqrt{10} - 13\\sqrt{13}}{27}', expr: '(80*sqrt(10) - 13*sqrt(13))/27' },
          { latex: '\\frac{80\\sqrt{10} - 13\\sqrt{13}}{12}', expr: '(80*sqrt(10) - 13*sqrt(13))/12', mistake: 'power-rule-int-coefficient', why: '∫√u du = ⅔u^{3/2}; multiplying by 3/2 instead gives (4/9)(3/2) = 2/3 and the denominator 12.' },
          { latex: '\\frac{80\\sqrt{10}}{27}', expr: '80*sqrt(10)/27', mistake: 'ftc-not-subtracted', why: 'Only u = 10 was used; the value at u = 13/4 must be subtracted.' },
          { latex: '\\frac{80\\sqrt{10} - 26\\sqrt{13}}{27}', expr: '(80*sqrt(10) - 26*sqrt(13))/27', mistake: 'arithmetic-error', why: '(13/4)^{3/2} = 13√13/8, not 13√13/4: the denominator is 4^{3/2} = 8.' },
          { latex: '\\frac{80\\sqrt{10} + 13\\sqrt{13}}{27}', expr: '(80*sqrt(10) + 13*sqrt(13))/27', mistake: 'ftc-not-subtracted', why: 'The value at the lower limit was added instead of subtracted.' },
        ],
        correct: 0,
        explanation: '$\\frac{4}{9}\\cdot\\frac{2}{3}u^{3/2}\\Big|_{13/4}^{10} = \\frac{8}{27}\\left(10\\sqrt{10} - \\frac{13\\sqrt{13}}{8}\\right)$.',
        result: { latex: 'L = \\frac{8}{27}u^{3/2}\\Big|_{13/4}^{10} = \\frac{8}{27}\\left(10\\sqrt{10} - \\frac{13\\sqrt{13}}{8}\\right) = \\frac{80\\sqrt{10} - 13\\sqrt{13}}{27} \\approx 7.63' },
        check: { kind: 'value', expected: '(80*sqrt(10) - 13*sqrt(13))/27' },
      },
    ],
    final: {
      latex: 'L = \\frac{80\\sqrt{10} - 13\\sqrt{13}}{27}',
      expr: '(80*sqrt(10) - 13*sqrt(13))/27',
      check: { kind: 'definite-integral', integrand: 'sqrt(1 + (3/2*x^(1/2))^2)', lower: '1', upper: '4' },
      recap: "Use the branch through the given points, square $f'$ before adding 1, and take the $x$-coordinates 1 and 4 as limits; the linear radicand is finished by $u = 1 + \\frac{9}{4}x$.",
    },
  },
  {
    id: 'al-s-03',
    topic: 'arc-length',
    title: 'Semicubical parabola, integrating in y',
    difficulty: 2,
    statement: { text: 'Find the length of $y^2 = x^3$ from $(1, 1)$ to $(4, 8)$ by integrating with respect to $y$.' },
    variable: 'y',
    domain: [1, 8],
    steps: [
      {
        prompt: 'Write the curve as $x = g(y)$ and give the $y$-limits.',
        options: [
          { text: '$x = y^{2/3}$, with $1 \\le y \\le 8$' },
          { text: '$x = y^{2/3}$, with $1 \\le y \\le 4$', mistake: 'bounds-wrong-axis', why: '1 and 4 are the x-coordinates; in y the endpoints are y = 1 and y = 8.' },
          { text: '$x = y^{3/2}$, with $1 \\le y \\le 8$', mistake: 'inverse-function-wrong', why: 'x³ = y² gives x = (y²)^{1/3} = y^{2/3}; 3/2 inverts the wrong way.' },
          { text: '$x = y^{1/3}$, with $1 \\le y \\le 8$', mistake: 'inverse-function-wrong', why: 'x³ = y² gives x = (y²)^{1/3} = y^{2/3}; the square on y was lost.' },
          { text: '$x = \\pm y^{2/3}$, with $1 \\le y \\le 8$', mistake: 'wrong-branch-chosen', why: 'A real cube root has one value: x³ = y² gives x = y^{2/3}, with no ±.' },
        ],
        correct: 0,
        explanation: 'From $x^3 = y^2$, $x = y^{2/3}$; the endpoints have $y = 1$ and $y = 8$.',
        result: { text: '$x = g(y) = y^{2/3}$ for $1 \\le y \\le 8$.' },
      },
      {
        prompt: "Compute $(g'(y))^2$.",
        options: [
          { latex: '\\frac{4}{9}y^{-2/3}', expr: '4/9*y^(-2/3)' },
          { latex: '\\frac{4}{9}y^{2/3}', expr: '4/9*y^(2/3)', mistake: 'power-rule-exponent', why: 'd/dy y^{2/3} = (2/3)y^{−1/3}; the exponent 2/3 − 1 = −1/3 was taken as +1/3.' },
          { latex: '\\frac{2}{3}y^{-1/3}', expr: '2/3*y^(-1/3)', mistake: 'arclength-not-squared', why: 'That is g′(y) itself; it still has to be squared.' },
          { latex: 'y^{4/3}', expr: 'y^(4/3)', mistake: 'arclength-f-instead-of-fprime', why: '(y^{2/3})² = y^{4/3} is g(y)², not (g′(y))².' },
          { latex: '\\frac{2}{3}y^{-2/3}', expr: '2/3*y^(-2/3)', mistake: 'coefficient-mishandled', why: '((2/3)y^{−1/3})² = (4/9)y^{−2/3}; the 2/3 was not squared.' },
          { latex: '\\frac{9}{4}y', expr: '9/4*y', mistake: 'arclength-variable-mismatch', why: 'This is (f′(x))² = 9x/4 with x renamed y; in y the slope is g′(y) = (2/3)y^{−1/3}.' },
        ],
        correct: 0,
        explanation: "$g'(y) = \\frac{2}{3}y^{-1/3}$, so $(g'(y))^2 = \\frac{4}{9}y^{-2/3}$.",
        result: { latex: "g'(y) = \\frac{2}{3}y^{-1/3},\\qquad (g'(y))^2 = \\frac{4}{9}y^{-2/3}" },
        check: { kind: 'identity', lhs: '((2/3)*y^(-1/3))^2' },
      },
      {
        prompt: 'Set up the arc length.',
        options: [
          { latex: 'L = \\int_1^8 \\sqrt{1 + \\frac{4}{9}y^{-2/3}}\\,dy', expr: 'integral(sqrt(1 + 4/9*y^(-2/3)), y, 1, 8)' },
          { latex: 'L = \\int_1^4 \\sqrt{1 + \\frac{4}{9}y^{-2/3}}\\,dy', expr: 'integral(sqrt(1 + 4/9*y^(-2/3)), y, 1, 4)', mistake: 'arclength-variable-mismatch', why: '1 and 4 are x-values; a dy integral runs from y = 1 to y = 8.' },
          { latex: 'L = \\int_1^8 \\sqrt{1 + \\frac{4}{9}y^{-2/3}}\\,dx', expr: 'integral(sqrt(1 + 4/9*y^(-2/3)), x, 1, 8)', mistake: 'dx-dy-mismatch', why: 'The integrand and limits are in y, so the differential must be dy.' },
          { latex: 'L = \\int_1^8 \\left(1 + \\frac{2}{3}y^{-1/3}\\right)dy', expr: 'integral(1 + 2/3*y^(-1/3), y, 1, 8)', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √((g′)²); a square root does not split over a sum.' },
          { latex: 'L = \\int_1^8 \\left(1 + \\frac{4}{9}y^{-2/3}\\right)dy', expr: 'integral(1 + 4/9*y^(-2/3), y, 1, 8)', mistake: 'arclength-no-root', why: 'The square root around 1 + (g′)² is missing.' },
          { latex: 'L = \\int_1^8 \\sqrt{1 + y^{4/3}}\\,dy', expr: 'integral(sqrt(1 + y^(4/3)), y, 1, 8)', mistake: 'arclength-f-instead-of-fprime', why: 'This squares g(y) = y^{2/3} instead of g′(y).' },
        ],
        correct: 0,
        explanation: 'Theorem 5.2 with $(g\')^2 = \\frac{4}{9}y^{-2/3}$ and the $y$-values 1 and 8.',
        result: { latex: 'L = \\int_1^8 \\sqrt{1 + \\frac{4}{9}y^{-2/3}}\\,dy' },
        check: { kind: 'value', expected: '(80*sqrt(10) - 13*sqrt(13))/27' },
      },
      {
        prompt: 'Combine the radicand into one fraction and simplify the integrand.',
        options: [
          { latex: '\\frac{\\sqrt{9y^{2/3} + 4}}{3y^{1/3}}', expr: 'sqrt(9*y^(2/3) + 4)/(3*y^(1/3))' },
          { latex: '\\frac{\\sqrt{9y^{2/3} + 4}}{9y^{2/3}}', expr: 'sqrt(9*y^(2/3) + 4)/(9*y^(2/3))', mistake: 'sqrt-constant-not-rooted', why: 'The root of the denominator 9y^{2/3} is 3y^{1/3}; it was left unrooted.' },
          { latex: '\\frac{\\sqrt{y^{2/3} + 4}}{3y^{1/3}}', expr: 'sqrt(y^(2/3) + 4)/(3*y^(1/3))', mistake: 'algebra-error', why: '1 = 9y^{2/3}/(9y^{2/3}), so the numerator is 9y^{2/3} + 4, not y^{2/3} + 4.' },
          { latex: '\\frac{3y^{1/3} + 2}{3y^{1/3}}', expr: '(3*y^(1/3) + 2)/(3*y^(1/3))', mistake: 'sqrt-of-sum-split', why: '√(9y^{2/3} + 4) is not 3y^{1/3} + 2; a root does not split over a sum.' },
          { latex: '\\frac{\\sqrt{9y^{2/3} + 4}}{3y^{2/3}}', expr: 'sqrt(9*y^(2/3) + 4)/(3*y^(2/3))', mistake: 'formula-wrong-power', why: '√(y^{2/3}) = y^{1/3}; the exponent must be halved.' },
        ],
        correct: 0,
        explanation: '$1 + \\frac{4}{9y^{2/3}} = \\frac{9y^{2/3} + 4}{9y^{2/3}}$, and $\\sqrt{9y^{2/3}} = 3y^{1/3}$.',
        result: { latex: '\\sqrt{1 + \\frac{4}{9y^{2/3}}} = \\sqrt{\\frac{9y^{2/3} + 4}{9y^{2/3}}} = \\frac{\\sqrt{9y^{2/3} + 4}}{3y^{1/3}}' },
        check: { kind: 'identity', lhs: 'sqrt(1 + 4/9*y^(-2/3))' },
      },
      {
        prompt: 'Substitute $u = 9y^{2/3} + 4$. What does $L$ become?',
        options: [
          { latex: '\\frac{1}{18}\\int_{13}^{40} \\sqrt{u}\\,du', expr: 'integral(sqrt(u), u, 13, 40)/18' },
          { latex: '\\frac{1}{18}\\int_1^8 \\sqrt{u}\\,du', expr: 'integral(sqrt(u), u, 1, 8)/18', mistake: 'bounds-not-converted', why: 'The y-limits were kept; they become u(1) = 13 and u(8) = 40.' },
          { latex: '\\frac{1}{6}\\int_{13}^{40} \\sqrt{u}\\,du', expr: 'integral(sqrt(u), u, 13, 40)/6', mistake: 'coefficient-mishandled', why: 'The ⅓ from the denominator 3y^{1/3} was lost; ⅓·⅙ = 1/18.' },
          { latex: '\\frac{1}{3}\\int_{13}^{40} \\sqrt{u}\\,du', expr: 'integral(sqrt(u), u, 13, 40)/3', mistake: 'du-constant-wrong', why: 'du = 6y^{−1/3}dy, so y^{−1/3}dy = du/6; the ⅙ was dropped.' },
          { latex: '\\frac{1}{18}\\int_{13}^{36} \\sqrt{u}\\,du', expr: 'integral(sqrt(u), u, 13, 36)/18', mistake: 'arithmetic-error', why: 'At y = 8, y^{2/3} = 4, so u = 9·4 + 4 = 40.' },
        ],
        correct: 0,
        explanation: '$du = 6y^{-1/3}\\,dy$, so $\\frac{1}{3}y^{-1/3}\\,dy = \\frac{1}{18}\\,du$; $y = 1 \\mapsto u = 13$, $y = 8 \\mapsto u = 40$.',
        result: { latex: 'u = 9y^{2/3} + 4,\\ du = 6y^{-1/3}\\,dy:\\quad L = \\frac{1}{3}\\cdot\\frac{1}{6}\\int_{13}^{40} \\sqrt{u}\\,du = \\frac{1}{18}\\int_{13}^{40} \\sqrt{u}\\,du' },
        check: { kind: 'value', expected: '(80*sqrt(10) - 13*sqrt(13))/27' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '\\frac{80\\sqrt{10} - 13\\sqrt{13}}{27}', expr: '(80*sqrt(10) - 13*sqrt(13))/27' },
          { latex: '\\frac{80\\sqrt{10} - 13\\sqrt{13}}{12}', expr: '(80*sqrt(10) - 13*sqrt(13))/12', mistake: 'power-rule-int-coefficient', why: '∫√u du = ⅔u^{3/2}; multiplying by 3/2 instead turns 1/18 into 1/12.' },
          { latex: '\\frac{80\\sqrt{10}}{27}', expr: '80*sqrt(10)/27', mistake: 'ftc-not-subtracted', why: 'Only u = 40 was used; the value at u = 13 must be subtracted.' },
          { latex: '\\frac{40\\sqrt{10} - 13\\sqrt{13}}{27}', expr: '(40*sqrt(10) - 13*sqrt(13))/27', mistake: 'arithmetic-error', why: '40^{3/2} = 40√40 = 80√10, not 40√10.' },
          { latex: '\\frac{80\\sqrt{10} + 13\\sqrt{13}}{27}', expr: '(80*sqrt(10) + 13*sqrt(13))/27', mistake: 'ftc-not-subtracted', why: 'The value at the lower limit was added instead of subtracted.' },
        ],
        correct: 0,
        explanation: '$\\frac{1}{18}\\cdot\\frac{2}{3}u^{3/2}\\Big|_{13}^{40} = \\frac{40\\sqrt{40} - 13\\sqrt{13}}{27}$ and $40\\sqrt{40} = 80\\sqrt{10}$.',
        result: { latex: 'L = \\frac{1}{27}u^{3/2}\\Big|_{13}^{40} = \\frac{40\\sqrt{40} - 13\\sqrt{13}}{27} = \\frac{80\\sqrt{10} - 13\\sqrt{13}}{27}' },
        check: { kind: 'value', expected: '(80*sqrt(10) - 13*sqrt(13))/27' },
      },
    ],
    final: {
      latex: 'L = \\frac{80\\sqrt{10} - 13\\sqrt{13}}{27}',
      expr: '(80*sqrt(10) - 13*sqrt(13))/27',
      check: { kind: 'definite-integral', integrand: 'sqrt(1 + ((2/3)*y^(-1/3))^2)', lower: '1', upper: '8' },
      recap: 'Integrating in $y$ needs $x = g(y)$ and the $y$-limits 1 to 8; it gives the same length as the $x$-integral, which is the simpler choice here.',
    },
  },
  {
    id: 'al-s-04',
    topic: 'arc-length',
    title: 'The perimeter of the unit circle',
    difficulty: 1,
    statement: {
      text: 'Use the arc-length formula to find the perimeter of the unit circle $x^2 + y^2 = 1$. You may use $\\int \\frac{1}{\\sqrt{1 - x^2}}\\,dx = \\arcsin x + C$.',
    },
    domain: [0.1, 0.9],
    steps: [
      {
        prompt: 'The whole circle is not the graph of one function. Which $y = f(x)$ gives the upper semicircle?',
        options: [
          { latex: '\\sqrt{1 - x^2}', expr: 'sqrt(1 - x^2)' },
          { latex: '-\\sqrt{1 - x^2}', expr: '-sqrt(1 - x^2)', mistake: 'wrong-branch-chosen', why: 'The negative square root gives the lower semicircle.' },
          { latex: '1 - x', expr: '1 - x', mistake: 'sqrt-of-sum-split', why: '√(1 − x²) is not 1 − x; a square root does not split over a difference.' },
          { latex: '1 - x^2', expr: '1 - x^2', mistake: 'algebra-error', why: 'y² = 1 − x² still needs a square root: y = √(1 − x²).' },
          { latex: '\\sqrt{1 + x^2}', expr: 'sqrt(1 + x^2)', mistake: 'sign-error', why: 'Solving x² + y² = 1 gives y² = 1 − x², not 1 + x².' },
        ],
        correct: 0,
        explanation: 'Solving $x^2 + y^2 = 1$ gives $y = \\pm\\sqrt{1 - x^2}$; the $+$ root is the upper half, one $y$ per $x$.',
        result: { latex: 'y = f(x) = \\sqrt{1 - x^2},\\quad -1 \\le x \\le 1' },
        check: { kind: 'identity', lhs: 'sqrt(1 - x^2)' },
      },
      {
        prompt: "Simplify $1 + (f'(x))^2$.",
        options: [
          { latex: '\\frac{1}{1 - x^2}', expr: '1/(1 - x^2)' },
          { latex: '2 - x^2', expr: '2 - x^2', mistake: 'arclength-f-instead-of-fprime', why: '1 + (√(1 − x²))² = 2 − x² uses f(x), not f′(x) = −x/√(1 − x²).' },
          { latex: '\\frac{1 - 2x^2}{1 - x^2}', expr: '(1 - 2*x^2)/(1 - x^2)', mistake: 'negative-squared-wrong', why: '(−x/√(1 − x²))² = +x²/(1 − x²); the minus sign was kept after squaring.' },
          { latex: '\\frac{1 + x^2}{1 - x^2}', expr: '(1 + x^2)/(1 - x^2)', mistake: 'algebra-error', why: '1 + x²/(1 − x²) needs the common denominator: (1 − x² + x²)/(1 − x²).' },
          { latex: '\\frac{5 - 4x^2}{4 - 4x^2}', expr: '(5 - 4*x^2)/(4 - 4*x^2)', mistake: 'chain-rule-missing', why: 'f′ was taken as 1/(2√(1 − x²)) without the inner derivative −2x.' },
        ],
        correct: 0,
        explanation: "$f'(x) = \\frac{-x}{\\sqrt{1 - x^2}}$, so $1 + \\frac{x^2}{1 - x^2} = \\frac{1 - x^2 + x^2}{1 - x^2} = \\frac{1}{1 - x^2}$.",
        result: { latex: "f'(x) = \\frac{-x}{\\sqrt{1 - x^2}},\\quad 1 + (f'(x))^2 = 1 + \\frac{x^2}{1 - x^2} = \\frac{1}{1 - x^2}" },
        check: { kind: 'identity', lhs: '1 + (-x/sqrt(1 - x^2))^2' },
      },
      {
        prompt: 'Using symmetry, set up the perimeter $P$.',
        options: [
          { latex: 'P = 4\\int_0^1 \\frac{1}{\\sqrt{1 - x^2}}\\,dx', expr: '4*integral(1/sqrt(1 - x^2), x, 0, 1)' },
          { latex: 'P = 2\\int_0^1 \\frac{1}{\\sqrt{1 - x^2}}\\,dx', expr: '2*integral(1/sqrt(1 - x^2), x, 0, 1)', mistake: 'coefficient-mishandled', why: 'From x = 0 to x = 1 the upper semicircle is one quarter of the circle; there are four quarters.' },
          { latex: 'P = 4\\int_{-1}^{1} \\frac{1}{\\sqrt{1 - x^2}}\\,dx', expr: '4*integral(1/sqrt(1 - x^2), x, -1, 1)', mistake: 'coefficient-mishandled', why: 'From −1 to 1 is already the whole upper half; multiplying by 4 counts the circle twice.' },
          { latex: 'P = 4\\int_0^1 \\frac{x}{\\sqrt{1 - x^2}}\\,dx', expr: '4*integral(x/sqrt(1 - x^2), x, 0, 1)', mistake: 'arclength-missing-one', why: 'x/√(1 − x²) is √((f′)²) = |f′|; the 1 under the root was dropped.' },
          { latex: 'P = 4\\int_0^1 \\sqrt{2 - x^2}\\,dx', expr: '4*integral(sqrt(2 - x^2), x, 0, 1)', mistake: 'arclength-f-instead-of-fprime', why: '2 − x² = 1 + f(x)² squares f, not f′.' },
          { latex: 'P = 4\\int_0^1 \\left(1 + \\frac{x}{\\sqrt{1 - x^2}}\\right)dx', expr: '4*integral(1 + x/sqrt(1 - x^2), x, 0, 1)', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √((f′)²); combine 1 + (f′)² = 1/(1 − x²) first.' },
        ],
        correct: 0,
        explanation: 'The arc of $y = \\sqrt{1 - x^2}$ over $[0, 1]$ is a quarter of the circle, and $\\sqrt{\\frac{1}{1 - x^2}} = \\frac{1}{\\sqrt{1 - x^2}}$.',
        result: { latex: 'P = 4\\int_0^1 \\sqrt{\\frac{1}{1 - x^2}}\\,dx = 4\\int_0^1 \\frac{1}{\\sqrt{1 - x^2}}\\,dx' },
        check: { kind: 'value', expected: '2*pi' },
      },
      {
        prompt: 'Evaluate the quarter-arc length $\\int_0^1 \\frac{1}{\\sqrt{1 - x^2}}\\,dx$.',
        options: [
          { latex: '\\frac{\\pi}{2}', expr: 'pi/2' },
          { latex: '\\frac{\\pi}{4}', expr: 'pi/4', mistake: 'inverse-trig-value-wrong', why: 'arcsin 1 = π/2 because sin(π/2) = 1; sin(π/4) = √2/2.' },
          { latex: '\\pi', expr: 'pi', mistake: 'inverse-trig-value-wrong', why: 'arcsin 1 = π/2, not π; sin π = 0.' },
          { latex: '-\\frac{\\pi}{2}', expr: '-pi/2', mistake: 'ftc-order-swapped', why: 'This is arcsin 0 − arcsin 1; subtract in the order F(1) − F(0).' },
          { latex: '1', expr: '1', mistake: 'u-choice-wrong', why: 'Using u = 1 − x² gives −√(1 − x²), but du = −2x dx needs a factor x that this integrand does not have.' },
        ],
        correct: 0,
        explanation: '$\\arcsin x\\Big|_0^1 = \\arcsin 1 - \\arcsin 0 = \\frac{\\pi}{2}$, so each quarter-arc has length $\\frac{\\pi}{2}$.',
        result: { latex: '\\int_0^1 \\frac{dx}{\\sqrt{1 - x^2}} = \\arcsin x\\Big|_0^1 = \\frac{\\pi}{2},\\qquad P = 4\\cdot\\frac{\\pi}{2} = 2\\pi' },
        check: { kind: 'value', expected: 'pi/2' },
      },
    ],
    final: {
      latex: 'P = 2\\pi',
      expr: '2*pi',
      check: { kind: 'definite-integral', integrand: '4*sqrt(1 + (-x/sqrt(1 - x^2))^2)', lower: '0', upper: '1' },
      recap: "The circle is not one function, so use the upper semicircle and symmetry; $1 + (f')^2 = \\frac{1}{1 - x^2}$, and four quarter-arcs of length $\\frac{\\pi}{2}$ give $2\\pi$.",
    },
  },
  {
    id: 'al-s-05',
    topic: 'arc-length',
    title: 'A log-sine curve',
    difficulty: 2,
    statement: { text: 'Find the exact length of the curve', latex: 'y = \\frac{1}{2}\\ln(\\sin 2x),\\quad \\frac{\\pi}{8} \\le x \\le \\frac{\\pi}{6}' },
    domain: [0.3, 0.6],
    steps: [
      {
        prompt: "Find $f'(x)$.",
        options: [
          { latex: '\\cot(2x)', expr: 'cot(2*x)' },
          { latex: '\\frac{1}{2}\\cot(2x)', expr: 'cot(2*x)/2', mistake: 'chain-rule-missing', why: 'd/dx sin 2x = 2cos 2x; the inner derivative 2 was dropped.' },
          { latex: '2\\cot(2x)', expr: '2*cot(2*x)', mistake: 'coefficient-mishandled', why: 'The ½ in front of ln was dropped: ½·(2cos 2x/sin 2x) = cot 2x.' },
          { latex: '\\tan(2x)', expr: 'tan(2*x)', mistake: 'log-derivative-wrong', why: 'd/dx ln u = u′/u = 2cos 2x/sin 2x; flipping it to u/u′ gives tan.' },
          { latex: '\\cos(2x)', expr: 'cos(2*x)', mistake: 'log-derivative-wrong', why: 'd/dx ln u = u′/u; the division by u = sin 2x is missing.' },
        ],
        correct: 0,
        explanation: "$f'(x) = \\frac{1}{2}\\cdot\\frac{2\\cos 2x}{\\sin 2x} = \\cot 2x$.",
        result: { latex: "f'(x) = \\frac{1}{2}\\cdot\\frac{2\\cos 2x}{\\sin 2x} = \\cot 2x" },
        check: { kind: 'derivative', of: 'log(sin(2*x))/2' },
      },
      {
        prompt: "Simplify $1 + (f'(x))^2$.",
        options: [
          { latex: '\\csc^2(2x)', expr: 'csc(2*x)^2' },
          { latex: '\\sec^2(2x)', expr: 'sec(2*x)^2', mistake: 'pythagorean-wrong', why: 'The identity is 1 + cot²θ = csc²θ; sec² pairs with tan².' },
          { latex: '\\cot^2(2x)', expr: 'cot(2*x)^2', mistake: 'arclength-missing-one', why: 'That is (f′)² alone; the 1 was never added.' },
          { latex: '\\csc^2 x', expr: 'csc(x)^2', mistake: 'algebra-error', why: 'The identity keeps the angle: 1 + cot²(2x) = csc²(2x), not csc²x.' },
          { latex: '1 + \\cot(2x)', expr: '1 + cot(2*x)', mistake: 'arclength-not-squared', why: 'f′ = cot 2x was added to 1 without being squared.' },
        ],
        correct: 0,
        explanation: 'Use $1 + \\cot^2\\theta = \\csc^2\\theta$ with $\\theta = 2x$.',
        result: { latex: "1 + (f'(x))^2 = 1 + \\cot^2(2x) = \\csc^2(2x)" },
        check: { kind: 'identity', lhs: '1 + (cos(2*x)/sin(2*x))^2' },
      },
      {
        prompt: 'Why may $\\sqrt{\\csc^2(2x)}$ be replaced by $\\csc(2x)$ here?',
        options: [
          { text: 'On this interval $\\sin 2x > 0$, so $|\\csc 2x| = \\csc 2x$' },
          { text: 'On this interval $\\cos 2x > 0$, so $|\\csc 2x| = \\csc 2x$', mistake: 'abs-sign-on-interval', why: 'csc 2x = 1/sin 2x, so its sign is the sign of sin 2x, not of cos 2x.' },
          { text: 'On this interval $x > 0$, so $|\\csc 2x| = \\csc 2x$', mistake: 'abs-sign-on-interval', why: 'The sign of csc 2x depends on sin 2x, not on the sign of x.' },
          { text: 'On this interval $\\csc^2 2x \\ge 1$, so $|\\csc 2x| = \\csc 2x$', mistake: 'sqrt-square-abs', why: 'csc² 2x ≥ 1 holds wherever it is defined and does not fix the sign of csc 2x.' },
          { text: 'On this interval $\\sqrt{u^2} = u$ applies, so $|\\csc 2x| = \\csc 2x$', mistake: 'sqrt-square-abs', why: '√(u²) = |u|; whether |csc 2x| = csc 2x depends on the sign of sin 2x.' },
        ],
        correct: 0,
        explanation: '$\\sqrt{\\csc^2 2x} = |\\csc 2x|$; with $2x \\in [\\frac{\\pi}{4}, \\frac{\\pi}{3}]$, $\\sin 2x > 0$, so the absolute value can be dropped.',
        result: { text: '$\\sqrt{\\csc^2 2x} = |\\csc 2x| = \\csc 2x$ here, so $L = \\int_{\\pi/8}^{\\pi/6} \\csc(2x)\\,dx$.' },
      },
      {
        prompt: 'Substitute $u = 2x$. What does $L$ become?',
        options: [
          { latex: '\\frac{1}{2}\\int_{\\pi/4}^{\\pi/3} \\csc u\\,du', expr: 'integral(csc(u), u, pi/4, pi/3)/2' },
          { latex: '\\frac{1}{2}\\int_{\\pi/8}^{\\pi/6} \\csc u\\,du', expr: 'integral(csc(u), u, pi/8, pi/6)/2', mistake: 'bounds-not-converted', why: 'The x-limits were kept; they become u = π/4 and u = π/3.' },
          { latex: '2\\int_{\\pi/4}^{\\pi/3} \\csc u\\,du', expr: '2*integral(csc(u), u, pi/4, pi/3)', mistake: 'du-constant-wrong', why: 'du = 2dx gives dx = ½du, not 2du.' },
          { latex: '\\int_{\\pi/4}^{\\pi/3} \\csc u\\,du', expr: 'integral(csc(u), u, pi/4, pi/3)', mistake: 'inner-constant-factor-missing', why: 'dx = ½du; the factor ½ was dropped.' },
          { latex: '\\frac{1}{2}\\int_{\\pi/4}^{\\pi/3} \\csc u\\,dx', expr: 'integral(csc(u), x, pi/4, pi/3)/2', mistake: 'dx-not-replaced', why: 'The differential must become du; dx was left in place.' },
        ],
        correct: 0,
        explanation: '$du = 2\\,dx$, so $dx = \\frac{1}{2}\\,du$; $x = \\frac{\\pi}{8} \\mapsto u = \\frac{\\pi}{4}$ and $x = \\frac{\\pi}{6} \\mapsto u = \\frac{\\pi}{3}$.',
        result: { latex: 'u = 2x,\\ dx = \\frac{1}{2}\\,du:\\quad L = \\frac{1}{2}\\int_{\\pi/4}^{\\pi/3} \\csc u\\,du' },
        check: { kind: 'value', expected: 'log((sqrt(2) + 1)/sqrt(3))/2' },
      },
      {
        prompt: 'Evaluate, using $\\int \\csc u\\,du = \\ln|\\csc u - \\cot u| + C$.',
        options: [
          { latex: '\\frac{1}{2}\\ln\\left(\\frac{\\sqrt{2} + 1}{\\sqrt{3}}\\right)', expr: 'log((sqrt(2) + 1)/sqrt(3))/2' },
          { latex: '\\ln\\left(\\frac{\\sqrt{2} + 1}{\\sqrt{3}}\\right)', expr: 'log((sqrt(2) + 1)/sqrt(3))', mistake: 'inner-constant-factor-missing', why: 'The ½ from dx = ½du was dropped at the end.' },
          { latex: '\\frac{1}{2}\\ln\\left(\\frac{\\sqrt{3}}{\\sqrt{2} + 1}\\right)', expr: 'log(sqrt(3)/(sqrt(2) + 1))/2', mistake: 'ftc-order-swapped', why: 'This is F(π/4) − F(π/3); the length must be F(π/3) − F(π/4) > 0.' },
          { latex: '\\frac{1}{2}\\ln\\left(\\frac{\\sqrt{2} - 1}{\\sqrt{3}}\\right)', expr: 'log((sqrt(2) - 1)/sqrt(3))/2', mistake: 'ftc-not-subtracted', why: 'The two logarithms were added instead of subtracted.' },
          { latex: '\\frac{1}{2}\\ln\\left(\\frac{1}{\\sqrt{3}}\\right)', expr: 'log(1/sqrt(3))/2', mistake: 'ftc-not-subtracted', why: 'Only the upper limit was used; ln(√2 − 1) at u = π/4 must be subtracted.' },
          { latex: '\\frac{1}{2}\\ln\\left(\\frac{\\sqrt{2} + 1}{3}\\right)', expr: 'log((sqrt(2) + 1)/3)/2', mistake: 'arithmetic-error', why: 'csc(π/3) − cot(π/3) = 2/√3 − 1/√3 = 1/√3, not 1/3.' },
        ],
        correct: 0,
        explanation: 'At $\\frac{\\pi}{3}$: $\\csc - \\cot = \\frac{1}{\\sqrt{3}}$; at $\\frac{\\pi}{4}$: $\\sqrt{2} - 1$; and $\\frac{1/\\sqrt{3}}{\\sqrt{2} - 1} = \\frac{\\sqrt{2} + 1}{\\sqrt{3}}$.',
        result: { latex: 'L = \\frac{1}{2}\\ln|\\csc u - \\cot u|\\Big|_{\\pi/4}^{\\pi/3} = \\frac{1}{2}\\left[\\ln\\frac{1}{\\sqrt{3}} - \\ln(\\sqrt{2} - 1)\\right] = \\frac{1}{2}\\ln\\left(\\frac{\\sqrt{2} + 1}{\\sqrt{3}}\\right)' },
        check: { kind: 'value', expected: 'log((sqrt(2) + 1)/sqrt(3))/2' },
      },
    ],
    final: {
      latex: 'L = \\frac{1}{2}\\ln\\left(\\frac{\\sqrt{2} + 1}{\\sqrt{3}}\\right)',
      expr: 'log((sqrt(2) + 1)/sqrt(3))/2',
      check: { kind: 'definite-integral', integrand: 'sqrt(1 + (cos(2*x)/sin(2*x))^2)', lower: 'pi/8', upper: 'pi/6' },
      recap: "$f' = \\cot 2x$ and $1 + \\cot^2 2x = \\csc^2 2x$; since $\\sin 2x > 0$ on the interval, $\\sqrt{\\csc^2 2x} = \\csc 2x$, and $u = 2x$ brings in a factor $\\frac{1}{2}$.",
    },
  },
  {
    id: 'al-s-06',
    topic: 'arc-length',
    title: 'A log-cosine curve',
    difficulty: 1,
    statement: { text: 'Find the exact length of the curve', latex: 'y = \\ln(\\cos x),\\quad 0 \\le x \\le \\frac{\\pi}{3}' },
    domain: [0.2, 0.9],
    steps: [
      {
        prompt: "Find $f'(x)$.",
        options: [
          { latex: '-\\tan x', expr: '-tan(x)' },
          { latex: '\\tan x', expr: 'tan(x)', mistake: 'sign-error-derivative', why: 'd/dx cos x = −sin x, so f′ = −sin x/cos x = −tan x.' },
          { latex: '\\frac{1}{\\cos x}', expr: '1/cos(x)', mistake: 'chain-rule-missing', why: 'd/dx ln(cos x) needs the inner derivative −sin x; 1/cos x alone drops it.' },
          { latex: '-\\sin x', expr: '-sin(x)', mistake: 'log-derivative-wrong', why: 'd/dx ln u = u′/u; the division by u = cos x is missing.' },
          { latex: '-\\cot x', expr: '-cot(x)', mistake: 'log-derivative-wrong', why: 'd/dx ln u = u′/u, not u/u′.' },
        ],
        correct: 0,
        explanation: "$f'(x) = \\frac{-\\sin x}{\\cos x} = -\\tan x$.",
        result: { latex: "f'(x) = \\frac{-\\sin x}{\\cos x} = -\\tan x" },
        check: { kind: 'derivative', of: 'log(cos(x))' },
      },
      {
        prompt: "Simplify $\\sqrt{1 + (f'(x))^2}$ on $[0, \\frac{\\pi}{3}]$.",
        options: [
          { latex: '\\sec x', expr: 'sec(x)' },
          { latex: '-\\sec x', expr: '-sec(x)', mistake: 'abs-sign-on-interval', why: '√(sec²x) = |sec x|, and cos x > 0 on [0, π/3], so no minus sign.' },
          { latex: '\\sec^2 x', expr: 'sec(x)^2', mistake: 'arclength-no-root', why: '1 + tan²x = sec²x is the radicand; its square root is sec x.' },
          { latex: '1 + \\tan x', expr: '1 + tan(x)', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √(tan²x); use 1 + tan²x = sec²x instead.' },
          { latex: '\\tan x', expr: 'tan(x)', mistake: 'arclength-missing-one', why: 'Without the 1, √(tan²x) = tan x only measures the vertical change.' },
          { latex: '\\csc x', expr: 'csc(x)', mistake: 'pythagorean-wrong', why: 'The identity is 1 + tan²x = sec²x; csc² pairs with cot².' },
        ],
        correct: 0,
        explanation: '$1 + \\tan^2 x = \\sec^2 x$ and $\\sqrt{\\sec^2 x} = |\\sec x| = \\sec x$ because $\\cos x > 0$ on $[0, \\frac{\\pi}{3}]$.',
        result: { latex: '\\sqrt{1 + \\tan^2 x} = \\sqrt{\\sec^2 x} = |\\sec x| = \\sec x' },
        check: { kind: 'identity', lhs: 'sqrt(1 + (-tan(x))^2)' },
      },
      {
        prompt: 'Write the arc length as an integral.',
        options: [
          { latex: 'L = \\int_0^{\\pi/3} \\sec x\\,dx', expr: 'integral(sec(x), x, 0, pi/3)' },
          { latex: 'L = \\int_0^{-\\ln 2} \\sec x\\,dx', expr: 'integral(sec(x), x, 0, -log(2))', mistake: 'arclength-variable-mismatch', why: '0 and −ln 2 are the y-values of the endpoints; the dx integral runs from x = 0 to x = π/3.' },
          { latex: 'L = \\int_0^{\\pi/3} \\sec^2 x\\,dx', expr: 'integral(sec(x)^2, x, 0, pi/3)', mistake: 'arclength-no-root', why: 'sec²x is the radicand 1 + tan²x; the root is sec x.' },
          { latex: 'L = \\int_0^{\\pi/3} \\tan x\\,dx', expr: 'integral(tan(x), x, 0, pi/3)', mistake: 'arclength-missing-one', why: 'Without the 1, the integrand only measures the vertical change.' },
          { latex: 'L = \\int_0^{\\pi/3} \\sqrt{1 + \\ln^2(\\cos x)}\\,dx', expr: 'integral(sqrt(1 + log(cos(x))^2), x, 0, pi/3)', mistake: 'arclength-f-instead-of-fprime', why: 'This squares f(x) = ln(cos x) instead of f′(x) = −tan x.' },
        ],
        correct: 0,
        explanation: 'Use the simplified integrand $\\sec x$ with the $x$-limits $0$ and $\\frac{\\pi}{3}$.',
        result: { latex: 'L = \\int_0^{\\pi/3} \\sec x\\,dx' },
        check: { kind: 'value', expected: 'log(2 + sqrt(3))' },
      },
      {
        prompt: 'Evaluate, using $\\int \\sec x\\,dx = \\ln|\\sec x + \\tan x| + C$.',
        options: [
          { latex: '\\ln(2 + \\sqrt{3})', expr: 'log(2 + sqrt(3))' },
          { latex: '\\ln(2 - \\sqrt{3})', expr: 'log(2 - sqrt(3))', mistake: 'sec-antiderivative-wrong', why: '∫sec x dx = ln|sec x + tan x| + C; the minus version gives a negative "length".' },
          { latex: '\\ln 2', expr: 'log(2)', mistake: 'sec-antiderivative-wrong', why: 'ln|sec x| alone is not an antiderivative of sec x (its derivative is tan x).' },
          { latex: '2\\sqrt{3}', expr: '2*sqrt(3)', mistake: 'trig-antiderivative-swapped', why: 'sec x tan x is the derivative of sec x, not an antiderivative of it.' },
          { latex: '\\sqrt{3}', expr: 'sqrt(3)', mistake: 'trig-antiderivative-swapped', why: 'tan x is an antiderivative of sec²x, not of sec x.' },
          { latex: '\\ln\\left(\\frac{2 + \\sqrt{3}}{2}\\right)', expr: 'log((2 + sqrt(3))/2)', mistake: 'arithmetic-error', why: 'At x = 0, sec 0 + tan 0 = 1 + 0 = 1 and ln 1 = 0; using tan 0 = 1 subtracts ln 2.' },
        ],
        correct: 0,
        explanation: '$\\ln|\\sec x + \\tan x|\\Big|_0^{\\pi/3} = \\ln(2 + \\sqrt{3}) - \\ln(1 + 0) = \\ln(2 + \\sqrt{3})$.',
        result: { latex: 'L = \\ln|\\sec x + \\tan x|\\Big|_0^{\\pi/3} = \\ln(2 + \\sqrt{3}) - \\ln 1 = \\ln(2 + \\sqrt{3}) \\approx 1.317' },
        check: { kind: 'value', expected: 'log(2 + sqrt(3))' },
      },
    ],
    final: {
      latex: 'L = \\ln(2 + \\sqrt{3})',
      expr: 'log(2 + sqrt(3))',
      check: { kind: 'definite-integral', integrand: 'sqrt(1 + (-sin(x)/cos(x))^2)', lower: '0', upper: 'pi/3' },
      recap: "$f' = -\\tan x$ and $1 + \\tan^2 x = \\sec^2 x$; because $\\sec x > 0$ on $[0, \\frac{\\pi}{3}]$, $L = \\int_0^{\\pi/3} \\sec x\\,dx = \\ln(2 + \\sqrt{3})$.",
    },
  },
  {
    id: 'al-s-07',
    topic: 'arc-length',
    title: 'An exponential curve x = g(y)',
    difficulty: 2,
    statement: { text: 'Find the length of the curve', latex: 'x = e^{y} + \\frac{1}{4}e^{-y},\\quad 0 \\le y \\le 1' },
    variable: 'y',
    steps: [
      {
        prompt: 'Which setup fits this curve?',
        options: [
          { text: "$L = \\int_0^1 \\sqrt{1 + (g'(y))^2}\\,dy$, since the curve is $x = g(y)$ with $y$-limits" },
          { text: "$L = \\int_0^1 \\sqrt{1 + \\left(\\frac{1}{g'(y)}\\right)^2}\\,dy$, using the slope $\\frac{dy}{dx} = \\frac{1}{g'(y)}$", mistake: 'arclength-variable-mismatch', why: 'In a dy integral the root needs dx/dy = g′(y); the slope dy/dx = 1/g′(y) belongs to the dx formula.' },
          { text: "$L = \\int_{5/4}^{e + 1/(4e)} \\sqrt{1 + (g'(y))^2}\\,dy$, using the $x$-values as limits", mistake: 'arclength-variable-mismatch', why: 'A dy integral runs over the y-values 0 to 1, not the x-values of the endpoints.' },
          { text: '$L = \\int_0^1 \\sqrt{1 + (g(y))^2}\\,dy$, with $g$ itself in the root', mistake: 'arclength-f-instead-of-fprime', why: 'The formula squares the derivative g′(y), not g(y).' },
          { text: "$L = \\int_0^1 \\sqrt{1 + (g'(y))^2}\\,dx$, keeping the usual $dx$", mistake: 'dx-dy-mismatch', why: 'The integrand and limits are in y, so the differential must be dy.' },
        ],
        correct: 0,
        explanation: 'The curve is already solved for $x$ as a function of $y$, so Theorem 5.2 applies directly with $0 \\le y \\le 1$.',
        result: { text: "Integrate in $y$: $L = \\int_0^1 \\sqrt{1 + (g'(y))^2}\\,dy$ with $g(y) = e^{y} + \\frac{1}{4}e^{-y}$." },
      },
      {
        prompt: "Find $g'(y)$.",
        options: [
          { latex: 'e^{y} - \\frac{1}{4}e^{-y}', expr: 'exp(y) - exp(-y)/4' },
          { latex: 'e^{y} + \\frac{1}{4}e^{-y}', expr: 'exp(y) + exp(-y)/4', mistake: 'chain-rule-missing', why: 'd/dy e^{−y} = −e^{−y}; the inner derivative −1 was dropped.' },
          { latex: 'ye^{y - 1} - \\frac{1}{4}e^{-y}', expr: 'y*exp(y - 1) - exp(-y)/4', mistake: 'exponential-as-power', why: 'e^y is not a power of y; d/dy e^y = e^y.' },
          { latex: 'e^{y} - 1', expr: 'exp(y) - 1', mistake: 'quotient-rule-denominator', why: 'As 1/(4e^y), the quotient rule needs (4e^y)² = 16e^{2y} in the denominator; using 4e^y gives −1.' },
          { latex: 'e^{y} - e^{-y}', expr: 'exp(y) - exp(-y)', mistake: 'coefficient-mishandled', why: 'The constant ¼ must stay: d/dy(¼e^{−y}) = −¼e^{−y}.' },
        ],
        correct: 0,
        explanation: "$\\frac{d}{dy}e^{y} = e^{y}$ and $\\frac{d}{dy}\\left(\\frac{1}{4}e^{-y}\\right) = -\\frac{1}{4}e^{-y}$.",
        result: { latex: "g'(y) = e^{y} - \\frac{1}{4}e^{-y}" },
        check: { kind: 'derivative', of: 'exp(y) + exp(-y)/4' },
      },
      {
        prompt: "Simplify $1 + (g'(y))^2$.",
        options: [
          { latex: 'e^{2y} + \\frac{1}{2} + \\frac{1}{16}e^{-2y}', expr: 'exp(2*y) + 1/2 + exp(-2*y)/16' },
          { latex: 'e^{2y} - \\frac{1}{2} + \\frac{1}{16}e^{-2y}', expr: 'exp(2*y) - 1/2 + exp(-2*y)/16', mistake: 'arclength-missing-one', why: 'That is (g′)² alone; adding the 1 turns −½ into +½.' },
          { latex: 'e^{2y} + 1 + \\frac{1}{16}e^{-2y}', expr: 'exp(2*y) + 1 + exp(-2*y)/16', mistake: 'algebra-error', why: 'The cross term 2·e^y·(−¼e^{−y}) = −½ was dropped when squaring.' },
          { latex: 'e^{2y} + \\frac{1}{2} + \\frac{1}{4}e^{-2y}', expr: 'exp(2*y) + 1/2 + exp(-2*y)/4', mistake: 'coefficient-mishandled', why: '(¼e^{−y})² = (1/16)e^{−2y}; the ¼ was not squared.' },
          { latex: 'e^{2y} + \\frac{3}{2} + \\frac{1}{16}e^{-2y}', expr: 'exp(2*y) + 3/2 + exp(-2*y)/16', mistake: 'sign-error', why: 'The cross term is 2·e^y·(−¼e^{−y}) = −½, not +½.' },
        ],
        correct: 0,
        explanation: '$(g\')^2 = e^{2y} - \\frac{1}{2} + \\frac{1}{16}e^{-2y}$; adding 1 gives $+\\frac{1}{2}$ in the middle.',
        result: { latex: "1 + (g'(y))^2 = 1 + e^{2y} - \\frac{1}{2} + \\frac{1}{16}e^{-2y} = e^{2y} + \\frac{1}{2} + \\frac{1}{16}e^{-2y}" },
        check: { kind: 'identity', lhs: '1 + (exp(y) - exp(-y)/4)^2' },
      },
      {
        prompt: 'Recognize a perfect square and take the square root.',
        options: [
          { latex: 'e^{y} + \\frac{1}{4}e^{-y}', expr: 'exp(y) + exp(-y)/4' },
          { latex: 'e^{y} - \\frac{1}{4}e^{-y}', expr: 'exp(y) - exp(-y)/4', mistake: 'sign-error', why: '(e^y − ¼e^{−y})² has middle term −½; the radicand has +½.' },
          { latex: 'e^{y} + \\frac{1}{16}e^{-y}', expr: 'exp(y) + exp(-y)/16', mistake: 'sqrt-constant-not-rooted', why: '√((1/16)e^{−2y}) = ¼e^{−y}; the 1/16 was not square-rooted.' },
          { latex: 'e^{2y} + \\frac{1}{4}e^{-2y}', expr: 'exp(2*y) + exp(-2*y)/4', mistake: 'formula-wrong-power', why: '√(e^{2y}) = e^y; the exponent must be halved.' },
          { latex: '\\left(e^{y} + \\frac{1}{4}e^{-y}\\right)^2', expr: '(exp(y) + exp(-y)/4)^2', mistake: 'arclength-no-root', why: 'This is the radicand itself; the square root was never taken.' },
          { latex: '1 + e^{y} - \\frac{1}{4}e^{-y}', expr: '1 + exp(y) - exp(-y)/4', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √((g′)²); a square root does not split over a sum.' },
        ],
        correct: 0,
        explanation: '$e^{2y} + \\frac{1}{2} + \\frac{1}{16}e^{-2y} = \\left(e^{y} + \\frac{1}{4}e^{-y}\\right)^2$, and the base is positive.',
        result: { latex: "\\sqrt{1 + (g'(y))^2} = \\sqrt{\\left(e^{y} + \\frac{1}{4}e^{-y}\\right)^2} = e^{y} + \\frac{1}{4}e^{-y}" },
        check: { kind: 'identity', lhs: 'sqrt(exp(2*y) + 1/2 + exp(-2*y)/16)' },
      },
      {
        prompt: 'Evaluate $L = \\int_0^1 \\left(e^{y} + \\frac{1}{4}e^{-y}\\right)dy$.',
        options: [
          { latex: 'e - \\frac{1}{4e} - \\frac{3}{4}', expr: 'e - 1/(4*e) - 3/4' },
          { latex: 'e + \\frac{1}{4e} - \\frac{5}{4}', expr: 'e + 1/(4*e) - 5/4', mistake: 'exp-antiderivative-wrong', why: '∫e^{−y}dy = −e^{−y}; using +¼e^{−y} as the antiderivative flips that term.' },
          { latex: 'e - \\frac{1}{4e}', expr: 'e - 1/(4*e)', mistake: 'ftc-not-subtracted', why: 'Only the upper limit was used; F(0) = 1 − ¼ = ¾ must be subtracted.' },
          { latex: 'e - \\frac{1}{4e} - \\frac{5}{4}', expr: 'e - 1/(4*e) - 5/4', mistake: 'sign-error', why: 'F(0) = e⁰ − ¼e⁰ = ¾; evaluating it as 1 + ¼ = 5/4 is a sign slip.' },
          { latex: '\\frac{3}{4} - e + \\frac{1}{4e}', expr: '3/4 - e + 1/(4*e)', mistake: 'ftc-order-swapped', why: 'This is F(0) − F(1); the length is F(1) − F(0) > 0.' },
        ],
        correct: 0,
        explanation: '$\\left[e^{y} - \\frac{1}{4}e^{-y}\\right]_0^1 = \\left(e - \\frac{1}{4e}\\right) - \\left(1 - \\frac{1}{4}\\right)$.',
        result: { latex: 'L = \\left[e^{y} - \\frac{1}{4}e^{-y}\\right]_0^1 = \\left(e - \\frac{1}{4e}\\right) - \\frac{3}{4} = e - \\frac{1}{4e} - \\frac{3}{4} \\approx 1.876' },
        check: { kind: 'value', expected: 'e - 1/(4*e) - 3/4' },
      },
    ],
    final: {
      latex: 'L = e - \\frac{1}{4e} - \\frac{3}{4}',
      expr: 'e - 1/(4*e) - 3/4',
      check: { kind: 'definite-integral', integrand: 'sqrt(1 + (exp(y) - exp(-y)/4)^2)', lower: '0', upper: '1' },
      recap: "Adding 1 flips $-\\frac{1}{2}$ to $+\\frac{1}{2}$, so $1 + (g')^2 = \\left(e^{y} + \\frac{1}{4}e^{-y}\\right)^2$ and the integrand is simply $e^{y} + \\frac{1}{4}e^{-y}$.",
    },
  },
  {
    id: 'al-s-08',
    topic: 'arc-length',
    title: 'Set up an arc-length integral',
    difficulty: 1,
    statement: { text: 'Set up (do not evaluate) an integral for the arc length of', latex: 'f(x) = (x^4 - 1)^{3/2},\\quad 1 \\le x \\le 3' },
    domain: [1.05, 2],
    steps: [
      {
        prompt: "Find $f'(x)$.",
        options: [
          { latex: '6x^3(x^4 - 1)^{1/2}', expr: '6*x^3*(x^4 - 1)^(1/2)' },
          { latex: '\\frac{3}{2}(x^4 - 1)^{1/2}', expr: '3/2*(x^4 - 1)^(1/2)', mistake: 'chain-rule-missing', why: 'The inner derivative 4x³ of x⁴ − 1 was dropped.' },
          { latex: '6x^3(x^4 - 1)^{3/2}', expr: '6*x^3*(x^4 - 1)^(3/2)', mistake: 'power-rule-exponent', why: 'The outer exponent 3/2 must drop to 1/2.' },
          { latex: '4x^3(x^4 - 1)^{1/2}', expr: '4*x^3*(x^4 - 1)^(1/2)', mistake: 'power-rule-coefficient', why: 'The factor 3/2 from the power rule was dropped: (3/2)·4x³ = 6x³.' },
          { latex: '6x^3', expr: '6*x^3', mistake: 'chain-rule-outer-wrong', why: 'Only the constants and the inner derivative were kept; the factor (x⁴ − 1)^{1/2} from the outer derivative is missing.' },
        ],
        correct: 0,
        explanation: "Chain rule: $\\frac{3}{2}(x^4 - 1)^{1/2}\\cdot 4x^3 = 6x^3(x^4 - 1)^{1/2}$.",
        result: { latex: "f'(x) = \\frac{3}{2}(x^4 - 1)^{1/2}\\cdot 4x^3 = 6x^3\\sqrt{x^4 - 1}" },
        check: { kind: 'derivative', of: '(x^4 - 1)^(3/2)' },
      },
      {
        prompt: "Compute $(f'(x))^2$.",
        options: [
          { latex: '36x^6(x^4 - 1)', expr: '36*x^6*(x^4 - 1)' },
          { latex: '6x^6(x^4 - 1)', expr: '6*x^6*(x^4 - 1)', mistake: 'coefficient-mishandled', why: '(6x³)² = 36x⁶; the 6 was not squared.' },
          { latex: '36x^6(x^4 - 1)^2', expr: '36*x^6*(x^4 - 1)^2', mistake: 'formula-wrong-power', why: '((x⁴ − 1)^{1/2})² = x⁴ − 1, not (x⁴ − 1)².' },
          { latex: '36x^9(x^4 - 1)', expr: '36*x^9*(x^4 - 1)', mistake: 'exponent-arithmetic', why: '(x³)² = x⁶: when a power is squared the exponents multiply, 3·2 = 6.' },
          { latex: '6x^3(x^4 - 1)^{1/2}', expr: '6*x^3*(x^4 - 1)^(1/2)', mistake: 'arclength-not-squared', why: 'That is f′(x) itself; it still has to be squared.' },
        ],
        correct: 0,
        explanation: '$(6x^3)^2 = 36x^6$ and $\\left((x^4 - 1)^{1/2}\\right)^2 = x^4 - 1$.',
        result: { latex: "(f'(x))^2 = 36x^6(x^4 - 1)" },
        check: { kind: 'identity', lhs: '(6*x^3*(x^4 - 1)^(1/2))^2' },
      },
      {
        prompt: 'Set up the arc-length integral.',
        options: [
          { latex: 'L = \\int_1^3 \\sqrt{1 + 36x^6(x^4 - 1)}\\,dx', expr: 'integral(sqrt(1 + 36*x^6*(x^4 - 1)), x, 1, 3)' },
          { latex: 'L = \\int_1^3 \\sqrt{36x^6(x^4 - 1)}\\,dx', expr: 'integral(sqrt(36*x^6*(x^4 - 1)), x, 1, 3)', mistake: 'arclength-missing-one', why: 'The 1 under the root is missing; this only measures the vertical change.' },
          { latex: 'L = \\int_1^3 \\left(1 + 36x^6(x^4 - 1)\\right)dx', expr: 'integral(1 + 36*x^6*(x^4 - 1), x, 1, 3)', mistake: 'arclength-no-root', why: 'The square root around 1 + (f′)² is missing.' },
          { latex: 'L = \\int_1^3 \\sqrt{1 + (x^4 - 1)^3}\\,dx', expr: 'integral(sqrt(1 + (x^4 - 1)^3), x, 1, 3)', mistake: 'arclength-f-instead-of-fprime', why: 'This squares f(x) = (x⁴ − 1)^{3/2} instead of f′(x).' },
          { latex: 'L = \\int_1^3 \\left(1 + 6x^3\\sqrt{x^4 - 1}\\right)dx', expr: 'integral(1 + 6*x^3*sqrt(x^4 - 1), x, 1, 3)', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √((f′)²); a square root does not split over a sum.' },
          { latex: 'L = \\int_1^3 \\sqrt{1 + 6x^3(x^4 - 1)^{1/2}}\\,dx', expr: 'integral(sqrt(1 + 6*x^3*(x^4 - 1)^(1/2)), x, 1, 3)', mistake: 'arclength-not-squared', why: 'f′(x) was placed under the root without being squared.' },
        ],
        correct: 0,
        explanation: 'Theorem 5.1 with $(f\')^2 = 36x^6(x^4 - 1)$ and the $x$-limits 1 and 3.',
        result: { latex: 'L = \\int_1^3 \\sqrt{1 + 36x^6(x^4 - 1)}\\,dx = \\int_1^3 \\sqrt{36x^{10} - 36x^6 + 1}\\,dx' },
        check: { kind: 'value', expected: 'integral(sqrt(1 + (3/2*(x^4 - 1)^(1/2)*4*x^3)^2), x, 1, 3)' },
      },
    ],
    final: {
      latex: 'L = \\int_1^3 \\sqrt{1 + 36x^6(x^4 - 1)}\\,dx',
      expr: 'integral(sqrt(1 + 36*x^6*(x^4 - 1)), x, 1, 3)',
      check: { kind: 'value', expected: 'integral(sqrt(1 + (3/2*(x^4 - 1)^(1/2)*4*x^3)^2), x, 1, 3)' },
      recap: "Differentiate with the chain rule, square $f'$, add 1, and keep the $x$-limits; this radicand is not a perfect square, so the setup itself is the answer.",
    },
  },
  {
    id: 'al-s-09',
    topic: 'arc-length',
    title: 'Length of the astroid',
    difficulty: 2,
    statement: { text: 'Find the total length of the astroid $x^{2/3} + y^{2/3} = 1$ using its first-quadrant arc and symmetry.' },
    domain: [0.1, 0.9],
    steps: [
      {
        prompt: 'Solve for $y$ on the first-quadrant arc, $0 \\le x \\le 1$.',
        options: [
          { latex: '(1 - x^{2/3})^{3/2}', expr: '(1 - x^(2/3))^(3/2)' },
          { latex: '(1 - x^{2/3})^{2/3}', expr: '(1 - x^(2/3))^(2/3)', mistake: 'exponent-arithmetic', why: 'To undo the power 2/3 on y, raise both sides to 3/2, not 2/3.' },
          { latex: '1 - x', expr: '1 - x', mistake: 'sqrt-of-sum-split', why: 'Raising each term to the 3/2 power separately is invalid: (a + b)^{3/2} ≠ a^{3/2} + b^{3/2}.' },
          { latex: '1 - x^{2/3}', expr: '1 - x^(2/3)', mistake: 'algebra-error', why: 'That is y^{2/3}; it still has to be raised to the 3/2 power.' },
          { latex: '(1 - x^{3/2})^{2/3}', expr: '(1 - x^(3/2))^(2/3)', mistake: 'inverse-function-wrong', why: 'The exponents were swapped: y^{2/3} = 1 − x^{2/3} gives y = (1 − x^{2/3})^{3/2}.' },
        ],
        correct: 0,
        explanation: '$y^{2/3} = 1 - x^{2/3}$, so $y = (1 - x^{2/3})^{3/2}$ for $y \\ge 0$.',
        result: { latex: 'y^{2/3} = 1 - x^{2/3}\\ \\Rightarrow\\ y = f(x) = (1 - x^{2/3})^{3/2}' },
        check: { kind: 'identity', lhs: '((1 - x^(2/3))^(1/2))^3' },
      },
      {
        prompt: "Find $f'(x)$.",
        options: [
          { latex: '-x^{-1/3}(1 - x^{2/3})^{1/2}', expr: '-x^(-1/3)*(1 - x^(2/3))^(1/2)' },
          { latex: '\\frac{3}{2}(1 - x^{2/3})^{1/2}', expr: '3/2*(1 - x^(2/3))^(1/2)', mistake: 'chain-rule-missing', why: 'The inner derivative −(2/3)x^{−1/3} of 1 − x^{2/3} was dropped.' },
          { latex: 'x^{-1/3}(1 - x^{2/3})^{1/2}', expr: 'x^(-1/3)*(1 - x^(2/3))^(1/2)', mistake: 'sign-error', why: 'd/dx(1 − x^{2/3}) = −(2/3)x^{−1/3}; the minus sign was lost.' },
          { latex: '-\\frac{3}{2}x^{-1/3}(1 - x^{2/3})^{1/2}', expr: '-3/2*x^(-1/3)*(1 - x^(2/3))^(1/2)', mistake: 'power-rule-coefficient', why: 'd/dx x^{2/3} = (2/3)x^{−1/3}; the factor 2/3 was dropped.' },
          { latex: '-x^{-1/3}(1 - x^{2/3})^{3/2}', expr: '-x^(-1/3)*(1 - x^(2/3))^(3/2)', mistake: 'power-rule-exponent', why: 'The outer exponent 3/2 must drop to 1/2.' },
        ],
        correct: 0,
        explanation: "$\\frac{3}{2}(1 - x^{2/3})^{1/2}\\cdot\\left(-\\frac{2}{3}x^{-1/3}\\right) = -x^{-1/3}(1 - x^{2/3})^{1/2}$.",
        result: { latex: "f'(x) = \\frac{3}{2}(1 - x^{2/3})^{1/2}\\left(-\\frac{2}{3}x^{-1/3}\\right) = -x^{-1/3}(1 - x^{2/3})^{1/2}" },
        check: { kind: 'derivative', of: '(1 - x^(2/3))^(3/2)' },
      },
      {
        prompt: "Simplify the integrand $\\sqrt{1 + (f'(x))^2}$.",
        options: [
          { latex: 'x^{-1/3}', expr: 'x^(-1/3)' },
          { latex: 'x^{-2/3}', expr: 'x^(-2/3)', mistake: 'arclength-no-root', why: 'x^{−2/3} is 1 + (f′)²; the square root still has to be taken.' },
          { latex: '\\sqrt{x^{-2/3} - 1}', expr: 'sqrt(x^(-2/3) - 1)', mistake: 'arclength-missing-one', why: 'x^{−2/3} − 1 is (f′)²; the 1 was never added.' },
          { latex: '1 + x^{-1/3}\\sqrt{1 - x^{2/3}}', expr: '1 + x^(-1/3)*sqrt(1 - x^(2/3))', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √((f′)²) = 1 + |f′|; a square root does not split over a sum.' },
          { latex: '\\sqrt{\\frac{13}{4} - \\frac{9}{4}x^{2/3}}', expr: 'sqrt(13/4 - 9/4*x^(2/3))', mistake: 'chain-rule-missing', why: 'This uses f′ = (3/2)(1 − x^{2/3})^{1/2}, which lacks the inner derivative.' },
          { latex: '\\sqrt{1 + x^{-2/3}}', expr: 'sqrt(1 + x^(-2/3))', mistake: 'algebra-error', why: 'x^{−2/3}(1 − x^{2/3}) = x^{−2/3} − 1; the factor (1 − x^{2/3}) was not distributed.' },
        ],
        correct: 0,
        explanation: "$(f')^2 = x^{-2/3}(1 - x^{2/3}) = x^{-2/3} - 1$, so $1 + (f')^2 = x^{-2/3}$, whose square root is $x^{-1/3}$ for $x > 0$.",
        result: { latex: "\\sqrt{1 + (f'(x))^2} = \\sqrt{1 + x^{-2/3} - 1} = \\sqrt{x^{-2/3}} = x^{-1/3}" },
        check: { kind: 'identity', lhs: 'sqrt(1 + (-(x^(-1/3))*(1 - x^(2/3))^(1/2))^2)' },
      },
      {
        prompt: 'Set up the total length using symmetry.',
        options: [
          { latex: 'L = 4\\int_0^1 x^{-1/3}\\,dx', expr: '4*integral(x^(-1/3), x, 0, 1)' },
          { latex: 'L = \\int_0^1 x^{-1/3}\\,dx', expr: 'integral(x^(-1/3), x, 0, 1)', mistake: 'coefficient-mishandled', why: 'That is only the first-quadrant arc; the astroid has four congruent arcs.' },
          { latex: 'L = 4\\int_0^1 x^{-2/3}\\,dx', expr: '4*integral(x^(-2/3), x, 0, 1)', mistake: 'arclength-no-root', why: 'x^{−2/3} is 1 + (f′)²; its square root is x^{−1/3}.' },
          { latex: 'L = 2\\int_0^1 x^{-1/3}\\,dx', expr: '2*integral(x^(-1/3), x, 0, 1)', mistake: 'coefficient-mishandled', why: 'The astroid has four congruent arcs, one per quadrant, not two.' },
          { latex: 'L = 4\\int_0^1 \\sqrt{x^{-2/3} - 1}\\,dx', expr: '4*integral(sqrt(x^(-2/3) - 1), x, 0, 1)', mistake: 'arclength-missing-one', why: 'x^{−2/3} − 1 is (f′)²; the 1 was never added.' },
          { latex: 'L = 4\\int_0^1 \\left(1 + x^{-1/3}\\sqrt{1 - x^{2/3}}\\right)dx', expr: '4*integral(1 + x^(-1/3)*sqrt(1 - x^(2/3)), x, 0, 1)', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √((f′)²); a square root does not split over a sum.' },
        ],
        correct: 0,
        explanation: '$\\sqrt{x^{-2/3}} = x^{-1/3}$ for $x > 0$, and four congruent arcs make up the astroid.',
        result: { latex: 'L = 4\\int_0^1 x^{-1/3}\\,dx' },
        check: { kind: 'value', expected: '6' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '6', expr: '6' },
          { latex: '\\frac{3}{2}', expr: '3/2', mistake: 'coefficient-mishandled', why: '3/2 is one quarter-arc; multiply by 4.' },
          { latex: '\\frac{8}{3}', expr: '8/3', mistake: 'power-rule-int-coefficient', why: '∫x^{−1/3}dx = x^{2/3}/(2/3) = (3/2)x^{2/3}; multiplying by 2/3 instead gives 8/3.' },
          { latex: '4', expr: '4', mistake: 'power-rule-int-coefficient', why: 'The antiderivative x^{2/3} must be divided by the new exponent 2/3.' },
          { latex: '12', expr: '12', mistake: 'arclength-no-root', why: '4∫₀¹x^{−2/3}dx = 12 integrates 1 + (f′)² without the square root.' },
        ],
        correct: 0,
        explanation: '$4\\cdot\\frac{3}{2}x^{2/3}\\Big|_0^1 = 4\\cdot\\frac{3}{2} = 6$.',
        result: { latex: 'L = 4\\cdot\\frac{3}{2}x^{2/3}\\Big|_0^1 = 6' },
        check: { kind: 'value', expected: '6' },
      },
    ],
    final: {
      latex: 'L = 6',
      expr: '6',
      check: { kind: 'definite-integral', integrand: '4*sqrt(1 + (-(x^(-1/3))*(1 - x^(2/3))^(1/2))^2)', lower: '0', upper: '1' },
      recap: "On the first-quadrant arc $1 + (f')^2$ collapses to $x^{-2/3}$, so each quarter has length $\\int_0^1 x^{-1/3}\\,dx = \\frac{3}{2}$ (the integrand is unbounded at $x = 0$, but the integral converges); four arcs give 6.",
    },
  },
  {
    id: 'al-s-10',
    topic: 'arc-length',
    title: 'Completing the square under the root',
    difficulty: 2,
    statement: { text: 'Find the exact length of the curve', latex: 'y = \\frac{1}{3}(x^2 + 2)^{3/2},\\quad 0 \\le x \\le 1' },
    steps: [
      {
        prompt: "Find $f'(x)$.",
        options: [
          { latex: 'x(x^2 + 2)^{1/2}', expr: 'x*(x^2 + 2)^(1/2)' },
          { latex: '\\frac{1}{2}(x^2 + 2)^{1/2}', expr: '(x^2 + 2)^(1/2)/2', mistake: 'chain-rule-missing', why: 'The inner derivative 2x of x² + 2 was dropped.' },
          { latex: 'x(x^2 + 2)^{3/2}', expr: 'x*(x^2 + 2)^(3/2)', mistake: 'power-rule-exponent', why: 'The exponent 3/2 must drop to 1/2.' },
          { latex: '3x(x^2 + 2)^{1/2}', expr: '3*x*(x^2 + 2)^(1/2)', mistake: 'coefficient-mishandled', why: 'The ⅓ in front was dropped, leaving (3/2)·2x(x² + 2)^{1/2} = 3x(x² + 2)^{1/2}; with it, ⅓·3x = x.' },
          { latex: '\\frac{2}{3}x(x^2 + 2)^{1/2}', expr: '2/3*x*(x^2 + 2)^(1/2)', mistake: 'power-rule-coefficient', why: 'The exponent 3/2 was not brought down: ⅓·(3/2)·2x = x, not ⅔x.' },
        ],
        correct: 0,
        explanation: "$\\frac{1}{3}\\cdot\\frac{3}{2}(x^2 + 2)^{1/2}\\cdot 2x = x\\sqrt{x^2 + 2}$.",
        result: { latex: "f'(x) = \\frac{1}{3}\\cdot\\frac{3}{2}(x^2 + 2)^{1/2}\\cdot 2x = x\\sqrt{x^2 + 2}" },
        check: { kind: 'derivative', of: '(x^2 + 2)^(3/2)/3' },
      },
      {
        prompt: "Simplify $1 + (f'(x))^2$.",
        options: [
          { latex: '(x^2 + 1)^2', expr: '(x^2 + 1)^2' },
          { latex: 'x^4 + 2x^2', expr: 'x^4 + 2*x^2', mistake: 'arclength-missing-one', why: 'That is (f′)² alone; the 1 is what completes the square.' },
          { latex: '(x^2 - 1)^2', expr: '(x^2 - 1)^2', mistake: 'sign-error', why: '(x² − 1)² = x⁴ − 2x² + 1; here the middle term is +2x².' },
          { latex: '1 + x^2(x^2 + 2)^2', expr: '1 + x^2*(x^2 + 2)^2', mistake: 'formula-wrong-power', why: '(√(x² + 2))² = x² + 2, not (x² + 2)².' },
          { latex: '\\frac{x^2}{4} + \\frac{3}{2}', expr: 'x^2/4 + 3/2', mistake: 'chain-rule-missing', why: 'This uses f′ = ½√(x² + 2), which lacks the inner derivative 2x.' },
          { latex: '1 + x\\sqrt{x^2 + 2}', expr: '1 + x*sqrt(x^2 + 2)', mistake: 'arclength-not-squared', why: 'f′ was added to 1 without being squared.' },
        ],
        correct: 0,
        explanation: '$1 + x^2(x^2 + 2) = x^4 + 2x^2 + 1 = (x^2 + 1)^2$.',
        result: { latex: "1 + (f'(x))^2 = 1 + x^2(x^2 + 2) = x^4 + 2x^2 + 1 = (x^2 + 1)^2" },
        check: { kind: 'identity', lhs: '1 + (x*sqrt(x^2 + 2))^2' },
      },
      {
        prompt: 'Set up $L$ with the square root removed.',
        options: [
          { latex: 'L = \\int_0^1 \\left(x^2 + 1\\right)dx', expr: 'integral(x^2 + 1, x, 0, 1)' },
          { latex: 'L = \\int_0^1 (x^2 + 1)^2\\,dx', expr: 'integral((x^2 + 1)^2, x, 0, 1)', mistake: 'arclength-no-root', why: 'The square root of the perfect square was never taken.' },
          { latex: 'L = \\int_0^1 x\\sqrt{x^2 + 2}\\,dx', expr: 'integral(x*sqrt(x^2 + 2), x, 0, 1)', mistake: 'arclength-missing-one', why: 'Without the 1, the root of (f′)² is just f′.' },
          { latex: 'L = \\int_0^1 \\left(1 + x\\sqrt{x^2 + 2}\\right)dx', expr: 'integral(1 + x*sqrt(x^2 + 2), x, 0, 1)', mistake: 'sqrt-of-sum-split', why: 'The root was split as √1 + √((f′)²); a square root does not split over a sum.' },
          { latex: 'L = \\int_{2\\sqrt{2}/3}^{\\sqrt{3}} \\left(x^2 + 1\\right)dx', expr: 'integral(x^2 + 1, x, 2*sqrt(2)/3, sqrt(3))', mistake: 'arclength-variable-mismatch', why: 'f(0) = 2√2/3 and f(1) = √3 are y-values; the dx integral runs from x = 0 to x = 1.' },
        ],
        correct: 0,
        explanation: '$\\sqrt{(x^2 + 1)^2} = x^2 + 1$ because $x^2 + 1 > 0$.',
        result: { latex: 'L = \\int_0^1 \\sqrt{(x^2 + 1)^2}\\,dx = \\int_0^1 (x^2 + 1)\\,dx' },
        check: { kind: 'value', expected: '4/3' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '\\frac{4}{3}', expr: '4/3' },
          { latex: '\\frac{1}{3}', expr: '1/3', mistake: 'constant-not-integrated', why: 'Writing ∫(x² + 1)dx = x³/3 + 1 leaves the constant unintegrated: (1/3 + 1) − 1 = 1/3; the 1 integrates to x.' },
          { latex: '\\frac{28}{15}', expr: '28/15', mistake: 'arclength-no-root', why: '∫₀¹(x² + 1)²dx = 1/5 + 2/3 + 1 = 28/15 keeps the square.' },
          { latex: '2', expr: '2', mistake: 'power-rule-int-coefficient', why: '∫x² dx = x³/3; without dividing by 3 the result is 1 + 1 = 2.' },
          { latex: '\\frac{3}{2}', expr: '3/2', mistake: 'power-rule-int-exponent', why: 'The exponent of x² must rise to 3: x³/3, not x²/2.' },
        ],
        correct: 0,
        explanation: '$\\left[\\frac{x^3}{3} + x\\right]_0^1 = \\frac{1}{3} + 1 = \\frac{4}{3}$.',
        result: { latex: 'L = \\left[\\frac{x^3}{3} + x\\right]_0^1 = \\frac{4}{3}' },
        check: { kind: 'value', expected: '4/3' },
      },
    ],
    final: {
      latex: 'L = \\frac{4}{3}',
      expr: '4/3',
      check: { kind: 'definite-integral', integrand: 'sqrt(1 + (x*sqrt(x^2 + 2))^2)', lower: '0', upper: '1' },
      recap: "$(f')^2 = x^4 + 2x^2$, so adding 1 completes the square $(x^2 + 1)^2$ and the root disappears.",
    },
  },
];
