import type { StepProblem } from '../types';

/**
 * Step-Through problems for topic "diff-review" (Lecture 1 "Try it yourself" list: #7, #9, #10a, #10c).
 * Authored by content-author; verified by math-verifier.
 */
export const steps: StepProblem[] = [
  {
    id: 'dr-s-01',
    topic: 'diff-review',
    title: 'Quotient rule with a trig simplification',
    difficulty: 2,
    statement: { text: 'Differentiate and simplify', latex: 'f(x) = \\frac{\\sin x}{1 + \\cos x}' },
    steps: [
      {
        prompt: 'Which rule applies outermost?',
        options: [
          {
            text: 'Product rule with the factors $\\sin x$ and $1 + \\cos x$',
            mistake: 'technique-wrong',
            why: 'The expression is a quotient; the two functions are divided, not multiplied.',
          },
          {
            text: 'Differentiate top and bottom separately: $\\frac{\\cos x}{-\\sin x}$',
            mistake: 'quotient-of-derivatives',
            why: '$\\left(\\frac{f}{g}\\right)\' \\neq \\frac{f\'}{g\'}$; the quotient rule mixes both functions and both derivatives.',
          },
          { text: 'Quotient rule with $f = \\sin x$ (top) and $g = 1 + \\cos x$ (bottom)' },
          {
            text: 'Quotient rule with $f = 1 + \\cos x$ (top) and $g = \\sin x$ (bottom)',
            mistake: 'quotient-rule-order',
            why: 'Swapping the roles differentiates $\\frac{1+\\cos x}{\\sin x}$ instead: the numerator changes sign and the denominator becomes $\\sin^2 x$.',
          },
          {
            text: 'Chain rule with outer function $\\sin u$ and inner function $u = \\frac{x}{1 + \\cos x}$',
            mistake: 'technique-wrong',
            why: '$\\sin x$ is divided by $1 + \\cos x$; sine is not applied to a quotient.',
          },
        ],
        correct: 2,
        explanation: 'One function divided by another: use $\\left(\\frac fg\\right)\' = \\frac{f\'g - fg\'}{g^2}$.',
        result: { latex: 'f = \\sin x,\\quad g = 1 + \\cos x' },
      },
      {
        prompt: "What are $f'$ and $g'$?",
        options: [
          { latex: "f' = \\cos x,\\quad g' = \\sin x", expr: '[cos(x), sin(x)]', mistake: 'sign-error-derivative', why: "$(\\cos x)' = -\\sin x$; the minus sign was dropped." },
          { latex: "f' = \\cos x,\\quad g' = 1 - \\sin x", expr: '[cos(x), 1 - sin(x)]', mistake: 'constant-derivative', why: 'The derivative of the constant $1$ is $0$, not $1$.' },
          { latex: "f' = -\\cos x,\\quad g' = -\\sin x", expr: '[-cos(x), -sin(x)]', mistake: 'trig-derivative-swapped', why: "$(\\sin x)' = +\\cos x$; only the cosine derivative carries a minus sign." },
          { latex: "f' = \\cos x,\\quad g' = -\\sin x", expr: '[cos(x), -sin(x)]' },
          { latex: "f' = -\\cos x,\\quad g' = \\sin x", expr: '[-cos(x), sin(x)]', mistake: 'trig-derivative-swapped', why: "Both signs were swapped: $(\\sin x)' = +\\cos x$ and $(\\cos x)' = -\\sin x$." },
          { latex: "f' = -\\cos x,\\quad g' = 1 - \\sin x", expr: '[-cos(x), 1 - sin(x)]', mistake: 'constant-derivative', why: "Two slips: the constant $1$ was differentiated to $1$ instead of $0$, and $(\\sin x)'$ was given a minus sign." },
        ],
        correct: 3,
        explanation: '$(\\sin x)\' = \\cos x$ and $(1 + \\cos x)\' = 0 - \\sin x$.',
        result: { latex: "f' = \\cos x,\\quad g' = -\\sin x" },
        check: { kind: 'value', expected: '[cos(x), -sin(x)]' },
      },
      {
        prompt: "Assemble the quotient rule $\\frac{f'g - fg'}{g^2}$.",
        options: [
          { latex: '\\frac{\\cos x(1+\\cos x) - \\sin x(-\\sin x)}{(1+\\cos x)^2}', expr: '(cos(x)*(1 + cos(x)) - sin(x)*(-sin(x)))/(1 + cos(x))^2' },
          { latex: '\\frac{\\sin x(-\\sin x) - \\cos x(1+\\cos x)}{(1+\\cos x)^2}', expr: '(sin(x)*(-sin(x)) - cos(x)*(1 + cos(x)))/(1 + cos(x))^2', mistake: 'quotient-rule-order', why: "The numerator must be $f'g - fg'$ (derivative of the top first)." },
          { latex: '\\frac{\\cos x(1+\\cos x) + \\sin x(-\\sin x)}{(1+\\cos x)^2}', expr: '(cos(x)*(1 + cos(x)) + sin(x)*(-sin(x)))/(1 + cos(x))^2', mistake: 'quotient-rule-plus', why: "The quotient rule subtracts $fg'$." },
          { latex: '\\frac{\\cos x(1+\\cos x) - \\sin x(-\\sin x)}{1+\\cos x}', expr: '(cos(x)*(1 + cos(x)) - sin(x)*(-sin(x)))/(1 + cos(x))', mistake: 'quotient-rule-denominator', why: 'The denominator is $g^2 = (1 + \\cos x)^2$.' },
          { latex: '\\frac{\\sin x(-\\sin x) - \\cos x(1+\\cos x)}{1+\\cos x}', expr: '(sin(x)*(-sin(x)) - cos(x)*(1 + cos(x)))/(1 + cos(x))', mistake: 'quotient-rule-order', why: "Two slips: the numerator must be $f'g - fg'$, and the denominator must be $g^2$." },
          { latex: '\\frac{\\cos x(1+\\cos x) + \\sin x(-\\sin x)}{1+\\cos x}', expr: '(cos(x)*(1 + cos(x)) + sin(x)*(-sin(x)))/(1 + cos(x))', mistake: 'quotient-rule-plus', why: "Two slips: the quotient rule subtracts $fg'$, and the denominator must be $g^2$." },
        ],
        correct: 0,
        explanation: "$f'g - fg' = \\cos x(1+\\cos x) - \\sin x(-\\sin x)$, over $g^2 = (1+\\cos x)^2$.",
        result: { latex: "f'(x) = \\frac{\\cos x(1+\\cos x) - \\sin x(-\\sin x)}{(1+\\cos x)^2}" },
        check: { kind: 'derivative', of: 'sin(x)/(1 + cos(x))' },
      },
      {
        prompt: 'Expand the numerator. What does it simplify to?',
        options: [
          {
            latex: '\\cos x + \\cos^2 x - \\sin^2 x',
            expr: 'cos(x) + cos(x)^2 - sin(x)^2',
            mistake: 'sign-error',
            why: '$-\\sin x\\cdot(-\\sin x) = +\\sin^2 x$; with a minus sign the identity $\\sin^2 x + \\cos^2 x = 1$ cannot be used.',
          },
          {
            latex: '\\cos x',
            expr: 'cos(x)',
            mistake: 'pythagorean-wrong',
            why: '$\\cos^2 x + \\sin^2 x = 1$, not $0$.',
          },
          {
            latex: '1',
            expr: '1',
            mistake: 'algebra-error',
            why: 'The term $\\cos x\\cdot 1$ from expanding $\\cos x(1 + \\cos x)$ was dropped.',
          },
          {
            latex: '\\cos x + \\cos^2 x',
            expr: 'cos(x) + cos(x)^2',
            mistake: 'algebra-error',
            why: 'The term $-\\sin x\\cdot(-\\sin x) = \\sin^2 x$ was dropped.',
          },
          { latex: '1 + \\cos x', expr: '1 + cos(x)' },
        ],
        correct: 4,
        explanation: '$\\cos x + \\cos^2 x + \\sin^2 x = \\cos x + 1$ because $\\sin^2 x + \\cos^2 x = 1$.',
        result: { latex: '\\cos x + \\cos^2 x + \\sin^2 x = 1 + \\cos x' },
        check: { kind: 'value', expected: 'cos(x)*(1 + cos(x)) - sin(x)*(-sin(x))' },
      },
      {
        prompt: 'Simplify the whole derivative.',
        options: [
          { latex: '1', expr: '1', mistake: 'algebra-error', why: '$\\frac{1+\\cos x}{(1+\\cos x)^2}$ keeps one factor of $1 + \\cos x$ in the denominator.' },
          { latex: '\\frac{1}{1+\\cos x}', expr: '1/(1 + cos(x))' },
          { latex: '-1', expr: '-1', mistake: 'quotient-rule-order', why: "Two slips: the swapped numerator $fg' - f'g$ gives $-(1+\\cos x)$, and it was cancelled completely against the denominator." },
          { latex: '\\frac{1}{(1+\\cos x)^2}', expr: '1/(1 + cos(x))^2', mistake: 'algebra-error', why: 'The numerator is $1 + \\cos x$, not $1$; it cancels one power of the denominator.' },
          { latex: '-\\frac{1}{(1+\\cos x)^2}', expr: '-1/(1 + cos(x))^2', mistake: 'quotient-rule-order', why: 'Two slips: the swapped numerator gives $-(1+\\cos x)$, and it was then treated as $-1$.' },
          { latex: '-\\frac{1}{1+\\cos x}', expr: '-1/(1 + cos(x))', mistake: 'quotient-rule-order', why: "This is what the swapped numerator $fg' - f'g$ produces." },
        ],
        correct: 1,
        explanation: '$\\frac{1+\\cos x}{(1+\\cos x)^2} = \\frac{1}{1+\\cos x}$ (where $\\cos x \\neq -1$).',
        result: { latex: "f'(x) = \\frac{1}{1+\\cos x}" },
        check: { kind: 'derivative', of: 'sin(x)/(1 + cos(x))' },
      },
    ],
    final: {
      latex: "f'(x) = \\frac{1}{1 + \\cos x}",
      expr: '1/(1 + cos(x))',
      check: { kind: 'derivative', of: 'sin(x)/(1 + cos(x))' },
      recap: 'Quotient rule (low d-high minus high d-low, over low squared); then $\\sin^2 x + \\cos^2 x = 1$ collapses the numerator to $1 + \\cos x$, which cancels once.',
    },
  },
  {
    id: 'dr-s-02',
    topic: 'diff-review',
    title: 'Chain rule on a root in the denominator',
    difficulty: 1,
    statement: { text: 'Differentiate', latex: 'f(x) = \\frac{1}{\\sqrt[3]{x^2 + x + 1}}' },
    steps: [
      {
        prompt: 'Rewrite $f$ as a single power.',
        options: [
          {
            latex: 'f(x) = (x^2+x+1)^{1/3}',
            expr: '(x^2 + x + 1)^(1/3)',
            mistake: 'negative-exponent-sign',
            why: 'A root in the denominator gives a negative exponent: $\\frac{1}{\\sqrt[3]{u}} = u^{-1/3}$.',
          },
          { latex: 'f(x) = (x^2+x+1)^{-1/3}', expr: '(x^2 + x + 1)^(-1/3)' },
          {
            latex: 'f(x) = (x^2+x+1)^{-3}',
            expr: '(x^2 + x + 1)^(-3)',
            mistake: 'algebra-error',
            why: '$\\sqrt[3]{u} = u^{1/3}$, so $\\frac{1}{\\sqrt[3]{u}} = u^{-1/3}$, not $u^{-3}$.',
          },
          {
            latex: 'f(x) = x^{-2/3} + x^{-1/3} + 1',
            expr: 'x^(-2/3) + x^(-1/3) + 1',
            mistake: 'sqrt-of-sum-split',
            why: 'A root (or power) of a sum cannot be split term by term.',
          },
          {
            latex: 'f(x) = (x^2+x+1)^{3}',
            expr: '(x^2 + x + 1)^3',
            mistake: 'negative-exponent-sign',
            why: 'Two slips: the cube root became a cube, and the minus sign from the reciprocal was lost: $\\frac{1}{\\sqrt[3]{u}} = u^{-1/3}$.',
          },
          {
            latex: 'f(x) = -(x^2+x+1)^{1/3}',
            expr: '-(x^2 + x + 1)^(1/3)',
            mistake: 'negative-exponent-sign',
            why: '$\\frac1u$ is $u^{-1}$, not $-u$.',
          },
        ],
        correct: 1,
        explanation: '$\\sqrt[3]{u} = u^{1/3}$ and $\\frac1u = u^{-1}$, so $\\frac{1}{\\sqrt[3]{u}} = u^{-1/3}$.',
        result: { latex: 'f(x) = (x^2+x+1)^{-1/3}' },
        check: { kind: 'identity', lhs: '1/nthRoot(x^2 + x + 1, 3)' },
      },
      {
        prompt: 'Which rule applies outermost?',
        options: [
          { text: 'Power rule: $-\\frac{1}{3}(x^2+x+1)^{-4/3}$', mistake: 'chain-rule-missing', why: 'The base is a function of $x$, not $x$ itself; its derivative $2x + 1$ must multiply the result.' },
          { text: 'Differentiate the inside first: $\\frac{1}{\\sqrt[3]{2x+1}}$', mistake: 'chain-rule-outer-wrong', why: 'The inner derivative multiplies the outer derivative; it does not replace the inner function.' },
          { text: 'Split into $x^{-2/3} + x^{-1/3} + 1$ and use the power rule on each term', mistake: 'sqrt-of-sum-split', why: 'A power of a sum is not the sum of the powers.' },
          { text: "Exponential rule: $\\frac{d}{dx}a^{u} = a^{u}\\ln a\\cdot u'$", mistake: 'power-as-exponential', why: 'The variable is in the base, not in the exponent, so the power rule (with the chain rule) applies.' },
          { text: 'Chain rule: outer function $u^{-1/3}$, inner function $u = x^2+x+1$' },
          { text: 'Chain rule: outer function $u^{-3}$, inner function $u = \\sqrt[3]{x^2+x+1}$', mistake: 'composition-misread', why: '$(\\sqrt[3]{x^2+x+1})^{-3} = (x^2+x+1)^{-1}$, which is not $f$; the outer function is $u^{-1/3}$ with $u = x^2+x+1$.' },
        ],
        correct: 4,
        explanation: 'After rewriting, $f$ is a power of an inner function, so the chain rule applies, with the power rule outside.',
        result: { text: "Chain rule: $\\frac{d}{dx}u^{-1/3} = -\\frac13 u^{-4/3}\\cdot u'$ with $u = x^2+x+1$" },
      },
      {
        prompt: "What is the inner derivative $u'$?",
        options: [
          {
            latex: "u' = 2x + 2",
            expr: '2*x + 2',
            mistake: 'constant-derivative',
            why: 'The constant $1$ has derivative $0$.',
          },
          {
            latex: "u' = 2x",
            expr: '2*x',
            mistake: 'algebra-error',
            why: 'The middle term $x$ has derivative $1$; it was dropped.',
          },
          { latex: "u' = 2x + 1", expr: '2*x + 1' },
          {
            latex: "u' = x + 1",
            expr: 'x + 1',
            mistake: 'power-rule-coefficient',
            why: '$(x^2)\' = 2x$, not $x$.',
          },
          {
            latex: "u' = \\frac{x^3}{3} + \\frac{x^2}{2} + x",
            expr: 'x^3/3 + x^2/2 + x',
            mistake: 'integrated-instead',
            why: 'This is an antiderivative of $x^2 + x + 1$, not its derivative.',
          },
        ],
        correct: 2,
        explanation: '$(x^2 + x + 1)\' = 2x + 1 + 0$.',
        result: { latex: "u = x^2+x+1,\\quad u' = 2x+1" },
        check: { kind: 'derivative', of: 'x^2 + x + 1' },
      },
      {
        prompt: "Assemble $f'(x)$.",
        options: [
          { latex: '-\\frac{1}{3}(x^2+x+1)^{-4/3}', expr: '-1/3*(x^2 + x + 1)^(-4/3)', mistake: 'chain-rule-missing', why: 'The inner derivative $2x + 1$ was dropped.' },
          { latex: '-\\frac{1}{3}(x^2+x+1)^{-2/3}(2x+1)', expr: '-1/3*(x^2 + x + 1)^(-2/3)*(2*x + 1)', mistake: 'arithmetic-error', why: 'The exponent was lowered by only $\\frac13$; the power rule subtracts 1: $-\\frac13 - 1 = -\\frac43$.' },
          { latex: '\\frac{1}{3}(x^2+x+1)^{-4/3}(2x+1)', expr: '1/3*(x^2 + x + 1)^(-4/3)*(2*x + 1)', mistake: 'negative-exponent-sign', why: 'The power rule brings down the exponent $-\\frac13$, so the coefficient is negative.' },
          { latex: '\\frac{1}{3}(x^2+x+1)^{-4/3}', expr: '1/3*(x^2 + x + 1)^(-4/3)', mistake: 'chain-rule-missing', why: 'Two slips: the inner derivative $2x+1$ was dropped, and the factor $-\\frac13$ became $+\\frac13$.' },
          { latex: '\\frac{1}{3}(x^2+x+1)^{-2/3}(2x+1)', expr: '1/3*(x^2 + x + 1)^(-2/3)*(2*x + 1)', mistake: 'arithmetic-error', why: 'Two slips: the exponent was lowered by only $\\frac13$, and the factor $-\\frac13$ lost its sign.' },
          { latex: '-\\frac{1}{3}(x^2+x+1)^{-4/3}(2x+1)', expr: '-1/3*(x^2 + x + 1)^(-4/3)*(2*x + 1)' },
        ],
        correct: 5,
        explanation: "Chain rule: $-\\frac13 u^{-4/3}\\cdot u'$ with $u = x^2+x+1$ and $u' = 2x+1$.",
        result: { latex: "f'(x) = -\\frac{1}{3}(x^2+x+1)^{-4/3}(2x+1)" },
        check: { kind: 'derivative', of: '(x^2 + x + 1)^(-1/3)' },
      },
      {
        prompt: 'Write the answer without negative exponents.',
        options: [
          { latex: '-\\frac{2x+1}{3(x^2+x+1)^{4/3}}', expr: '-(2*x + 1)/(3*(x^2 + x + 1)^(4/3))' },
          {
            latex: '-\\frac{2x+1}{(x^2+x+1)^{4/3}}',
            expr: '-(2*x + 1)/(x^2 + x + 1)^(4/3)',
            mistake: 'coefficient-mishandled',
            why: 'The factor $\\frac13$ was lost: the denominator must be $3(x^2+x+1)^{4/3}$.',
          },
          {
            latex: '-\\frac{(2x+1)(x^2+x+1)^{4/3}}{3}',
            expr: '-(2*x + 1)*(x^2 + x + 1)^(4/3)/3',
            mistake: 'negative-exponent-sign',
            why: '$u^{-4/3}$ belongs in the denominator as $u^{4/3}$; it cannot stay upstairs with a positive exponent.',
          },
          {
            latex: '-\\frac{2x+1}{3\\sqrt[3]{x^2+x+1}}',
            expr: '-(2*x + 1)/(3*nthRoot(x^2 + x + 1, 3))',
            mistake: 'algebra-error',
            why: '$u^{4/3} = u\\sqrt[3]{u}$, not $\\sqrt[3]{u}$.',
          },
          {
            latex: '-\\frac{3(2x+1)}{(x^2+x+1)^{4/3}}',
            expr: '-3*(2*x + 1)/(x^2 + x + 1)^(4/3)',
            mistake: 'algebra-error',
            why: 'The factor $\\frac13$ stays in the denominator as a 3; it does not become a 3 in the numerator.',
          },
        ],
        correct: 0,
        explanation: "$u^{-4/3} = \\frac{1}{u^{4/3}}$, so $f'(x) = -\\frac{2x+1}{3(x^2+x+1)^{4/3}}$.",
        result: { latex: "f'(x) = -\\frac{2x+1}{3(x^2+x+1)^{4/3}}" },
        check: { kind: 'derivative', of: '(x^2 + x + 1)^(-1/3)' },
      },
    ],
    final: {
      latex: "f'(x) = -\\frac{2x+1}{3(x^2+x+1)^{4/3}}",
      expr: '-(2*x + 1)/(3*(x^2 + x + 1)^(4/3))',
      check: { kind: 'derivative', of: '1/nthRoot(x^2 + x + 1, 3)' },
      recap: 'Rewrite the root as the power $u^{-1/3}$, apply the power rule outside, and multiply by the inner derivative $2x + 1$.',
    },
  },
  {
    id: 'dr-s-03',
    topic: 'diff-review',
    title: 'Inverse cosine of a square root',
    difficulty: 2,
    statement: { text: 'Find $f\'(x)$ for $0 < x < 1$:', latex: 'f(x) = \\arccos(\\sqrt{x})' },
    steps: [
      {
        prompt: 'Which rule applies outermost?',
        options: [
          { text: 'Product rule: $\\arccos$ times $\\sqrt{x}$', mistake: 'technique-wrong', why: '$\\arccos$ is applied to $\\sqrt{x}$; this is a composition, not a product.' },
          { text: 'Chain rule: outer function $\\arccos u$, inner function $u = \\sqrt{x}$' },
          { text: 'Differentiate $\\arccos x$, then replace $x$ by $\\sqrt{x}$', mistake: 'chain-rule-missing', why: 'The inner function $\\sqrt{x}$ has its own derivative, which must multiply the outer derivative.' },
          { text: 'Read $\\arccos(\\sqrt{x})$ as $\\frac{1}{\\cos\\sqrt{x}}$ and use the quotient rule', mistake: 'inverse-trig-as-reciprocal', why: '$\\arccos$ is the inverse cosine, not the reciprocal of cosine.' },
          { text: 'Power rule, since $\\sqrt{x} = x^{1/2}$', mistake: 'chain-rule-outer-wrong', why: 'The outer function is $\\arccos$; the power rule handles only the inner $\\sqrt{x}$.' },
          { text: 'Chain rule: outer function $\\sqrt{u}$, inner function $u = \\arccos x$', mistake: 'composition-misread', why: '$\\sqrt{\\arccos x}$ is a different function; here $\\arccos$ is applied to $\\sqrt{x}$, so $\\arccos$ is the outer function.' },
        ],
        correct: 1,
        explanation: '$\\arccos$ is applied to the inner function $\\sqrt{x}$, so the chain rule comes first.',
        result: { text: 'Chain rule with $u = \\sqrt{x}$' },
      },
      {
        prompt: 'What is $\\frac{d}{du}\\arccos u$?',
        variable: 'u',
        options: [
          {
            latex: '\\frac{1}{\\sqrt{1-u^2}}',
            expr: '1/sqrt(1 - u^2)',
            mistake: 'sign-error-derivative',
            why: 'That is the derivative of $\\arcsin u$; $\\arccos u$ carries a minus sign.',
          },
          {
            latex: '-\\frac{1}{1+u^2}',
            expr: '-1/(1 + u^2)',
            mistake: 'inverse-trig-confused',
            why: 'A denominator $1 + u^2$ belongs to the inverse tangent family; $\\arccos$ has a square root.',
          },
          {
            latex: '\\sec u\\tan u',
            expr: 'sec(u)*tan(u)',
            mistake: 'inverse-trig-as-reciprocal',
            why: '$\\arccos u$ was treated as $\\frac{1}{\\cos u} = \\sec u$.',
          },
          {
            latex: '-\\frac{1}{\\sqrt{1+u^2}}',
            expr: '-1/sqrt(1 + u^2)',
            mistake: 'inverse-trig-confused',
            why: 'The radicand is $1 - u^2$, not $1 + u^2$.',
          },
          { latex: '-\\frac{1}{\\sqrt{1-u^2}}', expr: '-1/sqrt(1 - u^2)' },
        ],
        correct: 4,
        explanation: 'Standard formula: $\\frac{d}{du}\\arccos u = -\\frac{1}{\\sqrt{1-u^2}}$.',
        result: { latex: '\\frac{d}{du}\\arccos u = -\\frac{1}{\\sqrt{1-u^2}}' },
        check: { kind: 'derivative', of: 'acos(u)' },
      },
      {
        prompt: "What is the inner derivative $u' = \\frac{d}{dx}\\sqrt{x}$?",
        options: [
          { latex: "u' = \\frac{1}{\\sqrt{x}}", expr: '1/sqrt(x)', mistake: 'power-rule-coefficient', why: "$(x^{1/2})' = \\frac12 x^{-1/2}$; the factor $\\frac12$ was dropped." },
          { latex: "u' = \\frac{1}{2}\\sqrt{x}", expr: 'sqrt(x)/2', mistake: 'power-rule-exponent', why: 'The exponent $\\frac12$ was not lowered to $-\\frac12$.' },
          { latex: "u' = \\frac{1}{2\\sqrt{x}}", expr: '1/(2*sqrt(x))' },
          { latex: "u' = -\\frac{1}{\\sqrt{x}}", expr: '-1/sqrt(x)', mistake: 'power-rule-coefficient', why: 'Two slips: the factor $\\frac12$ was dropped, and the sign of the new exponent was put on the result.' },
          { latex: "u' = -\\frac{1}{2\\sqrt{x}}", expr: '-1/(2*sqrt(x))', mistake: 'negative-exponent-sign', why: 'The new exponent is $-\\frac12$, but the coefficient is the old exponent $+\\frac12$.' },
          { latex: "u' = -\\frac{1}{2}\\sqrt{x}", expr: '-sqrt(x)/2', mistake: 'power-rule-exponent', why: 'Two slips: the exponent was not lowered, and a minus sign was attached.' },
        ],
        correct: 2,
        explanation: "$\\sqrt{x} = x^{1/2}$, so $u' = \\frac12 x^{-1/2} = \\frac{1}{2\\sqrt{x}}$.",
        result: { latex: "u' = \\frac{1}{2\\sqrt{x}}" },
        check: { kind: 'derivative', of: 'sqrt(x)' },
      },
      {
        prompt: "Assemble $f'(x)$ with the chain rule.",
        options: [
          { latex: '-\\frac{1}{\\sqrt{1-x^2}}\\cdot\\frac{1}{2\\sqrt{x}}', expr: '-1/(sqrt(1 - x^2)*2*sqrt(x))', mistake: 'chain-rule-outer-wrong', why: 'The outer derivative must be evaluated at $u = \\sqrt{x}$: $1 - u^2 = 1 - x$, not $1 - x^2$.' },
          { latex: '-\\frac{1}{\\sqrt{1-x}}', expr: '-1/sqrt(1 - x)', mistake: 'chain-rule-missing', why: 'The inner derivative $\\frac{1}{2\\sqrt{x}}$ was dropped.' },
          { latex: '\\frac{1}{\\sqrt{1-x^2}}\\cdot\\frac{1}{2\\sqrt{x}}', expr: '1/(sqrt(1 - x^2)*2*sqrt(x))', mistake: 'chain-rule-outer-wrong', why: 'Two slips: the outer derivative was evaluated at $x$ instead of $\\sqrt{x}$, and its minus sign was lost.' },
          { latex: '\\frac{1}{\\sqrt{1-x}}\\cdot\\frac{1}{2\\sqrt{x}}', expr: '1/(sqrt(1 - x)*2*sqrt(x))', mistake: 'sign-error-derivative', why: 'The minus sign of the $\\arccos$ derivative was lost.' },
          { latex: '-\\frac{1}{\\sqrt{1-x}}\\cdot\\frac{1}{2\\sqrt{x}}', expr: '-1/(sqrt(1 - x)*2*sqrt(x))' },
          { latex: '\\frac{1}{\\sqrt{1-x}}', expr: '1/sqrt(1 - x)', mistake: 'chain-rule-missing', why: 'Two slips: the inner derivative $\\frac{1}{2\\sqrt{x}}$ was dropped, and the minus sign of the $\\arccos$ derivative was lost.' },
        ],
        correct: 4,
        explanation: "$f'(x) = -\\frac{1}{\\sqrt{1-u^2}}\\cdot u'$ with $u^2 = (\\sqrt{x})^2 = x$.",
        result: { latex: "f'(x) = -\\frac{1}{\\sqrt{1-x}}\\cdot\\frac{1}{2\\sqrt{x}}" },
        check: { kind: 'derivative', of: 'acos(sqrt(x))' },
      },
      {
        prompt: 'Simplify.',
        options: [
          { latex: '\\frac{1}{2\\sqrt{x-x^2}}', expr: '1/(2*sqrt(x - x^2))', mistake: 'sign-error', why: 'The minus sign from the $\\arccos$ derivative was lost while simplifying.' },
          { latex: '-\\frac{1}{2\\sqrt{x-x^2}}', expr: '-1/(2*sqrt(x - x^2))' },
          { latex: '-\\frac{1}{\\sqrt{x-x^2}}', expr: '-1/sqrt(x - x^2)', mistake: 'coefficient-mishandled', why: 'The factor 2 from $\\frac{1}{2\\sqrt{x}}$ was lost.' },
          { latex: '-\\frac{\\sqrt{x}}{2\\sqrt{1-x}}', expr: '-sqrt(x)/(2*sqrt(1 - x))', mistake: 'algebra-error', why: '$\\frac{1}{2\\sqrt{x}}$ puts $\\sqrt{x}$ in the denominator, not the numerator.' },
          { latex: '\\frac{1}{\\sqrt{x-x^2}}', expr: '1/sqrt(x - x^2)', mistake: 'coefficient-mishandled', why: 'Two slips: the factor 2 was lost, and so was the minus sign of the $\\arccos$ derivative.' },
          { latex: '\\frac{\\sqrt{x}}{2\\sqrt{1-x}}', expr: 'sqrt(x)/(2*sqrt(1 - x))', mistake: 'algebra-error', why: 'Two slips: $\\sqrt{x}$ belongs in the denominator, and the minus sign was lost.' },
        ],
        correct: 1,
        explanation: '$\\sqrt{x}\\,\\sqrt{1-x} = \\sqrt{x(1-x)} = \\sqrt{x - x^2}$ for $0 < x < 1$.',
        result: { latex: "f'(x) = -\\frac{1}{2\\sqrt{x-x^2}}" },
        check: { kind: 'derivative', of: 'acos(sqrt(x))' },
      },
    ],
    final: {
      latex: "f'(x) = -\\frac{1}{2\\sqrt{x-x^2}}",
      expr: '-1/(2*sqrt(x - x^2))',
      check: { kind: 'derivative', of: 'acos(sqrt(x))' },
      recap: "Chain rule: evaluate $-\\frac{1}{\\sqrt{1-u^2}}$ at $u = \\sqrt{x}$ (so $u^2 = x$) and multiply by $u' = \\frac{1}{2\\sqrt{x}}$.",
    },
    domain: [0.1, 0.9],
  },
  {
    id: 'dr-s-04',
    topic: 'diff-review',
    title: 'Square of an inverse tangent',
    difficulty: 1,
    statement: { text: 'Find $f\'(x)$ for', latex: 'f(x) = \\left(\\tan^{-1}x\\right)^2' },
    steps: [
      {
        prompt: 'Which rule applies outermost?',
        options: [
          {
            text: 'Chain rule: outer function $\\tan^{-1}u$, inner function $u = x^2$',
            mistake: 'composition-misread',
            why: 'The square is applied to $\\tan^{-1}x$, not to $x$: $(\\tan^{-1}x)^2 \\neq \\tan^{-1}(x^2)$.',
          },
          {
            text: 'Read $\\tan^{-1}x$ as $\\frac{1}{\\tan x}$, so $f = \\cot^2 x$',
            mistake: 'inverse-trig-as-reciprocal',
            why: 'The $-1$ means the inverse tangent, not the reciprocal of $\\tan x$.',
          },
          {
            text: 'Power rule: the answer is $2\\tan^{-1}x$',
            mistake: 'chain-rule-missing',
            why: 'The base $\\tan^{-1}x$ is a function of $x$, so its derivative must multiply the result.',
          },
          { text: 'Chain rule: outer function $u^2$, inner function $u = \\tan^{-1}x$' },
          {
            text: 'Product rule with the factors $\\tan^{-1}$ and $x$',
            mistake: 'technique-wrong',
            why: '$\\tan^{-1}$ is a function applied to $x$, not a factor multiplying $x$.',
          },
        ],
        correct: 3,
        explanation: 'The last operation is squaring, so the outer function is $u^2$ with $u = \\tan^{-1}x$.',
        result: { text: 'Outer $u^2$, inner $u = \\tan^{-1}x$' },
      },
      {
        prompt: 'What is the outer derivative $\\frac{d}{du}u^2$, written at $u = \\tan^{-1}x$?',
        options: [
          { latex: '2\\tan^{-1}x', expr: '2*atan(x)' },
          {
            latex: '\\tan^{-1}x',
            expr: 'atan(x)',
            mistake: 'power-rule-coefficient',
            why: '$(u^2)\' = 2u$; the factor 2 was dropped.',
          },
          {
            latex: '2x',
            expr: '2*x',
            mistake: 'chain-rule-outer-wrong',
            why: 'The outer derivative $2u$ must be evaluated at $u = \\tan^{-1}x$, not at $x$.',
          },
          {
            latex: '2(\\tan^{-1}x)^2',
            expr: '2*atan(x)^2',
            mistake: 'power-rule-exponent',
            why: 'The 2 was brought down but the exponent was not lowered: $(u^2)\' = 2u^1$.',
          },
          {
            latex: '\\frac{1}{3}(\\tan^{-1}x)^3',
            expr: 'atan(x)^3/3',
            mistake: 'integrated-instead',
            why: 'Raising the power and dividing by 3 is the integration power rule.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{d}{du}u^2 = 2u = 2\\tan^{-1}x$.',
        result: { latex: '2u = 2\\tan^{-1}x' },
        check: { kind: 'value', expected: '2*atan(x)' },
      },
      {
        prompt: 'What is the inner derivative $\\frac{d}{dx}\\tan^{-1}x$?',
        options: [
          { latex: '\\frac{1}{\\sqrt{1-x^2}}', expr: '1/sqrt(1 - x^2)', mistake: 'inverse-trig-confused', why: '$\\frac{1}{\\sqrt{1-x^2}}$ is the derivative of $\\sin^{-1}x$.' },
          { latex: '-\\frac{1}{1+x^2}', expr: '-1/(1 + x^2)', mistake: 'sign-error-derivative', why: '$\\tan^{-1}x$ is increasing, so its derivative is positive.' },
          { latex: '\\frac{1}{1+x^2}', expr: '1/(1 + x^2)' },
          { latex: '-\\frac{1}{\\sqrt{1-x^2}}', expr: '-1/sqrt(1 - x^2)', mistake: 'inverse-trig-confused', why: '$-\\frac{1}{\\sqrt{1-x^2}}$ is the derivative of $\\cos^{-1}x$, not of $\\tan^{-1}x$.' },
          { latex: '-\\csc^2 x', expr: '-csc(x)^2', mistake: 'inverse-trig-as-reciprocal', why: '$\\tan^{-1}x$ was read as $\\cot x$; the $-1$ means the inverse tangent.' },
          { latex: '\\csc^2 x', expr: 'csc(x)^2', mistake: 'inverse-trig-as-reciprocal', why: "Two slips: $\\tan^{-1}x$ was read as $\\cot x$, and the minus sign of $(\\cot x)'$ was lost." },
        ],
        correct: 2,
        explanation: '$\\frac{d}{dx}\\tan^{-1}x = \\frac{1}{1+x^2}$.',
        result: { latex: '\\frac{d}{dx}\\tan^{-1}x = \\frac{1}{1+x^2}' },
        check: { kind: 'derivative', of: 'atan(x)' },
      },
      {
        prompt: "Assemble $f'(x)$.",
        options: [
          {
            latex: '2\\tan^{-1}x',
            expr: '2*atan(x)',
            mistake: 'chain-rule-missing',
            why: 'The inner derivative $\\frac{1}{1+x^2}$ was dropped.',
          },
          {
            latex: '\\frac{2}{1+x^2}',
            expr: '2/(1 + x^2)',
            mistake: 'chain-rule-outer-wrong',
            why: 'The factor $\\tan^{-1}x$ from the outer derivative $2u$ was dropped.',
          },
          {
            latex: '\\frac{1}{(1+x^2)^2}',
            expr: '1/(1 + x^2)^2',
            mistake: 'chain-rule-outer-wrong',
            why: "The inner derivative was squared; the chain rule gives $2u\\cdot u'$, not $(u')^2$.",
          },
          {
            latex: '\\frac{2\\tan^{-1}x}{(1+x^2)^2}',
            expr: '2*atan(x)/(1 + x^2)^2',
            mistake: 'chain-rule-doubled',
            why: 'The inner derivative $\\frac{1}{1+x^2}$ was applied twice.',
          },
          { latex: '\\frac{2\\tan^{-1}x}{1+x^2}', expr: '2*atan(x)/(1 + x^2)' },
        ],
        correct: 4,
        explanation: 'Chain rule: $2\\tan^{-1}x\\cdot\\frac{1}{1+x^2}$.',
        result: { latex: "f'(x) = \\frac{2\\tan^{-1}x}{1+x^2}" },
        check: { kind: 'derivative', of: 'atan(x)^2' },
      },
    ],
    final: {
      latex: "f'(x) = \\frac{2\\tan^{-1}x}{1+x^2}",
      expr: '2*atan(x)/(1 + x^2)',
      check: { kind: 'derivative', of: 'atan(x)^2' },
      recap: 'Outer square first: $2u$ with $u = \\tan^{-1}x$, times the inner derivative $\\frac{1}{1+x^2}$.',
    },
    domain: [0.1, 0.9],
  },
];
