import type { StepProblem } from '../types';

/** Step-Through problems for topic "ibp". Authored by content-author; verified by math-verifier. */
export const steps: StepProblem[] = [
  // ── 1. A single function: ∫ arcsin(x) dx (IBP followed by a substitution) ─────────────────
  {
    id: 'ip-s-01',
    topic: 'ibp',
    title: 'A single function: arcsin x',
    difficulty: 1,
    statement: { text: 'Evaluate the integral.', latex: '\\int \\arcsin(x)\\,dx' },
    domain: [0.1, 0.9],
    steps: [
      {
        prompt: 'The integrand is a single function. Which choice of $u$ and $dv$ should we use?',
        options: [
          { latex: 'u = \\arcsin(x),\\ dv = dx', expr: '[asin(x), dx]' },
          {
            latex: 'u = 1,\\ dv = \\arcsin(x)\\,dx',
            expr: '[1, asin(x)*dx]',
            mistake: 'ibp-wrong-u-dv',
            why: 'Then v = ∫arcsin(x) dx is the original problem and du = 0; nothing is gained.',
          },
          {
            latex: 'u = \\arcsin(x),\\ dv = x\\,dx',
            expr: '[asin(x), x*dx]',
            mistake: 'ibp-v-wrong',
            why: 'There is no factor x in the integrand; x is v = ∫dx, while dv is just dx.',
          },
          {
            latex: 'u = \\frac{1}{\\sqrt{1-x^2}},\\ dv = dx',
            expr: '[1/sqrt(1-x^2), dx]',
            mistake: 'ibp-du-wrong',
            why: '1/√(1−x²) is the derivative of arcsin(x); it belongs in du, not in u.',
          },
          {
            latex: 'u = \\frac{1}{\\sin(x)},\\ dv = dx',
            expr: '[1/sin(x), dx]',
            mistake: 'inverse-trig-as-reciprocal',
            why: 'arcsin(x) (also written sin⁻¹x) is the inverse sine, not the reciprocal 1/sin(x).',
          },
        ],
        correct: 0,
        explanation: 'For a single function take $u = \\arcsin(x)$ (its derivative is algebraic) and $dv = dx$.',
        result: { latex: 'u = \\arcsin(x),\\quad dv = dx' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'The new integral is $\\int v\\,du$. What is $v\\,du$?',
        options: [
          { latex: '\\frac{x}{\\sqrt{1-x^2}}\\,dx', expr: 'x*dx/sqrt(1-x^2)' },
          {
            latex: '\\frac{x}{1+x^2}\\,dx',
            expr: 'x*dx/(1+x^2)',
            mistake: 'inverse-trig-confused',
            why: 'du was taken as dx/(1+x²), the derivative of arctan(x); for arcsin(x) it is dx/√(1−x²).',
          },
          {
            latex: '-\\frac{x}{\\sqrt{1-x^2}}\\,dx',
            expr: '-x*dx/sqrt(1-x^2)',
            mistake: 'inverse-trig-confused',
            why: 'The minus sign belongs to the derivative of arccos(x), not arcsin(x).',
          },
          {
            latex: '\\frac{1}{\\sqrt{1-x^2}}\\,dx',
            expr: 'dx/sqrt(1-x^2)',
            mistake: 'ibp-formula-wrong',
            why: 'This is du alone; the factor v = x was left out of v du.',
          },
          {
            latex: '\\frac{x^2}{2\\sqrt{1-x^2}}\\,dx',
            expr: 'x^2*dx/(2*sqrt(1-x^2))',
            mistake: 'ibp-v-wrong',
            why: 'v = ∫dx = x; x²/2 would be the antiderivative of x dx.',
          },
          {
            latex: 'x\\sqrt{1-x^2}\\,dx',
            expr: 'x*sqrt(1-x^2)*dx',
            mistake: 'ibp-du-wrong',
            why: 'd(arcsin x) = dx/√(1−x²); the root belongs in the denominator.',
          },
        ],
        correct: 0,
        explanation: '$du = \\frac{dx}{\\sqrt{1-x^2}}$ and $v = x$, so $v\\,du = \\frac{x}{\\sqrt{1-x^2}}\\,dx$.',
        result: { latex: 'du = \\frac{1}{\\sqrt{1-x^2}}\\,dx,\\quad v = x,\\quad v\\,du = \\frac{x}{\\sqrt{1-x^2}}\\,dx' },
        check: { kind: 'value', expected: 'x*(1/sqrt(1-x^2))*dx' },
      },
      {
        prompt: 'Apply $\\int u\\,dv = uv - \\int v\\,du$.',
        options: [
          { latex: 'x\\arcsin(x) - \\int \\frac{x}{\\sqrt{1-x^2}}\\,dx', expr: 'x*asin(x) - indefinite(x/sqrt(1-x^2), x)' },
          {
            latex: 'x\\arcsin(x) + \\int \\frac{x}{\\sqrt{1-x^2}}\\,dx',
            expr: 'x*asin(x) + indefinite(x/sqrt(1-x^2), x)',
            mistake: 'ibp-sign-error',
            why: 'The formula subtracts ∫v du; the plus sign is wrong.',
          },
          {
            latex: '-x\\arcsin(x) + \\int \\frac{x}{\\sqrt{1-x^2}}\\,dx',
            expr: '-x*asin(x) + indefinite(x/sqrt(1-x^2), x)',
            mistake: 'formula-wrong-sign',
            why: 'This is ∫v du − uv, the negative of the formula.',
          },
          {
            latex: 'x\\arcsin(x) - \\int \\arcsin(x)\\,dx',
            expr: 'x*asin(x) - indefinite(asin(x), x)',
            mistake: 'ibp-formula-wrong',
            why: 'The new integral is ∫v du, not ∫u dv again; this just repeats the original problem.',
          },
          {
            latex: '\\arcsin(x) - \\int \\frac{x}{\\sqrt{1-x^2}}\\,dx',
            expr: 'asin(x) - indefinite(x/sqrt(1-x^2), x)',
            mistake: 'ibp-formula-wrong',
            why: 'The boundary term is uv = x·arcsin(x); the factor v = x was left off.',
          },
        ],
        correct: 0,
        explanation: '$uv - \\int v\\,du = x\\arcsin(x) - \\int \\frac{x}{\\sqrt{1-x^2}}\\,dx$.',
        result: { latex: '\\int \\arcsin(x)\\,dx = x\\arcsin(x) - \\int \\frac{x}{\\sqrt{1-x^2}}\\,dx' },
        check: { kind: 'identity', lhs: 'x*asin(x) - indefinite(x*(1/sqrt(1-x^2)), x)' },
      },
      {
        prompt: 'The new integral needs a substitution. With $w = 1 - x^2$, evaluate $\\int \\frac{x}{\\sqrt{1-x^2}}\\,dx$.',
        options: [
          { latex: '-\\sqrt{1-x^2} + C', expr: '-sqrt(1-x^2)' },
          {
            latex: '\\sqrt{1-x^2} + C',
            expr: 'sqrt(1-x^2)',
            mistake: 'u-cos-sign-missing',
            why: 'dw = −2x dx, so x dx = −dw/2; the minus sign was dropped.',
          },
          {
            latex: '-2\\sqrt{1-x^2} + C',
            expr: '-2*sqrt(1-x^2)',
            mistake: 'du-constant-wrong',
            why: 'x dx = −dw/2; the ½ was dropped, doubling the result.',
          },
          {
            latex: '-\\frac{1}{2}\\sqrt{1-x^2} + C',
            expr: '-sqrt(1-x^2)/2',
            mistake: 'power-rule-int-coefficient',
            why: '∫w^{−1/2} dw = 2w^{1/2}; the division by the new exponent ½ was skipped.',
          },
          {
            latex: '-\\frac{1}{2}\\ln(1-x^2) + C',
            expr: '-log(1-x^2)/2',
            mistake: 'ln-misapplied',
            why: 'The power of w is −1/2, not −1, so the power rule applies, not the logarithm.',
          },
          {
            latex: '\\arcsin(x) + C',
            expr: 'asin(x)',
            mistake: 'formula-swapped',
            why: 'arcsin(x) is ∫dx/√(1−x²); the extra factor x in the numerator changes the integral.',
          },
        ],
        correct: 0,
        explanation: '$x\\,dx = -\\frac12\\,dw$: $-\\frac12\\int w^{-1/2}\\,dw = -w^{1/2} = -\\sqrt{1-x^2} + C$.',
        result: { latex: '\\int \\frac{x}{\\sqrt{1-x^2}}\\,dx = -\\frac{1}{2}\\int w^{-1/2}\\,dw = -\\sqrt{1-x^2} + C' },
        check: { kind: 'antiderivative', integrand: 'x/sqrt(1-x^2)' },
      },
      {
        prompt: 'So $\\int \\arcsin(x)\\,dx = x\\arcsin(x) + \\sqrt{1-x^2} + C$. Check it by differentiating: what is the derivative of $x\\arcsin(x) + \\sqrt{1-x^2}$?',
        options: [
          { latex: '\\arcsin(x)', expr: 'asin(x)' },
          {
            latex: '\\arcsin(x) + \\frac{2x}{\\sqrt{1-x^2}}',
            expr: 'asin(x) + 2*x/sqrt(1-x^2)',
            mistake: 'sign-error-derivative',
            why: 'The derivative of √(1−x²) is −x/√(1−x²); with the sign lost the two x-terms add instead of cancel.',
          },
          {
            latex: '\\arcsin(x) - \\frac{x}{\\sqrt{1-x^2}}',
            expr: 'asin(x) - x/sqrt(1-x^2)',
            mistake: 'product-rule-missing-term',
            why: 'The derivative of x·arcsin(x) is arcsin(x) + x/√(1−x²); the second product-rule term was dropped.',
          },
          {
            latex: '\\arcsin(x) + \\frac{x}{\\sqrt{1-x^2}} + \\frac{1}{2\\sqrt{1-x^2}}',
            expr: 'asin(x) + x/sqrt(1-x^2) + 1/(2*sqrt(1-x^2))',
            mistake: 'chain-rule-missing',
            why: 'Differentiating √(1−x²) needs the inner derivative −2x; without it the root term gives 1/(2√(1−x²)).',
          },
          {
            latex: '0',
            expr: '0',
            mistake: 'product-rule-missing-term',
            why: 'In the derivative of x·arcsin(x) the term (x)′·arcsin(x) = arcsin(x) was dropped.',
          },
        ],
        correct: 0,
        explanation: '$\\arcsin(x) + \\frac{x}{\\sqrt{1-x^2}} - \\frac{x}{\\sqrt{1-x^2}} = \\arcsin(x)$, the original integrand, so the answer checks.',
        result: { latex: '\\frac{d}{dx}\\left[x\\arcsin(x) + \\sqrt{1-x^2}\\right] = \\arcsin(x) + \\frac{x}{\\sqrt{1-x^2}} - \\frac{x}{\\sqrt{1-x^2}} = \\arcsin(x)' },
        check: { kind: 'derivative', of: 'x*asin(x) + sqrt(1-x^2)' },
      },
    ],
    final: {
      latex: 'x\\arcsin(x) + \\sqrt{1-x^2} + C',
      expr: 'x*asin(x) + sqrt(1-x^2)',
      check: { kind: 'antiderivative', integrand: 'asin(x)' },
      recap: 'For a single function take $u = f(x)$ and $dv = dx$; the leftover $\\int\\frac{x}{\\sqrt{1-x^2}}\\,dx$ needs the substitution $w = 1 - x^2$, and differentiating confirms the answer.',
    },
  },

  // ── 2. Definite, LIATE picks u = x: ∫₀^{π/2} x sin(2x) dx ────────────────────────────────
  {
    id: 'ip-s-02',
    topic: 'ibp',
    title: 'Definite integral: x sin 2x',
    difficulty: 1,
    statement: { text: 'Evaluate the definite integral.', latex: '\\int_0^{\\pi/2} x\\sin(2x)\\,dx' },
    steps: [
      {
        prompt: 'Following LIATE, choose $u$ and $dv$.',
        options: [
          { latex: 'u = x,\\ dv = \\sin(2x)\\,dx', expr: '[x, sin(2*x)*dx]' },
          {
            latex: 'u = \\sin(2x),\\ dv = x\\,dx',
            expr: '[sin(2*x), x*dx]',
            mistake: 'liate-misordered',
            why: 'Algebraic comes before trigonometric; with dv = x dx the power of x grows to x²/2.',
          },
          {
            latex: 'u = x,\\ dv = dx',
            expr: '[x, dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor sin(2x) is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = \\sin(2x),\\ dv = dx',
            expr: '[sin(2*x), dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor x is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = x,\\ dv = -\\frac{1}{2}\\cos(2x)\\,dx',
            expr: '[x, -cos(2*x)/2*dx]',
            mistake: 'ibp-v-wrong',
            why: '−½cos(2x) is v, the antiderivative; dv is sin(2x) dx as written in the integrand.',
          },
        ],
        correct: 0,
        explanation: 'A comes before T: $u = x$ differentiates to $du = dx$, and $dv = \\sin(2x)\\,dx$ is easy to integrate.',
        result: { latex: 'u = x,\\quad dv = \\sin(2x)\\,dx' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'With $du = dx$, what is $v$?',
        options: [
          { latex: 'v = -\\frac{1}{2}\\cos(2x)', expr: '-cos(2*x)/2' },
          {
            latex: 'v = \\frac{1}{2}\\cos(2x)',
            expr: 'cos(2*x)/2',
            mistake: 'trig-antiderivative-sign',
            why: '∫sin(2x) dx = −½cos(2x); the antiderivative of sine carries a minus sign.',
          },
          {
            latex: 'v = -2\\cos(2x)',
            expr: '-2*cos(2*x)',
            mistake: 'inner-constant-factor-missing',
            why: 'For sin(2x), divide by the inner constant 2; multiplying by 2 is the derivative pattern.',
          },
          {
            latex: 'v = -\\cos(2x)',
            expr: '-cos(2*x)',
            mistake: 'inner-constant-factor-missing',
            why: 'The factor ½ from the inner 2x was dropped.',
          },
          {
            latex: 'v = 2\\cos(2x)',
            expr: '2*cos(2*x)',
            mistake: 'differentiated-instead',
            why: '2cos(2x) is the derivative of sin(2x); v must be an antiderivative.',
          },
        ],
        correct: 0,
        explanation: '$v = \\int\\sin(2x)\\,dx = -\\frac12\\cos(2x)$.',
        result: { latex: 'du = dx,\\quad v = -\\frac{1}{2}\\cos(2x)' },
        check: { kind: 'value', expected: '-cos(2*x)/2' },
      },
      {
        prompt: 'Apply $\\int_a^b u\\,dv = uv\\big|_a^b - \\int_a^b v\\,du$.',
        options: [
          { latex: '\\left[-\\frac{x}{2}\\cos(2x)\\right]_0^{\\pi/2} + \\frac{1}{2}\\int_0^{\\pi/2}\\cos(2x)\\,dx' },
          {
            latex: '\\left[-x\\cos(2x)\\right]_0^{\\pi/2} + \\frac{1}{2}\\int_0^{\\pi/2}\\cos(2x)\\,dx',
            mistake: 'coefficient-mishandled',
            why: 'The boundary term is uv = x · (−½cos 2x); the ½ from v was dropped there.',
          },
          {
            latex: '-\\frac{x}{2}\\cos(2x) + \\frac{1}{2}\\int_0^{\\pi/2}\\cos(2x)\\,dx',
            mistake: 'ibp-bounds-not-applied',
            why: 'The boundary term uv must also be evaluated from 0 to π/2.',
          },
          {
            latex: '\\left[\\frac{x}{2}\\cos(2x)\\right]_0^{\\pi/2} - \\frac{1}{2}\\int_0^{\\pi/2}\\cos(2x)\\,dx',
            mistake: 'formula-wrong-sign',
            why: 'This is ∫v du − uv, the negative of the formula.',
          },
          {
            latex: '\\left[-\\frac{x}{2}\\cos(2x)\\right]_0^{\\pi/2} + \\frac{1}{2}\\int_0^{\\pi/2}x\\cos(2x)\\,dx',
            mistake: 'ibp-du-wrong',
            why: 'du = dx for u = x; the extra factor x means u was used instead of du.',
          },
        ],
        correct: 0,
        explanation: '$uv = -\\frac{x}{2}\\cos(2x)$ and $-\\int v\\,du = +\\frac12\\int\\cos(2x)\\,dx$, both over $[0, \\frac{\\pi}{2}]$.',
        result: { latex: '\\int_0^{\\pi/2} x\\sin(2x)\\,dx = \\left[-\\frac{x}{2}\\cos(2x)\\right]_0^{\\pi/2} + \\frac{1}{2}\\int_0^{\\pi/2}\\cos(2x)\\,dx' },
      },
      {
        prompt: 'Evaluate. What is the value of the integral?',
        options: [
          { latex: '\\frac{\\pi}{4}', expr: 'pi/4' },
          {
            latex: '-\\frac{\\pi}{4}',
            expr: '-pi/4',
            mistake: 'ftc-order-swapped',
            why: 'The value at π/2 was subtracted from the value at 0 instead of the other way round.',
          },
          {
            latex: '0',
            expr: '0',
            mistake: 'arithmetic-error',
            why: 'cos(π) = −1, not 0; the boundary term is −(π/4)(−1) = π/4.',
          },
          {
            latex: '\\frac{1}{4}',
            expr: '1/4',
            mistake: 'arithmetic-error',
            why: 'At x = π/2 the angle 2x is π; using cos(π/2) = 0 and sin(π/2) = 1 instead gives ¼.',
          },
          {
            latex: '\\frac{\\pi}{4} - \\frac{1}{2}',
            expr: 'pi/4 - 1/2',
            mistake: 'trig-antiderivative-swapped',
            why: '∫cos(2x) dx = ½sin(2x); using ½cos(2x) gives ¼(cos π − cos 0) = −½ for the second part.',
          },
          {
            latex: '\\frac{\\pi}{2}',
            expr: 'pi/2',
            mistake: 'coefficient-mishandled',
            why: 'The ½ in −(x/2)cos(2x) was dropped when plugging in π/2.',
          },
        ],
        correct: 0,
        explanation: '$-\\frac{\\pi}{4}\\cos\\pi - 0 = \\frac{\\pi}{4}$, and $\\frac14\\sin(2x)\\big|_0^{\\pi/2} = \\frac14(\\sin\\pi - \\sin 0) = 0$.',
        result: { latex: '= \\left(-\\frac{\\pi}{4}\\cos\\pi - 0\\right) + \\frac{1}{4}\\sin(2x)\\Big|_0^{\\pi/2} = \\frac{\\pi}{4} + 0 = \\frac{\\pi}{4}' },
        check: { kind: 'value', expected: 'pi/4' },
      },
    ],
    final: {
      latex: '\\frac{\\pi}{4}',
      expr: 'pi/4',
      check: { kind: 'definite-integral', integrand: 'x*sin(2*x)', lower: '0', upper: 'pi/2' },
      recap: 'LIATE picks $u = x$ (algebraic before trig); in a definite integral the boundary term $uv$ is evaluated between the limits as well.',
    },
  },

  // ── 3. Repeated IBP: ∫ x² e^{3x} dx ───────────────────────────────────────────────────────
  {
    id: 'ip-s-03',
    topic: 'ibp',
    title: 'Integrating by parts twice: x²e³ˣ',
    difficulty: 2,
    statement: { text: 'Evaluate the integral.', latex: '\\int x^2e^{3x}\\,dx' },
    steps: [
      {
        prompt: 'Following LIATE, choose $u$ and $dv$.',
        options: [
          { latex: 'u = x^2,\\ dv = e^{3x}\\,dx', expr: '[x^2, exp(3*x)*dx]' },
          {
            latex: 'u = e^{3x},\\ dv = x^2\\,dx',
            expr: '[exp(3*x), x^2*dx]',
            mistake: 'liate-misordered',
            why: 'Exponential is last in LIATE; with dv = x² dx the power of x grows to x³/3.',
          },
          {
            latex: 'u = x^2,\\ dv = dx',
            expr: '[x^2, dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor e^{3x} is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = e^{3x},\\ dv = dx',
            expr: '[exp(3*x), dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor x² is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = x^2,\\ dv = \\frac{1}{3}e^{3x}\\,dx',
            expr: '[x^2, exp(3*x)/3*dx]',
            mistake: 'ibp-v-wrong',
            why: '⅓e^{3x} is v, the antiderivative; dv is e^{3x} dx as written in the integrand.',
          },
        ],
        correct: 0,
        explanation: 'A comes before E: differentiating $u = x^2$ lowers the power, and $dv = e^{3x}\\,dx$ integrates easily.',
        result: { latex: 'u = x^2,\\quad dv = e^{3x}\\,dx' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'The new integral is $\\int v\\,du$. What is $v\\,du$?',
        options: [
          { latex: '\\frac{2}{3}xe^{3x}\\,dx', expr: '2/3*x*exp(3*x)*dx' },
          {
            latex: '6xe^{3x}\\,dx',
            expr: '6*x*exp(3*x)*dx',
            mistake: 'ibp-v-wrong',
            why: 'v was taken as 3e^{3x}, the derivative of e^{3x}; v = ∫e^{3x} dx = ⅓e^{3x}.',
          },
          {
            latex: '2xe^{3x}\\,dx',
            expr: '2*x*exp(3*x)*dx',
            mistake: 'exp-antiderivative-wrong',
            why: '∫e^{3x} dx = ⅓e^{3x}; with v = e^{3x} the factor ⅓ is missing.',
          },
          {
            latex: '\\frac{1}{3}xe^{3x}\\,dx',
            expr: '1/3*x*exp(3*x)*dx',
            mistake: 'ibp-du-wrong',
            why: 'd(x²) = 2x dx; taking du = x dx loses the factor 2.',
          },
          {
            latex: '\\frac{1}{3}x^2e^{3x}\\,dx',
            expr: '1/3*x^2*exp(3*x)*dx',
            mistake: 'ibp-formula-wrong',
            why: 'This is v times u; the new integral uses du = 2x dx, not u = x².',
          },
        ],
        correct: 0,
        explanation: '$du = 2x\\,dx$ and $v = \\frac13e^{3x}$, so $v\\,du = \\frac23xe^{3x}\\,dx$.',
        result: { latex: 'du = 2x\\,dx,\\quad v = \\frac{1}{3}e^{3x},\\quad v\\,du = \\frac{2}{3}xe^{3x}\\,dx' },
        check: { kind: 'value', expected: 'exp(3*x)/3*2*x*dx' },
      },
      {
        prompt: 'Apply the integration by parts formula.',
        options: [
          { latex: '\\frac{1}{3}x^2e^{3x} - \\frac{2}{3}\\int xe^{3x}\\,dx', expr: 'x^2*exp(3*x)/3 - 2/3*indefinite(x*exp(3*x), x)' },
          {
            latex: '\\frac{1}{3}x^2e^{3x} + \\frac{2}{3}\\int xe^{3x}\\,dx',
            expr: 'x^2*exp(3*x)/3 + 2/3*indefinite(x*exp(3*x), x)',
            mistake: 'ibp-sign-error',
            why: 'The formula is uv − ∫v du; the new integral was added.',
          },
          {
            latex: '-\\frac{1}{3}x^2e^{3x} + \\frac{2}{3}\\int xe^{3x}\\,dx',
            expr: '-x^2*exp(3*x)/3 + 2/3*indefinite(x*exp(3*x), x)',
            mistake: 'formula-wrong-sign',
            why: 'This is ∫v du − uv, the negative of the formula.',
          },
          {
            latex: '\\frac{1}{3}x^2e^{3x} - \\int x^2e^{3x}\\,dx',
            expr: 'x^2*exp(3*x)/3 - indefinite(x^2*exp(3*x), x)',
            mistake: 'ibp-formula-wrong',
            why: 'The new integral is ∫v du, not ∫u dv again; this just repeats the original problem.',
          },
          {
            latex: 'x^2e^{3x} - \\frac{2}{3}\\int xe^{3x}\\,dx',
            expr: 'x^2*exp(3*x) - 2/3*indefinite(x*exp(3*x), x)',
            mistake: 'coefficient-mishandled',
            why: 'The boundary term is uv = x²·⅓e^{3x}; the ⅓ from v was dropped there.',
          },
        ],
        correct: 0,
        explanation: '$uv - \\int v\\,du = \\frac13x^2e^{3x} - \\frac23\\int xe^{3x}\\,dx$; the new integral has a lower power of $x$.',
        result: { latex: '\\int x^2e^{3x}\\,dx = \\frac{1}{3}x^2e^{3x} - \\frac{2}{3}\\int xe^{3x}\\,dx' },
        check: { kind: 'identity', lhs: 'x^2*exp(3*x)/3 - indefinite(2/3*x*exp(3*x), x)' },
      },
      {
        prompt: 'The new integral still needs integration by parts ($u = x$, $dv = e^{3x}\\,dx$). Evaluate $\\int xe^{3x}\\,dx$.',
        options: [
          { latex: '\\frac{1}{3}xe^{3x} - \\frac{1}{9}e^{3x} + C', expr: 'x*exp(3*x)/3 - exp(3*x)/9' },
          {
            latex: '\\frac{1}{3}xe^{3x} + \\frac{1}{9}e^{3x} + C',
            expr: 'x*exp(3*x)/3 + exp(3*x)/9',
            mistake: 'ibp-sign-error',
            why: 'The formula subtracts ∫v du = ∫⅓e^{3x} dx; it was added.',
          },
          {
            latex: '\\frac{1}{3}xe^{3x} - \\frac{1}{3}e^{3x} + C',
            expr: 'x*exp(3*x)/3 - exp(3*x)/3',
            mistake: 'exp-antiderivative-wrong',
            why: '∫⅓e^{3x} dx = (1/9)e^{3x}; the second factor ⅓ was dropped.',
          },
          {
            latex: '\\frac{1}{3}xe^{3x} + C',
            expr: 'x*exp(3*x)/3',
            mistake: 'ibp-formula-wrong',
            why: 'Only uv was kept; the term −∫⅓e^{3x} dx was dropped.',
          },
          {
            latex: '\\frac{x^2}{6}e^{3x} + C',
            expr: 'x^2/6*exp(3*x)',
            mistake: 'product-rule-integral',
            why: 'x and e^{3x} were integrated separately and multiplied; there is no product rule for integrals.',
          },
          {
            latex: '3xe^{3x} - 9e^{3x} + C',
            expr: '3*x*exp(3*x) - 9*exp(3*x)',
            mistake: 'ibp-v-wrong',
            why: 'Both antiderivatives of e^{3x} were computed by multiplying by 3 (the derivative rule) instead of dividing.',
          },
        ],
        correct: 0,
        explanation: '$u = x$, $v = \\frac13e^{3x}$: $\\frac13xe^{3x} - \\frac13\\int e^{3x}\\,dx = \\frac13xe^{3x} - \\frac19e^{3x} + C$.',
        result: { latex: '\\int xe^{3x}\\,dx = \\frac{1}{3}xe^{3x} - \\frac{1}{9}e^{3x} + C' },
        check: { kind: 'antiderivative', integrand: 'x*exp(3*x)' },
      },
      {
        prompt: 'Substitute back and simplify.',
        options: [
          {
            latex: '\\frac{1}{3}x^2e^{3x} - \\frac{2}{9}xe^{3x} + \\frac{2}{27}e^{3x} + C',
            expr: 'x^2*exp(3*x)/3 - 2*x*exp(3*x)/9 + 2*exp(3*x)/27',
          },
          {
            latex: '\\frac{1}{3}x^2e^{3x} - \\frac{2}{9}xe^{3x} - \\frac{2}{27}e^{3x} + C',
            expr: 'x^2*exp(3*x)/3 - 2*x*exp(3*x)/9 - 2*exp(3*x)/27',
            mistake: 'ibp-tabular-sign',
            why: '−⅔ · (−(1/9)e^{3x}) = +(2/27)e^{3x}; the signs must alternate +, −, +.',
          },
          {
            latex: '\\frac{1}{3}x^2e^{3x} + \\frac{2}{9}xe^{3x} + \\frac{2}{27}e^{3x} + C',
            expr: 'x^2*exp(3*x)/3 + 2*x*exp(3*x)/9 + 2*exp(3*x)/27',
            mistake: 'ibp-tabular-sign',
            why: 'Every term got a + sign; the middle term comes from −⅔ · ⅓xe^{3x}.',
          },
          {
            latex: '\\frac{1}{3}x^2e^{3x} - \\frac{2}{9}xe^{3x} + \\frac{1}{9}e^{3x} + C',
            expr: 'x^2*exp(3*x)/3 - 2*x*exp(3*x)/9 + exp(3*x)/9',
            mistake: 'coefficient-mishandled',
            why: 'The ⅔ was multiplied into the first term of the bracket only; it also multiplies −(1/9)e^{3x}.',
          },
          {
            latex: '\\frac{1}{3}x^2e^{3x} - \\frac{2}{9}xe^{3x} + C',
            expr: 'x^2*exp(3*x)/3 - 2*x*exp(3*x)/9',
            mistake: 'ibp-stopped-early',
            why: 'The −(1/9)e^{3x} part of the second integration by parts was dropped, so the last term is missing.',
          },
        ],
        correct: 0,
        explanation: '$\\frac13x^2e^{3x} - \\frac23\\left(\\frac13xe^{3x} - \\frac19e^{3x}\\right) = \\frac13x^2e^{3x} - \\frac29xe^{3x} + \\frac{2}{27}e^{3x}$.',
        result: {
          latex: '\\int x^2e^{3x}\\,dx = \\frac{1}{3}x^2e^{3x} - \\frac{2}{3}\\left(\\frac{1}{3}xe^{3x} - \\frac{1}{9}e^{3x}\\right) + C = \\frac{1}{3}x^2e^{3x} - \\frac{2}{9}xe^{3x} + \\frac{2}{27}e^{3x} + C',
        },
        check: { kind: 'antiderivative', integrand: 'x^2*exp(3*x)' },
      },
    ],
    final: {
      latex: '\\frac{1}{3}x^2e^{3x} - \\frac{2}{9}xe^{3x} + \\frac{2}{27}e^{3x} + C',
      expr: 'x^2*exp(3*x)/3 - 2*x*exp(3*x)/9 + 2*exp(3*x)/27',
      check: { kind: 'antiderivative', integrand: 'x^2*exp(3*x)' },
      recap: 'Choose $u = x^2$ (A before E) and integrate by parts twice; each round lowers the power of $x$, and the signs alternate $+,-,+$.',
    },
  },

  // ── 4. Cyclic IBP: ∫ e^{2x} cos(3x) dx ──────────────────────────────────────────────────
  {
    id: 'ip-s-04',
    topic: 'ibp',
    title: 'The integral reappears: e²ˣcos 3x',
    difficulty: 2,
    statement: { text: 'Evaluate $I = \\int e^{2x}\\cos(3x)\\,dx$.', latex: '\\int e^{2x}\\cos(3x)\\,dx' },
    steps: [
      {
        prompt: 'Following LIATE, choose $u$ and $dv$.',
        options: [
          { latex: 'u = \\cos(3x),\\ dv = e^{2x}\\,dx', expr: '[cos(3*x), exp(2*x)*dx]' },
          {
            latex: 'u = e^{2x},\\ dv = \\cos(3x)\\,dx',
            expr: '[exp(2*x), cos(3*x)*dx]',
            mistake: 'liate-misordered',
            why: 'LIATE puts trigonometric before exponential, so cos(3x) is u; this swap is not the LIATE choice.',
          },
          {
            latex: 'u = \\cos(3x),\\ dv = dx',
            expr: '[cos(3*x), dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor e^{2x} is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = e^{2x},\\ dv = dx',
            expr: '[exp(2*x), dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor cos(3x) is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = \\cos(3x),\\ dv = \\frac{1}{2}e^{2x}\\,dx',
            expr: '[cos(3*x), exp(2*x)/2*dx]',
            mistake: 'ibp-v-wrong',
            why: '½e^{2x} is v, the antiderivative; dv is e^{2x} dx as written in the integrand.',
          },
        ],
        correct: 0,
        explanation: 'T comes before E: $u = \\cos(3x)$ and $dv = e^{2x}\\,dx$, as in the lecture example.',
        result: { latex: 'u = \\cos(3x),\\quad dv = e^{2x}\\,dx' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'The new integral is $\\int v\\,du$. What is $v\\,du$?',
        options: [
          { latex: '-\\frac{3}{2}e^{2x}\\sin(3x)\\,dx', expr: '-3/2*exp(2*x)*sin(3*x)*dx' },
          {
            latex: '\\frac{3}{2}e^{2x}\\sin(3x)\\,dx',
            expr: '3/2*exp(2*x)*sin(3*x)*dx',
            mistake: 'sign-error-derivative',
            why: 'd(cos 3x) = −3 sin(3x) dx; the minus sign of the cosine derivative was lost.',
          },
          {
            latex: '-\\frac{1}{2}e^{2x}\\sin(3x)\\,dx',
            expr: '-1/2*exp(2*x)*sin(3*x)*dx',
            mistake: 'chain-rule-missing',
            why: 'The inner derivative 3 of cos(3x) was dropped from du.',
          },
          {
            latex: '-6e^{2x}\\sin(3x)\\,dx',
            expr: '-6*exp(2*x)*sin(3*x)*dx',
            mistake: 'ibp-v-wrong',
            why: 'v was taken as 2e^{2x}, the derivative of e^{2x}; v = ∫e^{2x} dx = ½e^{2x}.',
          },
          {
            latex: '-3e^{2x}\\sin(3x)\\,dx',
            expr: '-3*exp(2*x)*sin(3*x)*dx',
            mistake: 'exp-antiderivative-wrong',
            why: '∫e^{2x} dx = ½e^{2x}; with v = e^{2x} the factor ½ is missing.',
          },
        ],
        correct: 0,
        explanation: '$du = -3\\sin(3x)\\,dx$ and $v = \\frac12e^{2x}$, so $v\\,du = -\\frac32e^{2x}\\sin(3x)\\,dx$.',
        result: { latex: 'du = -3\\sin(3x)\\,dx,\\quad v = \\frac{1}{2}e^{2x},\\quad v\\,du = -\\frac{3}{2}e^{2x}\\sin(3x)\\,dx' },
        check: { kind: 'value', expected: 'exp(2*x)/2*(-3*sin(3*x))*dx' },
      },
      {
        prompt: 'Apply the formula once.',
        options: [
          {
            latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{2}\\int e^{2x}\\sin(3x)\\,dx',
            expr: 'exp(2*x)*cos(3*x)/2 + 3/2*indefinite(exp(2*x)*sin(3*x), x)',
          },
          {
            latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) - \\frac{3}{2}\\int e^{2x}\\sin(3x)\\,dx',
            expr: 'exp(2*x)*cos(3*x)/2 - 3/2*indefinite(exp(2*x)*sin(3*x), x)',
            mistake: 'ibp-sign-error',
            why: '−∫v du = −∫(−(3/2)e^{2x} sin 3x) dx = +(3/2)∫e^{2x} sin(3x) dx; the two minus signs cancel.',
          },
          {
            latex: 'I = -\\frac{1}{2}e^{2x}\\cos(3x) - \\frac{3}{2}\\int e^{2x}\\sin(3x)\\,dx',
            expr: '-exp(2*x)*cos(3*x)/2 - 3/2*indefinite(exp(2*x)*sin(3*x), x)',
            mistake: 'formula-wrong-sign',
            why: 'This is ∫v du − uv, the negative of the formula.',
          },
          {
            latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{2}\\int e^{2x}\\cos(3x)\\,dx',
            expr: 'exp(2*x)*cos(3*x)/2 + 3/2*indefinite(exp(2*x)*cos(3*x), x)',
            mistake: 'ibp-formula-wrong',
            why: 'The new integral must contain du, which has sin(3x); keeping cos(3x) reuses u.',
          },
          {
            latex: 'I = e^{2x}\\cos(3x) + \\frac{3}{2}\\int e^{2x}\\sin(3x)\\,dx',
            expr: 'exp(2*x)*cos(3*x) + 3/2*indefinite(exp(2*x)*sin(3*x), x)',
            mistake: 'coefficient-mishandled',
            why: 'The boundary term is uv = cos(3x) · ½e^{2x}; the ½ from v was dropped there.',
          },
        ],
        correct: 0,
        explanation: '$uv - \\int v\\,du = \\frac12e^{2x}\\cos(3x) + \\frac32\\int e^{2x}\\sin(3x)\\,dx$.',
        result: { latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{2}\\int e^{2x}\\sin(3x)\\,dx' },
        check: { kind: 'identity', lhs: 'exp(2*x)*cos(3*x)/2 - indefinite(-3/2*exp(2*x)*sin(3*x), x)' },
      },
      {
        prompt: 'Integrate by parts again, keeping trig as $u$: $u = \\sin(3x)$, $dv = e^{2x}\\,dx$. Then $\\int e^{2x}\\sin(3x)\\,dx =$',
        options: [
          {
            latex: '\\frac{1}{2}e^{2x}\\sin(3x) - \\frac{3}{2}\\int e^{2x}\\cos(3x)\\,dx',
            expr: 'exp(2*x)*sin(3*x)/2 - 3/2*indefinite(exp(2*x)*cos(3*x), x)',
          },
          {
            latex: '\\frac{1}{2}e^{2x}\\sin(3x) + \\frac{3}{2}\\int e^{2x}\\cos(3x)\\,dx',
            expr: 'exp(2*x)*sin(3*x)/2 + 3/2*indefinite(exp(2*x)*cos(3*x), x)',
            mistake: 'ibp-sign-error',
            why: 'This time du = +3cos(3x) dx, so −∫v du keeps its minus sign.',
          },
          {
            latex: '\\frac{1}{2}e^{2x}\\sin(3x) - \\frac{1}{2}\\int e^{2x}\\cos(3x)\\,dx',
            expr: 'exp(2*x)*sin(3*x)/2 - 1/2*indefinite(exp(2*x)*cos(3*x), x)',
            mistake: 'chain-rule-missing',
            why: 'd(sin 3x) = 3cos(3x) dx; the inner factor 3 was dropped.',
          },
          {
            latex: '\\frac{1}{2}e^{2x}\\sin(3x) - \\frac{3}{2}\\int e^{2x}\\sin(3x)\\,dx',
            expr: 'exp(2*x)*sin(3*x)/2 - 3/2*indefinite(exp(2*x)*sin(3*x), x)',
            mistake: 'ibp-formula-wrong',
            why: 'The new integral must contain du, which has cos(3x); keeping sin(3x) reuses u.',
          },
          {
            latex: '\\frac{1}{2}e^{2x}\\sin(3x) - 3\\int e^{2x}\\cos(3x)\\,dx',
            expr: 'exp(2*x)*sin(3*x)/2 - 3*indefinite(exp(2*x)*cos(3*x), x)',
            mistake: 'coefficient-mishandled',
            why: 'v du = ½e^{2x} · 3cos(3x) dx; the ½ from v was dropped inside the integral.',
          },
        ],
        correct: 0,
        explanation: '$du = 3\\cos(3x)\\,dx$, $v = \\frac12e^{2x}$: $\\frac12e^{2x}\\sin(3x) - \\frac32\\int e^{2x}\\cos(3x)\\,dx$.',
        result: { latex: '\\int e^{2x}\\sin(3x)\\,dx = \\frac{1}{2}e^{2x}\\sin(3x) - \\frac{3}{2}\\int e^{2x}\\cos(3x)\\,dx' },
        check: { kind: 'identity', lhs: 'exp(2*x)*sin(3*x)/2 - indefinite(exp(2*x)/2*3*cos(3*x), x)' },
      },
      {
        prompt: 'Substitute this into the first result. The original integral $I$ reappears. Which equation do you get?',
        options: [
          { latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{4}e^{2x}\\sin(3x) - \\frac{9}{4}I' },
          {
            latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{4}e^{2x}\\sin(3x) + \\frac{9}{4}I',
            mistake: 'sign-error',
            why: '(3/2) · (−3/2) = −9/4; the product of the coefficients is negative.',
          },
          {
            latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{1}{2}e^{2x}\\sin(3x) - \\frac{9}{4}I',
            mistake: 'coefficient-mishandled',
            why: 'The 3/2 in front of the bracket was multiplied into −(3/2)I but not into ½e^{2x}sin(3x).',
          },
          {
            latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{4}e^{2x}\\sin(3x) - \\frac{3}{2}I',
            mistake: 'algebra-error',
            why: 'The 3/2 in front of the bracket also multiplies −(3/2)I, giving −(9/4)I.',
          },
          {
            latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{4}e^{2x}\\sin(3x) - \\frac{9}{4}\\int e^{2x}\\sin(3x)\\,dx',
            mistake: 'ibp-cyclic-algebra',
            why: 'The integral that reappears is ∫e^{2x}cos(3x) dx, which is I itself; recognizing it is what lets you solve for I.',
          },
        ],
        correct: 0,
        explanation: '$\\frac32\\left(\\frac12e^{2x}\\sin(3x) - \\frac32 I\\right) = \\frac34e^{2x}\\sin(3x) - \\frac94I$.',
        result: { latex: 'I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{4}e^{2x}\\sin(3x) - \\frac{9}{4}I' },
      },
      {
        prompt: 'Solve for $I$.',
        options: [
          {
            latex: '\\frac{2}{13}e^{2x}\\cos(3x) + \\frac{3}{13}e^{2x}\\sin(3x) + C',
            expr: '2/13*exp(2*x)*cos(3*x) + 3/13*exp(2*x)*sin(3*x)',
          },
          {
            latex: '-\\frac{2}{5}e^{2x}\\cos(3x) - \\frac{3}{5}e^{2x}\\sin(3x) + C',
            expr: '-2/5*exp(2*x)*cos(3*x) - 3/5*exp(2*x)*sin(3*x)',
            mistake: 'ibp-cyclic-algebra',
            why: '(9/4)I was subtracted from both sides instead of added, giving (1 − 9/4)I = −(5/4)I.',
          },
          {
            latex: '\\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{4}e^{2x}\\sin(3x) + C',
            expr: '1/2*exp(2*x)*cos(3*x) + 3/4*exp(2*x)*sin(3*x)',
            mistake: 'ibp-cyclic-algebra',
            why: 'The −(9/4)I on the right was ignored; it must be moved to the left and combined with I.',
          },
          {
            latex: '\\frac{2}{9}e^{2x}\\cos(3x) + \\frac{1}{3}e^{2x}\\sin(3x) + C',
            expr: '2/9*exp(2*x)*cos(3*x) + 1/3*exp(2*x)*sin(3*x)',
            mistake: 'ibp-cyclic-algebra',
            why: 'The right side was divided by 9/4 instead of by 1 + 9/4 = 13/4.',
          },
          {
            latex: '\\frac{13}{8}e^{2x}\\cos(3x) + \\frac{39}{16}e^{2x}\\sin(3x) + C',
            expr: '13/8*exp(2*x)*cos(3*x) + 39/16*exp(2*x)*sin(3*x)',
            mistake: 'ibp-cyclic-algebra',
            why: 'From (13/4)I = …, the right side was multiplied by 13/4 instead of by 4/13.',
          },
        ],
        correct: 0,
        explanation: 'Add $\\frac94I$ to both sides: $\\frac{13}{4}I = \\frac12e^{2x}\\cos(3x) + \\frac34e^{2x}\\sin(3x)$, then multiply by $\\frac{4}{13}$.',
        result: {
          latex: '\\frac{13}{4}I = \\frac{1}{2}e^{2x}\\cos(3x) + \\frac{3}{4}e^{2x}\\sin(3x) \\Rightarrow I = \\frac{2}{13}e^{2x}\\cos(3x) + \\frac{3}{13}e^{2x}\\sin(3x) + C',
        },
        check: { kind: 'antiderivative', integrand: 'exp(2*x)*cos(3*x)' },
      },
    ],
    final: {
      latex: '\\frac{2}{13}e^{2x}\\cos(3x) + \\frac{3}{13}e^{2x}\\sin(3x) + C',
      expr: '2/13*exp(2*x)*cos(3*x) + 3/13*exp(2*x)*sin(3*x)',
      check: { kind: 'antiderivative', integrand: 'exp(2*x)*cos(3*x)' },
      recap: 'Integrate by parts twice with the same roles (trig as $u$); when $I$ reappears, add $\\frac94I$ to both sides and divide by $\\frac{13}{4}$.',
    },
  },

  // ── 5. Substitution first: ∫ x ln(x²) dx ────────────────────────────────────────────────
  {
    id: 'ip-s-05',
    topic: 'ibp',
    title: 'Substitution first: x ln(x²)',
    difficulty: 1,
    statement: { text: 'Evaluate the integral. Before integrating by parts, check whether a substitution helps.', latex: '\\int x\\ln(x^2)\\,dx' },
    steps: [
      {
        prompt: 'Which substitution turns this into a basic integration by parts problem?',
        options: [
          { text: '$w = x^2$, because $dw = 2x\\,dx$ and the factor $x\\,dx$ is present' },
          {
            text: '$w = \\ln(x^2)$, because its derivative $\\frac{2}{x}$ is present',
            mistake: 'u-choice-wrong',
            why: 'The derivative of ln(x²) is 2/x, but the integrand has a factor x, not 1/x.',
          },
          {
            text: '$w = 2x$, because $2x$ is the derivative of $x^2$',
            mistake: 'u-choice-wrong',
            why: 'w = 2x does not simplify ln(x²); the inner function x², whose derivative is present, should be w.',
          },
          {
            text: 'No substitution helps; integrate by parts with $u = x$, $dv = \\ln(x^2)\\,dx$',
            mistake: 'liate-misordered',
            why: 'A substitution is available, and logarithmic comes before algebraic: dv = ln(x²) dx would need its own integration by parts.',
          },
          {
            text: '$w = x$, because $dw = dx$',
            mistake: 'u-choice-wrong',
            why: 'w = x changes nothing; choose the inner function x² whose derivative 2x appears.',
          },
        ],
        correct: 0,
        explanation: 'The factor $x\\,dx = \\frac12\\,dw$ is present, and $\\ln(x^2)$ becomes $\\ln(w)$.',
        result: { latex: 'w = x^2,\\quad dw = 2x\\,dx' },
      },
      {
        prompt: 'Rewrite the integral in terms of $w$.',
        variable: 'w',
        options: [
          { latex: '\\frac{1}{2}\\int \\ln(w)\\,dw', expr: 'indefinite(log(w), w)/2' },
          {
            latex: '2\\int \\ln(w)\\,dw',
            expr: '2*indefinite(log(w), w)',
            mistake: 'du-constant-wrong',
            why: 'x dx = dw/2, not 2 dw.',
          },
          {
            latex: '\\int \\ln(w)\\,dw',
            expr: 'indefinite(log(w), w)',
            mistake: 'du-constant-wrong',
            why: 'The ½ from x dx = dw/2 was dropped.',
          },
          {
            latex: '\\frac{1}{2}\\int \\sqrt{w}\\ln(w)\\,dw',
            expr: 'indefinite(sqrt(w)*log(w), w)/2',
            mistake: 'leftover-x-in-u-integral',
            why: 'dw = 2x dx absorbs the factor x; replacing dx by dw/2 leaves an extra x = √w behind.',
          },
          {
            latex: '\\frac{1}{2}\\int \\frac{\\ln(w)}{\\sqrt{w}}\\,dw',
            expr: 'indefinite(log(w)/sqrt(w), w)/2',
            mistake: 'algebra-error',
            why: 'dx = dw/(2√w) is right, but the factor x = √w in front of the log was dropped.',
          },
        ],
        correct: 0,
        explanation: '$x\\,dx = \\frac12\\,dw$ and $\\ln(x^2) = \\ln(w)$, so the integral is $\\frac12\\int\\ln(w)\\,dw$.',
        result: { latex: '\\int x\\ln(x^2)\\,dx = \\frac{1}{2}\\int \\ln(w)\\,dw' },
        check: { kind: 'none', reason: 'rewriting after a substitution; options are compared by integrand' },
      },
      {
        prompt: 'Integrate by parts with $u = \\ln(w)$, $dv = dw$. Then $\\int \\ln(w)\\,dw =$',
        variable: 'w',
        options: [
          { latex: 'w\\ln(w) - w + C', expr: 'w*log(w) - w' },
          {
            latex: 'w\\ln(w) + w + C',
            expr: 'w*log(w) + w',
            mistake: 'ibp-sign-error',
            why: 'The formula subtracts ∫v du = ∫w · (1/w) dw = w.',
          },
          {
            latex: 'w\\ln(w) + C',
            expr: 'w*log(w)',
            mistake: 'ibp-formula-wrong',
            why: 'Only uv was kept; the term −∫w · (1/w) dw = −w was dropped.',
          },
          {
            latex: '\\frac{(\\ln(w))^2}{2} + C',
            expr: 'log(w)^2/2',
            mistake: 'dx-not-replaced',
            why: 'The power rule was applied to ln(w) as if dw/w were present; that is ∫ln(w)/w dw.',
          },
          {
            latex: 'w\\ln(w) - \\frac{w^2}{2} + C',
            expr: 'w*log(w) - w^2/2',
            mistake: 'ibp-du-wrong',
            why: 'd(ln w) was taken as dw instead of dw/w, so ∫v du became ∫w dw.',
          },
          {
            latex: 'w\\ln(w) - \\ln(w) + C',
            expr: 'w*log(w) - log(w)',
            mistake: 'ibp-formula-wrong',
            why: 'In ∫v du = ∫w · (1/w) dw the factor v = w was dropped, leaving ∫dw/w.',
          },
        ],
        correct: 0,
        explanation: '$u = \\ln(w)$, $v = w$: $w\\ln(w) - \\int w\\cdot\\frac1w\\,dw = w\\ln(w) - w + C$.',
        result: { latex: '\\int \\ln(w)\\,dw = w\\ln(w) - w + C' },
        check: { kind: 'antiderivative', integrand: 'log(w)' },
      },
      {
        prompt: 'Back-substitute $w = x^2$ into $\\frac{1}{2}\\left(w\\ln(w) - w\\right) + C$.',
        options: [
          { latex: '\\frac{x^2}{2}\\ln(x^2) - \\frac{x^2}{2} + C', expr: 'x^2/2*log(x^2) - x^2/2' },
          {
            latex: '\\frac{x^2}{2}\\ln(x^2) - x^2 + C',
            expr: 'x^2/2*log(x^2) - x^2',
            mistake: 'coefficient-mishandled',
            why: 'The ½ multiplies both terms: ½(w ln w − w).',
          },
          {
            latex: '\\frac{x^2}{2}\\ln(x) - \\frac{x^2}{2} + C',
            expr: 'x^2/2*log(x) - x^2/2',
            mistake: 'back-substitution-wrong',
            why: 'ln(w) becomes ln(x²), not ln(x).',
          },
          {
            latex: '\\frac{x}{2}\\ln(x) - \\frac{x}{2} + C',
            expr: 'x/2*log(x) - x/2',
            mistake: 'back-substitution-wrong',
            why: 'w stands for x², not x.',
          },
          {
            latex: '\\frac{1}{2}w\\ln(w) - \\frac{1}{2}w + C',
            expr: 'w*log(w)/2 - w/2',
            mistake: 'not-back-substituted',
            why: 'The answer must be written in x; w = x² was never substituted back.',
          },
        ],
        correct: 0,
        explanation: '$\\frac12\\left(x^2\\ln(x^2) - x^2\\right) = \\frac{x^2}{2}\\ln(x^2) - \\frac{x^2}{2}$.',
        result: { latex: '\\int x\\ln(x^2)\\,dx = \\frac{x^2}{2}\\ln(x^2) - \\frac{x^2}{2} + C' },
        check: { kind: 'antiderivative', integrand: 'x*log(x^2)' },
      },
    ],
    final: {
      latex: '\\frac{x^2}{2}\\ln(x^2) - \\frac{x^2}{2} + C',
      expr: 'x^2/2*log(x^2) - x^2/2',
      check: { kind: 'antiderivative', integrand: 'x*log(x^2)' },
      recap: 'Try substitution first: $w = x^2$ gives $\\frac12\\int\\ln(w)\\,dw$, a one-step integration by parts. (Integrating by parts directly with $u = \\ln(x^2)$, $dv = x\\,dx$ gives the same answer.)',
    },
  },

  // ── 6. Definite with a negative v: ∫₁⁵ ln(x)/x² dx ───────────────────────────────────────
  {
    id: 'ip-s-06',
    topic: 'ibp',
    title: 'Definite integral: ln x / x²',
    difficulty: 1,
    statement: { text: 'Evaluate the definite integral.', latex: '\\int_1^5 \\frac{\\ln(x)}{x^2}\\,dx' },
    steps: [
      {
        prompt: 'Following LIATE, choose $u$ and $dv$.',
        options: [
          { latex: 'u = \\ln(x),\\ dv = \\frac{1}{x^2}\\,dx', expr: '[log(x), dx/x^2]' },
          {
            latex: 'u = \\frac{1}{x^2},\\ dv = \\ln(x)\\,dx',
            expr: '[1/x^2, log(x)*dx]',
            mistake: 'liate-misordered',
            why: 'Logarithmic comes first; with dv = ln(x) dx you must integrate ln(x) by parts before you can even start.',
          },
          {
            latex: 'u = \\ln(x),\\ dv = dx',
            expr: '[log(x), dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor 1/x² is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = \\frac{1}{x^2},\\ dv = dx',
            expr: '[1/x^2, dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor ln(x) is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = \\ln(x),\\ dv = -\\frac{1}{x}\\,dx',
            expr: '[log(x), -dx/x]',
            mistake: 'ibp-v-wrong',
            why: '−1/x is v = ∫x⁻² dx; dv is the factor dx/x² from the integrand.',
          },
        ],
        correct: 0,
        explanation: 'L comes before A: $u = \\ln(x)$ and $dv = x^{-2}\\,dx$.',
        result: { latex: 'u = \\ln(x),\\quad dv = \\frac{1}{x^2}\\,dx' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'The new integrand is $v\\,du$. What is it?',
        options: [
          { latex: '-\\frac{1}{x^2}\\,dx', expr: '-dx/x^2' },
          {
            latex: '\\frac{1}{x^2}\\,dx',
            expr: 'dx/x^2',
            mistake: 'ibp-v-wrong',
            why: 'v = ∫x⁻² dx = x⁻¹/(−1) = −1/x; the minus sign was lost.',
          },
          {
            latex: '-\\frac{1}{3x^4}\\,dx',
            expr: '-dx/(3*x^4)',
            mistake: 'power-rule-int-exponent',
            why: 'Integrating x⁻² raises the exponent to −1; lowering it to −3 gives the wrong v = −1/(3x³).',
          },
          {
            latex: '-\\frac{2}{x^4}\\,dx',
            expr: '-2*dx/x^4',
            mistake: 'differentiated-instead',
            why: 'v was taken as −2/x³, the derivative of 1/x², instead of an antiderivative.',
          },
          {
            latex: '-\\frac{1}{x}\\,dx',
            expr: '-dx/x',
            mistake: 'ibp-du-wrong',
            why: 'd(ln x) = (1/x) dx; with du = dx the product is (−1/x) dx.',
          },
        ],
        correct: 0,
        explanation: '$du = \\frac{dx}{x}$ and $v = -\\frac1x$, so $v\\,du = -\\frac{dx}{x^2}$.',
        result: { latex: 'du = \\frac{1}{x}\\,dx,\\quad v = -\\frac{1}{x},\\quad v\\,du = -\\frac{1}{x^2}\\,dx' },
        check: { kind: 'value', expected: '-1/x*(1/x)*dx' },
      },
      {
        prompt: 'Apply $\\int_a^b u\\,dv = uv\\big|_a^b - \\int_a^b v\\,du$.',
        options: [
          { latex: '\\left[-\\frac{\\ln(x)}{x}\\right]_1^5 + \\int_1^5 \\frac{1}{x^2}\\,dx' },
          {
            latex: '\\left[-\\frac{\\ln(x)}{x}\\right]_1^5 - \\int_1^5 \\frac{1}{x^2}\\,dx',
            mistake: 'ibp-sign-error',
            why: 'v du = −dx/x², so −∫v du = +∫dx/x²; the minus signs cancel.',
          },
          {
            latex: '-\\frac{\\ln(x)}{x} + \\int_1^5 \\frac{1}{x^2}\\,dx',
            mistake: 'ibp-bounds-not-applied',
            why: 'The boundary term uv must also be evaluated from 1 to 5.',
          },
          {
            latex: '\\left[-\\frac{\\ln(x)}{x}\\right]_1^5 - \\int_1^5 \\frac{1}{x}\\,dx',
            mistake: 'ibp-formula-wrong',
            why: 'The factor v = −1/x was dropped from ∫v du, leaving −∫du = −∫dx/x.',
          },
          {
            latex: '\\left[\\frac{\\ln(x)}{x}\\right]_1^5 - \\int_1^5 \\frac{1}{x^2}\\,dx',
            mistake: 'formula-wrong-sign',
            why: 'This is ∫v du − uv, the negative of the formula.',
          },
        ],
        correct: 0,
        explanation: '$uv = -\\frac{\\ln(x)}{x}$ and $-\\int v\\,du = +\\int\\frac{dx}{x^2}$, both over $[1, 5]$.',
        result: { latex: '\\int_1^5 \\frac{\\ln(x)}{x^2}\\,dx = \\left[-\\frac{\\ln(x)}{x}\\right]_1^5 + \\int_1^5 \\frac{1}{x^2}\\,dx' },
      },
      {
        prompt: 'Evaluate.',
        options: [
          { latex: '\\frac{4}{5} - \\frac{\\ln 5}{5}', expr: '4/5 - log(5)/5' },
          {
            latex: '-\\frac{1}{5} - \\frac{\\ln 5}{5}',
            expr: '-1/5 - log(5)/5',
            mistake: 'ftc-not-subtracted',
            why: 'Evaluating −1/x from 1 to 5 gives −1/5 − (−1) = 4/5; the value at the lower limit was not subtracted.',
          },
          {
            latex: '-\\frac{4}{5} - \\frac{\\ln 5}{5}',
            expr: '-4/5 - log(5)/5',
            mistake: 'ftc-order-swapped',
            why: 'The integral of dx/x² was evaluated as F(1) − F(5) = −4/5.',
          },
          {
            latex: '\\frac{9}{5} - \\frac{\\ln 5}{5}',
            expr: '9/5 - log(5)/5',
            mistake: 'arithmetic-error',
            why: 'ln 1 = 0, not 1; the boundary term vanishes at x = 1.',
          },
          {
            latex: '\\frac{9}{5}\\ln 5',
            expr: '9/5*log(5)',
            mistake: 'ln-misapplied',
            why: '∫dx/x² = −1/x by the power rule; integrating it as ln(x²) gives 2 ln 5 instead of 4/5.',
          },
        ],
        correct: 0,
        explanation: '$\\left(-\\frac{\\ln 5}{5} + 0\\right) + \\left(-\\frac15 + 1\\right) = \\frac45 - \\frac{\\ln 5}{5}$.',
        result: {
          latex: '= \\left(-\\frac{\\ln 5}{5} + \\frac{\\ln 1}{1}\\right) + \\left[-\\frac{1}{x}\\right]_1^5 = -\\frac{\\ln 5}{5} + \\left(-\\frac{1}{5} + 1\\right) = \\frac{4}{5} - \\frac{\\ln 5}{5}',
        },
        check: { kind: 'value', expected: '4/5 - log(5)/5' },
      },
    ],
    final: {
      latex: '\\frac{4}{5} - \\frac{\\ln 5}{5}',
      expr: '4/5 - log(5)/5',
      check: { kind: 'definite-integral', integrand: 'log(x)/x^2', lower: '1', upper: '5' },
      recap: 'LIATE gives $u = \\ln(x)$, $dv = x^{-2}\\,dx$; with $v = -\\frac1x$ the two minus signs make the remaining integral $+\\int_1^5 x^{-2}\\,dx$, and $\\ln 1 = 0$ removes the lower boundary value.',
    },
  },

  // ── 7. Inverse trig times a power: ∫ x² tan⁻¹(x) dx ─────────────────────────────────────
  {
    id: 'ip-s-07',
    topic: 'ibp',
    title: 'Inverse trig first: x² tan⁻¹x',
    difficulty: 2,
    statement: { text: 'Evaluate the integral.', latex: '\\int x^2\\tan^{-1}(x)\\,dx' },
    domain: [0.2, 0.9],
    steps: [
      {
        prompt: 'Following LIATE, choose $u$ and $dv$.',
        options: [
          { latex: 'u = \\tan^{-1}(x),\\ dv = x^2\\,dx', expr: '[atan(x), x^2*dx]' },
          {
            latex: 'u = x^2,\\ dv = \\tan^{-1}(x)\\,dx',
            expr: '[x^2, atan(x)*dx]',
            mistake: 'liate-misordered',
            why: 'Inverse trig comes before algebraic; with dv = tan⁻¹(x) dx you would first have to integrate tan⁻¹(x) by parts.',
          },
          {
            latex: 'u = \\tan^{-1}(x),\\ dv = dx',
            expr: '[atan(x), dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor x² is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = x^2,\\ dv = dx',
            expr: '[x^2, dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor tan⁻¹(x) is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = \\tan^{-1}(x),\\ dv = \\frac{x^3}{3}\\,dx',
            expr: '[atan(x), x^3/3*dx]',
            mistake: 'ibp-v-wrong',
            why: 'x³/3 is v, the antiderivative; dv is x² dx as written in the integrand.',
          },
        ],
        correct: 0,
        explanation: 'I comes before A: $u = \\tan^{-1}(x)$ has an algebraic derivative, and $dv = x^2\\,dx$ integrates easily.',
        result: { latex: 'u = \\tan^{-1}(x),\\quad dv = x^2\\,dx' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'The new integral is $\\int v\\,du$. What is $v\\,du$?',
        options: [
          { latex: '\\frac{x^3}{3(1+x^2)}\\,dx', expr: 'x^3*dx/(3*(1+x^2))' },
          {
            latex: '\\frac{x^3}{3\\sqrt{1-x^2}}\\,dx',
            expr: 'x^3*dx/(3*sqrt(1-x^2))',
            mistake: 'inverse-trig-confused',
            why: 'du was taken as dx/√(1−x²), the derivative of arcsin; d(tan⁻¹x) = dx/(1+x²).',
          },
          {
            latex: '\\frac{2x}{1+x^2}\\,dx',
            expr: '2*x*dx/(1+x^2)',
            mistake: 'ibp-v-wrong',
            why: 'v must be ∫x² dx = x³/3; 2x is the derivative of x².',
          },
          {
            latex: '\\frac{x^3}{1+x^2}\\,dx',
            expr: 'x^3*dx/(1+x^2)',
            mistake: 'power-rule-int-coefficient',
            why: 'v = ∫x² dx = x³/3; the division by 3 was skipped.',
          },
          {
            latex: '-\\frac{x^3}{3}\\csc^2(x)\\,dx',
            expr: '-x^3/3*csc(x)^2*dx',
            mistake: 'inverse-trig-as-reciprocal',
            why: 'tan⁻¹(x) was read as 1/tan(x) = cot(x), whose derivative is −csc²(x); tan⁻¹ means arctan.',
          },
        ],
        correct: 0,
        explanation: '$du = \\frac{dx}{1+x^2}$ and $v = \\frac{x^3}{3}$, so $v\\,du = \\frac{x^3}{3(1+x^2)}\\,dx$.',
        result: { latex: 'du = \\frac{1}{1+x^2}\\,dx,\\quad v = \\frac{x^3}{3},\\quad v\\,du = \\frac{x^3}{3(1+x^2)}\\,dx' },
        check: { kind: 'value', expected: 'x^3/3*(1/(1+x^2))*dx' },
      },
      {
        prompt: 'Apply the integration by parts formula.',
        options: [
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\frac{1}{3}\\int \\frac{x^3}{1+x^2}\\,dx',
            expr: 'x^3/3*atan(x) - 1/3*indefinite(x^3/(1+x^2), x)',
          },
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) + \\frac{1}{3}\\int \\frac{x^3}{1+x^2}\\,dx',
            expr: 'x^3/3*atan(x) + 1/3*indefinite(x^3/(1+x^2), x)',
            mistake: 'ibp-sign-error',
            why: 'The formula subtracts ∫v du; the plus sign is wrong.',
          },
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\int \\frac{x^3}{1+x^2}\\,dx',
            expr: 'x^3/3*atan(x) - indefinite(x^3/(1+x^2), x)',
            mistake: 'coefficient-mishandled',
            why: 'v = x³/3 carries its ⅓ into ∫v du as well.',
          },
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\int \\frac{1}{1+x^2}\\,dx',
            expr: 'x^3/3*atan(x) - indefinite(1/(1+x^2), x)',
            mistake: 'ibp-formula-wrong',
            why: 'The factor v = x³/3 was dropped from ∫v du, leaving ∫du.',
          },
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\int x^2\\tan^{-1}(x)\\,dx',
            expr: 'x^3/3*atan(x) - indefinite(x^2*atan(x), x)',
            mistake: 'ibp-formula-wrong',
            why: 'The new integral is ∫v du, not ∫u dv again; this just restates the problem.',
          },
        ],
        correct: 0,
        explanation: '$uv - \\int v\\,du = \\frac{x^3}{3}\\tan^{-1}(x) - \\frac13\\int\\frac{x^3}{1+x^2}\\,dx$.',
        result: { latex: '\\int x^2\\tan^{-1}(x)\\,dx = \\frac{x^3}{3}\\tan^{-1}(x) - \\frac{1}{3}\\int \\frac{x^3}{1+x^2}\\,dx' },
        check: { kind: 'identity', lhs: 'x^3/3*atan(x) - indefinite(x^3/(3*(1+x^2)), x)' },
      },
      {
        prompt: 'Divide first: $\\frac{x^3}{1+x^2} = x - \\frac{x}{1+x^2}$. Then $\\int \\frac{x^3}{1+x^2}\\,dx =$',
        options: [
          { latex: '\\frac{x^2}{2} - \\frac{1}{2}\\ln(1+x^2) + C', expr: 'x^2/2 - log(1+x^2)/2' },
          {
            latex: '\\frac{x^2}{2} + \\frac{1}{2}\\ln(1+x^2) + C',
            expr: 'x^2/2 + log(1+x^2)/2',
            mistake: 'sign-error',
            why: 'The division leaves −x/(1+x²), whose antiderivative is −½ln(1+x²).',
          },
          {
            latex: '\\frac{x^2}{2} - \\ln(1+x^2) + C',
            expr: 'x^2/2 - log(1+x^2)',
            mistake: 'du-constant-wrong',
            why: 'With w = 1 + x², x dx = dw/2; the ½ was dropped.',
          },
          {
            latex: '\\frac{x^2}{2} - \\tan^{-1}(x) + C',
            expr: 'x^2/2 - atan(x)',
            mistake: 'formula-swapped',
            why: 'tan⁻¹(x) is ∫dx/(1+x²); with x in the numerator the antiderivative is ½ln(1+x²).',
          },
          {
            latex: '\\frac{x^4}{4}\\tan^{-1}(x) + C',
            expr: 'x^4/4*atan(x)',
            mistake: 'product-rule-integral',
            why: '(∫x³ dx)(∫dx/(1+x²)) was used; there is no product rule for integrals — divide first.',
          },
        ],
        correct: 0,
        explanation: '$\\int x\\,dx - \\int\\frac{x}{1+x^2}\\,dx = \\frac{x^2}{2} - \\frac12\\ln(1+x^2) + C$ (with $w = 1 + x^2$ in the second part).',
        result: { latex: '\\int \\frac{x^3}{1+x^2}\\,dx = \\int\\left(x - \\frac{x}{1+x^2}\\right)dx = \\frac{x^2}{2} - \\frac{1}{2}\\ln(1+x^2) + C' },
        check: { kind: 'antiderivative', integrand: 'x^3/(1+x^2)' },
      },
      {
        prompt: 'Substitute back and simplify.',
        options: [
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\frac{x^2}{6} + \\frac{1}{6}\\ln(1+x^2) + C',
            expr: 'x^3/3*atan(x) - x^2/6 + log(1+x^2)/6',
          },
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\frac{x^2}{6} - \\frac{1}{6}\\ln(1+x^2) + C',
            expr: 'x^3/3*atan(x) - x^2/6 - log(1+x^2)/6',
            mistake: 'sign-error',
            why: '−⅓ · (−½ln(1+x²)) = +⅙ln(1+x²); the minus was not distributed.',
          },
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\frac{x^2}{2} + \\frac{1}{2}\\ln(1+x^2) + C',
            expr: 'x^3/3*atan(x) - x^2/2 + log(1+x^2)/2',
            mistake: 'coefficient-mishandled',
            why: 'The factor ⅓ in front of the integral was dropped.',
          },
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\frac{x^2}{6} + \\frac{1}{2}\\ln(1+x^2) + C',
            expr: 'x^3/3*atan(x) - x^2/6 + log(1+x^2)/2',
            mistake: 'algebra-error',
            why: 'The ⅓ was applied to x²/2 only; it multiplies ½ln(1+x²) too.',
          },
          {
            latex: '\\frac{x^3}{3}\\tan^{-1}(x) + \\frac{x^2}{6} - \\frac{1}{6}\\ln(1+x^2) + C',
            expr: 'x^3/3*atan(x) + x^2/6 - log(1+x^2)/6',
            mistake: 'ibp-sign-error',
            why: 'The integral is subtracted in uv − ∫v du; adding it flips both of its terms.',
          },
        ],
        correct: 0,
        explanation: '$\\frac{x^3}{3}\\tan^{-1}(x) - \\frac13\\left(\\frac{x^2}{2} - \\frac12\\ln(1+x^2)\\right) = \\frac{x^3}{3}\\tan^{-1}(x) - \\frac{x^2}{6} + \\frac16\\ln(1+x^2)$.',
        result: { latex: '\\int x^2\\tan^{-1}(x)\\,dx = \\frac{x^3}{3}\\tan^{-1}(x) - \\frac{x^2}{6} + \\frac{1}{6}\\ln(1+x^2) + C' },
        check: { kind: 'antiderivative', integrand: 'x^2*atan(x)' },
      },
    ],
    final: {
      latex: '\\frac{x^3}{3}\\tan^{-1}(x) - \\frac{x^2}{6} + \\frac{1}{6}\\ln(1+x^2) + C',
      expr: 'x^3/3*atan(x) - x^2/6 + log(1+x^2)/6',
      check: { kind: 'antiderivative', integrand: 'x^2*atan(x)' },
      recap: 'Inverse trig comes before algebraic, so $u = \\tan^{-1}(x)$ (which is $\\arctan x$, not $\\frac{1}{\\tan x}$); the new integral $\\int\\frac{x^3}{1+x^2}\\,dx$ needs long division first.',
    },
  },

  // ── 8. Definite, twice by parts: ∫₀^{2π} t² sin(2t) dt ───────────────────────────────────
  {
    id: 'ip-s-08',
    topic: 'ibp',
    title: 'Definite, twice by parts: t² sin 2t',
    difficulty: 2,
    statement: { text: 'Evaluate the definite integral.', latex: '\\int_0^{2\\pi} t^2\\sin(2t)\\,dt' },
    variable: 't',
    steps: [
      {
        prompt: 'Following LIATE, choose $u$ and $dv$.',
        options: [
          { latex: 'u = t^2,\\ dv = \\sin(2t)\\,dt', expr: '[t^2, sin(2*t)*dt]' },
          {
            latex: 'u = \\sin(2t),\\ dv = t^2\\,dt',
            expr: '[sin(2*t), t^2*dt]',
            mistake: 'liate-misordered',
            why: 'Algebraic comes before trigonometric; with dv = t² dt the power of t grows at every step.',
          },
          {
            latex: 'u = t^2,\\ dv = dt',
            expr: '[t^2, dt]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor sin(2t) is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = \\sin(2t),\\ dv = dt',
            expr: '[sin(2*t), dt]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor t² is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = 2t,\\ dv = \\sin(2t)\\,dt',
            expr: '[2*t, sin(2*t)*dt]',
            mistake: 'ibp-du-wrong',
            why: '2t is the derivative of t² (it belongs in du); u must be t² itself.',
          },
        ],
        correct: 0,
        explanation: 'A comes before T: differentiating $u = t^2$ lowers the power, and $dv = \\sin(2t)\\,dt$ integrates easily.',
        result: { latex: 'u = t^2,\\quad dv = \\sin(2t)\\,dt' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'The new integral is $\\int v\\,du$. What is $v\\,du$?',
        options: [
          { latex: '-t\\cos(2t)\\,dt', expr: '-t*cos(2*t)*dt' },
          {
            latex: 't\\cos(2t)\\,dt',
            expr: 't*cos(2*t)*dt',
            mistake: 'trig-antiderivative-sign',
            why: 'v = ∫sin(2t) dt = −½cos(2t); the minus sign of the sine antiderivative was lost.',
          },
          {
            latex: '-4t\\cos(2t)\\,dt',
            expr: '-4*t*cos(2*t)*dt',
            mistake: 'inner-constant-factor-missing',
            why: 'v was computed by multiplying by the inner 2 (v = −2cos 2t) instead of dividing by it.',
          },
          {
            latex: '-2t\\cos(2t)\\,dt',
            expr: '-2*t*cos(2*t)*dt',
            mistake: 'ibp-v-wrong',
            why: 'v = −½cos(2t); dropping the ½ gives v = −cos(2t) and a v du twice too large.',
          },
          {
            latex: '-\\frac{1}{2}t\\cos(2t)\\,dt',
            expr: '-t/2*cos(2*t)*dt',
            mistake: 'ibp-du-wrong',
            why: 'd(t²) = 2t dt; taking du = t dt loses the factor 2.',
          },
          {
            latex: '4t\\cos(2t)\\,dt',
            expr: '4*t*cos(2*t)*dt',
            mistake: 'differentiated-instead',
            why: 'v was taken as 2cos(2t), the derivative of sin(2t), instead of an antiderivative.',
          },
        ],
        correct: 0,
        explanation: '$du = 2t\\,dt$ and $v = -\\frac12\\cos(2t)$, so $v\\,du = -t\\cos(2t)\\,dt$.',
        result: { latex: 'du = 2t\\,dt,\\quad v = -\\frac{1}{2}\\cos(2t),\\quad v\\,du = -t\\cos(2t)\\,dt' },
        check: { kind: 'value', expected: '-cos(2*t)/2*2*t*dt' },
      },
      {
        prompt: 'Apply $\\int_a^b u\\,dv = uv\\big|_a^b - \\int_a^b v\\,du$.',
        options: [
          { latex: '\\left[-\\frac{t^2}{2}\\cos(2t)\\right]_0^{2\\pi} + \\int_0^{2\\pi} t\\cos(2t)\\,dt' },
          {
            latex: '\\left[\\frac{t^2}{2}\\cos(2t)\\right]_0^{2\\pi} - \\int_0^{2\\pi} t\\cos(2t)\\,dt',
            mistake: 'formula-wrong-sign',
            why: 'This is ∫v du − uv, the negative of the formula.',
          },
          {
            latex: '-\\frac{t^2}{2}\\cos(2t) + \\int_0^{2\\pi} t\\cos(2t)\\,dt',
            mistake: 'ibp-bounds-not-applied',
            why: 'The boundary term uv must also be evaluated from 0 to 2π.',
          },
          {
            latex: '\\left[-t^2\\cos(2t)\\right]_0^{2\\pi} + \\int_0^{2\\pi} t\\cos(2t)\\,dt',
            mistake: 'coefficient-mishandled',
            why: 'uv = t² · (−½cos 2t); the ½ from v was dropped in the boundary term.',
          },
          {
            latex: '\\left[-\\frac{t^2}{2}\\cos(2t)\\right]_0^{2\\pi} + \\int_0^{2\\pi} t^2\\cos(2t)\\,dt',
            mistake: 'ibp-formula-wrong',
            why: 'u = t² was kept in the new integral; ∫v du uses du = 2t dt, which lowers the power.',
          },
        ],
        correct: 0,
        explanation: '$uv = -\\frac{t^2}{2}\\cos(2t)$ and $-\\int v\\,du = +\\int t\\cos(2t)\\,dt$, both over $[0, 2\\pi]$.',
        result: { latex: '\\int_0^{2\\pi} t^2\\sin(2t)\\,dt = \\left[-\\frac{t^2}{2}\\cos(2t)\\right]_0^{2\\pi} + \\int_0^{2\\pi} t\\cos(2t)\\,dt' },
      },
      {
        prompt: 'Evaluate the boundary term $\\left[-\\frac{t^2}{2}\\cos(2t)\\right]_0^{2\\pi}$.',
        options: [
          { latex: '-2\\pi^2', expr: '-2*pi^2' },
          {
            latex: '2\\pi^2',
            expr: '2*pi^2',
            mistake: 'ftc-order-swapped',
            why: 'The value at 2π was subtracted from the value at 0 instead of the other way round.',
          },
          {
            latex: '-4\\pi^2',
            expr: '-4*pi^2',
            mistake: 'coefficient-mishandled',
            why: 'The ½ in −t²/2 was dropped: −(2π)²/2 = −2π².',
          },
          {
            latex: '-\\pi^2',
            expr: '-pi^2',
            mistake: 'arithmetic-error',
            why: '(2π)² = 4π², not 2π².',
          },
          {
            latex: '0',
            expr: '0',
            mistake: 'arithmetic-error',
            why: 'cos(4π) = 1, not 0, so the boundary term does not vanish.',
          },
        ],
        correct: 0,
        explanation: '$-\\frac{(2\\pi)^2}{2}\\cos(4\\pi) - 0 = -2\\pi^2$.',
        result: { latex: '\\left[-\\frac{t^2}{2}\\cos(2t)\\right]_0^{2\\pi} = -\\frac{(2\\pi)^2}{2}\\cos(4\\pi) + 0 = -2\\pi^2' },
        check: { kind: 'value', expected: '-2*pi^2' },
      },
      {
        prompt: 'The remaining integral needs a second integration by parts ($u = t$, $dv = \\cos(2t)\\,dt$). Which antiderivative of $t\\cos(2t)$ do you get?',
        options: [
          { latex: '\\frac{t}{2}\\sin(2t) + \\frac{1}{4}\\cos(2t) + C', expr: 't/2*sin(2*t) + cos(2*t)/4' },
          {
            latex: '\\frac{t}{2}\\sin(2t) - \\frac{1}{4}\\cos(2t) + C',
            expr: 't/2*sin(2*t) - cos(2*t)/4',
            mistake: 'ibp-sign-error',
            why: '−∫v du = −½∫sin(2t) dt = +¼cos(2t); the sign was flipped.',
          },
          {
            latex: '-\\frac{t}{2}\\sin(2t) - \\frac{1}{4}\\cos(2t) + C',
            expr: '-t/2*sin(2*t) - cos(2*t)/4',
            mistake: 'trig-antiderivative-sign',
            why: 'v = ∫cos(2t) dt = +½sin(2t); taking −½sin(2t) flips every term.',
          },
          {
            latex: '2t\\sin(2t) + 4\\cos(2t) + C',
            expr: '2*t*sin(2*t) + 4*cos(2*t)',
            mistake: 'inner-constant-factor-missing',
            why: 'Both antiderivatives multiplied by the inner 2 instead of dividing by it.',
          },
          {
            latex: '\\frac{t^2}{4}\\sin(2t) + C',
            expr: 't^2/4*sin(2*t)',
            mistake: 'product-rule-integral',
            why: 't and cos(2t) were integrated separately and multiplied; there is no product rule for integrals.',
          },
          {
            latex: '\\frac{t}{2}\\sin(2t) + C',
            expr: 't/2*sin(2*t)',
            mistake: 'ibp-formula-wrong',
            why: 'Only uv was kept; the term −½∫sin(2t) dt = ¼cos(2t) was dropped.',
          },
        ],
        correct: 0,
        explanation: '$u = t$, $v = \\frac12\\sin(2t)$: $\\frac{t}{2}\\sin(2t) - \\frac12\\int\\sin(2t)\\,dt = \\frac{t}{2}\\sin(2t) + \\frac14\\cos(2t) + C$.',
        result: { latex: '\\int_0^{2\\pi} t\\cos(2t)\\,dt = \\left[\\frac{t}{2}\\sin(2t) + \\frac{1}{4}\\cos(2t)\\right]_0^{2\\pi}' },
        check: { kind: 'antiderivative', integrand: 't*cos(2*t)' },
      },
      {
        prompt: 'Evaluate this part and add the boundary term $-2\\pi^2$. What is the value of the original integral?',
        options: [
          { latex: '-2\\pi^2', expr: '-2*pi^2' },
          {
            latex: '0',
            expr: '0',
            mistake: 'ibp-formula-wrong',
            why: 'The boundary term −2π² was dropped; only the second integral (which is 0) was kept.',
          },
          {
            latex: '-2\\pi^2 + \\frac{1}{4}',
            expr: '-2*pi^2 + 1/4',
            mistake: 'ftc-not-subtracted',
            why: 'The second part is ¼ − ¼ = 0; the value ¼ at t = 0 was not subtracted.',
          },
          {
            latex: '-2\\pi^2 + \\frac{1}{2}',
            expr: '-2*pi^2 + 1/2',
            mistake: 'ftc-not-subtracted',
            why: 'The values at the two limits (¼ and ¼) were added instead of subtracted.',
          },
          {
            latex: '-2\\pi^2 - \\frac{1}{2}',
            expr: '-2*pi^2 - 1/2',
            mistake: 'arithmetic-error',
            why: 'cos(4π) = 1, not −1, so the second part is ¼ − ¼ = 0.',
          },
          {
            latex: '-2\\pi^2 + \\pi',
            expr: '-2*pi^2 + pi',
            mistake: 'arithmetic-error',
            why: 'sin(4π) = 0, not 1, so (t/2)sin(2t) is 0 at t = 2π.',
          },
        ],
        correct: 0,
        explanation: '$\\left[\\frac{t}{2}\\sin(2t) + \\frac14\\cos(2t)\\right]_0^{2\\pi} = \\left(0 + \\frac14\\right) - \\left(0 + \\frac14\\right) = 0$, so the total is $-2\\pi^2$.',
        result: { latex: '\\int_0^{2\\pi} t^2\\sin(2t)\\,dt = -2\\pi^2 + \\left(0 + \\frac{1}{4}\\right) - \\left(0 + \\frac{1}{4}\\right) = -2\\pi^2' },
        check: { kind: 'value', expected: '-2*pi^2' },
      },
    ],
    final: {
      latex: '-2\\pi^2',
      expr: '-2*pi^2',
      check: { kind: 'definite-integral', integrand: 't^2*sin(2*t)', lower: '0', upper: '2*pi' },
      recap: 'Integrate by parts twice ($u = t^2$, then $u = t$), evaluating each boundary term from $0$ to $2\\pi$; the second part vanishes, leaving $-2\\pi^2$.',
    },
  },

  // ── 9. A volume that needs IBP: π∫₁³ (ln x)² dx ─────────────────────────────────────────
  {
    id: 'ip-s-09',
    topic: 'ibp',
    title: 'Volume under y = ln x',
    difficulty: 2,
    statement: {
      text: 'The region bounded by $y = \\ln(x)$, $y = 0$, and $x = 3$ is rotated about the x-axis. Find the volume of the solid.',
    },
    steps: [
      {
        prompt: 'Set up the volume with disks.',
        options: [
          { latex: 'V = \\pi\\int_1^3 (\\ln(x))^2\\,dx', expr: 'pi*integral(log(x)^2, x, 1, 3)' },
          {
            latex: 'V = \\pi\\int_0^3 (\\ln(x))^2\\,dx',
            expr: 'pi*integral(log(x)^2, x, 0, 3)',
            mistake: 'missing-intersection',
            why: 'The region starts where ln(x) = 0, at x = 1; for 0 < x < 1 the curve is below the x-axis and not part of the region.',
          },
          {
            latex: 'V = \\pi\\int_1^3 \\ln(x)\\,dx',
            expr: 'pi*integral(log(x), x, 1, 3)',
            mistake: 'radius-not-squared',
            why: 'The disk area is πR² = π(ln x)²; the radius was not squared.',
          },
          {
            latex: 'V = \\int_1^3 (\\ln(x))^2\\,dx',
            expr: 'integral(log(x)^2, x, 1, 3)',
            mistake: 'pi-missing',
            why: 'The area of a disk is πR²; the factor π was dropped.',
          },
          {
            latex: 'V = 2\\pi\\int_1^3 x\\ln(x)\\,dx',
            expr: '2*pi*integral(x*log(x), x, 1, 3)',
            mistake: 'method-formula-swapped',
            why: 'This is a shell integrand 2π·x·ln(x) with vertical slices, which describes rotation about the y-axis, not the x-axis.',
          },
        ],
        correct: 0,
        explanation: 'Each disk has radius $R(x) = \\ln(x)$, and the region runs from $x = 1$ (where $\\ln x = 0$) to $x = 3$.',
        result: { latex: 'V = \\pi\\int_1^3 R(x)^2\\,dx = \\pi\\int_1^3 (\\ln(x))^2\\,dx' },
        check: { kind: 'value', expected: 'pi*integral(log(x)^2, x, 1, 3)' },
      },
      {
        prompt: 'Choose $u$ and $dv$ for $\\int (\\ln(x))^2\\,dx$.',
        options: [
          { latex: 'u = (\\ln(x))^2,\\ dv = dx', expr: '[log(x)^2, dx]' },
          {
            latex: 'u = \\ln(x),\\ dv = dx',
            expr: '[log(x), dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'Only one factor of ln(x) is accounted for; u dv must contain (ln x)² dx.',
          },
          {
            latex: 'u = 1,\\ dv = (\\ln(x))^2\\,dx',
            expr: '[1, log(x)^2*dx]',
            mistake: 'ibp-wrong-u-dv',
            why: 'Then v = ∫(ln x)² dx is the original problem and du = 0; nothing is gained.',
          },
          {
            latex: 'u = \\frac{2\\ln(x)}{x},\\ dv = dx',
            expr: '[2*log(x)/x, dx]',
            mistake: 'ibp-du-wrong',
            why: '2 ln(x)/x is the derivative of (ln x)²; it belongs in du, not in u.',
          },
          {
            latex: 'u = \\ln(x^2),\\ dv = dx',
            expr: '[log(x^2), dx]',
            mistake: 'algebra-error',
            why: '(ln x)² is not ln(x²) = 2 ln(x); the square applies to the logarithm itself.',
          },
        ],
        correct: 0,
        explanation: 'Treat $(\\ln x)^2$ as a single function: $u = (\\ln x)^2$, $dv = dx$, so $du = \\frac{2\\ln(x)}{x}\\,dx$ and $v = x$.',
        result: { latex: 'u = (\\ln(x))^2,\\quad du = \\frac{2\\ln(x)}{x}\\,dx,\\quad dv = dx,\\quad v = x' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'Apply the integration by parts formula.',
        options: [
          { latex: 'x(\\ln(x))^2 - 2\\int \\ln(x)\\,dx', expr: 'x*log(x)^2 - 2*indefinite(log(x), x)' },
          {
            latex: 'x(\\ln(x))^2 - \\int \\ln(x)\\,dx',
            expr: 'x*log(x)^2 - indefinite(log(x), x)',
            mistake: 'coefficient-mishandled',
            why: 'du = (2 ln x / x) dx carries the factor 2 into ∫v du.',
          },
          {
            latex: 'x(\\ln(x))^2 - 2\\int \\frac{\\ln(x)}{x}\\,dx',
            expr: 'x*log(x)^2 - 2*indefinite(log(x)/x, x)',
            mistake: 'ibp-formula-wrong',
            why: 'The factor v = x was dropped from ∫v du; x · (2 ln x / x) = 2 ln(x).',
          },
          {
            latex: 'x(\\ln(x))^2 - 2\\int x\\ln(x)\\,dx',
            expr: 'x*log(x)^2 - 2*indefinite(x*log(x), x)',
            mistake: 'algebra-error',
            why: 'v du = x · (2 ln x / x) dx; the x in v cancels the x in the denominator of du.',
          },
          {
            latex: '\\frac{x^2}{2}(\\ln(x))^2 - \\int x\\ln(x)\\,dx',
            expr: 'x^2/2*log(x)^2 - indefinite(x*log(x), x)',
            mistake: 'ibp-v-wrong',
            why: 'v = ∫dx = x; x²/2 would be the antiderivative of x dx.',
          },
        ],
        correct: 0,
        explanation: '$uv - \\int v\\,du = x(\\ln x)^2 - \\int x\\cdot\\frac{2\\ln(x)}{x}\\,dx = x(\\ln x)^2 - 2\\int\\ln(x)\\,dx$.',
        result: { latex: '\\int (\\ln(x))^2\\,dx = x(\\ln(x))^2 - 2\\int \\ln(x)\\,dx' },
        check: { kind: 'identity', lhs: 'x*log(x)^2 - indefinite(x*2*log(x)/x, x)' },
      },
      {
        prompt: 'Use $\\int \\ln(x)\\,dx = x\\ln(x) - x + C$ to finish the antiderivative.',
        options: [
          { latex: 'x(\\ln(x))^2 - 2x\\ln(x) + 2x + C', expr: 'x*log(x)^2 - 2*x*log(x) + 2*x' },
          {
            latex: 'x(\\ln(x))^2 - 2x\\ln(x) - 2x + C',
            expr: 'x*log(x)^2 - 2*x*log(x) - 2*x',
            mistake: 'sign-error',
            why: '−2(x ln x − x) = −2x ln(x) + 2x; the minus was not distributed to the second term.',
          },
          {
            latex: 'x(\\ln(x))^2 - 2x\\ln(x) + x + C',
            expr: 'x*log(x)^2 - 2*x*log(x) + x',
            mistake: 'coefficient-mishandled',
            why: 'The 2 was not distributed: −2(x ln x − x) ends with +2x, not +x.',
          },
          {
            latex: 'x(\\ln(x))^2 - 2x\\ln(x) + C',
            expr: 'x*log(x)^2 - 2*x*log(x)',
            mistake: 'ibp-formula-wrong',
            why: 'Only the x ln(x) part of ∫ln(x) dx = x ln(x) − x was used; the −x part gives the +2x term.',
          },
          {
            latex: 'x(\\ln(x))^2 - \\frac{2}{x} + C',
            expr: 'x*log(x)^2 - 2/x',
            mistake: 'differentiated-instead',
            why: 'ln(x) was differentiated (1/x) instead of integrated.',
          },
        ],
        correct: 0,
        explanation: '$x(\\ln x)^2 - 2\\left(x\\ln(x) - x\\right) = x(\\ln x)^2 - 2x\\ln(x) + 2x$.',
        result: { latex: '\\int (\\ln(x))^2\\,dx = x(\\ln(x))^2 - 2\\left(x\\ln(x) - x\\right) + C = x(\\ln(x))^2 - 2x\\ln(x) + 2x + C' },
        check: { kind: 'antiderivative', integrand: 'log(x)^2' },
      },
      {
        prompt: 'Evaluate $V = \\pi\\left[x(\\ln(x))^2 - 2x\\ln(x) + 2x\\right]_1^3$.',
        options: [
          { latex: 'V = \\pi\\left(3(\\ln 3)^2 - 6\\ln 3 + 4\\right)', expr: 'pi*(3*log(3)^2 - 6*log(3) + 4)' },
          {
            latex: 'V = \\pi\\left(3(\\ln 3)^2 - 6\\ln 3 + 6\\right)',
            expr: 'pi*(3*log(3)^2 - 6*log(3) + 6)',
            mistake: 'ftc-not-subtracted',
            why: 'At x = 1 the antiderivative is 0 − 0 + 2 = 2, not 0; it must be subtracted.',
          },
          {
            latex: 'V = 3(\\ln 3)^2 - 6\\ln 3 + 4',
            expr: '3*log(3)^2 - 6*log(3) + 4',
            mistake: 'pi-missing',
            why: 'The factor π from the disk area was dropped.',
          },
          {
            latex: 'V = \\pi\\left(6\\ln 3 - 3(\\ln 3)^2 - 4\\right)',
            expr: 'pi*(6*log(3) - 3*log(3)^2 - 4)',
            mistake: 'ftc-order-swapped',
            why: 'The antiderivative was evaluated as F(1) − F(3).',
          },
          {
            latex: 'V = \\pi\\left(9(\\ln 3)^2 - 6\\ln 3 + 4\\right)',
            expr: 'pi*(9*log(3)^2 - 6*log(3) + 4)',
            mistake: 'algebra-error',
            why: '3(ln 3)² means 3 · (ln 3)², not (3 ln 3)² = 9(ln 3)².',
          },
        ],
        correct: 0,
        explanation: '$F(3) = 3(\\ln 3)^2 - 6\\ln 3 + 6$ and $F(1) = 2$, so $V = \\pi\\left(3(\\ln 3)^2 - 6\\ln 3 + 4\\right)$.',
        result: { latex: 'V = \\pi\\left[\\left(3(\\ln 3)^2 - 6\\ln 3 + 6\\right) - (0 - 0 + 2)\\right] = \\pi\\left(3(\\ln 3)^2 - 6\\ln 3 + 4\\right)' },
        check: { kind: 'value', expected: 'pi*integral(log(x)^2, x, 1, 3)' },
      },
    ],
    final: {
      latex: 'V = \\pi\\left(3(\\ln 3)^2 - 6\\ln 3 + 4\\right)',
      expr: 'pi*(3*log(3)^2 - 6*log(3) + 4)',
      check: { kind: 'definite-integral', integrand: 'pi*log(x)^2', lower: '1', upper: '3' },
      recap: 'Disks give $V = \\pi\\int_1^3(\\ln x)^2\\,dx$; integrate by parts with $u = (\\ln x)^2$, $dv = dx$, then use $\\int\\ln x\\,dx = x\\ln x - x$ and evaluate from $1$ to $3$.',
    },
  },

  // ── 10. Using ∫tan x dx: ∫ x sec²(x) dx ──────────────────────────────────────────────────
  {
    id: 'ip-s-10',
    topic: 'ibp',
    title: 'Finishing with ∫ tan x: x sec²x',
    difficulty: 1,
    statement: { text: 'Evaluate the integral. (Recall $\\int \\sec^2(x)\\,dx = \\tan(x) + C$.)', latex: '\\int x\\sec^2(x)\\,dx' },
    steps: [
      {
        prompt: 'Following LIATE, choose $u$ and $dv$.',
        options: [
          { latex: 'u = x,\\ dv = \\sec^2(x)\\,dx', expr: '[x, sec(x)^2*dx]' },
          {
            latex: 'u = \\sec^2(x),\\ dv = x\\,dx',
            expr: '[sec(x)^2, x*dx]',
            mistake: 'liate-misordered',
            why: 'Algebraic comes before trigonometric; this choice leads to ∫x² sec²(x) tan(x) dx, which is harder.',
          },
          {
            latex: 'u = x,\\ dv = dx',
            expr: '[x, dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor sec²(x) is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = \\sec^2(x),\\ dv = dx',
            expr: '[sec(x)^2, dx]',
            mistake: 'ibp-incomplete-dv',
            why: 'The factor x is in neither u nor dv; u dv must contain the whole integrand.',
          },
          {
            latex: 'u = x,\\ dv = \\tan(x)\\,dx',
            expr: '[x, tan(x)*dx]',
            mistake: 'ibp-v-wrong',
            why: 'tan(x) is v = ∫sec²(x) dx; dv is sec²(x) dx itself.',
          },
        ],
        correct: 0,
        explanation: 'A comes before T: $u = x$, and $dv = \\sec^2(x)\\,dx$ integrates directly.',
        result: { latex: 'u = x,\\quad dv = \\sec^2(x)\\,dx' },
        check: { kind: 'none', reason: 'choice of u/dv' },
      },
      {
        prompt: 'With $du = dx$, what is $v$?',
        options: [
          { latex: 'v = \\tan(x)', expr: 'tan(x)' },
          {
            latex: 'v = \\sec(x)\\tan(x)',
            expr: 'sec(x)*tan(x)',
            mistake: 'trig-antiderivative-swapped',
            why: 'sec(x)tan(x) is the derivative of sec(x); ∫sec²(x) dx = tan(x).',
          },
          {
            latex: 'v = 2\\sec^2(x)\\tan(x)',
            expr: '2*sec(x)^2*tan(x)',
            mistake: 'differentiated-instead',
            why: '2sec²(x)tan(x) is the derivative of sec²(x); v must be an antiderivative.',
          },
          {
            latex: 'v = -\\tan(x)',
            expr: '-tan(x)',
            mistake: 'trig-antiderivative-sign',
            why: 'd/dx tan(x) = +sec²(x), so ∫sec²(x) dx = +tan(x).',
          },
          {
            latex: 'v = \\frac{\\sec^3(x)}{3}',
            expr: 'sec(x)^3/3',
            mistake: 'dx-not-replaced',
            why: 'The power rule was applied to sec(x) as if its derivative sec(x)tan(x) dx were present.',
          },
        ],
        correct: 0,
        explanation: '$v = \\int\\sec^2(x)\\,dx = \\tan(x)$, because $\\frac{d}{dx}\\tan x = \\sec^2 x$.',
        result: { latex: 'du = dx,\\quad v = \\tan(x)' },
        check: { kind: 'value', expected: 'tan(x)' },
      },
      {
        prompt: 'Apply the integration by parts formula.',
        options: [
          { latex: 'x\\tan(x) - \\int \\tan(x)\\,dx', expr: 'x*tan(x) - indefinite(tan(x), x)' },
          {
            latex: 'x\\tan(x) + \\int \\tan(x)\\,dx',
            expr: 'x*tan(x) + indefinite(tan(x), x)',
            mistake: 'ibp-sign-error',
            why: 'The formula subtracts ∫v du; the plus sign is wrong.',
          },
          {
            latex: '-x\\tan(x) + \\int \\tan(x)\\,dx',
            expr: '-x*tan(x) + indefinite(tan(x), x)',
            mistake: 'formula-wrong-sign',
            why: 'This is ∫v du − uv, the negative of the formula.',
          },
          {
            latex: 'x\\tan(x) - \\int x\\tan(x)\\,dx',
            expr: 'x*tan(x) - indefinite(x*tan(x), x)',
            mistake: 'ibp-du-wrong',
            why: 'du = dx for u = x; the extra factor x means u was used instead of du.',
          },
          {
            latex: 'x\\tan(x) - \\int \\sec^2(x)\\,dx',
            expr: 'x*tan(x) - indefinite(sec(x)^2, x)',
            mistake: 'ibp-formula-wrong',
            why: 'The new integral is ∫v du = ∫tan(x) dx; ∫sec²(x) dx is just ∫dv again.',
          },
        ],
        correct: 0,
        explanation: '$uv - \\int v\\,du = x\\tan(x) - \\int\\tan(x)\\,dx$.',
        result: { latex: '\\int x\\sec^2(x)\\,dx = x\\tan(x) - \\int \\tan(x)\\,dx' },
        check: { kind: 'identity', lhs: 'x*tan(x) - indefinite(tan(x), x)' },
      },
      {
        prompt: 'Finish using $\\int \\tan(x)\\,dx$.',
        options: [
          { latex: 'x\\tan(x) + \\ln|\\cos(x)| + C', expr: 'x*tan(x) + log(abs(cos(x)))' },
          {
            latex: 'x\\tan(x) - \\ln|\\cos(x)| + C',
            expr: 'x*tan(x) - log(abs(cos(x)))',
            mistake: 'tan-antiderivative-wrong',
            why: '∫tan(x) dx = −ln|cos(x)|, so −∫tan(x) dx = +ln|cos(x)|; the sign of the log was flipped.',
          },
          {
            latex: 'x\\tan(x) - \\ln|\\sin(x)| + C',
            expr: 'x*tan(x) - log(abs(sin(x)))',
            mistake: 'formula-swapped',
            why: 'ln|sin(x)| is the antiderivative of cot(x), not tan(x).',
          },
          {
            latex: 'x\\tan(x) - \\sec^2(x) + C',
            expr: 'x*tan(x) - sec(x)^2',
            mistake: 'differentiated-instead',
            why: 'sec²(x) is the derivative of tan(x), not an antiderivative of it.',
          },
          {
            latex: 'x\\tan(x) - \\frac{\\tan^2(x)}{2} + C',
            expr: 'x*tan(x) - tan(x)^2/2',
            mistake: 'dx-not-replaced',
            why: 'The power rule was applied to tan(x) as if sec²(x) dx were present; ∫tan(x) dx = −ln|cos(x)|.',
          },
        ],
        correct: 0,
        explanation: 'Since $\\int\\tan x\\,dx = -\\ln|\\cos x| + C$, subtracting it gives $x\\tan(x) + \\ln|\\cos(x)| + C$.',
        result: { latex: '\\int x\\sec^2(x)\\,dx = x\\tan(x) - \\left(-\\ln|\\cos(x)|\\right) + C = x\\tan(x) + \\ln|\\cos(x)| + C' },
        check: { kind: 'antiderivative', integrand: 'x*sec(x)^2' },
      },
    ],
    final: {
      latex: 'x\\tan(x) + \\ln|\\cos(x)| + C',
      expr: 'x*tan(x) + log(abs(cos(x)))',
      check: { kind: 'antiderivative', integrand: 'x*sec(x)^2' },
      recap: 'A before T gives $u = x$, $dv = \\sec^2(x)\\,dx$; since $\\int\\tan x\\,dx = -\\ln|\\cos x|$, the minus in the formula turns it into $+\\ln|\\cos(x)|$.',
    },
  },
];
