import type { StepProblem } from '../types';

/** Step-Through problems for topic "trig-integrals". Authored by content-author; verified by math-verifier. */
export const steps: StepProblem[] = [
  {
    id: 'ti-s-01',
    topic: 'trig-integrals',
    title: 'Odd power of sine',
    difficulty: 1,
    statement: { text: 'Evaluate', latex: '\\int \\sin^3 x\\cos^2 x\\,dx' },
    steps: [
      {
        prompt: 'Which strategy fits this integral?',
        options: [
          { text: 'Save one $\\cos x$ and let $u = \\sin x$', mistake: 'trig-wrong-factor-saved', why: 'Saving cos x leaves a single cos x, which needs a square root in terms of sin x.' },
          { text: 'Save one $\\sin x$ and let $u = \\cos x$' },
          { text: 'Save one $\\sin x$ and let $u = \\sin x$', mistake: 'trig-wrong-factor-saved', why: 'u = sin x needs du = cos x dx; the saved sin x dx does not match it.' },
          { text: 'Use the half-angle identities for $\\sin^2 x$ and $\\cos^2 x$', mistake: 'technique-wrong', why: 'Half-angle identities are for both powers even; an odd sine power gives a direct substitution.' },
          { text: 'Integration by parts with $u = \\sin^2 x$, $dv = \\sin x\\cos^2 x\\,dx$', mistake: 'technique-wrong', why: 'Parts only trades this for another trig product; the odd power of sine already allows u = cos x.' },
        ],
        correct: 1,
        explanation: 'The sine power 3 is odd: one $\\sin x\\,dx$ becomes $-du$, and the even power $\\sin^2 x$ converts to cosines.',
        result: { text: 'Odd power of sine: save $\\sin x\\,dx$, use $u = \\cos x$.' },
      },
      {
        prompt: 'Rewrite the integrand so that only $\\cos x$ and the saved $\\sin x\\,dx$ appear.',
        options: [
          { latex: '\\int (\\cos^2 x - 1)\\cos^2 x\\,\\sin x\\,dx', expr: 'indefinite((cos(x)^2 - 1)*cos(x)^2*sin(x), x)', mistake: 'pythagorean-wrong', why: 'sin²x = 1 − cos²x; this has the subtraction reversed.' },
          { latex: '\\int (1 + \\cos^2 x)\\cos^2 x\\,\\sin x\\,dx', expr: 'indefinite((1 + cos(x)^2)*cos(x)^2*sin(x), x)', mistake: 'pythagorean-wrong', why: 'cos²x was moved across the equals sign without changing its sign.' },
          { latex: '\\int (1 - \\cos x)\\cos^2 x\\,\\sin x\\,dx', expr: 'indefinite((1 - cos(x))*cos(x)^2*sin(x), x)', mistake: 'formula-wrong-power', why: 'The square on cosine was dropped: sin²x = 1 − cos²x.' },
          { latex: '\\int (1 - \\cos^2 x)^2\\cos^2 x\\,\\sin x\\,dx', expr: 'indefinite((1 - cos(x)^2)^2*cos(x)^2*sin(x), x)', mistake: 'exponent-arithmetic', why: 'After saving one sin x only sin²x remains, so (1 − cos²x) appears once; the square belongs to sin⁵x.' },
          { latex: '\\int (1 - \\cos^2 x)\\cos^2 x\\,\\sin x\\,dx', expr: 'indefinite((1 - cos(x)^2)*cos(x)^2*sin(x), x)' },
        ],
        correct: 4,
        explanation: '$\\sin^3 x = \\sin^2 x\\cdot\\sin x = (1 - \\cos^2 x)\\sin x$.',
        result: { latex: '\\int \\sin^3 x\\cos^2 x\\,dx = \\int (1 - \\cos^2 x)\\cos^2 x\\,\\sin x\\,dx' },
        check: { kind: 'identity', lhs: 'indefinite(sin(x)^3*cos(x)^2, x)' },
      },
      {
        prompt: 'Substitute $u = \\cos x$, $du = -\\sin x\\,dx$. The integral becomes',
        options: [
          { latex: '-\\int (1 - u^2)u^2\\,du', expr: '-indefinite((1 - u^2)*u^2, u)' },
          { latex: '\\int (1 - u^2)u^2\\,du', expr: 'indefinite((1 - u^2)*u^2, u)', mistake: 'u-cos-sign-missing', why: 'sin x dx = −du; the minus sign was dropped.' },
          { latex: '-\\int (1 - u^2)u^2\\sin x\\,du', expr: '-indefinite((1 - u^2)*u^2*sin(x), u)', mistake: 'leftover-x-in-u-integral', why: 'The saved sin x dx became −du; the sin x must not stay in the u-integral.' },
          { latex: '-\\frac{1}{2}\\int (1 - u^2)u^2\\,du', expr: '-indefinite((1 - u^2)*u^2, u)/2', mistake: 'du-constant-wrong', why: 'du = −sin x dx exactly matches the saved factor; there is no factor 1/2.' },
          { latex: '-\\int (1 - u^2)u\\,du', expr: '-indefinite((1 - u^2)*u, u)', mistake: 'trig-wrong-factor-saved', why: 'One cos x was removed as if it had been saved; the saved factor is sin x, so cos²x stays u².' },
        ],
        correct: 0,
        explanation: '$(1 - \\cos^2 x)\\cos^2 x\\,\\sin x\\,dx = (1 - u^2)u^2\\,(-du)$.',
        result: { latex: '= -\\int (1 - u^2)u^2\\,du = -\\int (u^2 - u^4)\\,du' },
        variable: 'u',
        domain: { u: [0.3, 0.95] },
        check: { kind: 'identity', lhs: '-indefinite((1 - u^2)*u^2, u)' },
      },
      {
        prompt: 'Integrate and substitute back $u = \\cos x$.',
        options: [
          { latex: '\\frac{1}{3}\\cos^3 x - \\frac{1}{5}\\cos^5 x + C', expr: 'cos(x)^3/3 - cos(x)^5/5', mistake: 'sign-error', why: 'The minus sign in front of the integral was dropped while integrating.' },
          { latex: '-\\frac{1}{3}\\sin^3 x + \\frac{1}{5}\\sin^5 x + C', expr: '-sin(x)^3/3 + sin(x)^5/5', mistake: 'back-substitution-wrong', why: 'u was cos x, so u³ and u⁵ become cos³x and cos⁵x.' },
          { latex: '-\\cos^3 x + \\cos^5 x + C', expr: '-cos(x)^3 + cos(x)^5', mistake: 'power-rule-int-coefficient', why: '∫u² du = u³/3 and ∫u⁴ du = u⁵/5; the divisions were skipped.' },
          { latex: '-\\frac{1}{3}\\cos^3 x - \\frac{1}{5}\\cos^5 x + C', expr: '-cos(x)^3/3 - cos(x)^5/5', mistake: 'algebra-error', why: '−(u² − u⁴) = −u² + u⁴; the sign of the u⁴ term was not flipped.' },
          { latex: '-\\frac{1}{3}\\cos^3 x + \\frac{1}{5}\\cos^5 x + C', expr: '-cos(x)^3/3 + cos(x)^5/5' },
          { latex: '-\\frac{u^3}{3} + \\frac{u^5}{5} + C', expr: '-u^3/3 + u^5/5', mistake: 'not-back-substituted', why: 'The answer must be written in x: replace u by cos x.' },
        ],
        correct: 4,
        explanation: '$-\\left(\\frac{u^3}{3} - \\frac{u^5}{5}\\right) + C$ with $u = \\cos x$.',
        result: { latex: '= -\\frac{u^3}{3} + \\frac{u^5}{5} + C = -\\frac{1}{3}\\cos^3 x + \\frac{1}{5}\\cos^5 x + C' },
        check: { kind: 'antiderivative', integrand: 'sin(x)^3*cos(x)^2' },
      },
    ],
    final: {
      latex: '-\\frac{1}{3}\\cos^3 x + \\frac{1}{5}\\cos^5 x + C',
      expr: '-cos(x)^3/3 + cos(x)^5/5',
      check: { kind: 'antiderivative', integrand: 'sin(x)^3*cos(x)^2' },
      recap: 'Odd power of sine: save one $\\sin x$, turn $\\sin^2 x$ into $1 - \\cos^2 x$, and remember that $du = -\\sin x\\,dx$ puts a minus sign in front.',
    },
  },
  {
    id: 'ti-s-02',
    topic: 'trig-integrals',
    title: 'Both powers even: half-angle identities',
    difficulty: 2,
    statement: { text: 'Evaluate', latex: '\\int \\sin^2 x\\cos^2 x\\,dx' },
    steps: [
      {
        prompt: 'Which strategy fits this integral?',
        options: [
          { text: 'Save one $\\sin x$ and let $u = \\cos x$', mistake: 'even-powers-no-identity', why: 'Saving sin x leaves a single sin x, which needs a square root in terms of cos x.' },
          { text: 'Save one $\\cos x$ and let $u = \\sin x$', mistake: 'even-powers-no-identity', why: 'Saving cos x leaves a single cos x, which needs a square root in terms of sin x.' },
          { text: 'Use the half-angle identities for $\\sin^2 x$ and $\\cos^2 x$' },
          { text: 'Write $\\sin^2 x = 1 - \\cos^2 x$ and let $u = \\cos x$', mistake: 'even-powers-no-identity', why: 'No sin x dx is left over to form du = −sin x dx.' },
          { text: 'Integration by parts with $u = \\sin^2 x$, $dv = \\cos^2 x\\,dx$', mistake: 'technique-wrong', why: 'Parts leaves another product of even powers; the half-angle identities reduce the powers directly.' },
        ],
        correct: 2,
        explanation: 'Powers 2 and 2 are both even, so no factor can be saved for a substitution; reduce the powers instead.',
        result: { text: 'Both even: use $\\sin^2 x = \\frac{1 - \\cos 2x}{2}$ and $\\cos^2 x = \\frac{1 + \\cos 2x}{2}$.' },
      },
      {
        prompt: 'Multiply the two half-angle forms. $\\sin^2 x\\cos^2 x$ equals',
        options: [
          { latex: '\\frac{1}{4}(1 + \\cos^2 2x)', expr: '(1 + cos(2*x)^2)/4', mistake: 'algebra-error', why: '(1 − a)(1 + a) = 1 − a², not 1 + a².' },
          { latex: '\\frac{1}{2}(1 - \\cos^2 2x)', expr: '(1 - cos(2*x)^2)/2', mistake: 'coefficient-mishandled', why: 'The two factors 1/2 multiply to 1/4, not 1/2.' },
          { latex: '\\frac{1}{4}(1 - \\cos^2 x)', expr: '(1 - cos(x)^2)/4', mistake: 'half-angle-wrong', why: 'The half-angle identities use cos 2x, not cos x.' },
          { latex: '\\frac{1}{4}(1 - \\cos 2x)^2', expr: '(1 - cos(2*x))^2/4', mistake: 'half-angle-wrong', why: 'The sine identity was used for both factors; cos²x = (1 + cos 2x)/2.' },
          { latex: '\\frac{1}{4}(1 - \\cos^2 2x)', expr: '(1 - cos(2*x)^2)/4' },
        ],
        correct: 4,
        explanation: '$\\frac{1 - \\cos 2x}{2}\\cdot\\frac{1 + \\cos 2x}{2} = \\frac{1 - \\cos^2 2x}{4}$ (difference of squares).',
        result: { latex: '\\sin^2 x\\cos^2 x = \\frac{1 - \\cos 2x}{2}\\cdot\\frac{1 + \\cos 2x}{2} = \\frac{1}{4}(1 - \\cos^2 2x)' },
        check: { kind: 'identity', lhs: 'sin(x)^2*cos(x)^2' },
      },
      {
        prompt: 'Reduce $\\cos^2 2x$ with the half-angle identity again. The integrand becomes',
        options: [
          { latex: '\\frac{1}{4} + \\frac{1}{8}\\cos 4x', expr: '1/4 + cos(4*x)/8', mistake: 'half-angle-wrong', why: 'Two slips: cos²2x was reduced with the sine identity (1 − cos 4x)/2, and the constant ¼·½ was never subtracted.' },
          { latex: '\\frac{1}{8}(1 - \\cos 4x)', expr: '(1 - cos(4*x))/8' },
          { latex: '\\frac{1}{8}(1 - \\cos 2x)', expr: '(1 - cos(2*x))/8', mistake: 'half-angle-wrong', why: 'Reducing cos²(2x) doubles the angle to 4x.' },
          { latex: '-\\frac{1}{4}\\cos 4x', expr: '-cos(4*x)/4', mistake: 'half-angle-wrong', why: 'cos²(2x) = (1 + cos 4x)/2; without the 1/2 the constant terms cancel.' },
          { latex: '\\frac{1}{4} - \\frac{1}{8}\\cos 4x', expr: '1/4 - cos(4*x)/8', mistake: 'algebra-error', why: '¼ − ¼·(1 + cos 4x)/2 = ⅛ − ⅛cos 4x; the ¼·½ from the constant was not subtracted.' },
        ],
        correct: 1,
        explanation: '$\\frac{1}{4}\\left(1 - \\frac{1 + \\cos 4x}{2}\\right) = \\frac{1}{4}\\cdot\\frac{1 - \\cos 4x}{2} = \\frac{1}{8}(1 - \\cos 4x)$.',
        result: { latex: '= \\frac{1}{4}\\left(1 - \\frac{1 + \\cos 4x}{2}\\right) = \\frac{1}{8}(1 - \\cos 4x)' },
        check: { kind: 'identity', lhs: 'sin(x)^2*cos(x)^2' },
      },
      {
        prompt: 'Integrate $\\frac{1}{8}(1 - \\cos 4x)$.',
        options: [
          { latex: '\\frac{x}{8} - \\frac{\\sin 4x}{8} + C', expr: 'x/8 - sin(4*x)/8', mistake: 'inner-constant-factor-missing', why: '∫cos 4x dx = ¼ sin 4x; the 1/4 was dropped.' },
          { latex: '\\frac{x}{8} + \\frac{\\sin 4x}{32} + C', expr: 'x/8 + sin(4*x)/32', mistake: 'trig-antiderivative-sign', why: '∫cos 4x dx = +¼ sin 4x; taking it as −¼ sin 4x flips the sign.' },
          { latex: '\\frac{x}{8} - \\frac{\\sin 4x}{2} + C', expr: 'x/8 - sin(4*x)/2', mistake: 'inner-constant-factor-missing', why: 'Multiplied by the inner 4 instead of dividing by it.' },
          { latex: '\\frac{x}{8} + \\frac{\\cos 4x}{32} + C', expr: 'x/8 + cos(4*x)/32', mistake: 'trig-antiderivative-swapped', why: 'Cosine integrates to sine; −cos is the antiderivative of sin.' },
          { latex: '\\frac{x}{8} - \\frac{\\sin 4x}{32} + C', expr: 'x/8 - sin(4*x)/32' },
        ],
        correct: 4,
        explanation: '$\\frac{1}{8}\\left(x - \\frac{\\sin 4x}{4}\\right) + C = \\frac{x}{8} - \\frac{\\sin 4x}{32} + C$.',
        result: { latex: '= \\frac{x}{8} - \\frac{1}{8}\\cdot\\frac{\\sin 4x}{4} + C = \\frac{x}{8} - \\frac{\\sin 4x}{32} + C' },
        check: { kind: 'antiderivative', integrand: 'sin(x)^2*cos(x)^2' },
      },
    ],
    final: {
      latex: '\\frac{x}{8} - \\frac{\\sin 4x}{32} + C',
      expr: 'x/8 - sin(4*x)/32',
      check: { kind: 'antiderivative', integrand: 'sin(x)^2*cos(x)^2' },
      recap: 'Both powers even: multiply the half-angle forms, reduce $\\cos^2 2x$ once more, and divide by 4 when integrating $\\cos 4x$.',
    },
  },
  {
    id: 'ti-s-03',
    topic: 'trig-integrals',
    title: 'Even power of secant',
    difficulty: 1,
    statement: { text: 'Evaluate', latex: '\\int \\sec^4 x\\,dx' },
    steps: [
      {
        prompt: 'Which strategy fits this integral?',
        options: [
          { text: 'Save $\\sec x\\tan x$ and let $u = \\sec x$', mistake: 'trig-wrong-factor-saved', why: 'There is no tangent factor in the integrand to save.' },
          { text: 'Integration by parts with $u = \\sec^2 x$, $dv = \\sec^2 x\\,dx$', mistake: 'technique-wrong', why: 'Parts is the plan for odd powers of secant; an even power allows a direct substitution.' },
          { text: 'Substitute $u = \\sec x$ and integrate $u^4$', mistake: 'u-choice-wrong', why: 'u = sec x needs du = sec x tan x dx, which is not in the integrand.' },
          { text: 'Save $\\sec^2 x$ and let $u = \\tan x$' },
          { text: 'Save $\\sec^2 x$ and let $u = \\sec x$', mistake: 'trig-wrong-factor-saved', why: 'The saved sec²x dx is du for u = tan x, not for u = sec x.' },
        ],
        correct: 3,
        explanation: 'The secant power 4 is even: $\\sec^2 x\\,dx = du$ for $u = \\tan x$, and the other $\\sec^2 x$ converts to $\\tan^2 x + 1$.',
        result: { text: 'Even power of secant: save $\\sec^2 x\\,dx$, use $u = \\tan x$.' },
      },
      {
        prompt: 'Rewrite the integral using the saved factor.',
        options: [
          { latex: '\\int (\\tan^2 x - 1)\\sec^2 x\\,dx', expr: 'indefinite((tan(x)^2 - 1)*sec(x)^2, x)', mistake: 'tan-sec-identity-direction', why: 'sec²x = tan²x + 1; writing tan²x − 1 reverses the identity.' },
          { latex: '\\int (\\tan^2 x + 1)\\sec^2 x\\,dx', expr: 'indefinite((tan(x)^2 + 1)*sec(x)^2, x)' },
          { latex: '\\int (\\tan^2 x - 1)\\sec x\\,dx', expr: 'indefinite((tan(x)^2 - 1)*sec(x), x)', mistake: 'tan-sec-identity-direction', why: 'Two slips: sec²x = tan²x + 1 (not tan²x − 1), and the saved factor is sec²x, not sec x.' },
          { latex: '\\int \\tan^2 x\\sec^2 x\\,dx', expr: 'indefinite(tan(x)^2*sec(x)^2, x)', mistake: 'pythagorean-wrong', why: 'The +1 in sec²x = tan²x + 1 was dropped.' },
          { latex: '\\int (\\tan^2 x + 1)\\sec x\\,dx', expr: 'indefinite((tan(x)^2 + 1)*sec(x), x)', mistake: 'exponent-arithmetic', why: 'sec⁴x = sec²x·sec²x; after converting one sec²x, the saved factor is sec²x, not sec x.' },
        ],
        correct: 1,
        explanation: '$\\sec^4 x = \\sec^2 x\\cdot\\sec^2 x = (\\tan^2 x + 1)\\sec^2 x$.',
        result: { latex: '\\int \\sec^2 x\\,\\sec^2 x\\,dx = \\int (\\tan^2 x + 1)\\sec^2 x\\,dx' },
        check: { kind: 'identity', lhs: 'indefinite(sec(x)^4, x)' },
      },
      {
        prompt: 'Substitute $u = \\tan x$, $du = \\sec^2 x\\,dx$. The integral becomes',
        options: [
          { latex: '\\int (u^2 + 1)^2\\,du', expr: 'indefinite((u^2 + 1)^2, u)', mistake: 'exponent-arithmetic', why: 'The saved sec²x dx is du; converting it to u² + 1 as well counts it twice.' },
          { latex: '\\int (u^2 + 1)u^2\\,du', expr: 'indefinite((u^2 + 1)*u^2, u)', mistake: 'exponent-arithmetic', why: 'The saved sec²x was counted twice: it became du and was also rewritten as tan²x = u².' },
          { latex: '\\int u^4\\,du', expr: 'indefinite(u^4, u)', mistake: 'u-choice-wrong', why: 'This treats sec x as u; with u = tan x, sec⁴x dx = (u² + 1)du.' },
          { latex: '\\int (u^2 + 1)\\sec^2 x\\,du', expr: 'indefinite((u^2 + 1)*sec(x)^2, u)', mistake: 'leftover-x-in-u-integral', why: 'sec²x dx became du; the sec²x must not stay in the u-integral.' },
          { latex: '\\int (u^2 + 1)\\,du', expr: 'indefinite(u^2 + 1, u)' },
        ],
        correct: 4,
        explanation: '$(\\tan^2 x + 1)\\sec^2 x\\,dx = (u^2 + 1)\\,du$.',
        result: { latex: 'u = \\tan x,\\ du = \\sec^2 x\\,dx:\\quad \\int (u^2 + 1)\\,du' },
        variable: 'u',
        domain: { u: [0.3, 1.2] },
        check: { kind: 'identity', lhs: 'indefinite(u^2 + 1, u)' },
      },
      {
        prompt: 'Integrate and substitute back.',
        options: [
          { latex: '\\frac{1}{3}\\sec^3 x + \\sec x + C', expr: 'sec(x)^3/3 + sec(x)', mistake: 'back-substitution-wrong', why: 'u was tan x, so u³/3 + u must become tangents, not secants.' },
          { latex: '\\tan x + \\tan^3 x + C', expr: 'tan(x) + tan(x)^3', mistake: 'power-rule-int-coefficient', why: '∫u² du = u³/3; the 1/3 was dropped.' },
          { latex: '\\frac{1}{3}\\tan^3 x + C', expr: 'tan(x)^3/3', mistake: 'constant-not-integrated', why: '∫1 du = u = tan x; the 1 was treated as a constant absorbed into C instead of being integrated.' },
          { latex: '\\tan x + \\frac{1}{3}\\tan^3 x + C', expr: 'tan(x) + tan(x)^3/3' },
          { latex: '\\frac{u^3}{3} + u + C', expr: 'u^3/3 + u', mistake: 'not-back-substituted', why: 'The answer must be written in x: replace u by tan x.' },
        ],
        correct: 3,
        explanation: '$\\frac{u^3}{3} + u + C$ with $u = \\tan x$.',
        result: { latex: '= \\frac{u^3}{3} + u + C = \\frac{1}{3}\\tan^3 x + \\tan x + C' },
        check: { kind: 'antiderivative', integrand: 'sec(x)^4' },
      },
    ],
    final: {
      latex: '\\tan x + \\frac{1}{3}\\tan^3 x + C',
      expr: 'tan(x) + tan(x)^3/3',
      check: { kind: 'antiderivative', integrand: 'sec(x)^4' },
      recap: 'Even power of secant: save $\\sec^2 x\\,dx$ as $du$ and convert the rest with $\\sec^2 x = \\tan^2 x + 1$.',
    },
  },
  {
    id: 'ti-s-04',
    topic: 'trig-integrals',
    title: 'Odd power of tangent with secant',
    difficulty: 2,
    statement: { text: 'Evaluate', latex: '\\int \\tan^3 x\\sec^3 x\\,dx' },
    steps: [
      {
        prompt: 'Which strategy fits this integral?',
        options: [
          { text: 'Save $\\sec^2 x$ and let $u = \\tan x$', mistake: 'trig-wrong-factor-saved', why: 'sec³x is odd: saving sec²x leaves sec x, which needs a square root in terms of tan x.' },
          { text: 'Save $\\sec x\\tan x$ and let $u = \\sec x$' },
          { text: 'Integration by parts with $dv = \\sec^2 x\\,dx$', mistake: 'technique-wrong', why: 'Parts is the plan for odd powers of secant with no tangent; an odd tangent power allows u = sec x.' },
          { text: 'Save $\\sec x\\tan x$ and let $u = \\tan x$', mistake: 'trig-wrong-factor-saved', why: 'u = tan x needs du = sec²x dx; the saved sec x tan x dx does not match.' },
          { text: 'Use the half-angle identities', mistake: 'technique-wrong', why: 'Half-angle identities reduce even powers of sine and cosine, not tangent and secant.' },
        ],
        correct: 1,
        explanation: 'The tangent power 3 is odd and secant is present: $\\sec x\\tan x\\,dx = du$ for $u = \\sec x$, and $\\tan^2 x = u^2 - 1$.',
        result: { text: 'Odd tangent power: save $\\sec x\\tan x\\,dx$, use $u = \\sec x$.' },
      },
      {
        prompt: 'Rewrite the integral using the saved factor.',
        options: [
          { latex: '\\int (\\sec^2 x + 1)\\sec^2 x\\,\\sec x\\tan x\\,dx', expr: 'indefinite((sec(x)^2 + 1)*sec(x)^2*sec(x)*tan(x), x)', mistake: 'tan-sec-identity-direction', why: 'tan²x = sec²x − 1, not sec²x + 1.' },
          { latex: '\\int (1 - \\sec^2 x)\\sec^2 x\\,\\sec x\\tan x\\,dx', expr: 'indefinite((1 - sec(x)^2)*sec(x)^2*sec(x)*tan(x), x)', mistake: 'pythagorean-wrong', why: 'This copies the sin²x = 1 − cos²x pattern; tan²x = sec²x − 1.' },
          { latex: '\\int (\\sec^2 x - 1)\\sec^3 x\\,\\sec x\\tan x\\,dx', expr: 'indefinite((sec(x)^2 - 1)*sec(x)^3*sec(x)*tan(x), x)', mistake: 'exponent-arithmetic', why: 'The saved sec x tan x uses up one secant, leaving sec²x; sec³x was kept.' },
          { latex: '\\int (\\sec^2 x - 1)\\sec^2 x\\,\\sec x\\tan x\\,dx', expr: 'indefinite((sec(x)^2 - 1)*sec(x)^2*sec(x)*tan(x), x)' },
          { latex: '\\int (\\sec^2 x + 1)\\sec^3 x\\,\\sec x\\tan x\\,dx', expr: 'indefinite((sec(x)^2 + 1)*sec(x)^3*sec(x)*tan(x), x)', mistake: 'tan-sec-identity-direction', why: 'Two slips: tan²x = sec²x − 1 (not + 1), and the saved sec x tan x uses up one secant, leaving sec²x rather than sec³x.' },
        ],
        correct: 3,
        explanation: '$\\tan^3 x\\sec^3 x = \\tan^2 x\\sec^2 x\\,(\\sec x\\tan x) = (\\sec^2 x - 1)\\sec^2 x\\,(\\sec x\\tan x)$.',
        result: { latex: '\\int \\tan^2 x\\sec^2 x\\,(\\sec x\\tan x)\\,dx = \\int (\\sec^2 x - 1)\\sec^2 x\\,\\sec x\\tan x\\,dx' },
        check: { kind: 'identity', lhs: 'indefinite(tan(x)^3*sec(x)^3, x)' },
      },
      {
        prompt: 'Substitute $u = \\sec x$, $du = \\sec x\\tan x\\,dx$. The integral becomes',
        options: [
          { latex: '-\\int (u^2 - 1)u^2\\,du', expr: '-indefinite((u^2 - 1)*u^2, u)', mistake: 'du-derivative-wrong', why: 'd(sec x) = +sec x tan x dx; there is no minus sign.' },
          { latex: '\\int (u^2 - 1)u^3\\,du', expr: 'indefinite((u^2 - 1)*u^3, u)', mistake: 'exponent-arithmetic', why: 'The sec x inside sec x tan x dx is part of du; counting it again gives u³.' },
          { latex: '\\int (u^2 - 1)u^2\\,du', expr: 'indefinite((u^2 - 1)*u^2, u)' },
          { latex: '\\int (u^2 - 1)u^2\\tan x\\,du', expr: 'indefinite((u^2 - 1)*u^2*tan(x), u)', mistake: 'leftover-x-in-u-integral', why: 'The saved sec x tan x dx became du; tan x must not stay in the u-integral.' },
          { latex: '\\int (u^2 - 1)^2u^2\\,du', expr: 'indefinite((u^2 - 1)^2*u^2, u)', mistake: 'exponent-arithmetic', why: 'tan²x = u² − 1 appears once; squaring it describes tan⁵x.' },
        ],
        correct: 2,
        explanation: '$(\\sec^2 x - 1)\\sec^2 x\\,(\\sec x\\tan x\\,dx) = (u^2 - 1)u^2\\,du$.',
        result: { latex: 'u = \\sec x,\\ du = \\sec x\\tan x\\,dx:\\quad \\int (u^2 - 1)u^2\\,du = \\int (u^4 - u^2)\\,du' },
        variable: 'u',
        domain: { u: [1.1, 2] },
        check: { kind: 'identity', lhs: 'indefinite((u^2 - 1)*u^2, u)' },
      },
      {
        prompt: 'Integrate and substitute back.',
        options: [
          { latex: '\\frac{1}{5}\\tan^5 x - \\frac{1}{3}\\tan^3 x + C', expr: 'tan(x)^5/5 - tan(x)^3/3', mistake: 'back-substitution-wrong', why: 'u was sec x, so the powers of u must become powers of sec x.' },
          { latex: '\\frac{1}{5}\\sec^5 x + \\frac{1}{3}\\sec^3 x + C', expr: 'sec(x)^5/5 + sec(x)^3/3', mistake: 'sign-error', why: '∫(u⁴ − u²)du keeps the minus: u⁵/5 − u³/3.' },
          { latex: '\\sec^5 x - \\sec^3 x + C', expr: 'sec(x)^5 - sec(x)^3', mistake: 'power-rule-int-coefficient', why: '∫u⁴ du = u⁵/5 and ∫u² du = u³/3; the divisions were skipped.' },
          { latex: '\\frac{1}{4}\\sec^4 x - \\frac{1}{2}\\sec^2 x + C', expr: 'sec(x)^4/4 - sec(x)^2/2', mistake: 'power-rule-int-exponent', why: 'The exponent must go up by one: ∫u⁴ du = u⁵/5, not u⁴/4.' },
          { latex: '\\frac{1}{5}\\sec^5 x - \\frac{1}{3}\\sec^3 x + C', expr: 'sec(x)^5/5 - sec(x)^3/3' },
          { latex: '\\frac{u^5}{5} - \\frac{u^3}{3} + C', expr: 'u^5/5 - u^3/3', mistake: 'not-back-substituted', why: 'The answer must be written in x: replace u by sec x.' },
        ],
        correct: 4,
        explanation: '$\\frac{u^5}{5} - \\frac{u^3}{3} + C$ with $u = \\sec x$.',
        result: { latex: '= \\frac{u^5}{5} - \\frac{u^3}{3} + C = \\frac{1}{5}\\sec^5 x - \\frac{1}{3}\\sec^3 x + C' },
        check: { kind: 'antiderivative', integrand: 'tan(x)^3*sec(x)^3' },
      },
    ],
    final: {
      latex: '\\frac{1}{5}\\sec^5 x - \\frac{1}{3}\\sec^3 x + C',
      expr: 'sec(x)^5/5 - sec(x)^3/3',
      check: { kind: 'antiderivative', integrand: 'tan(x)^3*sec(x)^3' },
      recap: 'Odd power of tangent: save $\\sec x\\tan x\\,dx$ as $du$ and turn the leftover even tangent power into secants with $\\tan^2 x = \\sec^2 x - 1$.',
    },
  },
  {
    id: 'ti-s-05',
    topic: 'trig-integrals',
    title: 'Odd power of secant: parts and solve',
    difficulty: 2,
    statement: { text: 'Evaluate', latex: '\\int \\sec^3 x\\,dx' },
    steps: [
      {
        prompt: 'Which strategy fits this integral?',
        options: [
          { text: 'Save $\\sec^2 x$ and let $u = \\tan x$', mistake: 'sec-odd-power-strategy', why: 'The leftover sec x cannot be written in tan x without a square root.' },
          { text: 'Substitute $u = \\sec x$, $du = \\sec x\\tan x\\,dx$', mistake: 'sec-odd-power-strategy', why: 'There is no tan x in the integrand to complete du.' },
          { text: 'Integration by parts with $u = \\sec^2 x$, $dv = \\sec x\\,dx$', mistake: 'ibp-wrong-u-dv', why: 'v = ln|sec x + tan x| makes the new integral harder; take dv = sec²x dx.' },
          { text: 'Save $\\sec x\\tan x$ and let $u = \\sec x$', mistake: 'trig-wrong-factor-saved', why: 'There is no tangent factor in the integrand to save.' },
          { text: 'Integration by parts with $u = \\sec x$, $dv = \\sec^2 x\\,dx$' },
        ],
        correct: 4,
        explanation: 'An odd power of secant alone needs parts: $dv = \\sec^2 x\\,dx$ has the simple antiderivative $v = \\tan x$.',
        result: { text: 'Parts: $u = \\sec x$, $dv = \\sec^2 x\\,dx$.' },
      },
      {
        prompt: 'With $du = \\sec x\\tan x\\,dx$ and $v = \\tan x$, integration by parts gives $\\int \\sec^3 x\\,dx =$',
        options: [
          { latex: '\\sec x\\tan x + \\int \\sec x\\tan^2 x\\,dx', expr: 'sec(x)*tan(x) + indefinite(sec(x)*tan(x)^2, x)', mistake: 'ibp-sign-error', why: 'The formula is uv − ∫v du; the integral is subtracted.' },
          { latex: '\\sec x\\tan x - \\int \\sec x\\tan^2 x\\,dx', expr: 'sec(x)*tan(x) - indefinite(sec(x)*tan(x)^2, x)' },
          { latex: '\\sec x\\tan x - \\int \\tan x\\sec^2 x\\,dx', expr: 'sec(x)*tan(x) - indefinite(tan(x)*sec(x)^2, x)', mistake: 'ibp-du-wrong', why: 'd(sec x) = sec x tan x dx; sec²x dx is d(tan x).' },
          { latex: '\\sec x\\tan x - \\int \\tan^2 x\\,dx', expr: 'sec(x)*tan(x) - indefinite(tan(x)^2, x)', mistake: 'ibp-du-wrong', why: 'du = sec x tan x dx; the factor sec x was dropped from v du.' },
          { latex: '\\sec x\\tan x - \\int \\sec x\\tan x\\,dx', expr: 'sec(x)*tan(x) - indefinite(sec(x)*tan(x), x)', mistake: 'ibp-formula-wrong', why: 'The formula subtracts ∫v du = ∫tan x·sec x tan x dx, not ∫du.' },
        ],
        correct: 1,
        explanation: '$uv - \\int v\\,du = \\sec x\\tan x - \\int \\tan x\\cdot\\sec x\\tan x\\,dx$.',
        result: { latex: '\\int \\sec^3 x\\,dx = \\sec x\\tan x - \\int \\sec x\\tan^2 x\\,dx' },
      },
      {
        prompt: 'Use $\\tan^2 x = \\sec^2 x - 1$ in the new integral. The right side becomes',
        options: [
          { latex: '\\sec x\\tan x - \\int \\sec^3 x\\,dx - \\int \\sec x\\,dx', expr: 'sec(x)*tan(x) - indefinite(sec(x)^3, x) - indefinite(sec(x), x)', mistake: 'tan-sec-identity-direction', why: 'tan²x = sec²x − 1; using sec²x + 1 flips the sign of the ∫sec x dx term.' },
          { latex: '\\sec x\\tan x + \\int \\sec^3 x\\,dx - \\int \\sec x\\,dx', expr: 'sec(x)*tan(x) + indefinite(sec(x)^3, x) - indefinite(sec(x), x)', mistake: 'pythagorean-wrong', why: 'tan²x was written as 1 − sec²x, which flips both terms.' },
          { latex: '\\sec x\\tan x - \\int \\sec^3 x\\,dx + \\int 1\\,dx', expr: 'sec(x)*tan(x) - indefinite(sec(x)^3, x) + indefinite(1, x)', mistake: 'algebra-error', why: 'sec x(sec²x − 1) = sec³x − sec x; the second term keeps its factor sec x.' },
          { latex: '\\sec x\\tan x - \\int \\sec^2 x\\,dx - \\int \\sec x\\,dx', expr: 'sec(x)*tan(x) - indefinite(sec(x)^2, x) - indefinite(sec(x), x)', mistake: 'exponent-arithmetic', why: 'Two slips: sec x·sec²x = sec³x (not sec²x), and after the outer minus the ∫sec x dx term must be positive.' },
          { latex: '\\sec x\\tan x - \\int \\sec^3 x\\,dx + \\int \\sec x\\,dx', expr: 'sec(x)*tan(x) - indefinite(sec(x)^3, x) + indefinite(sec(x), x)' },
        ],
        correct: 4,
        explanation: '$\\int \\sec x(\\sec^2 x - 1)\\,dx = \\int \\sec^3 x\\,dx - \\int \\sec x\\,dx$, and the minus in front flips both signs.',
        result: { latex: '\\int \\sec^3 x\\,dx = \\sec x\\tan x - \\int \\sec^3 x\\,dx + \\int \\sec x\\,dx' },
        check: { kind: 'value', expected: 'sec(x)*tan(x) - indefinite(sec(x)*tan(x)^2, x)' },
      },
      {
        prompt: 'The original integral appears on both sides. Solve for it.',
        options: [
          { latex: '\\int \\sec^3 x\\,dx = \\sec x\\tan x + \\int \\sec x\\,dx', expr: 'sec(x)*tan(x) + indefinite(sec(x), x)', mistake: 'ibp-cyclic-algebra', why: 'Moving ∫sec³x to the left gives 2∫sec³x; the division by 2 was skipped.' },
          { latex: '\\int \\sec^3 x\\,dx = \\frac{1}{2}\\sec x\\tan x + \\int \\sec x\\,dx', expr: 'sec(x)*tan(x)/2 + indefinite(sec(x), x)', mistake: 'ibp-cyclic-algebra', why: 'Only sec x tan x was divided by 2; every term on the right must be halved.' },
          { latex: '\\int \\sec^3 x\\,dx = \\frac{1}{2}\\sec x\\tan x - \\frac{1}{2}\\int \\sec x\\,dx', expr: 'sec(x)*tan(x)/2 - indefinite(sec(x), x)/2', mistake: 'sign-error', why: 'Only ∫sec³x changes sides; +∫sec x dx keeps its sign.' },
          { latex: '\\int \\sec^3 x\\,dx = \\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\int \\sec x\\,dx', expr: 'sec(x)*tan(x)/2 + indefinite(sec(x), x)/2' },
          { latex: '\\int \\sec^3 x\\,dx = 2\\sec x\\tan x + 2\\int \\sec x\\,dx', expr: '2*sec(x)*tan(x) + 2*indefinite(sec(x), x)', mistake: 'ibp-cyclic-algebra', why: 'From 2∫sec³x dx = …, divide by 2; this multiplied by 2 instead.' },
        ],
        correct: 3,
        explanation: 'Add $\\int \\sec^3 x\\,dx$ to both sides: $2\\int \\sec^3 x\\,dx = \\sec x\\tan x + \\int \\sec x\\,dx$, then halve.',
        result: { latex: '2\\int \\sec^3 x\\,dx = \\sec x\\tan x + \\int \\sec x\\,dx \\Rightarrow \\int \\sec^3 x\\,dx = \\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\int \\sec x\\,dx' },
      },
      {
        prompt: 'Finish with the antiderivative of $\\sec x$.',
        options: [
          { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(sec(x)))/2', mistake: 'sec-antiderivative-wrong', why: 'ln|sec x| is ∫tan x dx; ∫sec x dx = ln|sec x + tan x|.' },
          { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x - \\tan x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(sec(x) - tan(x)))/2', mistake: 'sec-antiderivative-wrong', why: 'd/dx ln|sec x − tan x| = −sec x; the sign inside must be +.' },
          { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x + \\tan x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(sec(x) + tan(x)))/2' },
          { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\csc x - \\cot x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(csc(x) - cot(x)))/2', mistake: 'formula-swapped', why: 'ln|csc x − cot x| is ∫csc x dx.' },
          { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\tan x + C', expr: 'sec(x)*tan(x)/2 + tan(x)/2', mistake: 'trig-antiderivative-swapped', why: 'tan x is ∫sec²x dx, not ∫sec x dx.' },
        ],
        correct: 2,
        explanation: '$\\int \\sec x\\,dx = \\ln|\\sec x + \\tan x| + C$.',
        result: { latex: '= \\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x + \\tan x| + C' },
        check: { kind: 'antiderivative', integrand: 'sec(x)^3' },
      },
    ],
    final: {
      latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x + \\tan x| + C',
      expr: 'sec(x)*tan(x)/2 + log(abs(sec(x) + tan(x)))/2',
      check: { kind: 'antiderivative', integrand: 'sec(x)^3' },
      recap: 'An odd power of secant alone: parts with $dv = \\sec^2 x\\,dx$, turn $\\tan^2 x$ into $\\sec^2 x - 1$, and solve for the integral that reappears (divide by 2).',
    },
  },
  {
    id: 'ti-s-06',
    topic: 'trig-integrals',
    title: 'Only tangent',
    difficulty: 1,
    statement: { text: 'Evaluate', latex: '\\int \\tan^4 x\\,dx' },
    steps: [
      {
        prompt: 'Which first move fits this integral?',
        options: [
          { text: 'Let $u = \\tan x$ and integrate $u^4$', mistake: 'u-choice-wrong', why: 'u = tan x needs du = sec²x dx, which is not in the integrand yet.' },
          { text: 'Write $\\tan^4 x = \\tan^2 x(\\sec^2 x + 1)$ and split', mistake: 'tan-sec-identity-direction', why: 'tan²x = sec²x − 1, not sec²x + 1.' },
          { text: 'Save $\\sec x\\tan x$ and let $u = \\sec x$', mistake: 'trig-wrong-factor-saved', why: 'There is no secant factor in the integrand to save.' },
          { text: 'Write $\\tan^4 x = \\tan^2 x(\\sec^2 x - 1)$ and split' },
          { text: 'Integration by parts with $u = \\tan^3 x$, $dv = \\tan x\\,dx$', mistake: 'technique-wrong', why: 'v = −ln|cos x| makes the new integral harder, not easier.' },
        ],
        correct: 3,
        explanation: 'With only tangent, replace one $\\tan^2 x$ by $\\sec^2 x - 1$: one piece gets a $\\sec^2 x$ for $u = \\tan x$, the other has a lower power.',
        result: { latex: '\\tan^4 x = \\tan^2 x\\,\\tan^2 x = \\tan^2 x(\\sec^2 x - 1)' },
      },
      {
        prompt: 'Split the integral.',
        options: [
          { latex: '\\int \\tan^2 x\\sec^2 x\\,dx + \\int \\tan^2 x\\,dx', expr: 'indefinite(tan(x)^2*sec(x)^2, x) + indefinite(tan(x)^2, x)', mistake: 'sign-error', why: 'tan²x(sec²x − 1) = tan²x sec²x − tan²x; the second piece is subtracted.' },
          { latex: '\\int \\tan^2 x\\sec^2 x\\,dx - \\int 1\\,dx', expr: 'indefinite(tan(x)^2*sec(x)^2, x) - indefinite(1, x)', mistake: 'algebra-error', why: 'tan²x multiplies both terms: the second piece is tan²x·1, not 1.' },
          { latex: '\\int \\tan^2 x\\sec^2 x\\,dx + \\int 1\\,dx', expr: 'indefinite(tan(x)^2*sec(x)^2, x) + indefinite(1, x)', mistake: 'algebra-error', why: 'Two slips: the second piece is tan²x·1, not 1, and it is subtracted, not added.' },
          { latex: '\\int \\tan^2 x\\sec^2 x\\,dx - \\int \\tan^2 x\\,dx', expr: 'indefinite(tan(x)^2*sec(x)^2, x) - indefinite(tan(x)^2, x)' },
          { latex: '\\int \\tan x\\sec^2 x\\,dx - \\int \\tan x\\,dx', expr: 'indefinite(tan(x)*sec(x)^2, x) - indefinite(tan(x), x)', mistake: 'exponent-arithmetic', why: 'That split belongs to tan³x; for tan⁴x a factor tan²x stays in both pieces.' },
        ],
        correct: 3,
        explanation: '$\\tan^2 x(\\sec^2 x - 1) = \\tan^2 x\\sec^2 x - \\tan^2 x$.',
        result: { latex: '\\int \\tan^4 x\\,dx = \\int \\tan^2 x\\sec^2 x\\,dx - \\int \\tan^2 x\\,dx' },
        check: { kind: 'identity', lhs: 'indefinite(tan(x)^4, x)' },
      },
      {
        prompt: 'Evaluate the first piece, $\\int \\tan^2 x\\sec^2 x\\,dx$.',
        options: [
          { latex: '\\frac{1}{3}\\tan^3 x + C', expr: 'tan(x)^3/3' },
          { latex: '\\frac{1}{3}\\sec^3 x + C', expr: 'sec(x)^3/3', mistake: 'back-substitution-wrong', why: 'With u = tan x, du = sec²x dx, the result u³/3 is ⅓tan³x.' },
          { latex: '\\tan^3 x + C', expr: 'tan(x)^3', mistake: 'power-rule-int-coefficient', why: '∫u² du = u³/3; the 1/3 was dropped.' },
          { latex: '\\frac{1}{3}\\tan^3 x\\sec^2 x + C', expr: 'tan(x)^3*sec(x)^2/3', mistake: 'leftover-x-in-u-integral', why: 'sec²x dx is du; it is used up by the substitution and does not stay in the answer.' },
          { latex: '(\\tan x - x)\\tan x + C', expr: '(tan(x) - x)*tan(x)', mistake: 'product-rule-integral', why: 'tan²x and sec²x were integrated separately and multiplied; there is no product rule for integrals.' },
        ],
        correct: 0,
        explanation: '$u = \\tan x$, $du = \\sec^2 x\\,dx$: $\\int u^2\\,du = \\frac{1}{3}\\tan^3 x + C$.',
        result: { latex: '\\int \\tan^2 x\\sec^2 x\\,dx = \\frac{1}{3}\\tan^3 x\\quad (u = \\tan x)' },
        check: { kind: 'antiderivative', integrand: 'tan(x)^2*sec(x)^2' },
      },
      {
        prompt: 'Evaluate the second piece, $\\int \\tan^2 x\\,dx$.',
        options: [
          { latex: '\\sec x\\tan x + x + C', expr: 'sec(x)*tan(x) + x', mistake: 'trig-antiderivative-swapped', why: 'Two slips: ∫sec²x dx = tan x (sec x tan x is the derivative of sec x), and tan²x = sec²x − 1 makes the x-term negative.' },
          { latex: '\\frac{1}{3}\\tan^3 x + C', expr: 'tan(x)^3/3', mistake: 'u-choice-wrong', why: 'Power rule with u = tan x, but du = sec²x dx is not in this integrand.' },
          { latex: '\\sec x\\tan x - x + C', expr: 'sec(x)*tan(x) - x', mistake: 'trig-antiderivative-swapped', why: 'sec x tan x is d/dx(sec x); ∫sec²x dx = tan x.' },
          { latex: 'x - \\tan x + C', expr: 'x - tan(x)', mistake: 'pythagorean-wrong', why: 'tan²x was rewritten as 1 − sec²x; the identity is tan²x = sec²x − 1.' },
          { latex: '\\tan x - x + C', expr: 'tan(x) - x' },
        ],
        correct: 4,
        explanation: '$\\int (\\sec^2 x - 1)\\,dx = \\tan x - x + C$.',
        result: { latex: '\\int \\tan^2 x\\,dx = \\int (\\sec^2 x - 1)\\,dx = \\tan x - x' },
        check: { kind: 'antiderivative', integrand: 'tan(x)^2' },
      },
      {
        prompt: 'Combine the two pieces.',
        options: [
          { latex: '\\frac{1}{3}\\tan^3 x - \\tan x - x + C', expr: 'tan(x)^3/3 - tan(x) - x', mistake: 'sign-error', why: 'Subtracting (tan x − x) gives −tan x + x; the minus was not distributed to x.' },
          { latex: '\\frac{1}{3}\\tan^3 x + \\tan x - x + C', expr: 'tan(x)^3/3 + tan(x) - x', mistake: 'sign-error', why: 'The second piece is subtracted, not added.' },
          { latex: '\\frac{1}{3}\\tan^3 x - \\tan x + x + C', expr: 'tan(x)^3/3 - tan(x) + x' },
          { latex: '\\frac{1}{3}\\tan^3 x - \\tan x + C', expr: 'tan(x)^3/3 - tan(x)', mistake: 'algebra-error', why: 'The +x from −(tan x − x) was dropped.' },
          { latex: '-\\frac{1}{3}\\tan^3 x + \\tan x - x + C', expr: '-tan(x)^3/3 + tan(x) - x', mistake: 'sign-error', why: 'Only the second integral is subtracted; the minus was applied to both pieces the wrong way round.' },
        ],
        correct: 2,
        explanation: '$\\frac{1}{3}\\tan^3 x - (\\tan x - x) + C$.',
        result: { latex: '= \\frac{1}{3}\\tan^3 x - (\\tan x - x) + C = \\frac{1}{3}\\tan^3 x - \\tan x + x + C' },
        check: { kind: 'antiderivative', integrand: 'tan(x)^4' },
      },
    ],
    final: {
      latex: '\\frac{1}{3}\\tan^3 x - \\tan x + x + C',
      expr: 'tan(x)^3/3 - tan(x) + x',
      check: { kind: 'antiderivative', integrand: 'tan(x)^4' },
      recap: 'With only tangent, peel off $\\tan^2 x = \\sec^2 x - 1$: one piece is a $u = \\tan x$ substitution, the other a lower power of tangent.',
    },
  },
  {
    id: 'ti-s-07',
    topic: 'trig-integrals',
    title: 'Even tangent, odd secant',
    difficulty: 2,
    statement: { text: 'Reduce to integrals of odd powers of secant:', latex: '\\int \\tan^4 x\\sec^3 x\\,dx' },
    steps: [
      {
        prompt: 'Which first move fits this integral?',
        options: [
          { text: 'Save $\\sec^2 x$ and let $u = \\tan x$', mistake: 'trig-wrong-factor-saved', why: 'sec³x is odd: after saving sec²x, the leftover sec x needs a square root in terms of tan x.' },
          { text: 'Save $\\sec x\\tan x$ and let $u = \\sec x$', mistake: 'trig-wrong-factor-saved', why: 'tan⁴x is even: after saving one tan x, tan³x needs a square root in terms of sec x.' },
          { text: 'Write $\\tan^4 x = (\\sec^2 x - 1)^2$ to get only powers of secant' },
          { text: 'Write $\\tan^4 x = (\\sec^2 x + 1)^2$ to get only powers of secant', mistake: 'tan-sec-identity-direction', why: 'tan²x = sec²x − 1, not sec²x + 1.' },
          { text: 'Use the half-angle identities', mistake: 'technique-wrong', why: 'Half-angle identities reduce even powers of sine and cosine, not tangent and secant.' },
        ],
        correct: 2,
        explanation: 'Neither factor can be saved (tangent even, secant odd), so convert every $\\tan^2 x$ to $\\sec^2 x - 1$.',
        result: { latex: '\\int \\tan^4 x\\sec^3 x\\,dx = \\int (\\sec^2 x - 1)^2\\sec^3 x\\,dx' },
      },
      {
        prompt: 'Expand the integrand.',
        options: [
          { latex: '\\int (\\sec^7 x - \\sec^3 x)\\,dx', expr: 'indefinite(sec(x)^7 - sec(x)^3, x)', mistake: 'algebra-error', why: '(sec²x − 1)² was squared term by term as sec⁴x − 1; it expands to sec⁴x − 2sec²x + 1.' },
          { latex: '\\int (\\sec^7 x + 2\\sec^5 x - \\sec^3 x)\\,dx', expr: 'indefinite(sec(x)^7 + 2*sec(x)^5 - sec(x)^3, x)', mistake: 'tan-sec-identity-direction', why: 'Two slips: tan²x = sec²x − 1 makes the middle term negative, and a squared bracket ends in +1, so the last term is +sec³x.' },
          { latex: '\\int (\\sec^6 x - 2\\sec^4 x + \\sec^2 x)\\,dx', expr: 'indefinite(sec(x)^6 - 2*sec(x)^4 + sec(x)^2, x)', mistake: 'exponent-arithmetic', why: 'The bracket must be multiplied by sec³x; this multiplied by sec²x.' },
          { latex: '\\int (\\sec^7 x - 2\\sec^5 x - \\sec^3 x)\\,dx', expr: 'indefinite(sec(x)^7 - 2*sec(x)^5 - sec(x)^3, x)', mistake: 'sign-error', why: '(sec²x − 1)² ends in +1, so the last term is +sec³x.' },
          { latex: '\\int (\\sec^7 x - 2\\sec^5 x + \\sec^3 x)\\,dx', expr: 'indefinite(sec(x)^7 - 2*sec(x)^5 + sec(x)^3, x)' },
        ],
        correct: 4,
        explanation: '$(\\sec^4 x - 2\\sec^2 x + 1)\\sec^3 x = \\sec^7 x - 2\\sec^5 x + \\sec^3 x$.',
        result: { latex: '= \\int \\sec^7 x\\,dx - 2\\int \\sec^5 x\\,dx + \\int \\sec^3 x\\,dx' },
        check: { kind: 'identity', lhs: 'indefinite(tan(x)^4*sec(x)^3, x)' },
      },
      {
        prompt: 'How is an odd power such as $\\int \\sec^5 x\\,dx$ handled?',
        options: [
          { text: 'Substitute $u = \\sec x$ and integrate $u^5$', mistake: 'sec-odd-power-strategy', why: 'du = sec x tan x dx is not in the integrand; an odd power of secant alone needs parts.' },
          { text: 'Save $\\sec^2 x$ and let $u = \\tan x$', mistake: 'sec-odd-power-strategy', why: 'The leftover sec³x is odd and cannot be written in tan x without a square root.' },
          { text: 'Integration by parts with $u = \\sec^3 x$, $dv = \\sec^2 x\\,dx$' },
          { text: 'Integration by parts with $u = \\sec^2 x$, $dv = \\sec^3 x\\,dx$', mistake: 'ibp-wrong-u-dv', why: 'dv = sec³x dx has no quick antiderivative; dv = sec²x dx integrates to tan x.' },
          { text: 'Save $\\sec x\\tan x$ and let $u = \\sec x$', mistake: 'sec-odd-power-strategy', why: 'After the rewrite there is no tangent factor left to save.' },
        ],
        correct: 2,
        explanation: 'Same plan as $\\int \\sec^3 x\\,dx$: parts with $dv = \\sec^2 x\\,dx$, convert $\\tan^2 x$, and combine like terms.',
        result: { text: 'Each odd power: parts with $dv = \\sec^2 x\\,dx$, as for $\\int \\sec^3 x\\,dx$.' },
      },
      {
        prompt: 'The last piece is the standard result $\\int \\sec^3 x\\,dx =$',
        options: [
          { latex: '\\frac{1}{2}\\sec x\\tan x - \\frac{1}{2}\\ln|\\sec x| + C', expr: 'sec(x)*tan(x)/2 - log(abs(sec(x)))/2', mistake: 'sec-antiderivative-wrong', why: 'Two slips: ∫sec x dx = ln|sec x + tan x| (ln|sec x| is ∫tan x dx), and using tan²x = sec²x + 1 flipped the sign of that term.' },
          { latex: '\\frac{1}{2}\\sec x\\tan x - \\frac{1}{2}\\ln|\\sec x + \\tan x| + C', expr: 'sec(x)*tan(x)/2 - log(abs(sec(x) + tan(x)))/2', mistake: 'tan-sec-identity-direction', why: 'Inside the parts step tan²x = sec²x − 1; using sec²x + 1 flips the log term.' },
          { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(sec(x)))/2', mistake: 'sec-antiderivative-wrong', why: 'ln|sec x| is ∫tan x dx; ∫sec x dx = ln|sec x + tan x|.' },
          { latex: '\\frac{1}{4}\\sec^4 x + C', expr: 'sec(x)^4/4', mistake: 'sec-odd-power-strategy', why: 'The power rule on sec x ignores du = sec x tan x dx; odd powers of secant need parts.' },
          { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x + \\tan x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(sec(x) + tan(x)))/2' },
        ],
        correct: 4,
        explanation: 'From parts: $2\\int \\sec^3 x\\,dx = \\sec x\\tan x + \\ln|\\sec x + \\tan x|$.',
        result: { latex: '\\int \\sec^3 x\\,dx = \\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x + \\tan x| + C' },
        check: { kind: 'antiderivative', integrand: 'sec(x)^3' },
      },
    ],
    final: {
      latex: '\\int \\sec^7 x\\,dx - 2\\int \\sec^5 x\\,dx + \\int \\sec^3 x\\,dx',
      expr: 'indefinite(sec(x)^7, x) - 2*indefinite(sec(x)^5, x) + indefinite(sec(x)^3, x)',
      check: { kind: 'value', expected: 'indefinite(tan(x)^4*sec(x)^3, x)' },
      recap: 'Even tangent with odd secant: $\\tan^2 x = \\sec^2 x - 1$ turns everything into odd powers of secant, each handled by parts like $\\int \\sec^3 x\\,dx$.',
    },
  },
  {
    id: 'ti-s-08',
    topic: 'trig-integrals',
    title: 'Fourth power of cosine on [0, π]',
    difficulty: 1,
    statement: { text: 'Evaluate', latex: '\\int_0^{\\pi} \\cos^4(2t)\\,dt' },
    steps: [
      {
        prompt: 'Which strategy fits this integral?',
        options: [
          { text: 'Save one $\\cos 2t$ and let $u = \\sin 2t$', mistake: 'even-powers-no-identity', why: 'Saving cos 2t leaves cos³(2t), an odd power that needs a square root in terms of sin 2t.' },
          { text: 'Let $u = \\cos 2t$ and integrate $u^4$', mistake: 'u-choice-wrong', why: 'u = cos 2t needs du = −2 sin 2t dt, which is not in the integrand.' },
          { text: 'Use $\\cos^2\\theta = \\frac{1 + \\cos 2\\theta}{2}$ and expand' },
          { text: 'Write $\\cos^4(2t) = (1 - \\sin^2 2t)^2$ and let $u = \\sin 2t$', mistake: 'even-powers-no-identity', why: 'No cos 2t dt is left over to form du = 2cos 2t dt.' },
          { text: 'Use $\\cos^2\\theta = \\frac{1 - \\cos 2\\theta}{2}$ and expand', mistake: 'half-angle-wrong', why: 'cos²θ = (1 + cos 2θ)/2; the minus sign belongs to sin²θ.' },
        ],
        correct: 2,
        explanation: 'Sine power 0 and cosine power 4 are both even, so reduce the powers with the half-angle identity.',
        result: { text: 'Both powers even: half-angle identity for $\\cos^2(2t)$.' },
      },
      {
        prompt: 'Apply the half-angle identity to $\\cos^2(2t)$. Then $\\cos^4(2t)$ equals',
        options: [
          { latex: '\\left(\\frac{1 + \\cos 2t}{2}\\right)^2', expr: '((1 + cos(2*t))/2)^2', mistake: 'half-angle-wrong', why: 'The angle doubles: cos²(2t) uses cos 4t, not cos 2t.' },
          { latex: '\\left(\\frac{1 - \\cos 4t}{2}\\right)^2', expr: '((1 - cos(4*t))/2)^2', mistake: 'half-angle-wrong', why: 'The minus sign belongs to sin²; cos² uses 1 + cos 4t.' },
          { latex: '\\frac{1 + \\cos 4t}{2}', expr: '(1 + cos(4*t))/2', mistake: 'exponent-arithmetic', why: 'That is cos²(2t); the fourth power is its square.' },
          { latex: '\\left(\\frac{1 + \\cos 4t}{2}\\right)^2', expr: '((1 + cos(4*t))/2)^2' },
          { latex: '(1 + \\cos 4t)^2', expr: '(1 + cos(4*t))^2', mistake: 'half-angle-wrong', why: 'The factor 1/2 inside the identity is missing.' },
        ],
        correct: 3,
        explanation: '$\\cos^4(2t) = \\left(\\cos^2 2t\\right)^2$ and $\\cos^2 2t = \\frac{1 + \\cos 4t}{2}$.',
        result: { latex: '\\cos^4(2t) = \\left(\\cos^2 2t\\right)^2 = \\left(\\frac{1 + \\cos 4t}{2}\\right)^2' },
        variable: 't',
        check: { kind: 'identity', lhs: 'cos(2*t)^4' },
      },
      {
        prompt: 'Expand and reduce $\\cos^2 4t$ as well. The integrand becomes',
        options: [
          { latex: '\\frac{1}{4} + \\frac{1}{4}\\cos^2 4t', expr: '1/4 + cos(4*t)^2/4', mistake: 'algebra-error', why: '(1 + a)² = 1 + 2a + a²; the middle term 2cos 4t is missing.' },
          { latex: '\\frac{3}{8} + \\frac{1}{2}\\cos 4t - \\frac{1}{8}\\cos 8t', expr: '3/8 + cos(4*t)/2 - cos(8*t)/8', mistake: 'half-angle-wrong', why: 'cos²4t = (1 + cos 8t)/2; the sine identity was used.' },
          { latex: '\\frac{1}{4} + \\frac{1}{2}\\cos 4t - \\frac{1}{8}\\cos 8t', expr: '1/4 + cos(4*t)/2 - cos(8*t)/8', mistake: 'half-angle-wrong', why: 'Two slips: cos²4t was reduced with the sine identity (1 − cos 8t)/2, and its constant 1/8 was dropped.' },
          { latex: '\\frac{1}{4} + \\frac{1}{2}\\cos 4t + \\frac{1}{8}\\cos 8t', expr: '1/4 + cos(4*t)/2 + cos(8*t)/8', mistake: 'algebra-error', why: '¼cos²4t = ⅛ + ⅛cos 8t; the constant ⅛ was dropped.' },
          { latex: '\\frac{3}{8} + \\frac{1}{2}\\cos 4t + \\frac{1}{8}\\cos 8t', expr: '3/8 + cos(4*t)/2 + cos(8*t)/8' },
        ],
        correct: 4,
        explanation: '$\\frac{1}{4}\\left(1 + 2\\cos 4t + \\frac{1 + \\cos 8t}{2}\\right) = \\frac{3}{8} + \\frac{1}{2}\\cos 4t + \\frac{1}{8}\\cos 8t$.',
        result: { latex: '= \\frac{1}{4}\\left(1 + 2\\cos 4t + \\frac{1 + \\cos 8t}{2}\\right) = \\frac{3}{8} + \\frac{1}{2}\\cos 4t + \\frac{1}{8}\\cos 8t' },
        variable: 't',
        check: { kind: 'identity', lhs: 'cos(2*t)^4' },
      },
      {
        prompt: 'Integrate from $0$ to $\\pi$.',
        options: [
          { latex: '-\\frac{3\\pi}{16}', expr: '-3*pi/16', mistake: 'ftc-order-swapped', why: 'Two slips: F(0) − F(π) was computed, and the constant 3/8 was divided by the inner 2.' },
          { latex: '\\frac{3\\pi}{16}', expr: '3*pi/16', mistake: 'coefficient-mishandled', why: 'The constant term integrates to 3t/8; a 1/k factor only comes from integrating cos(kt).' },
          { latex: '\\frac{3}{8}', expr: '3/8', mistake: 'constant-not-integrated', why: 'The average value 3/8 was not multiplied by the interval length π: ∫₀^π (3/8)dt = 3π/8.' },
          { latex: '\\frac{3\\pi}{4}', expr: '3*pi/4', mistake: 'coefficient-mishandled', why: 'The constant term was multiplied by the inner 2; only the cosine terms pick up factors, and they vanish here.' },
          { latex: '\\frac{3\\pi}{8}', expr: '3*pi/8' },
        ],
        correct: 4,
        explanation: '$\\sin 4\\pi = \\sin 8\\pi = \\sin 0 = 0$, so only $\\frac{3}{8}t$ contributes: $\\frac{3\\pi}{8}$.',
        result: { latex: '\\left[\\frac{3t}{8} + \\frac{\\sin 4t}{8} + \\frac{\\sin 8t}{64}\\right]_0^{\\pi} = \\frac{3\\pi}{8}' },
        variable: 't',
        check: { kind: 'value', expected: 'integral(cos(2*t)^4, t, 0, pi)' },
      },
    ],
    final: {
      latex: '\\frac{3\\pi}{8}',
      expr: '3*pi/8',
      check: { kind: 'definite-integral', integrand: 'cos(2*t)^4', lower: '0', upper: 'pi' },
      recap: 'Even powers only: apply the half-angle identity twice ($\\cos^2 2t$, then $\\cos^2 4t$); over $[0, \\pi]$ every cosine term integrates to zero.',
    },
    variable: 't',
  },
  {
    id: 'ti-s-09',
    topic: 'trig-integrals',
    title: 'Odd power of sine with angle 2t',
    difficulty: 2,
    statement: { text: 'Evaluate', latex: '\\int \\sin^5(2t)\\cos^2(2t)\\,dt' },
    steps: [
      {
        prompt: 'Which strategy fits this integral?',
        options: [
          { text: 'Save one $\\cos 2t$ and let $u = \\sin 2t$', mistake: 'trig-wrong-factor-saved', why: 'The cosine power is even: after saving cos 2t, a single cos 2t remains and needs a square root.' },
          { text: 'Save one $\\sin 2t$ and let $u = \\cos 2t$' },
          { text: 'Save one $\\sin 2t$ and let $u = \\sin 2t$', mistake: 'trig-wrong-factor-saved', why: 'u = sin 2t needs du = 2cos 2t dt; the saved sin 2t dt does not match.' },
          { text: 'Use the half-angle identities', mistake: 'technique-wrong', why: 'Half-angle identities are for both powers even; the odd sine power gives a direct substitution.' },
          { text: 'Save one $\\sin 2t$ and let $u = \\cos t$', mistake: 'angle-mismatch', why: 'u must use the same angle: d(cos t) = −sin t dt does not match sin 2t dt.' },
        ],
        correct: 1,
        explanation: 'The sine power 5 is odd: save $\\sin 2t\\,dt$ and write $\\sin^4 2t$ in terms of $\\cos 2t$.',
        result: { text: 'Odd power of sine: save $\\sin 2t\\,dt$, use $u = \\cos 2t$.' },
      },
      {
        prompt: 'Rewrite the integrand around the saved factor.',
        options: [
          { latex: '(1 - \\cos^2 2t)\\cos^2 2t\\,\\sin 2t', expr: '(1 - cos(2*t)^2)*cos(2*t)^2*sin(2*t)', mistake: 'exponent-arithmetic', why: 'After saving sin 2t, sin⁴2t = (1 − cos²2t)²; the square was dropped.' },
          { latex: '(1 + \\cos^2 2t)^2\\cos^2 2t\\,\\sin 2t', expr: '(1 + cos(2*t)^2)^2*cos(2*t)^2*sin(2*t)', mistake: 'pythagorean-wrong', why: 'sin²2t = 1 − cos²2t, not 1 + cos²2t.' },
          { latex: '(1 - \\cos^2 2t)^2\\cos^2 2t\\,\\sin 2t', expr: '(1 - cos(2*t)^2)^2*cos(2*t)^2*sin(2*t)' },
          { latex: '(1 - \\cos^4 2t)\\cos^2 2t\\,\\sin 2t', expr: '(1 - cos(2*t)^4)*cos(2*t)^2*sin(2*t)', mistake: 'algebra-error', why: '(1 − cos²2t)² was squared term by term; it expands to 1 − 2cos²2t + cos⁴2t.' },
          { latex: '(1 - \\cos^2 2t)^2\\cos^2 2t\\,\\cos 2t', expr: '(1 - cos(2*t)^2)^2*cos(2*t)^2*cos(2*t)', mistake: 'trig-wrong-factor-saved', why: 'The saved factor is sin 2t (sin⁵ = sin⁴·sin), not cos 2t.' },
        ],
        correct: 2,
        explanation: '$\\sin^5 2t = (\\sin^2 2t)^2\\sin 2t = (1 - \\cos^2 2t)^2\\sin 2t$.',
        result: { latex: '\\sin^5 2t\\cos^2 2t = (1 - \\cos^2 2t)^2\\cos^2 2t\\,\\sin 2t' },
        variable: 't',
        check: { kind: 'identity', lhs: 'sin(2*t)^5*cos(2*t)^2' },
      },
      {
        prompt: 'With $u = \\cos 2t$, what is $du$?',
        options: [
          { latex: 'du = -\\sin 2t\\,dt', expr: '-sin(2*t)*dt', mistake: 'chain-rule-missing', why: 'The chain rule brings down the inner 2: du = −2 sin 2t dt.' },
          { latex: 'du = 2\\sin 2t\\,dt', expr: '2*sin(2*t)*dt', mistake: 'u-cos-sign-missing', why: 'd/dt cos 2t = −2 sin 2t; the minus sign was dropped.' },
          { latex: 'du = -\\cos 2t\\,dt', expr: '-cos(2*t)*dt', mistake: 'du-derivative-wrong', why: 'Two slips: cos 2t differentiates to −2 sin 2t (a sine, not a cosine), and the chain-rule factor 2 is missing.' },
          { latex: 'du = -\\frac{1}{2}\\sin 2t\\,dt', expr: '-sin(2*t)*dt/2', mistake: 'du-constant-wrong', why: 'The chain rule multiplies by the inner 2; it does not divide.' },
          { latex: 'du = -2\\sin 2t\\,dt', expr: '-2*sin(2*t)*dt' },
        ],
        correct: 4,
        explanation: '$\\frac{d}{dt}\\cos 2t = -2\\sin 2t$, so $\\sin 2t\\,dt = -\\frac{1}{2}\\,du$.',
        result: { latex: 'u = \\cos 2t,\\quad du = -2\\sin 2t\\,dt \\Rightarrow \\sin 2t\\,dt = -\\frac{1}{2}\\,du' },
        variable: 't',
        check: { kind: 'value', expected: '-2*sin(2*t)*dt' },
      },
      {
        prompt: 'Write the integral in terms of $u$.',
        options: [
          { latex: '-2\\int (1 - u^2)^2u^2\\,du', expr: '-2*indefinite((1 - u^2)^2*u^2, u)', mistake: 'inner-constant-factor-missing', why: 'sin 2t dt = −½du, not −2du.' },
          { latex: '-\\frac{1}{2}\\int (1 - u^2)^2u^2\\,du', expr: '-indefinite((1 - u^2)^2*u^2, u)/2' },
          { latex: '-\\int (1 - u^2)^2u^2\\,du', expr: '-indefinite((1 - u^2)^2*u^2, u)', mistake: 'inner-constant-factor-missing', why: 'The factor 1/2 from du = −2 sin 2t dt was dropped.' },
          { latex: '\\frac{1}{2}\\int (1 - u^2)^2u^2\\,du', expr: 'indefinite((1 - u^2)^2*u^2, u)/2', mistake: 'u-cos-sign-missing', why: 'sin 2t dt = −½du; the minus sign was dropped.' },
          { latex: '-\\frac{1}{2}\\int (1 - u^2)^2u^2\\sin 2t\\,du', expr: '-indefinite((1 - u^2)^2*u^2*sin(2*t), u)/2', mistake: 'leftover-x-in-u-integral', why: 'The saved sin 2t dt became −½du; sin 2t must not stay in the u-integral.' },
        ],
        correct: 1,
        explanation: '$(1 - u^2)^2u^2\\cdot\\left(-\\frac{1}{2}\\,du\\right)$.',
        result: { latex: '= -\\frac{1}{2}\\int (1 - u^2)^2u^2\\,du = -\\frac{1}{2}\\int (u^2 - 2u^4 + u^6)\\,du' },
        variable: 'u',
        domain: { u: [0.3, 0.95], t: [0.25, 0.7] },
        check: { kind: 'identity', lhs: '-indefinite((1 - u^2)^2*u^2, u)/2' },
      },
      {
        prompt: 'Integrate and substitute back.',
        options: [
          { latex: '\\frac{1}{6}\\cos^3 2t - \\frac{1}{5}\\cos^5 2t + \\frac{1}{14}\\cos^7 2t + C', expr: 'cos(2*t)^3/6 - cos(2*t)^5/5 + cos(2*t)^7/14', mistake: 'sign-error', why: 'The −½ in front multiplies every term, so the u³ term is negative.' },
          { latex: '-\\frac{1}{3}\\cos^3 t + \\frac{2}{5}\\cos^5 t - \\frac{1}{7}\\cos^7 t + C', expr: '-cos(t)^3/3 + 2*cos(t)^5/5 - cos(t)^7/7', mistake: 'back-substitution-wrong', why: 'Two slips: the angle 2t became t when substituting back, and the 1/2 in front of the integral was dropped.' },
          { latex: '-\\frac{1}{3}\\cos^3 2t + \\frac{2}{5}\\cos^5 2t - \\frac{1}{7}\\cos^7 2t + C', expr: '-cos(2*t)^3/3 + 2*cos(2*t)^5/5 - cos(2*t)^7/7', mistake: 'coefficient-mishandled', why: 'The 1/2 in front of the integral was dropped while integrating.' },
          { latex: '-\\frac{1}{6}\\cos^3 2t + \\frac{1}{14}\\cos^7 2t + C', expr: '-cos(2*t)^3/6 + cos(2*t)^7/14', mistake: 'algebra-error', why: '(1 − u²)² was squared term by term as 1 − u⁴, giving −½(u³/3 − u⁷/7).' },
          { latex: '-\\frac{1}{6}\\cos^3 2t + \\frac{1}{5}\\cos^5 2t - \\frac{1}{14}\\cos^7 2t + C', expr: '-cos(2*t)^3/6 + cos(2*t)^5/5 - cos(2*t)^7/14' },
        ],
        correct: 4,
        explanation: '$-\\frac{1}{2}\\left(\\frac{u^3}{3} - \\frac{2u^5}{5} + \\frac{u^7}{7}\\right) + C$ with $u = \\cos 2t$.',
        result: { latex: '= -\\frac{1}{2}\\left(\\frac{u^3}{3} - \\frac{2u^5}{5} + \\frac{u^7}{7}\\right) + C = -\\frac{1}{6}\\cos^3 2t + \\frac{1}{5}\\cos^5 2t - \\frac{1}{14}\\cos^7 2t + C' },
        variable: 't',
        check: { kind: 'antiderivative', integrand: 'sin(2*t)^5*cos(2*t)^2' },
      },
    ],
    final: {
      latex: '-\\frac{1}{6}\\cos^3 2t + \\frac{1}{5}\\cos^5 2t - \\frac{1}{14}\\cos^7 2t + C',
      expr: '-cos(2*t)^3/6 + cos(2*t)^5/5 - cos(2*t)^7/14',
      check: { kind: 'antiderivative', integrand: 'sin(2*t)^5*cos(2*t)^2' },
      recap: 'Odd power of sine with inner angle $2t$: save $\\sin 2t$, and remember $du = -2\\sin 2t\\,dt$ brings a factor $-\\frac{1}{2}$.',
    },
    variable: 't',
  },
  {
    id: 'ti-s-10',
    topic: 'trig-integrals',
    title: 'A product of cosines',
    difficulty: 2,
    statement: { text: 'Evaluate', latex: '\\int_0^{\\pi/2} \\cos 5t\\cos 10t\\,dt' },
    steps: [
      {
        prompt: 'Which identity rewrites $\\cos 10t$ in terms of $\\cos 5t$ only?',
        options: [
          { latex: '\\cos 10t = 1 - 2\\cos^2 5t', expr: '1 - 2*cos(5*t)^2', mistake: 'double-angle-wrong', why: 'The sign is reversed: cos 2θ = 2cos²θ − 1 (check θ = 0).' },
          { latex: '\\cos 10t = 2\\cos^2 5t + 1', expr: '2*cos(5*t)^2 + 1', mistake: 'double-angle-wrong', why: 'cos 2θ = 2cos²θ − 1; the constant is subtracted.' },
          { latex: '\\cos 10t = 2\\sin 5t\\cos 5t', expr: '2*sin(5*t)*cos(5*t)', mistake: 'double-angle-wrong', why: '2 sin θ cos θ is sin 2θ, i.e. sin 10t.' },
          { latex: '\\cos 10t = 2\\cos^2 5t - 1', expr: '2*cos(5*t)^2 - 1' },
          { latex: '\\cos 10t = 1 - 2\\cos 5t', expr: '1 - 2*cos(5*t)', mistake: 'double-angle-wrong', why: 'Two slips: the sign is reversed (cos 2θ = 2cos²θ − 1), and the square on cos 5t was dropped.' },
        ],
        correct: 3,
        explanation: '$\\cos 2\\theta = 2\\cos^2\\theta - 1$ with $\\theta = 5t$; the integrand becomes $2\\cos^3 5t - \\cos 5t$.',
        result: { latex: '\\cos 5t\\cos 10t = \\cos 5t\\,(2\\cos^2 5t - 1) = 2\\cos^3 5t - \\cos 5t' },
        check: { kind: 'identity', lhs: 'cos(10*t)' },
      },
      {
        prompt: 'How do you integrate $2\\cos^3 5t$?',
        options: [
          { text: 'Save one $\\sin 5t$ and let $u = \\cos 5t$, with $du = -5\\sin 5t\\,dt$', mistake: 'trig-wrong-factor-saved', why: 'There is no sine factor in the integrand to save.' },
          { text: 'Let $u = \\cos 5t$ and integrate $u^3$', mistake: 'u-choice-wrong', why: 'u = cos 5t needs du = −5 sin 5t dt, which is not in the integrand.' },
          { text: 'Use $\\cos^2 5t = \\frac{1 + \\cos 10t}{2}$', mistake: 'technique-wrong', why: 'That recreates the product cos 5t cos 10t we started from; the odd power allows a substitution.' },
          { text: 'Save one $\\cos 5t$ and let $u = \\sin 5t$, with $du = \\cos 5t\\,dt$', mistake: 'du-constant-wrong', why: 'd/dt sin 5t = 5cos 5t, so du = 5cos 5t dt.' },
          { text: 'Save one $\\cos 5t$ and let $u = \\sin 5t$, with $du = 5\\cos 5t\\,dt$' },
        ],
        correct: 4,
        explanation: 'The cosine power 3 is odd: $\\cos^2 5t = 1 - u^2$ and $\\cos 5t\\,dt = \\frac{1}{5}\\,du$.',
        result: { text: 'Odd power of cosine: $u = \\sin 5t$, $du = 5\\cos 5t\\,dt$.' },
      },
      {
        prompt: 'Write $\\int_0^{\\pi/2} 2\\cos^3 5t\\,dt$ as a $u$-integral with new limits.',
        options: [
          { latex: '2\\int_0^1 (1 - u^2)\\,du', expr: '2*integral(1 - u^2, u, 0, 1)', mistake: 'inner-constant-factor-missing', why: 'du = 5cos 5t dt, so cos 5t dt = du/5; the 1/5 is missing.' },
          { latex: '\\frac{2}{5}\\int_0^{\\pi/2} (1 - u^2)\\,du', expr: '2/5*integral(1 - u^2, u, 0, pi/2)', mistake: 'bounds-not-converted', why: 'The t-limits were kept; u = sin 5t runs from sin 0 = 0 to sin(5π/2) = 1.' },
          { latex: '\\frac{2}{5}\\int_0^{-1} (1 - u^2)\\,du', expr: '2/5*integral(1 - u^2, u, 0, -1)', mistake: 'arithmetic-error', why: 'sin(5π/2) = sin(π/2 + 2π) = 1, not −1.' },
          { latex: '\\frac{2}{5}\\int_0^1 (1 - u^2)\\,du', expr: '2/5*integral(1 - u^2, u, 0, 1)' },
          { latex: '\\frac{2}{5}\\int_0^1 (1 + u^2)\\,du', expr: '2/5*integral(1 + u^2, u, 0, 1)', mistake: 'pythagorean-wrong', why: 'cos²5t = 1 − sin²5t, not 1 + sin²5t.' },
        ],
        correct: 3,
        explanation: '$2\\cos^2 5t\\cos 5t\\,dt = \\frac{2}{5}(1 - u^2)\\,du$ with $u$ from $0$ to $\\sin\\frac{5\\pi}{2} = 1$; the value is $\\frac{2}{5}\\cdot\\frac{2}{3} = \\frac{4}{15}$.',
        result: { latex: '\\int_0^{\\pi/2} 2\\cos^3 5t\\,dt = \\frac{2}{5}\\int_0^1 (1 - u^2)\\,du = \\frac{2}{5}\\cdot\\frac{2}{3} = \\frac{4}{15}' },
        check: { kind: 'value', expected: 'integral(2*cos(5*t)^3, t, 0, pi/2)' },
      },
      {
        prompt: 'Subtract $\\int_0^{\\pi/2} \\cos 5t\\,dt$ from $\\frac{4}{15}$. The result is',
        options: [
          { latex: '\\frac{7}{15}', expr: '7/15', mistake: 'sign-error', why: 'The ∫cos 5t dt piece (worth 1/5) is subtracted, not added.' },
          { latex: '-\\frac{11}{15}', expr: '-11/15', mistake: 'inner-constant-factor-missing', why: '∫cos 5t dt = ⅕ sin 5t; without the 1/5 the piece is worth 1.' },
          { latex: '\\frac{4}{15}', expr: '4/15', mistake: 'algebra-error', why: 'The −cos 5t term from 2cos³5t − cos 5t was dropped.' },
          { latex: '\\frac{1}{15}', expr: '1/15' },
          { latex: '-\\frac{1}{15}', expr: '-1/15', mistake: 'ftc-order-swapped', why: 'Evaluated F(0) − F(π/2) instead of F(π/2) − F(0).' },
        ],
        correct: 3,
        explanation: '$\\int_0^{\\pi/2} \\cos 5t\\,dt = \\frac{\\sin(5\\pi/2)}{5} = \\frac{1}{5}$, and $\\frac{4}{15} - \\frac{3}{15} = \\frac{1}{15}$.',
        result: { latex: '\\frac{4}{15} - \\left[\\frac{\\sin 5t}{5}\\right]_0^{\\pi/2} = \\frac{4}{15} - \\frac{1}{5} = \\frac{1}{15}' },
        check: { kind: 'value', expected: 'integral(cos(5*t)*cos(10*t), t, 0, pi/2)' },
      },
    ],
    final: {
      latex: '\\frac{1}{15}',
      expr: '1/15',
      check: { kind: 'definite-integral', integrand: 'cos(5*t)*cos(10*t)', lower: '0', upper: 'pi/2' },
      recap: 'Rewrite $\\cos 10t = 2\\cos^2 5t - 1$ to get an odd power of $\\cos 5t$, then substitute $u = \\sin 5t$ (with $du = 5\\cos 5t\\,dt$) and convert the limits.',
    },
    variable: 't',
  },
];
