import type { StepProblem } from '../types';

/**
 * Step-Through problems for topic "trig-sub" (Lecture 7, §3.3: Examples 7.2–7.5 and practice
 * problems 1d–1j). Authored by content-author; verified by math-verifier.
 * Pattern: choose the substitution → dx → simplify the radical (sign from the θ-interval) → rewrite
 * the integral in θ (and the limits) → integrate → back-substitute with the triangle / evaluate.
 */
export const steps: StepProblem[] = [
  {
    id: 'ts-s-01',
    topic: 'trig-sub',
    title: 'Tangent substitution (Example 7.2)',
    difficulty: 1,
    statement: { text: 'Evaluate (Example 7.2).', latex: '\\int \\frac{1}{x^2\\sqrt{x^2+4}}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution matches the form $x^2 + 4$?',
        options: [
          { latex: 'x = 2\\tan\\theta' },
          { latex: 'x = 2\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $4 - x^2$; $4\\sin^2\\theta + 4$ does not collapse to one square.' },
          { latex: 'x = 2\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 4$; $4\\sec^2\\theta + 4$ is not a single square.' },
          { latex: 'x = 4\\tan\\theta', mistake: 'trig-sub-coefficient', why: '$b^2 = 4$ means $b = 2$; $16\\tan^2\\theta + 4$ does not factor as $4(\\tan^2\\theta + 1)$.' },
          { latex: 'u = x^2 + 4', mistake: 'u-choice-wrong', why: '$du = 2x\\,dx$, but the integrand has no factor x (it has $\\frac{1}{x^2}$).' },
        ],
        correct: 0,
        explanation: 'A sum $x^2 + 2^2$ calls for $x = 2\\tan\\theta$, since $4\\tan^2\\theta + 4 = 4\\sec^2\\theta$.',
        result: { latex: 'x = 2\\tan\\theta,\\quad \\theta = \\arctan\\frac{x}{2} \\in \\left(-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right)' },
      },
      {
        prompt: 'Compute $dx$.',
        options: [
          { latex: 'dx = 2\\sec^2\\theta\\,d\\theta', expr: '2*sec(theta)^2*dtheta' },
          { latex: 'dx = 2\\sec\\theta\\tan\\theta\\,d\\theta', expr: '2*sec(theta)*tan(theta)*dtheta', mistake: 'dx-derivative-wrong', why: 'That is the derivative of $2\\sec\\theta$; the derivative of $\\tan\\theta$ is $\\sec^2\\theta$.' },
          { latex: 'dx = \\sec^2\\theta\\,d\\theta', expr: 'sec(theta)^2*dtheta', mistake: 'dx-coefficient', why: 'The factor 2 from $x = 2\\tan\\theta$ was dropped.' },
          { latex: 'dx = \\frac{1}{2}\\sec^2\\theta\\,d\\theta', expr: 'sec(theta)^2*dtheta/2', mistake: 'dx-coefficient', why: 'Divided by 2 instead of multiplying; that would be $dx$ for $2x = \\tan\\theta$.' },
          { latex: 'dx = -2\\csc^2\\theta\\,d\\theta', expr: '-2*csc(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: 'That is the derivative of $2\\cot\\theta$, not of $2\\tan\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{d\\theta}(2\\tan\\theta) = 2\\sec^2\\theta$.',
        result: { latex: 'dx = 2\\sec^2\\theta\\,d\\theta' },
        check: { kind: 'value', expected: '2*sec(theta)^2*dtheta' },
        variable: 'theta',
        domain: { theta: [0.2, 1.2], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Simplify $\\sqrt{x^2+4}$ (recall $-\\frac{\\pi}{2} < \\theta < \\frac{\\pi}{2}$).',
        options: [
          { latex: '\\sqrt{x^2+4} = 2\\sec\\theta', expr: '2*sec(theta)' },
          { latex: '\\sqrt{x^2+4} = 4\\sec\\theta', expr: '4*sec(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{4\\sec^2\\theta} = 2\\sec\\theta$; the 4 must be rooted too.' },
          { latex: '\\sqrt{x^2+4} = 2\\tan\\theta + 2', expr: '2*tan(theta) + 2', mistake: 'sqrt-of-sum-split', why: 'The root was split over the sum: $\\sqrt{4\\tan^2\\theta + 4} \\ne 2\\tan\\theta + 2$.' },
          { latex: '\\sqrt{x^2+4} = -2\\sec\\theta', expr: '-2*sec(theta)', mistake: 'theta-interval-sign', why: '$\\sec\\theta > 0$ on $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$, so the root is $+2\\sec\\theta$.' },
          { latex: '\\sqrt{x^2+4} = 2\\csc\\theta', expr: '2*csc(theta)', mistake: 'pythagorean-wrong', why: 'Used $1 + \\cot^2\\theta = \\csc^2\\theta$; the tangent identity is $1 + \\tan^2\\theta = \\sec^2\\theta$.' },
        ],
        correct: 0,
        explanation: '$4\\tan^2\\theta + 4 = 4\\sec^2\\theta$ and $\\sec\\theta > 0$ on $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$.',
        result: { latex: '\\sqrt{4\\tan^2\\theta + 4} = \\sqrt{4\\sec^2\\theta} = 2|\\sec\\theta| = 2\\sec\\theta' },
        check: { kind: 'identity', lhs: 'sqrt((2*tan(theta))^2 + 4)' },
        variable: 'theta',
        domain: { theta: [-1.2, 1.2] },
      },
      {
        prompt: 'Rewrite the integral entirely in θ.',
        options: [
          { latex: '\\int \\frac{\\sec\\theta}{4\\tan^2\\theta}\\,d\\theta', expr: 'indefinite(sec(theta)/(4*tan(theta)^2), theta)' },
          { latex: '\\int \\frac{1}{8\\tan^2\\theta\\sec\\theta}\\,d\\theta', expr: 'indefinite(1/(8*tan(theta)^2*sec(theta)), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $2\\sec^2\\theta$.' },
          { latex: '\\int \\frac{\\sec\\theta}{x^2}\\,d\\theta', expr: 'indefinite(sec(theta)/x^2, theta)', mistake: 'mixed-variables', why: 'The $x^2$ was never rewritten as $4\\tan^2\\theta$, so x and θ are mixed.' },
          { latex: '\\int \\frac{1}{4\\tan\\theta}\\,d\\theta', expr: 'indefinite(1/(4*tan(theta)), theta)', mistake: 'dx-derivative-wrong', why: 'Used $dx = 2\\sec\\theta\\tan\\theta\\,d\\theta$ instead of $2\\sec^2\\theta\\,d\\theta$.' },
          { latex: '\\int \\frac{\\sec\\theta}{2\\tan^2\\theta}\\,d\\theta', expr: 'indefinite(sec(theta)/(2*tan(theta)^2), theta)', mistake: 'coefficient-mishandled', why: 'Squared $2\\tan\\theta$ as $2\\tan^2\\theta$; it is $4\\tan^2\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{2\\sec^2\\theta}{4\\tan^2\\theta\\cdot 2\\sec\\theta} = \\frac{\\sec\\theta}{4\\tan^2\\theta}$, with nothing left in x.',
        result: { latex: '\\int \\frac{2\\sec^2\\theta\\,d\\theta}{4\\tan^2\\theta\\cdot 2\\sec\\theta} = \\frac{1}{4}\\int \\frac{\\sec\\theta}{\\tan^2\\theta}\\,d\\theta = \\frac{1}{4}\\int \\frac{\\cos\\theta}{\\sin^2\\theta}\\,d\\theta' },
        check: { kind: 'identity', lhs: 'indefinite(2*sec(theta)^2/((2*tan(theta))^2*sqrt((2*tan(theta))^2 + 4)), theta)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.2], x: [0.5, 3] },
      },
      {
        prompt: 'Integrate $\\frac{1}{4}\\int \\frac{\\cos\\theta}{\\sin^2\\theta}\\,d\\theta$ (let $u = \\sin\\theta$).',
        options: [
          { latex: '-\\frac{1}{4\\sin\\theta} + C', expr: '-1/(4*sin(theta))' },
          { latex: '\\frac{1}{4\\sin\\theta} + C', expr: '1/(4*sin(theta))', mistake: 'sign-error', why: '$\\int u^{-2}\\,du = -u^{-1}$; the minus sign was lost.' },
          { latex: '-\\frac{1}{12\\sin^3\\theta} + C', expr: '-1/(12*sin(theta)^3)', mistake: 'power-rule-int-exponent', why: 'The exponent was lowered to $-3$; integrating $u^{-2}$ raises it to $-1$.' },
          { latex: '\\frac{1}{4}\\ln|\\sin\\theta| + C', expr: 'log(abs(sin(theta)))/4', mistake: 'ln-misapplied', why: 'The logarithm is for $u^{-1}$; here the power is $u^{-2}$, so use the power rule.' },
          { latex: '-\\frac{\\cos\\theta}{4\\sin\\theta} + C', expr: '-cos(theta)/(4*sin(theta))', mistake: 'leftover-x-in-u-integral', why: 'The factor $\\cos\\theta\\,d\\theta$ became $du$; it must not reappear in the answer.' },
        ],
        correct: 0,
        explanation: 'With $u = \\sin\\theta$, $du = \\cos\\theta\\,d\\theta$: $\\frac{1}{4}\\int u^{-2}\\,du = -\\frac{1}{4u} + C$.',
        result: { latex: 'u = \\sin\\theta:\\ \\frac{1}{4}\\int u^{-2}\\,du = -\\frac{1}{4u} + C = -\\frac{1}{4\\sin\\theta} + C' },
        check: { kind: 'antiderivative', integrand: 'cos(theta)/(4*sin(theta)^2)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3] },
      },
      {
        prompt: 'Use the triangle for $\\tan\\theta = \\frac{x}{2}$ to write the answer in terms of x.',
        options: [
          { latex: '-\\frac{\\sqrt{x^2+4}}{4x} + C', expr: '-sqrt(x^2+4)/(4*x)' },
          { latex: '-\\frac{x}{4\\sqrt{x^2+4}} + C', expr: '-x/(4*sqrt(x^2+4))', mistake: 'triangle-sides-wrong', why: 'Replaced $\\frac{1}{\\sin\\theta}$ by $\\sin\\theta = \\frac{x}{\\sqrt{x^2+4}}$ instead of its reciprocal.' },
          { latex: '-\\frac{\\sqrt{x^2+4}}{8} + C', expr: '-sqrt(x^2+4)/8', mistake: 'triangle-sides-wrong', why: 'Used hypotenuse over adjacent ($\\sec\\theta$) in place of hypotenuse over opposite ($\\csc\\theta$).' },
          { latex: '-\\frac{1}{4\\sin x} + C', expr: '-1/(4*sin(x))', mistake: 'back-substitution-wrong', why: 'Replaced θ by x; θ is $\\arctan\\frac{x}{2}$, and $\\sin\\theta$ comes from the triangle.' },
          { latex: '-\\frac{1}{4\\sin\\theta} + C', expr: '-1/(4*sin(theta))', mistake: 'not-back-substituted', why: 'The answer must be written in the original variable x.' },
        ],
        correct: 0,
        explanation: 'Opposite $x$, adjacent 2, hypotenuse $\\sqrt{x^2+4}$, so $\\frac{1}{\\sin\\theta} = \\frac{\\sqrt{x^2+4}}{x}$.',
        result: { latex: '\\sin\\theta = \\frac{x}{\\sqrt{x^2+4}} \;\\Rightarrow\; -\\frac{1}{4\\sin\\theta} + C = -\\frac{\\sqrt{x^2+4}}{4x} + C' },
        check: { kind: 'antiderivative', integrand: '1/(x^2*sqrt(x^2+4))' },
        variable: 'x',
        domain: { x: [0.5, 3], theta: [0.3, 1.2] },
      },
    ],
    final: {
      latex: '-\\frac{\\sqrt{x^2+4}}{4x} + C',
      expr: '-sqrt(x^2+4)/(4*x)',
      check: { kind: 'antiderivative', integrand: '1/(x^2*sqrt(x^2+4))' },
      recap: 'A sum $x^2 + 4$ means $x = 2\\tan\\theta$; after integrating in θ, the triangle (opposite $x$, adjacent 2, hypotenuse $\\sqrt{x^2+4}$) turns $\\frac{1}{\\sin\\theta}$ into $\\frac{\\sqrt{x^2+4}}{x}$.',
    },
    domain: { x: [0.5, 3] },
    tags: ['tangent'],
  },
  {
    id: 'ts-s-02',
    topic: 'trig-sub',
    title: 'Sine substitution with limits (Example 7.3)',
    difficulty: 2,
    statement: { text: 'Evaluate (Example 7.3).', latex: '\\int_{-1/2}^{\\sqrt{2}/2} \\frac{x^3}{\\sqrt{1-x^2}}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution, with its θ-interval, fits $\\sqrt{1 - x^2}$?',
        options: [
          { text: '$x = \\sin\\theta$, with $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$' },
          { text: '$x = \\sin\\theta$, with $0 \\le \\theta \\le \\pi$', mistake: 'theta-interval-sign', why: '$[0, \\pi]$ is the range of arccos; arcsine returns angles in $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, where $\\cos\\theta \\ge 0$.' },
          { text: '$x = \\tan\\theta$, with $-\\frac{\\pi}{2} < \\theta < \\frac{\\pi}{2}$', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $1 + x^2$; $1 - \\tan^2\\theta$ is not a Pythagorean square.' },
          { text: '$x = \\sec\\theta$, with $0 \\le \\theta < \\frac{\\pi}{2}$', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 1$; here $1 - \\sec^2\\theta = -\\tan^2\\theta$ is negative under the root.' },
          { text: '$x = 2\\sin\\theta$, with $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$', mistake: 'trig-sub-coefficient', why: '$b^2 = 1$ means $b = 1$; $1 - 4\\sin^2\\theta$ does not collapse.' },
        ],
        correct: 0,
        explanation: '$1 - x^2$ is a difference $b^2 - x^2$ with $b = 1$; arcsine gives θ in $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.',
        result: { text: '$x = \\sin\\theta$, $\\theta = \\arcsin x \\in [-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, so $\\cos\\theta \\ge 0$.' },
      },
      {
        prompt: 'Find $\\sqrt{1-x^2}$ and $dx$ in terms of θ.',
        options: [
          { latex: '\\sqrt{1-x^2} = \\cos\\theta,\\quad dx = \\cos\\theta\\,d\\theta', expr: '[cos(theta), cos(theta)*dtheta]' },
          { latex: '\\sqrt{1-x^2} = -\\cos\\theta,\\quad dx = \\cos\\theta\\,d\\theta', expr: '[-cos(theta), cos(theta)*dtheta]', mistake: 'theta-interval-sign', why: 'Cosine is nonnegative on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, so the root is $+\\cos\\theta$.' },
          { latex: '\\sqrt{1-x^2} = \\cos\\theta,\\quad dx = -\\cos\\theta\\,d\\theta', expr: '[cos(theta), -cos(theta)*dtheta]', mistake: 'dx-derivative-wrong', why: 'The derivative of $\\sin\\theta$ is $+\\cos\\theta$.' },
          { latex: '\\sqrt{1-x^2} = 1 - \\sin\\theta,\\quad dx = \\cos\\theta\\,d\\theta', expr: '[1 - sin(theta), cos(theta)*dtheta]', mistake: 'sqrt-of-sum-split', why: 'The root was split: $\\sqrt{1 - \\sin^2\\theta} \\ne 1 - \\sin\\theta$.' },
          { latex: '\\sqrt{1-x^2} = \\cos\\theta,\\quad dx = d\\theta', expr: '[cos(theta), dtheta]', mistake: 'dx-not-replaced', why: '$dx$ was just renamed $d\\theta$; it is $\\cos\\theta\\,d\\theta$.' },
        ],
        correct: 0,
        explanation: '$1 - \\sin^2\\theta = \\cos^2\\theta$ with $\\cos\\theta \\ge 0$, and $\\frac{d}{d\\theta}\\sin\\theta = \\cos\\theta$.',
        result: { latex: '\\sqrt{1-\\sin^2\\theta} = |\\cos\\theta| = \\cos\\theta,\\quad dx = \\cos\\theta\\,d\\theta' },
        check: { kind: 'value', expected: '[sqrt(1 - sin(theta)^2), cos(theta)*dtheta]' },
        variable: 'theta',
        domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Rewrite the integral in θ, converting the limits too.',
        options: [
          { latex: '\\int_{-\\pi/6}^{\\pi/4} \\sin^3\\theta\\,d\\theta', expr: 'integral(sin(theta)^3, theta, -pi/6, pi/4)' },
          { latex: '\\int_{-1/2}^{\\sqrt{2}/2} \\sin^3\\theta\\,d\\theta', expr: 'integral(sin(theta)^3, theta, -1/2, sqrt(2)/2)', mistake: 'bounds-not-converted', why: 'The x-limits were kept in a θ-integral; they become $\\arcsin(-\\frac{1}{2})$ and $\\arcsin\\frac{\\sqrt{2}}{2}$.' },
          { latex: '\\int_{-\\pi/6}^{\\pi/4} \\frac{\\sin^3\\theta}{\\cos\\theta}\\,d\\theta', expr: 'integral(sin(theta)^3/cos(theta), theta, -pi/6, pi/4)', mistake: 'dx-not-replaced', why: 'The factor $\\cos\\theta$ from $dx$ was left out, so the root did not cancel.' },
          { latex: '\\int_{2\\pi/3}^{\\pi/4} \\sin^3\\theta\\,d\\theta', expr: 'integral(sin(theta)^3, theta, 2*pi/3, pi/4)', mistake: 'inverse-function-wrong-arg', why: 'Used arccos for the lower limit: $\\arccos(-\\frac{1}{2}) = \\frac{2\\pi}{3}$; the limits come from arcsine.' },
          { latex: '\\int_{\\pi/4}^{-\\pi/6} \\sin^3\\theta\\,d\\theta', expr: 'integral(sin(theta)^3, theta, pi/4, -pi/6)', mistake: 'bounds-swapped', why: 'The lower x-limit gives the lower θ-limit $-\\frac{\\pi}{6}$; the order was reversed.' },
          { latex: '\\int_{-\\pi/3}^{\\pi/4} \\sin^3\\theta\\,d\\theta', expr: 'integral(sin(theta)^3, theta, -pi/3, pi/4)', mistake: 'theta-bounds-wrong', why: '$\\sin(-\\frac{\\pi}{3}) = -\\frac{\\sqrt{3}}{2}$, not $-\\frac{1}{2}$.' },
        ],
        correct: 0,
        explanation: '$\\arcsin(-\\frac{1}{2}) = -\\frac{\\pi}{6}$, $\\arcsin\\frac{\\sqrt{2}}{2} = \\frac{\\pi}{4}$, and $\\frac{\\sin^3\\theta}{\\cos\\theta}\\cos\\theta = \\sin^3\\theta$.',
        result: { latex: 'x = -\\tfrac{1}{2} \\Rightarrow \\theta = -\\tfrac{\\pi}{6},\\quad x = \\tfrac{\\sqrt{2}}{2} \\Rightarrow \\theta = \\tfrac{\\pi}{4}:\\quad \\int_{-\\pi/6}^{\\pi/4} \\frac{\\sin^3\\theta}{\\cos\\theta}\\cos\\theta\\,d\\theta = \\int_{-\\pi/6}^{\\pi/4} \\sin^3\\theta\\,d\\theta' },
        check: { kind: 'value', expected: 'integral(x^3/sqrt(1-x^2), x, -1/2, sqrt(2)/2)' },
      },
      {
        prompt: 'Find an antiderivative of $\\sin^3\\theta$: save one $\\sin\\theta$, write $\\sin^2\\theta = 1 - \\cos^2\\theta$, and let $u = \\cos\\theta$.',
        options: [
          { latex: '\\frac{\\cos^3\\theta}{3} - \\cos\\theta + C', expr: 'cos(theta)^3/3 - cos(theta)' },
          { latex: '\\cos\\theta - \\frac{\\cos^3\\theta}{3} + C', expr: 'cos(theta) - cos(theta)^3/3', mistake: 'u-cos-sign-missing', why: 'With $u = \\cos\\theta$, $du = -\\sin\\theta\\,d\\theta$; the minus sign was dropped.' },
          { latex: '-\\cos\\theta - \\frac{\\cos^3\\theta}{3} + C', expr: '-cos(theta) - cos(theta)^3/3', mistake: 'pythagorean-wrong', why: 'Used $\\sin^2\\theta = 1 + \\cos^2\\theta$; it is $1 - \\cos^2\\theta$.' },
          { latex: '\\frac{\\sin^4\\theta}{4} + C', expr: 'sin(theta)^4/4', mistake: 'u-choice-wrong', why: 'The power rule on $\\sin\\theta$ needs the factor $\\cos\\theta\\,d\\theta$, which is not present.' },
          { latex: '3\\sin^2\\theta\\cos\\theta + C', expr: '3*sin(theta)^2*cos(theta)', mistake: 'differentiated-instead', why: 'That is the derivative of $\\sin^3\\theta$, not an antiderivative.' },
        ],
        correct: 0,
        explanation: '$\\int(1 - \\cos^2\\theta)\\sin\\theta\\,d\\theta = -\\int(1 - u^2)\\,du = \\frac{u^3}{3} - u + C$.',
        result: { latex: '-\\int (1-u^2)\\,du = \\frac{u^3}{3} - u + C = \\frac{\\cos^3\\theta}{3} - \\cos\\theta + C' },
        check: { kind: 'antiderivative', integrand: 'sin(theta)^3' },
        variable: 'theta',
        domain: { theta: [0.3, 1.2] },
      },
      {
        prompt: 'Evaluate $\\left[\\frac{\\cos^3\\theta}{3} - \\cos\\theta\\right]_{-\\pi/6}^{\\pi/4}$.',
        options: [
          { latex: '\\frac{3\\sqrt{3}}{8} - \\frac{5\\sqrt{2}}{12}', expr: '3*sqrt(3)/8 - 5*sqrt(2)/12' },
          { latex: '\\frac{5\\sqrt{2}}{12} - \\frac{3\\sqrt{3}}{8}', expr: '5*sqrt(2)/12 - 3*sqrt(3)/8', mistake: 'ftc-order-swapped', why: 'Computed $F(-\\frac{\\pi}{6}) - F(\\frac{\\pi}{4})$ instead of $F(\\frac{\\pi}{4}) - F(-\\frac{\\pi}{6})$.' },
          { latex: '-\\frac{5\\sqrt{2}}{12}', expr: '-5*sqrt(2)/12', mistake: 'ftc-not-subtracted', why: 'Only $F(\\frac{\\pi}{4}) = -\\frac{5\\sqrt{2}}{12}$ was computed; $F(-\\frac{\\pi}{6}) = -\\frac{3\\sqrt{3}}{8}$ must be subtracted.' },
          { latex: '-\\frac{5\\sqrt{2}}{12} - \\frac{3\\sqrt{3}}{8}', expr: '-5*sqrt(2)/12 - 3*sqrt(3)/8', mistake: 'ftc-not-subtracted', why: '$F(-\\frac{\\pi}{6})$ was added instead of subtracted.' },
          { latex: '-\\frac{5\\sqrt{2}}{12} - \\frac{11}{24}', expr: '-5*sqrt(2)/12 - 11/24', mistake: 'arithmetic-error', why: 'Used $\\sin(-\\frac{\\pi}{6}) = -\\frac{1}{2}$ in place of $\\cos(-\\frac{\\pi}{6}) = \\frac{\\sqrt{3}}{2}$ at the lower limit.' },
        ],
        correct: 0,
        explanation: '$F(\\frac{\\pi}{4}) = \\frac{\\sqrt{2}}{12} - \\frac{\\sqrt{2}}{2} = -\\frac{5\\sqrt{2}}{12}$ and $F(-\\frac{\\pi}{6}) = \\frac{\\sqrt{3}}{8} - \\frac{\\sqrt{3}}{2} = -\\frac{3\\sqrt{3}}{8}$; subtract.',
        result: { latex: '\\left(\\frac{\\sqrt{2}}{12} - \\frac{\\sqrt{2}}{2}\\right) - \\left(\\frac{\\sqrt{3}}{8} - \\frac{\\sqrt{3}}{2}\\right) = \\frac{3\\sqrt{3}}{8} - \\frac{5\\sqrt{2}}{12}' },
        check: { kind: 'value', expected: 'integral(x^3/sqrt(1-x^2), x, -1/2, sqrt(2)/2)' },
      },
    ],
    final: {
      latex: '\\frac{3\\sqrt{3}}{8} - \\frac{5\\sqrt{2}}{12}',
      expr: '3*sqrt(3)/8 - 5*sqrt(2)/12',
      check: { kind: 'definite-integral', integrand: 'x^3/sqrt(1-x^2)', lower: '-1/2', upper: 'sqrt(2)/2' },
      recap: 'Convert the limits with $\\theta = \\arcsin x$ (to $-\\frac{\\pi}{6}$ and $\\frac{\\pi}{4}$) and finish entirely in θ; there is no need to return to x.',
    },
    domain: { x: [-0.5, 0.7] },
    tags: ['sine', 'definite'],
  },
  {
    id: 'ts-s-03',
    topic: 'trig-sub',
    title: 'Secant substitution, x > √2 (Example 7.4)',
    difficulty: 2,
    statement: { text: 'Evaluate for $x > \\sqrt{2}$ (Example 7.4).', latex: '\\int \\frac{x^2}{\\sqrt{x^2-2}}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution fits $x^2 - 2$?',
        options: [
          { latex: 'x = \\sqrt{2}\\sec\\theta' },
          { latex: 'x = \\sqrt{2}\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums; $2\\tan^2\\theta - 2$ is not a Pythagorean square.' },
          { latex: 'x = \\sqrt{2}\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $2 - x^2$; $2\\sin^2\\theta - 2 = -2\\cos^2\\theta$ is negative under the root.' },
          { latex: 'x = 2\\sec\\theta', mistake: 'trig-sub-coefficient', why: '$b^2 = 2$ means $b = \\sqrt{2}$; $4\\sec^2\\theta - 2$ does not factor as $2(\\sec^2\\theta - 1)$.' },
          { latex: '\\sqrt{2}x = \\sec\\theta', mistake: 'trig-sub-coefficient', why: 'The constant belongs with θ: $\\sqrt{2}x = \\sec\\theta$ gives $\\frac{\\sec^2\\theta}{2} - 2$, which does not collapse.' },
        ],
        correct: 0,
        explanation: '$x^2 - 2 = x^2 - (\\sqrt{2})^2$ calls for $x = \\sqrt{2}\\sec\\theta$, so $dx = \\sqrt{2}\\sec\\theta\\tan\\theta\\,d\\theta$.',
        result: { latex: 'x = \\sqrt{2}\\sec\\theta,\\quad dx = \\sqrt{2}\\sec\\theta\\tan\\theta\\,d\\theta' },
      },
      {
        prompt: 'Since $x > \\sqrt{2}$, θ lies in $[0, \\frac{\\pi}{2})$. Simplify $\\sqrt{x^2-2}$.',
        options: [
          { latex: '\\sqrt{x^2-2} = \\sqrt{2}\\tan\\theta', expr: 'sqrt(2)*tan(theta)' },
          { latex: '\\sqrt{x^2-2} = -\\sqrt{2}\\tan\\theta', expr: '-sqrt(2)*tan(theta)', mistake: 'theta-interval-sign', why: 'On $[0, \\frac{\\pi}{2})$, $\\tan\\theta \\ge 0$; the minus sign is for $x < -\\sqrt{2}$.' },
          { latex: '\\sqrt{x^2-2} = 2\\tan\\theta', expr: '2*tan(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{2\\tan^2\\theta} = \\sqrt{2}\\tan\\theta$; the 2 must be rooted too.' },
          { latex: '\\sqrt{x^2-2} = \\sqrt{2}\\sec\\theta - \\sqrt{2}', expr: 'sqrt(2)*sec(theta) - sqrt(2)', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{2\\sec^2\\theta - 2} \\ne \\sqrt{2}\\sec\\theta - \\sqrt{2}$.' },
          { latex: '\\sqrt{x^2-2} = \\sqrt{2}\\sin\\theta', expr: 'sqrt(2)*sin(theta)', mistake: 'pythagorean-wrong', why: 'Mixed up identities: $\\sec^2\\theta - 1 = \\tan^2\\theta$; it is $1 - \\cos^2\\theta$ that equals $\\sin^2\\theta$.' },
        ],
        correct: 0,
        explanation: '$2\\sec^2\\theta - 2 = 2\\tan^2\\theta$, and $\\tan\\theta \\ge 0$ on $[0, \\frac{\\pi}{2})$.',
        result: { latex: '\\sqrt{2\\sec^2\\theta - 2} = \\sqrt{2\\tan^2\\theta} = \\sqrt{2}\\tan\\theta\\quad(\\tan\\theta \\ge 0)' },
        check: { kind: 'identity', lhs: 'sqrt((sqrt(2)*sec(theta))^2 - 2)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3] },
      },
      {
        prompt: 'Rewrite the integral entirely in θ.',
        options: [
          { latex: '\\int 2\\sec^3\\theta\\,d\\theta', expr: 'indefinite(2*sec(theta)^3, theta)' },
          { latex: '\\int \\frac{\\sqrt{2}\\sec^2\\theta}{\\tan\\theta}\\,d\\theta', expr: 'indefinite(sqrt(2)*sec(theta)^2/tan(theta), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\sqrt{2}\\sec\\theta\\tan\\theta$.' },
          { latex: '\\int x^2\\sec\\theta\\,d\\theta', expr: 'indefinite(x^2*sec(theta), theta)', mistake: 'mixed-variables', why: 'The numerator $x^2$ was left in x; it must become $2\\sec^2\\theta$.' },
          { latex: '\\int 2\\sec^2\\theta\\,d\\theta', expr: 'indefinite(2*sec(theta)^2, theta)', mistake: 'dx-derivative-wrong', why: 'Used $dx = \\sqrt{2}\\tan\\theta\\,d\\theta$; the derivative of $\\sec\\theta$ is $\\sec\\theta\\tan\\theta$.' },
          { latex: '\\int 2\\sqrt{2}\\sec^3\\theta\\,d\\theta', expr: 'indefinite(2*sqrt(2)*sec(theta)^3, theta)', mistake: 'dx-coefficient', why: 'Used $dx = 2\\sec\\theta\\tan\\theta\\,d\\theta$; the constant in $dx$ is $\\sqrt{2}$.' },
        ],
        correct: 0,
        explanation: '$\\frac{2\\sec^2\\theta}{\\sqrt{2}\\tan\\theta}\\cdot\\sqrt{2}\\sec\\theta\\tan\\theta = 2\\sec^3\\theta$.',
        result: { latex: '\\int \\frac{2\\sec^2\\theta}{\\sqrt{2}\\tan\\theta}\\,\\sqrt{2}\\sec\\theta\\tan\\theta\\,d\\theta = 2\\int\\sec^3\\theta\\,d\\theta' },
        check: { kind: 'identity', lhs: 'indefinite((sqrt(2)*sec(theta))^2*sqrt(2)*sec(theta)*tan(theta)/sqrt((sqrt(2)*sec(theta))^2 - 2), theta)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.2], x: [1.6, 3] },
      },
      {
        prompt: 'Integrate $2\\int\\sec^3\\theta\\,d\\theta$ (by parts, as in class: $u = \\sec\\theta$, $dv = \\sec^2\\theta\\,d\\theta$).',
        options: [
          { latex: '\\sec\\theta\\tan\\theta + \\ln|\\sec\\theta + \\tan\\theta| + C', expr: 'sec(theta)*tan(theta) + log(abs(sec(theta) + tan(theta)))' },
          { latex: '2\\sec\\theta\\tan\\theta + 2\\ln|\\sec\\theta + \\tan\\theta| + C', expr: '2*sec(theta)*tan(theta) + 2*log(abs(sec(theta) + tan(theta)))', mistake: 'ibp-cyclic-algebra', why: 'When $\\int\\sec^3\\theta\\,d\\theta$ reappeared, the equation was not divided by 2.' },
          { latex: '\\sec\\theta\\tan\\theta - \\ln|\\sec\\theta + \\tan\\theta| + C', expr: 'sec(theta)*tan(theta) - log(abs(sec(theta) + tan(theta)))', mistake: 'tan-sec-identity-direction', why: 'Used $\\tan^2\\theta = \\sec^2\\theta + 1$ in the parts step; it is $\\sec^2\\theta - 1$.' },
          { latex: '\\sec\\theta\\tan\\theta + C', expr: 'sec(theta)*tan(theta)', mistake: 'ibp-stopped-early', why: 'The term $\\int\\sec\\theta\\,d\\theta = \\ln|\\sec\\theta + \\tan\\theta|$ was dropped.' },
          { latex: '\\frac{\\sec^4\\theta}{2} + C', expr: 'sec(theta)^4/2', mistake: 'sec-odd-power-strategy', why: 'The power rule does not apply: $d(\\sec\\theta) = \\sec\\theta\\tan\\theta\\,d\\theta$ is not a factor; odd powers of secant need parts.' },
          { latex: '\\sec\\theta\\tan\\theta + \\ln|\\sec\\theta| + C', expr: 'sec(theta)*tan(theta) + log(abs(sec(theta)))', mistake: 'sec-antiderivative-wrong', why: '$\\int\\sec\\theta\\,d\\theta = \\ln|\\sec\\theta + \\tan\\theta|$, not $\\ln|\\sec\\theta|$.' },
        ],
        correct: 0,
        explanation: 'Parts gives $\\int\\sec^3\\theta\\,d\\theta = \\frac{1}{2}(\\sec\\theta\\tan\\theta + \\ln|\\sec\\theta + \\tan\\theta|) + C$; multiply by 2.',
        result: { latex: '2\\int\\sec^3\\theta\\,d\\theta = \\sec\\theta\\tan\\theta + \\ln|\\sec\\theta + \\tan\\theta| + C' },
        check: { kind: 'antiderivative', integrand: '2*sec(theta)^3' },
        variable: 'theta',
        domain: { theta: [0.2, 1.2] },
      },
      {
        prompt: 'Back-substitute with $\\sec\\theta = \\frac{x}{\\sqrt{2}}$ and $\\tan\\theta = \\frac{\\sqrt{x^2-2}}{\\sqrt{2}}$.',
        options: [
          { latex: '\\frac{x\\sqrt{x^2-2}}{2} + \\ln|x + \\sqrt{x^2-2}| + C', expr: 'x*sqrt(x^2-2)/2 + log(abs(x + sqrt(x^2-2)))' },
          { latex: 'x\\sqrt{x^2-2} + \\ln|x + \\sqrt{x^2-2}| + C', expr: 'x*sqrt(x^2-2) + log(abs(x + sqrt(x^2-2)))', mistake: 'coefficient-mishandled', why: 'The product has $\\sqrt{2}\\cdot\\sqrt{2} = 2$ in the denominator; it was dropped.' },
          { latex: '\\frac{x}{\\sqrt{x^2-2}} + \\ln|x + \\sqrt{x^2-2}| + C', expr: 'x/sqrt(x^2-2) + log(abs(x + sqrt(x^2-2)))', mistake: 'triangle-sides-wrong', why: 'Used adjacent over opposite for $\\tan\\theta$; that is $\\cot\\theta$.' },
          { latex: '\\frac{x\\sqrt{x^2+2}}{2} + \\ln|x + \\sqrt{x^2+2}| + C', expr: 'x*sqrt(x^2+2)/2 + log(abs(x + sqrt(x^2+2)))', mistake: 'triangle-sides-wrong', why: 'With hypotenuse x and adjacent side $\\sqrt{2}$, the opposite side is $\\sqrt{x^2 - 2}$.' },
          { latex: '\\sec\\theta\\tan\\theta + \\ln|\\sec\\theta + \\tan\\theta| + C', expr: 'sec(theta)*tan(theta) + log(abs(sec(theta) + tan(theta)))', mistake: 'not-back-substituted', why: 'The answer must be written in the original variable x.' },
        ],
        correct: 0,
        explanation: '$\\sec\\theta\\tan\\theta = \\frac{x\\sqrt{x^2-2}}{2}$, and $\\ln\\left|\\frac{x + \\sqrt{x^2-2}}{\\sqrt{2}}\\right| = \\ln|x + \\sqrt{x^2-2}| - \\ln\\sqrt{2}$; the constant joins C.',
        result: { latex: '\\frac{x}{\\sqrt{2}}\\cdot\\frac{\\sqrt{x^2-2}}{\\sqrt{2}} + \\ln\\left|\\frac{x + \\sqrt{x^2-2}}{\\sqrt{2}}\\right| + C = \\frac{x\\sqrt{x^2-2}}{2} + \\ln|x + \\sqrt{x^2-2}| + C_1' },
        check: { kind: 'antiderivative', integrand: 'x^2/sqrt(x^2-2)' },
        variable: 'x',
        domain: { x: [1.6, 4], theta: [0.3, 1.2] },
      },
    ],
    final: {
      latex: '\\frac{x\\sqrt{x^2-2}}{2} + \\ln|x + \\sqrt{x^2-2}| + C',
      expr: 'x*sqrt(x^2-2)/2 + log(abs(x + sqrt(x^2-2)))',
      check: { kind: 'antiderivative', integrand: 'x^2/sqrt(x^2-2)' },
      recap: 'For $x > \\sqrt{2}$, θ is in $[0, \\frac{\\pi}{2})$, so $\\sqrt{x^2-2} = \\sqrt{2}\\tan\\theta$ with no sign change; the integral becomes $2\\int\\sec^3\\theta\\,d\\theta$, done by parts.',
    },
    domain: { x: [1.6, 4] },
    tags: ['secant'],
  },
  {
    id: 'ts-s-04',
    topic: 'trig-sub',
    title: 'Sine substitution with a cotangent (Example 7.5)',
    difficulty: 1,
    statement: { text: 'Evaluate (Example 7.5).', latex: '\\int \\frac{\\sqrt{9-x^2}}{x^2}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution fits $9 - x^2$?',
        options: [
          { latex: 'x = 3\\sin\\theta' },
          { latex: 'x = 3\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $x^2 + 9$; $9 - 9\\tan^2\\theta$ is not a Pythagorean square.' },
          { latex: 'x = 3\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 9$; $9 - 9\\sec^2\\theta$ is negative under the root.' },
          { latex: 'x = 9\\sin\\theta', mistake: 'trig-sub-coefficient', why: '$b^2 = 9$ means $b = 3$; $9 - 81\\sin^2\\theta$ does not collapse.' },
          { latex: 'u = 9 - x^2', mistake: 'u-choice-wrong', why: '$du = -2x\\,dx$, but the integrand has $\\frac{1}{x^2}$ and no factor x.' },
        ],
        correct: 0,
        explanation: '$9 - x^2 = 3^2 - x^2$ is a difference, so $x = 3\\sin\\theta$ with $\\theta \\in [-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.',
        result: { latex: 'x = 3\\sin\\theta,\\quad \\theta = \\arcsin\\frac{x}{3} \\in \\left[-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right]' },
      },
      {
        prompt: 'Find $dx$ and $\\sqrt{9-x^2}$ in terms of θ.',
        options: [
          { latex: 'dx = 3\\cos\\theta\\,d\\theta,\\quad \\sqrt{9-x^2} = 3\\cos\\theta', expr: '[3*cos(theta)*dtheta, 3*cos(theta)]' },
          { latex: 'dx = \\cos\\theta\\,d\\theta,\\quad \\sqrt{9-x^2} = 3\\cos\\theta', expr: '[cos(theta)*dtheta, 3*cos(theta)]', mistake: 'dx-coefficient', why: 'The factor 3 in $dx = 3\\cos\\theta\\,d\\theta$ was dropped.' },
          { latex: 'dx = 3\\cos\\theta\\,d\\theta,\\quad \\sqrt{9-x^2} = 9\\cos\\theta', expr: '[3*cos(theta)*dtheta, 9*cos(theta)]', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{9\\cos^2\\theta} = 3\\cos\\theta$; the 9 must be rooted too.' },
          { latex: 'dx = 3\\cos\\theta\\,d\\theta,\\quad \\sqrt{9-x^2} = -3\\cos\\theta', expr: '[3*cos(theta)*dtheta, -3*cos(theta)]', mistake: 'theta-interval-sign', why: 'Cosine is nonnegative on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.' },
          { latex: 'dx = -3\\cos\\theta\\,d\\theta,\\quad \\sqrt{9-x^2} = 3\\cos\\theta', expr: '[-3*cos(theta)*dtheta, 3*cos(theta)]', mistake: 'dx-derivative-wrong', why: 'The derivative of $\\sin\\theta$ is $+\\cos\\theta$.' },
          { latex: 'dx = 3\\cos\\theta\\,d\\theta,\\quad \\sqrt{9-x^2} = 3 - 3\\sin\\theta', expr: '[3*cos(theta)*dtheta, 3 - 3*sin(theta)]', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{9 - 9\\sin^2\\theta} \\ne 3 - 3\\sin\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{d\\theta}(3\\sin\\theta) = 3\\cos\\theta$, and $\\sqrt{9 - 9\\sin^2\\theta} = 3|\\cos\\theta| = 3\\cos\\theta$ on this interval.',
        result: { latex: 'dx = 3\\cos\\theta\\,d\\theta,\\quad \\sqrt{9 - 9\\sin^2\\theta} = 3|\\cos\\theta| = 3\\cos\\theta' },
        check: { kind: 'value', expected: '[3*cos(theta)*dtheta, sqrt(9 - (3*sin(theta))^2)]' },
        variable: 'theta',
        domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Rewrite the integral entirely in θ.',
        options: [
          { latex: '\\int \\frac{\\cos^2\\theta}{\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(cos(theta)^2/sin(theta)^2, theta)' },
          { latex: '\\int \\frac{\\cos\\theta}{3\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(cos(theta)/(3*sin(theta)^2), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $3\\cos\\theta$.' },
          { latex: '\\int \\frac{9\\cos^2\\theta}{x^2}\\,d\\theta', expr: 'indefinite(9*cos(theta)^2/x^2, theta)', mistake: 'mixed-variables', why: 'The $x^2$ was never rewritten as $9\\sin^2\\theta$.' },
          { latex: '\\int \\frac{\\cos^2\\theta}{3\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(cos(theta)^2/(3*sin(theta)^2), theta)', mistake: 'dx-coefficient', why: 'Used $dx = \\cos\\theta\\,d\\theta$ instead of $3\\cos\\theta\\,d\\theta$.' },
          { latex: '\\int \\frac{3\\cos^2\\theta}{\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(3*cos(theta)^2/sin(theta)^2, theta)', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{9 - x^2} = 9\\cos\\theta$ instead of $3\\cos\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{3\\cos\\theta}{9\\sin^2\\theta}\\cdot 3\\cos\\theta = \\frac{\\cos^2\\theta}{\\sin^2\\theta} = \\cot^2\\theta$.',
        result: { latex: '\\int \\frac{3\\cos\\theta}{9\\sin^2\\theta}\\,3\\cos\\theta\\,d\\theta = \\int \\cot^2\\theta\\,d\\theta' },
        check: { kind: 'identity', lhs: 'indefinite(sqrt(9 - (3*sin(theta))^2)*3*cos(theta)/(3*sin(theta))^2, theta)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3], x: [0.5, 2.5] },
      },
      {
        prompt: 'Integrate $\\int\\cot^2\\theta\\,d\\theta$ (use $\\cot^2\\theta = \\csc^2\\theta - 1$).',
        options: [
          { latex: '-\\cot\\theta - \\theta + C', expr: '-cot(theta) - theta' },
          { latex: '-\\cot\\theta + \\theta + C', expr: '-cot(theta) + theta', mistake: 'pythagorean-wrong', why: 'Used $\\cot^2\\theta = \\csc^2\\theta + 1$; the identity is $\\csc^2\\theta - 1$.' },
          { latex: '\\cot\\theta - \\theta + C', expr: 'cot(theta) - theta', mistake: 'trig-antiderivative-sign', why: '$\\int\\csc^2\\theta\\,d\\theta = -\\cot\\theta$; the minus sign was dropped.' },
          { latex: '-\\csc\\theta - \\theta + C', expr: '-csc(theta) - theta', mistake: 'trig-antiderivative-swapped', why: '$-\\csc\\theta$ is the antiderivative of $\\csc\\theta\\cot\\theta$; for $\\csc^2\\theta$ it is $-\\cot\\theta$.' },
          { latex: '\\frac{\\cot^3\\theta}{3} + C', expr: 'cot(theta)^3/3', mistake: 'u-choice-wrong', why: 'The power rule needs $d(\\cot\\theta) = -\\csc^2\\theta\\,d\\theta$, which is not a factor.' },
        ],
        correct: 0,
        explanation: '$\\int(\\csc^2\\theta - 1)\\,d\\theta = -\\cot\\theta - \\theta + C$.',
        result: { latex: '\\int(\\csc^2\\theta - 1)\\,d\\theta = -\\cot\\theta - \\theta + C' },
        check: { kind: 'antiderivative', integrand: 'cos(theta)^2/sin(theta)^2' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3] },
      },
      {
        prompt: 'Back-substitute: $\\cot\\theta$ from the triangle and $\\theta = \\arcsin\\frac{x}{3}$.',
        options: [
          { latex: '-\\frac{\\sqrt{9-x^2}}{x} - \\arcsin\\frac{x}{3} + C', expr: '-sqrt(9-x^2)/x - asin(x/3)' },
          { latex: '-\\frac{x}{\\sqrt{9-x^2}} - \\arcsin\\frac{x}{3} + C', expr: '-x/sqrt(9-x^2) - asin(x/3)', mistake: 'triangle-sides-wrong', why: 'Used opposite over adjacent, which is $\\tan\\theta$, for $\\cot\\theta$.' },
          { latex: '-\\frac{\\sqrt{9-x^2}}{3} - \\arcsin\\frac{x}{3} + C', expr: '-sqrt(9-x^2)/3 - asin(x/3)', mistake: 'triangle-sides-wrong', why: 'Used adjacent over hypotenuse ($\\cos\\theta$); cotangent is adjacent over opposite.' },
          { latex: '-\\frac{\\sqrt{9-x^2}}{x} - \\arctan\\frac{x}{3} + C', expr: '-sqrt(9-x^2)/x - atan(x/3)', mistake: 'inverse-function-wrong-arg', why: 'With $x = 3\\sin\\theta$, $\\theta = \\arcsin\\frac{x}{3}$; arctangent belongs to a tangent substitution.' },
          { latex: '-\\cot\\theta - \\theta + C', expr: '-cot(theta) - theta', mistake: 'not-back-substituted', why: 'The answer must be written in the original variable x.' },
        ],
        correct: 0,
        explanation: 'Opposite $x$, hypotenuse 3, adjacent $\\sqrt{9-x^2}$, so $\\cot\\theta = \\frac{\\sqrt{9-x^2}}{x}$; and $\\theta = \\arcsin\\frac{x}{3}$.',
        result: { latex: '\\cot\\theta = \\frac{\\sqrt{9-x^2}}{x},\\quad \\theta = \\arcsin\\frac{x}{3}' },
        check: { kind: 'antiderivative', integrand: 'sqrt(9-x^2)/x^2' },
        variable: 'x',
        domain: { x: [0.5, 2.5], theta: [0.3, 1.2] },
      },
    ],
    final: {
      latex: '-\\frac{\\sqrt{9-x^2}}{x} - \\arcsin\\frac{x}{3} + C',
      expr: '-sqrt(9-x^2)/x - asin(x/3)',
      check: { kind: 'antiderivative', integrand: 'sqrt(9-x^2)/x^2' },
      recap: 'After $x = 3\\sin\\theta$ the integrand collapses to $\\cot^2\\theta = \\csc^2\\theta - 1$; the triangle gives $\\cot\\theta = \\frac{\\sqrt{9-x^2}}{x}$ and θ itself is $\\arcsin\\frac{x}{3}$.',
    },
    domain: { x: [0.5, 2.5] },
    tags: ['sine'],
  },
  {
    id: 'ts-s-05',
    topic: 'trig-sub',
    title: 'Half-disk area by sine substitution',
    difficulty: 1,
    statement: { text: 'Evaluate (practice problem 1d).', latex: '\\int_{-5}^{5} \\sqrt{25-x^2}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution fits $25 - x^2$?',
        options: [
          { latex: 'x = 5\\sin\\theta' },
          { latex: 'x = 5\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $x^2 + 25$; $25 - 25\\tan^2\\theta$ is not a Pythagorean square.' },
          { latex: 'x = 5\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 25$; $25 - 25\\sec^2\\theta$ is negative under the root.' },
          { latex: 'x = 25\\sin\\theta', mistake: 'trig-sub-coefficient', why: '$b^2 = 25$ means $b = 5$; $25 - 625\\sin^2\\theta$ does not collapse.' },
          { latex: '5x = \\sin\\theta', mistake: 'trig-sub-coefficient', why: 'The 5 belongs with θ: $5x = \\sin\\theta$ gives $25 - \\frac{\\sin^2\\theta}{25}$.' },
        ],
        correct: 0,
        explanation: '$25 - x^2 = 5^2 - x^2$ is a difference, so $x = 5\\sin\\theta$.',
        result: { latex: 'x = 5\\sin\\theta,\\quad \\theta = \\arcsin\\frac{x}{5} \\in \\left[-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right]' },
      },
      {
        prompt: 'Find $dx$ and $\\sqrt{25-x^2}$ in terms of θ.',
        options: [
          { latex: 'dx = 5\\cos\\theta\\,d\\theta,\\quad \\sqrt{25-x^2} = 5\\cos\\theta', expr: '[5*cos(theta)*dtheta, 5*cos(theta)]' },
          { latex: 'dx = \\cos\\theta\\,d\\theta,\\quad \\sqrt{25-x^2} = 5\\cos\\theta', expr: '[cos(theta)*dtheta, 5*cos(theta)]', mistake: 'dx-coefficient', why: 'The factor 5 in $dx = 5\\cos\\theta\\,d\\theta$ was dropped.' },
          { latex: 'dx = 5\\cos\\theta\\,d\\theta,\\quad \\sqrt{25-x^2} = 25\\cos\\theta', expr: '[5*cos(theta)*dtheta, 25*cos(theta)]', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{25\\cos^2\\theta} = 5\\cos\\theta$; the 25 must be rooted too.' },
          { latex: 'dx = 5\\cos\\theta\\,d\\theta,\\quad \\sqrt{25-x^2} = -5\\cos\\theta', expr: '[5*cos(theta)*dtheta, -5*cos(theta)]', mistake: 'theta-interval-sign', why: 'Cosine is nonnegative on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.' },
          { latex: 'dx = 5\\cos\\theta\\,d\\theta,\\quad \\sqrt{25-x^2} = 5 - 5\\sin\\theta', expr: '[5*cos(theta)*dtheta, 5 - 5*sin(theta)]', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{25 - 25\\sin^2\\theta} \\ne 5 - 5\\sin\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{d\\theta}(5\\sin\\theta) = 5\\cos\\theta$ and $\\sqrt{25\\cos^2\\theta} = 5\\cos\\theta$ since $\\cos\\theta \\ge 0$.',
        result: { latex: 'dx = 5\\cos\\theta\\,d\\theta,\\quad \\sqrt{25 - 25\\sin^2\\theta} = 5\\cos\\theta' },
        check: { kind: 'value', expected: '[5*cos(theta)*dtheta, sqrt(25 - (5*sin(theta))^2)]' },
        variable: 'theta',
        domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Rewrite the integral in θ, converting the limits.',
        options: [
          { latex: '\\int_{-\\pi/2}^{\\pi/2} 25\\cos^2\\theta\\,d\\theta', expr: 'integral(25*cos(theta)^2, theta, -pi/2, pi/2)' },
          { latex: '\\int_{-5}^{5} 25\\cos^2\\theta\\,d\\theta', expr: 'integral(25*cos(theta)^2, theta, -5, 5)', mistake: 'bounds-not-converted', why: 'The x-limits were kept; $x = \\pm 5$ gives $\\theta = \\arcsin(\\pm 1) = \\pm\\frac{\\pi}{2}$.' },
          { latex: '\\int_{-\\pi/2}^{\\pi/2} 5\\cos\\theta\\,d\\theta', expr: 'integral(5*cos(theta), theta, -pi/2, pi/2)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $5\\cos\\theta$.' },
          { latex: '\\int_{\\pi}^{0} 25\\cos^2\\theta\\,d\\theta', expr: 'integral(25*cos(theta)^2, theta, pi, 0)', mistake: 'inverse-function-wrong-arg', why: 'Used arccos for the limits ($\\arccos(-1) = \\pi$, $\\arccos 1 = 0$); a sine substitution needs arcsine.' },
          { latex: '\\int_{-\\pi/2}^{\\pi/2} 125\\cos^2\\theta\\,d\\theta', expr: 'integral(125*cos(theta)^2, theta, -pi/2, pi/2)', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{25 - x^2} = 25\\cos\\theta$ instead of $5\\cos\\theta$.' },
        ],
        correct: 0,
        explanation: '$5\\cos\\theta\\cdot 5\\cos\\theta\\,d\\theta = 25\\cos^2\\theta\\,d\\theta$, and $\\arcsin(\\pm 1) = \\pm\\frac{\\pi}{2}$.',
        result: { latex: '\\int_{-\\pi/2}^{\\pi/2} 5\\cos\\theta\\cdot 5\\cos\\theta\\,d\\theta = \\int_{-\\pi/2}^{\\pi/2} 25\\cos^2\\theta\\,d\\theta' },
        check: { kind: 'value', expected: 'integral(sqrt(25 - x^2), x, -5, 5)' },
      },
      {
        prompt: 'Evaluate $\\int_{-\\pi/2}^{\\pi/2} 25\\cos^2\\theta\\,d\\theta$ using $\\cos^2\\theta = \\frac{1 + \\cos 2\\theta}{2}$.',
        options: [
          { latex: '\\frac{25\\pi}{2}', expr: '25*pi/2' },
          { latex: '25\\pi', expr: '25*pi', mistake: 'half-angle-wrong', why: 'The factor $\\frac{1}{2}$ in the half-angle identity was dropped.' },
          { latex: '\\frac{25\\pi}{4}', expr: '25*pi/4', mistake: 'ftc-not-subtracted', why: 'Only $F(\\frac{\\pi}{2}) = \\frac{25\\pi}{4}$ was computed; $F(-\\frac{\\pi}{2}) = -\\frac{25\\pi}{4}$ must be subtracted.' },
          { latex: '0', expr: '0', mistake: 'sign-error', why: 'The sign of $F(-\\frac{\\pi}{2}) = -\\frac{25\\pi}{4}$ was lost, so the two values cancelled.' },
          { latex: '-\\frac{25\\pi}{2}', expr: '-25*pi/2', mistake: 'ftc-order-swapped', why: 'Computed $F(-\\frac{\\pi}{2}) - F(\\frac{\\pi}{2})$.' },
        ],
        correct: 0,
        explanation: '$\\frac{25}{2}\\left[\\theta + \\frac{\\sin 2\\theta}{2}\\right]_{-\\pi/2}^{\\pi/2} = \\frac{25}{2}\\cdot\\pi = \\frac{25\\pi}{2}$.',
        result: { latex: '\\frac{25}{2}\\left[\\theta + \\frac{\\sin 2\\theta}{2}\\right]_{-\\pi/2}^{\\pi/2} = \\frac{25}{2}\\left(\\frac{\\pi}{2} + \\frac{\\pi}{2}\\right) = \\frac{25\\pi}{2}' },
        check: { kind: 'value', expected: 'integral(sqrt(25 - x^2), x, -5, 5)' },
      },
    ],
    final: {
      latex: '\\frac{25\\pi}{2}',
      expr: '25*pi/2',
      check: { kind: 'definite-integral', integrand: 'sqrt(25 - x^2)', lower: '-5', upper: '5' },
      recap: 'Convert the limits with $\\theta = \\arcsin\\frac{x}{5}$ (to $\\pm\\frac{\\pi}{2}$) and lower the even power with the half-angle identity; the result is the area of a half-disk of radius 5.',
    },
    domain: { x: [-4, 4] },
    tags: ['sine', 'definite'],
  },
  {
    id: 'ts-s-06',
    topic: 'trig-sub',
    title: 'Sine substitution with a ≠ 1',
    difficulty: 2,
    statement: { text: 'Evaluate (practice problem 1e).', latex: '\\int \\sqrt{1-9x^2}\\,dx' },
    steps: [
      {
        prompt: 'Using $ax = b\\sin\\theta$, which substitution fits $1 - 9x^2$?',
        options: [
          { latex: '3x = \\sin\\theta' },
          { latex: 'x = 3\\sin\\theta', mistake: 'trig-sub-coefficient', why: 'The 3 multiplies x: $x = 3\\sin\\theta$ gives $1 - 81\\sin^2\\theta$, which does not collapse.' },
          { latex: '9x = \\sin\\theta', mistake: 'trig-sub-coefficient', why: '$(ax)^2 = 9x^2$ means $a = 3$, not 9; $9x = \\sin\\theta$ gives $1 - \\frac{\\sin^2\\theta}{9}$.' },
          { latex: '3x = \\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums; $1 - \\tan^2\\theta$ is not a Pythagorean square.' },
          { latex: '3x = \\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$; $1 - \\sec^2\\theta$ is negative under the root.' },
        ],
        correct: 0,
        explanation: '$1 - 9x^2 = 1^2 - (3x)^2$, so $a = 3$, $b = 1$: $3x = \\sin\\theta$.',
        result: { latex: '3x = \\sin\\theta,\\quad \\theta = \\arcsin(3x) \\in \\left[-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right]' },
      },
      {
        prompt: 'Compute $dx$.',
        options: [
          { latex: 'dx = \\frac{1}{3}\\cos\\theta\\,d\\theta', expr: 'cos(theta)*dtheta/3' },
          { latex: 'dx = 3\\cos\\theta\\,d\\theta', expr: '3*cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'Multiplied by $a = 3$ instead of dividing: $3\\,dx = \\cos\\theta\\,d\\theta$.' },
          { latex: 'dx = \\cos\\theta\\,d\\theta', expr: 'cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'The 3 multiplying $dx$ on the left was never divided out.' },
          { latex: 'dx = \\frac{1}{9}\\cos\\theta\\,d\\theta', expr: 'cos(theta)*dtheta/9', mistake: 'dx-coefficient', why: 'Divided by $a^2 = 9$ instead of $a = 3$.' },
          { latex: 'dx = -\\frac{1}{3}\\cos\\theta\\,d\\theta', expr: '-cos(theta)*dtheta/3', mistake: 'dx-derivative-wrong', why: 'The derivative of $\\sin\\theta$ is $+\\cos\\theta$.' },
        ],
        correct: 0,
        explanation: 'Differentiate $3x = \\sin\\theta$: $3\\,dx = \\cos\\theta\\,d\\theta$, so $dx = \\frac{b}{a}\\cos\\theta\\,d\\theta = \\frac{1}{3}\\cos\\theta\\,d\\theta$.',
        result: { latex: '3\\,dx = \\cos\\theta\\,d\\theta \;\\Rightarrow\; dx = \\frac{1}{3}\\cos\\theta\\,d\\theta' },
        check: { kind: 'value', expected: 'cos(theta)*dtheta/3' },
        variable: 'theta',
        domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Rewrite the integral entirely in θ.',
        options: [
          { latex: '\\int \\frac{1}{3}\\cos^2\\theta\\,d\\theta', expr: 'indefinite(cos(theta)^2/3, theta)' },
          { latex: '\\int 3\\cos^2\\theta\\,d\\theta', expr: 'indefinite(3*cos(theta)^2, theta)', mistake: 'dx-coefficient', why: 'Used $dx = 3\\cos\\theta\\,d\\theta$; it is $\\frac{1}{3}\\cos\\theta\\,d\\theta$.' },
          { latex: '\\int \\cos\\theta\\,d\\theta', expr: 'indefinite(cos(theta), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\frac{1}{3}\\cos\\theta$.' },
          { latex: '\\int -\\frac{1}{3}\\cos^2\\theta\\,d\\theta', expr: 'indefinite(-cos(theta)^2/3, theta)', mistake: 'theta-interval-sign', why: 'Took $\\sqrt{\\cos^2\\theta} = -\\cos\\theta$; cosine is nonnegative on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.' },
          { latex: '\\int \\frac{1}{3}\\cos\\theta\\sqrt{1-9x^2}\\,d\\theta', expr: 'indefinite(cos(theta)*sqrt(1 - 9*x^2)/3, theta)', mistake: 'mixed-variables', why: 'The root was left in x; it must become $\\cos\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\sqrt{1 - \\sin^2\\theta} = \\cos\\theta$ times $dx = \\frac{1}{3}\\cos\\theta\\,d\\theta$.',
        result: { latex: '\\int \\sqrt{1 - \\sin^2\\theta}\\cdot\\frac{1}{3}\\cos\\theta\\,d\\theta = \\frac{1}{3}\\int\\cos^2\\theta\\,d\\theta' },
        check: { kind: 'identity', lhs: 'indefinite(sqrt(1 - 9*(sin(theta)/3)^2)*cos(theta)/3, theta)' },
        variable: 'theta',
        domain: { theta: [-1.2, 1.2], x: [0.05, 0.3] },
      },
      {
        prompt: 'Integrate $\\frac{1}{3}\\int\\cos^2\\theta\\,d\\theta$ with the half-angle identity.',
        options: [
          { latex: '\\frac{\\theta}{6} + \\frac{\\sin 2\\theta}{12} + C', expr: 'theta/6 + sin(2*theta)/12' },
          { latex: '\\frac{\\theta}{6} - \\frac{\\sin 2\\theta}{12} + C', expr: 'theta/6 - sin(2*theta)/12', mistake: 'half-angle-wrong', why: 'Used the sine version $\\frac{1 - \\cos 2\\theta}{2}$ for $\\cos^2\\theta$.' },
          { latex: '\\frac{\\theta}{3} + \\frac{\\sin 2\\theta}{6} + C', expr: 'theta/3 + sin(2*theta)/6', mistake: 'half-angle-wrong', why: 'The factor $\\frac{1}{2}$ in $\\cos^2\\theta = \\frac{1 + \\cos 2\\theta}{2}$ was dropped.' },
          { latex: '\\frac{\\theta}{6} + \\frac{\\sin 2\\theta}{6} + C', expr: 'theta/6 + sin(2*theta)/6', mistake: 'inner-constant-factor-missing', why: '$\\int\\cos 2\\theta\\,d\\theta = \\frac{1}{2}\\sin 2\\theta$; the $\\frac{1}{2}$ was dropped.' },
          { latex: '\\frac{\\cos^3\\theta}{9} + C', expr: 'cos(theta)^3/9', mistake: 'u-choice-wrong', why: 'The power rule needs $d(\\cos\\theta) = -\\sin\\theta\\,d\\theta$, which is not a factor.' },
        ],
        correct: 0,
        explanation: '$\\frac{1}{3}\\int\\frac{1 + \\cos 2\\theta}{2}\\,d\\theta = \\frac{1}{6}\\left(\\theta + \\frac{\\sin 2\\theta}{2}\\right) + C$.',
        result: { latex: '\\frac{1}{3}\\int\\frac{1 + \\cos 2\\theta}{2}\\,d\\theta = \\frac{\\theta}{6} + \\frac{\\sin 2\\theta}{12} + C' },
        check: { kind: 'antiderivative', integrand: 'cos(theta)^2/3' },
        variable: 'theta',
        domain: { theta: [-1.2, 1.2] },
      },
      {
        prompt: 'Back-substitute using $\\sin 2\\theta = 2\\sin\\theta\\cos\\theta$, $\\sin\\theta = 3x$, $\\cos\\theta = \\sqrt{1-9x^2}$.',
        options: [
          { latex: '\\frac{1}{6}\\arcsin(3x) + \\frac{x}{2}\\sqrt{1-9x^2} + C', expr: 'asin(3*x)/6 + x/2*sqrt(1-9*x^2)' },
          { latex: '\\frac{1}{6}\\arcsin(3x) + \\frac{x}{4}\\sqrt{1-9x^2} + C', expr: 'asin(3*x)/6 + x/4*sqrt(1-9*x^2)', mistake: 'double-angle-wrong', why: 'Used $\\sin 2\\theta = \\sin\\theta\\cos\\theta$; the double-angle identity has a factor 2.' },
          { latex: '\\frac{1}{6}\\arcsin x + \\frac{x}{2}\\sqrt{1-9x^2} + C', expr: 'asin(x)/6 + x/2*sqrt(1-9*x^2)', mistake: 'inverse-function-wrong-arg', why: '$\\sin\\theta = 3x$, so $\\theta = \\arcsin(3x)$, not $\\arcsin x$.' },
          { latex: '\\frac{x}{2} + \\frac{x}{2}\\sqrt{1-9x^2} + C', expr: 'x/2 + x/2*sqrt(1-9*x^2)', mistake: 'inverse-function-wrong-arg', why: 'Replaced θ by $\\sin\\theta = 3x$ instead of $\\theta = \\arcsin(3x)$.' },
          { latex: '\\frac{1}{6}\\arcsin(3x) + \\frac{x}{2}\\sqrt{1-x^2} + C', expr: 'asin(3*x)/6 + x/2*sqrt(1-x^2)', mistake: 'triangle-sides-wrong', why: 'The opposite side is $3x$, so the adjacent side is $\\sqrt{1 - 9x^2}$, not $\\sqrt{1 - x^2}$.' },
          { latex: '\\frac{\\theta}{6} + \\frac{\\sin 2\\theta}{12} + C', expr: 'theta/6 + sin(2*theta)/12', mistake: 'not-back-substituted', why: 'The answer must be written in the original variable x.' },
        ],
        correct: 0,
        explanation: '$\\frac{\\sin 2\\theta}{12} = \\frac{2(3x)\\sqrt{1-9x^2}}{12} = \\frac{x}{2}\\sqrt{1-9x^2}$ and $\\theta = \\arcsin(3x)$.',
        result: { latex: '\\frac{\\theta}{6} + \\frac{2\\sin\\theta\\cos\\theta}{12} = \\frac{1}{6}\\arcsin(3x) + \\frac{x}{2}\\sqrt{1-9x^2} + C' },
        check: { kind: 'antiderivative', integrand: 'sqrt(1-9*x^2)' },
        variable: 'x',
        domain: { x: [0.05, 0.3], theta: [0.3, 1.2] },
      },
    ],
    final: {
      latex: '\\frac{1}{6}\\arcsin(3x) + \\frac{x}{2}\\sqrt{1-9x^2} + C',
      expr: 'asin(3*x)/6 + x/2*sqrt(1-9*x^2)',
      check: { kind: 'antiderivative', integrand: 'sqrt(1-9*x^2)' },
      recap: 'With $a \\ne 1$ the coefficient stays on the x side: $3x = \\sin\\theta$, so $dx = \\frac{1}{3}\\cos\\theta\\,d\\theta$ and $\\theta = \\arcsin(3x)$.',
    },
    domain: { x: [0.05, 0.3] },
    tags: ['sine'],
  },
  {
    id: 'ts-s-07',
    topic: 'trig-sub',
    title: 'Sine substitution giving csc²θ',
    difficulty: 1,
    statement: { text: 'Evaluate (practice problem 1f).', latex: '\\int \\frac{8}{x^2\\sqrt{4-x^2}}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution fits $4 - x^2$?',
        options: [
          { latex: 'x = 2\\sin\\theta' },
          { latex: 'x = 2\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $x^2 + 4$; $4 - 4\\tan^2\\theta$ is not a Pythagorean square.' },
          { latex: 'x = 2\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 4$; $4 - 4\\sec^2\\theta$ is negative under the root.' },
          { latex: 'x = 4\\sin\\theta', mistake: 'trig-sub-coefficient', why: '$b^2 = 4$ means $b = 2$; $4 - 16\\sin^2\\theta$ does not collapse.' },
          { latex: 'u = 4 - x^2', mistake: 'u-choice-wrong', why: '$du = -2x\\,dx$, but the integrand has $\\frac{1}{x^2}$ and no factor x.' },
        ],
        correct: 0,
        explanation: '$4 - x^2 = 2^2 - x^2$ is a difference, so $x = 2\\sin\\theta$ with $\\theta \\in [-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.',
        result: { latex: 'x = 2\\sin\\theta,\\quad \\theta = \\arcsin\\frac{x}{2}' },
      },
      {
        prompt: 'Find $dx$ and $\\sqrt{4-x^2}$ in terms of θ.',
        options: [
          { latex: 'dx = 2\\cos\\theta\\,d\\theta,\\quad \\sqrt{4-x^2} = 2\\cos\\theta', expr: '[2*cos(theta)*dtheta, 2*cos(theta)]' },
          { latex: 'dx = \\cos\\theta\\,d\\theta,\\quad \\sqrt{4-x^2} = 2\\cos\\theta', expr: '[cos(theta)*dtheta, 2*cos(theta)]', mistake: 'dx-coefficient', why: 'The factor 2 in $dx = 2\\cos\\theta\\,d\\theta$ was dropped.' },
          { latex: 'dx = 2\\cos\\theta\\,d\\theta,\\quad \\sqrt{4-x^2} = 4\\cos\\theta', expr: '[2*cos(theta)*dtheta, 4*cos(theta)]', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{4\\cos^2\\theta} = 2\\cos\\theta$; the 4 must be rooted too.' },
          { latex: 'dx = 2\\cos\\theta\\,d\\theta,\\quad \\sqrt{4-x^2} = -2\\cos\\theta', expr: '[2*cos(theta)*dtheta, -2*cos(theta)]', mistake: 'theta-interval-sign', why: 'Cosine is nonnegative on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.' },
          { latex: 'dx = -2\\cos\\theta\\,d\\theta,\\quad \\sqrt{4-x^2} = 2\\cos\\theta', expr: '[-2*cos(theta)*dtheta, 2*cos(theta)]', mistake: 'dx-derivative-wrong', why: 'The derivative of $\\sin\\theta$ is $+\\cos\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{d\\theta}(2\\sin\\theta) = 2\\cos\\theta$ and $\\sqrt{4 - 4\\sin^2\\theta} = 2\\cos\\theta$ since $\\cos\\theta \\ge 0$.',
        result: { latex: 'dx = 2\\cos\\theta\\,d\\theta,\\quad \\sqrt{4 - 4\\sin^2\\theta} = 2\\cos\\theta' },
        check: { kind: 'value', expected: '[2*cos(theta)*dtheta, sqrt(4 - (2*sin(theta))^2)]' },
        variable: 'theta',
        domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Rewrite the integral entirely in θ.',
        options: [
          { latex: '\\int 2\\csc^2\\theta\\,d\\theta', expr: 'indefinite(2*csc(theta)^2, theta)' },
          { latex: '\\int \\csc^2\\theta\\,d\\theta', expr: 'indefinite(csc(theta)^2, theta)', mistake: 'dx-coefficient', why: 'Used $dx = \\cos\\theta\\,d\\theta$ instead of $2\\cos\\theta\\,d\\theta$.' },
          { latex: '\\int \\frac{1}{\\sin^2\\theta\\cos\\theta}\\,d\\theta', expr: 'indefinite(1/(sin(theta)^2*cos(theta)), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $2\\cos\\theta$.' },
          { latex: '\\int -2\\csc^2\\theta\\,d\\theta', expr: 'indefinite(-2*csc(theta)^2, theta)', mistake: 'theta-interval-sign', why: 'Took $\\sqrt{4 - x^2} = -2\\cos\\theta$; cosine is nonnegative on this interval.' },
          { latex: '\\int \\frac{8}{x^2}\\,d\\theta', expr: 'indefinite(8/x^2, theta)', mistake: 'mixed-variables', why: 'The $x^2$ was never rewritten as $4\\sin^2\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{8\\cdot 2\\cos\\theta}{4\\sin^2\\theta\\cdot 2\\cos\\theta} = \\frac{2}{\\sin^2\\theta} = 2\\csc^2\\theta$.',
        result: { latex: '\\int \\frac{8\\cdot 2\\cos\\theta}{4\\sin^2\\theta\\cdot 2\\cos\\theta}\\,d\\theta = \\int 2\\csc^2\\theta\\,d\\theta' },
        check: { kind: 'identity', lhs: 'indefinite(8*2*cos(theta)/((2*sin(theta))^2*sqrt(4 - (2*sin(theta))^2)), theta)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3], x: [0.5, 1.8] },
      },
      {
        prompt: 'Integrate $\\int 2\\csc^2\\theta\\,d\\theta$.',
        options: [
          { latex: '-2\\cot\\theta + C', expr: '-2*cot(theta)' },
          { latex: '2\\cot\\theta + C', expr: '2*cot(theta)', mistake: 'trig-antiderivative-sign', why: '$\\frac{d}{d\\theta}\\cot\\theta = -\\csc^2\\theta$, so $\\int\\csc^2\\theta\\,d\\theta = -\\cot\\theta$.' },
          { latex: '-2\\csc\\theta + C', expr: '-2*csc(theta)', mistake: 'trig-antiderivative-swapped', why: '$-\\csc\\theta$ is the antiderivative of $\\csc\\theta\\cot\\theta$, not of $\\csc^2\\theta$.' },
          { latex: '2\\tan\\theta + C', expr: '2*tan(theta)', mistake: 'trig-antiderivative-swapped', why: '$\\tan\\theta$ is the antiderivative of $\\sec^2\\theta$, not of $\\csc^2\\theta$.' },
          { latex: '-\\frac{2}{3}\\csc^3\\theta + C', expr: '-2*csc(theta)^3/3', mistake: 'u-choice-wrong', why: 'The power rule needs $d(\\csc\\theta) = -\\csc\\theta\\cot\\theta\\,d\\theta$, which is not a factor.' },
        ],
        correct: 0,
        explanation: 'Since $\\frac{d}{d\\theta}(-\\cot\\theta) = \\csc^2\\theta$, $\\int 2\\csc^2\\theta\\,d\\theta = -2\\cot\\theta + C$.',
        result: { latex: '\\int 2\\csc^2\\theta\\,d\\theta = -2\\cot\\theta + C' },
        check: { kind: 'antiderivative', integrand: '2/sin(theta)^2' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3] },
      },
      {
        prompt: 'Back-substitute with the triangle for $\\sin\\theta = \\frac{x}{2}$.',
        options: [
          { latex: '-\\frac{2\\sqrt{4-x^2}}{x} + C', expr: '-2*sqrt(4-x^2)/x' },
          { latex: '-\\frac{2x}{\\sqrt{4-x^2}} + C', expr: '-2*x/sqrt(4-x^2)', mistake: 'triangle-sides-wrong', why: 'Used opposite over adjacent, which is $\\tan\\theta$, for $\\cot\\theta$.' },
          { latex: '-\\frac{\\sqrt{4-x^2}}{x} + C', expr: '-sqrt(4-x^2)/x', mistake: 'triangle-sides-wrong', why: 'Took $\\sin\\theta = x$ instead of $\\frac{x}{2}$ in $\\cot\\theta = \\frac{\\cos\\theta}{\\sin\\theta}$, which halves the answer.' },
          { latex: '-2\\cot x + C', expr: '-2*cot(x)', mistake: 'back-substitution-wrong', why: 'Replaced θ by x; θ is $\\arcsin\\frac{x}{2}$, and $\\cot\\theta$ comes from the triangle.' },
          { latex: '-2\\cot\\theta + C', expr: '-2*cot(theta)', mistake: 'not-back-substituted', why: 'The answer must be written in the original variable x.' },
        ],
        correct: 0,
        explanation: 'Opposite $x$, hypotenuse 2, adjacent $\\sqrt{4-x^2}$, so $\\cot\\theta = \\frac{\\sqrt{4-x^2}}{x}$.',
        result: { latex: '\\cot\\theta = \\frac{\\sqrt{4-x^2}}{x} \;\\Rightarrow\; -2\\cot\\theta + C = -\\frac{2\\sqrt{4-x^2}}{x} + C' },
        check: { kind: 'antiderivative', integrand: '8/(x^2*sqrt(4-x^2))' },
        variable: 'x',
        domain: { x: [0.5, 1.8], theta: [0.3, 1.2] },
      },
    ],
    final: {
      latex: '-\\frac{2\\sqrt{4-x^2}}{x} + C',
      expr: '-2*sqrt(4-x^2)/x',
      check: { kind: 'antiderivative', integrand: '8/(x^2*sqrt(4-x^2))' },
      recap: 'The $\\cos\\theta$ from $dx$ cancels the $\\cos\\theta$ from the root, leaving $2\\csc^2\\theta$; then $\\cot\\theta$ = adjacent over opposite $= \\frac{\\sqrt{4-x^2}}{x}$.',
    },
    domain: { x: [0.5, 1.8] },
    tags: ['sine'],
  },
  {
    id: 'ts-s-08',
    topic: 'trig-sub',
    title: 'Tangent substitution with limits',
    difficulty: 2,
    statement: { text: 'Evaluate (practice problem 1g).', latex: '\\int_{0}^{3/2} \\frac{8}{(x^2+1)^2}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution fits $(x^2 + 1)^2$?',
        options: [
          { latex: 'x = \\tan\\theta' },
          { latex: 'x = \\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $1 - x^2$; $\\sin^2\\theta + 1$ does not collapse.' },
          { latex: 'x = \\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 1$; $\\sec^2\\theta + 1$ is not a single square.' },
          { latex: 'x = 2\\tan\\theta', mistake: 'trig-sub-coefficient', why: 'The constant is $1 = 1^2$, so $b = 1$; $4\\tan^2\\theta + 1$ does not collapse.' },
          { latex: 'u = x^2 + 1', mistake: 'u-choice-wrong', why: '$du = 2x\\,dx$, but the numerator is 8, with no factor x.' },
        ],
        correct: 0,
        explanation: 'A sum $x^2 + 1^2$ calls for $x = \\tan\\theta$: $\\tan^2\\theta + 1 = \\sec^2\\theta$.',
        result: { latex: 'x = \\tan\\theta,\\quad \\theta = \\arctan x \\in \\left(-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right)' },
      },
      {
        prompt: 'Find $dx$ and $(x^2+1)^2$ in terms of θ.',
        options: [
          { latex: 'dx = \\sec^2\\theta\\,d\\theta,\\quad (x^2+1)^2 = \\sec^4\\theta', expr: '[sec(theta)^2*dtheta, sec(theta)^4]' },
          { latex: 'dx = \\sec\\theta\\tan\\theta\\,d\\theta,\\quad (x^2+1)^2 = \\sec^4\\theta', expr: '[sec(theta)*tan(theta)*dtheta, sec(theta)^4]', mistake: 'dx-derivative-wrong', why: 'That is the derivative of $\\sec\\theta$; for $x = \\tan\\theta$, $dx = \\sec^2\\theta\\,d\\theta$.' },
          { latex: 'dx = \\sec^2\\theta\\,d\\theta,\\quad (x^2+1)^2 = \\sec^2\\theta', expr: '[sec(theta)^2*dtheta, sec(theta)^2]', mistake: 'exponent-arithmetic', why: 'The outer square was lost: $(\\sec^2\\theta)^2 = \\sec^4\\theta$.' },
          { latex: 'dx = \\sec^2\\theta\\,d\\theta,\\quad (x^2+1)^2 = \\tan^4\\theta + 1', expr: '[sec(theta)^2*dtheta, tan(theta)^4 + 1]', mistake: 'algebra-error', why: '$(\\tan^2\\theta + 1)^2$ was expanded as $\\tan^4\\theta + 1$; use $\\tan^2\\theta + 1 = \\sec^2\\theta$ first.' },
          { latex: 'dx = \\sec^2\\theta\\,d\\theta,\\quad (x^2+1)^2 = \\csc^4\\theta', expr: '[sec(theta)^2*dtheta, csc(theta)^4]', mistake: 'pythagorean-wrong', why: 'Used $1 + \\cot^2\\theta = \\csc^2\\theta$; the tangent identity is $\\tan^2\\theta + 1 = \\sec^2\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{d}{d\\theta}\\tan\\theta = \\sec^2\\theta$ and $(\\tan^2\\theta + 1)^2 = (\\sec^2\\theta)^2 = \\sec^4\\theta$.',
        result: { latex: 'dx = \\sec^2\\theta\\,d\\theta,\\quad (x^2+1)^2 = (\\sec^2\\theta)^2 = \\sec^4\\theta' },
        check: { kind: 'value', expected: '[sec(theta)^2*dtheta, (tan(theta)^2 + 1)^2]' },
        variable: 'theta',
        domain: { theta: [0.2, 1.2], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Rewrite the integral in θ, converting the limits.',
        options: [
          { latex: '\\int_{0}^{\\arctan(3/2)} 8\\cos^2\\theta\\,d\\theta', expr: 'integral(8*cos(theta)^2, theta, 0, atan(3/2))' },
          { latex: '\\int_{0}^{3/2} 8\\cos^2\\theta\\,d\\theta', expr: 'integral(8*cos(theta)^2, theta, 0, 3/2)', mistake: 'bounds-not-converted', why: 'The x-limits were kept; $x = \\frac{3}{2}$ gives $\\theta = \\arctan\\frac{3}{2}$.' },
          { latex: '\\int_{0}^{\\arctan(3/2)} 8\\cos^4\\theta\\,d\\theta', expr: 'integral(8*cos(theta)^4, theta, 0, atan(3/2))', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\sec^2\\theta$.' },
          { latex: '\\int_{0}^{\\arctan(2/3)} 8\\cos^2\\theta\\,d\\theta', expr: 'integral(8*cos(theta)^2, theta, 0, atan(2/3))', mistake: 'inverse-function-wrong-arg', why: 'Inverted the ratio: $\\tan\\theta = x = \\frac{3}{2}$, not $\\frac{2}{3}$.' },
          { latex: '\\int_{0}^{\\arctan(3/2)} 8\\,d\\theta', expr: 'integral(8, theta, 0, atan(3/2))', mistake: 'exponent-arithmetic', why: 'Used $(x^2+1)^2 = \\sec^2\\theta$, so everything cancelled; it is $\\sec^4\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{8\\sec^2\\theta}{\\sec^4\\theta} = 8\\cos^2\\theta$; the limits are $\\arctan 0 = 0$ and $\\arctan\\frac{3}{2}$.',
        result: { latex: 'x = 0 \\Rightarrow \\theta = 0,\\ x = \\tfrac{3}{2} \\Rightarrow \\theta = \\arctan\\tfrac{3}{2}:\\quad \\int_0^{\\arctan(3/2)} \\frac{8\\sec^2\\theta}{\\sec^4\\theta}\\,d\\theta = \\int_0^{\\arctan(3/2)} 8\\cos^2\\theta\\,d\\theta' },
        check: { kind: 'value', expected: 'integral(8/(x^2+1)^2, x, 0, 3/2)' },
      },
      {
        prompt: 'Find an antiderivative of $8\\cos^2\\theta$ with the half-angle identity.',
        options: [
          { latex: '4\\theta + 2\\sin 2\\theta + C', expr: '4*theta + 2*sin(2*theta)' },
          { latex: '4\\theta - 2\\sin 2\\theta + C', expr: '4*theta - 2*sin(2*theta)', mistake: 'half-angle-wrong', why: 'Used the sine version $\\frac{1 - \\cos 2\\theta}{2}$ for $\\cos^2\\theta$.' },
          { latex: '8\\theta + 4\\sin 2\\theta + C', expr: '8*theta + 4*sin(2*theta)', mistake: 'half-angle-wrong', why: 'The factor $\\frac{1}{2}$ in $\\cos^2\\theta = \\frac{1 + \\cos 2\\theta}{2}$ was dropped.' },
          { latex: '4\\theta + 4\\sin 2\\theta + C', expr: '4*theta + 4*sin(2*theta)', mistake: 'inner-constant-factor-missing', why: '$\\int\\cos 2\\theta\\,d\\theta = \\frac{1}{2}\\sin 2\\theta$; the $\\frac{1}{2}$ was dropped.' },
          { latex: '\\frac{8\\cos^3\\theta}{3} + C', expr: '8*cos(theta)^3/3', mistake: 'u-choice-wrong', why: 'The power rule needs $d(\\cos\\theta) = -\\sin\\theta\\,d\\theta$, which is not a factor.' },
        ],
        correct: 0,
        explanation: '$8\\cdot\\frac{1 + \\cos 2\\theta}{2} = 4 + 4\\cos 2\\theta$, whose antiderivative is $4\\theta + 2\\sin 2\\theta$.',
        result: { latex: '\\int (4 + 4\\cos 2\\theta)\\,d\\theta = 4\\theta + 2\\sin 2\\theta + C' },
        check: { kind: 'antiderivative', integrand: '8*cos(theta)^2' },
        variable: 'theta',
        domain: { theta: [0.2, 1.2] },
      },
      {
        prompt: 'Evaluate $[4\\theta + 2\\sin 2\\theta]_0^{\\arctan(3/2)}$. (For $\\tan\\theta = \\frac{3}{2}$ the triangle has legs 3 and 2 and hypotenuse $\\sqrt{13}$.)',
        options: [
          { latex: '4\\arctan\\frac{3}{2} + \\frac{24}{13}', expr: '4*atan(3/2) + 24/13' },
          { latex: '4\\arctan\\frac{3}{2} + \\frac{12}{13}', expr: '4*atan(3/2) + 12/13', mistake: 'double-angle-wrong', why: 'Used $\\sin 2\\theta = \\sin\\theta\\cos\\theta = \\frac{6}{13}$; the double-angle identity has a factor 2.' },
          { latex: '6 + 2\\sin 3', expr: '6 + 2*sin(3)', mistake: 'bounds-not-converted', why: 'Plugged the x-limit $\\frac{3}{2}$ into a θ-antiderivative.' },
          { latex: '6 + \\frac{24}{13}', expr: '6 + 24/13', mistake: 'theta-bounds-wrong', why: 'Replaced $\\theta = \\arctan\\frac{3}{2}$ by $\\tan\\theta = \\frac{3}{2}$ in the $4\\theta$ term.' },
          { latex: '4\\arctan\\frac{3}{2} + \\frac{24}{\\sqrt{13}}', expr: '4*atan(3/2) + 24/sqrt(13)', mistake: 'triangle-sides-wrong', why: 'Divided by the hypotenuse only once: $\\sin\\theta\\cos\\theta = \\frac{3}{\\sqrt{13}}\\cdot\\frac{2}{\\sqrt{13}} = \\frac{6}{13}$.' },
        ],
        correct: 0,
        explanation: '$\\sin 2\\theta = 2\\cdot\\frac{3}{\\sqrt{13}}\\cdot\\frac{2}{\\sqrt{13}} = \\frac{12}{13}$, so the value is $4\\arctan\\frac{3}{2} + \\frac{24}{13}$ (the lower limit gives 0).',
        result: { latex: '4\\arctan\\frac{3}{2} + 2\\cdot\\frac{12}{13} - 0 = 4\\arctan\\frac{3}{2} + \\frac{24}{13}' },
        check: { kind: 'value', expected: 'integral(8/(x^2+1)^2, x, 0, 3/2)' },
      },
    ],
    final: {
      latex: '4\\arctan\\frac{3}{2} + \\frac{24}{13}',
      expr: '4*atan(3/2) + 24/13',
      check: { kind: 'definite-integral', integrand: '8/(x^2+1)^2', lower: '0', upper: '3/2' },
      recap: 'With $x = \\tan\\theta$ the limits become 0 and $\\arctan\\frac{3}{2}$ (not a special angle), so keep θ exact and read $\\sin 2\\theta$ off the triangle.',
    },
    domain: { x: [0.2, 1.4] },
    tags: ['tangent', 'definite'],
  },
  {
    id: 'ts-s-09',
    topic: 'trig-sub',
    title: 'Secant substitution, x > 1',
    difficulty: 2,
    statement: { text: 'Evaluate for $x > 1$ (practice problem 1h).', latex: '\\int \\frac{2}{x^3\\sqrt{x^2-1}}\\,dx' },
    steps: [
      {
        prompt: 'Which substitution and θ-interval fit $x^2 - 1$ with $x > 1$?',
        options: [
          { text: '$x = \\sec\\theta$ with $0 \\le \\theta < \\frac{\\pi}{2}$, so $\\tan\\theta \\ge 0$' },
          { text: '$x = \\sec\\theta$ with $\\frac{\\pi}{2} < \\theta \\le \\pi$, so $\\tan\\theta \\le 0$', mistake: 'theta-interval-sign', why: 'That interval is for $x \\le -1$; for $x > 1$, $\\operatorname{arcsec} x$ lies in $[0, \\frac{\\pi}{2})$.' },
          { text: '$x = \\sin\\theta$ with $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$', mistake: 'trig-sub-wrong-form', why: 'Sine is for $1 - x^2$; here $\\sin^2\\theta - 1 = -\\cos^2\\theta$ is negative under the root.' },
          { text: '$x = \\tan\\theta$ with $-\\frac{\\pi}{2} < \\theta < \\frac{\\pi}{2}$', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $x^2 + 1$; $\\tan^2\\theta - 1$ does not collapse.' },
          { text: 'u-substitution with $u = x^2 - 1$', mistake: 'u-choice-wrong', why: '$du = 2x\\,dx$, but the integrand has $\\frac{1}{x^3}$, not a factor x.' },
        ],
        correct: 0,
        explanation: '$x^2 - 1$ calls for $x = \\sec\\theta$, and $x > 1$ puts θ in $[0, \\frac{\\pi}{2})$, where $\\tan\\theta \\ge 0$.',
        result: { text: '$x = \\sec\\theta$, $\\theta = \\operatorname{arcsec} x \\in [0, \\frac{\\pi}{2})$, so $\\tan\\theta \\ge 0$.' },
      },
      {
        prompt: 'Find $\\sqrt{x^2-1}$ and $dx$ in terms of θ.',
        options: [
          { latex: '\\sqrt{x^2-1} = \\tan\\theta,\\quad dx = \\sec\\theta\\tan\\theta\\,d\\theta', expr: '[tan(theta), sec(theta)*tan(theta)*dtheta]' },
          { latex: '\\sqrt{x^2-1} = -\\tan\\theta,\\quad dx = \\sec\\theta\\tan\\theta\\,d\\theta', expr: '[-tan(theta), sec(theta)*tan(theta)*dtheta]', mistake: 'theta-interval-sign', why: 'For $x > 1$, $\\tan\\theta \\ge 0$, so the root is $+\\tan\\theta$.' },
          { latex: '\\sqrt{x^2-1} = \\tan\\theta,\\quad dx = \\sec^2\\theta\\,d\\theta', expr: '[tan(theta), sec(theta)^2*dtheta]', mistake: 'dx-derivative-wrong', why: '$\\sec^2\\theta$ is the derivative of $\\tan\\theta$; the derivative of $\\sec\\theta$ is $\\sec\\theta\\tan\\theta$.' },
          { latex: '\\sqrt{x^2-1} = \\sec\\theta - 1,\\quad dx = \\sec\\theta\\tan\\theta\\,d\\theta', expr: '[sec(theta) - 1, sec(theta)*tan(theta)*dtheta]', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{\\sec^2\\theta - 1} \\ne \\sec\\theta - 1$.' },
          { latex: '\\sqrt{x^2-1} = \\sin\\theta,\\quad dx = \\sec\\theta\\tan\\theta\\,d\\theta', expr: '[sin(theta), sec(theta)*tan(theta)*dtheta]', mistake: 'pythagorean-wrong', why: 'Mixed up identities: $\\sec^2\\theta - 1 = \\tan^2\\theta$; it is $1 - \\cos^2\\theta$ that equals $\\sin^2\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\sec^2\\theta - 1 = \\tan^2\\theta$ with $\\tan\\theta \\ge 0$, and $\\frac{d}{d\\theta}\\sec\\theta = \\sec\\theta\\tan\\theta$.',
        result: { latex: '\\sqrt{\\sec^2\\theta - 1} = \\tan\\theta,\\quad dx = \\sec\\theta\\tan\\theta\\,d\\theta' },
        check: { kind: 'value', expected: '[sqrt(sec(theta)^2 - 1), sec(theta)*tan(theta)*dtheta]' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Rewrite the integral entirely in θ.',
        options: [
          { latex: '\\int 2\\cos^2\\theta\\,d\\theta', expr: 'indefinite(2*cos(theta)^2, theta)' },
          { latex: '\\int -2\\cos^2\\theta\\,d\\theta', expr: 'indefinite(-2*cos(theta)^2, theta)', mistake: 'theta-interval-sign', why: 'Took $\\sqrt{x^2-1} = -\\tan\\theta$; for $x > 1$, $\\tan\\theta \\ge 0$.' },
          { latex: '\\int \\frac{2\\cos^3\\theta}{\\tan\\theta}\\,d\\theta', expr: 'indefinite(2*cos(theta)^3/tan(theta), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\sec\\theta\\tan\\theta$.' },
          { latex: '\\int 2\\sin^2\\theta\\,d\\theta', expr: 'indefinite(2*sin(theta)^2, theta)', mistake: 'algebra-error', why: '$\\frac{1}{\\sec^2\\theta} = \\cos^2\\theta$; sine is the reciprocal of cosecant, not of secant.' },
          { latex: '\\int \\frac{2\\sec\\theta}{x^3}\\,d\\theta', expr: 'indefinite(2*sec(theta)/x^3, theta)', mistake: 'mixed-variables', why: 'The $x^3$ was left in x; it must become $\\sec^3\\theta$.' },
        ],
        correct: 0,
        explanation: '$\\frac{2\\sec\\theta\\tan\\theta}{\\sec^3\\theta\\tan\\theta} = \\frac{2}{\\sec^2\\theta} = 2\\cos^2\\theta$.',
        result: { latex: '\\int \\frac{2\\sec\\theta\\tan\\theta}{\\sec^3\\theta\\tan\\theta}\\,d\\theta = \\int 2\\cos^2\\theta\\,d\\theta' },
        check: { kind: 'identity', lhs: 'indefinite(2*sec(theta)*tan(theta)/(sec(theta)^3*sqrt(sec(theta)^2 - 1)), theta)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3], x: [1.5, 3] },
      },
      {
        prompt: 'Integrate $\\int 2\\cos^2\\theta\\,d\\theta$.',
        options: [
          { latex: '\\theta + \\sin\\theta\\cos\\theta + C', expr: 'theta + sin(theta)*cos(theta)' },
          { latex: '\\theta - \\sin\\theta\\cos\\theta + C', expr: 'theta - sin(theta)*cos(theta)', mistake: 'half-angle-wrong', why: 'Used the sine version $\\frac{1 - \\cos 2\\theta}{2}$ for $\\cos^2\\theta$.' },
          { latex: '2\\theta + 2\\sin\\theta\\cos\\theta + C', expr: '2*theta + 2*sin(theta)*cos(theta)', mistake: 'half-angle-wrong', why: 'The factor $\\frac{1}{2}$ in $\\cos^2\\theta = \\frac{1 + \\cos 2\\theta}{2}$ was dropped.' },
          { latex: '\\theta + \\frac{1}{2}\\sin\\theta\\cos\\theta + C', expr: 'theta + sin(theta)*cos(theta)/2', mistake: 'double-angle-wrong', why: 'Rewrote $\\frac{1}{2}\\sin 2\\theta$ using $\\sin 2\\theta = \\sin\\theta\\cos\\theta$ (missing the 2).' },
          { latex: '\\frac{2\\cos^3\\theta}{3} + C', expr: '2*cos(theta)^3/3', mistake: 'u-choice-wrong', why: 'The power rule needs $d(\\cos\\theta) = -\\sin\\theta\\,d\\theta$, which is not a factor.' },
        ],
        correct: 0,
        explanation: '$\\int(1 + \\cos 2\\theta)\\,d\\theta = \\theta + \\frac{1}{2}\\sin 2\\theta = \\theta + \\sin\\theta\\cos\\theta$ (+C).',
        result: { latex: '\\int (1 + \\cos 2\\theta)\\,d\\theta = \\theta + \\frac{1}{2}\\sin 2\\theta + C = \\theta + \\sin\\theta\\cos\\theta + C' },
        check: { kind: 'antiderivative', integrand: '2*cos(theta)^2' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3] },
      },
      {
        prompt: 'Back-substitute: $\\theta = \\operatorname{arcsec} x$ and the triangle for $\\sec\\theta = x$.',
        options: [
          { latex: '\\operatorname{arcsec} x + \\frac{\\sqrt{x^2-1}}{x^2} + C', expr: 'asec(x) + sqrt(x^2-1)/x^2' },
          { latex: '\\operatorname{arcsec} x + \\sqrt{x^2-1} + C', expr: 'asec(x) + sqrt(x^2-1)', mistake: 'triangle-sides-wrong', why: 'Used $\\cos\\theta = x$ (that is $\\sec\\theta$); cosine is adjacent over hypotenuse, $\\frac{1}{x}$.' },
          { latex: '\\operatorname{arcsec} x - \\frac{\\sqrt{x^2-1}}{x^2} + C', expr: 'asec(x) - sqrt(x^2-1)/x^2', mistake: 'theta-interval-sign', why: 'For $x > 1$, θ is in $[0, \\frac{\\pi}{2})$, so $\\sin\\theta = \\frac{\\sqrt{x^2-1}}{x} \\ge 0$.' },
          { latex: '\\arctan x + \\frac{\\sqrt{x^2-1}}{x^2} + C', expr: 'atan(x) + sqrt(x^2-1)/x^2', mistake: 'inverse-function-wrong-arg', why: 'With $x = \\sec\\theta$, $\\theta = \\operatorname{arcsec} x$; arctangent belongs to a tangent substitution.' },
          { latex: '\\theta + \\sin\\theta\\cos\\theta + C', expr: 'theta + sin(theta)*cos(theta)', mistake: 'not-back-substituted', why: 'The answer must be written in the original variable x.' },
        ],
        correct: 0,
        explanation: 'Hypotenuse x, adjacent 1, opposite $\\sqrt{x^2-1}$: $\\sin\\theta\\cos\\theta = \\frac{\\sqrt{x^2-1}}{x}\\cdot\\frac{1}{x}$.',
        result: { latex: '\\sin\\theta = \\frac{\\sqrt{x^2-1}}{x},\\ \\cos\\theta = \\frac{1}{x}:\\quad \\operatorname{arcsec} x + \\frac{\\sqrt{x^2-1}}{x^2} + C' },
        check: { kind: 'antiderivative', integrand: '2/(x^3*sqrt(x^2-1))' },
        variable: 'x',
        domain: { x: [1.2, 3], theta: [0.3, 1.2] },
      },
    ],
    final: {
      latex: '\\operatorname{arcsec} x + \\frac{\\sqrt{x^2-1}}{x^2} + C',
      expr: 'asec(x) + sqrt(x^2-1)/x^2',
      check: { kind: 'antiderivative', integrand: '2/(x^3*sqrt(x^2-1))' },
      recap: 'Because $x > 1$, θ is in $[0, \\frac{\\pi}{2})$ and $\\sqrt{x^2-1} = \\tan\\theta$; the integrand becomes $2\\cos^2\\theta$, and the triangle gives $\\sin\\theta\\cos\\theta = \\frac{\\sqrt{x^2-1}}{x^2}$.',
    },
    domain: { x: [1.2, 3] },
    tags: ['secant'],
  },
  {
    id: 'ts-s-10',
    topic: 'trig-sub',
    title: 'Secant substitution with a ≠ 1',
    difficulty: 1,
    statement: { text: 'Evaluate for $x > \\frac{3}{5}$ (practice problem 1j).', latex: '\\int \\frac{5}{\\sqrt{25x^2-9}}\\,dx' },
    steps: [
      {
        prompt: 'Using $ax = b\\sec\\theta$, which substitution fits $25x^2 - 9$?',
        options: [
          { latex: '5x = 3\\sec\\theta' },
          { latex: '3x = 5\\sec\\theta', mistake: 'trig-sub-coefficient', why: 'a and b were swapped: $(ax)^2 = 25x^2$ means $a = 5$, and $b^2 = 9$ means $b = 3$.' },
          { latex: 'x = 3\\sec\\theta', mistake: 'trig-sub-coefficient', why: 'The coefficient $a = 5$ was ignored: $25\\cdot 9\\sec^2\\theta - 9$ does not factor as $9(\\sec^2\\theta - 1)$.' },
          { latex: '5x = 3\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums; $9\\tan^2\\theta - 9$ does not collapse.' },
          { latex: '5x = 3\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $9 - 25x^2$; here $9\\sin^2\\theta - 9$ is negative under the root.' },
          { latex: '25x = 9\\sec\\theta', mistake: 'trig-sub-coefficient', why: 'a and b are square roots: $a = \\sqrt{25} = 5$ and $b = \\sqrt{9} = 3$.' },
        ],
        correct: 0,
        explanation: '$25x^2 - 9 = (5x)^2 - 3^2$, so $a = 5$, $b = 3$: $5x = 3\\sec\\theta$.',
        result: { latex: '5x = 3\\sec\\theta,\\quad \\theta = \\operatorname{arcsec}\\frac{5x}{3} \\in \\left[0, \\frac{\\pi}{2}\\right)' },
      },
      {
        prompt: 'Compute $dx$.',
        options: [
          { latex: 'dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta', expr: '(3/5)*sec(theta)*tan(theta)*dtheta' },
          { latex: 'dx = 3\\sec\\theta\\tan\\theta\\,d\\theta', expr: '3*sec(theta)*tan(theta)*dtheta', mistake: 'dx-coefficient', why: 'The 5 multiplying $dx$ on the left was never divided out.' },
          { latex: 'dx = \\frac{5}{3}\\sec\\theta\\tan\\theta\\,d\\theta', expr: '(5/3)*sec(theta)*tan(theta)*dtheta', mistake: 'dx-coefficient', why: 'b/a was inverted; it is $\\frac{3}{5}$.' },
          { latex: 'dx = \\frac{3}{5}\\sec^2\\theta\\,d\\theta', expr: '(3/5)*sec(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: '$\\sec^2\\theta$ is the derivative of $\\tan\\theta$; the derivative of $\\sec\\theta$ is $\\sec\\theta\\tan\\theta$.' },
          { latex: 'dx = 15\\sec\\theta\\tan\\theta\\,d\\theta', expr: '15*sec(theta)*tan(theta)*dtheta', mistake: 'dx-coefficient', why: 'Multiplied by $a = 5$ instead of dividing by it.' },
        ],
        correct: 0,
        explanation: '$5\\,dx = 3\\sec\\theta\\tan\\theta\\,d\\theta$, so $dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta$.',
        result: { latex: 'dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta' },
        check: { kind: 'value', expected: '3*sec(theta)*tan(theta)*dtheta/5' },
        variable: 'theta',
        domain: { theta: [0.2, 1.2], dtheta: [0.25, 1.25] },
      },
      {
        prompt: 'Simplify $\\sqrt{25x^2-9}$ for $x > \\frac{3}{5}$.',
        options: [
          { latex: '\\sqrt{25x^2-9} = 3\\tan\\theta', expr: '3*tan(theta)' },
          { latex: '\\sqrt{25x^2-9} = 9\\tan\\theta', expr: '9*tan(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{9\\tan^2\\theta} = 3\\tan\\theta$; the 9 must be rooted too.' },
          { latex: '\\sqrt{25x^2-9} = -3\\tan\\theta', expr: '-3*tan(theta)', mistake: 'theta-interval-sign', why: 'For $x > \\frac{3}{5}$, θ is in $[0, \\frac{\\pi}{2})$ where $\\tan\\theta \\ge 0$.' },
          { latex: '\\sqrt{25x^2-9} = 3\\sec\\theta - 3', expr: '3*sec(theta) - 3', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{9\\sec^2\\theta - 9} \\ne 3\\sec\\theta - 3$.' },
          { latex: '\\sqrt{25x^2-9} = 5\\tan\\theta', expr: '5*tan(theta)', mistake: 'coefficient-mishandled', why: 'The constant that survives is $b = 3$: $(5x)^2 - 9 = 9\\sec^2\\theta - 9 = 9\\tan^2\\theta$.' },
        ],
        correct: 0,
        explanation: '$(5x)^2 - 9 = 9\\sec^2\\theta - 9 = 9\\tan^2\\theta$, and $\\tan\\theta \\ge 0$ on $[0, \\frac{\\pi}{2})$.',
        result: { latex: '\\sqrt{9\\sec^2\\theta - 9} = \\sqrt{9\\tan^2\\theta} = 3\\tan\\theta\\quad(\\tan\\theta \\ge 0)' },
        check: { kind: 'identity', lhs: 'sqrt(25*(3*sec(theta)/5)^2 - 9)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.3] },
      },
      {
        prompt: 'Rewrite the integral entirely in θ.',
        options: [
          { latex: '\\int \\sec\\theta\\,d\\theta', expr: 'indefinite(sec(theta), theta)' },
          { latex: '\\int 5\\sec\\theta\\,d\\theta', expr: 'indefinite(5*sec(theta), theta)', mistake: 'dx-coefficient', why: 'Used $dx = 3\\sec\\theta\\tan\\theta\\,d\\theta$; it is $\\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta$.' },
          { latex: '\\int \\frac{1}{3}\\sec\\theta\\,d\\theta', expr: 'indefinite(sec(theta)/3, theta)', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{25x^2-9} = 9\\tan\\theta$ instead of $3\\tan\\theta$.' },
          { latex: '\\int \\frac{5}{3\\tan\\theta}\\,d\\theta', expr: 'indefinite(5/(3*tan(theta)), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\frac{3}{5}\\sec\\theta\\tan\\theta$.' },
          { latex: '\\int \\frac{\\sec^2\\theta}{\\tan\\theta}\\,d\\theta', expr: 'indefinite(sec(theta)^2/tan(theta), theta)', mistake: 'dx-derivative-wrong', why: 'Used $dx = \\frac{3}{5}\\sec^2\\theta\\,d\\theta$ (the tangent derivative).' },
        ],
        correct: 0,
        explanation: '$\\frac{5}{3\\tan\\theta}\\cdot\\frac{3}{5}\\sec\\theta\\tan\\theta = \\sec\\theta$.',
        result: { latex: '\\int \\frac{5}{3\\tan\\theta}\\cdot\\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta = \\int\\sec\\theta\\,d\\theta' },
        check: { kind: 'identity', lhs: 'indefinite(5*(3/5)*sec(theta)*tan(theta)/sqrt(25*(3*sec(theta)/5)^2 - 9), theta)' },
        variable: 'theta',
        domain: { theta: [0.2, 1.2] },
      },
      {
        prompt: 'Integrate and back-substitute ($\\sec\\theta = \\frac{5x}{3}$, $\\tan\\theta = \\frac{\\sqrt{25x^2-9}}{3}$).',
        options: [
          { latex: '\\ln|5x + \\sqrt{25x^2-9}| + C', expr: 'log(abs(5*x + sqrt(25*x^2-9)))' },
          { latex: '\\ln\\left|\\frac{5x}{3}\\right| + C', expr: 'log(abs(5*x/3))', mistake: 'sec-antiderivative-wrong', why: 'Used $\\int\\sec\\theta\\,d\\theta = \\ln|\\sec\\theta|$; the $\\tan\\theta$ term is missing.' },
          { latex: '\\ln|5x - \\sqrt{25x^2-9}| + C', expr: 'log(abs(5*x - sqrt(25*x^2-9)))', mistake: 'sec-antiderivative-wrong', why: 'Used $\\ln|\\sec\\theta - \\tan\\theta|$; the antiderivative is $\\ln|\\sec\\theta + \\tan\\theta|$.' },
          { latex: '\\frac{5x\\sqrt{25x^2-9}}{9} + C', expr: '5*x*sqrt(25*x^2-9)/9', mistake: 'trig-antiderivative-swapped', why: 'Used $\\int\\sec\\theta\\,d\\theta = \\sec\\theta\\tan\\theta$; that is the derivative of $\\sec\\theta$.' },
          { latex: '\\ln|\\sec\\theta + \\tan\\theta| + C', expr: 'log(abs(sec(theta) + tan(theta)))', mistake: 'not-back-substituted', why: 'The answer must be written in the original variable x.' },
        ],
        correct: 0,
        explanation: '$\\ln\\left|\\frac{5x}{3} + \\frac{\\sqrt{25x^2-9}}{3}\\right| = \\ln|5x + \\sqrt{25x^2-9}| - \\ln 3$, and the constant joins C.',
        result: { latex: '\\ln\\left|\\frac{5x}{3} + \\frac{\\sqrt{25x^2-9}}{3}\\right| + C = \\ln|5x + \\sqrt{25x^2-9}| + C_1' },
        check: { kind: 'antiderivative', integrand: '5/sqrt(25*x^2-9)' },
        variable: 'x',
        domain: { x: [0.7, 2], theta: [0.3, 1.2] },
      },
    ],
    final: {
      latex: '\\ln|5x + \\sqrt{25x^2-9}| + C',
      expr: 'log(abs(5*x + sqrt(25*x^2-9)))',
      check: { kind: 'antiderivative', integrand: '5/sqrt(25*x^2-9)' },
      recap: 'With $5x = 3\\sec\\theta$, $dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta$ and $\\sqrt{25x^2-9} = 3\\tan\\theta$ cancel to $\\int\\sec\\theta\\,d\\theta$; the $\\frac{1}{3}$ inside the logarithm only shifts the constant.',
    },
    domain: { x: [0.7, 2] },
    tags: ['secant'],
  },
];
