import type { StepProblem } from '../types';

/**
 * Step-Through problems for topic "volumes-shells" (Lecture 4, §2.3). Authored by content-author;
 * verified by math-verifier.
 *
 * Each problem follows the Table 1 procedure: slice (parallel to the axis) → variable and limits →
 * radius and height → integral → evaluate. Every correct integral step is cross-checked against an
 * independent disk/washer (or geometric) computation of the same volume.
 */
export const steps: StepProblem[] = [
  // ───────────── vs-s-01: Example 4.1, the cone ─────────────
  {
    id: 'vs-s-01',
    topic: 'volumes-shells',
    title: 'The cone by shells',
    difficulty: 1,
    statement: {
      text: 'Use cylindrical shells to find the volume of the cone formed by rotating the triangle with vertices $(0, 0)$, $(6, 0)$, and $(0, 3)$ about the x-axis. The slanted side is the line $y = 3 - \\frac{x}{2}$.',
    },
    variable: 'y',
    steps: [
      {
        prompt: 'Which slices and limits does the shell method use here?',
        options: [
          { text: 'Vertical slices; integrate in $x$ from 0 to 6', mistake: 'shell-orientation-wrong', why: 'Vertical slices are perpendicular to the x-axis and sweep out disks; shell slices must be parallel to the axis.' },
          { text: 'Horizontal slices; integrate in $y$ from 0 to 3' },
          { text: 'Horizontal slices; integrate in $y$ from 0 to 6', mistake: 'bounds-wrong-axis', why: '6 is the width of the triangle along x; its height runs from y = 0 to y = 3.' },
          { text: 'Horizontal slices; integrate in $x$ from 0 to 6', mistake: 'wrong-integration-variable', why: 'A horizontal slice has thickness dy, so the shells are stacked along y.' },
          { text: 'Vertical slices; integrate in $y$ from 0 to 3', mistake: 'wrong-integration-variable', why: 'A vertical slice has thickness dx; and shells about the x-axis need horizontal slices anyway.' },
        ],
        correct: 1,
        explanation: 'Shell slices are parallel to the axis: horizontal slices of thickness $dy$, stacked from $y = 0$ up to the apex $y = 3$.',
        result: { text: 'Horizontal slices, $0 \\le y \\le 3$.' },
      },
      {
        prompt: 'At height $y$ the slice runs from the y-axis to the slanted side. What are the radius and height of the shell?',
        options: [
          { latex: 'r = 3 - y,\\quad h = 6 - 2y', expr: '[3 - y, 6 - 2*y]', mistake: 'shell-radius-wrong', why: '3 − y is the distance up to the apex height y = 3; the radius is the distance y down to the x-axis.' },
          { latex: 'r = y,\\quad h = 3 - \\frac{y}{2}', expr: '[y, 3 - y/2]', mistake: 'inverse-function-wrong', why: 'The line formula was reused with y in place of x; solving y = 3 − x/2 for x gives x = 6 − 2y.' },
          { latex: 'r = y,\\quad h = 6 - 2y', expr: '[y, 6 - 2*y]' },
          { latex: 'r = 3 - y,\\quad h = 3 - 2y', expr: '[3 - y, 3 - 2*y]', mistake: 'algebra-error', why: 'Two slips: x = 2(3 − y) was simplified to 3 − 2y instead of 6 − 2y, and 3 − y measures to the apex instead of the x-axis.' },
          { latex: 'r = y,\\quad h = 3 - 2y', expr: '[y, 3 - 2*y]', mistake: 'algebra-error', why: 'From x/2 = 3 − y we get x = 2(3 − y) = 6 − 2y; only the y-term was doubled.' },
          { latex: 'r = 3 - y,\\quad h = 3 - \\frac{y}{2}', expr: '[3 - y, 3 - y/2]', mistake: 'inverse-function-wrong', why: 'Two slips: the line formula was reused with y in place of x (x = 6 − 2y), and 3 − y measures to the apex instead of the x-axis.' },
        ],
        correct: 2,
        explanation: 'Solve the line for $x$: $x = 6 - 2y$, so the slice has length $6 - 2y$ and lies $y$ units above the x-axis.',
        result: { latex: 'x = 6 - 2y \\quad\\Rightarrow\\quad r = y,\\quad h = 6 - 2y' },
        check: { kind: 'value', expected: '[y, 6 - 2*y]' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_0^3 \\pi y(6 - 2y)\\,dy', expr: 'integral(pi*y*(6 - 2*y), y, 0, 3)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
          { latex: 'V = \\int_0^3 2\\pi y^2(6 - 2y)\\,dy', expr: 'integral(2*pi*y^2*(6 - 2*y), y, 0, 3)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_0^3 \\pi(6 - 2y)^2\\,dy', expr: 'integral(pi*(6 - 2*y)^2, y, 0, 3)', mistake: 'method-formula-swapped', why: 'π(length)² is a disk formula; a horizontal slice is parallel to the x-axis and sweeps out a shell.' },
          { latex: 'V = \\int_0^6 2\\pi y(6 - 2y)\\,dy', expr: 'integral(2*pi*y*(6 - 2*y), y, 0, 6)', mistake: 'bounds-wrong-axis', why: 'The y-limits are 0 and 3; 6 is an x-value.' },
          { latex: 'V = \\int_0^3 2\\pi y(6 - 2y)\\,dy', expr: 'integral(2*pi*y*(6 - 2*y), y, 0, 3)' },
        ],
        correct: 4,
        explanation: '$V = \\int_c^d 2\\pi r h\\,dy$ with $r = y$, $h = 6 - 2y$, $0 \\le y \\le 3$.',
        result: { latex: 'V = \\int_0^3 2\\pi y(6 - 2y)\\,dy' },
        check: { kind: 'value', expected: 'pi*3^2*6/3' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = 18\\pi', expr: '18*pi' },
          { latex: 'V = 72\\pi', expr: '72*pi', mistake: 'power-rule-int-coefficient', why: '∫6y dy = 3y²; writing 6y² gives 2π(54 − 18) = 72π.' },
          { latex: 'V = -54\\pi', expr: '-54*pi', mistake: 'power-rule-int-coefficient', why: '∫2y² dy = (2/3)y³; writing 2y³ gives 2π(27 − 54).' },
          { latex: 'V = 81\\pi', expr: '81*pi', mistake: 'product-rule-integral', why: 'The factors were integrated separately and multiplied: 2π·(9/2)·9; there is no product rule for integrals.' },
          { latex: 'V = 9\\pi', expr: '9*pi', mistake: 'coefficient-mishandled', why: 'The bracket is 9, so V = 2π·9; the factor 2 was lost.' },
        ],
        correct: 0,
        explanation: '$2\\pi\\left[3y^2 - \\frac{2}{3}y^3\\right]_0^3 = 2\\pi(27 - 18) = 18\\pi$.',
        result: { latex: 'V = 2\\pi\\left[3y^2 - \\tfrac{2}{3}y^3\\right]_0^3 = 2\\pi(27 - 18) = 18\\pi' },
        check: { kind: 'value', expected: '18*pi' },
      },
    ],
    final: {
      latex: 'V = 18\\pi',
      expr: '18*pi',
      check: { kind: 'definite-integral', integrand: '2*pi*y*(6 - 2*y)', lower: '0', upper: '3' },
      recap: 'About the x-axis, shells use horizontal slices: $r = y$ and $h = 6 - 2y$ (the line solved for $x$). The result matches the cone formula $\\frac{1}{3}\\pi r^2 h = \\frac{1}{3}\\pi\\cdot 3^2\\cdot 6 = 18\\pi$.',
    },
    tags: ['x-axis', 'cone'],
  },

  // ───────────── vs-s-02: Example 4.2, √x about the x-axis ─────────────
  {
    id: 'vs-s-02',
    topic: 'volumes-shells',
    title: 'Shells about the x-axis under y = √x',
    difficulty: 1,
    statement: {
      text: 'Use cylindrical shells to find the volume of the solid obtained by rotating the region bounded by $y = \\sqrt{x}$, the x-axis, and $x = 4$ about the x-axis.',
    },
    variable: 'y',
    steps: [
      {
        prompt: 'Shells about the x-axis use slices parallel to the axis, i.e. horizontal slices. Where does the slice at height $y$ run?',
        options: [
          { text: 'From $x = 0$ to $x = y^2$', mistake: 'shell-height-wrong', why: 'That piece lies left of the curve, outside the region; the region is to the right of x = y².' },
          { text: 'From $x = \\sqrt{y}$ to $x = 4$', mistake: 'inverse-function-wrong', why: 'Solving y = √x for x gives x = y², not x = √y.' },
          { text: 'From $x = y^2$ to $x = 4$' },
          { text: 'From $x = 0$ to $x = 4$', mistake: 'shell-height-wrong', why: 'That ignores the curve: at height y the region only begins at x = y².' },
          { text: 'From $y = 0$ up to $y = \\sqrt{x}$', mistake: 'shell-orientation-wrong', why: 'That is a vertical slice, perpendicular to the x-axis; it sweeps out a disk, not a shell.' },
        ],
        correct: 2,
        explanation: 'At height $y$ the region lies between the curve $x = y^2$ (left) and the line $x = 4$ (right).',
        result: { text: 'Horizontal slice at height $y$: from $x = y^2$ to $x = 4$.' },
      },
      {
        prompt: 'What are the variable and limits of integration?',
        options: [
          { text: '$y$ from 0 to 4', mistake: 'bounds-wrong-axis', why: '4 is the x-extent of the region; the curve only reaches height √4 = 2.' },
          { text: '$x$ from 0 to 4', mistake: 'wrong-integration-variable', why: 'Horizontal slices have thickness dy, so the shells are stacked along y.' },
          { text: '$y$ from $-2$ to 2', mistake: 'interval-not-respected', why: 'y² = 4 also has the root y = −2, but the region is bounded below by the x-axis, so y ≥ 0.' },
          { text: '$y$ from 0 to 2' },
          { text: '$y$ from 0 to 16', mistake: 'inverse-function-wrong', why: 'At x = 4 the curve is at height √4 = 2; 16 comes from squaring 4 instead of taking its root.' },
        ],
        correct: 3,
        explanation: 'The slices are stacked along $y$, from the x-axis ($y = 0$) up to the top of the region, $y = \\sqrt{4} = 2$.',
        result: { text: '$0 \\le y \\le 2$' },
      },
      {
        prompt: 'What are the radius and height of the shell at height $y$?',
        options: [
          { latex: 'r = 2 - y,\\quad h = y^2', expr: '[2 - y, y^2]', mistake: 'shell-height-wrong', why: 'Two slips: y² is the part left of the curve (outside the region), and 2 − y measures to the top of the region instead of the x-axis.' },
          { latex: 'r = y,\\quad h = y^2', expr: '[y, y^2]', mistake: 'shell-height-wrong', why: 'y² is the distance from the y-axis to the curve, which is outside the region; the slice runs from x = y² to x = 4.' },
          { latex: 'r = 2 - y,\\quad h = 4 - y^2', expr: '[2 - y, 4 - y^2]', mistake: 'shell-radius-wrong', why: '2 − y is the distance to the top of the region (y = 2); the radius is the distance y to the x-axis.' },
          { latex: 'r = y,\\quad h = 4 - \\sqrt{y}', expr: '[y, 4 - sqrt(y)]', mistake: 'inverse-function-wrong', why: 'The left end of the slice is x = y² (the curve solved for x), not √y.' },
          { latex: 'r = 2 - y,\\quad h = 4 - \\sqrt{y}', expr: '[2 - y, 4 - sqrt(y)]', mistake: 'inverse-function-wrong', why: 'Two slips: y = √x was solved as x = √y instead of y², and 2 − y measures to the top of the region instead of the x-axis.' },
          { latex: 'r = y,\\quad h = 4 - y^2', expr: '[y, 4 - y^2]' },
        ],
        correct: 5,
        explanation: 'Radius = distance from the slice to the x-axis = $y$; height = right − left = $4 - y^2$.',
        result: { latex: 'r = y,\\quad h = 4 - y^2' },
        check: { kind: 'value', expected: '[y, 4 - y^2]' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_0^2 \\pi y(4 - y^2)\\,dy', expr: 'integral(pi*y*(4 - y^2), y, 0, 2)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
          { latex: 'V = \\int_0^2 2\\pi y(4 - y^2)\\,dy', expr: 'integral(2*pi*y*(4 - y^2), y, 0, 2)' },
          { latex: 'V = \\int_0^2 2\\pi y^2(4 - y^2)\\,dy', expr: 'integral(2*pi*y^2*(4 - y^2), y, 0, 2)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_0^2 \\pi(4 - y^2)^2\\,dy', expr: 'integral(pi*(4 - y^2)^2, y, 0, 2)', mistake: 'method-formula-swapped', why: 'π(length)² is a disk formula; a horizontal slice is parallel to the x-axis and sweeps out a shell.' },
          { latex: 'V = \\int_0^4 2\\pi y(4 - y^2)\\,dy', expr: 'integral(2*pi*y*(4 - y^2), y, 0, 4)', mistake: 'bounds-wrong-axis', why: 'The y-limits are 0 and 2; 4 is an x-value.' },
        ],
        correct: 1,
        explanation: '$V = \\int_c^d 2\\pi r h\\,dy$ with $r = y$, $h = 4 - y^2$, $0 \\le y \\le 2$.',
        result: { latex: 'V = \\int_0^2 2\\pi y(4 - y^2)\\,dy' },
        check: { kind: 'value', expected: 'integral(pi*x, x, 0, 4)' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = -16\\pi', expr: '-16*pi', mistake: 'power-rule-int-coefficient', why: '∫y³ dy = y⁴/4; without the division by 4 the result is 2π(8 − 16).' },
          { latex: 'V = 24\\pi', expr: '24*pi', mistake: 'power-rule-int-coefficient', why: '∫4y dy = 2y²; writing 4y² gives 2π(16 − 4).' },
          { latex: 'V = 4\\pi', expr: '4*pi', mistake: 'coefficient-mishandled', why: 'The bracket is 4, so V = 2π·4; the factor 2 was lost.' },
          { latex: 'V = \\frac{64\\pi}{3}', expr: '64*pi/3', mistake: 'product-rule-integral', why: 'The factors were integrated separately and multiplied: 2π·2·(16/3); there is no product rule for integrals.' },
          { latex: 'V = 8\\pi', expr: '8*pi' },
        ],
        correct: 4,
        explanation: '$2\\pi\\left[2y^2 - \\frac{y^4}{4}\\right]_0^2 = 2\\pi(8 - 4) = 8\\pi$.',
        result: { latex: 'V = 2\\pi\\left[2y^2 - \\tfrac{y^4}{4}\\right]_0^2 = 2\\pi(8 - 4) = 8\\pi' },
        check: { kind: 'value', expected: '8*pi' },
      },
    ],
    final: {
      latex: 'V = 8\\pi',
      expr: '8*pi',
      check: { kind: 'definite-integral', integrand: '2*pi*y*(4 - y^2)', lower: '0', upper: '2' },
      recap: 'About the x-axis, shells use horizontal slices: $r = y$ and $h$ = right − left $= 4 - y^2$ for $0 \\le y \\le 2$. It matches the disk method, $\\pi\\int_0^4 x\\,dx = 8\\pi$.',
    },
    tags: ['x-axis'],
  },

  // ───────────── vs-s-03: Example 4.3, √x about the y-axis ─────────────
  {
    id: 'vs-s-03',
    topic: 'volumes-shells',
    title: 'Shells about the y-axis under y = √x',
    difficulty: 1,
    statement: {
      text: 'Use cylindrical shells to find the volume of the solid obtained by rotating the region bounded by $y = \\sqrt{x}$, the x-axis, and $x = 4$ about the y-axis.',
    },
    steps: [
      {
        prompt: 'Which slices and limits does the shell method use here?',
        options: [
          { text: 'Horizontal slices; integrate in $y$ from 0 to 2', mistake: 'shell-orientation-wrong', why: 'Horizontal slices are perpendicular to the y-axis and sweep out washers; shells need vertical slices.' },
          { text: 'Vertical slices; integrate in $x$ from 0 to 2', mistake: 'bounds-wrong-axis', why: '2 is the height of the region; along x it runs from 0 to 4.' },
          { text: 'Vertical slices; integrate in $y$ from 0 to 2', mistake: 'wrong-integration-variable', why: 'A vertical slice has thickness dx, so the shells are stacked along x.' },
          { text: 'Horizontal slices; integrate in $x$ from 0 to 4', mistake: 'wrong-integration-variable', why: 'A horizontal slice has thickness dy; and shells about the y-axis need vertical slices anyway.' },
          { text: 'Vertical slices; integrate in $x$ from 0 to 4' },
        ],
        correct: 4,
        explanation: 'Slices parallel to the y-axis are vertical (thickness $dx$) and cover $0 \\le x \\le 4$.',
        result: { text: 'Vertical slices, $0 \\le x \\le 4$.' },
      },
      {
        prompt: 'What are the radius and height of the shell at position $x$?',
        options: [
          { latex: 'r = 4 - x,\\quad h = \\sqrt{x}', expr: '[4 - x, sqrt(x)]', mistake: 'shell-radius-wrong', why: '4 − x is the distance to the right edge x = 4 of the region; the radius is the distance x to the y-axis.' },
          { latex: 'r = x,\\quad h = \\sqrt{x}', expr: '[x, sqrt(x)]' },
          { latex: 'r = x,\\quad h = 2 - \\sqrt{x}', expr: '[x, 2 - sqrt(x)]', mistake: 'shell-height-wrong', why: 'That measures from the curve up to y = 2, which is above the region.' },
          { latex: 'r = 4 - x,\\quad h = x^2', expr: '[4 - x, x^2]', mistake: 'inverse-function-wrong', why: 'Two slips: x² comes from mixing up y = √x with x = y², and 4 − x measures to x = 4 instead of the y-axis.' },
          { latex: 'r = x,\\quad h = x^2', expr: '[x, x^2]', mistake: 'inverse-function-wrong', why: 'x² comes from mixing up the curve y = √x with x = y²; the slice runs from y = 0 up to y = √x.' },
          { latex: 'r = 4 - x,\\quad h = 2 - \\sqrt{x}', expr: '[4 - x, 2 - sqrt(x)]', mistake: 'shell-radius-wrong', why: 'Two slips: 4 − x measures to x = 4 instead of the y-axis, and 2 − √x is the strip above the curve.' },
        ],
        correct: 1,
        explanation: 'The slice at $x$ runs from $y = 0$ up to $y = \\sqrt{x}$ and lies $x$ units from the y-axis.',
        result: { latex: 'r = x,\\quad h = \\sqrt{x}' },
        check: { kind: 'value', expected: '[x, sqrt(x)]' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_0^4 \\pi x\\sqrt{x}\\,dx', expr: 'integral(pi*x*sqrt(x), x, 0, 4)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
          { latex: 'V = \\int_0^4 2\\pi x^2\\sqrt{x}\\,dx', expr: 'integral(2*pi*x^2*sqrt(x), x, 0, 4)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_0^4 2\\pi x\\sqrt{x}\\,dx', expr: 'integral(2*pi*x*sqrt(x), x, 0, 4)' },
          { latex: 'V = \\int_0^4 \\pi(\\sqrt{x})^2\\,dx', expr: 'integral(pi*(sqrt(x))^2, x, 0, 4)', mistake: 'method-formula-swapped', why: 'That is the disk formula for slices perpendicular to the x-axis; it gives the x-axis solid.' },
          { latex: 'V = \\int_0^2 2\\pi x\\sqrt{x}\\,dx', expr: 'integral(2*pi*x*sqrt(x), x, 0, 2)', mistake: 'bounds-wrong-axis', why: 'The x-limits are 0 and 4; 2 is the largest y-value.' },
        ],
        correct: 2,
        explanation: '$V = \\int_a^b 2\\pi r h\\,dx$ with $r = x$, $h = \\sqrt{x}$, $0 \\le x \\le 4$.',
        result: { latex: 'V = \\int_0^4 2\\pi x\\sqrt{x}\\,dx = 2\\pi\\int_0^4 x^{3/2}\\,dx' },
        check: { kind: 'value', expected: 'integral(pi*(16 - y^4), y, 0, 2)' },
      },
      {
        prompt: 'Evaluate $2\\pi\\int_0^4 x^{3/2}\\,dx$.',
        options: [
          { latex: 'V = \\frac{64\\pi}{5}', expr: '64*pi/5', mistake: 'coefficient-mishandled', why: 'The bracket is (2/5)·32 = 64/5, so V = 2π·64/5; the factor 2 was lost.' },
          { latex: 'V = 160\\pi', expr: '160*pi', mistake: 'power-rule-int-coefficient', why: '$x^{5/2}$ was multiplied by 5/2 instead of divided: 2π·(5/2)·32.' },
          { latex: 'V = \\frac{128\\pi}{3}', expr: '128*pi/3', mistake: 'power-rule-int-coefficient', why: '$x^{5/2}$ was divided by 3/2 (the old exponent) instead of by 5/2.' },
          { latex: 'V = \\frac{128\\pi}{5}', expr: '128*pi/5' },
          { latex: 'V = 6\\pi', expr: '6*pi', mistake: 'differentiated-instead', why: '$x^{3/2}$ was differentiated to $\\frac{3}{2}x^{1/2}$ (3 at x = 4) instead of integrated.' },
        ],
        correct: 3,
        explanation: '$2\\pi\\cdot\\frac{2}{5}x^{5/2}\\Big|_0^4 = \\frac{4\\pi}{5}\\cdot 32 = \\frac{128\\pi}{5}$.',
        result: { latex: 'V = 2\\pi\\cdot\\tfrac{2}{5}x^{5/2}\\Big|_0^4 = \\tfrac{4\\pi}{5}\\cdot 32 = \\tfrac{128\\pi}{5}' },
        check: { kind: 'value', expected: '128*pi/5' },
      },
    ],
    final: {
      latex: 'V = \\frac{128\\pi}{5}',
      expr: '128*pi/5',
      check: { kind: 'definite-integral', integrand: '2*pi*x*sqrt(x)', lower: '0', upper: '4' },
      recap: 'About the y-axis, shells use vertical slices: $r = x$ (distance to the axis) and $h = \\sqrt{x}$ (top − bottom). Washers, $\\pi\\int_0^2 (16 - y^4)\\,dy$, give the same $\\frac{128\\pi}{5}$.',
    },
    tags: ['y-axis'],
  },

  // ───────────── vs-s-04: Example 4.4, √x about x = −1 ─────────────
  {
    id: 'vs-s-04',
    topic: 'volumes-shells',
    title: 'Moving the axis to x = −1',
    difficulty: 1,
    statement: {
      text: 'The region bounded by $y = \\sqrt{x}$, the x-axis, and $x = 4$ is now rotated about the line $x = -1$. Use cylindrical shells to find the volume.',
    },
    steps: [
      {
        prompt: 'Compared with rotating about the y-axis ($r = x$, $h = \\sqrt{x}$, $0 \\le x \\le 4$), what changes?',
        options: [
          { text: 'Only the height, which becomes $\\sqrt{x} + 1$', mistake: 'shell-height-wrong', why: 'Moving the axis changes distances to the axis (the radius), not the length of the slice.' },
          { text: 'Only the radius, which becomes $x - 1$', mistake: 'axis-shift-sign', why: 'The distance from x to the line x = −1 is x − (−1) = x + 1.' },
          { text: 'Only the radius, which becomes $x + 1$' },
          { text: 'Nothing changes: the radius is still $x$', mistake: 'axis-shift-missing', why: 'x is the distance to the y-axis; the new axis is one unit further left.' },
          { text: 'The slices must become horizontal', mistake: 'shell-orientation-wrong', why: 'x = −1 is a vertical line like the y-axis, so the shell slices stay vertical.' },
        ],
        correct: 2,
        explanation: 'The region and the slices are unchanged; only the distance from each slice to the axis grows by 1.',
        result: { text: 'Same vertical slices, $0 \\le x \\le 4$; new radius $x + 1$.' },
      },
      {
        prompt: 'What are the radius and height of the shell at position $x$?',
        options: [
          { latex: 'r = x - 1,\\quad h = \\sqrt{x}', expr: '[x - 1, sqrt(x)]', mistake: 'axis-shift-sign', why: 'The distance from x to the line x = −1 is x − (−1) = x + 1.' },
          { latex: 'r = x,\\quad h = \\sqrt{x} + 1', expr: '[x, sqrt(x) + 1]', mistake: 'shell-height-wrong', why: 'The shift was put into the height instead of the radius; the slice still runs from y = 0 to y = √x and sits x + 1 from the axis.' },
          { latex: 'r = x + 1,\\quad h = \\sqrt{x} + 1', expr: '[x + 1, sqrt(x) + 1]', mistake: 'shell-height-wrong', why: 'Moving the axis changes only the radius; the slice still runs from y = 0 up to y = √x.' },
          { latex: 'r = x,\\quad h = \\sqrt{x}', expr: '[x, sqrt(x)]', mistake: 'axis-shift-missing', why: 'x is the distance to the y-axis; the axis of rotation is x = −1.' },
          { latex: 'r = x + 1,\\quad h = \\sqrt{x}', expr: '[x + 1, sqrt(x)]' },
          { latex: 'r = x - 1,\\quad h = \\sqrt{x} + 1', expr: '[x - 1, sqrt(x) + 1]', mistake: 'axis-shift-sign', why: 'Two slips: the shift has the wrong sign (the radius is x + 1), and it was also added to the height.' },
        ],
        correct: 4,
        explanation: 'Radius = distance from the slice to $x = -1$: $x - (-1) = x + 1$; height = $\\sqrt{x} - 0$.',
        result: { latex: 'r = x + 1,\\quad h = \\sqrt{x}' },
        check: { kind: 'value', expected: '[x + 1, sqrt(x)]' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_0^4 2\\pi(x + 1)\\sqrt{x}\\,dx', expr: 'integral(2*pi*(x + 1)*sqrt(x), x, 0, 4)' },
          { latex: 'V = \\int_0^4 2\\pi(x - 1)\\sqrt{x}\\,dx', expr: 'integral(2*pi*(x - 1)*sqrt(x), x, 0, 4)', mistake: 'axis-shift-sign', why: 'The radius is x + 1; with x − 1 some shells would even have a negative radius.' },
          { latex: 'V = \\int_0^4 2\\pi(x + 1)^2\\sqrt{x}\\,dx', expr: 'integral(2*pi*(x + 1)^2*sqrt(x), x, 0, 4)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_0^4 \\pi(x + 1)\\sqrt{x}\\,dx', expr: 'integral(pi*(x + 1)*sqrt(x), x, 0, 4)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
          { latex: 'V = \\int_0^2 2\\pi(y + 1)(4 - y^2)\\,dy', expr: 'integral(2*pi*(y + 1)*(4 - y^2), y, 0, 2)', mistake: 'shell-orientation-wrong', why: 'Horizontal slices are perpendicular to x = −1; this integral is the volume about the horizontal line y = −1.' },
        ],
        correct: 0,
        explanation: '$V = \\int_0^4 2\\pi r h\\,dx$ with $r = x + 1$ and $h = \\sqrt{x}$.',
        result: { latex: 'V = \\int_0^4 2\\pi(x + 1)\\sqrt{x}\\,dx = 2\\pi\\int_0^4 \\left(x^{3/2} + x^{1/2}\\right)dx' },
        check: { kind: 'value', expected: 'integral(pi*(25 - (y^2 + 1)^2), y, 0, 2)' },
      },
      {
        prompt: 'Evaluate $2\\pi\\int_0^4 \\left(x^{3/2} + x^{1/2}\\right)dx$.',
        options: [
          { latex: 'V = \\frac{128\\pi}{5}', expr: '128*pi/5', mistake: 'algebra-error', why: 'Only the $x^{3/2}$ term was integrated; the $x^{1/2}$ term (worth 2π·16/3) was lost.' },
          { latex: 'V = \\frac{272\\pi}{15}', expr: '272*pi/15', mistake: 'coefficient-mishandled', why: 'The bracket is 64/5 + 16/3 = 272/15, so V = 2π·272/15; the factor 2 was lost.' },
          { latex: 'V = \\frac{224\\pi}{15}', expr: '224*pi/15', mistake: 'sign-error', why: 'The $x^{1/2}$ term was subtracted: 2π(64/5 − 16/3).' },
          { latex: 'V = 184\\pi', expr: '184*pi', mistake: 'power-rule-int-coefficient', why: 'The powers were multiplied by 5/2 and 3/2 instead of divided: 2π(80 + 12).' },
          { latex: 'V = \\frac{544\\pi}{15}', expr: '544*pi/15' },
        ],
        correct: 4,
        explanation: '$2\\pi\\left[\\frac{2}{5}x^{5/2} + \\frac{2}{3}x^{3/2}\\right]_0^4 = 2\\pi\\left(\\frac{64}{5} + \\frac{16}{3}\\right) = \\frac{544\\pi}{15}$.',
        result: { latex: 'V = 2\\pi\\left(\\tfrac{64}{5} + \\tfrac{16}{3}\\right) = 2\\pi\\cdot\\tfrac{272}{15} = \\tfrac{544\\pi}{15}' },
        check: { kind: 'value', expected: '544*pi/15' },
      },
    ],
    final: {
      latex: 'V = \\frac{544\\pi}{15}',
      expr: '544*pi/15',
      check: { kind: 'definite-integral', integrand: '2*pi*(x + 1)*sqrt(x)', lower: '0', upper: '4' },
      recap: 'Moving the axis to $x = -1$ only changes the radius: the distance from the slice at $x$ to the axis is $x - (-1) = x + 1$. The height and the limits come from the region, which did not move.',
    },
    tags: ['axis-shift'],
  },

  // ───────────── vs-s-05: e^x on [1, 2] about the y-axis ─────────────
  {
    id: 'vs-s-05',
    topic: 'volumes-shells',
    title: 'Keeping y = eˣ: shells about the y-axis',
    difficulty: 2,
    statement: {
      text: 'The region bounded by $y = e^x$, $y = 0$, $x = 1$, and $x = 2$ is rotated about the y-axis. Find the volume without rewriting the curve as $x = \\ln y$.',
    },
    steps: [
      {
        prompt: 'Shells about the y-axis use vertical slices. Where does the slice at position $x$ run?',
        options: [
          { text: 'From $y = e^x$ up to $y = e^2$', mistake: 'shell-height-wrong', why: 'That piece lies above the curve, outside the region.' },
          { text: 'From $x = \\ln y$ to $x = 2$', mistake: 'shell-orientation-wrong', why: 'That is a horizontal slice, perpendicular to the y-axis; it needs x = ln y and gives washers.' },
          { text: 'From $y = 0$ up to $y = e^x$' },
          { text: 'From $y = 1$ up to $y = e^x$', mistake: 'shell-height-wrong', why: 'The bottom of the region is y = 0; 1 is the x-value of its left edge.' },
          { text: 'From $y = 0$ up to $y = \\ln x$', mistake: 'inverse-function-wrong', why: 'ln is the inverse of the exponential; the top of the slice is on the curve y = eˣ itself.' },
        ],
        correct: 2,
        explanation: 'For each $x$ in $[1, 2]$ the region lies between $y = 0$ and $y = e^x$.',
        result: { text: 'Vertical slice at $x$, from $y = 0$ to $y = e^x$, $1 \\le x \\le 2$.' },
      },
      {
        prompt: 'What are the radius and height of the shell at position $x$?',
        options: [
          { latex: 'r = x,\\quad h = e^{x}', expr: '[x, exp(x)]' },
          { latex: 'r = x - 1,\\quad h = \\ln x', expr: '[x - 1, log(x)]', mistake: 'inverse-function-wrong', why: 'Two slips: ln x is the inverse of the curve (the top is y = eˣ), and x − 1 measures from the left edge x = 1 instead of the y-axis.' },
          { latex: 'r = x,\\quad h = e^{2} - e^{x}', expr: '[x, exp(2) - exp(x)]', mistake: 'shell-height-wrong', why: 'That measures from the curve up to y = e², which is above the region.' },
          { latex: 'r = x - 1,\\quad h = e^{x}', expr: '[x - 1, exp(x)]', mistake: 'shell-radius-wrong', why: 'x − 1 is the distance to the left edge x = 1 of the region; the radius is the distance x to the y-axis.' },
          { latex: 'r = x,\\quad h = \\ln x', expr: '[x, log(x)]', mistake: 'inverse-function-wrong', why: 'The top of the slice is on y = eˣ; ln x is the inverse function.' },
          { latex: 'r = x - 1,\\quad h = e^{2} - e^{x}', expr: '[x - 1, exp(2) - exp(x)]', mistake: 'shell-radius-wrong', why: 'Two slips: x − 1 measures from x = 1 instead of the y-axis, and e² − eˣ is the strip above the curve.' },
        ],
        correct: 0,
        explanation: 'Radius = distance from the slice to the y-axis = $x$; height = $e^x - 0$.',
        result: { latex: 'r = x,\\quad h = e^{x}' },
        check: { kind: 'value', expected: '[x, exp(x)]' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_1^2 \\pi(e^{x})^2\\,dx', expr: 'integral(pi*(exp(x))^2, x, 1, 2)', mistake: 'method-formula-swapped', why: 'That is the disk formula for slices perpendicular to the x-axis; it gives the x-axis solid.' },
          { latex: 'V = \\int_e^{e^2} 2\\pi x e^{x}\\,dx', expr: 'integral(2*pi*x*exp(x), x, e, e^2)', mistake: 'bounds-wrong-axis', why: 'e and e² are the heights of the curve at x = 1 and x = 2; the x-limits are 1 and 2.' },
          { latex: 'V = \\int_1^2 2\\pi x e^{x}\\,dx', expr: 'integral(2*pi*x*exp(x), x, 1, 2)' },
          { latex: 'V = \\int_1^2 2\\pi x^2 e^{x}\\,dx', expr: 'integral(2*pi*x^2*exp(x), x, 1, 2)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_1^2 \\pi x e^{x}\\,dx', expr: 'integral(pi*x*exp(x), x, 1, 2)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
        ],
        correct: 2,
        explanation: '$V = \\int_1^2 2\\pi r h\\,dx$ with $r = x$ and $h = e^x$ — one integral, no inverse function.',
        result: { latex: 'V = \\int_1^2 2\\pi x e^{x}\\,dx' },
        check: { kind: 'value', expected: 'integral(3*pi, y, 0, e) + integral(pi*(4 - log(y)^2), y, e, e^2)' },
      },
      {
        prompt: 'Integration by parts ($u = x$, $dv = e^x\\,dx$) gives $\\int x e^x\\,dx = (x - 1)e^x + C$. Evaluate $V$.',
        options: [
          { latex: 'V = 2\\pi(e^{2} - e)', expr: '2*pi*(e^2 - e)', mistake: 'arithmetic-error', why: 'F(1) was evaluated as e (as if x eˣ at x = 1) instead of (1 − 1)e = 0.' },
          { latex: 'V = 2\\pi(2e^{2} - e)', expr: '2*pi*(2*e^2 - e)', mistake: 'ibp-formula-wrong', why: 'Only uv = x eˣ was evaluated; the − ∫v du = − eˣ part was dropped.' },
          { latex: 'V = 2\\pi(3e^{2} - 2e)', expr: '2*pi*(3*e^2 - 2*e)', mistake: 'ibp-sign-error', why: 'Using (x + 1)eˣ, i.e. uv + ∫v du, gives 3e² − 2e.' },
          { latex: 'V = 2\\pi e^{2}', expr: '2*pi*e^2' },
          { latex: 'V = -2\\pi e^{2}', expr: '-2*pi*e^2', mistake: 'ftc-order-swapped', why: 'F(1) − F(2) was computed instead of F(2) − F(1).' },
        ],
        correct: 3,
        explanation: '$2\\pi\\left[(x - 1)e^x\\right]_1^2 = 2\\pi\\left(e^2 - 0\\right) = 2\\pi e^2$.',
        result: { latex: 'V = 2\\pi\\left[(x - 1)e^{x}\\right]_1^2 = 2\\pi(e^{2} - 0) = 2\\pi e^{2}' },
        check: { kind: 'value', expected: '2*pi*e^2' },
      },
    ],
    final: {
      latex: 'V = 2\\pi e^{2}',
      expr: '2*pi*e^2',
      check: { kind: 'definite-integral', integrand: '2*pi*x*exp(x)', lower: '1', upper: '2' },
      recap: 'Shells about the y-axis keep the curve as given: $r = x$, $h = e^x$, $1 \\le x \\le 2$. Washers would need $x = \\ln y$ and a split at $y = e$.',
    },
    tags: ['y-axis', 'method-selection'],
  },

  // ───────────── vs-s-06: y = x³, y = 8, x = 0 about x = −2 ─────────────
  {
    id: 'vs-s-06',
    topic: 'volumes-shells',
    title: 'Revolving about x = −2',
    difficulty: 2,
    statement: {
      text: 'The region bounded by $y = x^3$, $y = 8$, and $x = 0$ is revolved about the line $x = -2$. Use cylindrical shells to find the volume.',
    },
    steps: [
      {
        prompt: 'Shells about $x = -2$ use vertical slices, for $0 \\le x \\le 2$. Where does the slice at position $x$ run?',
        options: [
          { text: 'From $y = 0$ up to the curve $y = x^3$', mistake: 'shell-height-wrong', why: 'The region lies above the cubic (between y = x³ and y = 8), not under it.' },
          { text: 'From $y = 0$ up to $y = 8$', mistake: 'shell-height-wrong', why: 'The bottom of the slice is on the cubic y = x³, not on the x-axis.' },
          { text: 'From $x = 0$ to $x = \\sqrt[3]{y}$', mistake: 'shell-orientation-wrong', why: 'That is a horizontal slice, perpendicular to x = −2; it would sweep out a washer.' },
          { text: 'From the axis $x = -2$ to the curve', mistake: 'shell-radius-wrong', why: 'That segment is the radius (from the axis to the slice), not the slice itself.' },
          { text: 'From the curve $y = x^3$ up to the line $y = 8$' },
        ],
        correct: 4,
        explanation: 'For $0 \\le x \\le 2$ the region lies between the cubic $y = x^3$ (bottom) and the line $y = 8$ (top).',
        result: { text: 'Vertical slice at $x$: from $y = x^3$ to $y = 8$, $0 \\le x \\le 2$.' },
      },
      {
        prompt: 'What is the radius of the shell at position $x$?',
        options: [
          { latex: 'r = x - 2', expr: 'x - 2', mistake: 'axis-shift-sign', why: 'x − 2 is negative on 0 ≤ x ≤ 2; the distance from x to the line x = −2 is x − (−2) = x + 2.' },
          { latex: 'r = x', expr: 'x', mistake: 'axis-shift-missing', why: 'x is the distance to the y-axis; the axis of rotation is two units further left.' },
          { latex: 'r = x + 2', expr: 'x + 2' },
          { latex: 'r = 2 - x', expr: '2 - x', mistake: 'axis-shift-sign', why: '2 − x is the distance to the line x = 2, not to x = −2.' },
          { latex: 'r = 8 - x^3', expr: '8 - x^3', mistake: 'shell-radius-wrong', why: 'That is the length of the slice (the height), not its distance to the axis.' },
        ],
        correct: 2,
        explanation: 'The radius is the distance from the slice at $x$ to the line $x = -2$: $x - (-2) = x + 2$.',
        result: { latex: 'r = x + 2' },
        check: { kind: 'value', expected: 'x + 2' },
      },
      {
        prompt: 'What is the height of the shell at position $x$?',
        options: [
          { latex: 'h = x^3', expr: 'x^3', mistake: 'shell-height-wrong', why: 'The region lies above the cubic; x³ is the part below it.' },
          { latex: 'h = x^3 - 8', expr: 'x^3 - 8', mistake: 'top-bottom-swapped', why: 'Bottom minus top gives a negative height; the top is y = 8.' },
          { latex: 'h = 8', expr: '8', mistake: 'shell-height-wrong', why: 'That ignores the lower boundary y = x³.' },
          { latex: 'h = 8 - \\sqrt[3]{x}', expr: '8 - nthRoot(x, 3)', mistake: 'inverse-function-wrong', why: 'The cube root belongs to the inverse x = ∛y; the bottom of the vertical slice is at y = x³.' },
          { latex: 'h = 8 - x^3', expr: '8 - x^3' },
          { latex: 'h = \\sqrt[3]{y}', expr: 'nthRoot(y, 3)', mistake: 'not-in-terms-of-variable', why: '∛y is the length of a horizontal slice; shells in x need a height written in x.' },
        ],
        correct: 4,
        explanation: 'Height = top − bottom = $8 - x^3$.',
        result: { latex: 'h = 8 - x^3' },
        check: { kind: 'value', expected: '8 - x^3' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_0^2 2\\pi(x + 2)x^3\\,dx', expr: 'integral(2*pi*(x + 2)*x^3, x, 0, 2)', mistake: 'shell-height-wrong', why: 'The height is 8 − x³; x³ is the part under the curve, outside the region.' },
          { latex: 'V = \\int_0^2 2\\pi x(8 - x^3)\\,dx', expr: 'integral(2*pi*x*(8 - x^3), x, 0, 2)', mistake: 'axis-shift-missing', why: 'That rotates about the y-axis; the radius about x = −2 is x + 2.' },
          { latex: 'V = \\int_0^2 2\\pi(x + 2)(8 - x^3)\\,dx', expr: 'integral(2*pi*(x + 2)*(8 - x^3), x, 0, 2)' },
          { latex: 'V = \\int_0^2 2\\pi(x + 2)^2(8 - x^3)\\,dx', expr: 'integral(2*pi*(x + 2)^2*(8 - x^3), x, 0, 2)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_0^8 2\\pi(x + 2)(8 - x^3)\\,dx', expr: 'integral(2*pi*(x + 2)*(8 - x^3), x, 0, 8)', mistake: 'bounds-wrong-axis', why: '8 is the top y-value; the region spans 0 ≤ x ≤ 2.' },
          { latex: 'V = \\int_0^2 \\pi(x + 2)(8 - x^3)\\,dx', expr: 'integral(pi*(x + 2)*(8 - x^3), x, 0, 2)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
        ],
        correct: 2,
        explanation: '$V = \\int_0^2 2\\pi r h\\,dx$ with $r = x + 2$ and $h = 8 - x^3$ — a single integral.',
        result: { latex: 'V = \\int_0^2 2\\pi(x + 2)(8 - x^3)\\,dx = 2\\pi\\int_0^2 \\left(16 + 8x - 2x^3 - x^4\\right)dx' },
        check: { kind: 'value', expected: 'integral(pi*((nthRoot(y, 3) + 2)^2 - 4), y, 0, 8)' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\frac{168\\pi}{5}', expr: '168*pi/5', mistake: 'coefficient-mishandled', why: 'The bracket is 168/5, so V = 2π·168/5; the factor 2 was lost.' },
          { latex: 'V = \\frac{96\\pi}{5}', expr: '96*pi/5', mistake: 'algebra-error', why: 'Only x(8 − x³) survived the expansion; the 2(8 − x³) = 16 − 2x³ part was lost.' },
          { latex: 'V = \\frac{496\\pi}{5}', expr: '496*pi/5', mistake: 'sign-error', why: 'In the expansion −2x³ became +2x³.' },
          { latex: 'V = 144\\pi', expr: '144*pi', mistake: 'product-rule-integral', why: 'The factors were integrated separately and multiplied: 2π·6·12; there is no product rule for integrals.' },
          { latex: 'V = \\frac{336\\pi}{5}', expr: '336*pi/5' },
        ],
        correct: 4,
        explanation: '$2\\pi\\left[16x + 4x^2 - \\frac{x^4}{2} - \\frac{x^5}{5}\\right]_0^2 = 2\\pi\\left(32 + 16 - 8 - \\frac{32}{5}\\right) = \\frac{336\\pi}{5}$.',
        result: { latex: 'V = 2\\pi\\left[16x + 4x^2 - \\tfrac{x^4}{2} - \\tfrac{x^5}{5}\\right]_0^2 = 2\\pi\\cdot\\tfrac{168}{5} = \\tfrac{336\\pi}{5}' },
        check: { kind: 'value', expected: '336*pi/5' },
      },
    ],
    final: {
      latex: 'V = \\frac{336\\pi}{5}',
      expr: '336*pi/5',
      check: { kind: 'definite-integral', integrand: '2*pi*(x + 2)*(8 - x^3)', lower: '0', upper: '2' },
      recap: 'About $x = -2$, shells use vertical slices: $r = x - (-2) = x + 2$ and $h$ = top − bottom $= 8 - x^3$. One integral; washers in $y$ ($R = \\sqrt[3]{y} + 2$, $r = 2$) give the same $\\frac{336\\pi}{5}$.',
    },
    tags: ['axis-shift'],
  },

  // ───────────── vs-s-07: √x + 1 and x² + 1 about the x-axis (shells vs washers) ─────────────
  {
    id: 'vs-s-07',
    topic: 'volumes-shells',
    title: 'Shells vs. washers for y = √x + 1 and y = x² + 1',
    difficulty: 2,
    statement: {
      text: 'The region between $y = \\sqrt{x} + 1$ and $y = x^2 + 1$ (they meet at $(0, 1)$ and $(1, 2)$) is rotated about the x-axis. Find the volume with cylindrical shells, then compare with washers.',
    },
    variable: 'y',
    steps: [
      {
        prompt: 'Shells about the x-axis use horizontal slices, so both curves must be written as $x$ in terms of $y$. At height $y$ ($1 \\le y \\le 2$), where does the slice start and end?',
        options: [
          { text: 'Left end $x = (y - 1)^2$, right end $x = \\sqrt{y - 1}$' },
          { text: 'Left end $x = \\sqrt{y - 1}$, right end $x = (y - 1)^2$', mistake: 'top-bottom-swapped', why: 'For 1 < y < 2, (y − 1)² < √(y − 1), so (y − 1)² is the left end.' },
          { text: 'Left end $x = y^2 - 1$, right end $x = \\sqrt{y} - 1$', mistake: 'inverse-function-wrong', why: 'Subtract 1 before inverting: y = √x + 1 gives x = (y − 1)², not y² − 1.' },
          { text: 'Left end $x = (y + 1)^2$, right end $x = \\sqrt{y + 1}$', mistake: 'inverse-function-wrong', why: 'The shift has the wrong sign: y − 1 = √x and y − 1 = x², so x = (y − 1)² and x = √(y − 1).' },
          { text: 'Left end $x = 0$, right end $x = \\sqrt{y - 1}$', mistake: 'shell-height-wrong', why: 'The slice starts on the other curve, x = (y − 1)², not on the y-axis.' },
        ],
        correct: 0,
        explanation: 'From $y = \\sqrt{x} + 1$: $x = (y - 1)^2$; from $y = x^2 + 1$: $x = \\sqrt{y - 1}$; for $1 < y < 2$ the first is smaller.',
        result: { latex: 'x = (y - 1)^2 \\text{ (left)},\\quad x = \\sqrt{y - 1} \\text{ (right)},\\quad 1 \\le y \\le 2' },
      },
      {
        prompt: 'Set up the shell integral.',
        options: [
          { latex: 'V = \\int_1^2 \\pi y\\left(\\sqrt{y - 1} - (y - 1)^2\\right)\\,dy', expr: 'integral(pi*y*(sqrt(y - 1) - (y - 1)^2), y, 1, 2)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
          { latex: 'V = \\int_1^2 2\\pi y\\left((y - 1)^2 - \\sqrt{y - 1}\\right)\\,dy', expr: 'integral(2*pi*y*((y - 1)^2 - sqrt(y - 1)), y, 1, 2)', mistake: 'top-bottom-swapped', why: 'Left minus right gives a negative height; the height is right minus left.' },
          { latex: 'V = \\int_1^2 2\\pi(y - 1)\\left(\\sqrt{y - 1} - (y - 1)^2\\right)\\,dy', expr: 'integral(2*pi*(y - 1)*(sqrt(y - 1) - (y - 1)^2), y, 1, 2)', mistake: 'shell-radius-wrong', why: 'y − 1 is the distance to the bottom of the region (y = 1); the radius is the distance y to the x-axis.' },
          { latex: 'V = \\int_1^2 2\\pi y\\left(\\sqrt{y - 1} - (y - 1)^2\\right)\\,dy', expr: 'integral(2*pi*y*(sqrt(y - 1) - (y - 1)^2), y, 1, 2)' },
          { latex: 'V = \\int_1^2 \\pi\\left(\\sqrt{y - 1} - (y - 1)^2\\right)^2\\,dy', expr: 'integral(pi*(sqrt(y - 1) - (y - 1)^2)^2, y, 1, 2)', mistake: 'method-formula-swapped', why: 'π(length)² is a disk formula; a horizontal slice is parallel to the x-axis and sweeps out a shell.' },
          { latex: 'V = \\int_1^2 2\\pi y^2\\left(\\sqrt{y - 1} - (y - 1)^2\\right)\\,dy', expr: 'integral(2*pi*y^2*(sqrt(y - 1) - (y - 1)^2), y, 1, 2)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
        ],
        correct: 3,
        explanation: '$r = y$ (distance to the x-axis), $h$ = right − left $= \\sqrt{y - 1} - (y - 1)^2$, $1 \\le y \\le 2$.',
        result: { latex: 'V = \\int_1^2 2\\pi y\\left(\\sqrt{y - 1} - (y - 1)^2\\right)dy' },
        check: { kind: 'value', expected: 'integral(pi*((sqrt(x) + 1)^2 - (x^2 + 1)^2), x, 0, 1)' },
      },
      {
        prompt: 'Substitute $u = y - 1$. Which integral results?',
        options: [
          { latex: '2\\pi\\int_1^2 (u + 1)(\\sqrt{u} - u^2)\\,du', expr: '2*pi*integral((u + 1)*(sqrt(u) - u^2), u, 1, 2)', mistake: 'bounds-not-converted', why: 'The y-limits 1 and 2 must become u = 0 and u = 1.' },
          { latex: '2\\pi\\int_0^1 u(\\sqrt{u} - u^2)\\,du', expr: '2*pi*integral(u*(sqrt(u) - u^2), u, 0, 1)', mistake: 'phantom-axis-shift', why: 'Writing the radius as u measures from y = 1, as if the axis were y = 1; the radius (distance to the x-axis) is y = u + 1.' },
          { latex: '2\\pi\\int_0^1 (u - 1)(\\sqrt{u} - u^2)\\,du', expr: '2*pi*integral((u - 1)*(sqrt(u) - u^2), u, 0, 1)', mistake: 'sign-error', why: 'From u = y − 1 we get y = u + 1, not u − 1.' },
          { latex: '2\\pi\\int_0^1 (u + 1)(\\sqrt{u} - u^2)\\,du', expr: '2*pi*integral((u + 1)*(sqrt(u) - u^2), u, 0, 1)' },
          { latex: '\\pi\\int_0^1 (u + 1)(\\sqrt{u} - u^2)\\,du', expr: 'pi*integral((u + 1)*(sqrt(u) - u^2), u, 0, 1)', mistake: 'coefficient-mishandled', why: 'du = dy, so no constant changes; the factor 2 of 2π must stay.' },
        ],
        correct: 3,
        explanation: '$y = u + 1$, $dy = du$, and the limits $y = 1, 2$ become $u = 0, 1$.',
        result: { latex: 'V = 2\\pi\\int_0^1 (u + 1)(\\sqrt{u} - u^2)\\,du = 2\\pi\\int_0^1 \\left(u^{3/2} - u^3 + u^{1/2} - u^2\\right)du' },
        check: { kind: 'value', expected: 'integral(2*pi*y*(sqrt(y - 1) - (y - 1)^2), y, 1, 2)' },
      },
      {
        prompt: 'Evaluate $2\\pi\\int_0^1 \\left(u^{3/2} - u^3 + u^{1/2} - u^2\\right)du$.',
        options: [
          { latex: 'V = \\frac{29\\pi}{60}', expr: '29*pi/60', mistake: 'coefficient-mishandled', why: 'The bracket is 29/60, so V = 2π·29/60; the factor 2 was lost.' },
          { latex: 'V = \\frac{41\\pi}{6}', expr: '41*pi/6', mistake: 'power-rule-int-coefficient', why: 'The fractional powers were multiplied by 5/2 and 3/2 instead of divided: 2π(5/2 − 1/4 + 3/2 − 1/3).' },
          { latex: 'V = \\frac{29\\pi}{30}', expr: '29*pi/30' },
          { latex: 'V = \\frac{33\\pi}{10}', expr: '33*pi/10', mistake: 'sign-error', why: 'All four terms were added: 2π(2/5 + 1/4 + 2/3 + 1/3).' },
          { latex: 'V = \\frac{3\\pi}{10}', expr: '3*pi/10', mistake: 'algebra-error', why: 'Only u(√u − u²) was integrated; the 1·(√u − u²) part, worth 1/3, was dropped.' },
        ],
        correct: 2,
        explanation: '$2\\pi\\left(\\frac{2}{5} - \\frac{1}{4} + \\frac{2}{3} - \\frac{1}{3}\\right) = 2\\pi\\cdot\\frac{29}{60} = \\frac{29\\pi}{30}$.',
        result: { latex: 'V = 2\\pi\\left(\\tfrac{2}{5} - \\tfrac{1}{4} + \\tfrac{2}{3} - \\tfrac{1}{3}\\right) = 2\\pi\\cdot\\tfrac{29}{60} = \\tfrac{29\\pi}{30}' },
        check: { kind: 'value', expected: '29*pi/30' },
      },
      {
        prompt: 'Washers give the same $\\frac{29\\pi}{30}$. Which setup is less work for this region?',
        options: [
          { text: 'Shells in $y$: shells are always less work', mistake: 'method-choice-poor', why: 'Here the shell setup forced us to invert both curves; washers use them as given.' },
          { text: 'Washers in $y$: horizontal slices keep the curves as given', mistake: 'method-formula-swapped', why: 'Horizontal slices are parallel to the x-axis, so they sweep out shells, not washers.' },
          { text: 'Washers in $x$: the two curves are already functions of $x$' },
          { text: 'Shells in $x$: vertical slices avoid inverting the curves', mistake: 'shell-orientation-wrong', why: 'Vertical slices are perpendicular to the x-axis, so they sweep out washers, not shells.' },
          { text: 'Disks in $x$: the region touches the axis', mistake: 'washer-as-disk', why: 'The region lies above y = 1, so each vertical slice leaves a hole around the axis.' },
        ],
        correct: 2,
        explanation: 'Washers in $x$: $V = \\pi\\int_0^1 \\left((\\sqrt{x} + 1)^2 - (x^2 + 1)^2\\right)dx$ uses both curves exactly as given.',
        result: { latex: 'V = \\pi\\int_0^1 \\left((\\sqrt{x} + 1)^2 - (x^2 + 1)^2\\right)dx = \\tfrac{29\\pi}{30}' },
      },
    ],
    final: {
      latex: 'V = \\frac{29\\pi}{30}',
      expr: '29*pi/30',
      check: { kind: 'definite-integral', integrand: '2*pi*y*(sqrt(y - 1) - (y - 1)^2)', lower: '1', upper: '2' },
      recap: 'Horizontal slices forced both curves to be solved for $x$: $x = (y - 1)^2$ (left) and $x = \\sqrt{y - 1}$ (right). Shells give $\\frac{29\\pi}{30}$, the same as washers in $x$, which avoid the inverses.',
    },
    tags: ['x-axis', 'method-selection'],
  },

  // ───────────── vs-s-08: method selection with y = ln x ─────────────
  {
    id: 'vs-s-08',
    topic: 'volumes-shells',
    title: 'Choosing the method: y = ln x about the y-axis',
    difficulty: 2,
    statement: {
      text: 'Let $R$ be the region bounded by $y = \\ln x$, $y = 0$, and $x = 3$. Find the volume of the solid obtained by rotating $R$ about the y-axis.',
    },
    steps: [
      {
        prompt: 'Which setup avoids rewriting $y = \\ln x$ as $x = e^y$?',
        options: [
          { text: 'Washers: horizontal slices, integrate in $y$ from 0 to $\\ln 3$', mistake: 'method-choice-poor', why: 'Horizontal slices run from x = e^y to x = 3, so the curve must be rewritten as x = e^y.' },
          { text: 'Disks: vertical slices, integrate in $x$ from 1 to 3', mistake: 'method-formula-swapped', why: 'Vertical slices are parallel to the y-axis; they sweep out shells, not disks.' },
          { text: 'Shells: horizontal slices, integrate in $y$ from 0 to $\\ln 3$', mistake: 'shell-orientation-wrong', why: 'Horizontal slices are perpendicular to the y-axis; shell slices must be parallel to it.' },
          { text: 'Shells: vertical slices, integrate in $x$ from 1 to 3' },
          { text: 'Shells: vertical slices, integrate in $x$ from 0 to 3', mistake: 'bounds-from-axis', why: 'The integral was started at the axis x = 0; R starts at x = 1, where ln x = 0 (for 0 < x < 1, ln x is negative).' },
        ],
        correct: 3,
        explanation: 'Vertical slices are parallel to the y-axis (shells) and use $y = \\ln x$ as given; $R$ starts where $\\ln x = 0$, at $x = 1$.',
        result: { text: 'Shells: vertical slices, $1 \\le x \\le 3$.' },
      },
      {
        prompt: 'What are the radius and height of the shell at position $x$?',
        options: [
          { latex: 'r = 3 - x,\\quad h = e^{x}', expr: '[3 - x, exp(x)]', mistake: 'inverse-function-wrong', why: 'Two slips: eˣ is the inverse of ln (the top is y = ln x), and 3 − x measures to x = 3 instead of the y-axis.' },
          { latex: 'r = x,\\quad h = \\ln 3 - \\ln x', expr: '[x, log(3) - log(x)]', mistake: 'shell-height-wrong', why: 'That measures from the curve up to y = ln 3, above the curve and outside R.' },
          { latex: 'r = x,\\quad h = \\ln x', expr: '[x, log(x)]' },
          { latex: 'r = 3 - x,\\quad h = \\ln x', expr: '[3 - x, log(x)]', mistake: 'shell-radius-wrong', why: '3 − x is the distance to the right edge x = 3 of R; the radius is the distance x to the y-axis.' },
          { latex: 'r = x,\\quad h = e^{x}', expr: '[x, exp(x)]', mistake: 'inverse-function-wrong', why: 'eˣ is the inverse of ln; the top of the slice is on y = ln x.' },
          { latex: 'r = 3 - x,\\quad h = \\ln 3 - \\ln x', expr: '[3 - x, log(3) - log(x)]', mistake: 'shell-radius-wrong', why: 'Two slips: 3 − x measures to x = 3 instead of the y-axis, and ln 3 − ln x is the strip above the curve.' },
        ],
        correct: 2,
        explanation: 'The slice at $x$ runs from $y = 0$ up to $y = \\ln x$ and lies $x$ units from the y-axis.',
        result: { latex: 'r = x,\\quad h = \\ln x' },
        check: { kind: 'value', expected: '[x, log(x)]' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_0^3 2\\pi x\\ln x\\,dx', expr: 'integral(2*pi*x*log(x), x, 0, 3)', mistake: 'bounds-from-axis', why: 'The integral was started at the axis x = 0; R starts at x = 1, where ln x = 0 (for 0 < x < 1, ln x is negative).' },
          { latex: 'V = \\int_1^3 2\\pi x\\ln x\\,dx', expr: 'integral(2*pi*x*log(x), x, 1, 3)' },
          { latex: 'V = \\int_0^{\\ln 3} 2\\pi x\\ln x\\,dx', expr: 'integral(2*pi*x*log(x), x, 0, log(3))', mistake: 'bounds-wrong-axis', why: '0 and ln 3 are the y-limits; the vertical slices run from x = 1 to x = 3.' },
          { latex: 'V = \\int_1^3 \\pi(\\ln x)^2\\,dx', expr: 'integral(pi*(log(x))^2, x, 1, 3)', mistake: 'method-formula-swapped', why: 'That is the disk formula for slices perpendicular to the x-axis; it gives the x-axis solid.' },
          { latex: 'V = \\int_1^3 2\\pi x^2\\ln x\\,dx', expr: 'integral(2*pi*x^2*log(x), x, 1, 3)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_1^3 \\pi x\\ln x\\,dx', expr: 'integral(pi*x*log(x), x, 1, 3)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
        ],
        correct: 1,
        explanation: '$V = \\int_1^3 2\\pi r h\\,dx$ with $r = x$ and $h = \\ln x$.',
        result: { latex: 'V = \\int_1^3 2\\pi x\\ln x\\,dx' },
        check: { kind: 'value', expected: 'integral(pi*(9 - exp(2*y)), y, 0, log(3))' },
      },
      {
        prompt: 'Integrate by parts with $u = \\ln x$, $dv = x\\,dx$. What is $\\int x\\ln x\\,dx$?',
        options: [
          { latex: '\\frac{x^2}{2}\\ln x + \\frac{x^2}{4} + C', expr: 'x^2/2*log(x) + x^2/4 + C', mistake: 'ibp-sign-error', why: 'The formula is uv − ∫v du; the ∫v du = x²/4 term must be subtracted.' },
          { latex: '\\frac{x^2}{2}\\ln x - \\frac{x^2}{2} + C', expr: 'x^2/2*log(x) - x^2/2 + C', mistake: 'power-rule-int-coefficient', why: '∫v du = ∫(x/2) dx = x²/4, not x²/2.' },
          { latex: '\\frac{x^2}{2}\\ln x - \\frac{x^3}{6} + C', expr: 'x^2/2*log(x) - x^3/6 + C', mistake: 'ibp-du-wrong', why: 'd(ln x) = dx/x, not dx; with du = dx the leftover integral became ∫x²/2 dx.' },
          { latex: 'x\\ln x - x + C', expr: 'x*log(x) - x + C', mistake: 'ibp-incomplete-dv', why: 'That is ∫ln x dx; the factor x was left out of dv.' },
          { latex: '\\frac{x^2}{2}\\ln x + C', expr: 'x^2/2*log(x) + C', mistake: 'ibp-formula-wrong', why: 'Only uv was kept; the − ∫v du term is missing.' },
          { latex: '\\frac{x^2}{2}\\ln x - \\frac{x^2}{4} + C', expr: 'x^2/2*log(x) - x^2/4 + C' },
        ],
        correct: 5,
        explanation: '$du = \\frac{dx}{x}$, $v = \\frac{x^2}{2}$: $\\frac{x^2}{2}\\ln x - \\int \\frac{x}{2}\\,dx = \\frac{x^2}{2}\\ln x - \\frac{x^2}{4} + C$.',
        result: { latex: '\\int x\\ln x\\,dx = \\frac{x^2}{2}\\ln x - \\frac{x^2}{4} + C' },
        check: { kind: 'antiderivative', integrand: 'x*log(x)' },
      },
      {
        prompt: 'Evaluate $V = 2\\pi\\left[\\frac{x^2}{2}\\ln x - \\frac{x^2}{4}\\right]_1^3$.',
        options: [
          { latex: 'V = \\pi\\left(9\\ln 3 - \\frac{9}{2}\\right)', expr: 'pi*(9*log(3) - 9/2)', mistake: 'ftc-not-subtracted', why: 'The value at x = 1, which is −1/4, was never subtracted.' },
          { latex: 'V = \\pi(9\\ln 3 + 4)', expr: 'pi*(9*log(3) + 4)', mistake: 'ibp-sign-error', why: 'With +x²/4 in the antiderivative the bracket becomes (9/2)ln 3 + 2.' },
          { latex: 'V = \\frac{\\pi}{2}(9\\ln 3 - 4)', expr: 'pi/2*(9*log(3) - 4)', mistake: 'coefficient-mishandled', why: 'The bracket is (9/2)ln 3 − 2, so V = 2π times it; the factor 2 was lost.' },
          { latex: 'V = \\pi(9\\ln 3 - 4)', expr: 'pi*(9*log(3) - 4)' },
          { latex: 'V = \\pi(9\\ln 3 - 8)', expr: 'pi*(9*log(3) - 8)', mistake: 'power-rule-int-coefficient', why: 'Using x²/2 instead of x²/4 for ∫(x/2) dx gives the bracket (9/2)ln 3 − 4.' },
        ],
        correct: 3,
        explanation: '$2\\pi\\left[\\left(\\frac{9}{2}\\ln 3 - \\frac{9}{4}\\right) - \\left(0 - \\frac{1}{4}\\right)\\right] = 2\\pi\\left(\\frac{9}{2}\\ln 3 - 2\\right) = \\pi(9\\ln 3 - 4)$.',
        result: { latex: 'V = 2\\pi\\left(\\tfrac{9}{2}\\ln 3 - 2\\right) = \\pi(9\\ln 3 - 4)' },
        check: { kind: 'value', expected: 'pi*(9*log(3) - 4)' },
      },
    ],
    final: {
      latex: 'V = \\pi(9\\ln 3 - 4)',
      expr: 'pi*(9*log(3) - 4)',
      check: { kind: 'definite-integral', integrand: '2*pi*x*log(x)', lower: '1', upper: '3' },
      recap: 'Shells keep $y = \\ln x$ as given ($r = x$, $h = \\ln x$, $1 \\le x \\le 3$) and integration by parts finishes it. Washers with $x = e^y$ give the same $\\pi(9\\ln 3 - 4)$.',
    },
    tags: ['y-axis', 'method-selection'],
  },

  // ───────────── vs-s-09: Level III — one integral instead of two ─────────────
  {
    id: 'vs-s-09',
    topic: 'volumes-shells',
    title: 'One integral instead of two',
    difficulty: 2,
    statement: {
      text: 'Let $R$ be the region bounded by $x = 2$, $x = 4$, $y = 1$, and $x = 2 + \\sqrt{y - 3}$ (the curve runs from $(2, 3)$ to $(4, 7)$). Write a single integral for the volume when $R$ is rotated about the y-axis, and evaluate it.',
    },
    steps: [
      {
        prompt: 'Why do shells give the volume as a single integral here?',
        options: [
          { text: 'Shells never need more than one integral', mistake: 'volume-two-integrals-missed', why: 'False in general: about the x-axis this same region needs two shell integrals, split at y = 3.' },
          { text: 'Every horizontal slice runs from $x = 2$ to $x = 4$', mistake: 'volume-two-integrals-missed', why: 'Only for 1 ≤ y ≤ 3; above y = 3 the slice starts at the curve, which is why washers need a split.' },
          { text: 'Every vertical slice runs from $y = 1$ up to the curve' },
          { text: 'Washers would need slices parallel to the y-axis', mistake: 'method-formula-swapped', why: 'Washer slices are perpendicular to the axis (horizontal here); parallel slices give shells.' },
          { text: 'The curve cannot be solved for $y$', mistake: 'inverse-function-wrong', why: 'It can: x = 2 + √(y − 3) gives y = (x − 2)² + 3 for 2 ≤ x ≤ 4.' },
        ],
        correct: 2,
        explanation: 'The bottom ($y = 1$) and the top (the curve) of a vertical slice keep the same formulas for all $2 \\le x \\le 4$.',
        result: { text: 'Shells: vertical slices, $2 \\le x \\le 4$, one integral.' },
      },
      {
        prompt: 'Rewrite the curve $x = 2 + \\sqrt{y - 3}$ as $y$ in terms of $x$.',
        options: [
          { latex: 'y = (x + 2)^2 + 3', expr: '(x + 2)^2 + 3', mistake: 'inverse-function-wrong', why: 'Subtract 2 first: x − 2 = √(y − 3), so y = (x − 2)² + 3.' },
          { latex: 'y = (x - 2)^2 - 3', expr: '(x - 2)^2 - 3', mistake: 'sign-error', why: 'From (x − 2)² = y − 3, add 3 to both sides: y = (x − 2)² + 3.' },
          { latex: 'y = (x - 2)^2 + 3', expr: '(x - 2)^2 + 3' },
          { latex: 'y = \\sqrt{x - 2} + 3', expr: 'sqrt(x - 2) + 3', mistake: 'inverse-function-wrong', why: 'x and y were swapped inside the formula instead of solving for y.' },
          { latex: 'y = x + 1', expr: 'x + 1', mistake: 'algebra-error', why: '√(y − 3) = x − 2 gives y − 3 = (x − 2)²; the square was dropped.' },
        ],
        correct: 2,
        explanation: '$x - 2 = \\sqrt{y - 3} \\Rightarrow (x - 2)^2 = y - 3 \\Rightarrow y = (x - 2)^2 + 3$.',
        result: { latex: 'y = (x - 2)^2 + 3,\\quad 2 \\le x \\le 4' },
        domain: [2.2, 3.8],
        check: { kind: 'value', expected: '(x - 2)^2 + 3' },
      },
      {
        prompt: 'What are the radius and height of the shell at position $x$?',
        options: [
          { latex: 'r = x - 2,\\quad h = (x - 2)^2 + 2', expr: '[x - 2, (x - 2)^2 + 2]', mistake: 'shell-radius-wrong', why: 'x − 2 is the distance to the left edge x = 2 of R; the radius is the distance x to the y-axis.' },
          { latex: 'r = x,\\quad h = (x - 2)^2 + 3', expr: '[x, (x - 2)^2 + 3]', mistake: 'shell-height-wrong', why: 'That is the top y-value; the slice starts at y = 1, so subtract 1.' },
          { latex: 'r = x - 2,\\quad h = 4 - (x - 2)^2', expr: '[x - 2, 4 - (x - 2)^2]', mistake: 'shell-height-wrong', why: 'Two slips: 4 − (x − 2)² is the strip from the curve up to y = 7 (outside R), and x − 2 measures from x = 2 instead of the y-axis.' },
          { latex: 'r = x,\\quad h = (x - 2)^2 + 2', expr: '[x, (x - 2)^2 + 2]' },
          { latex: 'r = x,\\quad h = 4 - (x - 2)^2', expr: '[x, 4 - (x - 2)^2]', mistake: 'shell-height-wrong', why: 'That measures from the curve up to y = 7, which is outside R.' },
          { latex: 'r = x - 2,\\quad h = (x - 2)^2 + 3', expr: '[x - 2, (x - 2)^2 + 3]', mistake: 'shell-radius-wrong', why: 'Two slips: x − 2 measures from x = 2 instead of the y-axis, and y = 1 was not subtracted from the height.' },
        ],
        correct: 3,
        explanation: 'Height = top − bottom = $(x - 2)^2 + 3 - 1$; radius = distance to the y-axis = $x$.',
        result: { latex: 'r = x,\\quad h = (x - 2)^2 + 2' },
        check: { kind: 'value', expected: '[x, (x - 2)^2 + 2]' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_2^4 2\\pi x\\left((x - 2)^2 + 3\\right)\\,dx', expr: 'integral(2*pi*x*((x - 2)^2 + 3), x, 2, 4)', mistake: 'shell-height-wrong', why: 'The bottom boundary y = 1 was not subtracted from the height.' },
          { latex: 'V = \\int_1^7 2\\pi x\\left((x - 2)^2 + 2\\right)\\,dx', expr: 'integral(2*pi*x*((x - 2)^2 + 2), x, 1, 7)', mistake: 'bounds-wrong-axis', why: '1 and 7 are the lowest and highest y-values; the x-limits are 2 and 4.' },
          { latex: 'V = \\int_2^4 \\pi\\left((x - 2)^2 + 2\\right)^2\\,dx', expr: 'integral(pi*((x - 2)^2 + 2)^2, x, 2, 4)', mistake: 'method-formula-swapped', why: 'π(length)² is a disk formula; a vertical slice is parallel to the y-axis and sweeps out a shell.' },
          { latex: 'V = \\int_2^4 2\\pi x^2\\left((x - 2)^2 + 2\\right)\\,dx', expr: 'integral(2*pi*x^2*((x - 2)^2 + 2), x, 2, 4)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_2^4 2\\pi x\\left((x - 2)^2 + 2\\right)\\,dx', expr: 'integral(2*pi*x*((x - 2)^2 + 2), x, 2, 4)' },
        ],
        correct: 4,
        explanation: '$V = \\int_2^4 2\\pi r h\\,dx$ with $r = x$ and $h = (x - 2)^2 + 2$ — a single integral.',
        result: { latex: 'V = \\int_2^4 2\\pi x\\left((x - 2)^2 + 2\\right)dx' },
        check: { kind: 'value', expected: 'integral(pi*(16 - 4), y, 1, 3) + integral(pi*(16 - (2 + sqrt(y - 3))^2), y, 3, 7)' },
      },
      {
        prompt: 'Evaluate the integral (substitute $t = x - 2$).',
        options: [
          { latex: 'V = \\frac{64\\pi}{3}', expr: '64*pi/3', mistake: 'coefficient-mishandled', why: 'The bracket is 64/3, so V = 2π·64/3; the factor 2 was lost.' },
          { latex: 'V = \\frac{704\\pi}{3}', expr: '704*pi/3', mistake: 'bounds-not-converted', why: 'With t = x − 2 the limits 2 and 4 become 0 and 2; the x-limits were kept.' },
          { latex: 'V = 16\\pi', expr: '16*pi', mistake: 'shell-radius-wrong', why: 'After t = x − 2 the radius x becomes t + 2; writing t measures from x = 2 instead of from the y-axis.' },
          { latex: 'V = \\frac{128\\pi}{3}', expr: '128*pi/3' },
          { latex: 'V = \\frac{104\\pi}{3}', expr: '104*pi/3', mistake: 'algebra-error', why: '(t + 2)(t² + 2) = t³ + 2t² + 2t + 4; the 2t term was dropped.' },
        ],
        correct: 3,
        explanation: '$2\\pi\\int_0^2 (t + 2)(t^2 + 2)\\,dt = 2\\pi\\left[\\frac{t^4}{4} + \\frac{2t^3}{3} + t^2 + 4t\\right]_0^2 = 2\\pi\\cdot\\frac{64}{3} = \\frac{128\\pi}{3}$.',
        result: { latex: 'V = 2\\pi\\int_0^2 (t + 2)(t^2 + 2)\\,dt = 2\\pi\\left(4 + \\tfrac{16}{3} + 4 + 8\\right) = \\tfrac{128\\pi}{3}' },
        check: { kind: 'value', expected: '128*pi/3' },
      },
    ],
    final: {
      latex: 'V = \\frac{128\\pi}{3}',
      expr: '128*pi/3',
      check: { kind: 'definite-integral', integrand: '2*pi*x*((x - 2)^2 + 2)', lower: '2', upper: '4' },
      recap: 'Every vertical slice runs from $y = 1$ up to the curve, so shells need one integral: $r = x$, $h = (x - 2)^2 + 2$. Washers in $y$ would need a split at $y = 3$, where the inner radius changes.',
    },
    tags: ['y-axis', 'method-selection', 'single-integral'],
  },

  // ───────────── vs-s-10: x = 2y − y² about y = −1 ─────────────
  {
    id: 'vs-s-10',
    topic: 'volumes-shells',
    title: 'Shells about y = −1',
    difficulty: 1,
    statement: {
      text: 'The region bounded by $x = 2y - y^2$ and the y-axis is rotated about the line $y = -1$. Use cylindrical shells to find the volume.',
    },
    variable: 'y',
    steps: [
      {
        prompt: 'Which slices and limits does the shell method use here?',
        options: [
          { text: 'Vertical slices; integrate in $x$ from 0 to 1', mistake: 'shell-orientation-wrong', why: 'Vertical slices are perpendicular to y = −1 and sweep out washers; shells need horizontal slices.' },
          { text: 'Horizontal slices; integrate in $y$ from 0 to 1', mistake: 'bounds-wrong-axis', why: '1 is the largest x-value of the region (at y = 1); the curve meets the y-axis at y = 0 and y = 2.' },
          { text: 'Horizontal slices; integrate in $x$ from 0 to 1', mistake: 'wrong-integration-variable', why: 'A horizontal slice has thickness dy, so the shells are stacked along y.' },
          { text: 'Horizontal slices; integrate in $y$ from $-2$ to 0', mistake: 'sign-error', why: '2y − y² = y(2 − y) = 0 gives y = 0 and y = 2, not y = −2.' },
          { text: 'Horizontal slices; integrate in $y$ from 0 to 2' },
        ],
        correct: 4,
        explanation: 'The axis is horizontal, so shell slices are horizontal; $2y - y^2 = 0$ at $y = 0$ and $y = 2$.',
        result: { text: 'Horizontal slices, $0 \\le y \\le 2$.' },
      },
      {
        prompt: 'What are the radius and height of the shell at height $y$?',
        options: [
          { latex: 'r = y - 1,\\quad h = 2y - y^2', expr: '[y - 1, 2*y - y^2]', mistake: 'axis-shift-sign', why: 'The distance from height y down to the line y = −1 is y − (−1) = y + 1.' },
          { latex: 'r = y,\\quad h = y^2 - 2y', expr: '[y, y^2 - 2*y]', mistake: 'axis-shift-missing', why: 'Two slips: y measures to the x-axis instead of y = −1, and left minus right gives a negative length.' },
          { latex: 'r = y + 1,\\quad h = y^2 - 2y', expr: '[y + 1, y^2 - 2*y]', mistake: 'top-bottom-swapped', why: 'Left minus right gives a negative length; the slice runs from x = 0 to x = 2y − y².' },
          { latex: 'r = y + 1,\\quad h = 2y - y^2', expr: '[y + 1, 2*y - y^2]' },
          { latex: 'r = y,\\quad h = 2y - y^2', expr: '[y, 2*y - y^2]', mistake: 'axis-shift-missing', why: 'y is the distance to the x-axis; the axis of rotation is one unit lower, at y = −1.' },
          { latex: 'r = y - 1,\\quad h = y^2 - 2y', expr: '[y - 1, y^2 - 2*y]', mistake: 'axis-shift-sign', why: 'Two slips: the shift has the wrong sign (the radius is y + 1), and left minus right gives a negative length.' },
        ],
        correct: 3,
        explanation: 'The slice at height $y$ runs from $x = 0$ to $x = 2y - y^2$ and lies $y - (-1) = y + 1$ above the axis.',
        result: { latex: 'r = y + 1,\\quad h = 2y - y^2' },
        check: { kind: 'value', expected: '[y + 1, 2*y - y^2]' },
      },
      {
        prompt: 'Set up the volume integral.',
        options: [
          { latex: 'V = \\int_0^2 2\\pi y(2y - y^2)\\,dy', expr: 'integral(2*pi*y*(2*y - y^2), y, 0, 2)', mistake: 'axis-shift-missing', why: 'That rotates about the x-axis; the radius about y = −1 is y + 1.' },
          { latex: 'V = \\int_0^2 2\\pi(y - 1)(2y - y^2)\\,dy', expr: 'integral(2*pi*(y - 1)*(2*y - y^2), y, 0, 2)', mistake: 'axis-shift-sign', why: 'The radius is y + 1; with y − 1 the signed contributions even cancel to 0.' },
          { latex: 'V = \\int_0^2 \\pi(y + 1)(2y - y^2)\\,dy', expr: 'integral(pi*(y + 1)*(2*y - y^2), y, 0, 2)', mistake: 'two-pi-missing', why: 'The shell integrand is 2π·r·h; with π alone the volume is halved.' },
          { latex: 'V = \\int_0^2 2\\pi(y + 1)^2(2y - y^2)\\,dy', expr: 'integral(2*pi*(y + 1)^2*(2*y - y^2), y, 0, 2)', mistake: 'shell-radius-squared', why: 'The radius is not squared in 2πrh; squaring belongs to the disk formula.' },
          { latex: 'V = \\int_0^2 \\pi(2y - y^2)^2\\,dy', expr: 'integral(pi*(2*y - y^2)^2, y, 0, 2)', mistake: 'method-formula-swapped', why: 'π(length)² is a disk formula; a horizontal slice is parallel to y = −1 and sweeps out a shell.' },
          { latex: 'V = \\int_0^2 2\\pi(y + 1)(2y - y^2)\\,dy', expr: 'integral(2*pi*(y + 1)*(2*y - y^2), y, 0, 2)' },
        ],
        correct: 5,
        explanation: '$V = \\int_0^2 2\\pi r h\\,dy$ with $r = y + 1$ and $h = 2y - y^2$.',
        result: { latex: 'V = \\int_0^2 2\\pi(y + 1)(2y - y^2)\\,dy = 2\\pi\\int_0^2 \\left(2y + y^2 - y^3\\right)dy' },
        check: { kind: 'value', expected: 'integral(pi*((2 + sqrt(1 - x))^2 - (2 - sqrt(1 - x))^2), x, 0, 1)' },
      },
      {
        prompt: 'Evaluate $2\\pi\\int_0^2 \\left(2y + y^2 - y^3\\right)dy$.',
        options: [
          { latex: 'V = \\frac{8\\pi}{3}', expr: '8*pi/3', mistake: 'coefficient-mishandled', why: 'The bracket is 8/3, so V = 2π·8/3; the factor 2 was lost.' },
          { latex: 'V = 16\\pi', expr: '16*pi', mistake: 'sign-error', why: 'Expanding (y + 1)(2y − y²), the −y² term was written +y², giving 2y + 3y² − y³.' },
          { latex: 'V = \\frac{32\\pi}{3}', expr: '32*pi/3', mistake: 'product-rule-integral', why: 'The factors were integrated separately and multiplied: 2π·4·(4/3); there is no product rule for integrals.' },
          { latex: 'V = \\frac{16\\pi}{3}', expr: '16*pi/3' },
          { latex: 'V = \\frac{40\\pi}{3}', expr: '40*pi/3', mistake: 'power-rule-int-coefficient', why: 'Each power was divided by its old exponent: 2y²/1 + y³/2 − y⁴/3 at 2 gives 20/3.' },
        ],
        correct: 3,
        explanation: '$2\\pi\\left[y^2 + \\frac{y^3}{3} - \\frac{y^4}{4}\\right]_0^2 = 2\\pi\\left(4 + \\frac{8}{3} - 4\\right) = \\frac{16\\pi}{3}$.',
        result: { latex: 'V = 2\\pi\\left[y^2 + \\tfrac{y^3}{3} - \\tfrac{y^4}{4}\\right]_0^2 = 2\\pi\\cdot\\tfrac{8}{3} = \\tfrac{16\\pi}{3}' },
        check: { kind: 'value', expected: '16*pi/3' },
      },
    ],
    final: {
      latex: 'V = \\frac{16\\pi}{3}',
      expr: '16*pi/3',
      check: { kind: 'definite-integral', integrand: '2*pi*(y + 1)*(2*y - y^2)', lower: '0', upper: '2' },
      recap: 'About $y = -1$ the horizontal slice at height $y$ has radius $y - (-1) = y + 1$ and height $2y - y^2$. Shells avoid solving the parabola for $y$, which washers in $x$ would require.',
    },
    tags: ['axis-shift', 'method-selection'],
  },
];
