import type { StepProblem } from '../types';

/** Step-Through problems for topic "volumes-disks". Authored by content-author; verified by math-verifier. */
export const steps: StepProblem[] = [
  {
    id: 'vd-s-01',
    topic: 'volumes-disks',
    title: 'Sphere of radius 3 by slicing',
    difficulty: 1,
    statement: { text: 'Use slicing to find the volume of the sphere $x^2 + y^2 + z^2 \\le 9$ (radius 3, centered at the origin). Slice with planes perpendicular to the z-axis.' },
    variable: 'z',
    steps: [
      {
        prompt: 'The cross-section at height $z$ is a disk centered on the z-axis. What is its radius?',
        options: [
          { latex: 'r(z) = \\sqrt{9 - z^2}', expr: 'sqrt(9 - z^2)' },
          { latex: 'r(z) = 3 - z', expr: '3 - z', mistake: 'sqrt-of-sum-split', why: '$\\sqrt{9 - z^2}$ is not $3 - z$: a square root does not split over a difference.' },
          { latex: 'r(z) = 9 - z^2', expr: '9 - z^2', mistake: 'algebra-error', why: 'From $r^2 + z^2 = 9$ we get $r^2 = 9 - z^2$; the square root is still needed.' },
          { latex: 'r(z) = 3', expr: '3', mistake: 'cross-section-area-wrong', why: 'A constant radius 3 describes a cylinder; the slices of a sphere shrink to points at $z = \\pm 3$.' },
          { latex: 'r(z) = \\sqrt{9 + z^2}', expr: 'sqrt(9 + z^2)', mistake: 'sign-error', why: 'By Pythagoras $r^2 + z^2 = 9$, so $r^2 = 9 - z^2$; the sign is flipped.' },
          { latex: 'r(z) = \\sqrt{3 - z^2}', expr: 'sqrt(3 - z^2)', mistake: 'radius-not-squared', why: 'The radius of the sphere must be squared: $r^2 = 3^2 - z^2 = 9 - z^2$.' },
        ],
        correct: 0,
        explanation: 'A point on the edge of the slice lies on the sphere, so $r^2 + z^2 = 9$ and $r(z) = \\sqrt{9 - z^2}$.',
        result: { latex: 'r(z)^2 + z^2 = 9 \\;\\Rightarrow\\; r(z) = \\sqrt{9 - z^2},\\quad A(z) = \\pi(9 - z^2)' },
        check: { kind: 'value', expected: 'sqrt(9 - z^2)' },
      },
      {
        prompt: 'Over which interval of $z$ do the slices run?',
        options: [
          { text: 'From $z = -3$ to $z = 3$' },
          { text: 'From $z = 0$ to $z = 3$', mistake: 'missing-intersection', why: 'That covers only the upper hemisphere; the sphere runs from its bottom $z = -3$ to its top $z = 3$.' },
          { text: 'From $z = -9$ to $z = 9$', mistake: 'algebra-error', why: '9 is the radius squared; the sphere reaches only to $z = \\pm 3$.' },
          { text: 'From $z = 0$ to $z = 6$', mistake: 'diameter-as-radius', why: '6 is the diameter; with the center at the origin the slices run from $-3$ to $3$.' },
          { text: 'From $z = -\\sqrt{3}$ to $z = \\sqrt{3}$', mistake: 'radius-not-squared', why: 'The slices vanish where $9 - z^2 = 0$, at $z = \\pm 3$, not where $3 - z^2 = 0$.' },
        ],
        correct: 0,
        explanation: 'The slices exist wherever $9 - z^2 \\ge 0$, that is, from the bottom of the sphere at $z = -3$ to the top at $z = 3$.',
        result: { text: '$-3 \\le z \\le 3$' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\int_{-3}^{3} \\pi(9 - z^2)\\,dz', expr: 'integral(pi*(9 - z^2), z, -3, 3)' },
          { latex: 'V = \\int_{-3}^{3} \\pi\\sqrt{9 - z^2}\\,dz', expr: 'integral(pi*sqrt(9 - z^2), z, -3, 3)', mistake: 'radius-not-squared', why: 'The slice area is $\\pi r^2 = \\pi(9 - z^2)$; the radius was not squared.' },
          { latex: 'V = \\int_{-3}^{3} (9 - z^2)\\,dz', expr: 'integral(9 - z^2, z, -3, 3)', mistake: 'pi-missing', why: 'Each slice is a disk of area $\\pi r^2$; the $\\pi$ is missing.' },
          { latex: 'V = \\int_0^3 \\pi(9 - z^2)\\,dz', expr: 'integral(pi*(9 - z^2), z, 0, 3)', mistake: 'missing-intersection', why: 'Starting at $z = 0$ gives only the upper hemisphere.' },
          { latex: 'V = \\int_{-3}^{3} \\pi(3 - z)^2\\,dz', expr: 'integral(pi*(3 - z)^2, z, -3, 3)', mistake: 'sqrt-of-sum-split', why: 'The radius is $\\sqrt{9 - z^2}$, not $3 - z$; that radius describes a cone.' },
          { latex: 'V = \\int_{-3}^{3} 2\\pi\\sqrt{9 - z^2}\\,dz', expr: 'integral(2*pi*sqrt(9 - z^2), z, -3, 3)', mistake: 'formula-swapped', why: '$2\\pi r$ is the circumference of the slice, not its area.' },
        ],
        correct: 0,
        explanation: 'Integrate the slice area $A(z) = \\pi(9 - z^2)$ over $-3 \\le z \\le 3$.',
        result: { latex: 'V = \\int_{-3}^{3} \\pi(9 - z^2)\\,dz' },
        check: { kind: 'value', expected: '36*pi' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = 36\\pi', expr: '36*pi' },
          { latex: 'V = 18\\pi', expr: '18*pi', mistake: 'ftc-not-subtracted', why: 'Only $F(3) = 27 - 9 = 18$ was used; $F(-3) = -18$ must be subtracted.' },
          { latex: 'V = 54\\pi', expr: '54*pi', mistake: 'negative-squared-wrong', why: '$(-3)^3 = -27$; treating it as $+27$ gives $F(-3) = -36$ instead of $-18$.' },
          { latex: 'V = 72\\pi', expr: '72*pi', mistake: 'sign-error', why: 'The antiderivative was written $9z + \\frac{z^3}{3}$; the minus sign on $z^2$ was lost.' },
          { latex: 'V = 0', expr: '0', mistake: 'power-rule-int-coefficient', why: '$\\int z^2\\,dz = \\frac{z^3}{3}$; without the $\\frac13$ both $F(3)$ and $F(-3)$ are 0.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left[9z - \\frac{z^3}{3}\\right]_{-3}^{3} = \\pi(18 - (-18)) = 36\\pi$.',
        result: { latex: 'V = \\pi\\left[9z - \\frac{z^3}{3}\\right]_{-3}^{3} = \\pi(18 + 18) = 36\\pi' },
        check: { kind: 'value', expected: '36*pi' },
      },
    ],
    final: {
      latex: 'V = 36\\pi',
      expr: '36*pi',
      check: { kind: 'definite-integral', integrand: 'pi*(9 - z^2)', lower: '-3', upper: '3' },
      recap: 'Slice perpendicular to an axis, get each slice area from geometry ($r^2 + z^2 = 9$ gives $\\pi(9 - z^2)$), and integrate across the whole solid: $36\\pi = \\frac43\\pi \\cdot 3^3$.',
    },
  },
  {
    id: 'vd-s-02',
    topic: 'volumes-disks',
    title: 'A cone from a line segment',
    difficulty: 1,
    statement: { text: 'The region bounded by $y = 4 - 2x$, the x-axis, and the y-axis is rotated about the x-axis, producing a cone. Find its volume with the disk method.' },
    steps: [
      {
        prompt: 'Which slices, variable, and limits does the disk method use here?',
        options: [
          { text: 'Disks perpendicular to the x-axis, $x$ from 0 to 2' },
          { text: 'Disks perpendicular to the y-axis, $y$ from 0 to 4', mistake: 'wrong-integration-variable', why: 'That is the plan for rotation about the y-axis; slices must be perpendicular to the x-axis, stacked along $x$.' },
          { text: 'Washers perpendicular to the y-axis, $y$ from 0 to 4', mistake: 'wrong-integration-variable', why: 'Slices perpendicular to the y-axis belong to a vertical axis; here the axis is the x-axis, and the region reaches it, so there is no hole either.' },
          { text: 'Washers perpendicular to the x-axis, $x$ from 0 to 4', mistake: 'bounds-wrong-axis', why: '4 is the height of the region; the line meets the x-axis at $x = 2$, and the region reaches the axis, so the slices have no hole.' },
          { text: 'Disks perpendicular to the y-axis, $y$ from 0 to 2', mistake: 'bounds-wrong-axis', why: 'Slices must be perpendicular to the x-axis, and 2 is an x-value, not a height.' },
        ],
        correct: 0,
        explanation: 'Slices perpendicular to the x-axis reach from the axis to the line, so they are disks, for $0 \\le x \\le 2$ (where $4 - 2x = 0$ at $x = 2$).',
        result: { text: 'Disks perpendicular to the x-axis, $0 \\le x \\le 2$' },
      },
      {
        prompt: 'What is the radius $R(x)$ of the disk at $x$?',
        options: [
          { latex: 'R(x) = 4 - 2x', expr: '4 - 2*x' },
          { latex: 'R(x) = 2 - \\frac{y}{2}', expr: '2 - y/2', mistake: 'not-in-terms-of-variable', why: '$x = 2 - \\frac{y}{2}$ is the line solved for $x$; the radius of a vertical slice is its height, written in $x$.' },
          { latex: 'R(x) = x', expr: 'x', mistake: 'radius-is-function-value', why: 'The radius is the vertical distance from the axis to the line, $4 - 2x$, not the x-coordinate.' },
          { latex: 'R(x) = 4 + 2x', expr: '4 + 2*x', mistake: 'sign-error', why: 'The line falls from 4 to 0 as $x$ goes from 0 to 2: its height is $4 - 2x$.' },
          { latex: 'R(x) = 4 - \\frac{x}{2}', expr: '4 - x/2', mistake: 'algebra-error', why: 'The slope is $-2$ (the line drops 4 over a run of 2), not $-\\frac12$.' },
        ],
        correct: 0,
        explanation: 'The disk reaches from the axis $y = 0$ up to the line, so $R(x) = 4 - 2x$.',
        result: { latex: 'R(x) = 4 - 2x,\\quad r(x) = 0' },
        check: { kind: 'value', expected: '4 - 2*x' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\pi\\int_0^2 (4 - 2x)^2\\,dx', expr: 'integral(pi*(4 - 2*x)^2, x, 0, 2)' },
          { latex: 'V = \\pi\\int_0^2 (4 - 2x)\\,dx', expr: 'integral(pi*(4 - 2*x), x, 0, 2)', mistake: 'radius-not-squared', why: 'The disk area is $\\pi R^2$; the radius was not squared.' },
          { latex: 'V = \\pi\\int_0^2 \\left(4 - \\frac{x}{2}\\right)^2dx', expr: 'integral(pi*(4 - x/2)^2, x, 0, 2)', mistake: 'algebra-error', why: 'The line drops 4 over a run of 2, so its slope is $-2$: the radius is $4 - 2x$, not $4 - \\frac{x}{2}$.' },
          { latex: 'V = \\pi\\int_0^4 (4 - 2x)^2\\,dx', expr: 'integral(pi*(4 - 2*x)^2, x, 0, 4)', mistake: 'bounds-wrong-axis', why: '4 is the y-intercept; in $x$ the region ends at $x = 2$.' },
          { latex: 'V = \\pi\\int_0^4 \\left(2 - \\frac{y}{2}\\right)^2dy', expr: 'integral(pi*(2 - y/2)^2, y, 0, 4)', mistake: 'wrong-integration-variable', why: 'Horizontal disks of radius $2 - \\frac{y}{2}$ build the solid about the y-axis; about the x-axis the disks are vertical, in $x$.' },
        ],
        correct: 0,
        explanation: '$V = \\int_0^2 \\pi R(x)^2\\,dx = \\pi\\int_0^2 (4 - 2x)^2\\,dx$.',
        result: { latex: 'V = \\pi\\int_0^2 (4 - 2x)^2\\,dx' },
        check: { kind: 'value', expected: '32*pi/3' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\frac{32\\pi}{3}', expr: '32*pi/3' },
          { latex: 'V = 32\\pi', expr: '32*pi', mistake: 'power-rule-int-coefficient', why: 'Expanding gives $16 - 16x + 4x^2$; integrating $4x^2$ as $4x^3$ (no $\\frac13$) gives $32 - 32 + 32$.' },
          { latex: 'V = \\frac{64\\pi}{3}', expr: '64*pi/3', mistake: 'inner-constant-factor-missing', why: 'With $u = 4 - 2x$, $du = -2\\,dx$: the antiderivative is $-\\frac{(4 - 2x)^3}{6}$; the factor $\\frac12$ was dropped.' },
          { latex: 'V = -\\frac{32\\pi}{3}', expr: '-32*pi/3', mistake: 'u-cos-sign-missing', why: 'With $u = 4 - 2x$, $du = -2\\,dx$; dropping that minus sign gives a negative volume.' },
          { latex: 'V = \\frac{56\\pi}{3}', expr: '56*pi/3', mistake: 'arithmetic-error', why: 'At $x = 2$, $8x^2 = 32$, not 24.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left[-\\frac{(4 - 2x)^3}{6}\\right]_0^2 = \\pi\\left(0 + \\frac{64}{6}\\right) = \\frac{32\\pi}{3}$, which matches $\\frac13\\pi r^2 h$ with $r = 4$, $h = 2$.',
        result: { latex: 'V = \\pi\\left[16x - 8x^2 + \\frac{4x^3}{3}\\right]_0^2 = \\frac{32\\pi}{3}' },
        check: { kind: 'value', expected: '32*pi/3' },
      },
    ],
    final: {
      latex: 'V = \\frac{32\\pi}{3}',
      expr: '32*pi/3',
      check: { kind: 'definite-integral', integrand: 'pi*(4 - 2*x)^2', lower: '0', upper: '2' },
      recap: 'The segment sweeps out a cone: disks of radius $R(x) = 4 - 2x$ from $x = 0$ to $2$ give $\\frac{32\\pi}{3}$, the same as $\\frac13\\pi r^2 h$ with $r = 4$, $h = 2$.',
    },
  },
  {
    id: 'vd-s-03',
    topic: 'volumes-disks',
    title: 'Equilateral triangles on a disk',
    difficulty: 2,
    statement: { text: 'The base of a solid is the disk $x^2 + y^2 \\le 1$. Cross-sections perpendicular to the x-axis are equilateral triangles with one side in the base. Find the volume.' },
    steps: [
      {
        prompt: 'What is the side length $s(x)$ of the triangle at $x$?',
        options: [
          { latex: 's(x) = 2\\sqrt{1 - x^2}', expr: '2*sqrt(1 - x^2)' },
          { latex: 's(x) = \\sqrt{1 - x^2}', expr: 'sqrt(1 - x^2)', mistake: 'coefficient-mishandled', why: 'The side spans the whole chord from $y = -\\sqrt{1 - x^2}$ to $y = \\sqrt{1 - x^2}$; $\\sqrt{1 - x^2}$ is only half of it.' },
          { latex: 's(x) = 2(1 - x^2)', expr: '2*(1 - x^2)', mistake: 'algebra-error', why: 'Solving $x^2 + y^2 = 1$ for $y$ needs a square root: $y = \\pm\\sqrt{1 - x^2}$.' },
          { latex: 's(x) = 2\\sqrt{1 + x^2}', expr: '2*sqrt(1 + x^2)', mistake: 'sign-error', why: 'From $x^2 + y^2 = 1$, $y^2 = 1 - x^2$, not $1 + x^2$.' },
          { latex: 's(x) = 2 - 2x', expr: '2 - 2*x', mistake: 'sqrt-of-sum-split', why: '$\\sqrt{1 - x^2}$ is not $1 - x$; a root does not split over a difference.' },
        ],
        correct: 0,
        explanation: 'At $x$ the base runs from $y = -\\sqrt{1 - x^2}$ to $y = \\sqrt{1 - x^2}$, a chord of length $2\\sqrt{1 - x^2}$.',
        result: { latex: 's(x) = 2\\sqrt{1 - x^2}' },
        check: { kind: 'value', expected: '2*sqrt(1 - x^2)' },
        domain: [-0.9, 0.9],
      },
      {
        prompt: 'What is the area $A(x)$ of the triangle at $x$?',
        options: [
          { latex: 'A(x) = \\sqrt{3}(1 - x^2)', expr: 'sqrt(3)*(1 - x^2)' },
          { latex: 'A(x) = \\frac{\\sqrt{3}}{4}(1 - x^2)', expr: 'sqrt(3)/4*(1 - x^2)', mistake: 'coefficient-mishandled', why: '$s^2 = \\left(2\\sqrt{1 - x^2}\\right)^2 = 4(1 - x^2)$; the factor 4 from the 2 was lost.' },
          { latex: 'A(x) = \\frac{\\sqrt{3}}{2}(1 - x^2)', expr: 'sqrt(3)/2*(1 - x^2)', mistake: 'algebra-error', why: '$\\left(2\\sqrt{1 - x^2}\\right)^2 = 4(1 - x^2)$, not $2(1 - x^2)$.' },
          { latex: 'A(x) = 2(1 - x^2)', expr: '2*(1 - x^2)', mistake: 'cross-section-area-wrong', why: '$\\frac12 s^2$ takes the height equal to the side; an equilateral triangle has height $\\frac{\\sqrt{3}}{2}s$.' },
          { latex: 'A(x) = 4(1 - x^2)', expr: '4*(1 - x^2)', mistake: 'cross-section-area-wrong', why: '$s^2$ is the area of a square slice, not a triangle.' },
          { latex: 'A(x) = \\frac{\\sqrt{3}}{2}\\sqrt{1 - x^2}', expr: 'sqrt(3)/2*sqrt(1 - x^2)', mistake: 'formula-wrong-power', why: 'The side must be squared in $\\frac{\\sqrt{3}}{4}s^2$.' },
        ],
        correct: 0,
        explanation: '$A = \\frac{\\sqrt{3}}{4}s^2 = \\frac{\\sqrt{3}}{4} \\cdot 4(1 - x^2) = \\sqrt{3}(1 - x^2)$.',
        result: { latex: 'A(x) = \\frac{\\sqrt{3}}{4}\\left(2\\sqrt{1 - x^2}\\right)^2 = \\sqrt{3}(1 - x^2)' },
        check: { kind: 'value', expected: 'sqrt(3)/4*(2*sqrt(1 - x^2))^2' },
        domain: [-0.9, 0.9],
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\int_{-1}^{1} \\sqrt{3}(1 - x^2)\\,dx', expr: 'integral(sqrt(3)*(1 - x^2), x, -1, 1)' },
          { latex: 'V = \\int_0^1 \\sqrt{3}(1 - x^2)\\,dx', expr: 'integral(sqrt(3)*(1 - x^2), x, 0, 1)', mistake: 'missing-intersection', why: 'The base spans $-1 \\le x \\le 1$; starting at 0 covers only half the solid.' },
          { latex: 'V = \\pi\\int_{-1}^{1} \\sqrt{3}(1 - x^2)\\,dx', expr: 'integral(pi*sqrt(3)*(1 - x^2), x, -1, 1)', mistake: 'cross-section-area-wrong', why: 'The slices are triangles; their area $\\sqrt{3}(1 - x^2)$ is complete, with no factor $\\pi$.' },
          { latex: 'V = \\int_{-1}^{1} \\sqrt{3}(1 - x^2)^2\\,dx', expr: 'integral(sqrt(3)*(1 - x^2)^2, x, -1, 1)', mistake: 'formula-wrong-power', why: '$A(x) = \\sqrt{3}(1 - x^2)$ is already an area; squaring it again is not the slice area.' },
          { latex: 'V = \\int_{-2}^{2} \\sqrt{3}(1 - x^2)\\,dx', expr: 'integral(sqrt(3)*(1 - x^2), x, -2, 2)', mistake: 'diameter-as-radius', why: 'The base disk has radius 1, so $x$ runs from $-1$ to $1$; 2 is its diameter.' },
        ],
        correct: 0,
        explanation: 'Add up the slice areas across the base: $V = \\int_{-1}^{1} \\sqrt{3}(1 - x^2)\\,dx$.',
        result: { latex: 'V = \\int_{-1}^{1} \\sqrt{3}(1 - x^2)\\,dx' },
        check: { kind: 'value', expected: '4*sqrt(3)/3' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\frac{4\\sqrt{3}}{3}', expr: '4*sqrt(3)/3' },
          { latex: 'V = \\frac{2\\sqrt{3}}{3}', expr: '2*sqrt(3)/3', mistake: 'ftc-not-subtracted', why: 'Only $F(1) = \\frac{2\\sqrt{3}}{3}$ was used; $F(-1) = -\\frac{2\\sqrt{3}}{3}$ must be subtracted.' },
          { latex: 'V = 2\\sqrt{3}', expr: '2*sqrt(3)', mistake: 'negative-squared-wrong', why: '$(-1)^3 = -1$; treating it as $+1$ makes $F(-1) = -\\frac{4\\sqrt{3}}{3}$ instead of $-\\frac{2\\sqrt{3}}{3}$.' },
          { latex: 'V = \\frac{8\\sqrt{3}}{3}', expr: '8*sqrt(3)/3', mistake: 'sign-error', why: 'The antiderivative was written $\\sqrt{3}\\left(x + \\frac{x^3}{3}\\right)$; the minus sign was lost.' },
          { latex: 'V = 0', expr: '0', mistake: 'power-rule-int-coefficient', why: 'Integrating $x^2$ as $x^3$ (no $\\frac13$) gives $F(1) = F(-1) = 0$.' },
          { latex: 'V = \\frac{4}{3}', expr: '4/3', mistake: 'coefficient-mishandled', why: 'The constant factor $\\sqrt{3}$ was dropped.' },
        ],
        correct: 0,
        explanation: '$\\sqrt{3}\\left[x - \\frac{x^3}{3}\\right]_{-1}^{1} = \\sqrt{3}\\left(\\frac23 + \\frac23\\right) = \\frac{4\\sqrt{3}}{3}$.',
        result: { latex: 'V = \\sqrt{3}\\left[x - \\frac{x^3}{3}\\right]_{-1}^{1} = \\frac{4\\sqrt{3}}{3}' },
        check: { kind: 'value', expected: '4*sqrt(3)/3' },
      },
    ],
    final: {
      latex: 'V = \\frac{4\\sqrt{3}}{3}',
      expr: '4*sqrt(3)/3',
      check: { kind: 'definite-integral', integrand: 'sqrt(3)/4*(2*sqrt(1 - x^2))^2', lower: '-1', upper: '1' },
      recap: 'Slicing works for any cross-section: read the side from the base ($2\\sqrt{1 - x^2}$), put it into the shape area ($\\frac{\\sqrt{3}}{4}s^2$), and integrate across the base.',
    },
  },
  {
    id: 'vd-s-04',
    topic: 'volumes-disks',
    title: 'Root region about the y-axis',
    difficulty: 1,
    statement: { text: 'Find the volume of the solid obtained by rotating the region bounded by $y = \\sqrt{x}$, the x-axis, and $x = 4$ about the y-axis. Use the disk/washer method.' },
    variable: 'y',
    steps: [
      {
        prompt: 'The axis of rotation is vertical. How should the region be sliced?',
        options: [
          { text: 'Horizontal washers, $y$ from 0 to 2' },
          { text: 'Vertical disks, $x$ from 0 to 4', mistake: 'wrong-integration-variable', why: 'That is the plan for rotation about the x-axis; for the y-axis, disk/washer slices are horizontal.' },
          { text: 'Horizontal washers, $y$ from 0 to 4', mistake: 'bounds-wrong-axis', why: '0 to 4 is the x-range; the heights run from $y = 0$ to $y = \\sqrt{4} = 2$.' },
          { text: 'Horizontal disks, $y$ from 0 to 4', mistake: 'washer-as-disk', why: 'At height $y$ the region starts at $x = y^2$, so each slice has a hole; and the heights only run to 2.' },
          { text: 'Vertical washers, $x$ from 0 to 2', mistake: 'wrong-integration-variable', why: 'Vertical slices are parallel to the y-axis; disk/washer slices must be perpendicular to the axis of rotation.' },
        ],
        correct: 0,
        explanation: 'Integrate along the axis of rotation: horizontal slices, $y$ from the lowest point 0 to the highest point $\\sqrt{4} = 2$.',
        result: { text: 'Horizontal washers, $0 \\le y \\le 2$; the curve is $x = y^2$' },
      },
      {
        prompt: 'At height $y$, what are the outer and inner radii?',
        options: [
          { latex: 'R = 4,\\ r = y^2', expr: '[4, y^2]' },
          { latex: 'R = 4 - y^2,\\ r = 0', expr: '[4 - y^2, 0]', mistake: 'washer-difference-squared', why: '$4 - y^2$ is the slice length; using it as one radius computes $\\pi(R - r)^2$.' },
          { latex: 'R = 4,\\ r = 0', expr: '[4, 0]', mistake: 'washer-as-disk', why: 'At height $y$ the region starts at $x = y^2$, not at the axis, so there is a hole.' },
          { latex: 'R = \\sqrt{x},\\ r = 0', expr: '[sqrt(x), 0]', mistake: 'wrong-integration-variable', why: '$\\sqrt{x}$ is the height of a vertical slice, the disk radius for rotation about the x-axis; here the slices are horizontal.' },
          { latex: 'R = 2,\\ r = \\sqrt{y}', expr: '[2, sqrt(y)]', mistake: 'inverse-function-wrong', why: 'Solving $y = \\sqrt{x}$ for $x$ gives $x = y^2$, not $\\sqrt{y}$; and 2 is the top height, not the distance from the axis to $x = 4$.' },
          { latex: 'R = 4,\\ r = \\sqrt{y}', expr: '[4, sqrt(y)]', mistake: 'inverse-function-wrong', why: 'Solving $y = \\sqrt{x}$ for $x$ gives $x = y^2$, not $\\sqrt{y}$.' },
        ],
        correct: 0,
        explanation: 'The slice runs from the curve $x = y^2$ (near the axis) to the line $x = 4$ (far): $R = 4$, $r = y^2$.',
        result: { latex: 'R(y) = 4,\\quad r(y) = y^2' },
        check: { kind: 'value', expected: '[4, y^2]' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\pi\\int_0^2 \\left[4^2 - (y^2)^2\\right]dy', expr: 'integral(pi*(4^2 - (y^2)^2), y, 0, 2)' },
          { latex: 'V = \\pi\\int_0^2 (4 - y^2)^2\\,dy', expr: 'integral(pi*(4 - y^2)^2, y, 0, 2)', mistake: 'washer-difference-squared', why: 'The washer area is $\\pi(R^2 - r^2)$, not $\\pi(R - r)^2$.' },
          { latex: 'V = \\pi\\int_0^2 \\left[(y^2)^2 - 4^2\\right]dy', expr: 'integral(pi*((y^2)^2 - 4^2), y, 0, 2)', mistake: 'radii-swapped', why: 'Outer squared minus inner squared: $4^2 - (y^2)^2$; this version is negative.' },
          { latex: 'V = \\pi\\int_0^4 \\left[4^2 - (y^2)^2\\right]dy', expr: 'integral(pi*(4^2 - (y^2)^2), y, 0, 4)', mistake: 'bounds-wrong-axis', why: 'In $y$ the region runs from 0 to 2; 4 is an x-value.' },
          { latex: 'V = \\pi\\int_0^2 \\left(4 - y^2\\right)dy', expr: 'integral(pi*(4 - y^2), y, 0, 2)', mistake: 'radius-not-squared', why: 'Both radii must be squared: $\\pi(R^2 - r^2)$.' },
          { latex: 'V = \\pi\\int_0^4 (\\sqrt{x})^2\\,dx', expr: 'integral(pi*(sqrt(x))^2, x, 0, 4)', mistake: 'wrong-integration-variable', why: 'This is the disk volume about the x-axis; about the y-axis the slices are horizontal.' },
        ],
        correct: 0,
        explanation: '$V = \\int_0^2 \\pi\\left[R(y)^2 - r(y)^2\\right]dy = \\pi\\int_0^2 \\left[16 - y^4\\right]dy$.',
        result: { latex: 'V = \\pi\\int_0^2 \\left(16 - y^4\\right)dy' },
        check: { kind: 'value', expected: '128*pi/5' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\frac{128\\pi}{5}', expr: '128*pi/5' },
          { latex: 'V = \\frac{192\\pi}{5}', expr: '192*pi/5', mistake: 'sign-error', why: 'The antiderivative was written $16y + \\frac{y^5}{5}$; the minus sign was lost.' },
          { latex: 'V = \\frac{48\\pi}{5}', expr: '48*pi/5', mistake: 'power-rule-int-exponent', why: '$\\int 16\\,dy = 16y$, which is 32 at $y = 2$, not 16.' },
          { latex: 'V = \\frac{144\\pi}{5}', expr: '144*pi/5', mistake: 'arithmetic-error', why: '$2^5 = 32$, not 16.' },
          { latex: 'V = 0', expr: '0', mistake: 'power-rule-int-coefficient', why: '$\\int y^4\\,dy = \\frac{y^5}{5}$; without the $\\frac15$ the result is $32 - 32 = 0$.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left[16y - \\frac{y^5}{5}\\right]_0^2 = \\pi\\left(32 - \\frac{32}{5}\\right) = \\frac{128\\pi}{5}$.',
        result: { latex: 'V = \\pi\\left[16y - \\frac{y^5}{5}\\right]_0^2 = \\frac{128\\pi}{5}' },
        check: { kind: 'value', expected: '128*pi/5' },
      },
    ],
    final: {
      latex: 'V = \\frac{128\\pi}{5}',
      expr: '128*pi/5',
      check: { kind: 'definite-integral', integrand: 'pi*(4^2 - (y^2)^2)', lower: '0', upper: '2' },
      recap: 'About the y-axis, slice horizontally and write the radii in $y$: the region runs from $x = y^2$ (inner) to $x = 4$ (outer), so $V = \\pi\\int_0^2 (16 - y^4)\\,dy$.',
    },
  },
  {
    id: 'vd-s-05',
    topic: 'volumes-disks',
    title: 'Root region about x = -1',
    difficulty: 2,
    statement: { text: 'The region bounded by $y = \\sqrt{x}$, the x-axis, and $x = 4$ is rotated about the line $x = -1$. Find the volume using the disk/washer method.' },
    variable: 'y',
    steps: [
      {
        prompt: 'How should the region be sliced, and over which interval?',
        options: [
          { text: 'Horizontal washers, $y$ from 0 to 2' },
          { text: 'Vertical washers, $x$ from $-1$ to 4', mistake: 'wrong-integration-variable', why: 'Vertical slices are parallel to the vertical axis $x = -1$; washers need slices perpendicular to it, stacked along $y$.' },
          { text: 'Horizontal washers, $y$ from $-1$ to 2', mistake: 'bounds-from-axis', why: 'The axis position $x = -1$ is not a limit; $y$ runs over the heights of the region, 0 to 2.' },
          { text: 'Horizontal disks, $y$ from $-1$ to 2', mistake: 'washer-as-disk', why: 'The region starts at $x = y^2$, at least 1 unit from the axis, so every slice has a hole; and the heights run from 0 to 2.' },
          { text: 'Vertical disks, $x$ from 0 to 4', mistake: 'wrong-integration-variable', why: 'That is the plan for rotation about the x-axis; for the vertical line $x = -1$ the slices are horizontal.' },
        ],
        correct: 0,
        explanation: 'Slices perpendicular to the vertical axis are horizontal, stacked along $y$ over the heights $0 \\le y \\le 2$.',
        result: { text: 'Horizontal washers, $0 \\le y \\le 2$; the region runs from $x = y^2$ to $x = 4$' },
      },
      {
        prompt: 'Measured from $x = -1$, what are the outer and inner radii at height $y$?',
        options: [
          { latex: 'R = 5,\\ r = y^2 + 1', expr: '[5, y^2 + 1]' },
          { latex: 'R = 4,\\ r = y^2', expr: '[4, y^2]', mistake: 'axis-shift-missing', why: 'Those are distances to the y-axis; from $x = -1$ every distance grows by 1.' },
          { latex: 'R = 3,\\ r = y^2 - 1', expr: '[3, y^2 - 1]', mistake: 'axis-shift-sign', why: 'The distance from $x$ to the line $x = -1$ is $x + 1$, not $x - 1$.' },
          { latex: 'R = y^2 + 1,\\ r = 5', expr: '[y^2 + 1, 5]', mistake: 'radii-swapped', why: 'The line $x = 4$ is the far edge, 5 units from the axis, so it gives $R$.' },
          { latex: 'R = 5,\\ r = 0', expr: '[5, 0]', mistake: 'washer-as-disk', why: 'The curve $x = y^2$ is at least 1 unit from the axis, so there is a hole of radius $y^2 + 1$.' },
          { latex: 'R = 5,\\ r = \\sqrt{y} + 1', expr: '[5, sqrt(y) + 1]', mistake: 'inverse-function-wrong', why: 'Solving $y = \\sqrt{x}$ for $x$ gives $x = y^2$, not $\\sqrt{y}$.' },
        ],
        correct: 0,
        explanation: 'Distances to $x = -1$ are $x + 1$: the line $x = 4$ gives $R = 5$ and the curve $x = y^2$ gives $r = y^2 + 1$.',
        result: { latex: 'R(y) = 4 + 1 = 5,\\quad r(y) = y^2 + 1' },
        check: { kind: 'value', expected: '[5, y^2 + 1]' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\pi\\int_0^2 \\left[5^2 - (y^2 + 1)^2\\right]dy', expr: 'integral(pi*(5^2 - (y^2 + 1)^2), y, 0, 2)' },
          { latex: 'V = \\pi\\int_0^2 \\left[4^2 - (y^2)^2\\right]dy', expr: 'integral(pi*(4^2 - (y^2)^2), y, 0, 2)', mistake: 'axis-shift-missing', why: 'This is the volume about the y-axis; the shift to $x = -1$ was ignored.' },
          { latex: 'V = \\pi\\int_0^2 \\left[5 - (y^2 + 1)\\right]^2dy', expr: 'integral(pi*(5 - (y^2 + 1))^2, y, 0, 2)', mistake: 'washer-difference-squared', why: 'The washer area is $\\pi(R^2 - r^2)$, not $\\pi(R - r)^2$.' },
          { latex: 'V = \\pi\\int_0^2 \\left[3^2 - (y^2 - 1)^2\\right]dy', expr: 'integral(pi*(3^2 - (y^2 - 1)^2), y, 0, 2)', mistake: 'axis-shift-sign', why: 'Distances to $x = -1$ are $x + 1$; subtracting 1 measures distance to $x = 1$ instead.' },
          { latex: 'V = \\pi\\int_0^2 \\left[5^2 - (\\sqrt{y} + 1)^2\\right]dy', expr: 'integral(pi*(5^2 - (sqrt(y) + 1)^2), y, 0, 2)', mistake: 'inverse-function-wrong', why: 'Solving $y = \\sqrt{x}$ for $x$ gives $x = y^2$, so the inner radius is $y^2 + 1$.' },
          { latex: 'V = \\pi\\int_0^2 \\left[5^2 - (y^2 + 1)\\right]dy', expr: 'integral(pi*(5^2 - (y^2 + 1)), y, 0, 2)', mistake: 'radius-not-squared', why: 'The inner radius $y^2 + 1$ must be squared as well.' },
        ],
        correct: 0,
        explanation: '$V = \\pi\\int_0^2 \\left[R^2 - r^2\\right]dy$ with $R = 5$ and $r = y^2 + 1$.',
        result: { latex: 'V = \\pi\\int_0^2 \\left[25 - (y^2 + 1)^2\\right]dy = \\pi\\int_0^2 \\left(24 - 2y^2 - y^4\\right)dy' },
        check: { kind: 'value', expected: '544*pi/15' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\frac{544\\pi}{15}', expr: '544*pi/15' },
          { latex: 'V = \\frac{208\\pi}{5}', expr: '208*pi/5', mistake: 'algebra-error', why: 'The cross term $-2y^2$ from $(y^2 + 1)^2$ was dropped.' },
          { latex: 'V = \\frac{128\\pi}{5}', expr: '128*pi/5', mistake: 'power-rule-int-coefficient', why: '$\\int 2y^2\\,dy = \\frac{2y^3}{3}$; writing $2y^3$ subtracts 16 instead of $\\frac{16}{3}$.' },
          { latex: 'V = \\frac{704\\pi}{15}', expr: '704*pi/15', mistake: 'sign-error', why: 'The $-2y^2$ term was integrated with a plus sign.' },
          { latex: 'V = \\frac{574\\pi}{15}', expr: '574*pi/15', mistake: 'algebra-error', why: 'The constant 1 from $(y^2 + 1)^2$ was not subtracted: $25 - 1 = 24$.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left[24y - \\frac{2y^3}{3} - \\frac{y^5}{5}\\right]_0^2 = \\pi\\left(48 - \\frac{16}{3} - \\frac{32}{5}\\right) = \\frac{544\\pi}{15}$.',
        result: { latex: 'V = \\pi\\left[24y - \\frac{2y^3}{3} - \\frac{y^5}{5}\\right]_0^2 = \\frac{544\\pi}{15}' },
        check: { kind: 'value', expected: '544*pi/15' },
      },
    ],
    final: {
      latex: 'V = \\frac{544\\pi}{15}',
      expr: '544*pi/15',
      check: { kind: 'definite-integral', integrand: 'pi*(5^2 - (y^2 + 1)^2)', lower: '0', upper: '2' },
      recap: 'Moving the axis to $x = -1$ adds 1 to every horizontal distance: $R = 4 + 1$ and $r = y^2 + 1$. Radii are distances to the axis, not x-values.',
    },
  },
  {
    id: 'vd-s-06',
    topic: 'volumes-disks',
    title: 'Washers between two raised curves',
    difficulty: 1,
    statement: { text: 'Find the volume of the solid generated by rotating the region bounded by $y = \\sqrt{x} + 1$ and $y = x^2 + 1$ about the x-axis. Use the disk/washer method.' },
    steps: [
      {
        prompt: 'Which slices and limits apply?',
        options: [
          { text: 'Washers perpendicular to the x-axis, $x$ from 0 to 1' },
          { text: 'Disks perpendicular to the x-axis, $x$ from 0 to 1', mistake: 'washer-as-disk', why: 'Both curves stay at least 1 unit above the x-axis, so there is a gap and each slice has a hole.' },
          { text: 'Washers perpendicular to the y-axis, $y$ from 1 to 2', mistake: 'wrong-integration-variable', why: 'That is the plan for a vertical axis; slices perpendicular to the x-axis are vertical, stacked along $x$.' },
          { text: 'Disks perpendicular to the x-axis, $x$ from 1 to 2', mistake: 'bounds-wrong-axis', why: '1 to 2 is the range of heights; the curves meet at $x = 0$ and $x = 1$, and the gap below the region makes the slices washers.' },
          { text: 'Washers perpendicular to the x-axis, $x$ from $-1$ to 1', mistake: 'algebra-error', why: '$\\sqrt{x}$ is undefined for $x < 0$; $\\sqrt{x} = x^2$ gives $x = 0$ or $x = 1$.' },
          { text: 'Disks perpendicular to the y-axis, $y$ from 1 to 2', mistake: 'wrong-integration-variable', why: 'Slices must be perpendicular to the x-axis, the axis of rotation, and the region never reaches that axis.' },
        ],
        correct: 0,
        explanation: 'The curves meet where $\\sqrt{x} = x^2$, at $x = 0$ and $x = 1$, and the region does not touch the axis, so the slices are washers.',
        result: { text: 'Washers perpendicular to the x-axis, $0 \\le x \\le 1$' },
      },
      {
        prompt: 'What are the outer and inner radii at $x$?',
        options: [
          { latex: 'R = \\sqrt{x} + 1,\\ r = x^2 + 1', expr: '[sqrt(x) + 1, x^2 + 1]' },
          { latex: 'R = x^2 + 1,\\ r = \\sqrt{x} + 1', expr: '[x^2 + 1, sqrt(x) + 1]', mistake: 'radii-swapped', why: 'On $0 < x < 1$, $\\sqrt{x} > x^2$, so $\\sqrt{x} + 1$ is the top curve, farther from the axis.' },
          { latex: 'R = \\sqrt{x},\\ r = x^2', expr: '[sqrt(x), x^2]', mistake: 'phantom-axis-shift', why: 'The axis is $y = 0$, so the radii are the full heights $\\sqrt{x} + 1$ and $x^2 + 1$; there is no shift to remove.' },
          { latex: 'R = \\sqrt{x} + 1,\\ r = 0', expr: '[sqrt(x) + 1, 0]', mistake: 'washer-as-disk', why: 'The bottom curve $y = x^2 + 1$ leaves a gap above the axis, so there is a hole.' },
          { latex: 'R = \\sqrt{x} - x^2,\\ r = 0', expr: '[sqrt(x) - x^2, 0]', mistake: 'washer-difference-squared', why: '$\\sqrt{x} - x^2$ is the slice length; using it as one radius computes $\\pi(R - r)^2$.' },
        ],
        correct: 0,
        explanation: 'Measured from the x-axis, the top curve gives $R = \\sqrt{x} + 1$ and the bottom curve gives $r = x^2 + 1$.',
        result: { latex: 'R(x) = \\sqrt{x} + 1,\\quad r(x) = x^2 + 1' },
        check: { kind: 'value', expected: '[sqrt(x) + 1, x^2 + 1]' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\pi\\int_0^1 \\left[(\\sqrt{x} + 1)^2 - (x^2 + 1)^2\\right]dx', expr: 'integral(pi*((sqrt(x) + 1)^2 - (x^2 + 1)^2), x, 0, 1)' },
          { latex: 'V = \\pi\\int_0^1 \\left(\\sqrt{x} - x^2\\right)^2dx', expr: 'integral(pi*(sqrt(x) - x^2)^2, x, 0, 1)', mistake: 'washer-difference-squared', why: 'This is $\\pi(R - r)^2$; the washer area is $\\pi(R^2 - r^2)$.' },
          { latex: 'V = \\pi\\int_0^1 \\left[(x^2 + 1)^2 - (\\sqrt{x} + 1)^2\\right]dx', expr: 'integral(pi*((x^2 + 1)^2 - (sqrt(x) + 1)^2), x, 0, 1)', mistake: 'radii-swapped', why: 'Outer squared minus inner squared; this order makes the integral negative.' },
          { latex: 'V = \\pi\\int_0^1 (\\sqrt{x} + 1)^2\\,dx', expr: 'integral(pi*(sqrt(x) + 1)^2, x, 0, 1)', mistake: 'washer-as-disk', why: 'The hole of radius $x^2 + 1$ was not removed.' },
          { latex: 'V = \\pi\\int_0^1 \\left[(\\sqrt{x} + 1) - (x^2 + 1)\\right]dx', expr: 'integral(pi*((sqrt(x) + 1) - (x^2 + 1)), x, 0, 1)', mistake: 'radius-not-squared', why: 'The radii must be squared: $\\pi(R^2 - r^2)$.' },
          { latex: 'V = \\pi\\int_0^1 \\left[(\\sqrt{x})^2 - (x^2)^2\\right]dx', expr: 'integral(pi*((sqrt(x))^2 - (x^2)^2), x, 0, 1)', mistake: 'phantom-axis-shift', why: 'The $+1$ is part of each height above the x-axis; dropping it rotates a different region.' },
        ],
        correct: 0,
        explanation: '$V = \\pi\\int_0^1 \\left[R(x)^2 - r(x)^2\\right]dx$ with $R = \\sqrt{x} + 1$, $r = x^2 + 1$.',
        result: { latex: 'V = \\pi\\int_0^1 \\left[(\\sqrt{x} + 1)^2 - (x^2 + 1)^2\\right]dx = \\pi\\int_0^1 \\left(x + 2\\sqrt{x} - x^4 - 2x^2\\right)dx' },
        check: { kind: 'value', expected: '29*pi/30' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\frac{29\\pi}{30}', expr: '29*pi/30' },
          { latex: 'V = \\frac{3\\pi}{10}', expr: '3*pi/10', mistake: 'algebra-error', why: 'Both squares were expanded without their cross terms $2\\sqrt{x}$ and $2x^2$, leaving $x - x^4$.' },
          { latex: 'V = \\frac{79\\pi}{30}', expr: '79*pi/30', mistake: 'power-rule-int-coefficient', why: '$\\int 2\\sqrt{x}\\,dx = \\frac43 x^{3/2}$; multiplying by $\\frac32$ instead gives 3.' },
          { latex: 'V = \\frac{23\\pi}{10}', expr: '23*pi/10', mistake: 'sign-error', why: 'The $-2x^2$ term was integrated with a plus sign.' },
          { latex: 'V = \\frac{22\\pi}{15}', expr: '22*pi/15', mistake: 'power-rule-int-coefficient', why: '$\\int x\\,dx = \\frac{x^2}{2}$; without the $\\frac12$ the first term is 1.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left(\\frac12 + \\frac43 - \\frac15 - \\frac23\\right) = \\pi \\cdot \\frac{15 + 40 - 6 - 20}{30} = \\frac{29\\pi}{30}$.',
        result: { latex: 'V = \\pi\\left[\\frac{x^2}{2} + \\frac43 x^{3/2} - \\frac{x^5}{5} - \\frac{2x^3}{3}\\right]_0^1 = \\frac{29\\pi}{30}' },
        check: { kind: 'value', expected: '29*pi/30' },
      },
    ],
    final: {
      latex: 'V = \\frac{29\\pi}{30}',
      expr: '29*pi/30',
      check: { kind: 'definite-integral', integrand: 'pi*((sqrt(x) + 1)^2 - (x^2 + 1)^2)', lower: '0', upper: '1' },
      recap: 'Both curves sit above the axis, so each slice is a washer: $R$ is the top curve $\\sqrt{x} + 1$ and $r$ the bottom curve $x^2 + 1$; square each radius before subtracting.',
    },
  },
  {
    id: 'vd-s-07',
    topic: 'volumes-disks',
    title: 'Logarithm region about the y-axis',
    difficulty: 1,
    statement: { text: 'The region enclosed by $y = \\ln x$, $y = 0$, and $x = 3$ is rotated about the y-axis. Find the volume using the disk/washer method.' },
    variable: 'y',
    steps: [
      {
        prompt: 'How should the region be sliced, and over which interval?',
        options: [
          { text: 'Horizontal washers, $y$ from 0 to $\\ln 3$' },
          { text: 'Vertical disks, $x$ from 1 to 3', mistake: 'wrong-integration-variable', why: 'That is the plan for rotation about the x-axis; for the y-axis, disk/washer slices are horizontal.' },
          { text: 'Horizontal washers, $y$ from 1 to 3', mistake: 'bounds-wrong-axis', why: '1 to 3 is the x-range; the heights run from $y = 0$ to $y = \\ln 3$.' },
          { text: 'Horizontal disks, $y$ from 0 to 3', mistake: 'washer-as-disk', why: 'At height $y$ the region starts at $x = e^y \\ge 1$, so each slice has a hole; and the top height is $\\ln 3$, not 3.' },
          { text: 'Vertical washers, $x$ from 0 to 3', mistake: 'wrong-integration-variable', why: 'Vertical slices are parallel to the y-axis; disk/washer slices must be perpendicular to the axis of rotation.' },
        ],
        correct: 0,
        explanation: 'For a vertical axis, slice horizontally: the region spans heights from $y = 0$ up to $y = \\ln 3$, where the curve meets $x = 3$.',
        result: { text: 'Horizontal washers, $0 \\le y \\le \\ln 3$; the curve is $x = e^y$' },
      },
      {
        prompt: 'At height $y$, what are the outer and inner radii?',
        options: [
          { latex: 'R = 3,\\ r = e^{y}', expr: '[3, exp(y)]' },
          { latex: 'R = 3,\\ r = \\ln y', expr: '[3, log(y)]', mistake: 'inverse-function-wrong', why: 'Solving $y = \\ln x$ for $x$ gives $x = e^y$.' },
          { latex: 'R = 3,\\ r = 0', expr: '[3, 0]', mistake: 'washer-as-disk', why: 'The region starts at $x = e^y$, not at the axis, so there is a hole of radius $e^y$.' },
          { latex: 'R = \\ln x,\\ r = 0', expr: '[log(x), 0]', mistake: 'wrong-integration-variable', why: '$\\ln x$ is the height of a vertical slice, the disk radius for rotation about the x-axis; here the slices are horizontal.' },
          { latex: 'R = 3 - e^{y},\\ r = 0', expr: '[3 - exp(y), 0]', mistake: 'washer-difference-squared', why: '$3 - e^y$ is the slice length; using it as one radius computes $\\pi(R - r)^2$.' },
        ],
        correct: 0,
        explanation: 'The slice runs from the curve $x = e^y$ (near the axis) to the line $x = 3$ (far): $R = 3$, $r = e^y$.',
        result: { latex: 'R(y) = 3,\\quad r(y) = e^{y}' },
        check: { kind: 'value', expected: '[3, exp(y)]' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\pi\\int_0^{\\ln 3} \\left[3^2 - (e^{y})^2\\right]dy', expr: 'integral(pi*(3^2 - exp(y)^2), y, 0, log(3))' },
          { latex: 'V = \\pi\\int_0^{\\ln 3} \\left(3 - e^{y}\\right)^2dy', expr: 'integral(pi*(3 - exp(y))^2, y, 0, log(3))', mistake: 'washer-difference-squared', why: 'This is $\\pi(R - r)^2$; the washer area is $\\pi(R^2 - r^2)$.' },
          { latex: 'V = \\pi\\int_0^{\\ln 3} \\left[3^2 - (\\ln y)^2\\right]dy', expr: 'integral(pi*(3^2 - log(y)^2), y, 0, log(3))', mistake: 'inverse-function-wrong', why: 'Solving $y = \\ln x$ for $x$ gives $x = e^y$, so the inner radius is $e^y$, not $\\ln y$.' },
          { latex: 'V = \\pi\\int_1^3 (\\ln x)^2\\,dx', expr: 'integral(pi*log(x)^2, x, 1, 3)', mistake: 'wrong-integration-variable', why: 'Vertical disks of radius $\\ln x$ build the solid about the x-axis, not the y-axis.' },
          { latex: 'V = \\pi\\int_0^{\\ln 3} 3^2\\,dy', expr: 'integral(pi*3^2, y, 0, log(3))', mistake: 'washer-as-disk', why: 'The hole of radius $e^y$ was not removed.' },
          { latex: 'V = \\pi\\int_0^3 \\left[3^2 - (e^{y})^2\\right]dy', expr: 'integral(pi*(3^2 - exp(y)^2), y, 0, 3)', mistake: 'bounds-wrong-axis', why: 'The heights run from 0 to $\\ln 3$; 3 is an x-value.' },
        ],
        correct: 0,
        explanation: '$V = \\pi\\int_0^{\\ln 3} \\left[R^2 - r^2\\right]dy = \\pi\\int_0^{\\ln 3} \\left(9 - e^{2y}\\right)dy$.',
        result: { latex: 'V = \\pi\\int_0^{\\ln 3} \\left(9 - e^{2y}\\right)dy' },
        check: { kind: 'value', expected: 'pi*(9*log(3) - 4)' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\pi(9\\ln 3 - 4)', expr: 'pi*(9*log(3) - 4)' },
          { latex: 'V = \\pi\\left(9\\ln 3 - \\frac{9}{2}\\right)', expr: 'pi*(9*log(3) - 9/2)', mistake: 'ftc-not-subtracted', why: '$F(0) = -\\frac12$ was never subtracted.' },
          { latex: 'V = \\pi(9\\ln 3 - 8)', expr: 'pi*(9*log(3) - 8)', mistake: 'exp-antiderivative-wrong', why: '$\\int e^{2y}\\,dy = \\frac{e^{2y}}{2}$; without the $\\frac12$ the subtracted part is $9 - 1 = 8$.' },
          { latex: 'V = \\pi(9\\ln 3 - 5)', expr: 'pi*(9*log(3) - 5)', mistake: 'sign-error', why: '$F(0) = -\\frac12$ was subtracted as $+\\frac12$: $-\\frac92 - \\frac12 = -5$.' },
          { latex: 'V = \\pi\\left(9\\ln 3 - \\frac{5}{2}\\right)', expr: 'pi*(9*log(3) - 5/2)', mistake: 'algebra-error', why: '$e^{2\\ln 3} = \\left(e^{\\ln 3}\\right)^2 = 9$, not $2 \\cdot 3 = 6$.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left[9y - \\frac{e^{2y}}{2}\\right]_0^{\\ln 3} = \\pi\\left(9\\ln 3 - \\frac92 + \\frac12\\right) = \\pi(9\\ln 3 - 4)$.',
        result: { latex: 'V = \\pi\\left[9y - \\frac{e^{2y}}{2}\\right]_0^{\\ln 3} = \\pi(9\\ln 3 - 4)' },
        check: { kind: 'value', expected: 'pi*(9*log(3) - 4)' },
      },
    ],
    final: {
      latex: 'V = \\pi(9\\ln 3 - 4)',
      expr: 'pi*(9*log(3) - 4)',
      check: { kind: 'definite-integral', integrand: 'pi*(3^2 - exp(2*y))', lower: '0', upper: 'log(3)' },
      recap: 'For a vertical axis, solve the curve for $x$ ($x = e^y$) and slice horizontally; the line $x = 3$ gives the outer radius and the curve the inner one.',
    },
  },
  {
    id: 'vd-s-08',
    topic: 'volumes-disks',
    title: 'Exponential region about the x-axis',
    difficulty: 1,
    statement: { text: 'The region under $y = e^{x}$ and above the x-axis, between $x = 0$ and $x = 1$, is rotated about the x-axis. Find the volume using the disk/washer method.' },
    steps: [
      {
        prompt: 'What do the slices look like?',
        options: [
          { text: 'Disks perpendicular to the x-axis, $x$ from 0 to 1' },
          { text: 'Disks perpendicular to the y-axis, $y$ from 1 to $e$', mistake: 'wrong-integration-variable', why: 'Slices must be perpendicular to the axis of rotation, the x-axis, so they are stacked along $x$.' },
          { text: 'Washers perpendicular to the x-axis, $x$ from 1 to $e$', mistake: 'bounds-wrong-axis', why: '1 to $e$ is the range of heights; $x$ runs from 0 to 1, and the region reaches the axis, so there is no hole.' },
          { text: 'Cylindrical shells from vertical slices, $x$ from 0 to 1', mistake: 'shell-orientation-wrong', why: 'Vertical slices are perpendicular to the x-axis; rotated about it they sweep out disks, not shells.' },
          { text: 'Washers perpendicular to the y-axis, $y$ from 0 to $e$', mistake: 'wrong-integration-variable', why: 'That is a plan for a vertical axis; for the x-axis the slices are vertical, stacked along $x$ from 0 to 1.' },
        ],
        correct: 0,
        explanation: 'Each vertical slice reaches from the axis up to the curve, so it sweeps out a disk; $x$ runs from 0 to 1.',
        result: { text: 'Disks perpendicular to the x-axis, $0 \\le x \\le 1$, radius $R(x) = e^x$' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\pi\\int_0^1 (e^{x})^2\\,dx', expr: 'integral(pi*exp(x)^2, x, 0, 1)' },
          { latex: 'V = \\pi\\int_0^1 e^{x}\\,dx', expr: 'integral(pi*exp(x), x, 0, 1)', mistake: 'radius-not-squared', why: 'The disk area is $\\pi R^2 = \\pi(e^x)^2$; the radius was not squared.' },
          { latex: 'V = \\pi\\int_0^1 e^{x^2}\\,dx', expr: 'integral(pi*exp(x^2), x, 0, 1)', mistake: 'algebra-error', why: '$(e^x)^2 = e^{2x}$, not $e^{x^2}$.' },
          { latex: 'V = \\pi\\int_1^{e} (e^{x})^2\\,dx', expr: 'integral(pi*exp(x)^2, x, 1, e)', mistake: 'bounds-wrong-axis', why: '1 to $e$ is the range of heights of the curve; the region runs from $x = 0$ to $x = 1$.' },
          { latex: 'V = \\pi\\int_1^{e} (\\ln y)^2\\,dy', expr: 'integral(pi*log(y)^2, y, 1, e)', mistake: 'wrong-integration-variable', why: 'Horizontal disks of radius $\\ln y$ belong to a rotation about the y-axis, and they do not even describe this region.' },
          { latex: 'V = 2\\pi\\int_0^1 x e^{x}\\,dx', expr: 'integral(2*pi*x*exp(x), x, 0, 1)', mistake: 'method-formula-swapped', why: '$2\\pi x \\cdot$ height is the shell formula for rotation about the y-axis.' },
        ],
        correct: 0,
        explanation: '$V = \\int_0^1 \\pi R(x)^2\\,dx = \\pi\\int_0^1 (e^x)^2\\,dx = \\pi\\int_0^1 e^{2x}\\,dx$.',
        result: { latex: 'V = \\pi\\int_0^1 (e^{x})^2\\,dx = \\pi\\int_0^1 e^{2x}\\,dx' },
        check: { kind: 'value', expected: 'pi*(e^2 - 1)/2' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\frac{\\pi(e^2 - 1)}{2}', expr: 'pi*(e^2 - 1)/2' },
          { latex: 'V = \\pi(e^2 - 1)', expr: 'pi*(e^2 - 1)', mistake: 'exp-antiderivative-wrong', why: '$\\int e^{2x}\\,dx = \\frac{e^{2x}}{2}$; the $\\frac12$ was dropped.' },
          { latex: 'V = \\frac{\\pi e^2}{2}', expr: 'pi*e^2/2', mistake: 'ftc-not-subtracted', why: '$F(0) = \\frac{e^0}{2} = \\frac12$ was never subtracted.' },
          { latex: 'V = 2\\pi(e^2 - 1)', expr: '2*pi*(e^2 - 1)', mistake: 'inner-constant-factor-missing', why: 'The antiderivative was multiplied by the inner constant 2 instead of divided by it.' },
          { latex: 'V = \\frac{\\pi(1 - e^2)}{2}', expr: 'pi*(1 - e^2)/2', mistake: 'ftc-order-swapped', why: 'This is $F(0) - F(1)$; the FTC subtracts the lower limit from the upper.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left[\\frac{e^{2x}}{2}\\right]_0^1 = \\pi\\left(\\frac{e^2}{2} - \\frac12\\right) = \\frac{\\pi(e^2 - 1)}{2}$.',
        result: { latex: 'V = \\pi\\left[\\frac{e^{2x}}{2}\\right]_0^1 = \\frac{\\pi(e^2 - 1)}{2}' },
        check: { kind: 'value', expected: 'pi*(e^2 - 1)/2' },
      },
    ],
    final: {
      latex: 'V = \\frac{\\pi(e^2 - 1)}{2}',
      expr: 'pi*(e^2 - 1)/2',
      check: { kind: 'definite-integral', integrand: 'pi*exp(2*x)', lower: '0', upper: '1' },
      recap: 'A region that reaches the axis gives disks: $V = \\pi\\int_0^1 (e^x)^2\\,dx$. Remember $(e^x)^2 = e^{2x}$ and the $\\frac12$ in its antiderivative.',
    },
  },
  {
    id: 'vd-s-09',
    topic: 'volumes-disks',
    title: 'Two curves about x = 4',
    difficulty: 2,
    statement: { text: 'Find the volume of the solid generated by rotating the region bounded by $x = \\sqrt{y}$ and $x = \\frac{y}{2}$ about the line $x = 4$. Use the disk/washer method.' },
    variable: 'y',
    steps: [
      {
        prompt: 'How should the region be sliced, and over which interval?',
        options: [
          { text: 'Horizontal washers, $y$ from 0 to 4' },
          { text: 'Vertical washers, $x$ from 0 to 2', mistake: 'wrong-integration-variable', why: 'The axis $x = 4$ is vertical; washers come from horizontal slices stacked along $y$.' },
          { text: 'Horizontal disks, $y$ from 0 to 2', mistake: 'bounds-wrong-axis', why: 'The curves meet at $(0, 0)$ and $(2, 4)$, so the heights run to 4; and the region never reaches $x = 4$, so each slice has a hole.' },
          { text: 'Horizontal washers, $y$ from 0 to 16', mistake: 'algebra-error', why: 'Squaring $\\sqrt{y} = \\frac{y}{2}$ gives $y = \\frac{y^2}{4}$, so $y = 0$ or $y = 4$.' },
          { text: 'Vertical disks, $x$ from 0 to 4', mistake: 'wrong-integration-variable', why: 'Vertical slices are parallel to the axis $x = 4$; disk/washer slices must be horizontal.' },
        ],
        correct: 0,
        explanation: '$\\sqrt{y} = \\frac{y}{2}$ gives $y = 0$ or $y = 4$; slices perpendicular to the vertical axis are horizontal.',
        result: { text: 'Horizontal washers, $0 \\le y \\le 4$; at height $y$ the region runs from $x = \\frac{y}{2}$ to $x = \\sqrt{y}$' },
      },
      {
        prompt: 'Measured from $x = 4$, what are the outer and inner radii at height $y$?',
        options: [
          { latex: 'R = 4 - \\frac{y}{2},\\ r = 4 - \\sqrt{y}', expr: '[4 - y/2, 4 - sqrt(y)]' },
          { latex: 'R = 4 - \\sqrt{y},\\ r = 4 - \\frac{y}{2}', expr: '[4 - sqrt(y), 4 - y/2]', mistake: 'radii-swapped', why: 'On $0 < y < 4$, $\\sqrt{y} > \\frac{y}{2}$, so $x = \\sqrt{y}$ is nearer to $x = 4$ and gives $r$.' },
          { latex: 'R = \\sqrt{y},\\ r = \\frac{y}{2}', expr: '[sqrt(y), y/2]', mistake: 'axis-shift-missing', why: 'Those are distances to the y-axis; distances to $x = 4$ are $4 - x$.' },
          { latex: 'R = \\frac{y}{2} - 4,\\ r = \\sqrt{y} - 4', expr: '[y/2 - 4, sqrt(y) - 4]', mistake: 'axis-shift-sign', why: 'The region lies left of $x = 4$, so the distances are $4 - x$; these are negative.' },
          { latex: 'R = 4 - \\frac{y}{2},\\ r = 0', expr: '[4 - y/2, 0]', mistake: 'washer-as-disk', why: 'The near edge $x = \\sqrt{y}$ is $4 - \\sqrt{y}$ from the axis, so there is a hole.' },
          { latex: 'R = \\sqrt{y} - \\frac{y}{2},\\ r = 0', expr: '[sqrt(y) - y/2, 0]', mistake: 'washer-difference-squared', why: '$\\sqrt{y} - \\frac{y}{2}$ is the slice length; using it as one radius computes $\\pi(R - r)^2$.' },
        ],
        correct: 0,
        explanation: 'With the axis on the right, the left curve $x = \\frac{y}{2}$ is farther ($R = 4 - \\frac{y}{2}$) and the right curve $x = \\sqrt{y}$ is nearer ($r = 4 - \\sqrt{y}$).',
        result: { latex: 'R(y) = 4 - \\frac{y}{2},\\quad r(y) = 4 - \\sqrt{y}' },
        check: { kind: 'value', expected: '[4 - y/2, 4 - sqrt(y)]' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\pi\\int_0^4 \\left[\\left(4 - \\frac{y}{2}\\right)^2 - \\left(4 - \\sqrt{y}\\right)^2\\right]dy', expr: 'integral(pi*((4 - y/2)^2 - (4 - sqrt(y))^2), y, 0, 4)' },
          { latex: 'V = \\pi\\int_0^4 \\left[\\left(4 - \\sqrt{y}\\right)^2 - \\left(4 - \\frac{y}{2}\\right)^2\\right]dy', expr: 'integral(pi*((4 - sqrt(y))^2 - (4 - y/2)^2), y, 0, 4)', mistake: 'radii-swapped', why: 'Outer squared minus inner squared; this order makes the integral negative.' },
          { latex: 'V = \\pi\\int_0^4 \\left[(\\sqrt{y})^2 - \\left(\\frac{y}{2}\\right)^2\\right]dy', expr: 'integral(pi*((sqrt(y))^2 - (y/2)^2), y, 0, 4)', mistake: 'axis-shift-missing', why: 'This is the volume about the y-axis; about $x = 4$ the radii are $4 - x$.' },
          { latex: 'V = \\pi\\int_0^4 \\left(\\sqrt{y} - \\frac{y}{2}\\right)^2dy', expr: 'integral(pi*(sqrt(y) - y/2)^2, y, 0, 4)', mistake: 'washer-difference-squared', why: 'This is $\\pi(R - r)^2$; the washer area is $\\pi(R^2 - r^2)$.' },
          { latex: 'V = \\pi\\int_0^4 \\left(4 - \\frac{y}{2}\\right)^2dy', expr: 'integral(pi*(4 - y/2)^2, y, 0, 4)', mistake: 'washer-as-disk', why: 'The hole of radius $4 - \\sqrt{y}$ was not removed.' },
          { latex: 'V = \\pi\\int_0^4 \\left[\\left(4 + \\sqrt{y}\\right)^2 - \\left(4 + \\frac{y}{2}\\right)^2\\right]dy', expr: 'integral(pi*((4 + sqrt(y))^2 - (4 + y/2)^2), y, 0, 4)', mistake: 'axis-shift-sign', why: 'Adding 4 measures distance to $x = -4$; the axis $x = 4$ is to the right, so distances are $4 - x$.' },
        ],
        correct: 0,
        explanation: '$V = \\pi\\int_0^4 \\left[R(y)^2 - r(y)^2\\right]dy$ with $R = 4 - \\frac{y}{2}$ and $r = 4 - \\sqrt{y}$.',
        result: { latex: 'V = \\pi\\int_0^4 \\left[\\left(4 - \\frac{y}{2}\\right)^2 - \\left(4 - \\sqrt{y}\\right)^2\\right]dy = \\pi\\int_0^4 \\left(8\\sqrt{y} - 5y + \\frac{y^2}{4}\\right)dy' },
        check: { kind: 'value', expected: '8*pi' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = 8\\pi', expr: '8*pi' },
          { latex: 'V = 24\\pi', expr: '24*pi', mistake: 'algebra-error', why: '$\\left(4 - \\frac{y}{2}\\right)^2 = 16 - 4y + \\frac{y^2}{4}$; using $-2y$ for the cross term gives $-3y$ in place of $-5y$.' },
          { latex: 'V = \\frac{184\\pi}{3}', expr: '184*pi/3', mistake: 'power-rule-int-coefficient', why: '$\\int 8\\sqrt{y}\\,dy = \\frac{16}{3}y^{3/2}$; multiplying by $\\frac32$ instead gives 96 at $y = 4$.' },
          { latex: 'V = \\frac{152\\pi}{3}', expr: '152*pi/3', mistake: 'arithmetic-error', why: '$4^{3/2} = 8$, not 16.' },
          { latex: 'V = -\\frac{104\\pi}{3}', expr: '-104*pi/3', mistake: 'algebra-error', why: '$(4 - \\sqrt{y})^2 = 16 - 8\\sqrt{y} + y$; dropping the cross term removes the $8\\sqrt{y}$.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left[\\frac{16}{3}y^{3/2} - \\frac{5y^2}{2} + \\frac{y^3}{12}\\right]_0^4 = \\pi\\left(\\frac{128}{3} - 40 + \\frac{16}{3}\\right) = 8\\pi$.',
        result: { latex: 'V = \\pi\\left[\\frac{16}{3}y^{3/2} - \\frac{5y^2}{2} + \\frac{y^3}{12}\\right]_0^4 = 8\\pi' },
        check: { kind: 'value', expected: '8*pi' },
      },
    ],
    final: {
      latex: 'V = 8\\pi',
      expr: '8*pi',
      check: { kind: 'definite-integral', integrand: 'pi*((4 - y/2)^2 - (4 - sqrt(y))^2)', lower: '0', upper: '4' },
      recap: 'With the axis $x = 4$ to the right of the region, every radius is $4 - x$: the far curve $x = \\frac{y}{2}$ gives $R$ and the near curve $x = \\sqrt{y}$ gives $r$.',
    },
  },
  {
    id: 'vd-s-10',
    topic: 'volumes-disks',
    title: 'Circular cross-sections on a curved base',
    difficulty: 2,
    statement: { text: 'The base of a solid is the region between $y = 2 - x^2$ (above) and $y = x^2$ (below). Cross-sections perpendicular to the x-axis are circular disks whose diameters run across the base. Find the volume.' },
    steps: [
      {
        prompt: 'What is the diameter $D(x)$ of the disk at $x$?',
        options: [
          { latex: 'D(x) = 2 - 2x^2', expr: '2 - 2*x^2' },
          { latex: 'D(x) = 2', expr: '2', mistake: 'sum-instead-of-difference', why: '$(2 - x^2) + x^2 = 2$ adds the curves; the diameter is top minus bottom.' },
          { latex: 'D(x) = 2 - x^2', expr: '2 - x^2', mistake: 'single-function-area', why: 'The diameter runs from the bottom curve $y = x^2$, not from the x-axis.' },
          { latex: 'D(x) = 1 - x^2', expr: '1 - x^2', mistake: 'diameter-as-radius', why: '$1 - x^2$ is half the gap (the radius); the full distance between the curves is $2 - 2x^2$.' },
          { latex: 'D(x) = 2x^2 - 2', expr: '2*x^2 - 2', mistake: 'top-bottom-swapped', why: 'Bottom minus top is negative for $|x| < 1$; a length is top minus bottom.' },
        ],
        correct: 0,
        explanation: 'The diameter is the vertical distance across the base: $(2 - x^2) - x^2 = 2 - 2x^2$.',
        result: { latex: 'D(x) = (2 - x^2) - x^2 = 2 - 2x^2' },
        check: { kind: 'value', expected: '(2 - x^2) - x^2' },
      },
      {
        prompt: 'What is the area $A(x)$ of the disk at $x$?',
        options: [
          { latex: 'A(x) = \\pi(1 - x^2)^2', expr: 'pi*(1 - x^2)^2' },
          { latex: 'A(x) = \\pi(2 - 2x^2)^2', expr: 'pi*(2 - 2*x^2)^2', mistake: 'diameter-as-radius', why: '$2 - 2x^2$ is the diameter; the radius is half of it, $1 - x^2$.' },
          { latex: 'A(x) = \\pi(1 - x^2)', expr: 'pi*(1 - x^2)', mistake: 'radius-not-squared', why: 'The radius $1 - x^2$ must be squared.' },
          { latex: 'A(x) = \\frac{\\pi}{2}(1 - x^2)^2', expr: 'pi/2*(1 - x^2)^2', mistake: 'cross-section-area-wrong', why: '$\\frac12\\pi r^2$ is a semicircle; these cross-sections are full disks.' },
          { latex: 'A(x) = (1 - x^2)^2', expr: '(1 - x^2)^2', mistake: 'pi-missing', why: 'A disk of radius $r$ has area $\\pi r^2$; the $\\pi$ is missing.' },
          { latex: 'A(x) = \\pi(1 - x^4)', expr: 'pi*(1 - x^4)', mistake: 'algebra-error', why: '$(1 - x^2)^2 = 1 - 2x^2 + x^4$, not $1 - x^4$.' },
        ],
        correct: 0,
        explanation: 'Radius $= \\frac{D}{2} = 1 - x^2$, so $A(x) = \\pi(1 - x^2)^2$.',
        result: { latex: 'r(x) = \\frac{2 - 2x^2}{2} = 1 - x^2,\\quad A(x) = \\pi(1 - x^2)^2' },
        check: { kind: 'value', expected: 'pi*((2 - 2*x^2)/2)^2' },
      },
      {
        prompt: 'Which integral gives the volume?',
        options: [
          { latex: 'V = \\pi\\int_{-1}^{1} (1 - x^2)^2\\,dx', expr: 'integral(pi*(1 - x^2)^2, x, -1, 1)' },
          { latex: 'V = \\pi\\int_0^1 (1 - x^2)^2\\,dx', expr: 'integral(pi*(1 - x^2)^2, x, 0, 1)', mistake: 'missing-intersection', why: '$2 - x^2 = x^2$ has two solutions, $x = \\pm 1$; starting at 0 drops half the solid.' },
          { latex: 'V = \\pi\\int_{-\\sqrt{2}}^{\\sqrt{2}} (1 - x^2)^2\\,dx', expr: 'integral(pi*(1 - x^2)^2, x, -sqrt(2), sqrt(2))', mistake: 'single-function-area', why: '$\\pm\\sqrt{2}$ are where the top curve meets the x-axis; the base ends where the two curves meet, at $x = \\pm 1$.' },
          { latex: 'V = \\pi\\int_{-1}^{1} (2 - 2x^2)^2\\,dx', expr: 'integral(pi*(2 - 2*x^2)^2, x, -1, 1)', mistake: 'diameter-as-radius', why: 'The diameter $2 - 2x^2$ was used as the radius, making each slice 4 times too big.' },
          { latex: 'V = \\pi\\int_{-1}^{1} \\left[(2 - x^2)^2 - (x^2)^2\\right]dx', expr: 'integral(pi*((2 - x^2)^2 - (x^2)^2), x, -1, 1)', mistake: 'formula-swapped', why: 'This is the washer volume for rotating the base about the x-axis; here the disks stand on the base.' },
        ],
        correct: 0,
        explanation: 'The curves meet where $2 - x^2 = x^2$, at $x = \\pm 1$, so $V = \\int_{-1}^{1} \\pi(1 - x^2)^2\\,dx$.',
        result: { latex: 'V = \\pi\\int_{-1}^{1} (1 - x^2)^2\\,dx' },
        check: { kind: 'value', expected: '16*pi/15' },
      },
      {
        prompt: 'Evaluate the integral.',
        options: [
          { latex: 'V = \\frac{16\\pi}{15}', expr: '16*pi/15' },
          { latex: 'V = \\frac{8\\pi}{15}', expr: '8*pi/15', mistake: 'ftc-not-subtracted', why: 'Only $F(1) = \\frac{8}{15}$ was used; $F(-1) = -\\frac{8}{15}$ must be subtracted.' },
          { latex: 'V = \\frac{8\\pi}{5}', expr: '8*pi/5', mistake: 'algebra-error', why: '$(1 - x^2)^2$ was expanded as $1 - x^4$; the $-2x^2$ term is missing.' },
          { latex: 'V = 0', expr: '0', mistake: 'negative-squared-wrong', why: 'Odd powers of $-1$ are negative, so $F(-1) = -\\frac{8}{15}$; treating them as $+1$ makes $F(-1) = F(1)$.' },
          { latex: 'V = \\frac{56\\pi}{15}', expr: '56*pi/15', mistake: 'sign-error', why: 'The $-2x^2$ term was integrated with a plus sign.' },
        ],
        correct: 0,
        explanation: '$\\pi\\left[x - \\frac{2x^3}{3} + \\frac{x^5}{5}\\right]_{-1}^{1} = \\pi\\left(\\frac{8}{15} + \\frac{8}{15}\\right) = \\frac{16\\pi}{15}$.',
        result: { latex: 'V = \\pi\\left[x - \\frac{2x^3}{3} + \\frac{x^5}{5}\\right]_{-1}^{1} = \\frac{16\\pi}{15}' },
        check: { kind: 'value', expected: '16*pi/15' },
      },
    ],
    final: {
      latex: 'V = \\frac{16\\pi}{15}',
      expr: '16*pi/15',
      check: { kind: 'definite-integral', integrand: 'pi*((2 - 2*x^2)/2)^2', lower: '-1', upper: '1' },
      recap: 'The base gives the diameter (top minus bottom, $2 - 2x^2$); halve it for the radius before using $\\pi r^2$, then integrate between the intersection points $x = \\pm 1$.',
    },
  },
];
