import type { FlashGenerator, FlashItem } from '../types';

/** Flash Drill items for topic "antiderivatives". Authored by content-author; verified by math-verifier. */
export const flash: FlashItem[] = [
  // ───────────────────────── antiderivative: basic table and one-step substitutions ─────────────────────────
  {
    id: 'ad-f-001',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{1}{x^3}' },
    options: [
      { latex: '-\\frac{1}{2x^2} + C', expr: '-1/(2*x^2)' },
      {
        latex: '\\frac{1}{2x^2} + C',
        expr: '1/(2*x^2)',
        mistake: 'sign-error',
        why: 'The new exponent is −3 + 1 = −2, and dividing by −2 makes the result negative; that minus sign was dropped.',
      },
      {
        latex: '-\\frac{1}{3x^2} + C',
        expr: '-1/(3*x^2)',
        mistake: 'power-rule-int-coefficient',
        why: 'The exponent was raised to −2 correctly, but the division was by the old exponent −3 instead of the new exponent −2.',
      },
      {
        latex: '-\\frac{1}{4x^4} + C',
        expr: '-1/(4*x^4)',
        mistake: 'power-rule-int-exponent',
        why: 'The exponent was lowered from −3 to −4 (as when differentiating) instead of raised to −2.',
      },
      {
        latex: '-\\frac{3}{x^4} + C',
        expr: '-3/x^4',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of x^{−3}, namely −3x^{−4}, not an antiderivative.',
      },
      {
        latex: '\\ln|x^3| + C',
        expr: 'log(abs(x^3))',
        mistake: 'ln-misapplied',
        why: 'Only x^{−1} integrates to a logarithm; 1/x³ = x^{−3} needs the power rule.',
      },
    ],
    correct: 0,
    explanation: '$\\int x^{-3}\\,dx = \\frac{x^{-2}}{-2} + C = -\\frac{1}{2x^2} + C$.',
    check: { kind: 'antiderivative', integrand: '1/x^3' },
    difficulty: 1,
  },
  {
    id: 'ad-f-002',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: 'x\\sqrt{x}' },
    options: [
      { latex: '\\frac{2}{5}x^{5/2} + C', expr: '2/5*x^(5/2)' },
      {
        latex: '\\frac{2}{3}x^{5/2} + C',
        expr: '2/3*x^(5/2)',
        mistake: 'power-rule-int-coefficient',
        why: 'Divided by the old exponent 3/2 instead of the new exponent 5/2.',
      },
      {
        latex: '\\frac{5}{2}x^{5/2} + C',
        expr: '5/2*x^(5/2)',
        mistake: 'power-rule-int-coefficient',
        why: 'Multiplied by the new exponent 5/2 instead of dividing by it.',
      },
      {
        latex: '\\frac{1}{3}x^{7/2} + C',
        expr: '1/3*x^(7/2)',
        mistake: 'product-rule-integral',
        why: 'x and √x were integrated separately and multiplied: (x²/2)(⅔x^{3/2}). Combine x·x^{1/2} = x^{3/2} first.',
      },
      {
        latex: '\\frac{3}{2}x^{1/2} + C',
        expr: '3/2*x^(1/2)',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of x^{3/2}; integrating raises the exponent instead of lowering it.',
      },
    ],
    correct: 0,
    explanation: '$x\\sqrt{x} = x^{3/2}$, so $\\int x^{3/2}\\,dx = \\frac{x^{5/2}}{5/2} + C = \\frac{2}{5}x^{5/2} + C$.',
    check: { kind: 'antiderivative', integrand: 'x*sqrt(x)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-003',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{1}{x} - \\frac{1}{x^2}' },
    options: [
      { latex: '\\ln|x| + \\frac{1}{x} + C', expr: 'log(abs(x)) + 1/x' },
      {
        latex: '\\ln|x| - \\frac{1}{x} + C',
        expr: 'log(abs(x)) - 1/x',
        mistake: 'sign-error',
        why: '∫x^{−2}dx = x^{−1}/(−1) = −1/x, and subtracting it gives +1/x; the sign from dividing by −1 was lost.',
      },
      {
        latex: '\\ln|x| + \\frac{1}{2x} + C',
        expr: 'log(abs(x)) + 1/(2*x)',
        mistake: 'power-rule-int-coefficient',
        why: 'For x^{−2} the division was by the old exponent −2 instead of the new exponent −1.',
      },
      {
        latex: '\\ln|x| + \\frac{1}{3x^3} + C',
        expr: 'log(abs(x)) + 1/(3*x^3)',
        mistake: 'power-rule-int-exponent',
        why: 'The exponent of x^{−2} was lowered to −3 instead of raised to −1.',
      },
      {
        latex: '\\ln|x| - \\ln|x^2| + C',
        expr: 'log(abs(x)) - log(abs(x^2))',
        mistake: 'ln-misapplied',
        why: 'The logarithm rule is only for x^{−1}; 1/x² = x^{−2} needs the power rule.',
      },
      {
        latex: '-\\frac{1}{x^2} + \\frac{2}{x^3} + C',
        expr: '-1/x^2 + 2/x^3',
        mistake: 'differentiated-instead',
        why: 'Both terms were differentiated: (1/x)′ = −1/x² and (−1/x²)′ = 2/x³.',
      },
    ],
    correct: 0,
    explanation: '$\\int\\frac{dx}{x} = \\ln|x|$ and $\\int x^{-2}\\,dx = -x^{-1}$, so the result is $\\ln|x| + \\frac{1}{x} + C$.',
    check: { kind: 'antiderivative', integrand: '1/x - 1/x^2' },
    difficulty: 1,
  },
  {
    id: 'ad-f-004',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '3^{2x}' },
    options: [
      { latex: '\\frac{3^{2x}}{2\\ln 3} + C', expr: '3^(2*x)/(2*log(3))' },
      {
        latex: '\\frac{3^{2x}}{\\ln 3} + C',
        expr: '3^(2*x)/log(3)',
        mistake: 'inner-constant-factor-missing',
        why: 'The factor 1/2 for the inner 2x is missing: d/dx 3^{2x} = 3^{2x} · ln 3 · 2.',
      },
      {
        latex: '\\frac{2\\cdot 3^{2x}}{\\ln 3} + C',
        expr: '2*3^(2*x)/log(3)',
        mistake: 'inner-constant-factor-missing',
        why: 'Multiplied by the inner constant 2 instead of dividing by it.',
      },
      {
        latex: '2\\cdot 3^{2x}\\ln 3 + C',
        expr: '2*3^(2*x)*log(3)',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of 3^{2x}; integrating divides by 2 ln 3 instead of multiplying.',
      },
      {
        latex: '\\frac{3^{2x+1}}{2x+1} + C',
        expr: '3^(2*x+1)/(2*x+1)',
        mistake: 'exp-antiderivative-wrong',
        why: 'The power rule does not apply when the variable is in the exponent.',
      },
      {
        latex: '\\frac{3^{2x}}{2} + C',
        expr: '3^(2*x)/2',
        mistake: 'exp-base-log-missing',
        why: 'Treated 3^{2x} like e^{2x}; for base 3 you must also divide by ln 3.',
      },
    ],
    correct: 0,
    explanation: '$\\frac{d}{dx}3^{2x} = 3^{2x}\\ln 3\\cdot 2$, so $\\int 3^{2x}\\,dx = \\frac{3^{2x}}{2\\ln 3} + C$.',
    check: { kind: 'antiderivative', integrand: '3^(2*x)' },
    difficulty: 2,
  },
  {
    id: 'ad-f-005',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\csc^2 x' },
    options: [
      { latex: '-\\cot x + C', expr: '-cot(x)' },
      {
        latex: '\\cot x + C',
        expr: 'cot(x)',
        mistake: 'trig-antiderivative-sign',
        why: 'd/dx cot x = −csc²x, so the antiderivative of csc²x carries a minus sign.',
      },
      {
        latex: '\\tan x + C',
        expr: 'tan(x)',
        mistake: 'trig-antiderivative-swapped',
        why: 'tan x is the antiderivative of sec²x; csc²x pairs with −cot x.',
      },
      {
        latex: '-\\csc x + C',
        expr: '-csc(x)',
        mistake: 'trig-antiderivative-swapped',
        why: '−csc x is the antiderivative of csc x cot x, not of csc²x.',
      },
      {
        latex: '\\frac{\\csc^3 x}{3} + C',
        expr: 'csc(x)^3/3',
        mistake: 'dx-not-replaced',
        why: 'Used the power rule on csc x as if it were the variable; that needs d(csc x) = −csc x cot x dx, which is not in the integrand.',
      },
      {
        latex: '-2\\csc^2 x\\cot x + C',
        expr: '-2*csc(x)^2*cot(x)',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of csc²x (chain rule), not an antiderivative.',
      },
    ],
    correct: 0,
    explanation: 'Since $\\frac{d}{dx}(-\\cot x) = \\csc^2 x$, $\\int\\csc^2 x\\,dx = -\\cot x + C$.',
    check: { kind: 'antiderivative', integrand: 'csc(x)^2' },
    difficulty: 1,
  },
  {
    id: 'ad-f-006',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\csc(4x)\\cot(4x)' },
    options: [
      { latex: '-\\frac{1}{4}\\csc(4x) + C', expr: '-csc(4*x)/4' },
      {
        latex: '\\frac{1}{4}\\csc(4x) + C',
        expr: 'csc(4*x)/4',
        mistake: 'trig-antiderivative-sign',
        why: 'd/du csc u = −csc u cot u, so ∫csc u cot u du = −csc u; the minus sign was dropped.',
      },
      {
        latex: '-\\csc(4x) + C',
        expr: '-csc(4*x)',
        mistake: 'inner-constant-factor-missing',
        why: 'With u = 4x, dx = du/4; the factor 1/4 is missing.',
      },
      {
        latex: '-4\\csc(4x) + C',
        expr: '-4*csc(4*x)',
        mistake: 'inner-constant-factor-missing',
        why: 'Multiplied by the inner constant 4 instead of dividing by it.',
      },
      {
        latex: '-\\frac{1}{4}\\cot(4x) + C',
        expr: '-cot(4*x)/4',
        mistake: 'trig-antiderivative-swapped',
        why: '−cot u is the antiderivative of csc²u; ∫csc u cot u du = −csc u.',
      },
    ],
    correct: 0,
    explanation: 'With $u = 4x$: $\\frac{1}{4}\\int\\csc u\\cot u\\,du = -\\frac{1}{4}\\csc(4x) + C$.',
    check: { kind: 'antiderivative', integrand: 'csc(4*x)*cot(4*x)' },
    domain: [0.1, 0.7],
    difficulty: 1,
  },
  {
    id: 'ad-f-007',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{1}{1+9x^2}' },
    options: [
      { latex: '\\frac{1}{3}\\arctan(3x) + C', expr: 'atan(3*x)/3' },
      {
        latex: '\\arctan(3x) + C',
        expr: 'atan(3*x)',
        mistake: 'inner-constant-factor-missing',
        why: 'With u = 3x, dx = du/3; the factor 1/3 is missing.',
      },
      {
        latex: '3\\arctan(3x) + C',
        expr: '3*atan(3*x)',
        mistake: 'inner-constant-factor-missing',
        why: 'Multiplied by the inner constant 3 instead of dividing by it.',
      },
      {
        latex: '\\frac{1}{9}\\arctan(3x) + C',
        expr: 'atan(3*x)/9',
        mistake: 'du-constant-wrong',
        why: 'Divided by 9, the coefficient of x²; with u = 3x, du = 3 dx, so the factor is 1/3.',
      },
      {
        latex: '\\ln|1+9x^2| + C',
        expr: 'log(abs(1+9*x^2))',
        mistake: 'ln-misapplied',
        why: 'A logarithm needs the derivative 18x of the denominator on top; 1/(1 + u²) integrates to arctan u.',
      },
      {
        latex: '\\frac{1}{3}\\arcsin(3x) + C',
        expr: 'asin(3*x)/3',
        mistake: 'inverse-trig-confused',
        why: 'arcsin belongs to 1/√(1 − u²); 1/(1 + u²) belongs to arctan.',
      },
    ],
    correct: 0,
    explanation: 'Let $u = 3x$, $du = 3\\,dx$: $\\frac{1}{3}\\int\\frac{du}{1+u^2} = \\frac{1}{3}\\arctan(3x) + C$.',
    check: { kind: 'antiderivative', integrand: '1/(1+9*x^2)' },
    domain: [-0.3, 0.3],
    difficulty: 1,
  },
  {
    id: 'ad-f-008',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{1}{\\sqrt{1-4x^2}}' },
    options: [
      { latex: '\\frac{1}{2}\\sin^{-1}(2x) + C', expr: 'asin(2*x)/2' },
      {
        latex: '\\sin^{-1}(2x) + C',
        expr: 'asin(2*x)',
        mistake: 'inner-constant-factor-missing',
        why: 'u = 2x gives dx = du/2; the factor 1/2 is missing.',
      },
      {
        latex: '\\frac{1}{4}\\sin^{-1}(2x) + C',
        expr: 'asin(2*x)/4',
        mistake: 'du-constant-wrong',
        why: 'Divided by 4, the coefficient of x², instead of by 2, the derivative of u = 2x.',
      },
      {
        latex: '\\frac{1}{2}\\tan^{-1}(2x) + C',
        expr: 'atan(2*x)/2',
        mistake: 'inverse-trig-confused',
        why: 'tan⁻¹ belongs to 1/(1 + u²); 1/√(1 − u²) integrates to sin⁻¹u.',
      },
      {
        latex: '\\frac{1}{2}\\cos^{-1}(2x) + C',
        expr: 'acos(2*x)/2',
        mistake: 'inverse-trig-confused',
        why: 'd/du cos⁻¹u = −1/√(1 − u²), so this has the wrong sign.',
      },
      {
        latex: '-\\frac{1}{4}\\sqrt{1-4x^2} + C',
        expr: '-sqrt(1-4*x^2)/4',
        mistake: 'u-choice-wrong',
        why: 'Took u = 1 − 4x² and used the power rule, but du = −8x dx needs a factor x that is not in the integrand.',
      },
    ],
    correct: 0,
    explanation: 'With $u = 2x$, $du = 2\\,dx$: $\\frac{1}{2}\\int\\frac{du}{\\sqrt{1-u^2}} = \\frac{1}{2}\\sin^{-1}(2x) + C$.',
    check: { kind: 'antiderivative', integrand: '1/sqrt(1-4*x^2)' },
    domain: [-0.45, 0.45],
    difficulty: 1,
  },
  {
    id: 'ad-f-009',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { text: 'Here $x > 1$.', latex: '\\frac{1}{x\\sqrt{x^2-1}}' },
    options: [
      { latex: '\\sec^{-1}(x) + C', expr: 'asec(x)' },
      {
        latex: '\\tan^{-1}(x) + C',
        expr: 'atan(x)',
        mistake: 'inverse-trig-confused',
        why: 'tan⁻¹x is the antiderivative of 1/(1 + x²).',
      },
      {
        latex: '-\\sec^{-1}(x) + C',
        expr: '-asec(x)',
        mistake: 'sign-error',
        why: 'For x > 1, d/dx sec⁻¹x = 1/(x√(x² − 1)) is positive; there is no minus sign.',
      },
      {
        latex: '\\sqrt{x^2-1} + C',
        expr: 'sqrt(x^2-1)',
        mistake: 'u-choice-wrong',
        why: 'Took u = x² − 1 and used the power rule, but du = 2x dx needs x in the numerator, not 1/x.',
      },
      {
        latex: '\\ln|x\\sqrt{x^2-1}| + C',
        expr: 'log(abs(x*sqrt(x^2-1)))',
        mistake: 'ln-misapplied',
        why: '∫dx/g is not ln|g| unless g′ is in the numerator; this is the arcsecant form.',
      },
    ],
    correct: 0,
    explanation: 'For $x > 1$, $\\frac{d}{dx}\\sec^{-1}x = \\frac{1}{x\\sqrt{x^2-1}}$, so the antiderivative is $\\sec^{-1}x + C$.',
    check: { kind: 'antiderivative', integrand: '1/(x*sqrt(x^2-1))' },
    domain: [1.5, 3],
    difficulty: 1,
  },
  {
    id: 'ad-f-010',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: 'x\\sec^2(x^2)' },
    options: [
      { latex: '\\frac{1}{2}\\tan(x^2) + C', expr: 'tan(x^2)/2' },
      {
        latex: '\\tan(x^2) + C',
        expr: 'tan(x^2)',
        mistake: 'du-constant-wrong',
        why: 'u = x² gives du = 2x dx, so x dx = du/2; the 1/2 was dropped.',
      },
      {
        latex: '2\\tan(x^2) + C',
        expr: '2*tan(x^2)',
        mistake: 'du-constant-wrong',
        why: 'x dx was replaced by 2 du instead of du/2.',
      },
      {
        latex: '\\frac{1}{2}\\sec(x^2)\\tan(x^2) + C',
        expr: 'sec(x^2)*tan(x^2)/2',
        mistake: 'trig-antiderivative-swapped',
        why: 'sec u tan u is the derivative of sec u; the antiderivative of sec²u is tan u.',
      },
      {
        latex: '\\frac{x^2}{2}\\tan(x^2) + C',
        expr: 'x^2/2*tan(x^2)',
        mistake: 'product-rule-integral',
        why: 'x and sec²(x²) were integrated separately and multiplied; there is no product rule for integrals.',
      },
      {
        latex: '\\frac{x}{2}\\tan(x^2) + C',
        expr: 'x/2*tan(x^2)',
        mistake: 'leftover-x-in-u-integral',
        why: 'The factor x was absorbed into du = 2x dx; it must not reappear in the answer.',
      },
    ],
    correct: 0,
    explanation: '$u = x^2$, $du = 2x\\,dx$: $\\frac{1}{2}\\int\\sec^2 u\\,du = \\frac{1}{2}\\tan(x^2) + C$.',
    check: { kind: 'antiderivative', integrand: 'x*sec(x^2)^2' },
    domain: [0.2, 1],
    difficulty: 1,
  },
  {
    id: 'ad-f-011',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\cos^4 x\\,\\sin x' },
    options: [
      { latex: '-\\frac{1}{5}\\cos^5 x + C', expr: '-cos(x)^5/5' },
      {
        latex: '\\frac{1}{5}\\cos^5 x + C',
        expr: 'cos(x)^5/5',
        mistake: 'u-cos-sign-missing',
        why: 'With u = cos x, du = −sin x dx; the minus sign was dropped.',
      },
      {
        latex: '-\\frac{1}{5}\\sin^5 x + C',
        expr: '-sin(x)^5/5',
        mistake: 'back-substitution-wrong',
        why: 'u was cos x, but sin x was put back in its place.',
      },
      {
        latex: '-\\cos^5 x + C',
        expr: '-cos(x)^5',
        mistake: 'power-rule-int-coefficient',
        why: '∫u⁴du = u⁵/5; the division by 5 was skipped.',
      },
      {
        latex: '-\\frac{1}{5}\\cos^5 x\\,\\sin x + C',
        expr: '-cos(x)^5*sin(x)/5',
        mistake: 'leftover-x-in-u-integral',
        why: 'sin x dx became −du; the factor sin x must not stay in the answer.',
      },
    ],
    correct: 0,
    explanation: '$u = \\cos x$, $du = -\\sin x\\,dx$: $-\\int u^4\\,du = -\\frac{u^5}{5} + C = -\\frac{1}{5}\\cos^5 x + C$.',
    check: { kind: 'antiderivative', integrand: 'cos(x)^4*sin(x)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-012',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{x}{x^2+1}' },
    options: [
      { latex: '\\frac{1}{2}\\ln(x^2+1) + C', expr: 'log(x^2+1)/2' },
      {
        latex: '\\ln(x^2+1) + C',
        expr: 'log(x^2+1)',
        mistake: 'du-constant-wrong',
        why: 'u = x² + 1 gives du = 2x dx, so x dx = du/2; the 1/2 was dropped.',
      },
      {
        latex: '2\\ln(x^2+1) + C',
        expr: '2*log(x^2+1)',
        mistake: 'du-constant-wrong',
        why: 'x dx was replaced by 2 du instead of du/2.',
      },
      {
        latex: '\\arctan x + C',
        expr: 'atan(x)',
        mistake: 'technique-wrong',
        why: 'arctan x is the antiderivative of 1/(x² + 1); the x in the numerator makes this a logarithm substitution.',
      },
      {
        latex: '\\frac{x^2}{2}\\arctan x + C',
        expr: 'x^2/2*atan(x)',
        mistake: 'product-rule-integral',
        why: 'x and 1/(x² + 1) were integrated separately and multiplied; there is no product rule for integrals.',
      },
      {
        latex: '\\frac{x}{2}\\ln(x^2+1) + C',
        expr: 'x/2*log(x^2+1)',
        mistake: 'leftover-x-in-u-integral',
        why: 'The numerator x is part of du = 2x dx; it must not be kept as a factor.',
      },
    ],
    correct: 0,
    explanation: '$u = x^2+1$, $du = 2x\\,dx$: $\\frac{1}{2}\\int\\frac{du}{u} = \\frac{1}{2}\\ln(x^2+1) + C$ (no absolute value needed, $x^2+1 > 0$).',
    check: { kind: 'antiderivative', integrand: 'x/(x^2+1)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-013',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: 'x^2e^{x^3}' },
    options: [
      { latex: '\\frac{1}{3}e^{x^3} + C', expr: 'exp(x^3)/3' },
      {
        latex: 'e^{x^3} + C',
        expr: 'exp(x^3)',
        mistake: 'du-constant-wrong',
        why: 'u = x³ gives du = 3x² dx, so x² dx = du/3; the 1/3 was dropped.',
      },
      {
        latex: '3e^{x^3} + C',
        expr: '3*exp(x^3)',
        mistake: 'du-constant-wrong',
        why: 'x² dx was replaced by 3 du instead of du/3.',
      },
      {
        latex: '\\frac{x^3}{3}e^{x^3} + C',
        expr: 'x^3/3*exp(x^3)',
        mistake: 'product-rule-integral',
        why: 'x² and e^{x³} were integrated separately and multiplied; there is no product rule for integrals.',
      },
      {
        latex: '\\frac{x^2}{3}e^{x^3} + C',
        expr: 'x^2/3*exp(x^3)',
        mistake: 'leftover-x-in-u-integral',
        why: 'x² dx was absorbed into du/3; the factor x² must not remain.',
      },
      {
        latex: '\\frac{e^{x^3+1}}{3(x^3+1)} + C',
        expr: 'exp(x^3+1)/(3*(x^3+1))',
        mistake: 'exp-antiderivative-wrong',
        why: 'Used a power rule on e^u; the antiderivative of e^u is simply e^u.',
      },
    ],
    correct: 0,
    explanation: '$u = x^3$, $du = 3x^2\\,dx$: $\\frac{1}{3}\\int e^u\\,du = \\frac{1}{3}e^{x^3} + C$.',
    check: { kind: 'antiderivative', integrand: 'x^2*exp(x^3)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-014',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '(3x-1)^4' },
    options: [
      { latex: '\\frac{(3x-1)^5}{15} + C', expr: '(3*x-1)^5/15' },
      {
        latex: '\\frac{(3x-1)^5}{5} + C',
        expr: '(3*x-1)^5/5',
        mistake: 'inner-constant-factor-missing',
        why: 'u = 3x − 1 gives dx = du/3; the extra division by 3 is missing.',
      },
      {
        latex: '\\frac{3(3x-1)^5}{5} + C',
        expr: '3*(3*x-1)^5/5',
        mistake: 'inner-constant-factor-missing',
        why: 'Multiplied by the inner derivative 3 instead of dividing by it.',
      },
      {
        latex: '\\frac{(3x-1)^5}{12} + C',
        expr: '(3*x-1)^5/12',
        mistake: 'power-rule-int-coefficient',
        why: 'Divided by 3 · 4, using the old exponent 4 instead of the new exponent 5.',
      },
      {
        latex: '12(3x-1)^3 + C',
        expr: '12*(3*x-1)^3',
        mistake: 'differentiated-instead',
        why: 'This is the derivative 4(3x − 1)³ · 3, not an antiderivative.',
      },
    ],
    correct: 0,
    explanation: '$u = 3x-1$, $du = 3\\,dx$: $\\frac{1}{3}\\int u^4\\,du = \\frac{u^5}{15} + C = \\frac{(3x-1)^5}{15} + C$.',
    check: { kind: 'antiderivative', integrand: '(3*x-1)^4' },
    difficulty: 1,
  },
  {
    id: 'ad-f-015',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{(\\ln x)^2}{x}' },
    options: [
      { latex: '\\frac{(\\ln x)^3}{3} + C', expr: 'log(x)^3/3' },
      {
        latex: '(\\ln x)^3 + C',
        expr: 'log(x)^3',
        mistake: 'power-rule-int-coefficient',
        why: '∫u²du = u³/3; the division by 3 was skipped.',
      },
      {
        latex: '\\frac{(\\ln x)^3}{2} + C',
        expr: 'log(x)^3/2',
        mistake: 'power-rule-int-coefficient',
        why: 'Divided by the old exponent 2 instead of the new exponent 3.',
      },
      {
        latex: '\\frac{(\\ln x)^3}{3x} + C',
        expr: 'log(x)^3/(3*x)',
        mistake: 'leftover-x-in-u-integral',
        why: 'dx/x became du; the factor 1/x must not stay in the answer.',
      },
      {
        latex: '\\frac{2\\ln x}{x} + C',
        expr: '2*log(x)/x',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of (ln x)², not an antiderivative of (ln x)²/x.',
      },
    ],
    correct: 0,
    explanation: '$u = \\ln x$, $du = \\frac{dx}{x}$: $\\int u^2\\,du = \\frac{u^3}{3} + C = \\frac{(\\ln x)^3}{3} + C$.',
    check: { kind: 'antiderivative', integrand: 'log(x)^2/x' },
    difficulty: 1,
  },
  {
    id: 'ad-f-016',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\sqrt{2x+1}' },
    options: [
      { latex: '\\frac{1}{3}(2x+1)^{3/2} + C', expr: '(2*x+1)^(3/2)/3' },
      {
        latex: '\\frac{2}{3}(2x+1)^{3/2} + C',
        expr: '2/3*(2*x+1)^(3/2)',
        mistake: 'inner-constant-factor-missing',
        why: 'u = 2x + 1 gives dx = du/2; the extra factor 1/2 is missing.',
      },
      {
        latex: '\\frac{4}{3}(2x+1)^{3/2} + C',
        expr: '4/3*(2*x+1)^(3/2)',
        mistake: 'inner-constant-factor-missing',
        why: 'Multiplied by the inner derivative 2 instead of dividing by it.',
      },
      {
        latex: '(2x+1)^{3/2} + C',
        expr: '(2*x+1)^(3/2)',
        mistake: 'power-rule-int-coefficient',
        why: 'Divided by the old exponent 1/2 (then by 2) instead of by the new exponent 3/2.',
      },
      {
        latex: '(2x+1)^{-1/2} + C',
        expr: '(2*x+1)^(-1/2)',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of √(2x + 1): ½(2x + 1)^{−1/2} · 2.',
      },
    ],
    correct: 0,
    explanation: '$u = 2x+1$, $du = 2\\,dx$: $\\frac{1}{2}\\int u^{1/2}\\,du = \\frac{1}{2}\\cdot\\frac{2}{3}u^{3/2} + C = \\frac{1}{3}(2x+1)^{3/2} + C$.',
    check: { kind: 'antiderivative', integrand: 'sqrt(2*x+1)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-017',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\sin\\left(\\frac{x}{2}\\right)' },
    options: [
      { latex: '-2\\cos\\left(\\frac{x}{2}\\right) + C', expr: '-2*cos(x/2)' },
      {
        latex: '2\\cos\\left(\\frac{x}{2}\\right) + C',
        expr: '2*cos(x/2)',
        mistake: 'trig-antiderivative-sign',
        why: '∫sin u du = −cos u; the minus sign was dropped.',
      },
      {
        latex: '-\\frac{1}{2}\\cos\\left(\\frac{x}{2}\\right) + C',
        expr: '-cos(x/2)/2',
        mistake: 'inner-constant-factor-missing',
        why: 'Multiplied by the inner derivative 1/2 instead of dividing by it; dividing by 1/2 gives the factor 2.',
      },
      {
        latex: '-\\cos\\left(\\frac{x}{2}\\right) + C',
        expr: '-cos(x/2)',
        mistake: 'inner-constant-factor-missing',
        why: 'u = x/2 gives dx = 2 du; the factor 2 is missing.',
      },
      {
        latex: '\\frac{1}{2}\\cos\\left(\\frac{x}{2}\\right) + C',
        expr: 'cos(x/2)/2',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of sin(x/2), not an antiderivative.',
      },
    ],
    correct: 0,
    explanation: '$u = \\frac{x}{2}$, $dx = 2\\,du$: $2\\int\\sin u\\,du = -2\\cos\\left(\\frac{x}{2}\\right) + C$.',
    check: { kind: 'antiderivative', integrand: 'sin(x/2)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-018',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{1}{2x+1}' },
    options: [
      { latex: '\\frac{1}{2}\\ln|2x+1| + C', expr: 'log(abs(2*x+1))/2' },
      {
        latex: '\\ln|2x+1| + C',
        expr: 'log(abs(2*x+1))',
        mistake: 'inner-constant-factor-missing',
        why: 'u = 2x + 1 gives dx = du/2; the factor 1/2 is missing.',
      },
      {
        latex: '2\\ln|2x+1| + C',
        expr: '2*log(abs(2*x+1))',
        mistake: 'inner-constant-factor-missing',
        why: 'Multiplied by the inner derivative 2 instead of dividing by it.',
      },
      {
        latex: '\\ln|x^2+x| + C',
        expr: 'log(abs(x^2+x))',
        mistake: 'ln-argument-wrong',
        why: 'The logarithm takes the denominator u = 2x + 1 itself, not its antiderivative x² + x.',
      },
      {
        latex: '-\\frac{2}{(2x+1)^2} + C',
        expr: '-2/(2*x+1)^2',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of 1/(2x + 1), not an antiderivative.',
      },
    ],
    correct: 0,
    explanation: '$u = 2x+1$, $du = 2\\,dx$: $\\frac{1}{2}\\int\\frac{du}{u} = \\frac{1}{2}\\ln|2x+1| + C$.',
    check: { kind: 'antiderivative', integrand: '1/(2*x+1)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-019',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{\\sec^2 x}{\\tan x}' },
    options: [
      { latex: '\\ln|\\tan x| + C', expr: 'log(abs(tan(x)))' },
      {
        latex: '\\ln|\\sec^2 x| + C',
        expr: 'log(abs(sec(x)^2))',
        mistake: 'ln-argument-wrong',
        why: 'The logarithm takes the denominator u = tan x, whose derivative sec²x is on top, not the numerator.',
      },
      {
        latex: '-\\frac{1}{\\tan^2 x} + C',
        expr: '-1/tan(x)^2',
        mistake: 'differentiated-instead',
        why: '−1/u² is the derivative of 1/u, not its antiderivative; ∫du/u = ln|u|.',
      },
      {
        latex: '-\\frac{1}{2\\tan^2 x} + C',
        expr: '-1/(2*tan(x)^2)',
        mistake: 'power-rule-int-exponent',
        why: 'Lowered the exponent of u^{−1} to −2 (as when differentiating) and divided by it; the power −1 is exactly the case that gives ln|u|.',
      },
      {
        latex: '\\frac{\\tan^2 x}{2} + C',
        expr: 'tan(x)^2/2',
        mistake: 'algebra-error',
        why: 'Read the integrand as tan x · sec²x and integrated u du; it is (1/tan x) · sec²x = du/u.',
      },
    ],
    correct: 0,
    explanation: '$u = \\tan x$, $du = \\sec^2 x\\,dx$: $\\int\\frac{du}{u} = \\ln|\\tan x| + C$.',
    check: { kind: 'antiderivative', integrand: 'sec(x)^2/tan(x)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-020',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    variable: 't',
    prompt: { latex: '\\frac{\\sin(\\tan^{-1}(t))}{1+t^2}' },
    options: [
      { latex: '-\\cos(\\tan^{-1}(t)) + C', expr: '-cos(atan(t))' },
      {
        latex: '\\cos(\\tan^{-1}(t)) + C',
        expr: 'cos(atan(t))',
        mistake: 'trig-antiderivative-sign',
        why: '∫sin u du = −cos u; the minus sign was dropped.',
      },
      {
        latex: '-\\frac{\\cos(\\tan^{-1}(t))}{1+t^2} + C',
        expr: '-cos(atan(t))/(1+t^2)',
        mistake: 'leftover-x-in-u-integral',
        why: 'dt/(1 + t²) is du; the factor 1/(1 + t²) must not stay in the answer.',
      },
      {
        latex: '\\sin(\\tan^{-1}(t))\\tan^{-1}(t) + C',
        expr: 'sin(atan(t))*atan(t)',
        mistake: 'product-rule-integral',
        why: 'Treated sin(tan⁻¹t) as a constant and integrated only 1/(1 + t²); a product cannot be integrated factor by factor.',
      },
      {
        latex: '\\frac{1}{2}\\sin^2(\\tan^{-1}(t)) + C',
        expr: 'sin(atan(t))^2/2',
        mistake: 'du-derivative-wrong',
        why: 'Took u = sin(tan⁻¹t) but used du = dt/(1 + t²); the chain rule also gives a factor cos(tan⁻¹t).',
      },
    ],
    correct: 0,
    explanation: '$u = \\tan^{-1}t$, $du = \\frac{dt}{1+t^2}$: $\\int\\sin u\\,du = -\\cos(\\tan^{-1}t) + C$.',
    check: { kind: 'antiderivative', integrand: 'sin(atan(t))/(1+t^2)' },
    difficulty: 2,
  },
  {
    id: 'ad-f-021',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    prompt: { latex: '-5x^2\\sec^2(3x^3)\\tan^3(3x^3)' },
    options: [
      { latex: '-\\frac{5}{36}\\tan^4(3x^3) + C', expr: '-5/36*tan(3*x^3)^4' },
      {
        latex: '-\\frac{5}{4}\\tan^4(3x^3) + C',
        expr: '-5/4*tan(3*x^3)^4',
        mistake: 'du-constant-wrong',
        why: 'du = 9x² sec²(3x³) dx, so x² sec²(3x³) dx = du/9; the 1/9 was dropped.',
      },
      {
        latex: '-\\frac{5}{12}\\tan^4(3x^3) + C',
        expr: '-5/12*tan(3*x^3)^4',
        mistake: 'du-derivative-wrong',
        why: 'd/dx(3x³) = 9x², not 3x²; dividing by 3 instead of 9 gives 5/12.',
      },
      {
        latex: '-\\frac{5}{9}\\tan^4(3x^3) + C',
        expr: '-5/9*tan(3*x^3)^4',
        mistake: 'power-rule-int-coefficient',
        why: '∫u³du = u⁴/4; the division by 4 was skipped.',
      },
      {
        latex: '\\frac{5}{36}\\tan^4(3x^3) + C',
        expr: '5/36*tan(3*x^3)^4',
        mistake: 'sign-error',
        why: 'The factor −5 carries through to the answer; its minus sign was lost.',
      },
      {
        latex: '-\\frac{5}{36}\\sec^4(3x^3) + C',
        expr: '-5/36*sec(3*x^3)^4',
        mistake: 'back-substitution-wrong',
        why: 'u was tan(3x³), but sec(3x³) was put back in its place.',
      },
    ],
    correct: 0,
    explanation: '$u = \\tan(3x^3)$, $du = 9x^2\\sec^2(3x^3)\\,dx$: $-\\frac{5}{9}\\int u^3\\,du = -\\frac{5}{36}\\tan^4(3x^3) + C$.',
    check: { kind: 'antiderivative', integrand: '-5*x^2*sec(3*x^3)^2*tan(3*x^3)^3' },
    domain: [0.2, 0.75],
    difficulty: 2,
  },
  {
    id: 'ad-f-022',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    variable: 't',
    prompt: { latex: '\\frac{\\sqrt{2+\\sqrt{t}}}{\\sqrt{t}}' },
    options: [
      { latex: '\\frac{4}{3}(2+\\sqrt{t})^{3/2} + C', expr: '4/3*(2+sqrt(t))^(3/2)' },
      {
        latex: '\\frac{2}{3}(2+\\sqrt{t})^{3/2} + C',
        expr: '2/3*(2+sqrt(t))^(3/2)',
        mistake: 'du-constant-wrong',
        why: 'du = dt/(2√t), so dt/√t = 2 du; the factor 2 was dropped.',
      },
      {
        latex: '\\frac{1}{3}(2+\\sqrt{t})^{3/2} + C',
        expr: '1/3*(2+sqrt(t))^(3/2)',
        mistake: 'du-constant-wrong',
        why: 'Used dt/√t = du/2 instead of 2 du.',
      },
      {
        latex: '3(2+\\sqrt{t})^{3/2} + C',
        expr: '3*(2+sqrt(t))^(3/2)',
        mistake: 'power-rule-int-coefficient',
        why: 'Multiplied by the new exponent 3/2 instead of dividing by it: 2 · (3/2) = 3.',
      },
      {
        latex: '\\frac{4(2+\\sqrt{t})^{3/2}}{3\\sqrt{t}} + C',
        expr: '4*(2+sqrt(t))^(3/2)/(3*sqrt(t))',
        mistake: 'leftover-x-in-u-integral',
        why: 'dt/√t was absorbed into 2 du; the 1/√t must not stay in the answer.',
      },
    ],
    correct: 0,
    explanation: '$u = 2+\\sqrt{t}$, $du = \\frac{dt}{2\\sqrt{t}}$: $2\\int u^{1/2}\\,du = \\frac{4}{3}(2+\\sqrt{t})^{3/2} + C$.',
    check: { kind: 'antiderivative', integrand: 'sqrt(2+sqrt(t))/sqrt(t)' },
    difficulty: 2,
  },
  {
    id: 'ad-f-023',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    variable: 't',
    prompt: { latex: '\\frac{1+t}{1-t}' },
    options: [
      { latex: '-t - 2\\ln|1-t| + C', expr: '-t - 2*log(abs(1-t))' },
      {
        latex: '-t + 2\\ln|1-t| + C',
        expr: '-t + 2*log(abs(1-t))',
        mistake: 'u-cos-sign-missing',
        why: 'With u = 1 − t, du = −dt; dropping that minus flips the sign of the logarithm term.',
      },
      {
        latex: 't - 2\\ln|1-t| + C',
        expr: 't - 2*log(abs(1-t))',
        mistake: 'algebra-error',
        why: '(1 + t)/(1 − t) = −1 + 2/(1 − t), not 1 + 2/(1 − t): t divided by −t is −1.',
      },
      {
        latex: '-t - \\ln|1-t| + C',
        expr: '-t - log(abs(1-t))',
        mistake: 'coefficient-mishandled',
        why: 'After dividing, the remainder term is 2/(1 − t); the factor 2 was lost.',
      },
      {
        latex: '-(1+t)\\ln|1-t| + C',
        expr: '-(1+t)*log(abs(1-t))',
        mistake: 'product-rule-integral',
        why: 'The non-constant numerator 1 + t was pulled out of the integral and only 1/(1 − t) was integrated.',
      },
    ],
    correct: 0,
    explanation: 'Divide first: $\\frac{1+t}{1-t} = -1 + \\frac{2}{1-t}$; then $u = 1-t$, $du = -dt$ gives $-t - 2\\ln|1-t| + C$.',
    check: { kind: 'antiderivative', integrand: '(1+t)/(1-t)' },
    domain: [-1.5, 0.6],
    difficulty: 2,
  },

  // ───────────────────────── evaluate: definite integrals via FTC and substitution ─────────────────────────
  {
    id: 'ad-f-024',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_1^4 \\frac{1}{\\sqrt{x}}\\,dx' },
    options: [
      { latex: '2', expr: '2' },
      { latex: '4', expr: '4', mistake: 'ftc-not-subtracted', why: 'Only F(4) = 2√4 = 4 was computed; F(1) = 2 must be subtracted.' },
      { latex: '-2', expr: '-2', mistake: 'ftc-order-swapped', why: 'Computed F(1) − F(4) instead of F(4) − F(1).' },
      {
        latex: '\\frac{1}{2}',
        expr: '1/2',
        mistake: 'power-rule-int-coefficient',
        why: '∫x^{−1/2}dx = x^{1/2}/(1/2) = 2√x; multiplying by 1/2 instead gives ½√x from 1 to 4 = 1/2.',
      },
      {
        latex: '\\ln 2',
        expr: 'log(2)',
        mistake: 'ln-misapplied',
        why: 'Only x^{−1} integrates to a logarithm; ln√x from 1 to 4 = ln 2 comes from using ln for x^{−1/2}.',
      },
      {
        latex: '\\frac{7}{16}',
        expr: '7/16',
        mistake: 'differentiated-instead',
        why: 'Used −½x^{−3/2}, the derivative of x^{−1/2}, as the antiderivative: −1/16 + 1/2 = 7/16.',
      },
    ],
    correct: 0,
    explanation: '$\\int_1^4 x^{-1/2}\\,dx = 2\\sqrt{x}\\,\\Big|_1^4 = 4 - 2 = 2$.',
    check: { kind: 'definite-integral', integrand: '1/sqrt(x)', lower: '1', upper: '4' },
    difficulty: 1,
  },
  {
    id: 'ad-f-025',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_0^{\\pi/4} \\sin(2x)\\,dx' },
    options: [
      { latex: '\\frac{1}{2}', expr: '1/2' },
      { latex: '1', expr: '1', mistake: 'inner-constant-factor-missing', why: 'Used −cos(2x) without the factor 1/2: −cos(π/2) + cos 0 = 1.' },
      { latex: '2', expr: '2', mistake: 'inner-constant-factor-missing', why: 'Multiplied by the inner constant 2 instead of dividing: −2cos(2x) from 0 to π/4 gives 2.' },
      { latex: '-\\frac{1}{2}', expr: '-1/2', mistake: 'trig-antiderivative-sign', why: 'Used +½cos(2x) as the antiderivative; ∫sin u du = −cos u.' },
      { latex: '0', expr: '0', mistake: 'ftc-not-subtracted', why: 'Only F(π/4) = −½cos(π/2) = 0 was computed; F(0) = −1/2 was never subtracted.' },
    ],
    correct: 0,
    explanation: '$-\\frac{1}{2}\\cos(2x)\\,\\Big|_0^{\\pi/4} = -\\frac{1}{2}\\cos\\frac{\\pi}{2} + \\frac{1}{2}\\cos 0 = \\frac{1}{2}$.',
    check: { kind: 'definite-integral', integrand: 'sin(2*x)', lower: '0', upper: 'pi/4' },
    difficulty: 1,
  },
  {
    id: 'ad-f-026',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_{-1}^{1} x\\sqrt{9-x^2}\\,dx' },
    options: [
      { latex: '0', expr: '0' },
      {
        latex: '18 - \\frac{32\\sqrt{2}}{3}',
        expr: '18 - 32*sqrt(2)/3',
        mistake: 'signed-area-confusion',
        why: 'Doubled ∫₀¹ as if the integrand were even; x√(9 − x²) is odd, so its negative part on [−1, 0] cancels the positive part.',
      },
      {
        latex: '-\\frac{16\\sqrt{2}}{3}',
        expr: '-16*sqrt(2)/3',
        mistake: 'ftc-not-subtracted',
        why: 'Only F(1) = −⅓ · 8^{3/2} was computed; F(−1) has the same value and must be subtracted.',
      },
      {
        latex: '\\frac{10\\sqrt{10} - 16\\sqrt{2}}{3}',
        expr: '(10*sqrt(10) - 16*sqrt(2))/3',
        mistake: 'negative-squared-wrong',
        why: 'Took (−1)² = −1, so the lower u-limit became 9 − (−1) = 10 instead of 8.',
      },
      {
        latex: '-\\frac{2}{3}',
        expr: '-2/3',
        mistake: 'sqrt-of-sum-split',
        why: 'Replaced √(9 − x²) by 3 − x; a square root does not split over a difference. That gives ∫(3x − x²)dx = −2/3.',
      },
    ],
    correct: 0,
    explanation: 'With $u = 9 - x^2$, both limits become $u = 8$ (the integrand is odd), so $\\int_8^8 \\left(-\\tfrac{1}{2}\\sqrt{u}\\right)du = 0$.',
    check: { kind: 'definite-integral', integrand: 'x*sqrt(9-x^2)', lower: '-1', upper: '1' },
    difficulty: 2,
  },
  {
    id: 'ad-f-027',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_1^3 (2-x)^6\\,dx' },
    options: [
      { latex: '\\frac{2}{7}', expr: '2/7' },
      { latex: '-\\frac{2}{7}', expr: '-2/7', mistake: 'u-cos-sign-missing', why: 'With u = 2 − x, du = −dx; dropping that minus sign flips the result.' },
      { latex: '0', expr: '0', mistake: 'negative-squared-wrong', why: '(−1)⁷ = −1 (an odd power keeps the sign); taking it as +1 makes the two values cancel.' },
      { latex: '\\frac{1}{7}', expr: '1/7', mistake: 'ftc-not-subtracted', why: 'Only F(3) = 1/7 was computed; F(1) = −1/7 must be subtracted.' },
      { latex: '2', expr: '2', mistake: 'power-rule-int-coefficient', why: '∫u⁶du = u⁷/7; the division by 7 was skipped.' },
      {
        latex: '-\\frac{2186}{7}',
        expr: '-2186/7',
        mistake: 'bounds-not-converted',
        why: 'After u = 2 − x the x-limits 1 and 3 were kept: −∫₁³u⁶du = −2186/7.',
      },
    ],
    correct: 0,
    explanation: '$u = 2-x$, $du = -dx$: $-\\int_1^{-1} u^6\\,du = \\int_{-1}^{1} u^6\\,du = \\frac{2}{7}$.',
    check: { kind: 'definite-integral', integrand: '(2-x)^6', lower: '1', upper: '3' },
    difficulty: 2,
  },
  {
    id: 'ad-f-028',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_{-1}^{1} \\frac{1}{x+2}\\,dx' },
    options: [
      { latex: '\\ln 3', expr: 'log(3)' },
      { latex: '-\\ln 3', expr: '-log(3)', mistake: 'ftc-order-swapped', why: 'Computed F(−1) − F(1) = ln 1 − ln 3 instead of F(1) − F(−1).' },
      { latex: '\\ln 2', expr: 'log(2)', mistake: 'arithmetic-error', why: 'ln 3 − ln 1 = ln(3/1), not ln(3 − 1).' },
      {
        latex: '\\frac{8}{9}',
        expr: '8/9',
        mistake: 'differentiated-instead',
        why: 'Used −1/(x + 2)², the derivative of 1/(x + 2), as the antiderivative: −1/9 + 1 = 8/9.',
      },
      {
        latex: '\\frac{4}{9}',
        expr: '4/9',
        mistake: 'power-rule-int-exponent',
        why: 'Lowered the exponent of (x + 2)^{−1} to −2 (as when differentiating) and divided by it, getting −1/(2(x + 2)²); the power −1 integrates to ln|x + 2|.',
      },
      { latex: '0', expr: '0', mistake: 'ln-argument-wrong', why: 'Wrote ln|x| instead of ln|x + 2|: ln 1 − ln 1 = 0.' },
    ],
    correct: 0,
    explanation: '$\\ln|x+2|\\,\\Big|_{-1}^{1} = \\ln 3 - \\ln 1 = \\ln 3$; FTC applies since $x + 2 \\ne 0$ on $[-1, 1]$.',
    check: { kind: 'definite-integral', integrand: '1/(x+2)', lower: '-1', upper: '1' },
    difficulty: 1,
  },
  {
    id: 'ad-f-029',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_0^1 \\left(x^e + e^x\\right)\\,dx' },
    options: [
      { latex: '\\frac{1}{e+1} + e - 1', expr: '1/(e+1) + e - 1' },
      {
        latex: '\\frac{1}{e+1} + e',
        expr: '1/(e+1) + e',
        mistake: 'ftc-not-subtracted',
        why: 'The lower limit of e^x gives e⁰ = 1, not 0; it must be subtracted.',
      },
      {
        latex: '\\frac{1}{e} + e - 1',
        expr: '1/e + e - 1',
        mistake: 'power-rule-int-coefficient',
        why: '∫x^e dx = x^{e+1}/(e + 1); dividing by the old exponent e gives 1/e.',
      },
      {
        latex: '2e - 1',
        expr: '2*e - 1',
        mistake: 'differentiated-instead',
        why: 'Used e·x^{e−1}, the derivative of x^e, instead of its antiderivative: e + (e − 1).',
      },
      {
        latex: '\\frac{1}{e+1} + \\frac{e^2}{2} - e',
        expr: '1/(e+1) + e^2/2 - e',
        mistake: 'exp-antiderivative-wrong',
        why: 'Treated e^x like a power, e^{x+1}/(x + 1); the antiderivative of e^x is e^x itself.',
      },
    ],
    correct: 0,
    explanation: '$\\left[\\frac{x^{e+1}}{e+1} + e^x\\right]_0^1 = \\frac{1}{e+1} + e - 1$ ($x^e$ is a power, $e^x$ an exponential).',
    check: { kind: 'definite-integral', integrand: 'x^e + e^x', lower: '0', upper: '1' },
    difficulty: 1,
  },
  {
    id: 'ad-f-030',
    topic: 'antiderivatives',
    kind: 'evaluate',
    variable: 'z',
    prompt: { latex: '\\int_1^{18} \\sqrt{\\frac{3}{z}}\\,dz' },
    options: [
      { latex: '6\\sqrt{6} - 2\\sqrt{3}', expr: '6*sqrt(6) - 2*sqrt(3)' },
      { latex: '6\\sqrt{6}', expr: '6*sqrt(6)', mistake: 'ftc-not-subtracted', why: 'Only F(18) = 2√3 · √18 = 6√6 was computed; F(1) = 2√3 must be subtracted.' },
      {
        latex: '\\frac{3\\sqrt{6} - \\sqrt{3}}{2}',
        expr: '(3*sqrt(6) - sqrt(3))/2',
        mistake: 'power-rule-int-coefficient',
        why: '∫z^{−1/2}dz = 2z^{1/2}; multiplying by 1/2 instead of 2 gives ½√3(√18 − 1).',
      },
      {
        latex: '18\\sqrt{2} - 6',
        expr: '18*sqrt(2) - 6',
        mistake: 'algebra-error',
        why: 'Rewrote √(3/z) as 3/√z; the root applies to the 3 as well, giving √3/√z.',
      },
      { latex: '2\\sqrt{3} - 6\\sqrt{6}', expr: '2*sqrt(3) - 6*sqrt(6)', mistake: 'ftc-order-swapped', why: 'Computed F(1) − F(18) instead of F(18) − F(1).' },
      {
        latex: '\\frac{\\sqrt{3}}{2}\\ln 18',
        expr: 'sqrt(3)/2*log(18)',
        mistake: 'ln-misapplied',
        why: 'Only z^{−1} integrates to a logarithm; z^{−1/2} needs the power rule.',
      },
    ],
    correct: 0,
    explanation: '$\\sqrt{\\frac{3}{z}} = \\sqrt{3}\\,z^{-1/2}$, so the integral is $2\\sqrt{3}\\sqrt{z}\\,\\Big|_1^{18} = 2\\sqrt{3}(3\\sqrt{2} - 1) = 6\\sqrt{6} - 2\\sqrt{3}$.',
    check: { kind: 'definite-integral', integrand: 'sqrt(3/z)', lower: '1', upper: '18' },
    difficulty: 1,
  },
  {
    id: 'ad-f-031',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_0^{1/2} \\frac{1}{\\sqrt{1-x^2}}\\,dx' },
    options: [
      { latex: '\\frac{\\pi}{6}', expr: 'pi/6' },
      { latex: '\\frac{\\pi}{3}', expr: 'pi/3', mistake: 'inverse-trig-value-wrong', why: 'sin(π/3) = √3/2; the angle whose sine is 1/2 is π/6.' },
      { latex: '-\\frac{\\pi}{6}', expr: '-pi/6', mistake: 'ftc-order-swapped', why: 'Computed F(0) − F(1/2) instead of F(1/2) − F(0).' },
      {
        latex: '\\arctan\\left(\\frac{1}{2}\\right)',
        expr: 'atan(1/2)',
        mistake: 'inverse-trig-confused',
        why: 'arctan is the antiderivative of 1/(1 + x²); 1/√(1 − x²) integrates to arcsin x.',
      },
      {
        latex: '\\sqrt{3} - 2',
        expr: 'sqrt(3) - 2',
        mistake: 'u-choice-wrong',
        why: 'Used the power rule on (1 − x²)^{−1/2} as if du were dx: 2√(1 − x²) from 0 to 1/2; the needed factor −2x is not there.',
      },
    ],
    correct: 0,
    explanation: '$\\arcsin x\\,\\Big|_0^{1/2} = \\arcsin\\frac{1}{2} - \\arcsin 0 = \\frac{\\pi}{6}$.',
    check: { kind: 'definite-integral', integrand: '1/sqrt(1-x^2)', lower: '0', upper: '1/2' },
    difficulty: 1,
  },
  {
    id: 'ad-f-032',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_0^{\\ln 2} e^{3x}\\,dx' },
    options: [
      { latex: '\\frac{7}{3}', expr: '7/3' },
      { latex: '7', expr: '7', mistake: 'inner-constant-factor-missing', why: 'Used e^{3x} as the antiderivative without the factor 1/3: 8 − 1 = 7.' },
      { latex: '21', expr: '21', mistake: 'exp-antiderivative-wrong', why: 'Multiplied by 3 instead of dividing: 3e^{3x} from 0 to ln 2 gives 3(8 − 1) = 21.' },
      { latex: '\\frac{8}{3}', expr: '8/3', mistake: 'ftc-not-subtracted', why: 'Only F(ln 2) = e^{3 ln 2}/3 = 8/3 was computed; F(0) = 1/3 must be subtracted.' },
      { latex: '\\frac{5}{3}', expr: '5/3', mistake: 'algebra-error', why: 'e^{3 ln 2} = (e^{ln 2})³ = 8, not 3 · 2 = 6.' },
      { latex: '-\\frac{7}{3}', expr: '-7/3', mistake: 'ftc-order-swapped', why: 'Computed F(0) − F(ln 2) instead of F(ln 2) − F(0).' },
    ],
    correct: 0,
    explanation: '$\\frac{1}{3}e^{3x}\\,\\Big|_0^{\\ln 2} = \\frac{1}{3}\\left(e^{3\\ln 2} - 1\\right) = \\frac{1}{3}(8 - 1) = \\frac{7}{3}$.',
    check: { kind: 'definite-integral', integrand: 'exp(3*x)', lower: '0', upper: 'log(2)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-033',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_1^2 \\frac{x}{x^2+1}\\,dx' },
    options: [
      { latex: '\\frac{1}{2}\\ln\\left(\\frac{5}{2}\\right)', expr: 'log(5/2)/2' },
      {
        latex: '\\ln\\left(\\frac{5}{2}\\right)',
        expr: 'log(5/2)',
        mistake: 'du-constant-wrong',
        why: 'du = 2x dx, so x dx = du/2; the factor 1/2 was dropped.',
      },
      {
        latex: '\\frac{1}{2}\\ln 2',
        expr: 'log(2)/2',
        mistake: 'bounds-not-converted',
        why: 'After u = x² + 1 the x-limits 1 and 2 were kept; the u-limits are 2 and 5.',
      },
      {
        latex: '\\frac{1}{2}\\ln\\left(\\frac{26}{5}\\right)',
        expr: 'log(26/5)/2',
        mistake: 'mixed-limits-variable',
        why: 'The u-limits 2 and 5 were plugged into ½ln(x² + 1), an x-expression: ½(ln 26 − ln 5).',
      },
      {
        latex: '\\arctan 2 - \\frac{\\pi}{4}',
        expr: 'atan(2) - pi/4',
        mistake: 'technique-wrong',
        why: 'Used arctan, the antiderivative of 1/(x² + 1); the x in the numerator makes this a logarithm substitution.',
      },
      {
        latex: '-\\frac{1}{2}\\ln\\left(\\frac{5}{2}\\right)',
        expr: '-log(5/2)/2',
        mistake: 'ftc-order-swapped',
        why: 'Subtracted in the wrong order: F(1) − F(2).',
      },
    ],
    correct: 0,
    explanation: '$u = x^2+1$ runs from 2 to 5: $\\frac{1}{2}\\int_2^5\\frac{du}{u} = \\frac{1}{2}(\\ln 5 - \\ln 2) = \\frac{1}{2}\\ln\\frac{5}{2}$.',
    check: { kind: 'definite-integral', integrand: 'x/(x^2+1)', lower: '1', upper: '2' },
    difficulty: 2,
  },
  {
    id: 'ad-f-034',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_0^{\\pi/2} e^{\\sin x}\\cos x\\,dx' },
    options: [
      { latex: 'e - 1', expr: 'e - 1' },
      { latex: 'e', expr: 'e', mistake: 'ftc-not-subtracted', why: 'The lower limit gives e^{sin 0} = e⁰ = 1, not 0; it must be subtracted.' },
      {
        latex: 'e^{\\pi/2} - 1',
        expr: 'exp(pi/2) - 1',
        mistake: 'bounds-not-converted',
        why: 'After u = sin x the x-limits 0 and π/2 were kept; the u-limits are sin 0 = 0 and sin(π/2) = 1.',
      },
      {
        latex: 'e^{\\sin 1} - 1',
        expr: 'exp(sin(1)) - 1',
        mistake: 'mixed-limits-variable',
        why: 'The u-limits 0 and 1 were plugged into e^{sin x}, an x-expression.',
      },
      { latex: '1 - e', expr: '1 - e', mistake: 'ftc-order-swapped', why: 'Computed F(0) − F(π/2) instead of F(π/2) − F(0).' },
      {
        latex: '\\frac{e^2}{2} - e',
        expr: 'e^2/2 - e',
        mistake: 'exp-antiderivative-wrong',
        why: 'Treated e^u like a power, e^{u+1}/(u + 1); the antiderivative of e^u is e^u.',
      },
    ],
    correct: 0,
    explanation: '$u = \\sin x$ runs from 0 to 1: $\\int_0^1 e^u\\,du = e - 1$.',
    check: { kind: 'definite-integral', integrand: 'cos(x)*exp(sin(x))', lower: '0', upper: 'pi/2' },
    difficulty: 2,
  },
  {
    id: 'ad-f-035',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_0^{\\pi/3} \\sin x\\cos^2 x\\,dx' },
    options: [
      { latex: '\\frac{7}{24}', expr: '7/24' },
      { latex: '-\\frac{7}{24}', expr: '-7/24', mistake: 'u-cos-sign-missing', why: 'With u = cos x, du = −sin x dx; the minus sign was dropped.' },
      {
        latex: '-\\frac{\\pi^3}{81}',
        expr: '-pi^3/81',
        mistake: 'bounds-not-converted',
        why: 'The x-limits 0 and π/3 were kept on −∫u²du; the u-limits are cos 0 = 1 and cos(π/3) = 1/2.',
      },
      {
        latex: '\\frac{\\cos^3(1) - \\cos^3\\left(\\frac{1}{2}\\right)}{3}',
        expr: '(cos(1)^3 - cos(1/2)^3)/3',
        mistake: 'mixed-limits-variable',
        why: 'The u-limits 1 and 1/2 were plugged into −cos³x/3, an x-expression.',
      },
      { latex: '-\\frac{1}{24}', expr: '-1/24', mistake: 'ftc-not-subtracted', why: 'Only F(π/3) = −(1/2)³/3 = −1/24 was computed; F(0) = −1/3 must be subtracted.' },
      { latex: '\\frac{7}{8}', expr: '7/8', mistake: 'power-rule-int-coefficient', why: '∫u²du = u³/3; the division by 3 was skipped: 1 − 1/8 = 7/8.' },
    ],
    correct: 0,
    explanation: '$u = \\cos x$, $du = -\\sin x\\,dx$, $u$ runs from 1 to $\\frac{1}{2}$: $-\\int_1^{1/2} u^2\\,du = \\int_{1/2}^{1} u^2\\,du = \\frac{7}{24}$.',
    check: { kind: 'definite-integral', integrand: 'sin(x)*cos(x)^2', lower: '0', upper: 'pi/3' },
    difficulty: 2,
  },
  {
    id: 'ad-f-036',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_1^{\\sqrt{2}} x\\,2^{x^2-1}\\,dx' },
    options: [
      { latex: '\\frac{1}{2\\ln 2}', expr: '1/(2*log(2))' },
      { latex: '\\frac{1}{\\ln 2}', expr: '1/log(2)', mistake: 'du-constant-wrong', why: 'du = 2x dx, so x dx = du/2; the factor 1/2 was dropped.' },
      {
        latex: '\\frac{\\ln 2}{2}',
        expr: 'log(2)/2',
        mistake: 'differentiated-instead',
        why: 'Used 2^u ln 2 (the derivative of 2^u) instead of 2^u/ln 2: ½(2 − 1)ln 2.',
      },
      {
        latex: '\\frac{1}{4\\ln 2}',
        expr: '1/(4*log(2))',
        mistake: 'mixed-limits-variable',
        why: 'The u-limits 0 and 1 were plugged into 2^{x²−1}/(2 ln 2), an x-expression: (2⁰ − 2^{−1})/(2 ln 2).',
      },
      { latex: '\\frac{1}{2}', expr: '1/2', mistake: 'exp-base-log-missing', why: 'Integrated 2^u as 2^u (like e^u); the antiderivative of 2^u is 2^u/ln 2.' },
      {
        latex: '\\frac{2^{\\sqrt{2}} - 2}{2\\ln 2}',
        expr: '(2^sqrt(2) - 2)/(2*log(2))',
        mistake: 'bounds-not-converted',
        why: 'The x-limits 1 and √2 were kept for the u-integral ½∫2^u du; the u-limits are 0 and 1.',
      },
    ],
    correct: 0,
    explanation: '$u = x^2 - 1$ runs from 0 to 1: $\\frac{1}{2}\\int_0^1 2^u\\,du = \\frac{1}{2}\\cdot\\frac{2 - 1}{\\ln 2} = \\frac{1}{2\\ln 2}$.',
    check: { kind: 'definite-integral', integrand: 'x*2^(x^2-1)', lower: '1', upper: 'sqrt(2)' },
    difficulty: 2,
  },
  {
    id: 'ad-f-037',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_2^8 \\frac{-2e^{\\sqrt{2x}}}{\\sqrt{2x}}\\,dx' },
    options: [
      { latex: '2e^2 - 2e^4', expr: '2*e^2 - 2*e^4' },
      {
        latex: '4e^2 - 4e^4',
        expr: '4*e^2 - 4*e^4',
        mistake: 'du-derivative-wrong',
        why: 'Forgot the chain-rule factor 2: d/dx √(2x) = (1/(2√(2x))) · 2 = 1/√(2x), so the integrand is exactly −2e^u du.',
      },
      {
        latex: 'e^2 - e^4',
        expr: 'e^2 - e^4',
        mistake: 'du-constant-wrong',
        why: 'Forgot the 1/2 of the power rule and took du = 2dx/√(2x); in fact du = dx/√(2x).',
      },
      {
        latex: '2e^2 - 2e^8',
        expr: '2*e^2 - 2*e^8',
        mistake: 'bounds-not-converted',
        why: 'After u = √(2x) the x-limits 2 and 8 were kept; the u-limits are √4 = 2 and √16 = 4.',
      },
      {
        latex: '2e^2 - 2e^{2\\sqrt{2}}',
        expr: '2*e^2 - 2*e^(2*sqrt(2))',
        mistake: 'mixed-limits-variable',
        why: 'The u-limits 2 and 4 were plugged into −2e^{√(2x)}, an x-expression: √(2·4) = 2√2 and √(2·2) = 2.',
      },
      { latex: '2e^4 - 2e^2', expr: '2*e^4 - 2*e^2', mistake: 'ftc-order-swapped', why: 'Computed F(2) − F(8) instead of F(8) − F(2).' },
    ],
    correct: 0,
    explanation: '$u = \\sqrt{2x}$, $du = \\frac{dx}{\\sqrt{2x}}$, $u$ runs from 2 to 4: $-2\\int_2^4 e^u\\,du = -2(e^4 - e^2) = 2e^2 - 2e^4$.',
    check: { kind: 'definite-integral', integrand: '-2*exp(sqrt(2*x))/sqrt(2*x)', lower: '2', upper: '8' },
    difficulty: 2,
  },
  {
    id: 'ad-f-038',
    topic: 'antiderivatives',
    kind: 'evaluate',
    prompt: { latex: '\\int_0^1 \\frac{x^2+2x}{x^3+3x^2+1}\\,dx' },
    options: [
      { latex: '\\frac{1}{3}\\ln 5', expr: 'log(5)/3' },
      { latex: '\\ln 5', expr: 'log(5)', mistake: 'du-constant-wrong', why: 'du = (3x² + 6x)dx = 3(x² + 2x)dx; the factor 1/3 was dropped.' },
      { latex: '3\\ln 5', expr: '3*log(5)', mistake: 'du-constant-wrong', why: '(x² + 2x)dx was replaced by 3 du instead of du/3.' },
      {
        latex: '\\frac{1}{3}\\ln\\left(\\frac{201}{5}\\right)',
        expr: 'log(201/5)/3',
        mistake: 'mixed-limits-variable',
        why: 'The u-limits 1 and 5 were plugged into ⅓ln|x³ + 3x² + 1|, an x-expression.',
      },
      { latex: '-\\frac{1}{3}\\ln 5', expr: '-log(5)/3', mistake: 'ftc-order-swapped', why: 'Computed F(0) − F(1) instead of F(1) − F(0).' },
    ],
    correct: 0,
    explanation: '$u = x^3+3x^2+1$, $du = 3(x^2+2x)\\,dx$, $u$ runs from 1 to 5: $\\frac{1}{3}\\int_1^5\\frac{du}{u} = \\frac{1}{3}\\ln 5$.',
    check: { kind: 'definite-integral', integrand: '(x^2+2*x)/(x^3+3*x^2+1)', lower: '0', upper: '1' },
    difficulty: 2,
  },

  // ───────────────────────── concept ─────────────────────────
  {
    id: 'ad-f-039',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'Which function is an antiderivative of $\\sin(2x)$?' },
    options: [
      { latex: '\\sin^2 x', expr: 'sin(x)^2' },
      {
        latex: '\\cos^2 x',
        expr: 'cos(x)^2',
        mistake: 'trig-antiderivative-sign',
        why: 'd/dx cos²x = −2 sin x cos x = −sin(2x): the sign is wrong.',
      },
      {
        latex: '-\\cos(2x)',
        expr: '-cos(2*x)',
        mistake: 'inner-constant-factor-missing',
        why: 'Its derivative is 2 sin(2x); the factor 1/2 for the inner 2x is missing.',
      },
      {
        latex: '-2\\cos(2x)',
        expr: '-2*cos(2*x)',
        mistake: 'inner-constant-factor-missing',
        why: 'Multiplied by the inner constant 2 instead of dividing; its derivative is 4 sin(2x).',
      },
      {
        latex: '2\\cos(2x)',
        expr: '2*cos(2*x)',
        mistake: 'differentiated-instead',
        why: 'This is the derivative of sin(2x), not an antiderivative.',
      },
    ],
    correct: 0,
    explanation: '$\\frac{d}{dx}\\sin^2 x = 2\\sin x\\cos x = \\sin(2x)$; indeed $\\sin^2 x = -\\frac{1}{2}\\cos(2x) + \\frac{1}{2}$ differs from $-\\frac{1}{2}\\cos(2x)$ by a constant.',
    check: { kind: 'antiderivative', integrand: 'sin(2*x)' },
    difficulty: 2,
  },
  {
    id: 'ad-f-040',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: '$F(x) = x^2 + 3x$ is an antiderivative of $f(x) = 2x + 3$. Which function is also an antiderivative of $f$?' },
    options: [
      { latex: '\\left(x + \\frac{3}{2}\\right)^2', expr: '(x + 3/2)^2' },
      {
        latex: '(x+3)^2',
        expr: '(x+3)^2',
        mistake: 'algebra-error',
        why: '(x + 3)² = x² + 6x + 9, whose derivative is 2x + 6, not 2x + 3.',
      },
      {
        latex: '2x^2 + 6x',
        expr: '2*x^2 + 6*x',
        mistake: 'coefficient-mishandled',
        why: 'Multiplying F by a constant changes the derivative (to 4x + 6); only adding a constant keeps it.',
      },
      {
        latex: '2x + 3',
        expr: '2*x + 3',
        mistake: 'differentiated-instead',
        why: 'This is f itself, the derivative of F, not an antiderivative of f.',
      },
      {
        latex: '\\frac{(2x+3)^2}{2}',
        expr: '(2*x+3)^2/2',
        mistake: 'inner-constant-factor-missing',
        why: 'Its derivative is 2(2x + 3); dividing by 2 · 2 = 4 (for the inner 2x) would be needed.',
      },
    ],
    correct: 0,
    explanation: '$\\left(x + \\frac{3}{2}\\right)^2 = x^2 + 3x + \\frac{9}{4} = F(x) + \\frac{9}{4}$ differs from $F$ by a constant, so its derivative is also $2x + 3$.',
    check: { kind: 'antiderivative', integrand: '2*x + 3' },
    difficulty: 2,
  },
  {
    id: 'ad-f-041',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: {
      text: 'A student finds $\\int f(x)\\,dx = F(x) + 1 + C$, while a computer algebra system gives $F(x) + C$ (and that answer is correct). Which statement is true?',
    },
    options: [
      { text: 'Both answers are correct: $1 + C$ is still an arbitrary constant.' },
      {
        text: 'The student is wrong: the extra $+1$ changes the derivative of the answer.',
        mistake: 'constant-derivative',
        why: 'The derivative of the constant 1 is 0, so F(x) + 1 + C still has derivative f(x).',
      },
      {
        text: 'The student is wrong: an antiderivative may contain only one constant term, $+C$.',
        mistake: 'plus-c-misuse',
        why: 'Any added constant is absorbed into the arbitrary C; F + 1 + C and F + C describe the same family.',
      },
      {
        text: 'The computer is wrong: it lost the constant $1$.',
        mistake: 'plus-c-misuse',
        why: 'Nothing was lost; the 1 is absorbed into the arbitrary constant C.',
      },
      {
        text: 'The two answers agree only when $C = -1$.',
        mistake: 'plus-c-misuse',
        why: 'C is arbitrary in each answer; as families of functions the two answers are identical, not equal for just one value of C.',
      },
    ],
    correct: 0,
    explanation: 'Antiderivatives of $f$ differ only by constants, and $1 + C$ ranges over all constants, so $F(x) + 1 + C$ and $F(x) + C$ are the same family.',
    check: { kind: 'none', reason: 'conceptual: the family of antiderivatives and the arbitrary constant' },
    difficulty: 1,
  },
  {
    id: 'ad-f-042',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'Which pair is written correctly?' },
    options: [
      { text: '$\\int 2x\\,dx = x^2 + C$ and $\\int_0^1 2x\\,dx = 1$' },
      {
        text: '$\\int 2x\\,dx = x^2 + C$ and $\\int_0^1 2x\\,dx = 1 + C$',
        mistake: 'plus-c-misuse',
        why: 'A definite integral is a number (a signed area); it takes no + C.',
      },
      {
        text: '$\\int 2x\\,dx = x^2$ and $\\int_0^1 2x\\,dx = 1$',
        mistake: 'plus-c-misuse',
        why: 'An indefinite integral is the whole family of antiderivatives; it needs + C.',
      },
      {
        text: '$\\int 2x\\,dx = x^2$ and $\\int_0^1 2x\\,dx = 1 + C$',
        mistake: 'plus-c-misuse',
        why: 'The + C belongs to the indefinite integral (a family), not to the definite integral (a number).',
      },
      {
        text: '$\\int 2x\\,dx = x^2 + C$ and $\\int_0^1 2x\\,dx = x^2 + C$',
        mistake: 'plus-c-misuse',
        why: 'A definite integral must be evaluated to a number: x² from 0 to 1 gives 1.',
      },
    ],
    correct: 0,
    explanation: '$\\int f\\,dx$ is a family of antiderivatives (needs $+C$); $\\int_a^b f\\,dx$ is a number, here $x^2\\big|_0^1 = 1$.',
    check: { kind: 'none', reason: 'conceptual: + C on indefinite vs definite integrals' },
    difficulty: 1,
  },
  {
    id: 'ad-f-043',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'To which integral can the Fundamental Theorem of Calculus (Part 2) be applied directly?' },
    options: [
      { latex: '\\int_{-1}^{1} \\frac{1}{x+2}\\,dx' },
      {
        latex: '\\int_{-3}^{0} \\frac{1}{x^2}\\,dx',
        mistake: 'ftc-hypothesis-ignored',
        why: '1/x² is not continuous at x = 0, the upper limit of [−3, 0].',
      },
      {
        latex: '\\int_{-3}^{0} \\frac{1}{x+2}\\,dx',
        mistake: 'ftc-hypothesis-ignored',
        why: '1/(x + 2) is not continuous at x = −2, which lies in [−3, 0].',
      },
      {
        latex: '\\int_0^{\\pi} \\sec^2 x\\,dx',
        mistake: 'ftc-hypothesis-ignored',
        why: 'sec²x is undefined at x = π/2, which lies in [0, π].',
      },
      {
        latex: '\\int_0^{\\pi/2} \\tan x\\,dx',
        mistake: 'ftc-hypothesis-ignored',
        why: 'tan x is not continuous at x = π/2, the upper limit.',
      },
    ],
    correct: 0,
    explanation: 'FTC Part 2 needs $f$ continuous on $[a, b]$; $\\frac{1}{x+2}$ is discontinuous only at $x = -2$, which is outside $[-1, 1]$.',
    check: { kind: 'none', reason: 'conceptual: continuity hypothesis of FTC Part 2' },
    difficulty: 1,
  },
  {
    id: 'ad-f-044',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: {
      text: 'A student writes $\\int_{-1}^{1}\\frac{1}{x^2}\\,dx = -\\frac{1}{x}\\Big|_{-1}^{1} = -1 - 1 = -2$. What is wrong?',
    },
    options: [
      { text: 'FTC Part 2 does not apply: $\\frac{1}{x^2}$ is not continuous at $x = 0$, which lies in $[-1, 1]$.' },
      {
        text: 'The limits were subtracted in the wrong order; the correct value is $2$.',
        mistake: 'ftc-order-swapped',
        why: 'The order F(1) − F(−1) was right; the real problem is that FTC cannot be used across the discontinuity at 0.',
      },
      {
        text: 'The antiderivative should be $\\ln(x^2)$.',
        mistake: 'ln-misapplied',
        why: '1/x² = x^{−2} uses the power rule, so −1/x is the right antiderivative; the problem is the discontinuity.',
      },
      {
        text: 'Nothing is wrong: the integral equals $-2$.',
        mistake: 'ftc-hypothesis-ignored',
        why: 'A positive integrand cannot have a negative integral; FTC was applied across the discontinuity at x = 0.',
      },
      {
        text: 'The answer is missing a $+C$.',
        mistake: 'plus-c-misuse',
        why: 'A definite integral is a number and takes no + C; the real issue is the discontinuity at 0.',
      },
    ],
    correct: 0,
    explanation: 'FTC Part 2 requires $f$ continuous on $[a, b]$; $\\frac{1}{x^2}$ blows up at $x = 0$, so $F(1) - F(-1)$ is meaningless here.',
    check: { kind: 'none', reason: 'conceptual: where the Fundamental Theorem of Calculus does not apply' },
    difficulty: 2,
  },
  {
    id: 'ad-f-045',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'If $\\int_1^4 f(x)\\,dx = 5$ and $\\int_1^2 f(x)\\,dx = 2$, what is $\\int_4^2 f(x)\\,dx$?' },
    options: [
      { latex: '-3', expr: '-3' },
      { latex: '3', expr: '3', mistake: 'bounds-swapped', why: '3 is ∫₂⁴ f; running the limits from 4 down to 2 changes the sign.' },
      {
        latex: '-7',
        expr: '-7',
        mistake: 'sign-error',
        why: 'Split at 1 correctly, ∫₄² = ∫₄¹ + ∫₁², but subtracted the second piece: −5 − 2 instead of −5 + 2.',
      },
      { latex: '7', expr: '7', mistake: 'sign-error', why: 'Added the two given integrals; the piece from 2 to 4 is ∫₁⁴ f − ∫₁² f = 3.' },
      { latex: '-5', expr: '-5', mistake: 'algebra-error', why: '−5 is ∫₄¹ f; the piece from 1 to 2 (value 2) must be added back.' },
    ],
    correct: 0,
    explanation: '$\\int_4^2 f = -\\int_2^4 f = -\\left(\\int_1^4 f - \\int_1^2 f\\right) = -(5 - 2) = -3$.',
    check: { kind: 'value', expected: '-3' },
    difficulty: 2,
  },
  {
    id: 'ad-f-046',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'Given $\\int_2^5 g(x)\\,dx = 4$, what is $\\int_5^2 3g(x)\\,dx$?' },
    options: [
      { latex: '-12', expr: '-12' },
      { latex: '12', expr: '12', mistake: 'bounds-swapped', why: 'Reversing the limits changes the sign: ∫₅² = −∫₂⁵.' },
      { latex: '-4', expr: '-4', mistake: 'coefficient-mishandled', why: 'The constant 3 comes out of the integral as a factor: 3 · (−4).' },
      { latex: '-\\frac{4}{3}', expr: '-4/3', mistake: 'coefficient-mishandled', why: 'Divided by 3 instead of multiplying; ∫c·g = c∫g.' },
      { latex: '4', expr: '4', mistake: 'bounds-swapped', why: 'Kept the given value: the reversed limits flip the sign, and the factor 3 was dropped as well.' },
      { latex: '\\frac{4}{3}', expr: '4/3', mistake: 'coefficient-mishandled', why: 'Divided by 3 instead of multiplying, and ignored that reversing the limits changes the sign.' },
    ],
    correct: 0,
    explanation: '$\\int_5^2 3g(x)\\,dx = -3\\int_2^5 g(x)\\,dx = -3\\cdot 4 = -12$.',
    check: { kind: 'value', expected: '-12' },
    difficulty: 1,
  },
  {
    id: 'ad-f-047',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: {
      text: 'Let $I = \\int_0^{\\pi}\\cos x\\,dx$, and let $A$ be the area of the region between $y = \\cos x$ and the x-axis for $0 \\le x \\le \\pi$. Which is correct?',
    },
    options: [
      { latex: 'I = 0,\\quad A = 2', expr: '[0, 2]' },
      {
        latex: 'I = 2,\\quad A = 2',
        expr: '[2, 2]',
        mistake: 'signed-area-confusion',
        why: 'The part below the axis (π/2 to π) counts negatively in I, so I is not the area.',
      },
      {
        latex: 'I = 2,\\quad A = 0',
        expr: '[2, 0]',
        mistake: 'signed-area-confusion',
        why: 'The two quantities are swapped: the signed integral cancels to 0, while the area of the two pieces is 1 + 1 = 2.',
      },
      {
        latex: 'I = -2,\\quad A = 1',
        expr: '[-2, 1]',
        mistake: 'trig-antiderivative-swapped',
        why: 'Used cos x as its own antiderivative (giving −2) and counted only the piece above the axis.',
      },
      {
        latex: 'I = -2,\\quad A = 2',
        expr: '[-2, 2]',
        mistake: 'trig-antiderivative-swapped',
        why: 'Used cos x as its own antiderivative: cos π − cos 0 = −2; the antiderivative of cos x is sin x.',
      },
      {
        latex: 'I = 0,\\quad A = 1',
        expr: '[0, 1]',
        mistake: 'signed-area-confusion',
        why: 'Only the part above the axis (0 to π/2) was counted; the part below also has area 1.',
      },
    ],
    correct: 0,
    explanation: '$I = \\sin x\\,\\Big|_0^{\\pi} = 0$: the pieces above and below the axis cancel, while each has area 1, so $A = 2$.',
    check: { kind: 'value', expected: '[0, 2]' },
    difficulty: 1,
  },
  {
    id: 'ad-f-048',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'After the substitution $u = x^3 + 1$, the integral becomes', latex: '\\int_0^1 x^2(x^3+1)^4\\,dx' },
    options: [
      { latex: '\\frac{1}{3}\\int_1^2 u^4\\,du', expr: 'integral(u^4, u, 1, 2)/3' },
      {
        latex: '\\frac{1}{3}\\int_0^1 u^4\\,du',
        expr: 'integral(u^4, u, 0, 1)/3',
        mistake: 'bounds-not-converted',
        why: 'The x-limits 0 and 1 were kept; they become u(0) = 1 and u(1) = 2.',
      },
      {
        latex: '3\\int_1^2 u^4\\,du',
        expr: '3*integral(u^4, u, 1, 2)',
        mistake: 'du-constant-wrong',
        why: 'du = 3x² dx means x² dx = du/3, not 3 du.',
      },
      {
        latex: '\\int_1^2 u^4\\,du',
        expr: 'integral(u^4, u, 1, 2)',
        mistake: 'du-constant-wrong',
        why: 'du = 3x² dx, so x² dx = du/3; the factor 1/3 was dropped.',
      },
      {
        latex: '\\frac{1}{3}\\int_1^2 x^2u^4\\,du',
        expr: 'integral(x^2*u^4, u, 1, 2)/3',
        mistake: 'leftover-x-in-u-integral',
        why: 'x² dx became du/3; no x may remain inside a u-integral.',
      },
    ],
    correct: 0,
    explanation: '$du = 3x^2\\,dx$, so $x^2\\,dx = \\frac{du}{3}$, and the limits become $u(0) = 1$, $u(1) = 2$.',
    check: { kind: 'value', expected: 'integral(x^2*(x^3+1)^4, x, 0, 1)' },
    difficulty: 1,
  },
  {
    id: 'ad-f-049',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'After the substitution $u = \\cos x$, the integral becomes', latex: '\\int_0^{\\pi} e^{\\cos x}\\sin x\\,dx' },
    options: [
      { latex: '\\int_{-1}^{1} e^u\\,du', expr: 'integral(exp(u), u, -1, 1)' },
      {
        latex: '\\int_1^{-1} e^u\\,du',
        expr: 'integral(exp(u), u, 1, -1)',
        mistake: 'u-cos-sign-missing',
        why: 'du = −sin x dx, so sin x dx = −du; without that minus the limits 1 → −1 give the wrong sign.',
      },
      {
        latex: '-\\int_0^{\\pi} e^u\\,du',
        expr: '-integral(exp(u), u, 0, pi)',
        mistake: 'bounds-not-converted',
        why: 'The x-limits 0 and π were kept; they become cos 0 = 1 and cos π = −1.',
      },
      {
        latex: '\\int_{-1}^{1} e^u\\sin x\\,du',
        expr: 'integral(sin(x)*exp(u), u, -1, 1)',
        mistake: 'leftover-x-in-u-integral',
        why: 'sin x dx is absorbed into −du; no x may remain inside the u-integral.',
      },
      {
        latex: '\\int_0^1 e^u\\,du',
        expr: 'integral(exp(u), u, 0, 1)',
        mistake: 'arithmetic-error',
        why: 'cos π = −1, not 0; the new limits are −1 and 1.',
      },
    ],
    correct: 0,
    explanation: '$du = -\\sin x\\,dx$ and $u$ runs from $\\cos 0 = 1$ to $\\cos\\pi = -1$: $\\int_1^{-1} e^u(-du) = \\int_{-1}^{1} e^u\\,du$.',
    check: { kind: 'value', expected: 'integral(sin(x)*exp(cos(x)), x, 0, pi)' },
    difficulty: 2,
  },
  {
    id: 'ad-f-050',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'After the substitution $u = x - 1$, the integral becomes', latex: '\\int \\frac{x^2}{\\sqrt{x-1}}\\,dx' },
    options: [
      { latex: '\\int \\frac{(u+1)^2}{\\sqrt{u}}\\,du', expr: 'indefinite((u+1)^2/sqrt(u), u)' },
      {
        latex: '\\int \\frac{u^2+1}{\\sqrt{u}}\\,du',
        expr: 'indefinite((u^2+1)/sqrt(u), u)',
        mistake: 'algebra-error',
        why: '(u + 1)² = u² + 2u + 1; the middle term 2u was dropped.',
      },
      {
        latex: '\\int \\frac{(u-1)^2}{\\sqrt{u}}\\,du',
        expr: 'indefinite((u-1)^2/sqrt(u), u)',
        mistake: 'sign-error',
        why: 'Solving u = x − 1 for x gives x = u + 1; the sign was flipped.',
      },
      {
        latex: '\\int \\frac{x^2}{\\sqrt{u}}\\,du',
        expr: 'indefinite(x^2/sqrt(u), u)',
        mistake: 'leftover-x-in-u-integral',
        why: 'The x² must also be written in u: x = u + 1, so x² = (u + 1)².',
      },
      {
        latex: '\\int \\frac{u^2}{\\sqrt{u}}\\,du',
        expr: 'indefinite(u^2/sqrt(u), u)',
        mistake: 'back-substitution-wrong',
        why: 'x² is not u²: since u = x − 1, x² = (u + 1)².',
      },
    ],
    correct: 0,
    explanation: 'With $u = x - 1$: $x = u + 1$ and $dx = du$, so $\\frac{x^2}{\\sqrt{x-1}}\\,dx = \\frac{(u+1)^2}{\\sqrt{u}}\\,du$.',
    check: { kind: 'identity', lhs: '(u+1)^2/sqrt(u)' },
    difficulty: 2,
  },
  {
    id: 'ad-f-051',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'After the substitution $u = x^4 + 2$, the integral becomes', latex: '\\int x^3\\cos(x^4+2)\\,dx' },
    options: [
      { latex: '\\frac{1}{4}\\int \\cos u\\,du', expr: 'indefinite(cos(u)/4, u)' },
      {
        latex: '\\int \\cos u\\,du',
        expr: 'indefinite(cos(u), u)',
        mistake: 'du-constant-wrong',
        why: 'du = 4x³ dx, so x³ dx = du/4; the factor 1/4 was dropped.',
      },
      {
        latex: '4\\int \\cos u\\,du',
        expr: 'indefinite(4*cos(u), u)',
        mistake: 'du-constant-wrong',
        why: 'x³ dx was replaced by 4 du instead of du/4.',
      },
      {
        latex: '\\frac{1}{3}\\int \\cos u\\,du',
        expr: 'indefinite(cos(u)/3, u)',
        mistake: 'du-derivative-wrong',
        why: 'The derivative of x⁴ + 2 is 4x³, so the factor is 1/4; the exponent 3 of x³ does not set it.',
      },
      {
        latex: '\\frac{1}{4}\\int x^3\\cos u\\,du',
        expr: 'indefinite(x^3*cos(u)/4, u)',
        mistake: 'leftover-x-in-u-integral',
        why: 'x³ dx is absorbed into du/4; no x may remain inside the u-integral.',
      },
    ],
    correct: 0,
    explanation: '$du = 4x^3\\,dx$, so $x^3\\,dx = \\frac{du}{4}$ and $\\cos(x^4+2)$ becomes $\\cos u$.',
    check: { kind: 'identity', lhs: 'cos(u)/4' },
    difficulty: 1,
  },
  {
    id: 'ad-f-052',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: {
      text: 'A student evaluates $\\int_0^{\\sqrt{3}}\\frac{x}{\\sqrt{x^2+1}}\\,dx$ with $u = x^2 + 1$ and writes $\\frac{1}{2}\\int_1^4 u^{-1/2}\\,du = \\sqrt{x^2+1}\\,\\Big|_1^4 = \\sqrt{17} - \\sqrt{2}$. What went wrong?',
    },
    options: [
      { text: 'The limits $1$ and $4$ are $u$-values but were plugged into an expression in $x$.' },
      {
        text: 'The limits should have stayed $0$ and $\\sqrt{3}$ in the $u$-integral.',
        mistake: 'bounds-not-converted',
        why: 'Once the integrand is in u, the limits must be u-values: u(0) = 1 and u(√3) = 4 were right.',
      },
      {
        text: 'Since $du = 2x\\,dx$, the factor in front should be $2$, not $\\frac{1}{2}$.',
        mistake: 'du-constant-wrong',
        why: 'x dx = du/2, so the factor 1/2 is correct.',
      },
      {
        text: 'The antiderivative of $u^{-1/2}$ is $\\ln|u|$.',
        mistake: 'ln-misapplied',
        why: 'Only u^{−1} integrates to ln|u|; ∫u^{−1/2}du = 2u^{1/2}.',
      },
      {
        text: 'The result needs a $+C$.',
        mistake: 'plus-c-misuse',
        why: 'A definite integral is a number; + C does not belong.',
      },
    ],
    correct: 0,
    explanation: 'Once the limits are $u$-values, evaluate in $u$: $\\frac{1}{2}\\int_1^4 u^{-1/2}\\,du = \\sqrt{u}\\,\\Big|_1^4 = 2 - 1 = 1$.',
    check: { kind: 'none', reason: 'conceptual: diagnosing the u-limits-into-x-expression mistake' },
    difficulty: 2,
  },
  {
    id: 'ad-f-053',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: '$F$ is an antiderivative of a continuous function $f$. Which expression equals $\\int_1^4 f(2x)\\,dx$?' },
    options: [
      { latex: '\\frac{1}{2}\\left(F(8) - F(2)\\right)' },
      { latex: 'F(8) - F(2)', mistake: 'inner-constant-factor-missing', why: 'u = 2x gives dx = du/2; the factor 1/2 is missing.' },
      {
        latex: 'F(4) - F(1)',
        mistake: 'bounds-not-converted',
        why: 'Treated f(2x) like f(x): the limits were not converted (u = 2x runs from 2 to 8) and the factor 1/2 is missing.',
      },
      {
        latex: '\\frac{1}{2}\\left(F(4) - F(1)\\right)',
        mistake: 'bounds-not-converted',
        why: 'The limits change with u = 2x: x = 1 gives u = 2 and x = 4 gives u = 8.',
      },
      {
        latex: '\\frac{1}{2}\\left(F(2) - F(8)\\right)',
        mistake: 'ftc-order-swapped',
        why: 'Upper minus lower: the upper u-limit 8 comes first, F(8) − F(2).',
      },
    ],
    correct: 0,
    explanation: 'With $u = 2x$, $du = 2\\,dx$ and $u$ runs from 2 to 8: $\\frac{1}{2}\\int_2^8 f(u)\\,du = \\frac{1}{2}\\left(F(8) - F(2)\\right)$.',
    check: { kind: 'none', reason: 'symbolic answer in an unspecified antiderivative F' },
    difficulty: 2,
  },
  {
    id: 'ad-f-054',
    topic: 'antiderivatives',
    kind: 'concept',
    prompt: { text: 'For $f$ and $g$ continuous on $[a, b]$, which statement is always true?' },
    options: [
      { latex: '\\int_a^b 3f(x)\\,dx = 3\\int_a^b f(x)\\,dx' },
      {
        latex: '\\int_a^b f(x)g(x)\\,dx = \\int_a^b f(x)\\,dx\\cdot\\int_a^b g(x)\\,dx',
        mistake: 'product-rule-integral',
        why: 'There is no product rule for integrals: f = g = 1 on [0, 2] gives 2 on the left but 4 on the right.',
      },
      {
        latex: '\\int_a^b f(x)\\,dx = \\int_b^a f(x)\\,dx',
        mistake: 'bounds-swapped',
        why: 'Reversing the limits changes the sign: the integral from b to a is the negative of the one from a to b.',
      },
      {
        latex: '\\int_a^b |f(x)|\\,dx = \\left|\\int_a^b f(x)\\,dx\\right|',
        mistake: 'signed-area-confusion',
        why: 'Positive and negative parts cancel inside |∫f| but not in ∫|f|: f(x) = x on [−1, 1] gives 1 versus 0.',
      },
      {
        latex: '\\int_a^b \\frac{f(x)}{g(x)}\\,dx = \\frac{\\int_a^b f(x)\\,dx}{\\int_a^b g(x)\\,dx}',
        mistake: 'product-rule-integral',
        why: 'Integrals do not split over quotients any more than over products.',
      },
    ],
    correct: 0,
    explanation: 'Constant multiples come out of a definite integral: $\\int_a^b c\\,f(x)\\,dx = c\\int_a^b f(x)\\,dx$.',
    check: { kind: 'none', reason: 'conceptual: properties of the definite integral' },
    difficulty: 1,
  },

  // ───────────────────────── technique / formula ─────────────────────────
  {
    id: 'ad-f-055',
    topic: 'antiderivatives',
    kind: 'technique',
    prompt: { text: 'Which substitution turns this integral into a basic table integral?', latex: '\\int \\frac{e^x}{1+e^{2x}}\\,dx' },
    options: [
      { text: '$u = e^x$' },
      {
        text: '$u = 1 + e^{2x}$',
        mistake: 'u-choice-wrong',
        why: 'du = 2e^{2x} dx, but the numerator is e^x, not e^{2x}.',
      },
      {
        text: '$u = e^{2x}$',
        mistake: 'u-choice-wrong',
        why: 'du = 2e^{2x} dx does not match the numerator e^x, so a √u remains.',
      },
      {
        text: '$u = 2x$',
        mistake: 'u-choice-wrong',
        why: 'This only rescales the variable; e^{u/2}/(1 + e^u) is no simpler.',
      },
      {
        text: 'No substitution needed: the answer is $\\ln\\left(1 + e^{2x}\\right) + C$',
        mistake: 'ln-misapplied',
        why: 'ln|g| needs g′ = 2e^{2x} in the numerator; here the numerator is e^x.',
      },
    ],
    correct: 0,
    explanation: 'With $u = e^x$, $du = e^x\\,dx$ and $e^{2x} = u^2$: $\\int\\frac{du}{1+u^2} = \\arctan(e^x) + C$.',
    check: { kind: 'none', reason: 'technique recognition; options are substitutions' },
    difficulty: 2,
  },
  {
    id: 'ad-f-056',
    topic: 'antiderivatives',
    kind: 'technique',
    prompt: { text: 'Which substitution works directly?', latex: '\\int \\frac{\\sin(\\ln x)}{x}\\,dx' },
    options: [
      { text: '$u = \\ln x$' },
      {
        text: '$u = \\sin(\\ln x)$',
        mistake: 'u-choice-wrong',
        why: 'du = cos(ln x)/x dx, and cos(ln x) is not in the integrand.',
      },
      {
        text: '$u = \\frac{1}{x}$',
        mistake: 'u-choice-wrong',
        why: 'du = −dx/x² does not match dx/x, and sin(ln x) stays unchanged.',
      },
      {
        text: '$u = \\sin x$',
        mistake: 'u-choice-wrong',
        why: 'The inner function is ln x, not x; sin x does not even appear in the integrand.',
      },
      {
        text: 'Integration by parts with $u = \\sin(\\ln x)$, $dv = \\frac{dx}{x}$',
        mistake: 'ibp-when-usub',
        why: 'This produces ∫ln x cos(ln x)/x dx, which is harder; the integrand already has the form f(g(x))g′(x).',
      },
    ],
    correct: 0,
    explanation: '$u = \\ln x$ gives $du = \\frac{dx}{x}$, so the integral becomes $\\int\\sin u\\,du = -\\cos(\\ln x) + C$.',
    check: { kind: 'none', reason: 'technique recognition; options are substitutions' },
    difficulty: 1,
  },
  {
    id: 'ad-f-057',
    topic: 'antiderivatives',
    kind: 'technique',
    prompt: { text: 'In which integral does the substitution $u = \\tan x$ work directly?' },
    options: [
      { latex: '\\int \\sec^2 x\\,e^{\\tan x}\\,dx' },
      {
        latex: '\\int \\sec x\\,e^{\\tan x}\\,dx',
        mistake: 'du-derivative-wrong',
        why: 'd(tan x) = sec²x dx, not sec x dx; one factor of sec x is missing.',
      },
      {
        latex: '\\int e^{\\tan x}\\,dx',
        mistake: 'u-choice-wrong',
        why: 'The factor sec²x needed for du is missing entirely.',
      },
      {
        latex: '\\int \\cos^2 x\\,e^{\\tan x}\\,dx',
        mistake: 'du-derivative-wrong',
        why: 'sec²x = 1/cos²x, not cos²x; cos²x dx is not du.',
      },
      {
        latex: '\\int \\tan x\\,e^{\\tan x}\\,dx',
        mistake: 'u-choice-wrong',
        why: 'Seeing tan x is not enough: du = sec²x dx must also be present, not tan x dx.',
      },
    ],
    correct: 0,
    explanation: 'With $u = \\tan x$, $du = \\sec^2 x\\,dx$, so $\\int\\sec^2 x\\,e^{\\tan x}\\,dx = \\int e^u\\,du = e^{\\tan x} + C$.',
    check: { kind: 'none', reason: 'pattern recognition of f(g(x))g′(x); options are integrals' },
    difficulty: 1,
  },
  {
    id: 'ad-f-058',
    topic: 'antiderivatives',
    kind: 'technique',
    prompt: { text: 'Which integral does $u = x^2 + 1$ turn into a constant multiple of $\\int u^5\\,du$?' },
    options: [
      { latex: '\\int x(x^2+1)^5\\,dx' },
      {
        latex: '\\int (x^2+1)^5\\,dx',
        mistake: 'u-choice-wrong',
        why: 'du = 2x dx needs a factor x, which is missing.',
      },
      {
        latex: '\\int x^2(x^2+1)^5\\,dx',
        mistake: 'u-choice-wrong',
        why: 'x² dx is not a constant multiple of du = 2x dx; an extra x would remain.',
      },
      {
        latex: '\\int \\frac{(x^2+1)^5}{x}\\,dx',
        mistake: 'u-choice-wrong',
        why: 'Dividing by x is not multiplying by x; dx/x is not a constant multiple of du = 2x dx.',
      },
      {
        latex: '\\int 2(x^2+1)^5\\,dx',
        mistake: 'du-derivative-wrong',
        why: 'd/dx(x² + 1) is 2x, not 2; the factor x is still missing.',
      },
    ],
    correct: 0,
    explanation: '$du = 2x\\,dx$, so $x\\,dx = \\frac{du}{2}$ and $\\int x(x^2+1)^5\\,dx = \\frac{1}{2}\\int u^5\\,du$.',
    check: { kind: 'none', reason: 'pattern recognition of f(g(x))g′(x); options are integrals' },
    difficulty: 1,
  },
  {
    id: 'ad-f-059',
    topic: 'antiderivatives',
    kind: 'formula',
    prompt: {
      text: 'Complete the substitution rule for definite integrals, with $u = g(x)$ and $F$ an antiderivative of $f$:',
      latex: '\\int_a^b f(g(x))\\,g\'(x)\\,dx = \\;?',
    },
    options: [
      { latex: '\\int_{g(a)}^{g(b)} f(u)\\,du' },
      {
        latex: '\\int_a^b f(u)\\,du',
        mistake: 'bounds-not-converted',
        why: 'a and b are x-values; with u = g(x) the limits become g(a) and g(b).',
      },
      {
        latex: '\\int_{g(b)}^{g(a)} f(u)\\,du',
        mistake: 'bounds-swapped',
        why: 'x = a corresponds to the lower limit u = g(a), and x = b to the upper limit u = g(b).',
      },
      {
        latex: '\\int_{g(a)}^{g(b)} f(u)\\,g\'(u)\\,du',
        mistake: 'leftover-x-in-u-integral',
        why: 'g′(x) dx is exactly du; it must not appear again inside the u-integral.',
      },
      {
        latex: '\\int_{g(a)}^{g(b)} f(g(u))\\,du',
        mistake: 'back-substitution-wrong',
        why: 'f(g(x)) becomes f(u), not f(g(u)); g is applied only once.',
      },
    ],
    correct: 0,
    explanation: 'Put $u = g(x)$, $du = g\'(x)\\,dx$; $x = a$ gives $u = g(a)$ and $x = b$ gives $u = g(b)$, so the result is $F(g(b)) - F(g(a))$.',
    check: { kind: 'none', reason: 'symbolic statement of the substitution rule' },
    difficulty: 1,
  },
  {
    id: 'ad-f-060',
    topic: 'antiderivatives',
    kind: 'formula',
    prompt: { text: 'If $f$ is continuous on $[a, b]$ and $F\' = f$, the Fundamental Theorem of Calculus (Part 2) says $\\int_a^b f(x)\\,dx =$' },
    options: [
      { latex: 'F(b) - F(a)' },
      { latex: 'F(a) - F(b)', mistake: 'ftc-order-swapped', why: 'The upper limit comes first: F(b) − F(a).' },
      { latex: 'f(b) - f(a)', mistake: 'formula-swapped', why: 'The antiderivative F is evaluated at the limits, not the integrand f.' },
      { latex: 'F(b) + F(a)', mistake: 'ftc-not-subtracted', why: 'The values at the two limits are subtracted, not added.' },
      {
        latex: '\\frac{F(b) - F(a)}{b - a}',
        mistake: 'formula-swapped',
        why: 'That is the average rate of change of F on [a, b]; the integral itself is F(b) − F(a), with no division.',
      },
    ],
    correct: 0,
    explanation: 'FTC Part 2: for continuous $f$ and any antiderivative $F$, $\\int_a^b f(x)\\,dx = F(b) - F(a)$.',
    check: { kind: 'none', reason: 'symbolic statement of FTC Part 2' },
    difficulty: 1,
  },
  {
    id: 'ad-f-061',
    topic: 'antiderivatives',
    kind: 'formula',
    prompt: { text: 'For $n \\ne -1$, the power rule for integrals says $\\int x^n\\,dx =$' },
    options: [
      { latex: '\\frac{x^{n+1}}{n+1} + C', expr: 'x^(n+1)/(n+1)' },
      {
        latex: '\\frac{x^{n+1}}{n} + C',
        expr: 'x^(n+1)/n',
        mistake: 'power-rule-int-coefficient',
        why: 'Divide by the new exponent n + 1, not the old exponent n.',
      },
      {
        latex: '(n+1)x^{n+1} + C',
        expr: '(n+1)*x^(n+1)',
        mistake: 'power-rule-int-coefficient',
        why: 'Multiplied by n + 1 instead of dividing by it.',
      },
      {
        latex: 'nx^{n-1} + C',
        expr: 'n*x^(n-1)',
        mistake: 'differentiated-instead',
        why: 'This is the power rule for derivatives, d/dx xⁿ.',
      },
      {
        latex: '\\frac{x^{n-1}}{n-1} + C',
        expr: 'x^(n-1)/(n-1)',
        mistake: 'power-rule-int-exponent',
        why: 'Integrating raises the exponent by 1; it does not lower it.',
      },
      {
        latex: '\\ln|x^n| + C',
        expr: 'log(abs(x^n))',
        mistake: 'ln-misapplied',
        why: 'The logarithm appears only for n = −1, which is excluded here.',
      },
    ],
    correct: 0,
    explanation: 'For $n \\ne -1$, $\\frac{d}{dx}\\frac{x^{n+1}}{n+1} = x^n$, so $\\int x^n\\,dx = \\frac{x^{n+1}}{n+1} + C$.',
    check: { kind: 'antiderivative', integrand: 'x^n' },
    domain: { x: [0.5, 2], n: [1.5, 3.5] },
    difficulty: 1,
  },
  {
    id: 'ad-f-062',
    topic: 'antiderivatives',
    kind: 'formula',
    prompt: { text: 'For a constant base $a > 0$, $a \\ne 1$: $\\int a^x\\,dx =$' },
    options: [
      { latex: '\\frac{a^x}{\\ln a} + C', expr: 'a^x/log(a)' },
      {
        latex: 'a^x\\ln a + C',
        expr: 'a^x*log(a)',
        mistake: 'differentiated-instead',
        why: 'a^x ln a is the derivative of a^x; integrating divides by ln a.',
      },
      {
        latex: '\\frac{a^{x+1}}{x+1} + C',
        expr: 'a^(x+1)/(x+1)',
        mistake: 'exp-antiderivative-wrong',
        why: 'The power rule does not apply: the variable is in the exponent, not the base.',
      },
      {
        latex: 'a^x + C',
        expr: 'a^x',
        mistake: 'exp-base-log-missing',
        why: 'Only base e is its own antiderivative; for base a divide by ln a.',
      },
      {
        latex: 'xa^{x-1} + C',
        expr: 'x*a^(x-1)',
        mistake: 'exponential-as-power',
        why: 'Treated a^x like the power x^a; the variable is in the exponent.',
      },
    ],
    correct: 0,
    explanation: '$\\frac{d}{dx}\\frac{a^x}{\\ln a} = \\frac{a^x\\ln a}{\\ln a} = a^x$.',
    check: { kind: 'antiderivative', integrand: 'a^x' },
    domain: { x: [0.25, 1.25], a: [1.5, 5] },
    difficulty: 1,
  },
];

// ───────────────────────── generators ─────────────────────────
function mulberry(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** `x^{k}` for display (plain `x` when k = 1). */
function xPowTex(k: number): string {
  return k === 1 ? 'x' : `x^{${k}}`;
}
/** `x^k` for mathjs (plain `x` when k = 1). */
function xPowExpr(k: number): string {
  return k === 1 ? 'x' : `x^${k}`;
}

/** Powers used by the reciprocal-power generator (3 is covered by ad-f-001). */
const RECIP_POWERS = [2, 4, 5, 6, 7, 8, 9];

/** Parameterized generators (optional). */
export const generators: FlashGenerator[] = [
  {
    id: 'ad-g-recip-power',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    describe: '∫ 1/xⁿ dx for n ∈ {2, 4, …, 9}: power rule with a negative exponent',
    generate(seed) {
      const rng = mulberry(seed);
      const n = RECIP_POWERS[Math.floor(rng() * RECIP_POWERS.length)];
      const m = n - 1; // new exponent is −m
      const coefTex = (c: number) => (c === 1 ? '' : `${c}`);
      return {
        id: `ad-g-recip-power:${seed}`,
        topic: 'antiderivatives',
        kind: 'antiderivative',
        prompt: { latex: `\\frac{1}{x^{${n}}}` },
        options: [
          { latex: `-\\frac{1}{${coefTex(m)}${xPowTex(m)}} + C`, expr: `-1/(${m}*${xPowExpr(m)})` },
          {
            latex: `\\frac{1}{${coefTex(m)}${xPowTex(m)}} + C`,
            expr: `1/(${m}*${xPowExpr(m)})`,
            mistake: 'sign-error',
            why: `The new exponent is −${n} + 1 = −${m}, and dividing by −${m} makes the result negative; that minus sign was dropped.`,
          },
          {
            latex: `-\\frac{1}{${n}${xPowTex(m)}} + C`,
            expr: `-1/(${n}*${xPowExpr(m)})`,
            mistake: 'power-rule-int-coefficient',
            why: `The exponent was raised to −${m} correctly, but the division was by the old exponent −${n} instead of the new exponent −${m}.`,
          },
          {
            latex: `\\frac{1}{${n}${xPowTex(m)}} + C`,
            expr: `1/(${n}*${xPowExpr(m)})`,
            mistake: 'power-rule-int-coefficient',
            why: `Divided by the old exponent ${n} instead of the new exponent ${m}, and the minus sign from dividing by −${m} was dropped.`,
          },
          {
            latex: `\\frac{1}{${n + 1}x^{${n + 1}}} + C`,
            expr: `1/(${n + 1}*x^${n + 1})`,
            mistake: 'power-rule-int-exponent',
            why: `The exponent was lowered from −${n} to −${n + 1} (as when differentiating) instead of raised to −${m}, then divided by ${n + 1}.`,
          },
          {
            latex: `-\\frac{${n}}{x^{${n + 1}}} + C`,
            expr: `-${n}/x^${n + 1}`,
            mistake: 'differentiated-instead',
            why: `This is the derivative of x^{−${n}}, namely −${n}x^{−${n + 1}}, not an antiderivative.`,
          },
        ],
        correct: 0,
        explanation: `$\\int x^{-${n}}\\,dx = \\frac{x^{-${m}}}{-${m}} + C = -\\frac{1}{${coefTex(m)}${xPowTex(m)}} + C$.`,
        check: { kind: 'antiderivative', integrand: `1/x^${n}` },
        difficulty: 1,
      };
    },
  },
  {
    id: 'ad-g-exp-kx',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    describe: '∫ e^{kx} dx for k = ±2 … ±9: the 1/k factor from the inner kx',
    generate(seed) {
      const rng = mulberry(seed);
      const k = 2 + Math.floor(rng() * 8); // 2..9
      const neg = rng() < 0.5;
      const K = neg ? -k : k; // signed inner coefficient
      const ekx = `e^{${K}x}`;
      const ekxExpr = `exp(${K}*x)`;
      const correctTex = neg ? `-\\frac{1}{${k}}${ekx}` : `\\frac{1}{${k}}${ekx}`;
      const options: FlashItem['options'] = [
        neg ? { latex: `${correctTex} + C`, expr: `-${ekxExpr}/${k}` } : { latex: `${correctTex} + C`, expr: `${ekxExpr}/${k}` },
        {
          latex: `${ekx} + C`,
          expr: ekxExpr,
          mistake: 'inner-constant-factor-missing',
          why: `With u = ${K}x, dx = du/(${K}); the factor 1/(${K}) is missing.`,
        },
        {
          latex: `${K}${ekx} + C`,
          expr: `${K}*${ekxExpr}`,
          mistake: 'differentiated-instead',
          why: `Multiplying by ${K} gives the derivative of e^{${K}x}; integrating divides by ${K}.`,
        },
        {
          latex: `\\frac{e^{${K}x+1}}{${K}x+1} + C`,
          expr: `exp(${K}*x+1)/(${K}*x+1)`,
          mistake: 'exp-antiderivative-wrong',
          why: 'The power rule does not apply to e^u; the variable is in the exponent.',
        },
        {
          latex: `\\frac{${ekx}}{${K}x} + C`,
          expr: `${ekxExpr}/(${K}*x)`,
          mistake: 'exp-antiderivative-wrong',
          why: `Divided by the whole exponent ${K}x; only the constant ${K} (the derivative of ${K}x) is divided out.`,
        },
      ];
      if (neg) {
        options.push({
          latex: `\\frac{1}{${k}}${ekx} + C`,
          expr: `${ekxExpr}/${k}`,
          mistake: 'sign-error',
          why: `Dividing by −${k} makes the coefficient −1/${k}; the minus sign was dropped.`,
        });
      }
      return {
        id: `ad-g-exp-kx:${seed}`,
        topic: 'antiderivatives',
        kind: 'antiderivative',
        prompt: { latex: ekx },
        options,
        correct: 0,
        explanation: `With $u = ${K}x$, $dx = \\frac{du}{${K}}$: $\\int ${ekx}\\,dx = ${correctTex} + C$.`,
        check: { kind: 'antiderivative', integrand: ekxExpr },
        difficulty: 1,
      };
    },
  },
  {
    id: 'ad-g-trig-kx',
    topic: 'antiderivatives',
    kind: 'antiderivative',
    describe: '∫ sin(kx) dx or ∫ cos(kx) dx for k = 2 … 9: sign and the 1/k factor',
    generate(seed) {
      const rng = mulberry(seed);
      const k = 2 + Math.floor(rng() * 8); // 2..9
      const isSin = rng() < 0.5;
      const kx = `${k}x`;
      const kxE = `${k}*x`;
      if (isSin) {
        return {
          id: `ad-g-trig-kx:${seed}`,
          topic: 'antiderivatives',
          kind: 'antiderivative',
          prompt: { latex: `\\sin(${kx})` },
          options: [
            { latex: `-\\frac{1}{${k}}\\cos(${kx}) + C`, expr: `-cos(${kxE})/${k}` },
            {
              latex: `-\\cos(${kx}) + C`,
              expr: `-cos(${kxE})`,
              mistake: 'inner-constant-factor-missing',
              why: `With u = ${kx}, dx = du/${k}; the factor 1/${k} is missing.`,
            },
            {
              latex: `-${k}\\cos(${kx}) + C`,
              expr: `-${k}*cos(${kxE})`,
              mistake: 'inner-constant-factor-missing',
              why: `Multiplied by the inner constant ${k} instead of dividing by it.`,
            },
            {
              latex: `\\frac{1}{${k}}\\cos(${kx}) + C`,
              expr: `cos(${kxE})/${k}`,
              mistake: 'trig-antiderivative-sign',
              why: '∫sin u du = −cos u; the minus sign was dropped.',
            },
            {
              latex: `${k}\\cos(${kx}) + C`,
              expr: `${k}*cos(${kxE})`,
              mistake: 'differentiated-instead',
              why: `This is the derivative of sin(${kx}), not an antiderivative.`,
            },
            {
              latex: `\\cos(${kx}) + C`,
              expr: `cos(${kxE})`,
              mistake: 'trig-antiderivative-sign',
              why: `Dropped both the minus sign of ∫sin u du = −cos u and the factor 1/${k} from dx = du/${k}.`,
            },
          ],
          correct: 0,
          explanation: `With $u = ${kx}$, $dx = \\frac{du}{${k}}$: $\\frac{1}{${k}}\\int\\sin u\\,du = -\\frac{1}{${k}}\\cos(${kx}) + C$.`,
          check: { kind: 'antiderivative', integrand: `sin(${kxE})` },
          difficulty: 1,
        };
      }
      return {
        id: `ad-g-trig-kx:${seed}`,
        topic: 'antiderivatives',
        kind: 'antiderivative',
        prompt: { latex: `\\cos(${kx})` },
        options: [
          { latex: `\\frac{1}{${k}}\\sin(${kx}) + C`, expr: `sin(${kxE})/${k}` },
          {
            latex: `\\sin(${kx}) + C`,
            expr: `sin(${kxE})`,
            mistake: 'inner-constant-factor-missing',
            why: `With u = ${kx}, dx = du/${k}; the factor 1/${k} is missing.`,
          },
          {
            latex: `${k}\\sin(${kx}) + C`,
            expr: `${k}*sin(${kxE})`,
            mistake: 'inner-constant-factor-missing',
            why: `Multiplied by the inner constant ${k} instead of dividing by it.`,
          },
          {
            latex: `-\\frac{1}{${k}}\\sin(${kx}) + C`,
            expr: `-sin(${kxE})/${k}`,
            mistake: 'trig-antiderivative-sign',
            why: '∫cos u du = +sin u; the minus sign belongs to ∫sin u du = −cos u.',
          },
          {
            latex: `-${k}\\sin(${kx}) + C`,
            expr: `-${k}*sin(${kxE})`,
            mistake: 'differentiated-instead',
            why: `This is the derivative of cos(${kx}), not an antiderivative.`,
          },
          {
            latex: `-\\sin(${kx}) + C`,
            expr: `-sin(${kxE})`,
            mistake: 'trig-antiderivative-sign',
            why: `Added a minus sign that belongs to ∫sin u du, and dropped the factor 1/${k} from dx = du/${k}.`,
          },
        ],
        correct: 0,
        explanation: `With $u = ${kx}$, $dx = \\frac{du}{${k}}$: $\\frac{1}{${k}}\\int\\cos u\\,du = \\frac{1}{${k}}\\sin(${kx}) + C$.`,
        check: { kind: 'antiderivative', integrand: `cos(${kxE})` },
        difficulty: 1,
      };
    },
  },
];
