import type { FlashGenerator, FlashItem } from '../types';

/** Flash Drill items for topic "arc-length". Authored by content-author; verified by math-verifier. */
export const flash: FlashItem[] = [
  // ───────────── formulas & what they mean ─────────────
  {
    id: 'al-f-001',
    topic: 'arc-length',
    kind: 'formula',
    prompt: { text: "The curve $y = f(x)$ has $f'$ continuous on $[a, b]$. Its length from $x = a$ to $x = b$ is" },
    options: [
      { latex: "L = \\int_a^b \\sqrt{1 + \\left(f'(x)\\right)^2}\\,dx" },
      {
        latex: "L = \\int_c^d \\sqrt{1 + \\left(g'(y)\\right)^2}\\,dy",
        mistake: 'arclength-variable-mismatch',
        why: 'That is the formula for a curve written as x = g(y) with y-limits; this curve is y = f(x) with x-limits a and b.',
      },
      {
        latex: 'L = \\int_a^b \\sqrt{1 + \\left(f(x)\\right)^2}\\,dx',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'The formula squares the slope f′(x), not the height f(x).',
      },
      {
        latex: "L = \\int_a^b \\sqrt{1 + f'(x)}\\,dx",
        mistake: 'arclength-not-squared',
        why: 'The derivative must be squared: the rise over a small piece is f′(x)dx, and the Pythagorean theorem squares it.',
      },
      {
        latex: "L = \\int_a^b \\left(1 + \\left(f'(x)\\right)^2\\right)dx",
        mistake: 'arclength-no-root',
        why: 'The square root is missing; without it the integrand is the squared length of a small piece, not its length.',
      },
      {
        latex: "L = \\int_a^b \\sqrt{\\left(f'(x)\\right)^2}\\,dx",
        mistake: 'arclength-missing-one',
        why: 'The 1 (from the horizontal leg dx) is missing; √((f′)²) = |f′| measures only the vertical change.',
      },
    ],
    correct: 0,
    explanation: "Theorem 5.1: for $y = f(x)$ on $[a, b]$, $L = \\int_a^b \\sqrt{1 + (f'(x))^2}\\,dx$.",
    check: { kind: 'none', reason: 'formula recall for an arbitrary function f' },
    difficulty: 1,
  },
  {
    id: 'al-f-002',
    topic: 'arc-length',
    kind: 'formula',
    prompt: { text: "The curve $x = g(y)$ has $g'$ continuous on $[c, d]$. Its length from $y = c$ to $y = d$ is" },
    options: [
      { latex: "L = \\int_c^d \\sqrt{1 + \\left(g'(y)\\right)^2}\\,dy" },
      {
        latex: "L = \\int_a^b \\sqrt{1 + \\left(f'(x)\\right)^2}\\,dx",
        mistake: 'arclength-variable-mismatch',
        why: 'That is the formula for y = f(x) with x-limits; here the curve is x = g(y) and c, d are y-values.',
      },
      {
        latex: "L = \\int_c^d \\sqrt{1 + \\left(g'(y)\\right)^2}\\,dx",
        mistake: 'dx-dy-mismatch',
        why: 'The integrand and the limits are in y, so the differential must be dy, not dx.',
      },
      {
        latex: 'L = \\int_c^d \\sqrt{1 + \\left(g(y)\\right)^2}\\,dy',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'The formula squares the derivative g′(y), not the function value g(y).',
      },
      {
        latex: "L = \\int_c^d \\left(1 + \\left|g'(y)\\right|\\right)dy",
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √((g′)²) = 1 + |g′|; a square root does not split over a sum.',
      },
      {
        latex: "L = \\int_c^d \\sqrt{1 + g'(y)}\\,dy",
        mistake: 'arclength-not-squared',
        why: 'The derivative g′(y) must be squared inside the root.',
      },
    ],
    correct: 0,
    explanation: "Theorem 5.2: for $x = g(y)$ on $[c, d]$, $L = \\int_c^d \\sqrt{1 + (g'(y))^2}\\,dy$.",
    check: { kind: 'none', reason: 'formula recall for an arbitrary function g' },
    difficulty: 1,
  },
  {
    id: 'al-f-003',
    topic: 'arc-length',
    kind: 'formula',
    prompt: { text: "In $L = \\int_a^b \\sqrt{1 + (f'(x))^2}\\,dx$, the quantity $\\sqrt{1 + (f'(x))^2}\\,dx$ is" },
    options: [
      { text: "the length of the tiny piece of the curve over $[x, x + dx]$, the hypotenuse of a right triangle with legs $dx$ and $f'(x)\\,dx$" },
      {
        text: 'the area of the thin rectangle of width $dx$ and height $f(x)$ under the curve over $[x, x + dx]$',
        mistake: 'formula-swapped',
        why: 'That describes f(x)dx, the area element; arc length adds up hypotenuse lengths, not rectangle areas.',
      },
      {
        text: "the vertical rise $|f'(x)|\\,dx$ of the curve over $[x, x + dx]$, one leg of the small right triangle there",
        mistake: 'arclength-missing-one',
        why: 'The rise alone is √((f′)²)dx; the 1 under the root accounts for the horizontal leg dx.',
      },
      {
        text: "the sum $dx + |f'(x)|\\,dx$ of the horizontal run and the vertical rise of the small right triangle",
        mistake: 'sqrt-of-sum-split',
        why: 'Adding the two legs gives (1 + |f′|)dx; the hypotenuse √(dx² + (f′dx)²) is shorter than that sum.',
      },
      {
        text: "the squared length $(dx)^2 + (f'(x)\\,dx)^2$ of the tiny piece of the curve over $[x, x + dx]$",
        mistake: 'arclength-no-root',
        why: 'The squared length would be (1 + (f′)²)dx²; the square root turns it into an actual length.',
      },
      {
        text: 'the length of the straight chord from $(a, f(a))$ to $(b, f(b))$, split evenly over $[a, b]$',
        mistake: 'formula-swapped',
        why: 'The chord is one straight segment; the integral adds up tiny segments that follow the curve itself.',
      },
    ],
    correct: 0,
    explanation: "Over $[x, x + dx]$ the curve rises about $f'(x)\\,dx$, so the piece has length $\\sqrt{dx^2 + (f'(x)dx)^2} = \\sqrt{1 + (f'(x))^2}\\,dx$.",
    check: { kind: 'none', reason: 'conceptual: meaning of the arc-length element' },
    difficulty: 1,
  },
  {
    id: 'al-f-004',
    topic: 'arc-length',
    kind: 'formula',
    prompt: { text: 'The curve $y = f(x)$ runs from the point $(a, c)$ to the point $(b, d)$. Which expression gives its length?' },
    options: [
      { latex: "\\int_a^b \\sqrt{1 + \\left(f'(x)\\right)^2}\\,dx" },
      {
        latex: "\\int_c^d \\sqrt{1 + \\left(f'(x)\\right)^2}\\,dx",
        mistake: 'arclength-variable-mismatch',
        why: 'c and d are the y-coordinates of the endpoints; a dx integral runs over the x-coordinates a to b.',
      },
      {
        latex: "\\int_a^b \\sqrt{1 + \\left(f'(x)\\right)^2}\\,dy",
        mistake: 'dx-dy-mismatch',
        why: 'The integrand and the limits are in x, so the differential must be dx.',
      },
      {
        latex: "\\int_c^d \\sqrt{1 + \\left(f'(y)\\right)^2}\\,dy",
        mistake: 'arclength-variable-mismatch',
        why: 'To integrate in y the curve must be rewritten as x = g(y); f′(y) is not the slope dx/dy.',
      },
      {
        latex: '\\sqrt{(b - a)^2 + (d - c)^2}',
        mistake: 'formula-swapped',
        why: 'This is the straight-line distance between the endpoints (the chord), which is shorter than the curve unless the curve is a line.',
      },
      {
        latex: '\\int_a^b \\sqrt{1 + \\left(f(x)\\right)^2}\\,dx',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'The formula squares the slope f′(x), not the height f(x).',
      },
    ],
    correct: 0,
    explanation: "Integrating in $x$ uses $y = f(x)$ and the endpoints' $x$-values: $L = \\int_a^b \\sqrt{1 + (f'(x))^2}\\,dx$.",
    check: { kind: 'none', reason: 'formula recall with symbolic limits' },
    difficulty: 1,
  },
  {
    id: 'al-f-005',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'To compute an arc length by integrating with respect to $y$, you must' },
    options: [
      { text: 'write the curve as $x = g(y)$ and use the $y$-values of the endpoints as the limits' },
      {
        text: 'write the curve as $x = g(y)$ and use the $x$-values of the endpoints as the limits',
        mistake: 'bounds-wrong-axis',
        why: 'In a dy integral the limits must be y-values; the x-values belong to a dx integral.',
      },
      {
        text: "keep $y = f(x)$, use $\\sqrt{1 + (f'(x))^2}$, and change $dx$ to $dy$ with the $y$-values as limits",
        mistake: 'dx-dy-mismatch',
        why: 'f′(x) is dy/dx and is written in x; a dy integral needs dx/dy = g′(y), written in y.',
      },
      {
        text: 'replace every $x$ in $f(x)$ by $y$ and use the $y$-values of the endpoints as the limits',
        mistake: 'inverse-function-wrong',
        why: 'Swapping the letters is not solving for x; x = g(y) comes from solving y = f(x) for x.',
      },
      {
        text: 'write the curve as $x = g(y)$ and integrate $\\sqrt{1 + (g(y))^2}$ over the $y$-values',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'The integrand squares the derivative g′(y), not g(y) itself.',
      },
    ],
    correct: 0,
    explanation: 'Theorem 5.2 needs the curve as $x = g(y)$, the integrand $\\sqrt{1 + (g\'(y))^2}$, and $y$-values as limits.',
    check: { kind: 'none', reason: 'conceptual: setting up a dy arc-length integral' },
    difficulty: 1,
  },
  {
    id: 'al-f-006',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'To find the length of $y^2 = x^3$ from $(1, 1)$ to $(4, 8)$ by integrating with respect to $y$, use' },
    options: [
      { text: '$x = y^{2/3}$ with $1 \\le y \\le 8$' },
      {
        text: '$x = y^{2/3}$ with $1 \\le y \\le 4$',
        mistake: 'bounds-wrong-axis',
        why: '1 and 4 are the x-coordinates of the endpoints; a dy integral runs over the y-values 1 to 8.',
      },
      {
        text: '$x = y^{3/2}$ with $1 \\le y \\le 8$',
        mistake: 'inverse-function-wrong',
        why: 'From x³ = y², x = (y²)^{1/3} = y^{2/3}; the exponent 3/2 inverts the relation the wrong way.',
      },
      {
        text: '$y = x^{3/2}$ with $1 \\le y \\le 8$',
        mistake: 'arclength-variable-mismatch',
        why: 'A dy integral needs the curve solved for x as a function of y, not y as a function of x.',
      },
      {
        text: '$x = y^{1/3}$ with $1 \\le y \\le 8$',
        mistake: 'inverse-function-wrong',
        why: 'x³ = y² gives x = (y²)^{1/3} = y^{2/3}; the square on y was lost.',
      },
    ],
    correct: 0,
    explanation: 'Solve $x^3 = y^2$ for $x$: $x = y^{2/3}$; the endpoints have $y = 1$ and $y = 8$.',
    check: { kind: 'none', reason: 'options pair a curve with an interval (text)' },
    difficulty: 1,
  },
  {
    id: 'al-f-007',
    topic: 'arc-length',
    kind: 'concept',
    prompt: {
      text: 'For $y = \\frac{1}{2}\\ln(\\sin 2x)$ on $[\\frac{\\pi}{8}, \\frac{\\pi}{6}]$, the arc-length integrand becomes $\\sqrt{\\csc^2(2x)}$. Why may we replace it by $\\csc(2x)$?',
    },
    options: [
      { text: 'On $[\\frac{\\pi}{8}, \\frac{\\pi}{6}]$, $2x$ is in the first quadrant, so $\\sin 2x > 0$ and $|\\csc 2x| = \\csc 2x$.' },
      {
        text: 'Because $\\sqrt{u^2} = u$ for every real number $u$, so the root and the square cancel.',
        mistake: 'sqrt-square-abs',
        why: '√(u²) = |u|, not u; the sign of csc 2x on the interval still has to be checked.',
      },
      {
        text: 'On $[\\frac{\\pi}{8}, \\frac{\\pi}{6}]$, $x$ is positive, so every expression in $x$ is positive there.',
        mistake: 'theta-interval-sign',
        why: 'What matters is the sign of csc 2x itself, not of x; plenty of functions are negative for positive x.',
      },
      {
        text: 'Since $\\csc^2(2x) = 1 + \\cot^2(2x) \\ge 1$, its square root is $\\csc 2x$ on any interval.',
        mistake: 'sqrt-square-abs',
        why: 'That only shows the radicand is at least 1; the root is still |csc 2x|, which equals −csc 2x where sin 2x < 0.',
      },
      {
        text: 'On $[\\frac{\\pi}{8}, \\frac{\\pi}{6}]$, $\\cos 2x > 0$, so $|\\csc 2x| = \\csc 2x$ there.',
        mistake: 'theta-interval-sign',
        why: 'csc 2x = 1/sin 2x, so its sign is the sign of sin 2x; the sign of cos 2x is irrelevant.',
      },
    ],
    correct: 0,
    explanation: '$\\sqrt{\\csc^2 2x} = |\\csc 2x|$, and for $2x \\in [\\frac{\\pi}{4}, \\frac{\\pi}{3}]$ we have $\\sin 2x > 0$, so $|\\csc 2x| = \\csc 2x$.',
    check: { kind: 'none', reason: 'conceptual: justification of √(u²) = |u| on the interval' },
    difficulty: 1,
  },
  {
    id: 'al-f-008',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'A curve can be written both as $y = f(x)$ and as $x = g(y)$. Which description should you use for its arc length?' },
    options: [
      { text: 'Either one gives the same length; pick the one with the simpler derivative and simpler integrand.' },
      {
        text: 'Always $y = f(x)$: an arc-length integral must be taken with respect to $x$.',
        mistake: 'arclength-variable-mismatch',
        why: 'Theorem 5.2 integrates with respect to y; both variables are allowed.',
      },
      {
        text: 'The one whose interval of integration is shorter, since that gives the smaller, correct length.',
        mistake: 'method-choice-poor',
        why: 'Both integrals give the same length of the same curve; only the difficulty of the integral changes.',
      },
      {
        text: 'Either one, but they give different lengths, so the $x$-version is the official answer.',
        mistake: 'arclength-variable-mismatch',
        why: 'Both describe the same curve, so the two integrals are equal; neither is more official.',
      },
      {
        text: 'Always $x = g(y)$, because integrals in $y$ never contain a square root.',
        mistake: 'technique-wrong',
        why: 'The dy formula has the same √(1 + (g′)²) structure; choose by which derivative is simpler.',
      },
    ],
    correct: 0,
    explanation: 'Both formulas measure the same curve; the lecture says to choose the representation with the simpler derivative and integrand.',
    check: { kind: 'none', reason: 'conceptual: choosing the variable of integration' },
    difficulty: 1,
  },

  // ───────────── "the arc-length integrand for … is" (identity checks) ─────────────
  {
    id: 'al-f-009',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: "The arc-length integrand $\\sqrt{1 + (f'(x))^2}$ for $y = \\frac{2}{3}x^{3/2}$ is" },
    options: [
      { latex: '\\sqrt{1 + x}', expr: 'sqrt(1 + x)' },
      {
        latex: '\\sqrt{1 + \\frac{4}{9}x^3}',
        expr: 'sqrt(1 + 4/9*x^3)',
        mistake: 'arclength-f-instead-of-fprime',
        why: '(⅔x^{3/2})² = (4/9)x³ is f(x)², not the square of the derivative f′(x) = x^{1/2}.',
      },
      {
        latex: '\\sqrt{1 + \\sqrt{x}}',
        expr: 'sqrt(1 + sqrt(x))',
        mistake: 'arclength-not-squared',
        why: 'f′(x) = √x was put under the root without squaring it; (√x)² = x.',
      },
      {
        latex: '1 + \\sqrt{x}',
        expr: '1 + sqrt(x)',
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √x; √(1 + x) is not 1 + √x.',
      },
      {
        latex: '\\sqrt{1 + x^2}',
        expr: 'sqrt(1 + x^2)',
        mistake: 'power-rule-exponent',
        why: 'f′ was taken as x (exponent lowered by ½ instead of by 1); the correct f′ = ⅔·(3/2)x^{1/2} = x^{1/2}.',
      },
      {
        latex: '\\sqrt{1 + \\frac{4}{9}x}',
        expr: 'sqrt(1 + 4/9*x)',
        mistake: 'power-rule-coefficient',
        why: 'The exponent 3/2 was not brought down: f′ = ⅔·(3/2)x^{1/2} = x^{1/2}, not ⅔x^{1/2}.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = \\frac{2}{3}\\cdot\\frac{3}{2}x^{1/2} = \\sqrt{x}$, so $1 + (f'(x))^2 = 1 + x$.",
    check: { kind: 'identity', lhs: 'sqrt(1 + (2/3*3/2*x^(1/2))^2)' },
    difficulty: 1,
  },
  {
    id: 'al-f-010',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: "The arc-length integrand $\\sqrt{1 + (f'(x))^2}$ for $y = \\ln(\\cos x)$ is" },
    options: [
      { latex: '\\sqrt{1 + \\tan^2 x}', expr: 'sqrt(1 + tan(x)^2)' },
      {
        latex: '\\sqrt{1 + \\cot^2 x}',
        expr: 'sqrt(1 + cot(x)^2)',
        mistake: 'log-derivative-wrong',
        why: 'd/dx ln u = u′/u = −sin x/cos x; flipping the quotient to u/u′ gives cot x instead of −tan x.',
      },
      {
        latex: '\\sqrt{1 + \\sec^2 x}',
        expr: 'sqrt(1 + sec(x)^2)',
        mistake: 'chain-rule-missing',
        why: 'd/dx ln(cos x) was written as 1/cos x; the inner derivative −sin x is missing.',
      },
      {
        latex: '\\sqrt{1 - \\tan x}',
        expr: 'sqrt(1 - tan(x))',
        mistake: 'arclength-not-squared',
        why: 'f′(x) = −tan x was placed under the root without being squared.',
      },
      {
        latex: '\\sqrt{1 + \\ln^2(\\cos x)}',
        expr: 'sqrt(1 + log(cos(x))^2)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares f(x) = ln(cos x) instead of the derivative f′(x) = −tan x.',
      },
      {
        latex: '\\sqrt{1 - \\tan^2 x}',
        expr: 'sqrt(1 - tan(x)^2)',
        mistake: 'negative-squared-wrong',
        why: '(−tan x)² = +tan²x; the minus sign cannot survive squaring.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = \\frac{-\\sin x}{\\cos x} = -\\tan x$, and $(-\\tan x)^2 = \\tan^2 x$.",
    domain: [0.2, 0.7],
    check: { kind: 'identity', lhs: 'sqrt(1 + (-sin(x)/cos(x))^2)' },
    difficulty: 1,
  },
  {
    id: 'al-f-011',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: "The arc-length integrand $\\sqrt{1 + (f'(x))^2}$ for $y = \\frac{1}{2}\\ln(\\sin 2x)$ is" },
    options: [
      { latex: '\\sqrt{1 + \\cot^2(2x)}', expr: 'sqrt(1 + cot(2*x)^2)' },
      {
        latex: '\\sqrt{1 + \\frac{1}{4}\\cot^2(2x)}',
        expr: 'sqrt(1 + cot(2*x)^2/4)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative 2 of sin 2x was dropped, leaving f′ = ½cot 2x instead of cot 2x.',
      },
      {
        latex: '\\sqrt{1 + 4\\cot^2(2x)}',
        expr: 'sqrt(1 + 4*cot(2*x)^2)',
        mistake: 'coefficient-mishandled',
        why: 'The factor ½ in front of ln was dropped, leaving f′ = 2cot 2x; with it, ½·2cot 2x = cot 2x.',
      },
      {
        latex: '\\sqrt{1 + \\tan^2(2x)}',
        expr: 'sqrt(1 + tan(2*x)^2)',
        mistake: 'log-derivative-wrong',
        why: 'd/dx ln u = u′/u = 2cos 2x/sin 2x; flipping it to u/u′ produces tan 2x.',
      },
      {
        latex: '\\sqrt{1 + \\cot(2x)}',
        expr: 'sqrt(1 + cot(2*x))',
        mistake: 'arclength-not-squared',
        why: 'f′(x) = cot 2x was placed under the root without being squared.',
      },
      {
        latex: '\\sqrt{1 + \\frac{1}{4}\\ln^2(\\sin 2x)}',
        expr: 'sqrt(1 + log(sin(2*x))^2/4)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares f(x) = ½ln(sin 2x) itself instead of its derivative cot 2x.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = \\frac{1}{2}\\cdot\\frac{2\\cos 2x}{\\sin 2x} = \\cot 2x$, so the integrand is $\\sqrt{1 + \\cot^2(2x)}$.",
    domain: [0.3, 0.6],
    check: { kind: 'identity', lhs: 'sqrt(1 + (1/2*(2*cos(2*x))/sin(2*x))^2)' },
    difficulty: 2,
  },
  {
    id: 'al-f-012',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: "The arc-length integrand $\\sqrt{1 + (f'(x))^2}$ for $y = \\ln x$ is" },
    options: [
      { latex: '\\sqrt{1 + \\frac{1}{x^2}}', expr: 'sqrt(1 + 1/x^2)' },
      {
        latex: '\\sqrt{1 + (\\ln x)^2}',
        expr: 'sqrt(1 + log(x)^2)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares f(x) = ln x instead of its derivative 1/x.',
      },
      {
        latex: '\\sqrt{1 + \\frac{1}{x}}',
        expr: 'sqrt(1 + 1/x)',
        mistake: 'arclength-not-squared',
        why: 'f′(x) = 1/x was placed under the root without being squared.',
      },
      {
        latex: '\\sqrt{1 + \\frac{1}{x^4}}',
        expr: 'sqrt(1 + 1/x^4)',
        mistake: 'log-derivative-wrong',
        why: 'd/dx ln x was taken as 1/x²; it is 1/x, whose square is 1/x².',
      },
      {
        latex: '1 + \\frac{1}{x}',
        expr: '1 + 1/x',
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √(1/x²); a square root does not distribute over a sum.',
      },
      {
        latex: '\\sqrt{\\frac{1}{x^2}}',
        expr: 'sqrt(1/x^2)',
        mistake: 'arclength-missing-one',
        why: 'The 1 under the root is missing; √((f′)²) alone measures only the vertical change.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = \\frac{1}{x}$, so $\\sqrt{1 + (f'(x))^2} = \\sqrt{1 + \\frac{1}{x^2}}$.",
    check: { kind: 'identity', lhs: 'sqrt(1 + (1/x)^2)' },
    difficulty: 1,
  },
  {
    id: 'al-f-013',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: "The arc-length integrand $\\sqrt{1 + (f'(x))^2}$ for $f(x) = (x^4 - 1)^{3/2}$ is" },
    options: [
      { latex: '\\sqrt{1 + 36x^6(x^4 - 1)}', expr: 'sqrt(1 + 36*x^6*(x^4 - 1))' },
      {
        latex: '\\sqrt{1 + \\frac{9}{4}(x^4 - 1)}',
        expr: 'sqrt(1 + 9/4*(x^4 - 1))',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative 4x³ of x⁴ − 1 was dropped, so f′ = (3/2)(x⁴ − 1)^{1/2}.',
      },
      {
        latex: '\\sqrt{1 + (x^4 - 1)^3}',
        expr: 'sqrt(1 + (x^4 - 1)^3)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares f(x) = (x⁴ − 1)^{3/2}, not its derivative.',
      },
      {
        latex: '\\sqrt{1 + 6x^3(x^4 - 1)^{1/2}}',
        expr: 'sqrt(1 + 6*x^3*(x^4 - 1)^(1/2))',
        mistake: 'arclength-not-squared',
        why: 'f′(x) = 6x³(x⁴ − 1)^{1/2} was placed under the root without being squared.',
      },
      {
        latex: '\\sqrt{1 + 6x^6(x^4 - 1)}',
        expr: 'sqrt(1 + 6*x^6*(x^4 - 1))',
        mistake: 'coefficient-mishandled',
        why: '(6x³)² = 36x⁶; the coefficient 6 was not squared.',
      },
      {
        latex: '\\sqrt{1 + 36x^6(x^4 - 1)^3}',
        expr: 'sqrt(1 + 36*x^6*(x^4 - 1)^3)',
        mistake: 'power-rule-exponent',
        why: 'The exponent 3/2 was not lowered to 1/2 in f′, so squaring left (x⁴ − 1)³ instead of (x⁴ − 1).',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = \\frac{3}{2}(x^4 - 1)^{1/2}\\cdot 4x^3 = 6x^3\\sqrt{x^4 - 1}$, so $(f'(x))^2 = 36x^6(x^4 - 1)$.",
    domain: [1.05, 1.6],
    check: { kind: 'identity', lhs: 'sqrt(1 + (3/2*(x^4 - 1)^(1/2)*4*x^3)^2)' },
    difficulty: 2,
  },
  {
    id: 'al-f-014',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: "The arc-length integrand $\\sqrt{1 + (g'(y))^2}$ for $x = \\frac{y^3}{6} + \\frac{1}{2y}$ is" },
    options: [
      { latex: '\\sqrt{1 + \\left(\\frac{y^2}{2} - \\frac{1}{2y^2}\\right)^2}', expr: 'sqrt(1 + (y^2/2 - 1/(2*y^2))^2)' },
      {
        latex: '\\sqrt{1 + \\left(\\frac{y^3}{6} + \\frac{1}{2y}\\right)^2}',
        expr: 'sqrt(1 + (y^3/6 + 1/(2*y))^2)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares g(y) itself instead of its derivative g′(y).',
      },
      {
        latex: '\\sqrt{1 + \\left(\\frac{y^2}{2} + \\frac{1}{2y^2}\\right)^2}',
        expr: 'sqrt(1 + (y^2/2 + 1/(2*y^2))^2)',
        mistake: 'negative-exponent-sign',
        why: 'd/dy (1/(2y)) = −1/(2y²); the minus sign from the negative exponent was lost.',
      },
      {
        latex: '\\sqrt{1 + \\left(\\frac{y^2}{6} - \\frac{1}{2y^2}\\right)^2}',
        expr: 'sqrt(1 + (y^2/6 - 1/(2*y^2))^2)',
        mistake: 'power-rule-coefficient',
        why: 'd/dy (y³/6) = 3y²/6 = y²/2; the exponent 3 was not brought down.',
      },
      {
        latex: '\\sqrt{1 + \\frac{y^2}{2} - \\frac{1}{2y^2}}',
        expr: 'sqrt(1 + y^2/2 - 1/(2*y^2))',
        mistake: 'arclength-not-squared',
        why: 'g′(y) was placed under the root without being squared.',
      },
      {
        latex: '\\sqrt{1 + \\left(\\frac{y^2}{2} - \\frac{1}{2y}\\right)^2}',
        expr: 'sqrt(1 + (y^2/2 - 1/(2*y))^2)',
        mistake: 'power-rule-exponent',
        why: 'd/dy (½y^{−1}) = −½y^{−2}; the exponent −1 was not lowered to −2.',
      },
    ],
    correct: 0,
    explanation: "$g'(y) = \\frac{y^2}{2} - \\frac{1}{2y^2}$, and the $dy$ formula squares it: $\\sqrt{1 + (g'(y))^2}$.",
    variable: 'y',
    domain: [1, 2],
    check: { kind: 'identity', lhs: 'sqrt(1 + (3*y^2/6 - 1/(2*y^2))^2)' },
    difficulty: 1,
  },
  {
    id: 'al-f-015',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: "The arc-length integrand $\\sqrt{1 + (f'(x))^2}$ for $y = e^{2x}$ is" },
    options: [
      { latex: '\\sqrt{1 + 4e^{4x}}', expr: 'sqrt(1 + 4*exp(4*x))' },
      {
        latex: '\\sqrt{1 + e^{4x}}',
        expr: 'sqrt(1 + exp(4*x))',
        mistake: 'chain-rule-missing',
        why: 'd/dx e^{2x} = 2e^{2x}; without the inner derivative 2 the square is only e^{4x}.',
      },
      {
        latex: '\\sqrt{1 + 2e^{4x}}',
        expr: 'sqrt(1 + 2*exp(4*x))',
        mistake: 'coefficient-mishandled',
        why: '(2e^{2x})² = 4e^{4x}; the coefficient 2 was not squared.',
      },
      {
        latex: '\\sqrt{1 + 4e^{2x}}',
        expr: 'sqrt(1 + 4*exp(2*x))',
        mistake: 'algebra-error',
        why: '(e^{2x})² = e^{4x}: squaring an exponential doubles its exponent, but here it stayed e^{2x}.',
      },
      {
        latex: '\\sqrt{1 + 2e^{2x}}',
        expr: 'sqrt(1 + 2*exp(2*x))',
        mistake: 'arclength-not-squared',
        why: 'f′(x) = 2e^{2x} was placed under the root without being squared.',
      },
      {
        latex: '\\sqrt{1 + \\frac{1}{4}e^{4x}}',
        expr: 'sqrt(1 + exp(4*x)/4)',
        mistake: 'integrated-instead',
        why: '½e^{2x} is an antiderivative of e^{2x}, not its derivative 2e^{2x}.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = 2e^{2x}$, so $(f'(x))^2 = 4e^{4x}$.",
    check: { kind: 'identity', lhs: 'sqrt(1 + (2*exp(2*x))^2)' },
    difficulty: 1,
  },
  {
    id: 'al-f-016',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: "For the upper semicircle $y = \\sqrt{1 - x^2}$, the expression $1 + (f'(x))^2$ simplifies to" },
    options: [
      { latex: '\\frac{1}{1 - x^2}', expr: '1/(1 - x^2)' },
      {
        latex: '2 - x^2',
        expr: '2 - x^2',
        mistake: 'arclength-f-instead-of-fprime',
        why: '1 + (√(1 − x²))² = 2 − x² uses f(x); the formula needs f′(x) = −x/√(1 − x²).',
      },
      {
        latex: '\\frac{1 - 2x^2}{1 - x^2}',
        expr: '(1 - 2*x^2)/(1 - x^2)',
        mistake: 'negative-squared-wrong',
        why: '(−x/√(1 − x²))² = +x²/(1 − x²); the minus sign was kept after squaring.',
      },
      {
        latex: '\\frac{1 + x^2}{1 - x^2}',
        expr: '(1 + x^2)/(1 - x^2)',
        mistake: 'algebra-error',
        why: '1 + x²/(1 − x²) was combined as (1 + x²)/(1 − x²); the 1 must first become (1 − x²)/(1 − x²).',
      },
      {
        latex: '\\frac{5 - 4x^2}{4 - 4x^2}',
        expr: '(5 - 4*x^2)/(4 - 4*x^2)',
        mistake: 'chain-rule-missing',
        why: 'f′ was taken as 1/(2√(1 − x²)) without the inner derivative −2x, giving 1 + 1/(4(1 − x²)).',
      },
      {
        latex: '\\frac{x^2}{1 - x^2}',
        expr: 'x^2/(1 - x^2)',
        mistake: 'arclength-missing-one',
        why: 'This is (f′)² alone; the 1 was never added.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = \\frac{-x}{\\sqrt{1 - x^2}}$, so $1 + \\frac{x^2}{1 - x^2} = \\frac{1 - x^2 + x^2}{1 - x^2} = \\frac{1}{1 - x^2}$.",
    domain: [0.1, 0.9],
    check: { kind: 'identity', lhs: '1 + (-x/sqrt(1 - x^2))^2' },
    difficulty: 2,
  },
  {
    id: 'al-f-017',
    topic: 'arc-length',
    kind: 'concept',
    prompt: {
      text: "For the first-quadrant arc of the astroid, $y = (1 - x^{2/3})^{3/2}$, the expression $1 + (f'(x))^2$ simplifies to",
    },
    options: [
      { latex: 'x^{-2/3}', expr: 'x^(-2/3)' },
      {
        latex: '\\frac{13}{4} - \\frac{9}{4}x^{2/3}',
        expr: '13/4 - 9/4*x^(2/3)',
        mistake: 'chain-rule-missing',
        why: 'f′ was taken as (3/2)(1 − x^{2/3})^{1/2}, missing the inner derivative −(2/3)x^{−1/3}.',
      },
      {
        latex: '1 + (1 - x^{2/3})^3',
        expr: '1 + (1 - x^(2/3))^3',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares f(x) = (1 − x^{2/3})^{3/2} instead of f′(x).',
      },
      {
        latex: 'x^{-2/3} - 1',
        expr: 'x^(-2/3) - 1',
        mistake: 'arclength-missing-one',
        why: 'This is (f′)² = x^{−2/3}(1 − x^{2/3}) = x^{−2/3} − 1 alone; the 1 was never added.',
      },
      {
        latex: '2 - x^{-2/3}',
        expr: '2 - x^(-2/3)',
        mistake: 'negative-squared-wrong',
        why: 'The square of the negative f′ was taken as −(x^{−2/3} − 1); a square is never negative.',
      },
      {
        latex: '\\frac{9}{4}x^{-2/3} - \\frac{5}{4}',
        expr: '9/4*x^(-2/3) - 5/4',
        mistake: 'power-rule-coefficient',
        why: 'd/dx x^{2/3} was taken as x^{−1/3} without the factor 2/3, so f′ picked up an extra factor 3/2.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = -x^{-1/3}(1 - x^{2/3})^{1/2}$, so $1 + (f')^2 = 1 + x^{-2/3} - 1 = x^{-2/3}$.",
    domain: [0.1, 0.9],
    check: { kind: 'identity', lhs: '1 + ((3/2)*(1 - x^(2/3))^(1/2)*(-(2/3)*x^(-1/3)))^2' },
    difficulty: 2,
  },

  // ───────────── "the arc length of … is given by" (value checks on integrals) ─────────────
  {
    id: 'al-f-018',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of $y = \\frac{1}{3}(x^2 + 2)^{3/2}$ for $0 \\le x \\le 1$ simplifies to' },
    options: [
      { latex: '\\int_0^1 (x^2 + 1)\\,dx', expr: 'integral(x^2 + 1, x, 0, 1)' },
      {
        latex: '\\int_0^1 x\\sqrt{x^2 + 2}\\,dx',
        expr: 'integral(x*sqrt(x^2 + 2), x, 0, 1)',
        mistake: 'arclength-missing-one',
        why: 'Without the 1, the root of (f′)² = x²(x² + 2) is just |f′| = x√(x² + 2).',
      },
      {
        latex: '\\int_0^1 \\left(1 + x\\sqrt{x^2 + 2}\\right)dx',
        expr: 'integral(1 + x*sqrt(x^2 + 2), x, 0, 1)',
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √((f′)²); instead combine 1 + x⁴ + 2x² = (x² + 1)² first.',
      },
      {
        latex: '\\int_0^1 (x^2 + 1)^2\\,dx',
        expr: 'integral((x^2 + 1)^2, x, 0, 1)',
        mistake: 'arclength-no-root',
        why: '1 + (f′)² = (x² + 1)² is the radicand; the square root was never taken.',
      },
      {
        latex: '\\int_0^1 \\sqrt{\\frac{x^2}{4} + \\frac{3}{2}}\\,dx',
        expr: 'integral(sqrt(x^2/4 + 3/2), x, 0, 1)',
        mistake: 'chain-rule-missing',
        why: 'f′ was taken as ½(x² + 2)^{1/2}, missing the inner derivative 2x, so no perfect square appears.',
      },
      {
        latex: '\\int_0^1 \\sqrt{1 + \\frac{(x^2 + 2)^3}{9}}\\,dx',
        expr: 'integral(sqrt(1 + (x^2 + 2)^3/9), x, 0, 1)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares f(x) = ⅓(x² + 2)^{3/2} instead of f′(x) = x√(x² + 2).',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = x\\sqrt{x^2 + 2}$, so $1 + (f')^2 = x^4 + 2x^2 + 1 = (x^2 + 1)^2$ and the root is $x^2 + 1$.",
    check: { kind: 'value', expected: '4/3' },
    difficulty: 1,
  },
  {
    id: 'al-f-019',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of $y^2 = x^3$ from $(1, 1)$ to $(4, 8)$, written as an integral in $x$, is' },
    options: [
      { latex: '\\int_1^4 \\sqrt{1 + \\frac{9}{4}x}\\,dx', expr: 'integral(sqrt(1 + 9/4*x), x, 1, 4)' },
      {
        latex: '\\int_1^8 \\sqrt{1 + \\frac{9}{4}x}\\,dx',
        expr: 'integral(sqrt(1 + 9/4*x), x, 1, 8)',
        mistake: 'arclength-variable-mismatch',
        why: '1 and 8 are the y-coordinates of the endpoints; a dx integral runs from x = 1 to x = 4.',
      },
      {
        latex: '\\int_1^4 \\sqrt{1 + x^3}\\,dx',
        expr: 'integral(sqrt(1 + x^3), x, 1, 4)',
        mistake: 'arclength-f-instead-of-fprime',
        why: '(x^{3/2})² = x³ is f(x)²; the formula needs (f′(x))² = (9/4)x.',
      },
      {
        latex: '\\int_1^4 \\sqrt{1 + \\frac{3}{2}x^{1/2}}\\,dx',
        expr: 'integral(sqrt(1 + 3/2*x^(1/2)), x, 1, 4)',
        mistake: 'arclength-not-squared',
        why: 'f′(x) = (3/2)x^{1/2} was placed under the root without being squared.',
      },
      {
        latex: '\\int_1^4 \\left(1 + \\frac{9}{4}x\\right)dx',
        expr: 'integral(1 + 9/4*x, x, 1, 4)',
        mistake: 'arclength-no-root',
        why: 'The square root around 1 + (f′)² is missing.',
      },
      {
        latex: '\\int_1^4 \\sqrt{1 + \\frac{9}{4}x^2}\\,dx',
        expr: 'integral(sqrt(1 + 9/4*x^2), x, 1, 4)',
        mistake: 'power-rule-exponent',
        why: 'f′ was taken as (3/2)x (exponent lowered by ½); the correct f′ = (3/2)x^{1/2} squares to (9/4)x.',
      },
    ],
    correct: 0,
    explanation: "On the upper branch $y = x^{3/2}$, $f'(x) = \\frac{3}{2}x^{1/2}$, so $L = \\int_1^4 \\sqrt{1 + \\frac{9}{4}x}\\,dx$ over the $x$-values 1 to 4.",
    check: { kind: 'value', expected: '(80*sqrt(10) - 13*sqrt(13))/27' },
    difficulty: 1,
  },
  {
    id: 'al-f-020',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of $y^2 = x^3$ from $(1, 1)$ to $(4, 8)$, written as an integral in $y$, is' },
    options: [
      { latex: '\\int_1^8 \\sqrt{1 + \\frac{4}{9}y^{-2/3}}\\,dy', expr: 'integral(sqrt(1 + 4/9*y^(-2/3)), y, 1, 8)' },
      {
        latex: '\\int_1^4 \\sqrt{1 + \\frac{4}{9}y^{-2/3}}\\,dy',
        expr: 'integral(sqrt(1 + 4/9*y^(-2/3)), y, 1, 4)',
        mistake: 'arclength-variable-mismatch',
        why: '1 and 4 are the x-coordinates; in y the endpoints are y = 1 and y = 8.',
      },
      {
        latex: '\\int_1^8 \\sqrt{1 + \\frac{9}{4}y}\\,dy',
        expr: 'integral(sqrt(1 + 9/4*y), y, 1, 8)',
        mistake: 'arclength-variable-mismatch',
        why: 'This reuses (f′(x))² = 9x/4 with x renamed y; in y the slope is g′(y) = (2/3)y^{−1/3}.',
      },
      {
        latex: '\\int_1^8 \\sqrt{1 + y^{4/3}}\\,dy',
        expr: 'integral(sqrt(1 + y^(4/3)), y, 1, 8)',
        mistake: 'arclength-f-instead-of-fprime',
        why: '(y^{2/3})² = y^{4/3} is g(y)²; the formula needs (g′(y))².',
      },
      {
        latex: '\\int_1^8 \\sqrt{1 + \\frac{2}{3}y^{-1/3}}\\,dy',
        expr: 'integral(sqrt(1 + 2/3*y^(-1/3)), y, 1, 8)',
        mistake: 'arclength-not-squared',
        why: 'g′(y) = (2/3)y^{−1/3} was placed under the root without being squared.',
      },
      {
        latex: '\\int_1^8 \\sqrt{1 + \\frac{4}{9}y^{2/3}}\\,dy',
        expr: 'integral(sqrt(1 + 4/9*y^(2/3)), y, 1, 8)',
        mistake: 'power-rule-exponent',
        why: 'd/dy y^{2/3} = (2/3)y^{−1/3}; the new exponent 2/3 − 1 = −1/3 was taken as +1/3.',
      },
    ],
    correct: 0,
    explanation: "Here $x = y^{2/3}$, $g'(y) = \\frac{2}{3}y^{-1/3}$, $(g')^2 = \\frac{4}{9}y^{-2/3}$, and $y$ runs from 1 to 8.",
    check: { kind: 'value', expected: '(80*sqrt(10) - 13*sqrt(13))/27' },
    difficulty: 2,
  },
  {
    id: 'al-f-021',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'Using the upper semicircle $y = \\sqrt{1 - x^2}$ and symmetry, the perimeter of the unit circle equals' },
    options: [
      { latex: '4\\int_0^1 \\frac{1}{\\sqrt{1 - x^2}}\\,dx', expr: '4*integral(1/sqrt(1 - x^2), x, 0, 1)' },
      {
        latex: '\\int_{-1}^{1} \\frac{1}{\\sqrt{1 - x^2}}\\,dx',
        expr: 'integral(1/sqrt(1 - x^2), x, -1, 1)',
        mistake: 'coefficient-mishandled',
        why: 'y = √(1 − x²) traces only the upper half of the circle; the lower half doubles the result.',
      },
      {
        latex: '\\int_0^1 \\frac{1}{\\sqrt{1 - x^2}}\\,dx',
        expr: 'integral(1/sqrt(1 - x^2), x, 0, 1)',
        mistake: 'coefficient-mishandled',
        why: 'From x = 0 to x = 1 the upper semicircle is one quarter of the circle; multiply by 4.',
      },
      {
        latex: '4\\int_0^1 \\frac{x}{\\sqrt{1 - x^2}}\\,dx',
        expr: '4*integral(x/sqrt(1 - x^2), x, 0, 1)',
        mistake: 'arclength-missing-one',
        why: 'x/√(1 − x²) is √((f′)²) = |f′|; the 1 under the root was dropped.',
      },
      {
        latex: '4\\int_0^1 \\sqrt{2 - x^2}\\,dx',
        expr: '4*integral(sqrt(2 - x^2), x, 0, 1)',
        mistake: 'arclength-f-instead-of-fprime',
        why: '1 + (√(1 − x²))² = 2 − x² squares f(x); the formula squares f′(x) = −x/√(1 − x²).',
      },
      {
        latex: '4\\int_0^1 \\left(1 + \\frac{x}{\\sqrt{1 - x^2}}\\right)dx',
        expr: '4*integral(1 + x/sqrt(1 - x^2), x, 0, 1)',
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √((f′)²); combine 1 + x²/(1 − x²) = 1/(1 − x²) first.',
      },
    ],
    correct: 0,
    explanation: "$1 + (f')^2 = \\frac{1}{1 - x^2}$; the arc from $x = 0$ to $1$ is a quarter circle, so the perimeter is $4\\int_0^1 \\frac{dx}{\\sqrt{1 - x^2}}$.",
    check: { kind: 'value', expected: '2*pi' },
    difficulty: 1,
  },
  {
    id: 'al-f-022',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of $y = \\ln(\\cos x)$ for $0 \\le x \\le \\frac{\\pi}{3}$ simplifies to' },
    options: [
      { latex: '\\int_0^{\\pi/3} \\sec x\\,dx', expr: 'integral(sec(x), x, 0, pi/3)' },
      {
        latex: '\\int_0^{\\pi/3} \\tan x\\,dx',
        expr: 'integral(tan(x), x, 0, pi/3)',
        mistake: 'arclength-missing-one',
        why: 'Without the 1, √(tan²x) = tan x only measures the vertical change; 1 + tan²x = sec²x.',
      },
      {
        latex: '\\int_0^{\\pi/3} \\sec^2 x\\,dx',
        expr: 'integral(sec(x)^2, x, 0, pi/3)',
        mistake: 'arclength-no-root',
        why: '1 + tan²x = sec²x is the radicand; its square root is sec x.',
      },
      {
        latex: '\\int_0^{\\pi/3} (1 + \\tan x)\\,dx',
        expr: 'integral(1 + tan(x), x, 0, pi/3)',
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √(tan²x); use 1 + tan²x = sec²x instead.',
      },
      {
        latex: '\\int_0^{\\pi/3} (-\\sec x)\\,dx',
        expr: 'integral(-sec(x), x, 0, pi/3)',
        mistake: 'theta-interval-sign',
        why: '√(sec²x) = |sec x|, and sec x > 0 on [0, π/3]; a length cannot come out negative.',
      },
      {
        latex: '\\int_0^{\\pi/3} \\sqrt{1 + \\ln^2(\\cos x)}\\,dx',
        expr: 'integral(sqrt(1 + log(cos(x))^2), x, 0, pi/3)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares f(x) = ln(cos x) instead of f′(x) = −tan x.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = -\\tan x$, $1 + \\tan^2 x = \\sec^2 x$, and $\\sqrt{\\sec^2 x} = \\sec x$ because $\\cos x > 0$ on $[0, \\frac{\\pi}{3}]$.",
    check: { kind: 'value', expected: 'log(2 + sqrt(3))' },
    difficulty: 1,
  },
  {
    id: 'al-f-023',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of $y = \\frac{1}{2}\\ln(\\sin 2x)$ for $\\frac{\\pi}{8} \\le x \\le \\frac{\\pi}{6}$ simplifies to' },
    options: [
      { latex: '\\int_{\\pi/8}^{\\pi/6} \\csc(2x)\\,dx', expr: 'integral(csc(2*x), x, pi/8, pi/6)' },
      {
        latex: '\\int_{\\pi/8}^{\\pi/6} \\cot(2x)\\,dx',
        expr: 'integral(cot(2*x), x, pi/8, pi/6)',
        mistake: 'arclength-missing-one',
        why: 'Without the 1, √(cot²2x) = cot 2x; the 1 is what turns cot² into csc².',
      },
      {
        latex: '\\int_{\\pi/8}^{\\pi/6} \\csc^2(2x)\\,dx',
        expr: 'integral(csc(2*x)^2, x, pi/8, pi/6)',
        mistake: 'arclength-no-root',
        why: '1 + cot²2x = csc²2x is the radicand; its square root is csc 2x.',
      },
      {
        latex: '\\int_{\\pi/8}^{\\pi/6} \\sec(2x)\\,dx',
        expr: 'integral(sec(2*x), x, pi/8, pi/6)',
        mistake: 'pythagorean-wrong',
        why: 'The identity is 1 + cot²θ = csc²θ; sec² pairs with tan².',
      },
      {
        latex: '\\int_{\\pi/8}^{\\pi/6} \\frac{1}{2}\\csc(2x)\\,dx',
        expr: 'integral(csc(2*x)/2, x, pi/8, pi/6)',
        mistake: 'coefficient-mishandled',
        why: 'The ½ from f is used up in f′ = ½·(2cos 2x/sin 2x) = cot 2x; it does not reappear in front.',
      },
      {
        latex: '\\int_{\\pi/8}^{\\pi/6} \\left(1 + \\cot(2x)\\right)dx',
        expr: 'integral(1 + cot(2*x), x, pi/8, pi/6)',
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √(cot²2x); use 1 + cot²2x = csc²2x instead.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = \\cot 2x$, $1 + \\cot^2 2x = \\csc^2 2x$, and $\\csc 2x > 0$ on the interval, so $L = \\int \\csc(2x)\\,dx$.",
    check: { kind: 'value', expected: 'log((sqrt(2) + 1)/sqrt(3))/2' },
    difficulty: 2,
  },
  {
    id: 'al-f-024',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of $x = e^{y} + \\frac{1}{4}e^{-y}$ for $0 \\le y \\le 1$ simplifies to' },
    options: [
      { latex: '\\int_0^1 \\left(e^{y} + \\frac{1}{4}e^{-y}\\right)dy', expr: 'integral(exp(y) + exp(-y)/4, y, 0, 1)' },
      {
        latex: '\\int_0^1 \\left(e^{y} - \\frac{1}{4}e^{-y}\\right)dy',
        expr: 'integral(exp(y) - exp(-y)/4, y, 0, 1)',
        mistake: 'arclength-missing-one',
        why: 'This is √((g′)²) = g′: without the 1 the middle term of the square never flips to +½.',
      },
      {
        latex: '\\int_0^1 \\left(1 + e^{y} - \\frac{1}{4}e^{-y}\\right)dy',
        expr: 'integral(1 + exp(y) - exp(-y)/4, y, 0, 1)',
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √((g′)²); instead 1 + (g′)² = (e^y + ¼e^{−y})².',
      },
      {
        latex: '\\int_0^1 \\left(e^{y} + \\frac{1}{4}e^{-y}\\right)^2 dy',
        expr: 'integral((exp(y) + exp(-y)/4)^2, y, 0, 1)',
        mistake: 'arclength-no-root',
        why: '(e^y + ¼e^{−y})² is the radicand; the square root was never taken.',
      },
      {
        latex: '\\int_{5/4}^{e + 1/(4e)} \\left(e^{y} + \\frac{1}{4}e^{-y}\\right)dy',
        expr: 'integral(exp(y) + exp(-y)/4, y, 5/4, e + 1/(4*e))',
        mistake: 'arclength-variable-mismatch',
        why: '5/4 and e + 1/(4e) are the x-values of the endpoints; a dy integral runs from y = 0 to y = 1.',
      },
      {
        latex: '\\int_0^1 \\sqrt{1 + \\left(e^{y} + \\frac{1}{4}e^{-y}\\right)^2}\\,dy',
        expr: 'integral(sqrt(1 + (exp(y) + exp(-y)/4)^2), y, 0, 1)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares g(y) itself; the formula uses g′(y) = e^y − ¼e^{−y}.',
      },
    ],
    correct: 0,
    explanation: "$1 + (e^{y} - \\frac{1}{4}e^{-y})^2 = e^{2y} + \\frac{1}{2} + \\frac{1}{16}e^{-2y} = (e^{y} + \\frac{1}{4}e^{-y})^2$, a positive quantity.",
    check: { kind: 'value', expected: 'e - 1/(4*e) - 3/4' },
    difficulty: 1,
  },
  {
    id: 'al-f-025',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of $y = \\frac{x^3}{6} + \\frac{1}{2x}$ for $1 \\le x \\le 2$ simplifies to' },
    options: [
      { latex: '\\int_1^2 \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)dx', expr: 'integral(x^2/2 + 1/(2*x^2), x, 1, 2)' },
      {
        latex: '\\int_1^2 \\left(\\frac{x^2}{2} - \\frac{1}{2x^2}\\right)dx',
        expr: 'integral(x^2/2 - 1/(2*x^2), x, 1, 2)',
        mistake: 'arclength-missing-one',
        why: 'This is √((f′)²) = f′: the 1 was dropped, so the middle sign of the square never flipped.',
      },
      {
        latex: '\\int_1^2 \\left(1 + \\frac{x^2}{2} - \\frac{1}{2x^2}\\right)dx',
        expr: 'integral(1 + x^2/2 - 1/(2*x^2), x, 1, 2)',
        mistake: 'sqrt-of-sum-split',
        why: 'The root was split as √1 + √((f′)²); instead 1 + (f′)² = (x²/2 + 1/(2x²))².',
      },
      {
        latex: '\\int_1^2 \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)^2 dx',
        expr: 'integral((x^2/2 + 1/(2*x^2))^2, x, 1, 2)',
        mistake: 'arclength-no-root',
        why: 'This square is the radicand 1 + (f′)²; the root was never taken.',
      },
      {
        latex: '\\int_1^2 \\left(\\frac{x^3}{6} + \\frac{1}{2x}\\right)dx',
        expr: 'integral(x^3/6 + 1/(2*x), x, 1, 2)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'The perfect square is built from f′ = x²/2 − 1/(2x²) with its middle sign flipped, not from f itself.',
      },
      {
        latex: '\\int_1^2 \\left(\\frac{x^2}{2} + \\frac{1}{2x}\\right)dx',
        expr: 'integral(x^2/2 + 1/(2*x), x, 1, 2)',
        mistake: 'power-rule-exponent',
        why: 'd/dx (½x^{−1}) = −½x^{−2}; keeping the exponent −1 gives 1/(2x) instead of 1/(2x²).',
      },
    ],
    correct: 0,
    explanation: "$1 + \\left(\\frac{x^2}{2} - \\frac{1}{2x^2}\\right)^2 = \\left(\\frac{x^2}{2} + \\frac{1}{2x^2}\\right)^2$, and that base is positive.",
    check: { kind: 'value', expected: '17/12' },
    difficulty: 1,
  },
  {
    id: 'al-f-026',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of $f(x) = (x^3 - 1)^{3/2}$ from $x = 1$ to $x = 4$ is' },
    options: [
      { latex: '\\int_1^4 \\sqrt{1 + \\frac{81}{4}x^4(x^3 - 1)}\\,dx', expr: 'integral(sqrt(1 + 81/4*x^4*(x^3 - 1)), x, 1, 4)' },
      {
        latex: '\\int_1^4 \\sqrt{1 + \\frac{9}{4}(x^3 - 1)}\\,dx',
        expr: 'integral(sqrt(1 + 9/4*(x^3 - 1)), x, 1, 4)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative 3x² of x³ − 1 was dropped, so f′ = (3/2)(x³ − 1)^{1/2}.',
      },
      {
        latex: '\\int_1^4 \\sqrt{1 + (x^3 - 1)^3}\\,dx',
        expr: 'integral(sqrt(1 + (x^3 - 1)^3), x, 1, 4)',
        mistake: 'arclength-f-instead-of-fprime',
        why: 'This squares f(x) = (x³ − 1)^{3/2} instead of its derivative.',
      },
      {
        latex: '\\int_1^4 \\sqrt{1 + \\frac{9}{2}x^2(x^3 - 1)^{1/2}}\\,dx',
        expr: 'integral(sqrt(1 + 9/2*x^2*(x^3 - 1)^(1/2)), x, 1, 4)',
        mistake: 'arclength-not-squared',
        why: 'f′(x) = (9/2)x²(x³ − 1)^{1/2} was placed under the root without being squared.',
      },
      {
        latex: '\\int_1^4 \\sqrt{1 + \\frac{9}{2}x^4(x^3 - 1)}\\,dx',
        expr: 'integral(sqrt(1 + 9/2*x^4*(x^3 - 1)), x, 1, 4)',
        mistake: 'coefficient-mishandled',
        why: '((9/2)x²)² = (81/4)x⁴; the coefficient 9/2 was not squared.',
      },
      {
        latex: '\\int_1^4 \\sqrt{1 + 9x^4(x^3 - 1)}\\,dx',
        expr: 'integral(sqrt(1 + 9*x^4*(x^3 - 1)), x, 1, 4)',
        mistake: 'power-rule-coefficient',
        why: 'The exponent 3/2 was not brought down: f′ = (3/2)(x³ − 1)^{1/2}·3x², not 3x²(x³ − 1)^{1/2}.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = \\frac{3}{2}(x^3 - 1)^{1/2}\\cdot 3x^2 = \\frac{9}{2}x^2\\sqrt{x^3 - 1}$, so $(f')^2 = \\frac{81}{4}x^4(x^3 - 1)$.",
    check: { kind: 'value', expected: 'integral(sqrt(1 + (3/2*(x^3 - 1)^(1/2)*3*x^2)^2), x, 1, 4)' },
    difficulty: 2,
  },
  {
    id: 'al-f-027',
    topic: 'arc-length',
    kind: 'concept',
    prompt: { text: 'The length of the line $y = 2x + 1$ from $x = 0$ to $x = 3$ is' },
    options: [
      { latex: '3\\sqrt{5}', expr: '3*sqrt(5)' },
      {
        latex: '3\\sqrt{3}',
        expr: '3*sqrt(3)',
        mistake: 'arclength-not-squared',
        why: 'The slope 2 was not squared: √(1 + 2) instead of √(1 + 2²).',
      },
      {
        latex: '9',
        expr: '9',
        mistake: 'sqrt-of-sum-split',
        why: '√(1 + 2²) was split into 1 + 2 = 3, giving 3·3 = 9.',
      },
      {
        latex: '15',
        expr: '15',
        mistake: 'arclength-no-root',
        why: '∫₀³(1 + 2²)dx = 15: the square root of 5 was never taken.',
      },
      {
        latex: '6',
        expr: '6',
        mistake: 'arclength-missing-one',
        why: '∫₀³√(2²)dx = 6 measures only the vertical rise from y = 1 to y = 7.',
      },
      {
        latex: '6\\sqrt{5}',
        expr: '6*sqrt(5)',
        mistake: 'arclength-variable-mismatch',
        why: 'The y-values 1 to 7 (a span of 6) were used as limits of the dx integral instead of x from 0 to 3.',
      },
    ],
    correct: 0,
    explanation: "$f'(x) = 2$, so $L = \\int_0^3 \\sqrt{1 + 4}\\,dx = 3\\sqrt{5}$, the distance from $(0, 1)$ to $(3, 7)$.",
    check: { kind: 'value', expected: 'integral(sqrt(1 + 2^2), x, 0, 3)' },
    difficulty: 1,
  },
];

/** Parameterized generators (optional). */
export const generators: FlashGenerator[] = [];
