import type { FlashGenerator, FlashItem } from '../types';

/**
 * Flash Drill items for topic "diff-review" (Lecture 1, §1.4–1.7: the derivative rules and table).
 * Authored by content-author; verified by math-verifier.
 *
 * Seeds: the lecture's "Try it yourself" list — d/dx(2), x^{3/4}, 1/x², ∛(x²), e^{2x} − 1, x ln x,
 * sin x/(1 + cos x), 5^{x²}, 1/∛(x² + x + 1), arccos(√x), sec⁻¹(√x − 1), (tan⁻¹x)², sin⁻¹(5x) —
 * plus the rest of the derivative table (tan, sec, csc, cot, a^x, log_a x, inverse trig).
 * Course convention: d/dx sec⁻¹x = 1/(|x|√(x² − 1)); sample points for sec⁻¹ items have |u| > 1.
 * Both notations appear in class: \sin^{-1}, \tan^{-1} and \arcsin, \arctan.
 */
export const flash: FlashItem[] = [
  // ───────────── Lecture "Try it yourself" list and close relatives ─────────────
  {
    id: 'dr-f-001',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'x^{3/4}' },
    options: [
      {
        latex: '\\frac{3}{4}x^{3/4}',
        expr: '3/4*x^(3/4)',
        mistake: 'power-rule-exponent',
        why: 'The exponent was left at $\\frac34$; the power rule lowers it by 1, to $-\\frac14$.',
      },
      { latex: '\\frac{3}{4}x^{-1/4}', expr: '3/4*x^(-1/4)' },
      {
        latex: '\\frac{3}{4}x^{1/4}',
        expr: '3/4*x^(1/4)',
        mistake: 'power-rule-exponent',
        why: '$\\frac34 - 1$ was computed as $+\\frac14$; it is $-\\frac14$.',
      },
      {
        latex: '\\frac{4}{7}x^{7/4}',
        expr: '4/7*x^(7/4)',
        mistake: 'integrated-instead',
        why: 'Raising the exponent to $\\frac74$ and dividing by it gives the antiderivative, not the derivative.',
      },
      {
        latex: '-\\frac{1}{4}x^{-1/4}',
        expr: '-1/4*x^(-1/4)',
        mistake: 'power-rule-coefficient',
        why: 'The new exponent $-\\frac14$ was used as the coefficient; the power rule multiplies by the old exponent $\\frac34$.',
      },
      {
        latex: '\\frac{3}{4}x^{7/4}',
        expr: '3/4*x^(7/4)',
        mistake: 'power-rule-exponent',
        why: 'One was added to the exponent (as when integrating) instead of subtracted.',
      },
    ],
    correct: 1,
    explanation: 'Power rule $\\frac{d}{dx}x^n = nx^{n-1}$ with $n = \\frac34$: $\\frac34 x^{-1/4}$.',
    check: { kind: 'derivative', of: 'x^(3/4)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-002',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\frac{1}{x^2}' },
    options: [
      {
        latex: '\\frac{2}{x^3}',
        expr: '2/x^3',
        mistake: 'negative-exponent-sign',
        why: 'Written as $x^{-2}$, the power rule brings down $-2$, so the derivative is negative.',
      },
      {
        latex: '-\\frac{2}{x}',
        expr: '-2/x',
        mistake: 'power-rule-exponent',
        why: 'The exponent went from $-2$ up to $-1$; subtracting 1 gives $-3$.',
      },
      { latex: '-\\frac{2}{x^3}', expr: '-2/x^3' },
      {
        latex: '-\\frac{1}{x}',
        expr: '-1/x',
        mistake: 'integrated-instead',
        why: '$-\\frac1x$ is the antiderivative of $\\frac{1}{x^2}$, not its derivative.',
      },
      {
        latex: '-\\frac{3}{x^3}',
        expr: '-3/x^3',
        mistake: 'power-rule-coefficient',
        why: 'The new exponent $-3$ was used as the coefficient; the power rule multiplies by the old exponent $-2$.',
      },
      {
        latex: '-\\frac{2}{x^2}',
        expr: '-2/x^2',
        mistake: 'power-rule-exponent',
        why: 'The $-2$ was brought down but the exponent was not lowered: $x^{-2}$ must become $x^{-3}$.',
      },
    ],
    correct: 2,
    explanation: '$\\frac{1}{x^2} = x^{-2}$, so the power rule gives $-2x^{-3} = -\\frac{2}{x^3}$.',
    check: { kind: 'derivative', of: '1/x^2' },
    difficulty: 1,
  },
  {
    id: 'dr-f-003',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\sqrt[3]{x^2}' },
    options: [
      {
        latex: '\\frac{3}{2}\\sqrt{x}',
        expr: '3/2*sqrt(x)',
        mistake: 'algebra-error',
        why: 'The root was rewritten as $x^{3/2}$ (index and power swapped); $\\sqrt[3]{x^2} = x^{2/3}$.',
      },
      {
        latex: '\\frac{2}{3}\\sqrt[3]{x}',
        expr: '2/3*nthRoot(x, 3)',
        mistake: 'power-rule-exponent',
        why: '$\\frac23 - 1$ was taken as $+\\frac13$; it is $-\\frac13$, which puts $\\sqrt[3]{x}$ in the denominator.',
      },
      {
        latex: '\\frac{3}{5}\\sqrt[3]{x^5}',
        expr: '3/5*nthRoot(x^5, 3)',
        mistake: 'integrated-instead',
        why: 'Raising the exponent to $\\frac53$ and dividing by it gives the antiderivative.',
      },
      { latex: '\\frac{2}{3\\sqrt[3]{x}}', expr: '2/(3*nthRoot(x, 3))' },
      {
        latex: '-\\frac{1}{3\\sqrt[3]{x}}',
        expr: '-1/(3*nthRoot(x, 3))',
        mistake: 'power-rule-coefficient',
        why: 'The coefficient must be the old exponent $\\frac23$, not the new exponent $-\\frac13$.',
      },
      {
        latex: '\\frac{2}{3}\\sqrt[3]{x^2}',
        expr: '2/3*nthRoot(x^2, 3)',
        mistake: 'power-rule-exponent',
        why: 'The $\\frac23$ was brought down but the exponent stayed $\\frac23$; it must drop to $-\\frac13$.',
      },
    ],
    correct: 3,
    explanation: '$\\sqrt[3]{x^2} = x^{2/3}$, so $f\'(x) = \\frac23 x^{-1/3} = \\frac{2}{3\\sqrt[3]{x}}$.',
    check: { kind: 'derivative', of: 'x^(2/3)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-004',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'e^{2x} - 1' },
    options: [
      {
        latex: 'e^{2x}',
        expr: 'exp(2*x)',
        mistake: 'chain-rule-missing',
        why: '$e^{2x}$ was treated like $e^x$; the chain rule multiplies by the inner derivative $2$.',
      },
      {
        latex: '2e^{2x} - 1',
        expr: '2*exp(2*x) - 1',
        mistake: 'constant-derivative',
        why: 'The constant $-1$ has derivative $0$; it must disappear.',
      },
      {
        latex: '2xe^{2x-1}',
        expr: '2*x*exp(2*x - 1)',
        mistake: 'exponential-as-power',
        why: 'The power rule was applied to $e^{2x}$ (exponent brought down and lowered by 1); $e^u$ differentiates to $e^u\\cdot u\'$.',
      },
      {
        latex: '\\frac{1}{2}e^{2x}',
        expr: 'exp(2*x)/2',
        mistake: 'integrated-instead',
        why: 'Dividing by 2 gives the antiderivative of $e^{2x}$; differentiating multiplies by 2.',
      },
      { latex: '2e^{2x}', expr: '2*exp(2*x)' },
      {
        latex: '2xe^{2x}',
        expr: '2*x*exp(2*x)',
        mistake: 'exponential-as-power',
        why: 'The exponent $2x$ itself was brought down in front; the chain-rule factor is its derivative, $2$.',
      },
    ],
    correct: 4,
    explanation: 'Chain rule: $\\frac{d}{dx}e^{2x} = e^{2x}\\cdot 2$, and the constant $-1$ contributes $0$.',
    check: { kind: 'derivative', of: 'exp(2*x) - 1' },
    difficulty: 1,
  },
  {
    id: 'dr-f-005',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'x\\ln x' },
    options: [
      {
        latex: '\\ln x',
        expr: 'log(x)',
        mistake: 'product-rule-missing-term',
        why: 'Only $x$ was differentiated; the term $x\\cdot(\\ln x)\' = x\\cdot\\frac1x = 1$ is missing.',
      },
      {
        latex: '1 + \\frac{1}{x}',
        expr: '1 + 1/x',
        mistake: 'product-rule-missing-term',
        why: 'Each factor was differentiated and the results added; the product rule keeps the other factor in each term.',
      },
      {
        latex: '\\ln x + x',
        expr: 'log(x) + x',
        mistake: 'log-derivative-wrong',
        why: '$(\\ln x)\'$ was taken as 1, so the second term became $x$; it is $x\\cdot\\frac1x = 1$.',
      },
      {
        latex: '\\ln x - 1',
        expr: 'log(x) - 1',
        mistake: 'sign-error',
        why: 'The two product-rule terms were subtracted, as in the quotient rule; the product rule adds them.',
      },
      {
        latex: '\\ln x + \\frac{1}{x}',
        expr: 'log(x) + 1/x',
        mistake: 'product-rule-missing-term',
        why: 'The factor $x$ was dropped from the second term: it is $x\\cdot\\frac1x$, not just $\\frac1x$.',
      },
      { latex: '\\ln x + 1', expr: 'log(x) + 1' },
    ],
    correct: 5,
    explanation: 'Product rule: $(x)\'\\ln x + x(\\ln x)\' = \\ln x + x\\cdot\\frac1x = \\ln x + 1$.',
    check: { kind: 'derivative', of: 'x*log(x)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-006',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '5^{x^2}' },
    options: [
      { latex: '2x\\cdot 5^{x^2}\\ln 5', expr: '2*x*5^(x^2)*log(5)' },
      {
        latex: '2x\\cdot 5^{x^2}',
        expr: '2*x*5^(x^2)',
        mistake: 'exp-base-log-missing',
        why: '$\\frac{d}{du}5^u = 5^u\\ln 5$; the factor $\\ln 5$ is missing (only $e^u$ is its own derivative).',
      },
      {
        latex: '5^{x^2}\\ln 5',
        expr: '5^(x^2)*log(5)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(x^2)\' = 2x$ was dropped.',
      },
      {
        latex: 'x^2\\cdot 5^{x^2-1}',
        expr: 'x^2*5^(x^2 - 1)',
        mistake: 'exponential-as-power',
        why: 'The power rule was applied to $5^{x^2}$, but the variable is in the exponent, so the exponential rule applies.',
      },
      {
        latex: '2x\\cdot 5^{x^2}\\ln x',
        expr: '2*x*5^(x^2)*log(x)',
        mistake: 'exp-base-log-missing',
        why: 'The factor is the log of the base, $\\ln 5$, not $\\ln x$.',
      },
      {
        latex: '\\frac{2x\\cdot 5^{x^2}}{\\ln 5}',
        expr: '2*x*5^(x^2)/log(5)',
        mistake: 'exp-base-log-missing',
        why: 'Dividing by $\\ln 5$ belongs to the antiderivative $\\int 5^u\\,du = \\frac{5^u}{\\ln 5} + C$; the derivative multiplies by $\\ln 5$.',
      },
    ],
    correct: 0,
    explanation: '$\\frac{d}{dx}a^{u} = a^{u}\\ln a\\cdot u\'$ with $a = 5$, $u = x^2$: $5^{x^2}\\ln 5\\cdot 2x$.',
    check: { kind: 'derivative', of: '5^(x^2)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-007',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\frac{1}{\\sqrt{x^3+1}}' },
    options: [
      {
        latex: '-\\frac{1}{2(x^3+1)^{3/2}}',
        expr: '-1/(2*(x^3 + 1)^(3/2))',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(x^3 + 1)\' = 3x^2$ was dropped.',
      },
      {
        latex: '\\frac{3x^2}{2(x^3+1)^{3/2}}',
        expr: '3*x^2/(2*(x^3 + 1)^(3/2))',
        mistake: 'negative-exponent-sign',
        why: 'The exponent is $-\\frac12$, so the power rule brings down a negative factor.',
      },
      { latex: '-\\frac{3x^2}{2(x^3+1)^{3/2}}', expr: '-3*x^2/(2*(x^3 + 1)^(3/2))' },
      {
        latex: '-\\frac{3x^2}{2(x^3+1)^{1/2}}',
        expr: '-3*x^2/(2*(x^3 + 1)^(1/2))',
        mistake: 'power-rule-exponent',
        why: 'The exponent was not lowered: $(x^3+1)^{-1/2}$ must become $(x^3+1)^{-3/2}$.',
      },
      {
        latex: '-\\frac{3x^2}{(x^3+1)^{3/2}}',
        expr: '-3*x^2/(x^3 + 1)^(3/2)',
        mistake: 'power-rule-coefficient',
        why: 'The factor $\\frac12$ from the exponent $-\\frac12$ was dropped.',
      },
      {
        latex: '\\frac{3x^2}{2(x^3+1)^{1/2}}',
        expr: '3*x^2/(2*(x^3 + 1)^(1/2))',
        mistake: 'negative-exponent-sign',
        why: '$\\frac{1}{\\sqrt{u}}$ was rewritten as $u^{1/2}$ instead of $u^{-1/2}$ before differentiating.',
      },
    ],
    correct: 2,
    explanation: 'Write $f = (x^3+1)^{-1/2}$; chain rule: $-\\frac12(x^3+1)^{-3/2}\\cdot 3x^2$.',
    check: { kind: 'derivative', of: '(x^3 + 1)^(-1/2)' },
    difficulty: 2,
  },
  {
    id: 'dr-f-008',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\cos^{-1}(x^2)' },
    options: [
      {
        latex: '\\frac{2x}{\\sqrt{1-x^4}}',
        expr: '2*x/sqrt(1 - x^4)',
        mistake: 'sign-error-derivative',
        why: '$\\frac{d}{du}\\cos^{-1}u = -\\frac{1}{\\sqrt{1-u^2}}$; without the minus sign this is the arcsine derivative.',
      },
      {
        latex: '-\\frac{1}{\\sqrt{1-x^4}}',
        expr: '-1/sqrt(1 - x^4)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(x^2)\' = 2x$ was dropped.',
      },
      {
        latex: '-\\frac{2x}{1+x^4}',
        expr: '-2*x/(1 + x^4)',
        mistake: 'inverse-trig-confused',
        why: 'A denominator $1 + u^2$ belongs to the inverse tangent family; $\\cos^{-1}u$ has $-\\frac{1}{\\sqrt{1-u^2}}$.',
      },
      {
        latex: '-\\frac{2x}{\\sqrt{1-x^2}}',
        expr: '-2*x/sqrt(1 - x^2)',
        mistake: 'chain-rule-outer-wrong',
        why: 'The outer derivative must be evaluated at the inner function: $1 - (x^2)^2 = 1 - x^4$, not $1 - x^2$.',
      },
      {
        latex: '2x\\sec(x^2)\\tan(x^2)',
        expr: '2*x*sec(x^2)*tan(x^2)',
        mistake: 'inverse-trig-as-reciprocal',
        why: '$\\cos^{-1}(x^2)$ was read as $\\frac{1}{\\cos(x^2)} = \\sec(x^2)$; the $-1$ means the inverse function arccos.',
      },
      { latex: '-\\frac{2x}{\\sqrt{1-x^4}}', expr: '-2*x/sqrt(1 - x^4)' },
    ],
    correct: 5,
    explanation: '$\\frac{d}{dx}\\cos^{-1}u = -\\frac{u\'}{\\sqrt{1-u^2}}$ with $u = x^2$: $-\\frac{2x}{\\sqrt{1-x^4}}$.',
    domain: [0.1, 0.9],
    check: { kind: 'derivative', of: 'acos(x^2)' },
    difficulty: 2,
  },
  {
    id: 'dr-f-009',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\sec^{-1}(\\sqrt{x}-1)' },
    options: [
      {
        latex: '\\frac{1}{|\\sqrt{x}-1|\\sqrt{(\\sqrt{x}-1)^2-1}}',
        expr: '1/(abs(sqrt(x) - 1)*sqrt((sqrt(x) - 1)^2 - 1))',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(\\sqrt{x} - 1)\' = \\frac{1}{2\\sqrt{x}}$ was dropped.',
      },
      {
        latex: '\\frac{1}{2\\sqrt{x}\\,|\\sqrt{x}-1|\\sqrt{(\\sqrt{x}-1)^2-1}}',
        expr: '1/(2*sqrt(x)*abs(sqrt(x) - 1)*sqrt((sqrt(x) - 1)^2 - 1))',
      },
      {
        latex: '-\\frac{1}{2\\sqrt{x}\\,|\\sqrt{x}-1|\\sqrt{(\\sqrt{x}-1)^2-1}}',
        expr: '-1/(2*sqrt(x)*abs(sqrt(x) - 1)*sqrt((sqrt(x) - 1)^2 - 1))',
        mistake: 'sign-error-derivative',
        why: '$\\sec^{-1}u$ has the positive derivative $\\frac{1}{|u|\\sqrt{u^2-1}}$; the minus sign belongs to $\\csc^{-1}u$.',
      },
      {
        latex: '\\frac{1}{2\\sqrt{x}\\,(1+(\\sqrt{x}-1)^2)}',
        expr: '1/(2*sqrt(x)*(1 + (sqrt(x) - 1)^2))',
        mistake: 'inverse-trig-confused',
        why: '$\\frac{1}{1+u^2}$ is the derivative of $\\tan^{-1}u$, not of $\\sec^{-1}u$.',
      },
      {
        latex: '\\frac{1}{2\\sqrt{x}\\,|x|\\sqrt{x^2-1}}',
        expr: '1/(2*sqrt(x)*abs(x)*sqrt(x^2 - 1))',
        mistake: 'chain-rule-outer-wrong',
        why: 'The outer derivative was evaluated at $x$ instead of at the inner function $u = \\sqrt{x} - 1$.',
      },
      {
        latex: '-\\frac{\\sin(\\sqrt{x}-1)}{2\\sqrt{x}}',
        expr: '-sin(sqrt(x) - 1)/(2*sqrt(x))',
        mistake: 'inverse-trig-as-reciprocal',
        why: '$\\sec^{-1}$ was read as $\\frac{1}{\\sec} = \\cos$ and $\\cos(\\sqrt{x}-1)$ was differentiated; $\\sec^{-1}$ is the inverse secant.',
      },
    ],
    correct: 1,
    explanation: '$\\frac{d}{dx}\\sec^{-1}u = \\frac{u\'}{|u|\\sqrt{u^2-1}}$ with $u = \\sqrt{x} - 1$ and $u\' = \\frac{1}{2\\sqrt{x}}$ (defined where $|u| > 1$, i.e. $x > 4$).',
    domain: [5, 12],
    check: { kind: 'derivative', of: 'asec(sqrt(x) - 1)' },
    difficulty: 2,
  },
  {
    id: 'dr-f-010',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '(\\arcsin x)^2' },
    options: [
      {
        latex: '2\\arcsin x',
        expr: '2*asin(x)',
        mistake: 'chain-rule-missing',
        why: 'The power rule was applied but the inner derivative $(\\arcsin x)\' = \\frac{1}{\\sqrt{1-x^2}}$ was dropped.',
      },
      {
        latex: '\\frac{2}{\\sqrt{1-x^2}}',
        expr: '2/sqrt(1 - x^2)',
        mistake: 'chain-rule-outer-wrong',
        why: 'The outer derivative is $2u = 2\\arcsin x$; the factor $\\arcsin x$ was lost and only the 2 kept.',
      },
      { latex: '\\frac{2\\arcsin x}{\\sqrt{1-x^2}}', expr: '2*asin(x)/sqrt(1 - x^2)' },
      {
        latex: '\\frac{1}{1-x^2}',
        expr: '1/(1 - x^2)',
        mistake: 'chain-rule-outer-wrong',
        why: 'The inner derivative was squared; the chain rule gives $(u^2)\' = 2u\\cdot u\'$, not $(u\')^2$.',
      },
      {
        latex: '-\\frac{2\\arcsin x}{\\sqrt{1-x^2}}',
        expr: '-2*asin(x)/sqrt(1 - x^2)',
        mistake: 'sign-error-derivative',
        why: '$\\arcsin x$ has a positive derivative; $-\\frac{1}{\\sqrt{1-x^2}}$ belongs to $\\arccos x$.',
      },
      {
        latex: '\\frac{2\\arcsin x}{1+x^2}',
        expr: '2*asin(x)/(1 + x^2)',
        mistake: 'inverse-trig-confused',
        why: '$\\frac{1}{1+x^2}$ is the derivative of $\\arctan x$, not of $\\arcsin x$.',
      },
    ],
    correct: 2,
    explanation: 'Chain rule with outer $u^2$: $2\\arcsin x\\cdot\\frac{1}{\\sqrt{1-x^2}}$.',
    domain: [0.1, 0.9],
    check: { kind: 'derivative', of: 'asin(x)^2' },
    difficulty: 2,
  },
  {
    id: 'dr-f-011',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\sin^{-1}(5x)' },
    options: [
      {
        latex: '\\frac{1}{\\sqrt{1-25x^2}}',
        expr: '1/sqrt(1 - 25*x^2)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(5x)\' = 5$ was dropped.',
      },
      {
        latex: '\\frac{5}{\\sqrt{1-5x^2}}',
        expr: '5/sqrt(1 - 5*x^2)',
        mistake: 'algebra-error',
        why: '$(5x)^2$ was written as $5x^2$; squaring gives $25x^2$.',
      },
      {
        latex: '\\frac{5}{1+25x^2}',
        expr: '5/(1 + 25*x^2)',
        mistake: 'inverse-trig-confused',
        why: '$\\frac{1}{1+u^2}$ is the derivative of $\\tan^{-1}u$; $\\sin^{-1}u$ has $\\frac{1}{\\sqrt{1-u^2}}$.',
      },
      {
        latex: '-\\frac{5}{\\sqrt{1-25x^2}}',
        expr: '-5/sqrt(1 - 25*x^2)',
        mistake: 'sign-error-derivative',
        why: '$\\sin^{-1}$ has a positive derivative; the minus sign belongs to $\\cos^{-1}$.',
      },
      {
        latex: '-5\\csc(5x)\\cot(5x)',
        expr: '-5*csc(5*x)*cot(5*x)',
        mistake: 'inverse-trig-as-reciprocal',
        why: '$\\sin^{-1}(5x)$ was read as $\\frac{1}{\\sin(5x)} = \\csc(5x)$; the $-1$ denotes the inverse sine.',
      },
      { latex: '\\frac{5}{\\sqrt{1-25x^2}}', expr: '5/sqrt(1 - 25*x^2)' },
    ],
    correct: 5,
    explanation: '$\\frac{d}{dx}\\sin^{-1}u = \\frac{u\'}{\\sqrt{1-u^2}}$ with $u = 5x$: $\\frac{5}{\\sqrt{1-25x^2}}$.',
    domain: [0.02, 0.18],
    check: { kind: 'derivative', of: 'asin(5*x)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-012',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\ln 7 + e^{2}' },
    options: [
      {
        latex: '\\ln 7 + e^{2}',
        expr: 'log(7) + e^2',
        mistake: 'constant-derivative',
        why: '$\\ln 7 + e^2$ is a number; constants do not survive differentiation.',
      },
      {
        latex: '\\frac{1}{7} + 2e',
        expr: '1/7 + 2*e',
        mistake: 'constant-derivative',
        why: '$\\ln 7$ and $e^2$ are numbers, not functions of $x$; differentiating them as $\\frac17$ and $2e$ treats them as variables.',
      },
      { latex: '0', expr: '0' },
      {
        latex: '1',
        expr: '1',
        mistake: 'constant-derivative',
        why: 'The derivative of a constant is $0$, not $1$ ($1$ is the derivative of $x$).',
      },
      {
        latex: '(\\ln 7 + e^{2})x',
        expr: '(log(7) + e^2)*x',
        mistake: 'integrated-instead',
        why: 'Multiplying the constant by $x$ gives its antiderivative, not its derivative.',
      },
    ],
    correct: 2,
    explanation: '$\\ln 7$ and $e^2$ are constants, and the derivative of any constant is $0$ (just like $\\frac{d}{dx}(2) = 0$).',
    check: { kind: 'derivative', of: 'log(7) + e^2' },
    difficulty: 1,
  },
  {
    id: 'dr-f-013',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '3x^4 - 2x^2 + 7' },
    options: [
      {
        latex: '12x^3 - 4x + 7',
        expr: '12*x^3 - 4*x + 7',
        mistake: 'constant-derivative',
        why: 'The constant $7$ has derivative $0$; it must disappear.',
      },
      {
        latex: '12x^4 - 4x^2',
        expr: '12*x^4 - 4*x^2',
        mistake: 'power-rule-exponent',
        why: 'The exponents were brought down as factors but not lowered by 1.',
      },
      {
        latex: '3x^3 - 2x',
        expr: '3*x^3 - 2*x',
        mistake: 'power-rule-coefficient',
        why: 'The exponents were lowered but never multiplied in: $3\\cdot 4 = 12$ and $2\\cdot 2 = 4$ are missing.',
      },
      { latex: '12x^3 - 4x', expr: '12*x^3 - 4*x' },
      {
        latex: '\\frac{3}{5}x^5 - \\frac{2}{3}x^3 + 7x',
        expr: '3/5*x^5 - 2/3*x^3 + 7*x',
        mistake: 'integrated-instead',
        why: 'Raising every exponent by 1 and dividing produces an antiderivative, not the derivative.',
      },
      {
        latex: '12x^3 - 4x + 1',
        expr: '12*x^3 - 4*x + 1',
        mistake: 'constant-derivative',
        why: 'The derivative of the constant $7$ is $0$, not $1$.',
      },
    ],
    correct: 3,
    explanation: 'Term by term with the power rule: $12x^3 - 4x + 0$.',
    check: { kind: 'derivative', of: '3*x^4 - 2*x^2 + 7' },
    difficulty: 1,
  },
  {
    id: 'dr-f-014',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\frac{4}{\\sqrt{x}}' },
    options: [
      {
        latex: '\\frac{2}{x\\sqrt{x}}',
        expr: '2/(x*sqrt(x))',
        mistake: 'negative-exponent-sign',
        why: '$\\frac{4}{\\sqrt{x}} = 4x^{-1/2}$; bringing down $-\\frac12$ makes the derivative negative.',
      },
      {
        latex: '-\\frac{2}{\\sqrt{x}}',
        expr: '-2/sqrt(x)',
        mistake: 'power-rule-exponent',
        why: 'The $-\\frac12$ was brought down but the exponent stayed $-\\frac12$; it must become $-\\frac32$.',
      },
      {
        latex: '\\frac{2}{\\sqrt{x}}',
        expr: '2/sqrt(x)',
        mistake: 'negative-exponent-sign',
        why: 'The function was treated as $4x^{1/2}$; a root in the denominator means the exponent is $-\\frac12$.',
      },
      {
        latex: '8\\sqrt{x}',
        expr: '8*sqrt(x)',
        mistake: 'integrated-instead',
        why: '$8\\sqrt{x}$ is the antiderivative of $\\frac{4}{\\sqrt{x}}$, not its derivative.',
      },
      {
        latex: '-\\frac{6}{x\\sqrt{x}}',
        expr: '-6/(x*sqrt(x))',
        mistake: 'power-rule-coefficient',
        why: 'The new exponent $-\\frac32$ was used as the factor ($4\\cdot(-\\frac32) = -6$); the power rule uses the old exponent $-\\frac12$.',
      },
      { latex: '-\\frac{2}{x\\sqrt{x}}', expr: '-2/(x*sqrt(x))' },
    ],
    correct: 5,
    explanation: '$\\frac{4}{\\sqrt{x}} = 4x^{-1/2}$, so $f\'(x) = 4\\cdot(-\\frac12)x^{-3/2} = -\\frac{2}{x\\sqrt{x}}$.',
    check: { kind: 'derivative', of: '4/sqrt(x)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-015',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\frac{\\ln x}{x}' },
    options: [
      {
        latex: '\\frac{\\ln x - 1}{x^2}',
        expr: '(log(x) - 1)/x^2',
        mistake: 'quotient-rule-order',
        why: 'The numerator was written $fg\' - f\'g$; the quotient rule is $\\frac{f\'g - fg\'}{g^2}$.',
      },
      { latex: '\\frac{1 - \\ln x}{x^2}', expr: '(1 - log(x))/x^2' },
      {
        latex: '\\frac{1 + \\ln x}{x^2}',
        expr: '(1 + log(x))/x^2',
        mistake: 'quotient-rule-plus',
        why: 'The quotient rule subtracts: $f\'g - fg\'$, not $f\'g + fg\'$.',
      },
      {
        latex: '\\frac{1 - \\ln x}{x}',
        expr: '(1 - log(x))/x',
        mistake: 'quotient-rule-denominator',
        why: 'The denominator must be $g^2 = x^2$, not $x$.',
      },
      {
        latex: '\\frac{x - \\ln x}{x^2}',
        expr: '(x - log(x))/x^2',
        mistake: 'log-derivative-wrong',
        why: '$(\\ln x)\'$ was taken as 1; with $(\\ln x)\' = \\frac1x$ the first term is $\\frac1x\\cdot x = 1$.',
      },
      {
        latex: '\\frac{(\\ln x)^2}{2}',
        expr: 'log(x)^2/2',
        mistake: 'integrated-instead',
        why: '$\\frac{(\\ln x)^2}{2}$ is the antiderivative of $\\frac{\\ln x}{x}$ (with $u = \\ln x$), not its derivative.',
      },
    ],
    correct: 1,
    explanation: 'Quotient rule: $\\frac{\\frac1x\\cdot x - \\ln x\\cdot 1}{x^2} = \\frac{1-\\ln x}{x^2}$.',
    check: { kind: 'derivative', of: 'log(x)/x' },
    difficulty: 1,
  },
  {
    id: 'dr-f-016',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\frac{e^x}{x^2}' },
    options: [
      {
        latex: '\\frac{e^x(2-x)}{x^3}',
        expr: 'exp(x)*(2 - x)/x^3',
        mistake: 'quotient-rule-order',
        why: 'The numerator was taken as $fg\' - f\'g$; the correct order is $f\'g - fg\'$ (derivative of the top first).',
      },
      {
        latex: '\\frac{e^x(x+2)}{x^3}',
        expr: 'exp(x)*(x + 2)/x^3',
        mistake: 'quotient-rule-plus',
        why: 'The two numerator terms were added; the quotient rule subtracts $fg\'$.',
      },
      {
        latex: '\\frac{e^x(x-2)}{x}',
        expr: 'exp(x)*(x - 2)/x',
        mistake: 'quotient-rule-denominator',
        why: 'The denominator was left as $x^2$ instead of $(x^2)^2 = x^4$, so only one factor of $x$ cancelled.',
      },
      {
        latex: '\\frac{e^x(x-1)}{x^3}',
        expr: 'exp(x)*(x - 1)/x^3',
        mistake: 'power-rule-coefficient',
        why: '$(x^2)\'$ was taken as $x$ instead of $2x$.',
      },
      { latex: '\\frac{e^x(x-2)}{x^3}', expr: 'exp(x)*(x - 2)/x^3' },
      {
        latex: '-\\frac{2e^x}{x^3}',
        expr: '-2*exp(x)/x^3',
        mistake: 'product-rule-missing-term',
        why: 'Writing $e^x\\cdot x^{-2}$, only $x^{-2}$ was differentiated; the term $(e^x)\'\\cdot x^{-2}$ is missing.',
      },
    ],
    correct: 4,
    explanation: 'Quotient rule: $\\frac{e^x x^2 - e^x\\cdot 2x}{x^4} = \\frac{e^x(x-2)}{x^3}$.',
    check: { kind: 'derivative', of: 'exp(x)/x^2' },
    difficulty: 2,
  },
  {
    id: 'dr-f-017',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\frac{x}{x^2+1}' },
    options: [
      {
        latex: '\\frac{x^2-1}{(x^2+1)^2}',
        expr: '(x^2 - 1)/(x^2 + 1)^2',
        mistake: 'quotient-rule-order',
        why: 'The numerator was computed as $fg\' - f\'g = 2x^2 - (x^2+1)$; the order is $f\'g - fg\'$.',
      },
      {
        latex: '\\frac{3x^2+1}{(x^2+1)^2}',
        expr: '(3*x^2 + 1)/(x^2 + 1)^2',
        mistake: 'quotient-rule-plus',
        why: 'The terms were added, $(x^2+1) + 2x^2$; the quotient rule subtracts.',
      },
      {
        latex: '\\frac{1-x^2}{x^2+1}',
        expr: '(1 - x^2)/(x^2 + 1)',
        mistake: 'quotient-rule-denominator',
        why: 'The denominator must be squared: $(x^2+1)^2$.',
      },
      {
        latex: '\\frac{1}{(x^2+1)^2}',
        expr: '1/(x^2 + 1)^2',
        mistake: 'power-rule-coefficient',
        why: '$(x^2+1)\'$ was taken as $x$, so $x\\cdot x$ cancelled the $x^2$; it is $2x$.',
      },
      {
        latex: '\\frac{1}{2}\\ln(x^2+1)',
        expr: 'log(x^2 + 1)/2',
        mistake: 'integrated-instead',
        why: '$\\frac12\\ln(x^2+1)$ is the antiderivative of $\\frac{x}{x^2+1}$, not its derivative.',
      },
      { latex: '\\frac{1-x^2}{(x^2+1)^2}', expr: '(1 - x^2)/(x^2 + 1)^2' },
    ],
    correct: 5,
    explanation: 'Quotient rule: $\\frac{1\\cdot(x^2+1) - x\\cdot 2x}{(x^2+1)^2} = \\frac{1-x^2}{(x^2+1)^2}$.',
    check: { kind: 'derivative', of: 'x/(x^2 + 1)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-018',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'x^2e^{-x}' },
    options: [
      {
        latex: '2xe^{-x} + x^2e^{-x}',
        expr: '2*x*exp(-x) + x^2*exp(-x)',
        mistake: 'chain-rule-missing',
        why: '$(e^{-x})\'$ was taken as $e^{-x}$; the inner derivative $-1$ makes it $-e^{-x}$.',
      },
      {
        latex: '-2xe^{-x}',
        expr: '-2*x*exp(-x)',
        mistake: 'product-rule-missing-term',
        why: 'The two derivatives were multiplied, $(2x)(-e^{-x})$; the product rule is $f\'g + fg\'$.',
      },
      { latex: '2xe^{-x} - x^2e^{-x}', expr: '2*x*exp(-x) - x^2*exp(-x)' },
      {
        latex: '2xe^{-x}',
        expr: '2*x*exp(-x)',
        mistake: 'product-rule-missing-term',
        why: 'Only $x^2$ was differentiated; the term $x^2\\cdot(e^{-x})\' = -x^2e^{-x}$ is missing.',
      },
      {
        latex: '2xe^{-x} - x^3e^{-x-1}',
        expr: '2*x*exp(-x) - x^3*exp(-x - 1)',
        mistake: 'exponential-as-power',
        why: '$e^{-x}$ was differentiated like a power ($-x\\,e^{-x-1}$); $e^u$ differentiates to $e^u\\cdot u\'$.',
      },
      {
        latex: '-x^2e^{-x}',
        expr: '-x^2*exp(-x)',
        mistake: 'product-rule-missing-term',
        why: 'Only $e^{-x}$ was differentiated; the term $(x^2)\'e^{-x} = 2xe^{-x}$ is missing.',
      },
    ],
    correct: 2,
    explanation: 'Product rule with $(e^{-x})\' = -e^{-x}$: $2xe^{-x} + x^2(-e^{-x})$.',
    check: { kind: 'derivative', of: 'x^2*exp(-x)' },
    difficulty: 2,
  },
  {
    id: 'dr-f-019',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'x^2\\ln x' },
    options: [
      { latex: '2x\\ln x + x', expr: '2*x*log(x) + x' },
      {
        latex: '2x\\ln x',
        expr: '2*x*log(x)',
        mistake: 'product-rule-missing-term',
        why: '$\\ln x$ was treated as a constant; the term $x^2\\cdot(\\ln x)\' = x$ is missing.',
      },
      {
        latex: '2x\\ln x + x^2',
        expr: '2*x*log(x) + x^2',
        mistake: 'log-derivative-wrong',
        why: '$(\\ln x)\'$ was taken as 1; it is $\\frac1x$, so $x^2\\cdot\\frac1x = x$.',
      },
      {
        latex: 'x\\ln x + x',
        expr: 'x*log(x) + x',
        mistake: 'power-rule-coefficient',
        why: '$(x^2)\'$ was taken as $x$ instead of $2x$.',
      },
      {
        latex: '2x\\ln x + 1',
        expr: '2*x*log(x) + 1',
        mistake: 'algebra-error',
        why: '$x^2\\cdot\\frac1x$ simplifies to $x$, not $1$.',
      },
      {
        latex: '2x + \\frac{1}{x}',
        expr: '2*x + 1/x',
        mistake: 'product-rule-missing-term',
        why: 'Each factor was differentiated and the results added; the product rule keeps the other factor in each term.',
      },
    ],
    correct: 0,
    explanation: 'Product rule: $2x\\ln x + x^2\\cdot\\frac1x = 2x\\ln x + x$.',
    check: { kind: 'derivative', of: 'x^2*log(x)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-020',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'x\\tan^{-1}x' },
    options: [
      {
        latex: '\\frac{x}{1+x^2}',
        expr: 'x/(1 + x^2)',
        mistake: 'product-rule-missing-term',
        why: 'Only $\\tan^{-1}x$ was differentiated; the term $(x)\'\\tan^{-1}x = \\tan^{-1}x$ is missing.',
      },
      {
        latex: '\\tan^{-1}x + \\frac{x}{\\sqrt{1-x^2}}',
        expr: 'atan(x) + x/sqrt(1 - x^2)',
        mistake: 'inverse-trig-confused',
        why: '$\\frac{1}{\\sqrt{1-x^2}}$ is the derivative of $\\sin^{-1}x$; $\\tan^{-1}x$ has $\\frac{1}{1+x^2}$.',
      },
      {
        latex: '\\cot x - x\\csc^2 x',
        expr: 'cot(x) - x*csc(x)^2',
        mistake: 'inverse-trig-as-reciprocal',
        why: '$\\tan^{-1}x$ was read as $\\frac{1}{\\tan x} = \\cot x$; the $-1$ denotes the inverse tangent.',
      },
      { latex: '\\tan^{-1}x + \\frac{x}{1+x^2}', expr: 'atan(x) + x/(1 + x^2)' },
      {
        latex: '\\tan^{-1}x - \\frac{x}{1+x^2}',
        expr: 'atan(x) - x/(1 + x^2)',
        mistake: 'sign-error-derivative',
        why: '$(\\tan^{-1}x)\' = +\\frac{1}{1+x^2}$; the negative version is the derivative of $\\cot^{-1}x$.',
      },
      {
        latex: '\\frac{1}{1+x^2}',
        expr: '1/(1 + x^2)',
        mistake: 'product-rule-missing-term',
        why: 'The derivatives of the two factors were multiplied, $1\\cdot\\frac{1}{1+x^2}$; the product rule is $f\'g + fg\'$.',
      },
    ],
    correct: 3,
    explanation: 'Product rule: $1\\cdot\\tan^{-1}x + x\\cdot\\frac{1}{1+x^2}$.',
    domain: [0.1, 0.9],
    check: { kind: 'derivative', of: 'x*atan(x)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-021',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\ln(x^2+1)' },
    options: [
      {
        latex: '\\frac{1}{x^2+1}',
        expr: '1/(x^2 + 1)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(x^2+1)\' = 2x$ was dropped.',
      },
      {
        latex: '\\frac{1}{2x}',
        expr: '1/(2*x)',
        mistake: 'log-derivative-wrong',
        why: '$\\frac{d}{dx}\\ln u = \\frac{u\'}{u}$; this is $\\frac{1}{u\'}$ instead.',
      },
      {
        latex: '2x\\ln(x^2+1)',
        expr: '2*x*log(x^2 + 1)',
        mistake: 'log-derivative-wrong',
        why: '$\\ln u$ was treated as its own derivative; $\\frac{d}{du}\\ln u = \\frac1u$.',
      },
      {
        latex: '\\frac{x}{x^2+1}',
        expr: 'x/(x^2 + 1)',
        mistake: 'power-rule-coefficient',
        why: '$(x^2)\'$ was taken as $x$ instead of $2x$.',
      },
      { latex: '\\frac{2x}{x^2+1}', expr: '2*x/(x^2 + 1)' },
      {
        latex: '\\frac{2x}{(x^2+1)^2}',
        expr: '2*x/(x^2 + 1)^2',
        mistake: 'log-derivative-wrong',
        why: '$\\frac{d}{du}\\ln u = \\frac1u$, not $\\frac{1}{u^2}$.',
      },
    ],
    correct: 4,
    explanation: '$\\frac{d}{dx}\\ln u = \\frac{u\'}{u}$ with $u = x^2+1$: $\\frac{2x}{x^2+1}$.',
    check: { kind: 'derivative', of: 'log(x^2 + 1)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-022',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\ln(\\sin x)' },
    options: [
      {
        latex: '-\\cot x',
        expr: '-cot(x)',
        mistake: 'sign-error-derivative',
        why: '$(\\sin x)\' = +\\cos x$, so $\\frac{u\'}{u} = \\frac{\\cos x}{\\sin x}$ is positive.',
      },
      {
        latex: '\\csc x',
        expr: 'csc(x)',
        mistake: 'chain-rule-missing',
        why: 'Only $\\frac{1}{\\sin x}$ was written; the inner derivative $\\cos x$ was dropped.',
      },
      { latex: '\\cot x', expr: 'cot(x)' },
      {
        latex: '\\tan x',
        expr: 'tan(x)',
        mistake: 'log-derivative-wrong',
        why: 'The fraction was flipped: $\\frac{u\'}{u} = \\frac{\\cos x}{\\sin x}$, not $\\frac{\\sin x}{\\cos x}$.',
      },
      {
        latex: '\\sec x',
        expr: 'sec(x)',
        mistake: 'log-derivative-wrong',
        why: 'This is $\\frac{1}{u\'} = \\frac{1}{\\cos x}$; the derivative of $\\ln u$ is $\\frac{u\'}{u}$.',
      },
      {
        latex: '\\cos x',
        expr: 'cos(x)',
        mistake: 'chain-rule-outer-wrong',
        why: 'Only the inner derivative $\\cos x$ was kept; the outer factor $\\frac{1}{\\sin x}$ is missing.',
      },
    ],
    correct: 2,
    explanation: '$\\frac{d}{dx}\\ln u = \\frac{u\'}{u} = \\frac{\\cos x}{\\sin x} = \\cot x$.',
    check: { kind: 'derivative', of: 'log(sin(x))' },
    difficulty: 1,
  },
  {
    id: 'dr-f-023',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\ln(7x)' },
    options: [
      {
        latex: '\\frac{1}{7x}',
        expr: '1/(7*x)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $7$ was dropped; $\\frac{1}{7x}\\cdot 7 = \\frac1x$.',
      },
      {
        latex: '\\frac{7}{x}',
        expr: '7/x',
        mistake: 'algebra-error',
        why: '$\\ln(7x) = \\ln 7 + \\ln x$, not $7\\ln x$.',
      },
      {
        latex: '\\frac{1}{7} + \\frac{1}{x}',
        expr: '1/7 + 1/x',
        mistake: 'constant-derivative',
        why: '$\\ln(7x) = \\ln 7 + \\ln x$, and $\\ln 7$ is a constant: its derivative is $0$, not $\\frac17$.',
      },
      {
        latex: '\\frac{7}{(7x)^2}',
        expr: '7/(7*x)^2',
        mistake: 'log-derivative-wrong',
        why: '$\\frac{d}{du}\\ln u = \\frac1u$, not $\\frac{1}{u^2}$.',
      },
      {
        latex: 'x\\ln(7x) - x',
        expr: 'x*log(7*x) - x',
        mistake: 'integrated-instead',
        why: '$x\\ln(7x) - x$ is an antiderivative of $\\ln(7x)$, not its derivative.',
      },
      { latex: '\\frac{1}{x}', expr: '1/x' },
    ],
    correct: 5,
    explanation: 'Chain rule: $\\frac{1}{7x}\\cdot 7 = \\frac1x$ (same as for $\\ln x$, since $\\ln(7x) = \\ln 7 + \\ln x$).',
    check: { kind: 'derivative', of: 'log(7*x)' },
    difficulty: 2,
  },
  {
    id: 'dr-f-024',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\sec(x^2)' },
    options: [
      {
        latex: '\\sec(x^2)\\tan(x^2)',
        expr: 'sec(x^2)*tan(x^2)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(x^2)\' = 2x$ was dropped.',
      },
      {
        latex: '2x\\sec^2(x^2)',
        expr: '2*x*sec(x^2)^2',
        mistake: 'trig-derivative-swapped',
        why: '$\\sec^2 u$ is the derivative of $\\tan u$; $(\\sec u)\' = \\sec u\\tan u$.',
      },
      {
        latex: '-2x\\sec(x^2)\\tan(x^2)',
        expr: '-2*x*sec(x^2)*tan(x^2)',
        mistake: 'sign-error-derivative',
        why: '$(\\sec u)\' = +\\sec u\\tan u$; the minus sign belongs to $(\\csc u)\' = -\\csc u\\cot u$.',
      },
      { latex: '2x\\sec(x^2)\\tan(x^2)', expr: '2*x*sec(x^2)*tan(x^2)' },
      {
        latex: '2x\\sec(2x)\\tan(2x)',
        expr: '2*x*sec(2*x)*tan(2*x)',
        mistake: 'chain-rule-outer-wrong',
        why: 'The outer derivative must be evaluated at the inner function $x^2$, not at its derivative $2x$.',
      },
      {
        latex: 'x^2\\sec(x^2)\\tan(x^2)',
        expr: 'x^2*sec(x^2)*tan(x^2)',
        mistake: 'chain-rule-missing',
        why: 'The factor must be the derivative of the inner function, $2x$, not the inner function $x^2$ itself.',
      },
    ],
    correct: 3,
    explanation: '$(\\sec u)\' = \\sec u\\tan u\\cdot u\'$ with $u = x^2$, $u\' = 2x$.',
    domain: [0.2, 1.1],
    check: { kind: 'derivative', of: 'sec(x^2)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-025',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\cot(\\sqrt{x})' },
    options: [
      {
        latex: '\\frac{\\csc^2(\\sqrt{x})}{2\\sqrt{x}}',
        expr: 'csc(sqrt(x))^2/(2*sqrt(x))',
        mistake: 'sign-error-derivative',
        why: '$(\\cot u)\' = -\\csc^2 u$; the minus sign was dropped.',
      },
      {
        latex: '-\\csc^2(\\sqrt{x})',
        expr: '-csc(sqrt(x))^2',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(\\sqrt{x})\' = \\frac{1}{2\\sqrt{x}}$ was dropped.',
      },
      {
        latex: '-\\frac{\\csc(\\sqrt{x})\\cot(\\sqrt{x})}{2\\sqrt{x}}',
        expr: '-csc(sqrt(x))*cot(sqrt(x))/(2*sqrt(x))',
        mistake: 'trig-derivative-swapped',
        why: '$-\\csc u\\cot u$ is the derivative of $\\csc u$; $(\\cot u)\' = -\\csc^2 u$.',
      },
      {
        latex: '\\frac{\\sec^2(\\sqrt{x})}{2\\sqrt{x}}',
        expr: 'sec(sqrt(x))^2/(2*sqrt(x))',
        mistake: 'trig-derivative-swapped',
        why: '$\\sec^2 u$ is the derivative of $\\tan u$; for $\\cot u$ it is $-\\csc^2 u$.',
      },
      {
        latex: '-\\frac{\\csc^2(\\sqrt{x})}{\\sqrt{x}}',
        expr: '-csc(sqrt(x))^2/sqrt(x)',
        mistake: 'power-rule-coefficient',
        why: '$(\\sqrt{x})\' = \\frac12 x^{-1/2} = \\frac{1}{2\\sqrt{x}}$; the factor $\\frac12$ was dropped.',
      },
      { latex: '-\\frac{\\csc^2(\\sqrt{x})}{2\\sqrt{x}}', expr: '-csc(sqrt(x))^2/(2*sqrt(x))' },
    ],
    correct: 5,
    explanation: '$(\\cot u)\' = -\\csc^2 u\\cdot u\'$ with $u = \\sqrt{x}$, $u\' = \\frac{1}{2\\sqrt{x}}$.',
    check: { kind: 'derivative', of: 'cot(sqrt(x))' },
    difficulty: 2,
  },
  {
    id: 'dr-f-026',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\csc(2x)' },
    options: [
      {
        latex: '2\\csc(2x)\\cot(2x)',
        expr: '2*csc(2*x)*cot(2*x)',
        mistake: 'sign-error-derivative',
        why: '$(\\csc u)\' = -\\csc u\\cot u$; the minus sign was dropped.',
      },
      { latex: '-2\\csc(2x)\\cot(2x)', expr: '-2*csc(2*x)*cot(2*x)' },
      {
        latex: '-\\csc(2x)\\cot(2x)',
        expr: '-csc(2*x)*cot(2*x)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(2x)\' = 2$ was dropped.',
      },
      {
        latex: '-2\\csc^2(2x)',
        expr: '-2*csc(2*x)^2',
        mistake: 'trig-derivative-swapped',
        why: '$-\\csc^2 u$ is the derivative of $\\cot u$; $(\\csc u)\' = -\\csc u\\cot u$.',
      },
      {
        latex: '2\\sec(2x)\\tan(2x)',
        expr: '2*sec(2*x)*tan(2*x)',
        mistake: 'trig-derivative-swapped',
        why: '$\\sec u\\tan u$ is the derivative of $\\sec u$, not of $\\csc u$.',
      },
      {
        latex: '-\\frac{1}{2}\\csc(2x)\\cot(2x)',
        expr: '-csc(2*x)*cot(2*x)/2',
        mistake: 'coefficient-mishandled',
        why: 'The chain rule multiplies by the inner derivative 2; it does not divide by it.',
      },
    ],
    correct: 1,
    explanation: '$(\\csc u)\' = -\\csc u\\cot u\\cdot u\'$ with $u = 2x$, $u\' = 2$.',
    domain: [0.1, 0.7],
    check: { kind: 'derivative', of: 'csc(2*x)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-027',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'e^{\\sin x}' },
    options: [
      {
        latex: 'e^{\\sin x}',
        expr: 'exp(sin(x))',
        mistake: 'chain-rule-missing',
        why: '$e^u$ was left as $e^u$; the chain rule multiplies by $u\' = \\cos x$.',
      },
      {
        latex: 'e^{\\cos x}',
        expr: 'exp(cos(x))',
        mistake: 'chain-rule-outer-wrong',
        why: 'The exponent was differentiated in place; the outer $e^{\\sin x}$ stays and is multiplied by $\\cos x$.',
      },
      {
        latex: 'e^{\\sin x - 1}\\sin x',
        expr: 'exp(sin(x) - 1)*sin(x)',
        mistake: 'exponential-as-power',
        why: 'The power rule was applied to $e^{\\sin x}$; $e^u$ differentiates to $e^u\\cdot u\'$.',
      },
      { latex: 'e^{\\sin x}\\cos x', expr: 'exp(sin(x))*cos(x)' },
      {
        latex: '-e^{\\sin x}\\cos x',
        expr: '-exp(sin(x))*cos(x)',
        mistake: 'trig-derivative-swapped',
        why: '$(\\sin x)\' = +\\cos x$; a minus sign appears only in $(\\cos x)\' = -\\sin x$.',
      },
    ],
    correct: 3,
    explanation: 'Chain rule: $e^{\\sin x}\\cdot(\\sin x)\' = e^{\\sin x}\\cos x$.',
    check: { kind: 'derivative', of: 'exp(sin(x))' },
    difficulty: 1,
  },
  {
    id: 'dr-f-028',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\sin^3 x' },
    options: [
      {
        latex: '3\\sin^2 x',
        expr: '3*sin(x)^2',
        mistake: 'chain-rule-missing',
        why: 'The power rule was applied to $(\\sin x)^3$ but the inner derivative $\\cos x$ was dropped.',
      },
      {
        latex: '3\\cos^2 x',
        expr: '3*cos(x)^2',
        mistake: 'chain-rule-outer-wrong',
        why: 'Sine was replaced by its derivative inside the power; the power rule keeps $\\sin x$: $3(\\sin x)^2\\cdot\\cos x$.',
      },
      {
        latex: '\\cos^3 x',
        expr: 'cos(x)^3',
        mistake: 'chain-rule-outer-wrong',
        why: 'Only the inside was differentiated; the outer cube was never differentiated with the power rule.',
      },
      {
        latex: '-3\\sin^2 x\\cos x',
        expr: '-3*sin(x)^2*cos(x)',
        mistake: 'trig-derivative-swapped',
        why: '$(\\sin x)\' = +\\cos x$; the minus sign belongs to $(\\cos x)\' = -\\sin x$.',
      },
      {
        latex: '3\\sin^3 x\\cos x',
        expr: '3*sin(x)^3*cos(x)',
        mistake: 'power-rule-exponent',
        why: 'The power was not lowered: it is $3(\\sin x)^2\\cos x$, not $3(\\sin x)^3\\cos x$.',
      },
      { latex: '3\\sin^2 x\\cos x', expr: '3*sin(x)^2*cos(x)' },
    ],
    correct: 5,
    explanation: '$\\sin^3 x = (\\sin x)^3$; the chain rule gives $3(\\sin x)^2\\cdot\\cos x$.',
    check: { kind: 'derivative', of: 'sin(x)^3' },
    difficulty: 1,
  },
  {
    id: 'dr-f-029',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\sqrt{x^2+9}' },
    options: [
      { latex: '\\frac{x}{\\sqrt{x^2+9}}', expr: 'x/sqrt(x^2 + 9)' },
      {
        latex: '\\frac{1}{2\\sqrt{x^2+9}}',
        expr: '1/(2*sqrt(x^2 + 9))',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(x^2+9)\' = 2x$ was dropped.',
      },
      {
        latex: '\\frac{2x}{\\sqrt{x^2+9}}',
        expr: '2*x/sqrt(x^2 + 9)',
        mistake: 'power-rule-coefficient',
        why: 'The factor $\\frac12$ from the exponent $\\frac12$ was dropped: $\\frac12\\cdot 2x = x$.',
      },
      {
        latex: 'x\\sqrt{x^2+9}',
        expr: 'x*sqrt(x^2 + 9)',
        mistake: 'power-rule-exponent',
        why: 'The exponent stayed $+\\frac12$; it drops to $-\\frac12$, which puts the root in the denominator.',
      },
      {
        latex: '\\frac{x}{(x^2+9)^{3/2}}',
        expr: 'x/(x^2 + 9)^(3/2)',
        mistake: 'power-rule-exponent',
        why: '$\\frac12 - 1$ was computed as $-\\frac32$; it is $-\\frac12$.',
      },
    ],
    correct: 0,
    explanation: 'Chain rule: $\\frac{1}{2\\sqrt{x^2+9}}\\cdot 2x = \\frac{x}{\\sqrt{x^2+9}}$.',
    check: { kind: 'derivative', of: 'sqrt(x^2 + 9)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-030',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\arctan(x^3)' },
    options: [
      {
        latex: '\\frac{1}{1+x^6}',
        expr: '1/(1 + x^6)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(x^3)\' = 3x^2$ was dropped.',
      },
      { latex: '\\frac{3x^2}{1+x^6}', expr: '3*x^2/(1 + x^6)' },
      {
        latex: '\\frac{3x^2}{1+x^2}',
        expr: '3*x^2/(1 + x^2)',
        mistake: 'chain-rule-outer-wrong',
        why: 'The outer derivative $\\frac{1}{1+u^2}$ must be evaluated at $u = x^3$, giving $1 + x^6$.',
      },
      {
        latex: '\\frac{3x^2}{1+x^5}',
        expr: '3*x^2/(1 + x^5)',
        mistake: 'algebra-error',
        why: '$(x^3)^2 = x^6$: exponents multiply, they do not add.',
      },
      {
        latex: '\\frac{3x^2}{\\sqrt{1-x^6}}',
        expr: '3*x^2/sqrt(1 - x^6)',
        mistake: 'inverse-trig-confused',
        why: '$\\frac{1}{\\sqrt{1-u^2}}$ is the derivative of $\\arcsin u$; $\\arctan u$ has $\\frac{1}{1+u^2}$.',
      },
      {
        latex: '-\\frac{3x^2}{1+x^6}',
        expr: '-3*x^2/(1 + x^6)',
        mistake: 'sign-error-derivative',
        why: '$\\arctan$ is increasing, so its derivative is positive; the minus belongs to the inverse cotangent.',
      },
    ],
    correct: 1,
    explanation: '$\\frac{d}{dx}\\arctan u = \\frac{u\'}{1+u^2}$ with $u = x^3$: $\\frac{3x^2}{1+x^6}$.',
    domain: [0.2, 0.95],
    check: { kind: 'derivative', of: 'atan(x^3)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-031',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\cos(e^{2x})' },
    options: [
      {
        latex: '-\\sin(e^{2x})',
        expr: '-sin(exp(2*x))',
        mistake: 'chain-rule-missing',
        why: 'No inner derivative was applied; $(e^{2x})\' = 2e^{2x}$ must multiply $-\\sin(e^{2x})$.',
      },
      {
        latex: '-e^{2x}\\sin(e^{2x})',
        expr: '-exp(2*x)*sin(exp(2*x))',
        mistake: 'chain-rule-missing',
        why: 'The innermost derivative $(2x)\' = 2$ was dropped: $(e^{2x})\' = 2e^{2x}$.',
      },
      {
        latex: '2e^{2x}\\sin(e^{2x})',
        expr: '2*exp(2*x)*sin(exp(2*x))',
        mistake: 'sign-error-derivative',
        why: '$(\\cos u)\' = -\\sin u$; the minus sign was lost.',
      },
      {
        latex: '-\\sin(2e^{2x})',
        expr: '-sin(2*exp(2*x))',
        mistake: 'chain-rule-outer-wrong',
        why: 'The inner derivative $2e^{2x}$ was plugged into sine instead of multiplying it.',
      },
      {
        latex: '-\\frac{1}{2}e^{2x}\\sin(e^{2x})',
        expr: '-exp(2*x)*sin(exp(2*x))/2',
        mistake: 'coefficient-mishandled',
        why: 'The chain rule multiplies by $(2x)\' = 2$; dividing by 2 is the antiderivative pattern.',
      },
      { latex: '-2e^{2x}\\sin(e^{2x})', expr: '-2*exp(2*x)*sin(exp(2*x))' },
    ],
    correct: 5,
    explanation: 'Two chain-rule layers: $-\\sin(e^{2x})\\cdot e^{2x}\\cdot 2$.',
    check: { kind: 'derivative', of: 'cos(exp(2*x))' },
    difficulty: 2,
  },
  {
    id: 'dr-f-032',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'e^{-x^2}' },
    options: [
      {
        latex: 'e^{-x^2}',
        expr: 'exp(-x^2)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(-x^2)\' = -2x$ was dropped.',
      },
      {
        latex: '2xe^{-x^2}',
        expr: '2*x*exp(-x^2)',
        mistake: 'sign-error',
        why: 'The inner derivative of $-x^2$ is $-2x$; its minus sign was lost.',
      },
      { latex: '-2xe^{-x^2}', expr: '-2*x*exp(-x^2)' },
      {
        latex: '-x^2e^{-x^2-1}',
        expr: '-x^2*exp(-x^2 - 1)',
        mistake: 'exponential-as-power',
        why: 'The power rule was applied to $e^{-x^2}$; with the variable in the exponent, $e^u$ differentiates to $e^u\\cdot u\'$.',
      },
      {
        latex: '-\\frac{e^{-x^2}}{2x}',
        expr: '-exp(-x^2)/(2*x)',
        mistake: 'integrated-instead',
        why: 'Dividing by the inner derivative is an (invalid) antiderivative move; differentiation multiplies by $-2x$.',
      },
      {
        latex: '-2xe^{-2x}',
        expr: '-2*x*exp(-2*x)',
        mistake: 'chain-rule-outer-wrong',
        why: 'The exponent was replaced by its derivative; the outer $e^{-x^2}$ must stay unchanged.',
      },
    ],
    correct: 2,
    explanation: 'Chain rule: $e^{-x^2}\\cdot(-x^2)\' = -2xe^{-x^2}$.',
    check: { kind: 'derivative', of: 'exp(-x^2)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-033',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\ln(\\ln x)' },
    options: [
      {
        latex: '\\frac{1}{\\ln x}',
        expr: '1/log(x)',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(\\ln x)\' = \\frac1x$ was dropped.',
      },
      {
        latex: '\\frac{1}{x}',
        expr: '1/x',
        mistake: 'chain-rule-outer-wrong',
        why: 'Only the inner derivative $\\frac1x$ was kept; the outer factor $\\frac{1}{\\ln x}$ is missing.',
      },
      {
        latex: '\\frac{\\ln x}{x}',
        expr: 'log(x)/x',
        mistake: 'log-derivative-wrong',
        why: '$u\'$ was multiplied by $u$ instead of divided: $\\frac{d}{dx}\\ln u = \\frac{u\'}{u}$.',
      },
      { latex: '\\frac{1}{x\\ln x}', expr: '1/(x*log(x))' },
      {
        latex: 'x\\ln x',
        expr: 'x*log(x)',
        mistake: 'log-derivative-wrong',
        why: 'The fraction was flipped: $\\frac{u}{u\'}$ instead of $\\frac{u\'}{u}$.',
      },
      {
        latex: '\\frac{1}{x^2\\ln x}',
        expr: '1/(x^2*log(x))',
        mistake: 'chain-rule-doubled',
        why: 'The inner derivative $\\frac1x$ was applied twice.',
      },
    ],
    correct: 3,
    explanation: '$\\frac{d}{dx}\\ln u = \\frac{u\'}{u}$ with $u = \\ln x$: $\\frac{1/x}{\\ln x} = \\frac{1}{x\\ln x}$.',
    domain: [1.5, 4],
    check: { kind: 'derivative', of: 'log(log(x))' },
    difficulty: 2,
  },
  {
    id: 'dr-f-034',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'xe^{x^2}' },
    options: [
      {
        latex: 'e^{x^2} + xe^{x^2}',
        expr: 'exp(x^2) + x*exp(x^2)',
        mistake: 'chain-rule-missing',
        why: '$(e^{x^2})\'$ was taken as $e^{x^2}$; the inner derivative $2x$ is missing.',
      },
      {
        latex: '2x^2e^{x^2}',
        expr: '2*x^2*exp(x^2)',
        mistake: 'product-rule-missing-term',
        why: 'Only $e^{x^2}$ was differentiated; the term $(x)\'e^{x^2} = e^{x^2}$ is missing.',
      },
      { latex: 'e^{x^2} + 2x^2e^{x^2}', expr: 'exp(x^2) + 2*x^2*exp(x^2)' },
      {
        latex: '2xe^{x^2}',
        expr: '2*x*exp(x^2)',
        mistake: 'product-rule-missing-term',
        why: 'The two derivatives were multiplied, $1\\cdot 2xe^{x^2}$; the product rule is $f\'g + fg\'$.',
      },
      {
        latex: 'e^{x^2} + x^3e^{x^2-1}',
        expr: 'exp(x^2) + x^3*exp(x^2 - 1)',
        mistake: 'exponential-as-power',
        why: '$e^{x^2}$ was differentiated like a power, $x^2e^{x^2-1}$; it is $e^{x^2}\\cdot 2x$.',
      },
      {
        latex: 'e^{x^2} + 2xe^{x^2}',
        expr: 'exp(x^2) + 2*x*exp(x^2)',
        mistake: 'algebra-error',
        why: 'The factor $x$ was dropped from the second term: $x\\cdot 2xe^{x^2} = 2x^2e^{x^2}$.',
      },
    ],
    correct: 2,
    explanation: 'Product rule, with the chain rule on $e^{x^2}$: $1\\cdot e^{x^2} + x\\cdot 2xe^{x^2}$.',
    check: { kind: 'derivative', of: 'x*exp(x^2)' },
    difficulty: 2,
  },
  {
    id: 'dr-f-035',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: '\\sec^{-1}(3x)' },
    options: [
      {
        latex: '\\frac{1}{|3x|\\sqrt{9x^2-1}}',
        expr: '1/(abs(3*x)*sqrt(9*x^2 - 1))',
        mistake: 'chain-rule-missing',
        why: 'The inner derivative $(3x)\' = 3$ was dropped.',
      },
      {
        latex: '\\frac{3}{|3x|\\sqrt{3x^2-1}}',
        expr: '3/(abs(3*x)*sqrt(3*x^2 - 1))',
        mistake: 'algebra-error',
        why: '$(3x)^2$ was written as $3x^2$; it is $9x^2$.',
      },
      {
        latex: '\\frac{3}{1+9x^2}',
        expr: '3/(1 + 9*x^2)',
        mistake: 'inverse-trig-confused',
        why: '$\\frac{1}{1+u^2}$ is the derivative of $\\tan^{-1}u$; $\\sec^{-1}u$ has $\\frac{1}{|u|\\sqrt{u^2-1}}$.',
      },
      {
        latex: '-\\frac{3}{|3x|\\sqrt{9x^2-1}}',
        expr: '-3/(abs(3*x)*sqrt(9*x^2 - 1))',
        mistake: 'sign-error-derivative',
        why: '$\\sec^{-1}u$ has a positive derivative; the minus sign belongs to $\\csc^{-1}u$.',
      },
      { latex: '\\frac{3}{|3x|\\sqrt{9x^2-1}}', expr: '3/(abs(3*x)*sqrt(9*x^2 - 1))' },
      {
        latex: '-3\\sin(3x)',
        expr: '-3*sin(3*x)',
        mistake: 'inverse-trig-as-reciprocal',
        why: '$\\sec^{-1}(3x)$ was read as $\\frac{1}{\\sec(3x)} = \\cos(3x)$; the $-1$ means the inverse secant.',
      },
    ],
    correct: 4,
    explanation: '$\\frac{d}{dx}\\sec^{-1}u = \\frac{u\'}{|u|\\sqrt{u^2-1}}$ with $u = 3x$, $u\' = 3$ (it simplifies to $\\frac{1}{|x|\\sqrt{9x^2-1}}$).',
    domain: [0.7, 2],
    check: { kind: 'derivative', of: 'asec(3*x)' },
    difficulty: 1,
  },
  {
    id: 'dr-f-036',
    topic: 'diff-review',
    kind: 'derivative',
    prompt: { latex: 'x^{\\pi} + \\pi^{x} + \\pi^{2}' },
    options: [
      {
        latex: '\\pi x^{\\pi-1} + x\\pi^{x-1}',
        expr: 'pi*x^(pi - 1) + x*pi^(x - 1)',
        mistake: 'exponential-as-power',
        why: '$\\pi^x$ has the variable in the exponent, so it differentiates to $\\pi^x\\ln\\pi$, not by the power rule.',
      },
      {
        latex: 'x^{\\pi}\\ln x + \\pi^{x}\\ln\\pi',
        expr: 'x^pi*log(x) + pi^x*log(pi)',
        mistake: 'exponential-as-power',
        why: '$x^{\\pi}$ is a power with the fixed exponent $\\pi$, so the power rule gives $\\pi x^{\\pi-1}$; the exponential rule does not apply.',
      },
      {
        latex: '\\pi x^{\\pi-1} + \\pi^{x}\\ln\\pi + 2\\pi',
        expr: 'pi*x^(pi - 1) + pi^x*log(pi) + 2*pi',
        mistake: 'constant-derivative',
        why: '$\\pi^2$ is a constant, so its derivative is $0$, not $2\\pi$.',
      },
      {
        latex: '\\pi x^{\\pi-1} + \\pi^{x}',
        expr: 'pi*x^(pi - 1) + pi^x',
        mistake: 'exp-base-log-missing',
        why: '$(\\pi^x)\' = \\pi^x\\ln\\pi$; the factor $\\ln\\pi$ is missing.',
      },
      { latex: '\\pi x^{\\pi-1} + \\pi^{x}\\ln\\pi', expr: 'pi*x^(pi - 1) + pi^x*log(pi)' },
    ],
    correct: 4,
    explanation: '$x^{\\pi}$ is a power ($\\pi x^{\\pi-1}$), $\\pi^x$ an exponential ($\\pi^x\\ln\\pi$), and $\\pi^2$ a constant ($0$).',
    check: { kind: 'derivative', of: 'x^pi + pi^x + pi^2' },
    difficulty: 2,
  },
  // @@APPEND_FLASH@@
];

/** Parameterized generators. */
export const generators: FlashGenerator[] = [];
