import type { FlashGenerator, FlashItem } from '../types';

/**
 * Flash Drill items for topic "trig-sub" (Lecture 7, §3.3). Authored by content-author; verified by
 * math-verifier.
 *
 * Course conventions: ax = b sin θ, ax = b tan θ, ax = b sec θ with dx = (b/a)(…) dθ.
 * Sine: θ ∈ [−π/2, π/2], cos θ ≥ 0. Tangent: θ ∈ (−π/2, π/2), sec θ > 0.
 * Secant: θ ∈ [0, π/2) ∪ (π/2, π]; tan θ ≥ 0 when x ≥ b/a, tan θ ≤ 0 when x ≤ −b/a.
 * Rewriting items check the θ-integrand against f(x(θ))·x′(θ) computed mechanically; triangle items
 * check against the exact trig value, e.g. sin(arctan(x/2)).
 */
export const flash: FlashItem[] = [
  // ───────────── choosing the substitution ─────────────
  {
    id: 'ts-f-001',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Which trigonometric substitution fits this integral?', latex: '\\int \\frac{1}{\\sqrt{25 + x^2}}\\,dx' },
    options: [
      { latex: 'x = 5\\tan\\theta' },
      { latex: 'x = 5\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for a difference $b^2 - (ax)^2$; here $25 + 25\\sin^2\\theta$ is not a single square, so the root stays.' },
      { latex: 'x = 5\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$; $25 + 25\\sec^2\\theta$ does not collapse to one square.' },
      { latex: '5x = \\tan\\theta', mistake: 'trig-sub-coefficient', why: 'The 5 is on the wrong side: $x = \\frac{1}{5}\\tan\\theta$ gives $25 + \\frac{1}{25}\\tan^2\\theta$, which is not a multiple of $1 + \\tan^2\\theta$.' },
      { latex: '5x = \\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for a difference, not a sum (and the 5 belongs with θ): $25 + \\frac{1}{25}\\sin^2\\theta$ has no identity that collapses it.' },
      { latex: '5x = \\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$, not a sum (and the 5 belongs with θ), so the radicand stays unsimplified.' },
    ],
    correct: 0,
    explanation: 'A sum $x^2 + 5^2$ calls for $x = 5\\tan\\theta$: $25 + 25\\tan^2\\theta = 25\\sec^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 1,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-002',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Which trigonometric substitution fits this integral?', latex: '\\int \\frac{\\sqrt{9 - x^2}}{x^2}\\,dx' },
    options: [
      { latex: 'x = 3\\sin\\theta' },
      { latex: 'x = 3\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for a sum $b^2 + (ax)^2$; $9 - 9\\tan^2\\theta$ is not a Pythagorean square.' },
      { latex: 'x = 3\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - b^2$; $9 - 9\\sec^2\\theta = -9\\tan^2\\theta$ is negative under the root.' },
      { latex: 'x = 9\\sin\\theta', mistake: 'trig-sub-coefficient', why: 'b is the square root of 9: $x = 9\\sin\\theta$ gives $9 - 81\\sin^2\\theta$, which does not factor as $9(1 - \\sin^2\\theta)$.' },
      { latex: 'x = 9\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums, and the coefficient should be $\\sqrt{9} = 3$, not 9.' },
      { latex: 'x = 9\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - b^2$, and the coefficient should be $\\sqrt{9} = 3$, not 9.' },
    ],
    correct: 0,
    explanation: '$9 - x^2 = 3^2 - x^2$ is a difference $b^2 - x^2$, so $x = 3\\sin\\theta$ gives $9 - 9\\sin^2\\theta = 9\\cos^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 1,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-003',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Which trigonometric substitution fits this integral (with $x > \\sqrt{2}$)?', latex: '\\int \\frac{x^2}{\\sqrt{x^2 - 2}}\\,dx' },
    options: [
      { latex: 'x = \\sqrt{2}\\sec\\theta' },
      { latex: 'x = \\sqrt{2}\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $b^2 - x^2$; $2\\sin^2\\theta - 2 = -2\\cos^2\\theta$ is negative under the root.' },
      { latex: 'x = \\sqrt{2}\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums; $2\\tan^2\\theta - 2$ is not a Pythagorean square.' },
      { latex: 'x = 2\\sec\\theta', mistake: 'trig-sub-coefficient', why: '$b^2 = 2$ means $b = \\sqrt{2}$; $x = 2\\sec\\theta$ gives $4\\sec^2\\theta - 2$, which does not factor as $2(\\sec^2\\theta - 1)$.' },
      { latex: 'x = 2\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $b^2 - x^2$, and the coefficient should be $\\sqrt{2}$, not 2.' },
      { latex: 'x = 2\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums, and the coefficient should be $\\sqrt{2}$, not 2.' },
    ],
    correct: 0,
    explanation: '$x^2 - 2 = x^2 - (\\sqrt{2})^2$, so $x = \\sqrt{2}\\sec\\theta$ gives $2\\sec^2\\theta - 2 = 2\\tan^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 1,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-004',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Using the course table ($ax = b\\sin\\theta$, $ax = b\\tan\\theta$, $ax = b\\sec\\theta$), which substitution fits this integral?', latex: '\\int \\frac{1}{\\sqrt{25x^2 + 9}}\\,dx' },
    options: [
      { latex: '5x = 3\\tan\\theta' },
      { latex: '5x = 3\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $b^2 - (ax)^2$; $9\\sin^2\\theta + 9$ does not collapse to one square.' },
      { latex: '5x = 3\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$; $9\\sec^2\\theta + 9$ is not a single square.' },
      { latex: '3x = 5\\tan\\theta', mistake: 'trig-sub-coefficient', why: 'a and b were swapped: $(ax)^2 = 25x^2$ needs $a = 5$ and $b = 3$; with $3x = 5\\tan\\theta$ the radicand is $\\frac{625}{9}\\tan^2\\theta + 9$.' },
      { latex: '3x = 5\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for a difference, not a sum, and a and b are swapped as well.' },
      { latex: '3x = 5\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$, not a sum, and a and b are swapped as well.' },
    ],
    correct: 0,
    explanation: '$25x^2 + 9 = (5x)^2 + 3^2$, so $a = 5$, $b = 3$: $5x = 3\\tan\\theta$ gives $9\\tan^2\\theta + 9 = 9\\sec^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 2,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-005',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Using the course table ($ax = b\\sin\\theta$, $ax = b\\tan\\theta$, $ax = b\\sec\\theta$), which substitution fits this integral?', latex: '\\int \\sqrt{1 - 9x^2}\\,dx' },
    options: [
      { latex: '3x = \\sin\\theta' },
      { latex: '3x = \\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums; $1 - \\tan^2\\theta$ is not a Pythagorean square.' },
      { latex: '3x = \\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$; $1 - \\sec^2\\theta = -\\tan^2\\theta$ is negative under the root.' },
      { latex: 'x = 3\\sin\\theta', mistake: 'trig-sub-coefficient', why: 'The 3 multiplies x, not the sine: $x = 3\\sin\\theta$ gives $1 - 81\\sin^2\\theta$, which does not collapse.' },
      { latex: 'x = 3\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums, and the 3 belongs with x.' },
      { latex: 'x = 3\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$, and the 3 belongs with x.' },
    ],
    correct: 0,
    explanation: '$1 - 9x^2 = 1^2 - (3x)^2$, so $a = 3$, $b = 1$: $3x = \\sin\\theta$ gives $1 - \\sin^2\\theta = \\cos^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 1,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-006',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'The substitution $2x = 3\\tan\\theta$ is designed to simplify which expression?' },
    options: [
      { latex: '4x^2 + 9' },
      { latex: '9x^2 + 4', mistake: 'trig-sub-coefficient', why: 'a and b were swapped: $9x^2 + 4 = (3x)^2 + 2^2$ needs $3x = 2\\tan\\theta$.' },
      { latex: '9 - 4x^2', mistake: 'trig-sub-wrong-form', why: 'A difference $b^2 - (ax)^2$ calls for a sine substitution, not tangent.' },
      { latex: '4x^2 - 9', mistake: 'trig-sub-wrong-form', why: '$(ax)^2 - b^2$ calls for a secant substitution, since $\\sec^2\\theta - 1 = \\tan^2\\theta$.' },
      { latex: '4 - 9x^2', mistake: 'trig-sub-wrong-form', why: 'A difference calls for sine, and the roles of 2 and 3 are swapped as well.' },
      { latex: '9x^2 - 4', mistake: 'trig-sub-wrong-form', why: '$(ax)^2 - b^2$ calls for secant, and the roles of 2 and 3 are swapped as well.' },
    ],
    correct: 0,
    explanation: 'With $2x = 3\\tan\\theta$: $(2x)^2 + 3^2 = 9\\tan^2\\theta + 9 = 9\\sec^2\\theta$, i.e. the expression $4x^2 + 9$.',
    check: { kind: 'none', reason: 'reverse lookup in the substitution table; options are expressions to be matched, not values' },
    difficulty: 2,
    tags: ['which-sub'],
  },

  // ───────────── computing dx ─────────────
  {
    id: 'ts-f-007',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'If $x = 3\\sin\\theta$, then' },
    options: [
      { latex: 'dx = 3\\cos\\theta\\,d\\theta', expr: '3*cos(theta)*dtheta' },
      { latex: 'dx = \\cos\\theta\\,d\\theta', expr: 'cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'The factor 3 was dropped: $\\frac{d}{d\\theta}(3\\sin\\theta) = 3\\cos\\theta$.' },
      { latex: 'dx = \\frac{1}{3}\\cos\\theta\\,d\\theta', expr: 'cos(theta)*dtheta/3', mistake: 'dx-coefficient', why: 'Divided by 3 instead of multiplying; that is $dx$ for $3x = \\sin\\theta$.' },
      { latex: 'dx = -3\\cos\\theta\\,d\\theta', expr: '-3*cos(theta)*dtheta', mistake: 'dx-derivative-wrong', why: 'The derivative of $\\sin\\theta$ is $+\\cos\\theta$; the minus sign belongs to the derivative of cosine.' },
      { latex: 'dx = 3\\sec^2\\theta\\,d\\theta', expr: '3*sec(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: 'That is $\\frac{d}{d\\theta}(3\\tan\\theta)$, the tangent row of the table.' },
    ],
    correct: 0,
    explanation: '$\\frac{dx}{d\\theta} = 3\\cos\\theta$, so $dx = 3\\cos\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
    check: { kind: 'value', expected: '3*cos(theta)*dtheta' },
    difficulty: 1,
    tags: ['dx'],
  },
  {
    id: 'ts-f-008',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With the course convention $ax = b\\sin\\theta$: if $3x = 2\\sin\\theta$, then' },
    options: [
      { latex: 'dx = \\frac{2}{3}\\cos\\theta\\,d\\theta', expr: '(2/3)*cos(theta)*dtheta' },
      { latex: 'dx = \\frac{3}{2}\\cos\\theta\\,d\\theta', expr: '(3/2)*cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'b/a was inverted: from $3\\,dx = 2\\cos\\theta\\,d\\theta$, divide by 3 to get $\\frac{2}{3}$.' },
      { latex: 'dx = 2\\cos\\theta\\,d\\theta', expr: '2*cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'The right side was differentiated, but the 3 multiplying $dx$ on the left was never divided out.' },
      { latex: 'dx = 6\\cos\\theta\\,d\\theta', expr: '6*cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'Multiplied by $a = 3$ instead of dividing by it.' },
      { latex: 'dx = -\\frac{2}{3}\\cos\\theta\\,d\\theta', expr: '-(2/3)*cos(theta)*dtheta', mistake: 'dx-derivative-wrong', why: 'The derivative of $\\sin\\theta$ is $+\\cos\\theta$; the minus sign belongs to the derivative of cosine.' },
    ],
    correct: 0,
    explanation: 'Differentiate both sides: $3\\,dx = 2\\cos\\theta\\,d\\theta$, so $dx = \\frac{b}{a}\\cos\\theta\\,d\\theta = \\frac{2}{3}\\cos\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
    check: { kind: 'value', expected: '2*cos(theta)*dtheta/3' },
    difficulty: 2,
    tags: ['dx'],
  },
  {
    id: 'ts-f-009',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'If $x = 2\\tan\\theta$, then' },
    options: [
      { latex: 'dx = 2\\sec^2\\theta\\,d\\theta', expr: '2*sec(theta)^2*dtheta' },
      { latex: 'dx = 2\\sec\\theta\\tan\\theta\\,d\\theta', expr: '2*sec(theta)*tan(theta)*dtheta', mistake: 'dx-derivative-wrong', why: 'That is the derivative of $2\\sec\\theta$; the derivative of $\\tan\\theta$ is $\\sec^2\\theta$.' },
      { latex: 'dx = \\sec^2\\theta\\,d\\theta', expr: 'sec(theta)^2*dtheta', mistake: 'dx-coefficient', why: 'The factor 2 from $x = 2\\tan\\theta$ was dropped.' },
      { latex: 'dx = \\frac{1}{2}\\sec^2\\theta\\,d\\theta', expr: 'sec(theta)^2*dtheta/2', mistake: 'dx-coefficient', why: 'Divided by 2 instead of multiplying; that is $dx$ for $2x = \\tan\\theta$.' },
      { latex: 'dx = -2\\csc^2\\theta\\,d\\theta', expr: '-2*csc(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: 'That is the derivative of $2\\cot\\theta$, not of $2\\tan\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\frac{d}{d\\theta}(2\\tan\\theta) = 2\\sec^2\\theta$, so $dx = 2\\sec^2\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2], dtheta: [0.25, 1.25] },
    check: { kind: 'value', expected: '2*sec(theta)^2*dtheta' },
    difficulty: 1,
    tags: ['dx'],
  },
  {
    id: 'ts-f-010',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With the course convention $ax = b\\sec\\theta$: if $5x = 3\\sec\\theta$, then' },
    options: [
      { latex: 'dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta', expr: '(3/5)*sec(theta)*tan(theta)*dtheta' },
      { latex: 'dx = \\frac{5}{3}\\sec\\theta\\tan\\theta\\,d\\theta', expr: '(5/3)*sec(theta)*tan(theta)*dtheta', mistake: 'dx-coefficient', why: 'b/a was inverted: $5\\,dx = 3\\sec\\theta\\tan\\theta\\,d\\theta$ gives $\\frac{3}{5}$.' },
      { latex: 'dx = 3\\sec\\theta\\tan\\theta\\,d\\theta', expr: '3*sec(theta)*tan(theta)*dtheta', mistake: 'dx-coefficient', why: 'The right side was differentiated, but the 5 multiplying $dx$ was never divided out.' },
      { latex: 'dx = \\frac{3}{5}\\sec^2\\theta\\,d\\theta', expr: '(3/5)*sec(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: 'That uses the derivative of $\\tan\\theta$; the derivative of $\\sec\\theta$ is $\\sec\\theta\\tan\\theta$.' },
      { latex: 'dx = \\frac{5}{3}\\sec^2\\theta\\,d\\theta', expr: '(5/3)*sec(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: 'Two slips: used the tangent derivative $\\sec^2\\theta$, and inverted $\\frac{b}{a}$ to $\\frac{5}{3}$.' },
    ],
    correct: 0,
    explanation: 'Differentiate both sides: $5\\,dx = 3\\sec\\theta\\tan\\theta\\,d\\theta$, so $dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2], dtheta: [0.25, 1.25] },
    check: { kind: 'value', expected: '3*sec(theta)*tan(theta)*dtheta/5' },
    difficulty: 2,
    tags: ['dx'],
  },

  // ───────────── collapsing the radicand ─────────────
  {
    id: 'ts-f-011',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With $x = 3\\sin\\theta$ and $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$, which simplification is correct?' },
    options: [
      { latex: '\\sqrt{9-x^2} = 3\\cos\\theta', expr: '3*cos(theta)' },
      { latex: '\\sqrt{9-x^2} = 9\\cos\\theta', expr: '9*cos(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{9\\cos^2\\theta} = 3|\\cos\\theta|$; the 9 must be rooted too.' },
      { latex: '\\sqrt{9-x^2} = -3\\cos\\theta', expr: '-3*cos(theta)', mistake: 'theta-interval-sign', why: 'On $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$ the cosine is nonnegative, so the root is $+3\\cos\\theta$.' },
      { latex: '\\sqrt{9-x^2} = 3 - 3\\sin\\theta', expr: '3 - 3*sin(theta)', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{9 - 9\\sin^2\\theta} \\ne \\sqrt{9} - \\sqrt{9\\sin^2\\theta}$.' },
      { latex: '\\sqrt{9-x^2} = 3\\tan\\theta', expr: '3*tan(theta)', mistake: 'pythagorean-wrong', why: 'Paired $1 - \\sin^2\\theta$ with $\\tan^2\\theta$; the identity is $1 - \\sin^2\\theta = \\cos^2\\theta$.' },
    ],
    correct: 0,
    explanation: '$9 - 9\\sin^2\\theta = 9\\cos^2\\theta$ and $\\cos\\theta \\ge 0$ on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, so the root is $3\\cos\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.2, 1.2] },
    check: { kind: 'identity', lhs: 'sqrt(9 - (3*sin(theta))^2)' },
    difficulty: 1,
    tags: ['radical'],
  },
  {
    id: 'ts-f-012',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Let $x = 2\\tan\\theta$ with $x < 0$, so $-\\frac{\\pi}{2} < \\theta < 0$. Which simplification is correct?' },
    options: [
      { latex: '\\sqrt{x^2+4} = 2\\sec\\theta', expr: '2*sec(theta)' },
      { latex: '\\sqrt{x^2+4} = -2\\sec\\theta', expr: '-2*sec(theta)', mistake: 'theta-interval-sign', why: 'A negative x does not make the root negative: $\\sec\\theta > 0$ on all of $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$.' },
      { latex: '\\sqrt{x^2+4} = 4\\cos\\theta', expr: '4*cos(theta)', mistake: 'sqrt-constant-not-rooted', why: 'Two slips: the 4 in $\\sqrt{4\\sec^2\\theta}$ was not rooted, and $\\sec\\theta$ was replaced by its reciprocal $\\cos\\theta$.' },
      { latex: '\\sqrt{x^2+4} = 2 - 2\\tan\\theta', expr: '2 - 2*tan(theta)', mistake: 'sqrt-of-sum-split', why: 'The root was split over the sum: $\\sqrt{4\\tan^2\\theta} + \\sqrt{4} = 2|\\tan\\theta| + 2$ is not $\\sqrt{4\\tan^2\\theta + 4}$.' },
      { latex: '\\sqrt{x^2+4} = 2\\cos\\theta', expr: '2*cos(theta)', mistake: 'pythagorean-wrong', why: 'The identity is $1 + \\tan^2\\theta = \\sec^2\\theta$; cosine is the reciprocal of secant, not the same function.' },
    ],
    correct: 0,
    explanation: '$4\\tan^2\\theta + 4 = 4\\sec^2\\theta$, and $\\sec\\theta > 0$ on $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$ even when $x < 0$, so the root is $2\\sec\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.3, -0.2] },
    check: { kind: 'identity', lhs: 'sqrt((2*tan(theta))^2 + 4)' },
    difficulty: 2,
    tags: ['radical', 'sign'],
  },
  {
    id: 'ts-f-013',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With $x = \\sqrt{2}\\sec\\theta$ and $x > \\sqrt{2}$ (so $0 \\le \\theta < \\frac{\\pi}{2}$), which simplification is correct?' },
    options: [
      { latex: '\\sqrt{x^2-2} = \\sqrt{2}\\tan\\theta', expr: 'sqrt(2)*tan(theta)' },
      { latex: '\\sqrt{x^2-2} = 2\\tan\\theta', expr: '2*tan(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{2\\tan^2\\theta} = \\sqrt{2}\\,|\\tan\\theta|$; the 2 must be rooted too.' },
      { latex: '\\sqrt{x^2-2} = -\\sqrt{2}\\tan\\theta', expr: '-sqrt(2)*tan(theta)', mistake: 'theta-interval-sign', why: 'For $x > \\sqrt{2}$, θ lies in $[0, \\frac{\\pi}{2})$ where $\\tan\\theta \\ge 0$; the minus sign is for $x < -\\sqrt{2}$.' },
      { latex: '\\sqrt{x^2-2} = \\sqrt{2}\\sec\\theta - \\sqrt{2}', expr: 'sqrt(2)*sec(theta) - sqrt(2)', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{2\\sec^2\\theta - 2} \\ne \\sqrt{2\\sec^2\\theta} - \\sqrt{2}$.' },
      { latex: '\\sqrt{x^2-2} = \\tan\\theta', expr: 'tan(theta)', mistake: 'coefficient-mishandled', why: 'The factor 2 in $2(\\sec^2\\theta - 1)$ was lost; its root $\\sqrt{2}$ must stay in front.' },
    ],
    correct: 0,
    explanation: '$2\\sec^2\\theta - 2 = 2\\tan^2\\theta$, and $\\tan\\theta \\ge 0$ on $[0, \\frac{\\pi}{2})$, so the root is $\\sqrt{2}\\tan\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.3] },
    check: { kind: 'identity', lhs: 'sqrt((sqrt(2)*sec(theta))^2 - 2)' },
    difficulty: 1,
    tags: ['radical', 'sign'],
  },
  {
    id: 'ts-f-014',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'The substitution $ax = b\\sin\\theta$ turns $b^2 - a^2x^2$ into a perfect square by using which identity?' },
    options: [
      { latex: '1 - \\sin^2\\theta = \\cos^2\\theta' },
      { latex: '1 + \\tan^2\\theta = \\sec^2\\theta', mistake: 'trig-sub-wrong-form', why: 'This identity is behind the tangent substitution, for a sum $b^2 + (ax)^2$.' },
      { latex: '\\sec^2\\theta - 1 = \\tan^2\\theta', mistake: 'trig-sub-wrong-form', why: 'This identity is behind the secant substitution, for $(ax)^2 - b^2$.' },
      { latex: '\\sin^2\\theta - 1 = \\cos^2\\theta', mistake: 'pythagorean-wrong', why: 'Sign error: $\\sin^2\\theta - 1 = -\\cos^2\\theta$.' },
      { latex: '1 - \\sin^2\\theta = \\tan^2\\theta', mistake: 'pythagorean-wrong', why: 'Wrong pairing: $1 - \\sin^2\\theta$ equals $\\cos^2\\theta$; tangent pairs with secant.' },
    ],
    correct: 0,
    explanation: '$b^2 - b^2\\sin^2\\theta = b^2(1 - \\sin^2\\theta) = b^2\\cos^2\\theta$.',
    check: { kind: 'none', reason: 'identity recall; several options are true identities that belong to other substitutions' },
    difficulty: 1,
    tags: ['identity'],
  },
  {
    id: 'ts-f-015',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With $4x = 3\\tan\\theta$ and $-\\frac{\\pi}{2} < \\theta < \\frac{\\pi}{2}$, $\\sqrt{16x^2 + 9}$ simplifies to' },
    options: [
      { latex: '3\\sec\\theta', expr: '3*sec(theta)' },
      { latex: '9\\sec\\theta', expr: '9*sec(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{9\\sec^2\\theta} = 3\\sec\\theta$; the 9 must be rooted too.' },
      { latex: '4\\sec\\theta', expr: '4*sec(theta)', mistake: 'coefficient-mishandled', why: 'The constant that survives is $b = 3$: $(4x)^2 + 9 = 9\\tan^2\\theta + 9 = 9\\sec^2\\theta$.' },
      { latex: '\\frac{3}{4}\\sec\\theta', expr: '(3/4)*sec(theta)', mistake: 'coefficient-mishandled', why: 'Factored $16x^2 + 9 = 16(x^2 + \\frac{9}{16})$ and dropped the 16: $\\sqrt{x^2 + \\frac{9}{16}} = \\frac{3}{4}\\sec\\theta$.' },
      { latex: '3\\tan\\theta + 3', expr: '3*tan(theta) + 3', mistake: 'sqrt-of-sum-split', why: 'The root was split over the sum: $\\sqrt{9\\tan^2\\theta + 9} \\ne 3\\tan\\theta + 3$.' },
      { latex: '-3\\sec\\theta', expr: '-3*sec(theta)', mistake: 'theta-interval-sign', why: '$\\sec\\theta > 0$ on $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$, so the root is positive.' },
    ],
    correct: 0,
    explanation: '$(4x)^2 = 9\\tan^2\\theta$, so $16x^2 + 9 = 9(\\tan^2\\theta + 1) = 9\\sec^2\\theta$, whose root is $3\\sec\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2] },
    check: { kind: 'identity', lhs: 'sqrt(16*(3*tan(theta)/4)^2 + 9)' },
    difficulty: 2,
    tags: ['radical'],
  },

  // ───────────── rewriting the whole integral in θ ─────────────
  {
    id: 'ts-f-016',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $x = 2\\tan\\theta$. The integral in θ is', latex: '\\int \\frac{1}{x^2\\sqrt{x^2+4}}\\,dx' },
    options: [
      { latex: '\\int \\frac{\\sec\\theta}{4\\tan^2\\theta}\\,d\\theta', expr: 'indefinite(sec(theta)/(4*tan(theta)^2), theta)' },
      { latex: '\\int \\frac{1}{8\\tan^2\\theta\\sec\\theta}\\,d\\theta', expr: 'indefinite(1/(8*tan(theta)^2*sec(theta)), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $2\\sec^2\\theta$.' },
      { latex: '\\int \\frac{\\sec\\theta}{8\\tan^2\\theta}\\,d\\theta', expr: 'indefinite(sec(theta)/(8*tan(theta)^2), theta)', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{x^2+4} = 4\\sec\\theta$; the root of $4\\sec^2\\theta$ is $2\\sec\\theta$.' },
      { latex: '\\int \\frac{1}{4\\tan\\theta}\\,d\\theta', expr: 'indefinite(1/(4*tan(theta)), theta)', mistake: 'dx-derivative-wrong', why: 'Used $dx = 2\\sec\\theta\\tan\\theta\\,d\\theta$ (the secant derivative) instead of $2\\sec^2\\theta\\,d\\theta$.' },
      { latex: '\\int \\frac{\\sec\\theta}{x^2}\\,d\\theta', expr: 'indefinite(sec(theta)/x^2, theta)', mistake: 'mixed-variables', why: 'The $x^2$ in the denominator was never rewritten as $4\\tan^2\\theta$, so x and θ are mixed.' },
      { latex: '\\int \\frac{\\sec\\theta}{2\\tan^2\\theta}\\,d\\theta', expr: 'indefinite(sec(theta)/(2*tan(theta)^2), theta)', mistake: 'coefficient-mishandled', why: 'Squared $2\\tan\\theta$ as $2\\tan^2\\theta$; the coefficient is squared too: $x^2 = 4\\tan^2\\theta$.' },
    ],
    correct: 0,
    explanation: '$x^2 = 4\\tan^2\\theta$, $\\sqrt{x^2+4} = 2\\sec\\theta$, $dx = 2\\sec^2\\theta\\,d\\theta$: $\\frac{2\\sec^2\\theta}{4\\tan^2\\theta\\cdot 2\\sec\\theta} = \\frac{\\sec\\theta}{4\\tan^2\\theta}$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2], x: [0.5, 3] },
    check: { kind: 'identity', lhs: 'indefinite(2*sec(theta)^2/((2*tan(theta))^2*sqrt((2*tan(theta))^2 + 4)), theta)' },
    difficulty: 1,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-017',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $x = \\sin\\theta$ with $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$. The integral in θ is', latex: '\\int \\frac{x^3}{\\sqrt{1-x^2}}\\,dx' },
    options: [
      { latex: '\\int \\sin^3\\theta\\,d\\theta', expr: 'indefinite(sin(theta)^3, theta)' },
      { latex: '\\int \\frac{\\sin^3\\theta}{\\cos\\theta}\\,d\\theta', expr: 'indefinite(sin(theta)^3/cos(theta), theta)', mistake: 'dx-not-replaced', why: '$dx$ became $d\\theta$ without the factor $\\cos\\theta$, so the root in the denominator did not cancel.' },
      { latex: '\\int -\\frac{\\sin^3\\theta}{\\cos\\theta}\\,d\\theta', expr: 'indefinite(-sin(theta)^3/cos(theta), theta)', mistake: 'theta-interval-sign', why: 'Two slips: took $\\sqrt{\\cos^2\\theta} = -\\cos\\theta$ (cosine is nonnegative on this interval) and dropped the factor $\\cos\\theta$ from $dx$.' },
      { latex: '\\int \\frac{\\sin^3\\theta\\cos\\theta}{1-\\sin\\theta}\\,d\\theta', expr: 'indefinite(sin(theta)^3*cos(theta)/(1 - sin(theta)), theta)', mistake: 'sqrt-of-sum-split', why: 'The root was split: $\\sqrt{1 - \\sin^2\\theta}$ was written as $1 - \\sin\\theta$.' },
      { latex: '\\int x^3\\,d\\theta', expr: 'indefinite(x^3, theta)', mistake: 'mixed-variables', why: 'The factor $x^3$ was left in x; it must become $\\sin^3\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\frac{\\sin^3\\theta}{\\cos\\theta}\\cdot\\cos\\theta\\,d\\theta = \\sin^3\\theta\\,d\\theta$, using $\\sqrt{1-\\sin^2\\theta} = \\cos\\theta \\ge 0$.',
    variable: 'theta',
    domain: { theta: [-1.2, 1.2], x: [0.2, 0.9] },
    check: { kind: 'identity', lhs: 'indefinite(sin(theta)^3*cos(theta)/sqrt(1 - sin(theta)^2), theta)' },
    difficulty: 1,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-018',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $x = \\sqrt{2}\\sec\\theta$, where $x > \\sqrt{2}$. The integral in θ is', latex: '\\int \\frac{x^2}{\\sqrt{x^2-2}}\\,dx' },
    options: [
      { latex: '\\int 2\\sec^3\\theta\\,d\\theta', expr: 'indefinite(2*sec(theta)^3, theta)' },
      { latex: '\\int -2\\sec^3\\theta\\,d\\theta', expr: 'indefinite(-2*sec(theta)^3, theta)', mistake: 'theta-interval-sign', why: 'Took $\\sqrt{x^2-2} = -\\sqrt{2}\\tan\\theta$; for $x > \\sqrt{2}$, $\\tan\\theta \\ge 0$, so the root is $+\\sqrt{2}\\tan\\theta$.' },
      { latex: '\\int \\sqrt{2}\\sec^3\\theta\\,d\\theta', expr: 'indefinite(sqrt(2)*sec(theta)^3, theta)', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{2\\tan^2\\theta} = 2\\tan\\theta$; the root is $\\sqrt{2}\\tan\\theta$.' },
      { latex: '\\int \\frac{\\sqrt{2}\\sec^2\\theta}{\\tan\\theta}\\,d\\theta', expr: 'indefinite(sqrt(2)*sec(theta)^2/tan(theta), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\sqrt{2}\\sec\\theta\\tan\\theta$.' },
      { latex: '\\int \\frac{2\\sec^4\\theta}{\\tan\\theta}\\,d\\theta', expr: 'indefinite(2*sec(theta)^4/tan(theta), theta)', mistake: 'dx-derivative-wrong', why: 'Used $dx = \\sqrt{2}\\sec^2\\theta\\,d\\theta$ (the tangent derivative); for secant it is $\\sqrt{2}\\sec\\theta\\tan\\theta\\,d\\theta$.' },
      { latex: '\\int x^2\\sec\\theta\\,d\\theta', expr: 'indefinite(x^2*sec(theta), theta)', mistake: 'mixed-variables', why: 'The numerator $x^2$ was left in x; it must become $2\\sec^2\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\frac{2\\sec^2\\theta}{\\sqrt{2}\\tan\\theta}\\cdot\\sqrt{2}\\sec\\theta\\tan\\theta\\,d\\theta = 2\\sec^3\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2], x: [1.6, 3] },
    check: { kind: 'identity', lhs: 'indefinite((sqrt(2)*sec(theta))^2*sqrt(2)*sec(theta)*tan(theta)/sqrt((sqrt(2)*sec(theta))^2 - 2), theta)' },
    difficulty: 2,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-019',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $x = 3\\sin\\theta$ with $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$. The integral in θ is', latex: '\\int \\frac{\\sqrt{9-x^2}}{x^2}\\,dx' },
    options: [
      { latex: '\\int \\frac{\\cos^2\\theta}{\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(cos(theta)^2/sin(theta)^2, theta)' },
      { latex: '\\int \\frac{\\cos\\theta}{3\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(cos(theta)/(3*sin(theta)^2), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $3\\cos\\theta$.' },
      { latex: '\\int \\frac{3\\cos^2\\theta}{\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(3*cos(theta)^2/sin(theta)^2, theta)', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{9\\cos^2\\theta} = 9\\cos\\theta$; the root is $3\\cos\\theta$.' },
      { latex: '\\int \\frac{\\cos^2\\theta}{3\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(cos(theta)^2/(3*sin(theta)^2), theta)', mistake: 'dx-coefficient', why: 'Used $dx = \\cos\\theta\\,d\\theta$; with $x = 3\\sin\\theta$ it is $3\\cos\\theta\\,d\\theta$.' },
      { latex: '\\int \\frac{9\\cos^2\\theta}{x^2}\\,d\\theta', expr: 'indefinite(9*cos(theta)^2/x^2, theta)', mistake: 'mixed-variables', why: 'The $x^2$ in the denominator was never rewritten as $9\\sin^2\\theta$.' },
      { latex: '\\int -\\frac{3\\cos^2\\theta}{\\sin^2\\theta}\\,d\\theta', expr: 'indefinite(-3*cos(theta)^2/sin(theta)^2, theta)', mistake: 'theta-interval-sign', why: 'Two slips: took $\\sqrt{9 - x^2} = -9\\cos\\theta$, with a negative sign (cosine is nonnegative here) and an unrooted 9.' },
    ],
    correct: 0,
    explanation: '$\\frac{3\\cos\\theta}{9\\sin^2\\theta}\\cdot 3\\cos\\theta\\,d\\theta = \\frac{\\cos^2\\theta}{\\sin^2\\theta}\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.3], x: [0.5, 2.5] },
    check: { kind: 'identity', lhs: 'indefinite(sqrt(9 - (3*sin(theta))^2)*3*cos(theta)/(3*sin(theta))^2, theta)' },
    difficulty: 1,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-020',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $3x = \\sin\\theta$ with $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$. The integral in θ is', latex: '\\int \\sqrt{1-9x^2}\\,dx' },
    options: [
      { latex: '\\int \\frac{1}{3}\\cos^2\\theta\\,d\\theta', expr: 'indefinite(cos(theta)^2/3, theta)' },
      { latex: '\\int 3\\cos^2\\theta\\,d\\theta', expr: 'indefinite(3*cos(theta)^2, theta)', mistake: 'dx-coefficient', why: 'Used $dx = 3\\cos\\theta\\,d\\theta$; from $3\\,dx = \\cos\\theta\\,d\\theta$, $dx = \\frac{1}{3}\\cos\\theta\\,d\\theta$.' },
      { latex: '\\int \\cos^2\\theta\\,d\\theta', expr: 'indefinite(cos(theta)^2, theta)', mistake: 'dx-coefficient', why: 'The factor $\\frac{1}{3}$ in $dx = \\frac{1}{3}\\cos\\theta\\,d\\theta$ was dropped.' },
      { latex: '\\int \\cos\\theta\\,d\\theta', expr: 'indefinite(cos(theta), theta)', mistake: 'dx-not-replaced', why: '$dx$ was simply renamed $d\\theta$; it must be $\\frac{1}{3}\\cos\\theta\\,d\\theta$.' },
      { latex: '\\int -3\\cos^2\\theta\\,d\\theta', expr: 'indefinite(-3*cos(theta)^2, theta)', mistake: 'theta-interval-sign', why: 'Two slips: took $\\sqrt{\\cos^2\\theta} = -\\cos\\theta$ (cosine is nonnegative here) and used $dx = 3\\cos\\theta\\,d\\theta$ instead of $\\frac{1}{3}\\cos\\theta\\,d\\theta$.' },
      { latex: '\\int \\frac{1}{3}\\cos\\theta\\sqrt{1-9x^2}\\,d\\theta', expr: 'indefinite(cos(theta)*sqrt(1 - 9*x^2)/3, theta)', mistake: 'mixed-variables', why: '$dx$ was replaced but the root was left in x; it must become $\\cos\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\sqrt{1 - \\sin^2\\theta} = \\cos\\theta$ and $dx = \\frac{1}{3}\\cos\\theta\\,d\\theta$, so the integrand is $\\frac{1}{3}\\cos^2\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.2, 1.2], x: [0.05, 0.3] },
    check: { kind: 'identity', lhs: 'indefinite(sqrt(1 - 9*(sin(theta)/3)^2)*cos(theta)/3, theta)' },
    difficulty: 1,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-021',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $x = 2\\sin\\theta$ with $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$. The integral in θ is', latex: '\\int \\frac{8}{x^2\\sqrt{4-x^2}}\\,dx' },
    options: [
      { latex: '\\int 2\\csc^2\\theta\\,d\\theta', expr: 'indefinite(2*csc(theta)^2, theta)' },
      { latex: '\\int \\csc^2\\theta\\,d\\theta', expr: 'indefinite(csc(theta)^2, theta)', mistake: 'dx-coefficient', why: 'Used $dx = \\cos\\theta\\,d\\theta$; with $x = 2\\sin\\theta$ it is $2\\cos\\theta\\,d\\theta$.' },
      { latex: '\\int 4\\csc^2\\theta\\,d\\theta', expr: 'indefinite(4*csc(theta)^2, theta)', mistake: 'coefficient-mishandled', why: 'Squared $2\\sin\\theta$ as $2\\sin^2\\theta$; the coefficient is squared too: $x^2 = 4\\sin^2\\theta$.' },
      { latex: '\\int \\frac{1}{\\sin^2\\theta\\cos\\theta}\\,d\\theta', expr: 'indefinite(1/(sin(theta)^2*cos(theta)), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $2\\cos\\theta$, so the $\\cos\\theta$ from the root did not cancel.' },
      { latex: '\\int -4\\csc^2\\theta\\,d\\theta', expr: 'indefinite(-4*csc(theta)^2, theta)', mistake: 'theta-interval-sign', why: 'Two slips: took $\\sqrt{4 - x^2} = -2\\cos\\theta$ (cosine is nonnegative here) and squared $2\\sin\\theta$ as $2\\sin^2\\theta$.' },
      { latex: '\\int \\frac{8}{x^2}\\,d\\theta', expr: 'indefinite(8/x^2, theta)', mistake: 'mixed-variables', why: 'The root and $dx$ were converted but $x^2$ was left in x; it must become $4\\sin^2\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\frac{8\\cdot 2\\cos\\theta}{4\\sin^2\\theta\\cdot 2\\cos\\theta} = \\frac{2}{\\sin^2\\theta} = 2\\csc^2\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.3], x: [0.5, 1.8] },
    check: { kind: 'identity', lhs: 'indefinite(8*2*cos(theta)/((2*sin(theta))^2*sqrt(4 - (2*sin(theta))^2)), theta)' },
    difficulty: 2,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-022',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $x = \\tan\\theta$. The integral in θ is', latex: '\\int \\frac{8}{(x^2+1)^2}\\,dx' },
    options: [
      { latex: '\\int 8\\cos^2\\theta\\,d\\theta', expr: 'indefinite(8*cos(theta)^2, theta)' },
      { latex: '\\int 8\\cos^4\\theta\\,d\\theta', expr: 'indefinite(8*cos(theta)^4, theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\sec^2\\theta$, leaving $\\frac{8}{\\sec^4\\theta}$.' },
      { latex: '\\int 8\\sin\\theta\\cos^2\\theta\\,d\\theta', expr: 'indefinite(8*sin(theta)*cos(theta)^2, theta)', mistake: 'dx-derivative-wrong', why: 'Used $dx = \\sec\\theta\\tan\\theta\\,d\\theta$ (the secant derivative); for $x = \\tan\\theta$, $dx = \\sec^2\\theta\\,d\\theta$.' },
      { latex: '\\int 8\\,d\\theta', expr: 'indefinite(8, theta)', mistake: 'exponent-arithmetic', why: 'Lost the outer square: $(x^2+1)^2 = (\\sec^2\\theta)^2 = \\sec^4\\theta$, not $\\sec^2\\theta$.' },
      { latex: '\\int 8\\sin^2\\theta\\,d\\theta', expr: 'indefinite(8*sin(theta)^2, theta)', mistake: 'reciprocal-identity-confused', why: '$\\frac{1}{\\sec^2\\theta} = \\cos^2\\theta$; sine is the reciprocal of cosecant, not of secant.' },
    ],
    correct: 0,
    explanation: '$x^2 + 1 = \\sec^2\\theta$ and $dx = \\sec^2\\theta\\,d\\theta$: $\\frac{8\\sec^2\\theta}{\\sec^4\\theta} = 8\\cos^2\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2] },
    check: { kind: 'identity', lhs: 'indefinite(8*sec(theta)^2/(tan(theta)^2 + 1)^2, theta)' },
    difficulty: 2,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-023',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $x = \\sec\\theta$, where $x > 1$ (so $0 \\le \\theta < \\frac{\\pi}{2}$). The integral in θ is', latex: '\\int \\frac{2}{x^3\\sqrt{x^2-1}}\\,dx' },
    options: [
      { latex: '\\int 2\\cos^2\\theta\\,d\\theta', expr: 'indefinite(2*cos(theta)^2, theta)' },
      { latex: '\\int -2\\cos^2\\theta\\,d\\theta', expr: 'indefinite(-2*cos(theta)^2, theta)', mistake: 'theta-interval-sign', why: 'Took $\\sqrt{x^2-1} = -\\tan\\theta$; for $x > 1$, $\\tan\\theta \\ge 0$.' },
      { latex: '\\int \\frac{2\\cos^3\\theta}{\\tan\\theta}\\,d\\theta', expr: 'indefinite(2*cos(theta)^3/tan(theta), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\sec\\theta\\tan\\theta$.' },
      { latex: '\\int \\frac{2\\cos^2\\theta}{\\sin\\theta}\\,d\\theta', expr: 'indefinite(2*cos(theta)^2/sin(theta), theta)', mistake: 'dx-derivative-wrong', why: 'Used $dx = \\sec^2\\theta\\,d\\theta$ (the tangent derivative); for $x = \\sec\\theta$, $dx = \\sec\\theta\\tan\\theta\\,d\\theta$.' },
      { latex: '\\int 2\\sin^2\\theta\\,d\\theta', expr: 'indefinite(2*sin(theta)^2, theta)', mistake: 'reciprocal-identity-confused', why: '$\\frac{1}{\\sec^2\\theta} = \\cos^2\\theta$; sine is the reciprocal of cosecant, not of secant.' },
      { latex: '\\int \\frac{2\\sec\\theta}{x^3}\\,d\\theta', expr: 'indefinite(2*sec(theta)/x^3, theta)', mistake: 'mixed-variables', why: 'The $x^3$ was left in x; it must become $\\sec^3\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\frac{2\\sec\\theta\\tan\\theta}{\\sec^3\\theta\\tan\\theta} = \\frac{2}{\\sec^2\\theta} = 2\\cos^2\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.3], x: [1.5, 3] },
    check: { kind: 'identity', lhs: 'indefinite(2*sec(theta)*tan(theta)/(sec(theta)^3*sqrt(sec(theta)^2 - 1)), theta)' },
    difficulty: 2,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-024',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $5x = 3\\sec\\theta$, where $x > \\frac{3}{5}$. The integral in θ is', latex: '\\int \\frac{5}{\\sqrt{25x^2-9}}\\,dx' },
    options: [
      { latex: '\\int \\sec\\theta\\,d\\theta', expr: 'indefinite(sec(theta), theta)' },
      { latex: '\\int 5\\sec\\theta\\,d\\theta', expr: 'indefinite(5*sec(theta), theta)', mistake: 'dx-coefficient', why: 'Used $dx = 3\\sec\\theta\\tan\\theta\\,d\\theta$; the 5 on the left must be divided out: $dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta$.' },
      { latex: '\\int \\frac{25}{9}\\sec\\theta\\,d\\theta', expr: 'indefinite(25*sec(theta)/9, theta)', mistake: 'dx-coefficient', why: 'Used $dx = \\frac{5}{3}\\sec\\theta\\tan\\theta\\,d\\theta$ (b/a inverted); it is $\\frac{3}{5}$.' },
      { latex: '\\int \\frac{1}{3}\\sec\\theta\\,d\\theta', expr: 'indefinite(sec(theta)/3, theta)', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{9\\tan^2\\theta} = 9\\tan\\theta$; the root is $3\\tan\\theta$.' },
      { latex: '\\int -\\sec\\theta\\,d\\theta', expr: 'indefinite(-sec(theta), theta)', mistake: 'theta-interval-sign', why: 'Took $\\sqrt{9\\tan^2\\theta} = -3\\tan\\theta$; for $x > \\frac{3}{5}$, $\\tan\\theta \\ge 0$.' },
      { latex: '\\int \\frac{5}{3\\tan\\theta}\\,d\\theta', expr: 'indefinite(5/(3*tan(theta)), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $\\frac{3}{5}\\sec\\theta\\tan\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\sqrt{9\\sec^2\\theta - 9} = 3\\tan\\theta$ and $dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta$: $\\frac{5}{3\\tan\\theta}\\cdot\\frac{3}{5}\\sec\\theta\\tan\\theta = \\sec\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2] },
    check: { kind: 'identity', lhs: 'indefinite(5*(3/5)*sec(theta)*tan(theta)/sqrt(25*(3*sec(theta)/5)^2 - 9), theta)' },
    difficulty: 2,
    tags: ['rewrite'],
  },
  {
    id: 'ts-f-025',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Substitute $x = 5\\tan\\theta$. The integral in θ is', latex: '\\int \\frac{1}{\\sqrt{25+x^2}}\\,dx' },
    options: [
      { latex: '\\int \\sec\\theta\\,d\\theta', expr: 'indefinite(sec(theta), theta)' },
      { latex: '\\int 5\\sec\\theta\\,d\\theta', expr: 'indefinite(5*sec(theta), theta)', mistake: 'coefficient-mishandled', why: 'Wrote $\\sqrt{25\\sec^2\\theta} = \\sec\\theta$, losing the 5 that cancels the 5 in $dx$.' },
      { latex: '\\int \\frac{1}{5}\\sec\\theta\\,d\\theta', expr: 'indefinite(sec(theta)/5, theta)', mistake: 'dx-coefficient', why: 'Used $dx = \\sec^2\\theta\\,d\\theta$; with $x = 5\\tan\\theta$ it is $5\\sec^2\\theta\\,d\\theta$.' },
      { latex: '\\int \\frac{1}{5\\sec\\theta}\\,d\\theta', expr: 'indefinite(1/(5*sec(theta)), theta)', mistake: 'dx-not-replaced', why: '$dx$ was renamed $d\\theta$ without its factor $5\\sec^2\\theta$.' },
      { latex: '\\int \\frac{1}{5}\\tan\\theta\\,d\\theta', expr: 'indefinite(tan(theta)/5, theta)', mistake: 'dx-derivative-wrong', why: 'Two slips: used the secant derivative and dropped the 5, $dx = \\sec\\theta\\tan\\theta\\,d\\theta$; it is $5\\sec^2\\theta\\,d\\theta$.' },
      { latex: '\\int \\frac{\\sec^2\\theta}{1+\\tan\\theta}\\,d\\theta', expr: 'indefinite(sec(theta)^2/(1 + tan(theta)), theta)', mistake: 'sqrt-of-sum-split', why: 'Split the root over the sum: $\\sqrt{25 + 25\\tan^2\\theta}$ was written as $5 + 5\\tan\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\sqrt{25 + 25\\tan^2\\theta} = 5\\sec\\theta$ and $dx = 5\\sec^2\\theta\\,d\\theta$, so the integrand is $\\frac{5\\sec^2\\theta}{5\\sec\\theta} = \\sec\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2] },
    check: { kind: 'identity', lhs: 'indefinite(5*sec(theta)^2/sqrt(25 + (5*tan(theta))^2), theta)' },
    difficulty: 1,
    tags: ['rewrite'],
  },

  // ───────────── bounds, θ-intervals and signs ─────────────
  {
    id: 'ts-f-026',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = \\sin\\theta$ this becomes $\\int_a^b \\sin^3\\theta\\,d\\theta$. Find $a$ and $b$.', latex: '\\int_{-1/2}^{\\sqrt{2}/2} \\frac{x^3}{\\sqrt{1-x^2}}\\,dx' },
    options: [
      { latex: 'a = -\\frac{\\pi}{6},\\quad b = \\frac{\\pi}{4}', expr: '[-pi/6, pi/4]' },
      { latex: 'a = -\\frac{1}{2},\\quad b = \\frac{\\sqrt{2}}{2}', expr: '[-1/2, sqrt(2)/2]', mistake: 'bounds-not-converted', why: 'These are the x-limits; a θ-integral needs $\\theta = \\arcsin x$ at each limit.' },
      { latex: 'a = \\frac{2\\pi}{3},\\quad b = \\frac{\\pi}{4}', expr: '[2*pi/3, pi/4]', mistake: 'inverse-function-wrong-arg', why: 'Used arccos: $\\arccos(-\\frac{1}{2}) = \\frac{2\\pi}{3}$; with $x = \\sin\\theta$ the limits come from arcsine.' },
      { latex: 'a = \\frac{7\\pi}{6},\\quad b = \\frac{\\pi}{4}', expr: '[7*pi/6, pi/4]', mistake: 'theta-bounds-wrong', why: '$\\sin\\frac{7\\pi}{6} = -\\frac{1}{2}$, but $\\frac{7\\pi}{6}$ is outside $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, the range of arcsine.' },
      { latex: 'a = -\\frac{\\pi}{3},\\quad b = \\frac{\\pi}{3}', expr: '[-pi/3, pi/3]', mistake: 'theta-bounds-wrong', why: 'Wrong special angles at both limits: $\\sin(\\pm\\frac{\\pi}{3}) = \\pm\\frac{\\sqrt{3}}{2}$, not $-\\frac{1}{2}$ or $\\frac{\\sqrt{2}}{2}$.' },
      { latex: 'a = -\\frac{\\pi}{3},\\quad b = \\frac{\\pi}{4}', expr: '[-pi/3, pi/4]', mistake: 'theta-bounds-wrong', why: '$\\sin(-\\frac{\\pi}{3}) = -\\frac{\\sqrt{3}}{2}$, not $-\\frac{1}{2}$; the angle with sine $-\\frac{1}{2}$ is $-\\frac{\\pi}{6}$.' },
    ],
    correct: 0,
    explanation: '$\\theta = \\arcsin x$: $\\arcsin(-\\frac{1}{2}) = -\\frac{\\pi}{6}$ and $\\arcsin\\frac{\\sqrt{2}}{2} = \\frac{\\pi}{4}$.',
    check: { kind: 'value', expected: '[asin(-1/2), asin(sqrt(2)/2)]' },
    difficulty: 1,
    tags: ['bounds'],
  },
  {
    id: 'ts-f-027',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = 5\\sin\\theta$ this becomes $\\int_a^b 25\\cos^2\\theta\\,d\\theta$. Find $a$ and $b$.', latex: '\\int_{-5}^{5} \\sqrt{25-x^2}\\,dx' },
    options: [
      { latex: 'a = -\\frac{\\pi}{2},\\quad b = \\frac{\\pi}{2}', expr: '[-pi/2, pi/2]' },
      { latex: 'a = -5,\\quad b = 5', expr: '[-5, 5]', mistake: 'bounds-not-converted', why: 'These are the x-limits; the θ-limits are $\\arcsin\\frac{x}{5}$ at $x = \\pm 5$.' },
      { latex: 'a = -1,\\quad b = 1', expr: '[-1, 1]', mistake: 'theta-bounds-wrong', why: 'Stopped at $\\sin\\theta = \\pm 1$; the limits are the angles $\\arcsin(\\pm 1) = \\pm\\frac{\\pi}{2}$.' },
      { latex: 'a = \\pi,\\quad b = 0', expr: '[pi, 0]', mistake: 'inverse-function-wrong-arg', why: 'Used arccos: $\\arccos(-1) = \\pi$ and $\\arccos 1 = 0$; with a sine substitution the limits come from arcsine.' },
      { latex: 'a = \\frac{3\\pi}{2},\\quad b = \\frac{\\pi}{2}', expr: '[3*pi/2, pi/2]', mistake: 'theta-bounds-wrong', why: '$\\sin\\frac{3\\pi}{2} = -1$, but $\\frac{3\\pi}{2}$ is outside $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.' },
      { latex: 'a = \\frac{\\pi}{2},\\quad b = -\\frac{\\pi}{2}', expr: '[pi/2, -pi/2]', mistake: 'bounds-swapped', why: 'The lower limit $x = -5$ gives the lower θ-limit $-\\frac{\\pi}{2}$; the order was reversed.' },
    ],
    correct: 0,
    explanation: '$\\theta = \\arcsin\\frac{x}{5}$: $x = -5 \\Rightarrow \\theta = -\\frac{\\pi}{2}$ and $x = 5 \\Rightarrow \\theta = \\frac{\\pi}{2}$.',
    check: { kind: 'value', expected: '[asin(-5/5), asin(5/5)]' },
    difficulty: 1,
    tags: ['bounds'],
  },
  {
    id: 'ts-f-028',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $2x = 3\\tan\\theta$, the limits $x = 0$ and $x = \\frac{3\\sqrt{3}}{2}$ become $\\theta = a$ and $\\theta = b$. Find $a$ and $b$.', latex: '\\int_{0}^{3\\sqrt{3}/2} \\frac{x^3}{(4x^2+9)^{3/2}}\\,dx' },
    options: [
      { latex: 'a = 0,\\quad b = \\frac{\\pi}{3}', expr: '[0, pi/3]' },
      { latex: 'a = 0,\\quad b = \\frac{3\\sqrt{3}}{2}', expr: '[0, 3*sqrt(3)/2]', mistake: 'bounds-not-converted', why: 'The upper x-limit was kept; the θ-limit is $\\arctan\\frac{2x}{3}$ at that x.' },
      { latex: 'a = 0,\\quad b = \\frac{\\pi}{6}', expr: '[0, pi/6]', mistake: 'inverse-function-wrong-arg', why: 'Inverted the ratio: $\\tan\\theta = \\frac{3}{2x} = \\frac{1}{\\sqrt{3}}$ gives $\\frac{\\pi}{6}$, but the substitution says $\\tan\\theta = \\frac{2x}{3} = \\sqrt{3}$.' },
      { latex: 'a = 0,\\quad b = \\sqrt{3}', expr: '[0, sqrt(3)]', mistake: 'theta-bounds-wrong', why: 'Stopped at $\\tan\\theta = \\sqrt{3}$; the limit is the angle $\\arctan\\sqrt{3} = \\frac{\\pi}{3}$.' },
      { latex: 'a = \\pi,\\quad b = \\frac{\\pi}{3}', expr: '[pi, pi/3]', mistake: 'theta-bounds-wrong', why: '$\\tan\\pi = 0$ too, but θ must lie in $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$, so $x = 0$ gives $\\theta = 0$.' },
      { latex: 'a = 0,\\quad b = \\arctan\\frac{\\sqrt{3}}{2}', expr: '[0, atan(sqrt(3)/2)]', mistake: 'trig-sub-coefficient', why: 'Used $\\tan\\theta = \\frac{x}{3}$, dropping the 2 from $2x = 3\\tan\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\theta = \\arctan\\frac{2x}{3}$: $x = 0 \\Rightarrow \\theta = 0$, and $x = \\frac{3\\sqrt{3}}{2} \\Rightarrow \\tan\\theta = \\sqrt{3}$, so $\\theta = \\frac{\\pi}{3}$.',
    check: { kind: 'value', expected: '[atan(2*0/3), atan(2*(3*sqrt(3)/2)/3)]' },
    difficulty: 2,
    tags: ['bounds'],
  },
  {
    id: 'ts-f-029',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Let $x = 2\\sec\\theta$ with $x < -2$, so $\\frac{\\pi}{2} < \\theta \\le \\pi$. Which simplification is correct?' },
    options: [
      { latex: '\\sqrt{x^2-4} = -2\\tan\\theta', expr: '-2*tan(theta)' },
      { latex: '\\sqrt{x^2-4} = 2\\tan\\theta', expr: '2*tan(theta)', mistake: 'theta-interval-sign', why: 'For $x < -2$, θ lies in $(\\frac{\\pi}{2}, \\pi]$ where $\\tan\\theta \\le 0$, so $2\\tan\\theta$ would be negative; the root is $-2\\tan\\theta$.' },
      { latex: '\\sqrt{x^2-4} = -4\\tan\\theta', expr: '-4*tan(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{4\\tan^2\\theta} = 2|\\tan\\theta|$; the 4 must be rooted too.' },
      { latex: '\\sqrt{x^2-4} = 2\\sec\\theta - 2', expr: '2*sec(theta) - 2', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{4\\sec^2\\theta - 4} \\ne \\sqrt{4\\sec^2\\theta} - \\sqrt{4}$.' },
      { latex: '\\sqrt{x^2-4} = 2\\sin\\theta', expr: '2*sin(theta)', mistake: 'pythagorean-wrong', why: 'Mixed up identities: $\\sec^2\\theta - 1 = \\tan^2\\theta$; it is $1 - \\cos^2\\theta$ that equals $\\sin^2\\theta$.' },
    ],
    correct: 0,
    explanation: '$4\\sec^2\\theta - 4 = 4\\tan^2\\theta$, so the root is $2|\\tan\\theta|$; on $(\\frac{\\pi}{2}, \\pi]$, $\\tan\\theta \\le 0$, so it equals $-2\\tan\\theta$.',
    variable: 'theta',
    domain: { theta: [1.8, 3.0] },
    check: { kind: 'identity', lhs: 'sqrt((2*sec(theta))^2 - 4)' },
    difficulty: 2,
    tags: ['radical', 'sign'],
  },
  {
    id: 'ts-f-030',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = 3\\sin\\theta$ and $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$, what is θ in terms of x?' },
    options: [
      { latex: '\\theta = \\arcsin\\frac{x}{3}', expr: 'asin(x/3)' },
      { latex: '\\theta = \\arcsin\\frac{3}{x}', expr: 'asin(3/x)', mistake: 'inverse-function-wrong-arg', why: 'Inverted the ratio: the substitution says $\\sin\\theta = \\frac{x}{3}$.' },
      { latex: '\\theta = \\arctan\\frac{x}{3}', expr: 'atan(x/3)', mistake: 'inverse-function-wrong-arg', why: 'Arctangent undoes a tangent substitution; here $\\sin\\theta = \\frac{x}{3}$.' },
      { latex: '\\theta = \\arccos\\frac{x}{3}', expr: 'acos(x/3)', mistake: 'inverse-function-wrong-arg', why: 'Arccosine would undo $x = 3\\cos\\theta$; solving $x = 3\\sin\\theta$ needs arcsine.' },
      { latex: '\\theta = \\arctan\\frac{3}{x}', expr: 'atan(3/x)', mistake: 'inverse-function-wrong-arg', why: 'Wrong inverse function, and the ratio is inverted too.' },
      { latex: '\\theta = \\arccos\\frac{3}{x}', expr: 'acos(3/x)', mistake: 'inverse-function-wrong-arg', why: 'This is $\\operatorname{arcsec}\\frac{x}{3}$, which undoes the secant substitution $x = 3\\sec\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\sin\\theta = \\frac{x}{3}$ with θ in the range of arcsine, so $\\theta = \\arcsin\\frac{x}{3}$.',
    domain: { x: [0.5, 2.5] },
    check: { kind: 'value', expected: 'asin(x/3)' },
    difficulty: 1,
    tags: ['inverse'],
  },
  {
    id: 'ts-f-031',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = 4\\sec\\theta$ and $x > 4$, what is θ in terms of x?' },
    options: [
      { latex: '\\theta = \\operatorname{arcsec}\\frac{x}{4}', expr: 'asec(x/4)' },
      { latex: '\\theta = \\operatorname{arcsec}\\frac{4}{x}', expr: 'asec(4/x)', mistake: 'inverse-function-wrong-arg', why: 'Inverted the ratio: the substitution says $\\sec\\theta = \\frac{x}{4}$.' },
      { latex: '\\theta = \\arctan\\frac{4}{x}', expr: 'atan(4/x)', mistake: 'inverse-function-wrong-arg', why: 'Arctangent belongs to a tangent substitution, and the ratio is inverted as well.' },
      { latex: '\\theta = \\arcsin\\frac{4}{x}', expr: 'asin(4/x)', mistake: 'inverse-function-wrong-arg', why: '$\\frac{4}{x}$ is adjacent over hypotenuse, which is $\\cos\\theta$, not $\\sin\\theta$.' },
      { latex: '\\theta = \\arctan\\frac{x}{4}', expr: 'atan(x/4)', mistake: 'inverse-function-wrong-arg', why: 'Arctangent undoes a tangent substitution, not $x = 4\\sec\\theta$.' },
      { latex: '\\theta = \\arcsin\\frac{x}{4}', expr: 'asin(x/4)', mistake: 'inverse-function-wrong-arg', why: 'Arcsine undoes $x = 4\\sin\\theta$, which only covers $|x| \\le 4$.' },
    ],
    correct: 0,
    explanation: '$\\sec\\theta = \\frac{x}{4}$, so $\\theta = \\operatorname{arcsec}\\frac{x}{4}$ (equivalently $\\arccos\\frac{4}{x}$), which lies in $[0, \\frac{\\pi}{2})$ for $x > 4$.',
    domain: { x: [4.5, 8] },
    check: { kind: 'value', expected: 'acos(4/x)' },
    difficulty: 2,
    tags: ['inverse'],
  },
  {
    id: 'ts-f-032',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = 3\\sin\\theta$, why is $\\sqrt{9 - x^2} = 3\\cos\\theta$, with no absolute value?' },
    options: [
      { text: 'Because $\\theta = \\arcsin\\frac{x}{3}$ lies in $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, where $\\cos\\theta \\ge 0$' },
      { text: 'Because the reference triangle has positive sides, so every trig ratio is positive', mistake: 'theta-interval-sign', why: 'Signs come from the θ-interval, not from a triangle; a triangle cannot show a negative x.' },
      { text: 'Because $x \\ge 0$ whenever $\\sqrt{9 - x^2}$ is defined', mistake: 'theta-interval-sign', why: 'x ranges over $[-3, 3]$ and can be negative; the sign argument must use the θ-interval.' },
      { text: 'Because $\\sqrt{u^2} = u$ for every real number $u$', mistake: 'sqrt-square-abs', why: 'False for negative u: $\\sqrt{u^2} = |u|$, so the sign of $\\cos\\theta$ must be checked.' },
      { text: 'Because $\\sin\\theta \\ge 0$ for every θ in $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$', mistake: 'theta-interval-sign', why: 'Sine is negative for $-\\frac{\\pi}{2} \\le \\theta < 0$; it is cosine that is nonnegative there.' },
      { text: 'Because θ lies in $[0, \\pi]$, where $\\cos\\theta \\ge 0$', mistake: 'theta-interval-sign', why: '$[0, \\pi]$ is the range of arccos, and cosine is negative on $(\\frac{\\pi}{2}, \\pi]$.' },
    ],
    correct: 0,
    explanation: '$\\sqrt{9\\cos^2\\theta} = 3|\\cos\\theta|$, and $\\cos\\theta \\ge 0$ on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, the range of arcsine.',
    check: { kind: 'none', reason: 'conceptual justification; options are statements' },
    difficulty: 1,
    tags: ['sign'],
  },
  {
    id: 'ts-f-033',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'For $x = 3\\sec\\theta$ with $x \\le -3$, what is true?' },
    options: [
      { text: '$\\frac{\\pi}{2} < \\theta \\le \\pi$, so $\\tan\\theta \\le 0$ and $\\sqrt{x^2-9} = -3\\tan\\theta$' },
      { text: '$0 \\le \\theta < \\frac{\\pi}{2}$, so $\\tan\\theta \\ge 0$ and $\\sqrt{x^2-9} = 3\\tan\\theta$', mistake: 'theta-interval-sign', why: 'That interval is for $x \\ge 3$; the arcsecant of a number $\\le -1$ lies in $(\\frac{\\pi}{2}, \\pi]$.' },
      { text: '$\\frac{\\pi}{2} < \\theta \\le \\pi$, so $\\tan\\theta \\ge 0$ and $\\sqrt{x^2-9} = 3\\tan\\theta$', mistake: 'theta-interval-sign', why: 'In the second quadrant sine is positive but cosine is negative, so $\\tan\\theta \\le 0$.' },
      { text: '$-\\frac{\\pi}{2} \\le \\theta < 0$, so $\\tan\\theta \\le 0$ and $\\sqrt{x^2-9} = -3\\tan\\theta$', mistake: 'inverse-function-wrong-arg', why: 'Negative angles are what arcsine and arctangent return for negative inputs; the arcsecant of a number $\\le -1$ lies in $(\\frac{\\pi}{2}, \\pi]$.' },
      { text: '$0 \\le \\theta < \\frac{\\pi}{2}$, so $\\tan\\theta \\ge 0$ and $\\sqrt{x^2-9} = -3\\tan\\theta$', mistake: 'theta-interval-sign', why: 'That interval is for $x \\ge 3$, and with $\\tan\\theta \\ge 0$ the value $-3\\tan\\theta$ would be negative, which a square root cannot be.' },
      { text: '$\\frac{\\pi}{2} < \\theta \\le \\pi$, so $\\tan\\theta \\le 0$ and $\\sqrt{x^2-9} = 3\\tan\\theta$', mistake: 'theta-interval-sign', why: 'A square root is never negative, and $3\\tan\\theta \\le 0$ here; the root is $3|\\tan\\theta| = -3\\tan\\theta$.' },
    ],
    correct: 0,
    explanation: 'For $x \\le -3$, $\\theta = \\operatorname{arcsec}\\frac{x}{3} \\in (\\frac{\\pi}{2}, \\pi]$ where $\\tan\\theta \\le 0$, so $\\sqrt{9\\tan^2\\theta} = -3\\tan\\theta$.',
    check: { kind: 'none', reason: 'conceptual statement about θ-intervals and signs; options are statements' },
    difficulty: 2,
    tags: ['sign'],
  },

  // ───────────── back-substitution with the reference triangle ─────────────
  {
    id: 'ts-f-034',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = 2\\tan\\theta$, the reference triangle gives $\\sin\\theta =$' },
    options: [
      { latex: '\\frac{x}{\\sqrt{x^2+4}}', expr: 'x/sqrt(x^2+4)' },
      { latex: '\\frac{2}{\\sqrt{x^2+4}}', expr: '2/sqrt(x^2+4)', mistake: 'triangle-sides-wrong', why: 'That is adjacent over hypotenuse, which is $\\cos\\theta$.' },
      { latex: '\\frac{\\sqrt{x^2+4}}{x}', expr: 'sqrt(x^2+4)/x', mistake: 'triangle-sides-wrong', why: 'That is hypotenuse over opposite, $\\csc\\theta = \\frac{1}{\\sin\\theta}$.' },
      { latex: '\\frac{x}{2}', expr: 'x/2', mistake: 'triangle-sides-wrong', why: 'That is opposite over adjacent, $\\tan\\theta$ itself.' },
      { latex: '\\frac{\\sqrt{x^2+4}}{2}', expr: 'sqrt(x^2+4)/2', mistake: 'triangle-sides-wrong', why: 'That is hypotenuse over adjacent, $\\sec\\theta$.' },
      { latex: '\\frac{x}{x+2}', expr: 'x/(x+2)', mistake: 'sqrt-of-sum-split', why: 'The hypotenuse is $\\sqrt{x^2 + 2^2}$, not $x + 2$: a root does not split over a sum.' },
    ],
    correct: 0,
    explanation: '$\\tan\\theta = \\frac{x}{2}$: opposite $x$, adjacent 2, hypotenuse $\\sqrt{x^2+4}$, so $\\sin\\theta = \\frac{x}{\\sqrt{x^2+4}}$.',
    domain: { x: [0.5, 3] },
    check: { kind: 'identity', lhs: 'sin(atan(x/2))' },
    difficulty: 1,
    tags: ['triangle'],
  },
  {
    id: 'ts-f-035',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = 3\\sin\\theta$ and $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$, the reference triangle gives $\\tan\\theta =$' },
    options: [
      { latex: '\\frac{x}{\\sqrt{9-x^2}}', expr: 'x/sqrt(9-x^2)' },
      { latex: '\\frac{\\sqrt{9-x^2}}{x}', expr: 'sqrt(9-x^2)/x', mistake: 'triangle-sides-wrong', why: 'That is adjacent over opposite, $\\cot\\theta$.' },
      { latex: '\\frac{x}{3}', expr: 'x/3', mistake: 'triangle-sides-wrong', why: 'That is opposite over hypotenuse, $\\sin\\theta$ itself.' },
      { latex: '\\frac{\\sqrt{9-x^2}}{3}', expr: 'sqrt(9-x^2)/3', mistake: 'triangle-sides-wrong', why: 'That is adjacent over hypotenuse, $\\cos\\theta$.' },
      { latex: '\\frac{3}{\\sqrt{9-x^2}}', expr: '3/sqrt(9-x^2)', mistake: 'triangle-sides-wrong', why: 'That is hypotenuse over adjacent, $\\sec\\theta$.' },
      { latex: '\\frac{x}{\\sqrt{x^2+9}}', expr: 'x/sqrt(x^2+9)', mistake: 'triangle-sides-wrong', why: 'With hypotenuse 3 and opposite side x, the adjacent side is $\\sqrt{9 - x^2}$; adding the squares treats 3 as a leg.' },
    ],
    correct: 0,
    explanation: '$\\sin\\theta = \\frac{x}{3}$: opposite $x$, hypotenuse 3, adjacent $\\sqrt{9-x^2}$, so $\\tan\\theta = \\frac{x}{\\sqrt{9-x^2}}$.',
    domain: { x: [0.5, 2.5] },
    check: { kind: 'identity', lhs: 'tan(asin(x/3))' },
    difficulty: 1,
    tags: ['triangle'],
  },
  {
    id: 'ts-f-036',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = \\sqrt{2}\\sec\\theta$ and $x > \\sqrt{2}$, the reference triangle gives $\\sin\\theta =$' },
    options: [
      { latex: '\\frac{\\sqrt{x^2-2}}{x}', expr: 'sqrt(x^2-2)/x' },
      { latex: '\\frac{\\sqrt{2}}{x}', expr: 'sqrt(2)/x', mistake: 'triangle-sides-wrong', why: 'That is adjacent over hypotenuse, $\\cos\\theta$.' },
      { latex: '\\frac{\\sqrt{x^2-2}}{\\sqrt{2}}', expr: 'sqrt(x^2-2)/sqrt(2)', mistake: 'triangle-sides-wrong', why: 'That is opposite over adjacent, $\\tan\\theta$.' },
      { latex: '\\frac{x}{\\sqrt{x^2-2}}', expr: 'x/sqrt(x^2-2)', mistake: 'triangle-sides-wrong', why: 'That is hypotenuse over opposite, $\\csc\\theta$.' },
      { latex: '\\frac{\\sqrt{x^2+2}}{\\sqrt{2}}', expr: 'sqrt(x^2+2)/sqrt(2)', mistake: 'triangle-sides-wrong', why: 'Two slips: used opposite over adjacent ($\\tan\\theta$) instead of opposite over hypotenuse, and took the opposite side as $\\sqrt{x^2 + 2}$ instead of $\\sqrt{x^2 - 2}$.' },
      { latex: '\\frac{x}{\\sqrt{2}}', expr: 'x/sqrt(2)', mistake: 'triangle-sides-wrong', why: 'That is hypotenuse over adjacent, $\\sec\\theta$ itself.' },
    ],
    correct: 0,
    explanation: '$\\sec\\theta = \\frac{x}{\\sqrt{2}}$: hypotenuse $x$, adjacent $\\sqrt{2}$, opposite $\\sqrt{x^2-2}$, so $\\sin\\theta = \\frac{\\sqrt{x^2-2}}{x}$.',
    domain: { x: [1.6, 4] },
    check: { kind: 'identity', lhs: 'sin(asec(x/sqrt(2)))' },
    difficulty: 2,
    tags: ['triangle'],
  },
  {
    id: 'ts-f-037',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = 5\\tan\\theta$, the reference triangle gives $\\cos\\theta =$' },
    options: [
      { latex: '\\frac{5}{\\sqrt{x^2+25}}', expr: '5/sqrt(x^2+25)' },
      { latex: '\\frac{\\sqrt{x^2+25}}{5}', expr: 'sqrt(x^2+25)/5', mistake: 'triangle-sides-wrong', why: 'That is hypotenuse over adjacent, $\\sec\\theta = \\frac{1}{\\cos\\theta}$.' },
      { latex: '\\frac{x}{\\sqrt{x^2+25}}', expr: 'x/sqrt(x^2+25)', mistake: 'triangle-sides-wrong', why: 'That is opposite over hypotenuse, $\\sin\\theta$.' },
      { latex: '\\frac{5}{x}', expr: '5/x', mistake: 'triangle-sides-wrong', why: 'That is adjacent over opposite, $\\cot\\theta$.' },
      { latex: '\\frac{\\sqrt{x^2+25}}{x}', expr: 'sqrt(x^2+25)/x', mistake: 'triangle-sides-wrong', why: 'That is hypotenuse over opposite, $\\csc\\theta$.' },
      { latex: '\\frac{5}{x+5}', expr: '5/(x+5)', mistake: 'sqrt-of-sum-split', why: 'The hypotenuse is $\\sqrt{x^2 + 5^2}$, not $x + 5$: a root does not split over a sum.' },
    ],
    correct: 0,
    explanation: '$\\tan\\theta = \\frac{x}{5}$: opposite $x$, adjacent 5, hypotenuse $\\sqrt{x^2+25}$, so $\\cos\\theta = \\frac{5}{\\sqrt{x^2+25}}$.',
    domain: { x: [0.5, 4] },
    check: { kind: 'identity', lhs: 'cos(atan(x/5))' },
    difficulty: 1,
    tags: ['triangle'],
  },
  {
    id: 'ts-f-038',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = 2\\sec\\theta$ and $x < -2$ (so $\\frac{\\pi}{2} < \\theta \\le \\pi$), $\\tan\\theta$ in terms of x is' },
    options: [
      { latex: '-\\frac{\\sqrt{x^2-4}}{2}', expr: '-sqrt(x^2-4)/2' },
      { latex: '\\frac{\\sqrt{x^2-4}}{2}', expr: 'sqrt(x^2-4)/2', mistake: 'theta-interval-sign', why: 'The triangle gives a positive length, but for $x < -2$, θ is in $(\\frac{\\pi}{2}, \\pi]$ where $\\tan\\theta \\le 0$.' },
      { latex: '-\\frac{2}{\\sqrt{x^2-4}}', expr: '-2/sqrt(x^2-4)', mistake: 'triangle-sides-wrong', why: 'That is adjacent over opposite (with the sign), i.e. $\\cot\\theta$.' },
      { latex: '-\\frac{\\sqrt{x^2-4}}{x}', expr: '-sqrt(x^2-4)/x', mistake: 'triangle-sides-wrong', why: 'That is opposite over hypotenuse, which gives $\\sin\\theta$, not $\\tan\\theta$.' },
      { latex: '-\\frac{\\sqrt{x^2+4}}{2}', expr: '-sqrt(x^2+4)/2', mistake: 'triangle-sides-wrong', why: 'With hypotenuse $|x|$ and adjacent side 2, the opposite side is $\\sqrt{x^2 - 4}$, not $\\sqrt{x^2 + 4}$.' },
    ],
    correct: 0,
    explanation: '$\\tan^2\\theta = \\sec^2\\theta - 1 = \\frac{x^2-4}{4}$ and $\\tan\\theta \\le 0$ on $(\\frac{\\pi}{2}, \\pi]$, so $\\tan\\theta = -\\frac{\\sqrt{x^2-4}}{2}$.',
    domain: { x: [-5, -2.3] },
    check: { kind: 'identity', lhs: 'tan(asec(x/2))' },
    difficulty: 2,
    tags: ['triangle', 'sign'],
  },
  {
    id: 'ts-f-039',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Example 7.2 ends with $-\\frac{1}{4\\sin\\theta} + C$, where $x = 2\\tan\\theta$. In terms of x this is' },
    options: [
      { latex: '-\\frac{\\sqrt{x^2+4}}{4x} + C', expr: '-sqrt(x^2+4)/(4*x) + C' },
      { latex: '-\\frac{x}{4\\sqrt{x^2+4}} + C', expr: '-x/(4*sqrt(x^2+4)) + C', mistake: 'triangle-sides-wrong', why: 'Replaced $\\frac{1}{\\sin\\theta}$ by $\\sin\\theta = \\frac{x}{\\sqrt{x^2+4}}$ instead of its reciprocal.' },
      { latex: '-\\frac{\\sqrt{x^2+4}}{8} + C', expr: '-sqrt(x^2+4)/8 + C', mistake: 'triangle-sides-wrong', why: 'Used $\\sec\\theta = \\frac{\\sqrt{x^2+4}}{2}$ (hypotenuse over adjacent) in place of $\\csc\\theta = \\frac{\\sqrt{x^2+4}}{x}$.' },
      { latex: '-\\frac{1}{4\\sin x} + C', expr: '-1/(4*sin(x)) + C', mistake: 'back-substitution-wrong', why: 'Replaced θ by x; θ is $\\arctan\\frac{x}{2}$, and the triangle expresses $\\sin\\theta$ in x.' },
      { latex: '-\\frac{1}{2x} + C', expr: '-1/(2*x) + C', mistake: 'triangle-sides-wrong', why: 'Used $\\tan\\theta = \\frac{x}{2}$ in place of $\\sin\\theta$.' },
      { latex: '-\\frac{x+2}{8} + C', expr: '-(x+2)/8 + C', mistake: 'sqrt-of-sum-split', why: 'Two slips: took the hypotenuse as $x + 2$ instead of $\\sqrt{x^2+4}$, and used $\\sec\\theta$ (hypotenuse over adjacent) in place of $\\csc\\theta$.' },
    ],
    correct: 0,
    explanation: 'The triangle has opposite $x$, adjacent 2, hypotenuse $\\sqrt{x^2+4}$, so $\\frac{1}{\\sin\\theta} = \\frac{\\sqrt{x^2+4}}{x}$.',
    domain: { x: [0.5, 3] },
    check: { kind: 'identity', lhs: '-1/(4*sin(atan(x/2)))' },
    difficulty: 2,
    tags: ['triangle'],
  },
  {
    id: 'ts-f-040',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $x = \\sqrt{2}\\sec\\theta$ and $x > \\sqrt{2}$, the product $\\sec\\theta\\tan\\theta$ in terms of x is' },
    options: [
      { latex: '\\frac{x\\sqrt{x^2-2}}{2}', expr: 'x*sqrt(x^2-2)/2' },
      { latex: 'x\\sqrt{x^2-2}', expr: 'x*sqrt(x^2-2)', mistake: 'coefficient-mishandled', why: 'Each ratio has the adjacent side $\\sqrt{2}$ in its denominator; $\\sqrt{2}\\cdot\\sqrt{2} = 2$ was dropped.' },
      { latex: '\\frac{x\\sqrt{x^2-2}}{\\sqrt{2}}', expr: 'x*sqrt(x^2-2)/sqrt(2)', mistake: 'coefficient-mishandled', why: 'Divided by $\\sqrt{2}$ only once; $\\sec\\theta$ and $\\tan\\theta$ each carry a $\\sqrt{2}$.' },
      { latex: '\\frac{x^2}{2}', expr: 'x^2/2', mistake: 'triangle-sides-wrong', why: 'Used $\\tan\\theta = \\frac{x}{\\sqrt{2}}$, which is $\\sec\\theta$ (hypotenuse over adjacent).' },
      { latex: '\\frac{x}{\\sqrt{x^2-2}}', expr: 'x/sqrt(x^2-2)', mistake: 'triangle-sides-wrong', why: 'Used adjacent over opposite, $\\frac{\\sqrt{2}}{\\sqrt{x^2-2}}$, for $\\tan\\theta$; that is $\\cot\\theta$.' },
      { latex: '\\frac{x\\sqrt{x^2+2}}{2}', expr: 'x*sqrt(x^2+2)/2', mistake: 'triangle-sides-wrong', why: 'The opposite side is $\\sqrt{x^2 - 2}$ (hypotenuse x, adjacent $\\sqrt{2}$), not $\\sqrt{x^2 + 2}$.' },
    ],
    correct: 0,
    explanation: '$\\sec\\theta = \\frac{x}{\\sqrt{2}}$ and $\\tan\\theta = \\frac{\\sqrt{x^2-2}}{\\sqrt{2}}$, so the product is $\\frac{x\\sqrt{x^2-2}}{2}$.',
    domain: { x: [1.6, 4] },
    check: { kind: 'identity', lhs: 'sec(asec(x/sqrt(2)))*tan(asec(x/sqrt(2)))' },
    difficulty: 2,
    tags: ['triangle'],
  },
  {
    id: 'ts-f-041',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'With $3x = \\sin\\theta$ and $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$, $\\cos\\theta$ in terms of x is' },
    options: [
      { latex: '\\sqrt{1-9x^2}', expr: 'sqrt(1-9*x^2)' },
      { latex: '\\sqrt{1-x^2}', expr: 'sqrt(1-x^2)', mistake: 'triangle-sides-wrong', why: 'The opposite side is $3x$, not x, so the adjacent side is $\\sqrt{1 - (3x)^2}$.' },
      { latex: '3x', expr: '3*x', mistake: 'triangle-sides-wrong', why: 'That is opposite over hypotenuse, $\\sin\\theta$ itself.' },
      { latex: '\\frac{\\sqrt{1-9x^2}}{3}', expr: 'sqrt(1-9*x^2)/3', mistake: 'triangle-sides-wrong', why: 'The hypotenuse is 1, not 3: $\\sin\\theta = \\frac{3x}{1}$.' },
      { latex: '\\frac{3x}{\\sqrt{1-9x^2}}', expr: '3*x/sqrt(1-9*x^2)', mistake: 'triangle-sides-wrong', why: 'That is opposite over adjacent, $\\tan\\theta$.' },
      { latex: '\\sqrt{1+9x^2}', expr: 'sqrt(1+9*x^2)', mistake: 'triangle-sides-wrong', why: 'The hypotenuse is 1 and a leg is $3x$, so the other leg is $\\sqrt{1 - 9x^2}$; the squares were added.' },
    ],
    correct: 0,
    explanation: 'Opposite $3x$, hypotenuse 1, adjacent $\\sqrt{1-9x^2}$; cosine is nonnegative on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, so $\\cos\\theta = \\sqrt{1-9x^2}$.',
    domain: { x: [0.05, 0.3] },
    check: { kind: 'identity', lhs: 'cos(asin(3*x))' },
    difficulty: 1,
    tags: ['triangle'],
  },

  // ───────────── technique: trig sub vs u-sub vs other ─────────────
  {
    id: 'ts-f-042',
    topic: 'trig-sub',
    kind: 'technique',
    prompt: { text: 'Which method is the most efficient?', latex: '\\int \\frac{x}{\\sqrt{x^2+4}}\\,dx' },
    options: [
      { text: 'u-substitution with $u = x^2 + 4$' },
      { text: 'Trig substitution $x = 2\\tan\\theta$', mistake: 'trig-sub-when-usub', why: 'It works but takes several steps; $du = 2x\\,dx$ is already in the integrand, so $u = x^2 + 4$ finishes at once.' },
      { text: 'Trig substitution $x = 2\\sec\\theta$', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 4$; with a sum the radicand does not collapse.' },
      { text: 'Trig substitution $x = 2\\sin\\theta$', mistake: 'trig-sub-wrong-form', why: 'Sine is for $4 - x^2$; with a sum the radicand does not collapse.' },
      { text: 'Integration by parts with $u = x$, $dv = \\frac{dx}{\\sqrt{x^2+4}}$', mistake: 'technique-wrong', why: 'v would need its own trig substitution, and the derivative of $x^2 + 4$ is already present.' },
    ],
    correct: 0,
    explanation: 'The numerator $x\\,dx$ is half of $du$ for $u = x^2 + 4$: $\\frac{1}{2}\\int u^{-1/2}\\,du = \\sqrt{x^2+4} + C$.',
    check: { kind: 'none', reason: 'technique recognition; options are method names' },
    difficulty: 1,
    tags: ['technique'],
  },
  {
    id: 'ts-f-043',
    topic: 'trig-sub',
    kind: 'technique',
    prompt: { text: 'Which method is the most efficient?', latex: '\\int \\frac{1}{x^2\\sqrt{x^2+4}}\\,dx' },
    options: [
      { text: 'Trig substitution $x = 2\\tan\\theta$' },
      { text: 'u-substitution with $u = x^2 + 4$', mistake: 'u-choice-wrong', why: '$du = 2x\\,dx$, but the integrand has no factor x (it has $\\frac{1}{x^2}$), so $du$ cannot be formed.' },
      { text: 'Trig substitution $x = 2\\sec\\theta$', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 4$; with a sum the radicand does not collapse.' },
      { text: 'Trig substitution $x = 2\\sin\\theta$', mistake: 'trig-sub-wrong-form', why: 'Sine is for $4 - x^2$; with a sum the radicand does not collapse.' },
      { text: 'Integration by parts with $u = \\frac{1}{x^2}$, $dv = \\frac{dx}{\\sqrt{x^2+4}}$', mistake: 'technique-wrong', why: 'v is a logarithm that itself needs a trig substitution, and the new integral is harder.' },
    ],
    correct: 0,
    explanation: 'No factor x is available for $u = x^2 + 4$; the sum $x^2 + 2^2$ calls for $x = 2\\tan\\theta$ (Example 7.2).',
    check: { kind: 'none', reason: 'technique recognition; options are method names' },
    difficulty: 1,
    tags: ['technique'],
  },
  {
    id: 'ts-f-044',
    topic: 'trig-sub',
    kind: 'technique',
    prompt: { text: 'Which method is the most efficient?', latex: '\\int x\\sqrt{9-x^2}\\,dx' },
    options: [
      { text: 'u-substitution with $u = 9 - x^2$' },
      { text: 'Trig substitution $x = 3\\sin\\theta$', mistake: 'trig-sub-when-usub', why: 'It works but is longer; $du = -2x\\,dx$ is already present, so $-\\frac{1}{2}\\int\\sqrt{u}\\,du$ finishes in one line.' },
      { text: 'Trig substitution $x = 3\\tan\\theta$', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $x^2 + 9$; with a difference the radicand does not collapse.' },
      { text: 'Trig substitution $x = 3\\sec\\theta$', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 9$; here it would give $-9\\tan^2\\theta$ under the root.' },
      { text: 'Integration by parts with $u = x$, $dv = \\sqrt{9-x^2}\\,dx$', mistake: 'technique-wrong', why: 'Finding v already needs a trig substitution; the factor x is the derivative of the inside up to a constant.' },
    ],
    correct: 0,
    explanation: 'With $u = 9 - x^2$, $x\\,dx = -\\frac{1}{2}du$, so the integral is $-\\frac{1}{3}(9-x^2)^{3/2} + C$.',
    check: { kind: 'none', reason: 'technique recognition; options are method names' },
    difficulty: 1,
    tags: ['technique'],
  },
  {
    id: 'ts-f-045',
    topic: 'trig-sub',
    kind: 'technique',
    prompt: { text: 'Which method is the most efficient?', latex: '\\int \\frac{x^2}{\\sqrt{9-x^2}}\\,dx' },
    options: [
      { text: 'Trig substitution $x = 3\\sin\\theta$' },
      { text: 'u-substitution with $u = 9 - x^2$', mistake: 'u-choice-wrong', why: '$du = -2x\\,dx$, but the numerator is $x^2$, not x; an extra x would remain.' },
      { text: 'Trig substitution $x = 3\\tan\\theta$', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $x^2 + 9$; with a difference the radicand does not collapse.' },
      { text: 'Trig substitution $x = 3\\sec\\theta$', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - 9$; here it would give $-9\\tan^2\\theta$ under the root.' },
      { text: 'Integration by parts with $u = x^2$, $dv = \\frac{dx}{\\sqrt{9-x^2}}$', mistake: 'technique-wrong', why: 'Then $v = \\arcsin\\frac{x}{3}$ and the new integral $\\int 2x\\arcsin\\frac{x}{3}\\,dx$ is harder.' },
    ],
    correct: 0,
    explanation: '$9 - x^2$ is a difference $b^2 - x^2$ and no factor x matches $du$, so $x = 3\\sin\\theta$ gives $\\int 9\\sin^2\\theta\\,d\\theta$.',
    check: { kind: 'none', reason: 'technique recognition; options are method names' },
    difficulty: 1,
    tags: ['technique'],
  },
  {
    id: 'ts-f-046',
    topic: 'trig-sub',
    kind: 'technique',
    prompt: { text: 'Which method is the most efficient (for $x > 4$)?', latex: '\\int \\frac{1}{x^2\\sqrt{x^2-16}}\\,dx' },
    options: [
      { text: 'Trig substitution $x = 4\\sec\\theta$' },
      { text: 'u-substitution with $u = x^2 - 16$', mistake: 'u-choice-wrong', why: '$du = 2x\\,dx$, but the integrand has $\\frac{1}{x^2}$ and no factor x, so $du$ cannot be formed.' },
      { text: 'Trig substitution $x = 4\\sin\\theta$', mistake: 'trig-sub-wrong-form', why: 'Sine is for $16 - x^2$; here $16\\sin^2\\theta - 16 = -16\\cos^2\\theta$ is negative under the root.' },
      { text: 'Trig substitution $x = 4\\tan\\theta$', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $x^2 + 16$; $16\\tan^2\\theta - 16$ does not collapse.' },
      { text: 'Integration by parts with $u = \\frac{1}{x^2}$, $dv = \\frac{dx}{\\sqrt{x^2-16}}$', mistake: 'technique-wrong', why: 'v is a logarithm that itself needs a trig substitution, and the new integral is harder.' },
    ],
    correct: 0,
    explanation: '$x^2 - 16 = x^2 - 4^2$ with no factor x available for a u-substitution, so $x = 4\\sec\\theta$ gives $\\sqrt{x^2-16} = 4\\tan\\theta$.',
    check: { kind: 'none', reason: 'technique recognition; options are method names' },
    difficulty: 2,
    tags: ['technique'],
  },
  {
    id: 'ts-f-047',
    topic: 'trig-sub',
    kind: 'technique',
    prompt: { text: 'Which method is the most efficient (for $x > 4$)?', latex: '\\int \\frac{x}{(x^2-16)^{3/2}}\\,dx' },
    options: [
      { text: 'u-substitution with $u = x^2 - 16$' },
      { text: 'Trig substitution $x = 4\\sec\\theta$', mistake: 'trig-sub-when-usub', why: 'It works but is longer; $du = 2x\\,dx$ is already present, so $\\frac{1}{2}\\int u^{-3/2}\\,du$ finishes at once.' },
      { text: 'Trig substitution $x = 4\\sin\\theta$', mistake: 'trig-sub-wrong-form', why: 'Sine is for $16 - x^2$; here the radicand would be negative.' },
      { text: 'Trig substitution $x = 4\\tan\\theta$', mistake: 'trig-sub-wrong-form', why: 'Tangent is for $x^2 + 16$; $16\\tan^2\\theta - 16$ does not collapse.' },
      { text: 'Integration by parts with $u = x$, $dv = (x^2-16)^{-3/2}\\,dx$', mistake: 'technique-wrong', why: 'Finding v needs a trig substitution, while the factor x already matches $du$.' },
    ],
    correct: 0,
    explanation: 'With $u = x^2 - 16$, $x\\,dx = \\frac{1}{2}du$: $\\frac{1}{2}\\int u^{-3/2}\\,du = -\\frac{1}{\\sqrt{x^2-16}} + C$.',
    check: { kind: 'none', reason: 'technique recognition; options are method names' },
    difficulty: 2,
    tags: ['technique'],
  },
  {
    id: 'ts-f-048',
    topic: 'trig-sub',
    kind: 'technique',
    prompt: { text: 'After $x = 5\\sin\\theta$, the integral $\\int\\sqrt{25 - x^2}\\,dx$ becomes $\\int 25\\cos^2\\theta\\,d\\theta$. How should this be integrated?' },
    options: [
      { text: 'Use the half-angle identity $\\cos^2\\theta = \\frac{1 + \\cos 2\\theta}{2}$' },
      { text: 'Substitute $u = \\cos\\theta$', mistake: 'even-powers-no-identity', why: '$du = -\\sin\\theta\\,d\\theta$ is not present; an even power of cosine alone needs the half-angle identity.' },
      { text: 'Substitute $u = \\sin\\theta$', mistake: 'even-powers-no-identity', why: 'Saving $\\cos\\theta\\,d\\theta = du$ leaves $\\cos\\theta = \\sqrt{1-u^2}$, which just undoes the trig substitution.' },
      { text: 'Power rule: $\\int 25\\cos^2\\theta\\,d\\theta = \\frac{25\\cos^3\\theta}{3} + C$', mistake: 'u-choice-wrong', why: 'The power rule needs the factor $d(\\cos\\theta) = -\\sin\\theta\\,d\\theta$, which is missing.' },
      { text: 'Rewrite $\\cos^2\\theta = 1 - \\sin^2\\theta$ and integrate term by term', mistake: 'technique-wrong', why: 'This trades $\\cos^2\\theta$ for $\\sin^2\\theta$, which has exactly the same difficulty.' },
    ],
    correct: 0,
    explanation: 'Even powers of sine and cosine are lowered with the half-angle identities: $25\\int\\frac{1+\\cos 2\\theta}{2}\\,d\\theta$.',
    check: { kind: 'none', reason: 'technique recognition; options are methods' },
    difficulty: 1,
    tags: ['technique'],
  },

  // ───────────── full answers ─────────────
  {
    id: 'ts-f-049',
    topic: 'trig-sub',
    kind: 'evaluate',
    prompt: { latex: '\\int_{-5}^{5} \\sqrt{25-x^2}\\,dx' },
    options: [
      { latex: '\\frac{25\\pi}{2}', expr: '25*pi/2' },
      { latex: '25\\pi', expr: '25*pi', mistake: 'half-angle-wrong', why: 'Used $\\cos^2\\theta = 1 + \\cos 2\\theta$ without the factor $\\frac{1}{2}$, doubling the result.' },
      { latex: '\\frac{125\\pi}{2}', expr: '125*pi/2', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{25\\cos^2\\theta} = 25\\cos\\theta$, giving $125\\int\\cos^2\\theta\\,d\\theta$.' },
      { latex: '\\frac{5\\pi}{2}', expr: '5*pi/2', mistake: 'dx-coefficient', why: 'Used $dx = \\cos\\theta\\,d\\theta$ (missing the 5), giving $5\\int\\cos^2\\theta\\,d\\theta$.' },
      { latex: '-\\frac{25\\pi}{2}', expr: '-25*pi/2', mistake: 'bounds-swapped', why: 'The θ-limits were reversed: $x = -5$ gives the lower limit $\\theta = -\\frac{\\pi}{2}$.' },
      { latex: '\\frac{25\\pi}{4}', expr: '25*pi/4', mistake: 'ftc-not-subtracted', why: 'Only $F(\\frac{\\pi}{2}) = \\frac{25\\pi}{4}$ was computed; $F(-\\frac{\\pi}{2}) = -\\frac{25\\pi}{4}$ must be subtracted.' },
    ],
    correct: 0,
    explanation: 'With $x = 5\\sin\\theta$: $\\int_{-\\pi/2}^{\\pi/2} 25\\cos^2\\theta\\,d\\theta = \\frac{25}{2}\\left[\\theta + \\sin\\theta\\cos\\theta\\right]_{-\\pi/2}^{\\pi/2} = \\frac{25\\pi}{2}$ (half of a disk of radius 5).',
    check: { kind: 'definite-integral', integrand: 'sqrt(25 - x^2)', lower: '-5', upper: '5' },
    difficulty: 1,
    tags: ['final'],
  },
  {
    id: 'ts-f-050',
    topic: 'trig-sub',
    kind: 'evaluate',
    prompt: { latex: '\\int_{0}^{3/2} \\frac{8}{(x^2+1)^2}\\,dx' },
    options: [
      { latex: '4\\arctan\\frac{3}{2} + \\frac{24}{13}', expr: '4*atan(3/2) + 24/13' },
      { latex: '4\\arctan\\frac{3}{2} + \\frac{12}{13}', expr: '4*atan(3/2) + 12/13', mistake: 'double-angle-wrong', why: 'Used $\\sin 2\\theta = \\sin\\theta\\cos\\theta$ (missing the 2); with $\\tan\\theta = \\frac{3}{2}$, $\\sin 2\\theta = \\frac{12}{13}$.' },
      { latex: '6 + 2\\sin 3', expr: '6 + 2*sin(3)', mistake: 'bounds-not-converted', why: 'Plugged the x-limits 0 and $\\frac{3}{2}$ into $4\\theta + 2\\sin 2\\theta$; the θ-limits are 0 and $\\arctan\\frac{3}{2}$.' },
      { latex: '8\\arctan\\frac{3}{2} + \\frac{48}{13}', expr: '8*atan(3/2) + 48/13', mistake: 'half-angle-wrong', why: 'Used $\\cos^2\\theta = 1 + \\cos 2\\theta$ without the factor $\\frac{1}{2}$, doubling the result.' },
      { latex: '4\\arctan\\frac{3}{2} - \\frac{24}{13}', expr: '4*atan(3/2) - 24/13', mistake: 'half-angle-wrong', why: 'Used the sine version $\\frac{1 - \\cos 2\\theta}{2}$ for $\\cos^2\\theta$.' },
      { latex: '6 + \\frac{24}{13}', expr: '6 + 24/13', mistake: 'theta-bounds-wrong', why: 'Replaced $\\theta = \\arctan\\frac{3}{2}$ by $\\tan\\theta = \\frac{3}{2}$ in the $4\\theta$ term.' },
    ],
    correct: 0,
    explanation: 'With $x = \\tan\\theta$: $\\int_0^{\\arctan(3/2)} 8\\cos^2\\theta\\,d\\theta = \\left[4\\theta + 2\\sin 2\\theta\\right]_0^{\\arctan(3/2)} = 4\\arctan\\frac{3}{2} + \\frac{24}{13}$.',
    check: { kind: 'definite-integral', integrand: '8/(x^2+1)^2', lower: '0', upper: '3/2' },
    difficulty: 2,
    tags: ['final'],
  },
  {
    id: 'ts-f-051',
    topic: 'trig-sub',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{1}{\\sqrt{25+x^2}}' },
    options: [
      { latex: '\\ln|x + \\sqrt{x^2+25}| + C', expr: 'log(abs(x + sqrt(x^2+25)))' },
      { latex: '\\frac{1}{5}\\ln|x + \\sqrt{x^2+25}| + C', expr: 'log(abs(x + sqrt(x^2+25)))/5', mistake: 'dx-coefficient', why: 'Used $dx = \\sec^2\\theta\\,d\\theta$ (missing the 5), which leaves $\\frac{1}{5}\\int\\sec\\theta\\,d\\theta$.' },
      { latex: '\\ln|\\sqrt{x^2+25}| + C', expr: 'log(abs(sqrt(x^2+25)))', mistake: 'sec-antiderivative-wrong', why: 'Used $\\int\\sec\\theta\\,d\\theta = \\ln|\\sec\\theta|$; the $\\tan\\theta$ term is missing.' },
      { latex: '\\ln|\\sqrt{x^2+25} - x| + C', expr: 'log(abs(sqrt(x^2+25) - x))', mistake: 'sec-antiderivative-wrong', why: 'Used $\\ln|\\sec\\theta - \\tan\\theta|$; the antiderivative is $\\ln|\\sec\\theta + \\tan\\theta|$.' },
      { latex: '\\arctan\\frac{x}{5} + C', expr: 'atan(x/5)', mistake: 'formula-swapped', why: 'That pattern belongs to $\\int\\frac{dx}{x^2+25}$ (up to a factor); here the denominator is a square root.' },
      { latex: '\\ln|\\sqrt{x^2+5} - x| + C', expr: 'log(abs(sqrt(x^2+5) - x))', mistake: 'triangle-sides-wrong', why: 'Two slips: the hypotenuse is $\\sqrt{x^2+25}$, not $\\sqrt{x^2+5}$, and $\\int\\sec\\theta\\,d\\theta = \\ln|\\sec\\theta + \\tan\\theta|$, not $\\ln|\\sec\\theta - \\tan\\theta|$.' },
    ],
    correct: 0,
    explanation: '$x = 5\\tan\\theta$ gives $\\int\\sec\\theta\\,d\\theta = \\ln\\left|\\frac{\\sqrt{x^2+25}}{5} + \\frac{x}{5}\\right| + C$, which differs from $\\ln|x + \\sqrt{x^2+25}|$ only by the constant $\\ln 5$.',
    domain: { x: [0.5, 3] },
    check: { kind: 'antiderivative', integrand: '1/sqrt(25+x^2)' },
    difficulty: 1,
    tags: ['final'],
  },
  {
    id: 'ts-f-052',
    topic: 'trig-sub',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{1}{x^2\\sqrt{x^2+4}}' },
    options: [
      { latex: '-\\frac{\\sqrt{x^2+4}}{4x} + C', expr: '-sqrt(x^2+4)/(4*x)' },
      { latex: '-\\frac{x}{4\\sqrt{x^2+4}} + C', expr: '-x/(4*sqrt(x^2+4))', mistake: 'triangle-sides-wrong', why: 'Back-substituted $\\frac{1}{\\sin\\theta}$ as $\\sin\\theta = \\frac{x}{\\sqrt{x^2+4}}$ instead of its reciprocal.' },
      { latex: '\\frac{\\sqrt{x^2+4}}{8x} + C', expr: 'sqrt(x^2+4)/(8*x)', mistake: 'sign-error', why: 'Two slips: the minus sign of $\\int u^{-2}\\,du = -u^{-1}$ was lost, and $\\sqrt{x^2+4} = 4\\sec\\theta$ (unrooted 4) halved the constant.' },
      { latex: '-\\frac{\\sqrt{x^2+4}}{8x} + C', expr: '-sqrt(x^2+4)/(8*x)', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{x^2+4} = 4\\sec\\theta$, which halves the constant in front.' },
      { latex: '-\\frac{\\sqrt{x^2+4}}{2x} + C', expr: '-sqrt(x^2+4)/(2*x)', mistake: 'coefficient-mishandled', why: 'Wrote $x^2 = 2\\tan^2\\theta$; squaring $2\\tan\\theta$ gives $4\\tan^2\\theta$.' },
      { latex: '-\\frac{\\sqrt{x^2+4}}{8} + C', expr: '-sqrt(x^2+4)/8', mistake: 'triangle-sides-wrong', why: 'Used $\\sec\\theta = \\frac{\\sqrt{x^2+4}}{2}$ in place of $\\csc\\theta = \\frac{\\sqrt{x^2+4}}{x}$.' },
    ],
    correct: 0,
    explanation: '$x = 2\\tan\\theta$ gives $\\frac{1}{4}\\int\\frac{\\cos\\theta}{\\sin^2\\theta}\\,d\\theta = -\\frac{1}{4\\sin\\theta} + C$, and $\\sin\\theta = \\frac{x}{\\sqrt{x^2+4}}$.',
    domain: { x: [0.5, 3] },
    check: { kind: 'antiderivative', integrand: '1/(x^2*sqrt(x^2+4))' },
    difficulty: 2,
    tags: ['final'],
  },
  {
    id: 'ts-f-053',
    topic: 'trig-sub',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{\\sqrt{9-x^2}}{x^2}' },
    options: [
      { latex: '-\\frac{\\sqrt{9-x^2}}{x} - \\arcsin\\frac{x}{3} + C', expr: '-sqrt(9-x^2)/x - asin(x/3)' },
      { latex: '-\\frac{\\sqrt{9-x^2}}{x} + \\arcsin\\frac{x}{3} + C', expr: '-sqrt(9-x^2)/x + asin(x/3)', mistake: 'pythagorean-wrong', why: 'Used $\\cot^2\\theta = \\csc^2\\theta + 1$; the identity is $\\cot^2\\theta = \\csc^2\\theta - 1$.' },
      { latex: '\\frac{\\sqrt{9-x^2}}{x} - \\arcsin\\frac{x}{3} + C', expr: 'sqrt(9-x^2)/x - asin(x/3)', mistake: 'trig-antiderivative-sign', why: '$\\int\\csc^2\\theta\\,d\\theta = -\\cot\\theta$; the minus sign was dropped.' },
      { latex: '\\frac{\\sqrt{9-x^2}}{x} + \\arcsin\\frac{x}{3} + C', expr: 'sqrt(9-x^2)/x + asin(x/3)', mistake: 'theta-interval-sign', why: 'Took $\\sqrt{9-x^2} = -3\\cos\\theta$, which negates the whole integral; cosine is nonnegative on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$.' },
      { latex: '-\\frac{x}{\\sqrt{9-x^2}} - \\arcsin\\frac{x}{3} + C', expr: '-x/sqrt(9-x^2) - asin(x/3)', mistake: 'triangle-sides-wrong', why: 'Back-substituted $\\cot\\theta$ as opposite over adjacent, which is $\\tan\\theta$.' },
      { latex: '-\\frac{\\sqrt{9-x^2}}{x} - \\frac{x}{3} + C', expr: '-sqrt(9-x^2)/x - x/3', mistake: 'inverse-function-wrong-arg', why: 'Replaced θ by $\\sin\\theta = \\frac{x}{3}$; θ itself is $\\arcsin\\frac{x}{3}$.' },
    ],
    correct: 0,
    explanation: '$x = 3\\sin\\theta$ gives $\\int\\cot^2\\theta\\,d\\theta = \\int(\\csc^2\\theta - 1)\\,d\\theta = -\\cot\\theta - \\theta + C$, with $\\cot\\theta = \\frac{\\sqrt{9-x^2}}{x}$, $\\theta = \\arcsin\\frac{x}{3}$.',
    domain: { x: [0.5, 2.5] },
    check: { kind: 'antiderivative', integrand: 'sqrt(9-x^2)/x^2' },
    difficulty: 2,
    tags: ['final'],
  },
  {
    id: 'ts-f-054',
    topic: 'trig-sub',
    kind: 'antiderivative',
    prompt: { text: 'Assume $x > \\frac{3}{5}$.', latex: '\\frac{5}{\\sqrt{25x^2-9}}' },
    options: [
      { latex: '\\ln|5x + \\sqrt{25x^2-9}| + C', expr: 'log(abs(5*x + sqrt(25*x^2-9)))' },
      { latex: '5\\ln|5x + \\sqrt{25x^2-9}| + C', expr: '5*log(abs(5*x + sqrt(25*x^2-9)))', mistake: 'dx-coefficient', why: 'Used $dx = 3\\sec\\theta\\tan\\theta\\,d\\theta$; the 5 in $5x = 3\\sec\\theta$ must be divided out.' },
      { latex: '\\frac{5}{3}\\ln|5x + \\sqrt{25x^2-9}| + C', expr: '5/3*log(abs(5*x + sqrt(25*x^2-9)))', mistake: 'dx-coefficient', why: 'Used $dx = \\sec\\theta\\tan\\theta\\,d\\theta$, dropping the factor $\\frac{b}{a} = \\frac{3}{5}$.' },
      { latex: '\\frac{1}{3}\\ln|5x + \\sqrt{25x^2-9}| + C', expr: 'log(abs(5*x + sqrt(25*x^2-9)))/3', mistake: 'sqrt-constant-not-rooted', why: 'Used $\\sqrt{9\\tan^2\\theta} = 9\\tan\\theta$; the root is $3\\tan\\theta$.' },
      { latex: '\\ln|5x - \\sqrt{25x^2-9}| + C', expr: 'log(abs(5*x - sqrt(25*x^2-9)))', mistake: 'sec-antiderivative-wrong', why: 'Used $\\ln|\\sec\\theta - \\tan\\theta|$; the antiderivative of $\\sec\\theta$ is $\\ln|\\sec\\theta + \\tan\\theta|$.' },
      { latex: '\\ln|5x + \\sqrt{25x^2+9}| + C', expr: 'log(abs(5*x + sqrt(25*x^2+9)))', mistake: 'triangle-sides-wrong', why: 'With hypotenuse $5x$ and adjacent side 3, the opposite side is $\\sqrt{25x^2 - 9}$.' },
    ],
    correct: 0,
    explanation: '$5x = 3\\sec\\theta$ gives $\\int\\sec\\theta\\,d\\theta = \\ln\\left|\\frac{5x}{3} + \\frac{\\sqrt{25x^2-9}}{3}\\right| + C$, which equals $\\ln|5x + \\sqrt{25x^2-9}|$ up to the constant $\\ln 3$.',
    domain: { x: [0.7, 2] },
    check: { kind: 'antiderivative', integrand: '5/sqrt(25*x^2-9)' },
    difficulty: 2,
    tags: ['final'],
  },
  {
    id: 'ts-f-055',
    topic: 'trig-sub',
    kind: 'antiderivative',
    prompt: { text: 'Assume $x > 1$.', latex: '\\frac{2}{x^3\\sqrt{x^2-1}}' },
    options: [
      { latex: '\\operatorname{arcsec} x + \\frac{\\sqrt{x^2-1}}{x^2} + C', expr: 'asec(x) + sqrt(x^2-1)/x^2' },
      { latex: '\\operatorname{arcsec} x - \\frac{\\sqrt{x^2-1}}{x^2} + C', expr: 'asec(x) - sqrt(x^2-1)/x^2', mistake: 'half-angle-wrong', why: 'Used $\\cos^2\\theta = \\frac{1 - \\cos 2\\theta}{2}$ (the sine version), giving $\\theta - \\sin\\theta\\cos\\theta$.' },
      { latex: '\\operatorname{arcsec} x + \\sqrt{x^2-1} + C', expr: 'asec(x) + sqrt(x^2-1)', mistake: 'triangle-sides-wrong', why: 'Used $\\cos\\theta = x$ (that is $\\sec\\theta$); cosine is adjacent over hypotenuse, $\\frac{1}{x}$.' },
      { latex: '\\operatorname{arcsec} x + \\frac{\\sqrt{x^2-1}}{2x^2} + C', expr: 'asec(x) + sqrt(x^2-1)/(2*x^2)', mistake: 'double-angle-wrong', why: 'Used $\\sin 2\\theta = \\sin\\theta\\cos\\theta$ (missing the 2) when back-substituting $\\frac{1}{2}\\sin 2\\theta$.' },
      { latex: '2\\operatorname{arcsec} x + \\frac{2\\sqrt{x^2-1}}{x^2} + C', expr: '2*asec(x) + 2*sqrt(x^2-1)/x^2', mistake: 'half-angle-wrong', why: 'Used $\\cos^2\\theta = 1 + \\cos 2\\theta$ without the factor $\\frac{1}{2}$, doubling the result.' },
      { latex: '\\arctan x + \\frac{\\sqrt{x^2-1}}{x^2} + C', expr: 'atan(x) + sqrt(x^2-1)/x^2', mistake: 'inverse-function-wrong-arg', why: 'With $x = \\sec\\theta$, $\\theta = \\operatorname{arcsec} x$; arctangent belongs to a tangent substitution.' },
    ],
    correct: 0,
    explanation: '$x = \\sec\\theta$ gives $\\int 2\\cos^2\\theta\\,d\\theta = \\theta + \\sin\\theta\\cos\\theta + C$, with $\\sin\\theta = \\frac{\\sqrt{x^2-1}}{x}$ and $\\cos\\theta = \\frac{1}{x}$.',
    domain: { x: [1.2, 3] },
    check: { kind: 'antiderivative', integrand: '2/(x^3*sqrt(x^2-1))' },
    difficulty: 2,
    tags: ['final'],
  },
  {
    id: 'ts-f-056',
    topic: 'trig-sub',
    kind: 'antiderivative',
    prompt: { latex: '\\frac{8}{x^2\\sqrt{4-x^2}}' },
    options: [
      { latex: '-\\frac{2\\sqrt{4-x^2}}{x} + C', expr: '-2*sqrt(4-x^2)/x' },
      { latex: '\\frac{2\\sqrt{4-x^2}}{x} + C', expr: '2*sqrt(4-x^2)/x', mistake: 'trig-antiderivative-sign', why: '$\\int\\csc^2\\theta\\,d\\theta = -\\cot\\theta$; the minus sign was dropped.' },
      { latex: '-\\frac{2x}{\\sqrt{4-x^2}} + C', expr: '-2*x/sqrt(4-x^2)', mistake: 'triangle-sides-wrong', why: 'Back-substituted $\\cot\\theta$ as opposite over adjacent, which is $\\tan\\theta$.' },
      { latex: '-\\frac{\\sqrt{4-x^2}}{x} + C', expr: '-sqrt(4-x^2)/x', mistake: 'dx-coefficient', why: 'Used $dx = \\cos\\theta\\,d\\theta$ (missing the 2), which leaves $\\int\\csc^2\\theta\\,d\\theta$.' },
      { latex: '-\\frac{4\\sqrt{4-x^2}}{x} + C', expr: '-4*sqrt(4-x^2)/x', mistake: 'coefficient-mishandled', why: 'Wrote $x^2 = 2\\sin^2\\theta$; squaring $2\\sin\\theta$ gives $4\\sin^2\\theta$.' },
    ],
    correct: 0,
    explanation: '$x = 2\\sin\\theta$ gives $\\int 2\\csc^2\\theta\\,d\\theta = -2\\cot\\theta + C$, and $\\cot\\theta = \\frac{\\sqrt{4-x^2}}{x}$.',
    domain: { x: [0.5, 1.8] },
    check: { kind: 'antiderivative', integrand: '8/(x^2*sqrt(4-x^2))' },
    difficulty: 1,
    tags: ['final'],
  },
];

/** Parameterized generators (optional; none for this topic). */
export const generators: FlashGenerator[] = [];
