import type { FlashGenerator, FlashItem } from '../types';

/**
 * Flash Drill items for topic "trig-sub" (Lecture 7, §3.3). Authored by content-author; verified by
 * math-verifier.
 *
 * Course conventions: ax = b sin θ, ax = b tan θ, ax = b sec θ with dx = (b/a)(…) dθ.
 * Sine: θ ∈ [−π/2, π/2], cos θ ≥ 0. Tangent: θ ∈ (−π/2, π/2), sec θ > 0.
 * Secant: θ ∈ [0, π/2) ∪ (π/2, π]; tan θ ≥ 0 when x ≥ b/a, tan θ ≤ 0 when x ≤ −b/a.
 * Rewriting items check the θ-integrand against f(x(θ))·x′(θ) computed mechanically; triangle items
 * check against the exact trig value, e.g. sin(arctan(x/2)).
 */
export const flash: FlashItem[] = [
  // ───────────── choosing the substitution ─────────────
  {
    id: 'ts-f-001',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Which trigonometric substitution fits this integral?', latex: '\\int \\frac{1}{\\sqrt{25 + x^2}}\\,dx' },
    options: [
      { latex: 'x = 5\\tan\\theta' },
      { latex: 'x = 5\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for a difference $b^2 - (ax)^2$; here $25 + 25\\sin^2\\theta$ is not a single square, so the root stays.' },
      { latex: 'x = 5\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$; $25 + 25\\sec^2\\theta$ does not collapse to one square.' },
      { latex: '5x = \\tan\\theta', mistake: 'trig-sub-coefficient', why: 'The 5 is on the wrong side: $x = \\frac{1}{5}\\tan\\theta$ gives $25 + \\frac{1}{25}\\tan^2\\theta$, which is not a multiple of $1 + \\tan^2\\theta$.' },
      { latex: '5x = \\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for a difference, not a sum (and the 5 belongs with θ): $25 + \\frac{1}{25}\\sin^2\\theta$ has no identity that collapses it.' },
      { latex: '5x = \\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$, not a sum (and the 5 belongs with θ), so the radicand stays unsimplified.' },
    ],
    correct: 0,
    explanation: 'A sum $x^2 + 5^2$ calls for $x = 5\\tan\\theta$: $25 + 25\\tan^2\\theta = 25\\sec^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 1,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-002',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Which trigonometric substitution fits this integral?', latex: '\\int \\frac{\\sqrt{9 - x^2}}{x^2}\\,dx' },
    options: [
      { latex: 'x = 3\\sin\\theta' },
      { latex: 'x = 3\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for a sum $b^2 + (ax)^2$; $9 - 9\\tan^2\\theta$ is not a Pythagorean square.' },
      { latex: 'x = 3\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - b^2$; $9 - 9\\sec^2\\theta = -9\\tan^2\\theta$ is negative under the root.' },
      { latex: 'x = 9\\sin\\theta', mistake: 'trig-sub-coefficient', why: 'b is the square root of 9: $x = 9\\sin\\theta$ gives $9 - 81\\sin^2\\theta$, which does not factor as $9(1 - \\sin^2\\theta)$.' },
      { latex: 'x = 9\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums, and the coefficient should be $\\sqrt{9} = 3$, not 9.' },
      { latex: 'x = 9\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $x^2 - b^2$, and the coefficient should be $\\sqrt{9} = 3$, not 9.' },
    ],
    correct: 0,
    explanation: '$9 - x^2 = 3^2 - x^2$ is a difference $b^2 - x^2$, so $x = 3\\sin\\theta$ gives $9 - 9\\sin^2\\theta = 9\\cos^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 1,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-003',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Which trigonometric substitution fits this integral (with $x > \\sqrt{2}$)?', latex: '\\int \\frac{x^2}{\\sqrt{x^2 - 2}}\\,dx' },
    options: [
      { latex: 'x = \\sqrt{2}\\sec\\theta' },
      { latex: 'x = \\sqrt{2}\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $b^2 - x^2$; $2\\sin^2\\theta - 2 = -2\\cos^2\\theta$ is negative under the root.' },
      { latex: 'x = \\sqrt{2}\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums; $2\\tan^2\\theta - 2$ is not a Pythagorean square.' },
      { latex: 'x = 2\\sec\\theta', mistake: 'trig-sub-coefficient', why: '$b^2 = 2$ means $b = \\sqrt{2}$; $x = 2\\sec\\theta$ gives $4\\sec^2\\theta - 2$, which does not factor as $2(\\sec^2\\theta - 1)$.' },
      { latex: 'x = 2\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $b^2 - x^2$, and the coefficient should be $\\sqrt{2}$, not 2.' },
      { latex: 'x = 2\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums, and the coefficient should be $\\sqrt{2}$, not 2.' },
    ],
    correct: 0,
    explanation: '$x^2 - 2 = x^2 - (\\sqrt{2})^2$, so $x = \\sqrt{2}\\sec\\theta$ gives $2\\sec^2\\theta - 2 = 2\\tan^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 1,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-004',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Using the course table ($ax = b\\sin\\theta$, $ax = b\\tan\\theta$, $ax = b\\sec\\theta$), which substitution fits this integral?', latex: '\\int \\frac{1}{\\sqrt{25x^2 + 9}}\\,dx' },
    options: [
      { latex: '5x = 3\\tan\\theta' },
      { latex: '5x = 3\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for $b^2 - (ax)^2$; $9\\sin^2\\theta + 9$ does not collapse to one square.' },
      { latex: '5x = 3\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$; $9\\sec^2\\theta + 9$ is not a single square.' },
      { latex: '3x = 5\\tan\\theta', mistake: 'trig-sub-coefficient', why: 'a and b were swapped: $(ax)^2 = 25x^2$ needs $a = 5$ and $b = 3$; with $3x = 5\\tan\\theta$ the radicand is $\\frac{625}{9}\\tan^2\\theta + 9$.' },
      { latex: '3x = 5\\sin\\theta', mistake: 'trig-sub-wrong-form', why: 'Sine is for a difference, not a sum, and a and b are swapped as well.' },
      { latex: '3x = 5\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$, not a sum, and a and b are swapped as well.' },
    ],
    correct: 0,
    explanation: '$25x^2 + 9 = (5x)^2 + 3^2$, so $a = 5$, $b = 3$: $5x = 3\\tan\\theta$ gives $9\\tan^2\\theta + 9 = 9\\sec^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 2,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-005',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'Using the course table ($ax = b\\sin\\theta$, $ax = b\\tan\\theta$, $ax = b\\sec\\theta$), which substitution fits this integral?', latex: '\\int \\sqrt{1 - 9x^2}\\,dx' },
    options: [
      { latex: '3x = \\sin\\theta' },
      { latex: '3x = \\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums; $1 - \\tan^2\\theta$ is not a Pythagorean square.' },
      { latex: '3x = \\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$; $1 - \\sec^2\\theta = -\\tan^2\\theta$ is negative under the root.' },
      { latex: 'x = 3\\sin\\theta', mistake: 'trig-sub-coefficient', why: 'The 3 multiplies x, not the sine: $x = 3\\sin\\theta$ gives $1 - 81\\sin^2\\theta$, which does not collapse.' },
      { latex: 'x = 3\\tan\\theta', mistake: 'trig-sub-wrong-form', why: 'Tangent is for sums, and the 3 belongs with x.' },
      { latex: 'x = 3\\sec\\theta', mistake: 'trig-sub-wrong-form', why: 'Secant is for $(ax)^2 - b^2$, and the 3 belongs with x.' },
    ],
    correct: 0,
    explanation: '$1 - 9x^2 = 1^2 - (3x)^2$, so $a = 3$, $b = 1$: $3x = \\sin\\theta$ gives $1 - \\sin^2\\theta = \\cos^2\\theta$.',
    check: { kind: 'none', reason: 'choice of substitution; options are substitutions, not values' },
    difficulty: 1,
    tags: ['which-sub'],
  },
  {
    id: 'ts-f-006',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'The substitution $2x = 3\\tan\\theta$ is designed to simplify which expression?' },
    options: [
      { latex: '4x^2 + 9' },
      { latex: '9x^2 + 4', mistake: 'trig-sub-coefficient', why: 'a and b were swapped: $9x^2 + 4 = (3x)^2 + 2^2$ needs $3x = 2\\tan\\theta$.' },
      { latex: '9 - 4x^2', mistake: 'trig-sub-wrong-form', why: 'A difference $b^2 - (ax)^2$ calls for a sine substitution, not tangent.' },
      { latex: '4x^2 - 9', mistake: 'trig-sub-wrong-form', why: '$(ax)^2 - b^2$ calls for a secant substitution, since $\\sec^2\\theta - 1 = \\tan^2\\theta$.' },
      { latex: '4 - 9x^2', mistake: 'trig-sub-wrong-form', why: 'A difference calls for sine, and the roles of 2 and 3 are swapped as well.' },
      { latex: '9x^2 - 4', mistake: 'trig-sub-wrong-form', why: '$(ax)^2 - b^2$ calls for secant, and the roles of 2 and 3 are swapped as well.' },
    ],
    correct: 0,
    explanation: 'With $2x = 3\\tan\\theta$: $(2x)^2 + 3^2 = 9\\tan^2\\theta + 9 = 9\\sec^2\\theta$, i.e. the expression $4x^2 + 9$.',
    check: { kind: 'none', reason: 'reverse lookup in the substitution table; options are expressions to be matched, not values' },
    difficulty: 2,
    tags: ['which-sub'],
  },

  // ───────────── computing dx ─────────────
  {
    id: 'ts-f-007',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'If $x = 3\\sin\\theta$, then' },
    options: [
      { latex: 'dx = 3\\cos\\theta\\,d\\theta', expr: '3*cos(theta)*dtheta' },
      { latex: 'dx = \\cos\\theta\\,d\\theta', expr: 'cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'The factor 3 was dropped: $\\frac{d}{d\\theta}(3\\sin\\theta) = 3\\cos\\theta$.' },
      { latex: 'dx = \\frac{1}{3}\\cos\\theta\\,d\\theta', expr: 'cos(theta)*dtheta/3', mistake: 'dx-coefficient', why: 'Divided by 3 instead of multiplying; that is $dx$ for $3x = \\sin\\theta$.' },
      { latex: 'dx = -3\\cos\\theta\\,d\\theta', expr: '-3*cos(theta)*dtheta', mistake: 'dx-derivative-wrong', why: 'The derivative of $\\sin\\theta$ is $+\\cos\\theta$; the minus sign belongs to the derivative of cosine.' },
      { latex: 'dx = 3\\sec^2\\theta\\,d\\theta', expr: '3*sec(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: 'That is $\\frac{d}{d\\theta}(3\\tan\\theta)$, the tangent row of the table.' },
    ],
    correct: 0,
    explanation: '$\\frac{dx}{d\\theta} = 3\\cos\\theta$, so $dx = 3\\cos\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
    check: { kind: 'value', expected: '3*cos(theta)*dtheta' },
    difficulty: 1,
    tags: ['dx'],
  },
  {
    id: 'ts-f-008',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With the course convention $ax = b\\sin\\theta$: if $3x = 2\\sin\\theta$, then' },
    options: [
      { latex: 'dx = \\frac{2}{3}\\cos\\theta\\,d\\theta', expr: '(2/3)*cos(theta)*dtheta' },
      { latex: 'dx = \\frac{3}{2}\\cos\\theta\\,d\\theta', expr: '(3/2)*cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'b/a was inverted: from $3\\,dx = 2\\cos\\theta\\,d\\theta$, divide by 3 to get $\\frac{2}{3}$.' },
      { latex: 'dx = 2\\cos\\theta\\,d\\theta', expr: '2*cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'The right side was differentiated, but the 3 multiplying $dx$ on the left was never divided out.' },
      { latex: 'dx = 6\\cos\\theta\\,d\\theta', expr: '6*cos(theta)*dtheta', mistake: 'dx-coefficient', why: 'Multiplied by $a = 3$ instead of dividing by it.' },
      { latex: 'dx = -\\frac{2}{3}\\cos\\theta\\,d\\theta', expr: '-(2/3)*cos(theta)*dtheta', mistake: 'dx-derivative-wrong', why: 'The derivative of $\\sin\\theta$ is $+\\cos\\theta$; the minus sign belongs to the derivative of cosine.' },
    ],
    correct: 0,
    explanation: 'Differentiate both sides: $3\\,dx = 2\\cos\\theta\\,d\\theta$, so $dx = \\frac{b}{a}\\cos\\theta\\,d\\theta = \\frac{2}{3}\\cos\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.2, 1.2], dtheta: [0.25, 1.25] },
    check: { kind: 'value', expected: '2*cos(theta)*dtheta/3' },
    difficulty: 2,
    tags: ['dx'],
  },
  {
    id: 'ts-f-009',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'If $x = 2\\tan\\theta$, then' },
    options: [
      { latex: 'dx = 2\\sec^2\\theta\\,d\\theta', expr: '2*sec(theta)^2*dtheta' },
      { latex: 'dx = 2\\sec\\theta\\tan\\theta\\,d\\theta', expr: '2*sec(theta)*tan(theta)*dtheta', mistake: 'dx-derivative-wrong', why: 'That is the derivative of $2\\sec\\theta$; the derivative of $\\tan\\theta$ is $\\sec^2\\theta$.' },
      { latex: 'dx = \\sec^2\\theta\\,d\\theta', expr: 'sec(theta)^2*dtheta', mistake: 'dx-coefficient', why: 'The factor 2 from $x = 2\\tan\\theta$ was dropped.' },
      { latex: 'dx = \\frac{1}{2}\\sec^2\\theta\\,d\\theta', expr: 'sec(theta)^2*dtheta/2', mistake: 'dx-coefficient', why: 'Divided by 2 instead of multiplying; that is $dx$ for $2x = \\tan\\theta$.' },
      { latex: 'dx = -2\\csc^2\\theta\\,d\\theta', expr: '-2*csc(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: 'That is the derivative of $2\\cot\\theta$, not of $2\\tan\\theta$.' },
    ],
    correct: 0,
    explanation: '$\\frac{d}{d\\theta}(2\\tan\\theta) = 2\\sec^2\\theta$, so $dx = 2\\sec^2\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2], dtheta: [0.25, 1.25] },
    check: { kind: 'value', expected: '2*sec(theta)^2*dtheta' },
    difficulty: 1,
    tags: ['dx'],
  },
  {
    id: 'ts-f-010',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With the course convention $ax = b\\sec\\theta$: if $5x = 3\\sec\\theta$, then' },
    options: [
      { latex: 'dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta', expr: '(3/5)*sec(theta)*tan(theta)*dtheta' },
      { latex: 'dx = \\frac{5}{3}\\sec\\theta\\tan\\theta\\,d\\theta', expr: '(5/3)*sec(theta)*tan(theta)*dtheta', mistake: 'dx-coefficient', why: 'b/a was inverted: $5\\,dx = 3\\sec\\theta\\tan\\theta\\,d\\theta$ gives $\\frac{3}{5}$.' },
      { latex: 'dx = 3\\sec\\theta\\tan\\theta\\,d\\theta', expr: '3*sec(theta)*tan(theta)*dtheta', mistake: 'dx-coefficient', why: 'The right side was differentiated, but the 5 multiplying $dx$ was never divided out.' },
      { latex: 'dx = \\frac{3}{5}\\sec^2\\theta\\,d\\theta', expr: '(3/5)*sec(theta)^2*dtheta', mistake: 'dx-derivative-wrong', why: 'That uses the derivative of $\\tan\\theta$; the derivative of $\\sec\\theta$ is $\\sec\\theta\\tan\\theta$.' },
      { latex: 'dx = 15\\sec\\theta\\tan\\theta\\,d\\theta', expr: '15*sec(theta)*tan(theta)*dtheta', mistake: 'dx-coefficient', why: 'Multiplied by $a = 5$ instead of dividing by it.' },
    ],
    correct: 0,
    explanation: 'Differentiate both sides: $5\\,dx = 3\\sec\\theta\\tan\\theta\\,d\\theta$, so $dx = \\frac{3}{5}\\sec\\theta\\tan\\theta\\,d\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2], dtheta: [0.25, 1.25] },
    check: { kind: 'value', expected: '3*sec(theta)*tan(theta)*dtheta/5' },
    difficulty: 2,
    tags: ['dx'],
  },

  // ───────────── collapsing the radicand ─────────────
  {
    id: 'ts-f-011',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With $x = 3\\sin\\theta$ and $-\\frac{\\pi}{2} \\le \\theta \\le \\frac{\\pi}{2}$, which simplification is correct?' },
    options: [
      { latex: '\\sqrt{9-x^2} = 3\\cos\\theta', expr: '3*cos(theta)' },
      { latex: '\\sqrt{9-x^2} = 9\\cos\\theta', expr: '9*cos(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{9\\cos^2\\theta} = 3|\\cos\\theta|$; the 9 must be rooted too.' },
      { latex: '\\sqrt{9-x^2} = -3\\cos\\theta', expr: '-3*cos(theta)', mistake: 'theta-interval-sign', why: 'On $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$ the cosine is nonnegative, so the root is $+3\\cos\\theta$.' },
      { latex: '\\sqrt{9-x^2} = 3 - 3\\sin\\theta', expr: '3 - 3*sin(theta)', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{9 - 9\\sin^2\\theta} \\ne \\sqrt{9} - \\sqrt{9\\sin^2\\theta}$.' },
      { latex: '\\sqrt{9-x^2} = 3\\tan\\theta', expr: '3*tan(theta)', mistake: 'pythagorean-wrong', why: 'Used $\\sec^2\\theta - 1 = \\tan^2\\theta$ (the secant identity); here $9 - 9\\sin^2\\theta = 9\\cos^2\\theta$.' },
    ],
    correct: 0,
    explanation: '$9 - 9\\sin^2\\theta = 9\\cos^2\\theta$ and $\\cos\\theta \\ge 0$ on $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$, so the root is $3\\cos\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.2, 1.2] },
    check: { kind: 'identity', lhs: 'sqrt(9 - (3*sin(theta))^2)' },
    difficulty: 1,
    tags: ['radical'],
  },
  {
    id: 'ts-f-012',
    topic: 'trig-sub',
    kind: 'concept',
    prompt: { text: 'Let $x = 2\\tan\\theta$ with $x < 0$, so $-\\frac{\\pi}{2} < \\theta < 0$. Which simplification is correct?' },
    options: [
      { latex: '\\sqrt{x^2+4} = 2\\sec\\theta', expr: '2*sec(theta)' },
      { latex: '\\sqrt{x^2+4} = -2\\sec\\theta', expr: '-2*sec(theta)', mistake: 'theta-interval-sign', why: 'A negative x does not make the root negative: $\\sec\\theta > 0$ on all of $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$.' },
      { latex: '\\sqrt{x^2+4} = 4\\sec\\theta', expr: '4*sec(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{4\\sec^2\\theta} = 2\\sec\\theta$; the 4 must be rooted too.' },
      { latex: '\\sqrt{x^2+4} = 2 - 2\\tan\\theta', expr: '2 - 2*tan(theta)', mistake: 'sqrt-of-sum-split', why: 'The root was split over the sum: $\\sqrt{4\\tan^2\\theta} + \\sqrt{4} = 2|\\tan\\theta| + 2$ is not $\\sqrt{4\\tan^2\\theta + 4}$.' },
      { latex: '\\sqrt{x^2+4} = 2\\cos\\theta', expr: '2*cos(theta)', mistake: 'pythagorean-wrong', why: 'The identity is $1 + \\tan^2\\theta = \\sec^2\\theta$; cosine is the reciprocal of secant, not the same function.' },
    ],
    correct: 0,
    explanation: '$4\\tan^2\\theta + 4 = 4\\sec^2\\theta$, and $\\sec\\theta > 0$ on $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$ even when $x < 0$, so the root is $2\\sec\\theta$.',
    variable: 'theta',
    domain: { theta: [-1.3, -0.2] },
    check: { kind: 'identity', lhs: 'sqrt((2*tan(theta))^2 + 4)' },
    difficulty: 2,
    tags: ['radical', 'sign'],
  },
  {
    id: 'ts-f-013',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With $x = \\sqrt{2}\\sec\\theta$ and $x > \\sqrt{2}$ (so $0 \\le \\theta < \\frac{\\pi}{2}$), which simplification is correct?' },
    options: [
      { latex: '\\sqrt{x^2-2} = \\sqrt{2}\\tan\\theta', expr: 'sqrt(2)*tan(theta)' },
      { latex: '\\sqrt{x^2-2} = 2\\tan\\theta', expr: '2*tan(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{2\\tan^2\\theta} = \\sqrt{2}\\,|\\tan\\theta|$; the 2 must be rooted too.' },
      { latex: '\\sqrt{x^2-2} = -\\sqrt{2}\\tan\\theta', expr: '-sqrt(2)*tan(theta)', mistake: 'theta-interval-sign', why: 'For $x > \\sqrt{2}$, θ lies in $[0, \\frac{\\pi}{2})$ where $\\tan\\theta \\ge 0$; the minus sign is for $x < -\\sqrt{2}$.' },
      { latex: '\\sqrt{x^2-2} = \\sqrt{2}\\sec\\theta - \\sqrt{2}', expr: 'sqrt(2)*sec(theta) - sqrt(2)', mistake: 'sqrt-of-sum-split', why: 'The root was split over the difference: $\\sqrt{2\\sec^2\\theta - 2} \\ne \\sqrt{2\\sec^2\\theta} - \\sqrt{2}$.' },
      { latex: '\\sqrt{x^2-2} = \\tan\\theta', expr: 'tan(theta)', mistake: 'coefficient-mishandled', why: 'The factor 2 in $2(\\sec^2\\theta - 1)$ was lost; its root $\\sqrt{2}$ must stay in front.' },
    ],
    correct: 0,
    explanation: '$2\\sec^2\\theta - 2 = 2\\tan^2\\theta$, and $\\tan\\theta \\ge 0$ on $[0, \\frac{\\pi}{2})$, so the root is $\\sqrt{2}\\tan\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.3] },
    check: { kind: 'identity', lhs: 'sqrt((sqrt(2)*sec(theta))^2 - 2)' },
    difficulty: 1,
    tags: ['radical', 'sign'],
  },
  {
    id: 'ts-f-014',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'The substitution $ax = b\\sin\\theta$ turns $b^2 - a^2x^2$ into a perfect square by using which identity?' },
    options: [
      { latex: '1 - \\sin^2\\theta = \\cos^2\\theta' },
      { latex: '1 + \\tan^2\\theta = \\sec^2\\theta', mistake: 'trig-sub-wrong-form', why: 'This identity is behind the tangent substitution, for a sum $b^2 + (ax)^2$.' },
      { latex: '\\sec^2\\theta - 1 = \\tan^2\\theta', mistake: 'trig-sub-wrong-form', why: 'This identity is behind the secant substitution, for $(ax)^2 - b^2$.' },
      { latex: '\\sin^2\\theta - 1 = \\cos^2\\theta', mistake: 'pythagorean-wrong', why: 'Sign error: $\\sin^2\\theta - 1 = -\\cos^2\\theta$.' },
      { latex: '1 - \\sin^2\\theta = \\tan^2\\theta', mistake: 'pythagorean-wrong', why: 'Wrong pairing: $1 - \\sin^2\\theta$ equals $\\cos^2\\theta$; tangent pairs with secant.' },
    ],
    correct: 0,
    explanation: '$b^2 - b^2\\sin^2\\theta = b^2(1 - \\sin^2\\theta) = b^2\\cos^2\\theta$.',
    check: { kind: 'none', reason: 'identity recall; several options are true identities that belong to other substitutions' },
    difficulty: 1,
    tags: ['identity'],
  },
  {
    id: 'ts-f-015',
    topic: 'trig-sub',
    kind: 'formula',
    prompt: { text: 'With $4x = 3\\tan\\theta$ and $-\\frac{\\pi}{2} < \\theta < \\frac{\\pi}{2}$, $\\sqrt{16x^2 + 9}$ simplifies to' },
    options: [
      { latex: '3\\sec\\theta', expr: '3*sec(theta)' },
      { latex: '9\\sec\\theta', expr: '9*sec(theta)', mistake: 'sqrt-constant-not-rooted', why: '$\\sqrt{9\\sec^2\\theta} = 3\\sec\\theta$; the 9 must be rooted too.' },
      { latex: '4\\sec\\theta', expr: '4*sec(theta)', mistake: 'coefficient-mishandled', why: 'The constant that survives is $b = 3$: $(4x)^2 + 9 = 9\\tan^2\\theta + 9 = 9\\sec^2\\theta$.' },
      { latex: '\\frac{3}{4}\\sec\\theta', expr: '(3/4)*sec(theta)', mistake: 'coefficient-mishandled', why: 'Used $x^2 + \\frac{9}{16}$ and dropped the factor 16: $16\\cdot\\frac{9}{16}\\tan^2\\theta + 9 = 9\\sec^2\\theta$.' },
      { latex: '3\\tan\\theta + 3', expr: '3*tan(theta) + 3', mistake: 'sqrt-of-sum-split', why: 'The root was split over the sum: $\\sqrt{9\\tan^2\\theta + 9} \\ne 3\\tan\\theta + 3$.' },
      { latex: '-3\\sec\\theta', expr: '-3*sec(theta)', mistake: 'theta-interval-sign', why: '$\\sec\\theta > 0$ on $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$, so the root is positive.' },
    ],
    correct: 0,
    explanation: '$(4x)^2 = 9\\tan^2\\theta$, so $16x^2 + 9 = 9(\\tan^2\\theta + 1) = 9\\sec^2\\theta$, whose root is $3\\sec\\theta$.',
    variable: 'theta',
    domain: { theta: [0.2, 1.2] },
    check: { kind: 'identity', lhs: 'sqrt(16*(3*tan(theta)/4)^2 + 9)' },
    difficulty: 2,
    tags: ['radical'],
  },
