import type { FlashGenerator, FlashItem } from '../types';

/** Flash Drill items for topic "trig-integrals". Authored by content-author; verified by math-verifier. */
export const flash: FlashItem[] = [
  // ───────────── formulas: identities ─────────────
  {
    id: 'ti-f-001',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: {
      text: 'In $\\int \\sin^3 x\\cos^2 x\\,dx$ you save one $\\sin x$ and substitute $u = \\cos x$. Which identity rewrites the leftover $\\sin^2 x$?',
    },
    options: [
      { latex: '\\sin^2 x = \\cos^2 x - 1', expr: 'cos(x)^2 - 1', mistake: 'pythagorean-wrong', why: 'Solving sin²x + cos²x = 1 for sin²x gives 1 − cos²x; this has the subtraction reversed (it would make sin²x negative).' },
      { latex: '\\sin^2 x = 1 - \\cos^2 x', expr: '1 - cos(x)^2' },
      { latex: '\\sin^2 x = 1 + \\cos^2 x', expr: '1 + cos(x)^2', mistake: 'pythagorean-wrong', why: 'cos²x was moved across the equals sign without changing its sign.' },
      { latex: '\\sin^2 x = \\sec^2 x - 1', expr: 'sec(x)^2 - 1', mistake: 'pythagorean-wrong', why: 'This borrows the tangent identity: sec²x − 1 equals tan²x, not sin²x.' },
      { latex: '\\sin^2 x = \\frac{1 + \\cos 2x}{2}', expr: '(1 + cos(2*x))/2', mistake: 'half-angle-wrong', why: '(1 + cos 2x)/2 is the half-angle form of cos²x; it is also the wrong tool here, since u = cos x needs sin²x written in cos x.' },
      { latex: '\\sin^2 x = 1 - \\cos x', expr: '1 - cos(x)', mistake: 'formula-wrong-power', why: 'The square on cosine was dropped: sin²x = 1 − cos²x.' },
    ],
    correct: 1,
    explanation: 'From $\\sin^2 x + \\cos^2 x = 1$: $\\sin^2 x = 1 - \\cos^2 x = 1 - u^2$.',
    check: { kind: 'identity', lhs: 'sin(x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-002',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: { text: 'With $u = \\sec x$, leftover even powers of tangent are converted with which identity?' },
    options: [
      { latex: '\\tan^2 x = \\sec^2 x + 1', expr: 'sec(x)^2 + 1', mistake: 'tan-sec-identity-direction', why: 'From tan²x + 1 = sec²x, subtracting 1 gives sec²x − 1; adding 1 reverses the identity.' },
      { latex: '\\tan^2 x = 1 - \\sec^2 x', expr: '1 - sec(x)^2', mistake: 'pythagorean-wrong', why: 'This copies the sin²x = 1 − cos²x pattern; since sec²x ≥ 1 it would make tan²x negative.' },
      { latex: '\\tan^2 x = \\sec^2 x - 1', expr: 'sec(x)^2 - 1' },
      { latex: '\\tan^2 x = 1 - \\cos^2 x', expr: '1 - cos(x)^2', mistake: 'pythagorean-wrong', why: '1 − cos²x is sin²x, not tan²x.' },
      { latex: '\\tan^2 x = \\sec x - 1', expr: 'sec(x) - 1', mistake: 'formula-wrong-power', why: 'The square on secant was dropped.' },
      { latex: '\\tan^2 x = \\csc^2 x - 1', expr: 'csc(x)^2 - 1', mistake: 'formula-swapped', why: 'csc²x − 1 equals cot²x; tangent pairs with secant.' },
    ],
    correct: 2,
    explanation: 'Divide $\\sin^2 x + \\cos^2 x = 1$ by $\\cos^2 x$: $\\tan^2 x + 1 = \\sec^2 x$, so $\\tan^2 x = \\sec^2 x - 1 = u^2 - 1$.',
    check: { kind: 'identity', lhs: 'tan(x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-003',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: {
      text: 'In $\\int \\sec^4 x\\,dx$ you save one $\\sec^2 x$ for $du$ (with $u = \\tan x$). The other $\\sec^2 x$ becomes',
    },
    options: [
      { latex: '\\tan^2 x - 1', expr: 'tan(x)^2 - 1', mistake: 'tan-sec-identity-direction', why: 'sec²x = tan²x + 1; writing tan²x − 1 reverses the identity.' },
      { latex: '1 - \\tan^2 x', expr: '1 - tan(x)^2', mistake: 'pythagorean-wrong', why: 'This borrows the cos²x = 1 − sin²x pattern; the secant identity adds 1, it does not subtract.' },
      { latex: '\\tan x + 1', expr: 'tan(x) + 1', mistake: 'formula-wrong-power', why: 'The square on tangent was dropped.' },
      { latex: '\\cot^2 x + 1', expr: 'cot(x)^2 + 1', mistake: 'formula-swapped', why: 'cot²x + 1 = csc²x; secant pairs with tangent.' },
      { latex: '\\tan^2 x + 1', expr: 'tan(x)^2 + 1' },
    ],
    correct: 4,
    explanation: '$\\tan^2 x + 1 = \\sec^2 x$, so $\\sec^4 x\\,dx = (\\tan^2 x + 1)\\sec^2 x\\,dx = (u^2 + 1)\\,du$.',
    check: { kind: 'identity', lhs: 'sec(x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-004',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: { text: 'Which power-reducing (half-angle) identity for $\\cos^2 x$ is correct?' },
    options: [
      { latex: '\\cos^2 x = \\frac{1 - \\cos 2x}{2}', expr: '(1 - cos(2*x))/2', mistake: 'half-angle-wrong', why: 'The minus sign belongs to sin²x; cos²x uses 1 + cos 2x.' },
      { latex: '\\cos^2 x = \\frac{1 + \\cos x}{2}', expr: '(1 + cos(x))/2', mistake: 'half-angle-wrong', why: 'The angle must double: the identity uses cos 2x, not cos x.' },
      { latex: '\\cos^2 x = \\frac{1 + \\cos 2x}{2}', expr: '(1 + cos(2*x))/2' },
      { latex: '\\cos^2 x = 1 + \\cos 2x', expr: '1 + cos(2*x)', mistake: 'half-angle-wrong', why: 'The factor 1/2 is missing (at x = 0 this gives 2, but cos²0 = 1).' },
      { latex: '\\cos^2 x = \\frac{1 + \\sin 2x}{2}', expr: '(1 + sin(2*x))/2', mistake: 'double-angle-wrong', why: 'cos 2x, not sin 2x, appears in the power-reducing identities.' },
    ],
    correct: 2,
    explanation: 'From $\\cos 2x = 2\\cos^2 x - 1$, solve for $\\cos^2 x = \\frac{1 + \\cos 2x}{2}$.',
    check: { kind: 'identity', lhs: 'cos(x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-005',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: { text: 'Which rewrite of $\\sin x\\cos x$ is correct? (It turns $\\sin^2 x\\cos^2 x$ into $\\tfrac14\\sin^2 2x$.)' },
    options: [
      { latex: '\\sin x\\cos x = \\sin 2x', expr: 'sin(2*x)', mistake: 'double-angle-wrong', why: 'sin 2x = 2 sin x cos x, so sin x cos x is only half of sin 2x.' },
      { latex: '\\sin x\\cos x = 2\\sin 2x', expr: '2*sin(2*x)', mistake: 'double-angle-wrong', why: 'The 2 went to the wrong side: sin 2x = 2 sin x cos x means sin x cos x = ½ sin 2x.' },
      { latex: '\\sin x\\cos x = \\frac{1}{2}\\cos 2x', expr: 'cos(2*x)/2', mistake: 'double-angle-wrong', why: 'cos 2x = cos²x − sin²x; the product sin x cos x comes from sin 2x.' },
      { latex: '\\sin x\\cos x = \\frac{1 - \\cos 2x}{2}', expr: '(1 - cos(2*x))/2', mistake: 'half-angle-wrong', why: '(1 − cos 2x)/2 is sin²x, not sin x cos x.' },
      { latex: '\\sin x\\cos x = \\frac{1}{2}\\sin 2x', expr: 'sin(2*x)/2' },
    ],
    correct: 4,
    explanation: '$\\sin 2x = 2\\sin x\\cos x$, so $\\sin x\\cos x = \\frac{1}{2}\\sin 2x$.',
    check: { kind: 'identity', lhs: 'sin(x)*cos(x)' },
    difficulty: 1,
  },
  {
    id: 'ti-f-006',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: { text: 'Which double-angle identity for $\\cos 2x$ is correct?' },
    options: [
      { latex: '\\cos 2x = \\cos^2 x - \\sin^2 x', expr: 'cos(x)^2 - sin(x)^2' },
      { latex: '\\cos 2x = \\sin^2 x - \\cos^2 x', expr: 'sin(x)^2 - cos(x)^2', mistake: 'double-angle-wrong', why: 'The order is reversed; test x = 0: cos 0 = 1, but sin²0 − cos²0 = −1.' },
      { latex: '\\cos 2x = \\cos^2 x + \\sin^2 x', expr: 'cos(x)^2 + sin(x)^2', mistake: 'double-angle-wrong', why: 'cos²x + sin²x is always 1; the double-angle formula subtracts.' },
      { latex: '\\cos 2x = 2\\cos^2 x + 1', expr: '2*cos(x)^2 + 1', mistake: 'double-angle-wrong', why: 'The alternate form is 2cos²x − 1; the constant is subtracted.' },
      { latex: '\\cos 2x = 2\\sin x\\cos x', expr: '2*sin(x)*cos(x)', mistake: 'double-angle-wrong', why: '2 sin x cos x is sin 2x.' },
      { latex: '\\cos 2x = 2\\cos x', expr: '2*cos(x)', mistake: 'double-angle-wrong', why: 'Cosine is not linear: cos 2x ≠ 2 cos x (at x = 0: 1 vs 2).' },
    ],
    correct: 0,
    explanation: '$\\cos(x + x) = \\cos x\\cos x - \\sin x\\sin x = \\cos^2 x - \\sin^2 x$ (equivalently $2\\cos^2 x - 1$ or $1 - 2\\sin^2 x$).',
    check: { kind: 'identity', lhs: 'cos(2*x)' },
    difficulty: 1,
  },
  {
    id: 'ti-f-007',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: { text: 'Rewrite $\\sin^2(3x)$ with a half-angle identity.' },
    options: [
      { latex: '\\frac{1 - \\cos 3x}{2}', expr: '(1 - cos(3*x))/2', mistake: 'half-angle-wrong', why: 'The angle doubles: 2·(3x) = 6x.' },
      { latex: '\\frac{1 + \\cos 6x}{2}', expr: '(1 + cos(6*x))/2', mistake: 'half-angle-wrong', why: '(1 + cos 6x)/2 is cos²(3x); sine takes the minus sign.' },
      { latex: '\\frac{1 - \\cos 6x}{6}', expr: '(1 - cos(6*x))/6', mistake: 'inner-constant-factor-missing', why: 'The inner 3 only changes the angle here; a 1/k factor appears when you integrate, not in the identity.' },
      { latex: '\\frac{1 - \\cos 6x}{2}', expr: '(1 - cos(6*x))/2' },
      { latex: '1 - \\cos 6x', expr: '1 - cos(6*x)', mistake: 'half-angle-wrong', why: 'The factor 1/2 is missing.' },
    ],
    correct: 3,
    explanation: '$\\sin^2\\theta = \\frac{1 - \\cos 2\\theta}{2}$ with $\\theta = 3x$ gives $\\frac{1 - \\cos 6x}{2}$.',
    check: { kind: 'identity', lhs: 'sin(3*x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-008',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: {
      text: 'Using $\\sin x\\cos x = \\frac{1}{2}\\sin 2x$ and then a half-angle identity, $\\sin^2 x\\cos^2 x$ equals',
    },
    options: [
      { latex: '\\frac{1 - \\cos 4x}{8}', expr: '(1 - cos(4*x))/8' },
      { latex: '\\frac{1 - \\cos 4x}{4}', expr: '(1 - cos(4*x))/4', mistake: 'half-angle-wrong', why: 'sin²(2x) = (1 − cos 4x)/2; that 1/2 was dropped, so the result is twice too big.' },
      { latex: '\\frac{1 - \\cos 2x}{8}', expr: '(1 - cos(2*x))/8', mistake: 'half-angle-wrong', why: 'Reducing sin²(2x) doubles the angle 2x to 4x, not to 2x.' },
      { latex: '\\frac{1 + \\cos 4x}{8}', expr: '(1 + cos(4*x))/8', mistake: 'half-angle-wrong', why: 'sin²(2x) uses 1 − cos 4x; the plus sign belongs to cos².' },
      { latex: '\\frac{1 - \\cos 4x}{2}', expr: '(1 - cos(4*x))/2', mistake: 'double-angle-wrong', why: 'This squares sin x cos x = sin 2x (missing the 1/2), which loses the factor 1/4.' },
    ],
    correct: 0,
    explanation: '$\\sin^2 x\\cos^2 x = \\frac{1}{4}\\sin^2 2x = \\frac{1}{4}\\cdot\\frac{1 - \\cos 4x}{2} = \\frac{1 - \\cos 4x}{8}$.',
    check: { kind: 'identity', lhs: 'sin(x)^2*cos(x)^2' },
    difficulty: 2,
  },
  {
    id: 'ti-f-009',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: { text: 'To integrate $\\cos(5t)\\cos(10t)$, rewrite $\\cos(10t)$ in terms of $\\cos(5t)$:' },
    options: [
      { latex: '1 - 2\\cos^2(5t)', expr: '1 - 2*cos(5*t)^2', mistake: 'double-angle-wrong', why: 'The sign is reversed: cos 2θ = 2cos²θ − 1 (check θ = 0: cos 0 = 1).' },
      { latex: '2\\cos^2(5t) + 1', expr: '2*cos(5*t)^2 + 1', mistake: 'double-angle-wrong', why: 'cos 2θ = 2cos²θ − 1; the constant is subtracted, not added.' },
      { latex: '\\cos^2(5t) + \\sin^2(5t)', expr: 'cos(5*t)^2 + sin(5*t)^2', mistake: 'double-angle-wrong', why: 'cos²θ + sin²θ = 1; the double-angle formula is cos²θ − sin²θ.' },
      { latex: '2\\sin(5t)\\cos(5t)', expr: '2*sin(5*t)*cos(5*t)', mistake: 'double-angle-wrong', why: '2 sin θ cos θ is sin 2θ, i.e. sin(10t).' },
      { latex: '2\\cos^2(5t) - 1', expr: '2*cos(5*t)^2 - 1' },
    ],
    correct: 4,
    explanation: '$\\cos 2\\theta = 2\\cos^2\\theta - 1$ with $\\theta = 5t$, leaving only cosines of $5t$ (odd power after multiplying by $\\cos 5t$).',
    variable: 't',
    check: { kind: 'identity', lhs: 'cos(10*t)' },
    difficulty: 2,
  },
  {
    id: 'ti-f-010',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: {
      text: 'For $\\int \\sin^5 x\\cos^2 x\\,dx$, save one $\\sin x$ and write the rest in cosine. $\\sin^5 x$ equals',
    },
    options: [
      { latex: '(1 - \\cos^2 x)\\sin x', expr: '(1 - cos(x)^2)*sin(x)', mistake: 'exponent-arithmetic', why: 'After saving sin x, sin⁴x = (sin²x)² = (1 − cos²x)²; the square was dropped (that is sin³x).' },
      { latex: '(1 - \\cos^4 x)\\sin x', expr: '(1 - cos(x)^4)*sin(x)', mistake: 'algebra-error', why: '(1 − cos²x)² was squared term by term; it expands to 1 − 2cos²x + cos⁴x.' },
      { latex: '(1 - \\cos^2 x)^2\\sin x', expr: '(1 - cos(x)^2)^2*sin(x)' },
      { latex: '(1 + \\cos^2 x)^2\\sin x', expr: '(1 + cos(x)^2)^2*sin(x)', mistake: 'pythagorean-wrong', why: 'sin²x = 1 − cos²x, not 1 + cos²x.' },
      { latex: '(1 - \\cos^2 x)^2\\cos x', expr: '(1 - cos(x)^2)^2*cos(x)', mistake: 'trig-wrong-factor-saved', why: 'The saved factor must be sin x (sin⁵x = sin⁴x·sin x); cos x is not a factor of sin⁵x.' },
    ],
    correct: 2,
    explanation: '$\\sin^5 x = (\\sin^2 x)^2\\sin x = (1 - \\cos^2 x)^2\\sin x$, ready for $u = \\cos x$.',
    check: { kind: 'identity', lhs: 'sin(x)^5' },
    difficulty: 2,
  },
  {
    id: 'ti-f-011',
    topic: 'trig-integrals',
    kind: 'formula',
    prompt: { text: 'Rewrite $\\cos^2\\left(\\frac{t}{2}\\right)$ with a half-angle identity.' },
    options: [
      { latex: '\\frac{1 + \\cos\\frac{t}{4}}{2}', expr: '(1 + cos(t/4))/2', mistake: 'half-angle-wrong', why: 'The angle doubles: 2·(t/2) = t; halving it again to t/4 goes the wrong way.' },
      { latex: '\\frac{1 - \\cos t}{2}', expr: '(1 - cos(t))/2', mistake: 'half-angle-wrong', why: 'The minus sign belongs to sin²; cos² uses 1 + cos.' },
      { latex: '\\frac{1 + \\cos t}{4}', expr: '(1 + cos(t))/4', mistake: 'coefficient-mishandled', why: 'The inner 1/2 only changes the angle; the identity’s factor stays 1/2.' },
      { latex: '\\frac{1 + \\cos t}{2}', expr: '(1 + cos(t))/2' },
      { latex: '\\frac{1 + \\cos 2t}{2}', expr: '(1 + cos(2*t))/2', mistake: 'half-angle-wrong', why: 'Double the angle t/2, not t: 2·(t/2) = t.' },
      { latex: '1 + \\cos t', expr: '1 + cos(t)', mistake: 'half-angle-wrong', why: 'The factor 1/2 is missing.' },
    ],
    correct: 3,
    explanation: '$\\cos^2\\theta = \\frac{1 + \\cos 2\\theta}{2}$ with $\\theta = \\frac{t}{2}$ gives $\\frac{1 + \\cos t}{2}$.',
    variable: 't',
    check: { kind: 'identity', lhs: 'cos(t/2)^2' },
    difficulty: 1,
  },

  // ───────────── the four "less common" antiderivatives ─────────────
  {
    id: 'ti-f-012',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\tan x' },
    options: [
      { latex: '\\ln|\\cos x| + C', expr: 'log(abs(cos(x)))', mistake: 'tan-antiderivative-wrong', why: 'With u = cos x, du = −sin x dx, so ∫tan x dx = −∫du/u; the minus sign was lost.' },
      { latex: '\\ln|\\sin x| + C', expr: 'log(abs(sin(x)))', mistake: 'tan-antiderivative-wrong', why: 'ln|sin x| is the antiderivative of cot x = cos x/sin x.' },
      { latex: '-\\ln|\\cos x| + C', expr: '-log(abs(cos(x)))' },
      { latex: '\\ln|\\sec x + \\tan x| + C', expr: 'log(abs(sec(x) + tan(x)))', mistake: 'tan-antiderivative-wrong', why: 'That is ∫sec x dx; its derivative is sec x, not tan x.' },
      { latex: '-\\ln|\\sin x| + C', expr: '-log(abs(sin(x)))', mistake: 'tan-antiderivative-wrong', why: 'The log must hold the denominator cos x (the u whose derivative −sin x appears), not sin x.' },
      { latex: '\\ln|\\tan x| + C', expr: 'log(abs(tan(x)))', mistake: 'ln-argument-wrong', why: '∫f dx is not ln|f|; ln|u| needs the integrand to be u′/u, and (tan x)′ = sec²x is not present.' },
    ],
    correct: 2,
    explanation: '$\\tan x = \\frac{\\sin x}{\\cos x}$; with $u = \\cos x$, $du = -\\sin x\\,dx$: $-\\int \\frac{du}{u} = -\\ln|\\cos x| + C$ ($= \\ln|\\sec x| + C$).',
    check: { kind: 'antiderivative', integrand: 'tan(x)' },
    difficulty: 1,
  },
  {
    id: 'ti-f-013',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sec x' },
    options: [
      { latex: '\\ln|\\sec x - \\tan x| + C', expr: 'log(abs(sec(x) - tan(x)))', mistake: 'sec-antiderivative-wrong', why: 'The sign inside is wrong: d/dx ln|sec x − tan x| = −sec x.' },
      { latex: '\\ln|\\sec x| + C', expr: 'log(abs(sec(x)))', mistake: 'sec-antiderivative-wrong', why: 'ln|sec x| = −ln|cos x| is ∫tan x dx.' },
      { latex: '\\ln|\\csc x - \\cot x| + C', expr: 'log(abs(csc(x) - cot(x)))', mistake: 'formula-swapped', why: 'That is ∫csc x dx; secant needs sec x + tan x inside the log.' },
      { latex: '\\sec x\\tan x + C', expr: 'sec(x)*tan(x)', mistake: 'trig-antiderivative-swapped', why: 'sec x tan x is the derivative of sec x, not an antiderivative of sec x.' },
      { latex: '\\ln|\\sec x + \\tan x| + C', expr: 'log(abs(sec(x) + tan(x)))' },
    ],
    correct: 4,
    explanation: 'Check: $\\frac{d}{dx}\\ln|\\sec x + \\tan x| = \\frac{\\sec x\\tan x + \\sec^2 x}{\\sec x + \\tan x} = \\sec x$.',
    check: { kind: 'antiderivative', integrand: 'sec(x)' },
    difficulty: 1,
  },
  {
    id: 'ti-f-014',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sec^2(3x)' },
    options: [
      { latex: '\\tan 3x + C', expr: 'tan(3*x)', mistake: 'inner-constant-factor-missing', why: 'd/dx tan 3x = 3sec²(3x); divide by the inner 3.' },
      { latex: '\\frac{1}{3}\\tan 3x + C', expr: 'tan(3*x)/3' },
      { latex: '3\\tan 3x + C', expr: '3*tan(3*x)', mistake: 'inner-constant-factor-missing', why: 'Multiplied by the inner 3 instead of dividing by it.' },
      { latex: '\\frac{1}{3}\\sec 3x\\tan 3x + C', expr: 'sec(3*x)*tan(3*x)/3', mistake: 'trig-antiderivative-swapped', why: 'sec u tan u is the derivative of sec u; ∫sec²u du = tan u.' },
      { latex: '\\frac{1}{9}\\sec^3(3x) + C', expr: 'sec(3*x)^3/9', mistake: 'u-choice-wrong', why: 'The power rule was applied to sec(3x) as if it were the variable; its derivative 3sec(3x)tan(3x) is not in the integrand.' },
    ],
    correct: 1,
    explanation: 'With $w = 3x$, $dx = \\frac{dw}{3}$: $\\frac{1}{3}\\int \\sec^2 w\\,dw = \\frac{1}{3}\\tan 3x + C$.',
    domain: [0.05, 0.45],
    check: { kind: 'antiderivative', integrand: 'sec(3*x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-015',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sec 2x\\tan 2x' },
    options: [
      { latex: '\\sec 2x + C', expr: 'sec(2*x)', mistake: 'inner-constant-factor-missing', why: 'd/dx sec 2x = 2 sec 2x tan 2x; divide by the inner 2.' },
      { latex: '2\\sec 2x + C', expr: '2*sec(2*x)', mistake: 'inner-constant-factor-missing', why: 'Multiplied by the inner 2 instead of dividing by it.' },
      { latex: '\\frac{1}{2}\\tan 2x + C', expr: 'tan(2*x)/2', mistake: 'trig-antiderivative-swapped', why: 'tan u is the antiderivative of sec²u, not of sec u tan u.' },
      { latex: '-\\frac{1}{2}\\sec 2x + C', expr: '-sec(2*x)/2', mistake: 'trig-antiderivative-sign', why: 'd/du sec u = +sec u tan u; the minus sign belongs to csc u.' },
      { latex: '\\frac{1}{2}\\sec 2x + C', expr: 'sec(2*x)/2' },
      { latex: '\\frac{1}{4}\\sec^2 2x + C', expr: 'sec(2*x)^2/4', mistake: 'du-derivative-wrong', why: 'With u = sec 2x, du = 2 sec 2x tan 2x dx, so the integral is ∫du/2; treating tan 2x dx alone as the differential gives ∫u du/2 instead.' },
    ],
    correct: 4,
    explanation: 'With $u = \\sec 2x$, $du = 2\\sec 2x\\tan 2x\\,dx$: $\\frac{1}{2}\\int du = \\frac{1}{2}\\sec 2x + C$.',
    domain: [0.1, 0.7],
    check: { kind: 'antiderivative', integrand: 'sec(2*x)*tan(2*x)' },
    difficulty: 1,
  },
  {
    id: 'ti-f-016',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\tan\\frac{x}{2}' },
    options: [
      { latex: '-\\ln\\left|\\cos\\frac{x}{2}\\right| + C', expr: '-log(abs(cos(x/2)))', mistake: 'inner-constant-factor-missing', why: '∫f(x/2)dx = 2F(x/2): dividing by the inner 1/2 multiplies by 2, which is missing here.' },
      { latex: '-\\frac{1}{2}\\ln\\left|\\cos\\frac{x}{2}\\right| + C', expr: '-log(abs(cos(x/2)))/2', mistake: 'inner-constant-factor-missing', why: 'Multiplied by the inner 1/2 instead of dividing by it.' },
      { latex: '2\\ln\\left|\\cos\\frac{x}{2}\\right| + C', expr: '2*log(abs(cos(x/2)))', mistake: 'tan-antiderivative-wrong', why: '∫tan u du = −ln|cos u|; the minus sign was lost.' },
      { latex: '-2\\ln\\left|\\cos\\frac{x}{2}\\right| + C', expr: '-2*log(abs(cos(x/2)))' },
      { latex: '2\\ln\\left|\\sin\\frac{x}{2}\\right| + C', expr: '2*log(abs(sin(x/2)))', mistake: 'tan-antiderivative-wrong', why: 'ln|sin u| is the antiderivative of cot u, not tan u.' },
    ],
    correct: 3,
    explanation: 'With $w = \\frac{x}{2}$, $dx = 2\\,dw$: $2\\int \\tan w\\,dw = -2\\ln\\left|\\cos\\frac{x}{2}\\right| + C$.',
    check: { kind: 'antiderivative', integrand: 'tan(x/2)' },
    difficulty: 2,
  },

  // ───────────── antiderivatives: sine / cosine ─────────────
  {
    id: 'ti-f-017',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\cos^3 x' },
    options: [
      { latex: '\\sin x + \\frac{1}{3}\\sin^3 x + C', expr: 'sin(x) + sin(x)^3/3', mistake: 'pythagorean-wrong', why: 'cos²x = 1 − sin²x; using 1 + sin²x flips the sign of the u³ term.' },
      { latex: '\\cos x - \\frac{1}{3}\\cos^3 x + C', expr: 'cos(x) - cos(x)^3/3', mistake: 'back-substitution-wrong', why: 'u was sin x, so u − u³/3 must become sin x − ⅓sin³x, not cosines.' },
      { latex: '\\sin x - \\sin^3 x + C', expr: 'sin(x) - sin(x)^3', mistake: 'power-rule-int-coefficient', why: '∫u² du = u³/3; the division by 3 was skipped.' },
      { latex: '\\frac{1}{3}\\sin^3 x - \\sin x + C', expr: 'sin(x)^3/3 - sin(x)', mistake: 'sign-error', why: 'A minus sign was attached to du as in the u = cos x case; with u = sin x, du = +cos x dx.' },
      { latex: '-\\cos x + \\frac{1}{3}\\cos^3 x + C', expr: '-cos(x) + cos(x)^3/3', mistake: 'trig-wrong-factor-saved', why: 'This is ∫sin³x dx (save sin x, u = cos x); cos³x has no sine factor to save.' },
      { latex: '\\sin x - \\frac{1}{3}\\sin^3 x + C', expr: 'sin(x) - sin(x)^3/3' },
    ],
    correct: 5,
    explanation: 'Save $\\cos x$: $\\int (1 - \\sin^2 x)\\cos x\\,dx$; with $u = \\sin x$ this is $\\int (1 - u^2)\\,du = \\sin x - \\frac{1}{3}\\sin^3 x + C$.',
    check: { kind: 'antiderivative', integrand: 'cos(x)^3' },
    difficulty: 1,
  },
  {
    id: 'ti-f-018',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sin^3 x\\cos^2 x' },
    options: [
      { latex: '\\frac{1}{3}\\cos^3 x - \\frac{1}{5}\\cos^5 x + C', expr: 'cos(x)^3/3 - cos(x)^5/5', mistake: 'u-cos-sign-missing', why: 'u = cos x gives du = −sin x dx; dropping that minus flips every sign.' },
      { latex: '-\\frac{1}{3}\\cos^3 x + \\frac{1}{5}\\cos^5 x + C', expr: '-cos(x)^3/3 + cos(x)^5/5' },
      { latex: '-\\frac{1}{3}\\sin^3 x + \\frac{1}{5}\\sin^5 x + C', expr: '-sin(x)^3/3 + sin(x)^5/5', mistake: 'back-substitution-wrong', why: 'u was cos x, so u³ and u⁵ must become cos³x and cos⁵x.' },
      { latex: '-\\frac{1}{3}\\cos^3 x - \\frac{1}{5}\\cos^5 x + C', expr: '-cos(x)^3/3 - cos(x)^5/5', mistake: 'pythagorean-wrong', why: 'sin²x = 1 − cos²x; using 1 + cos²x makes the u⁵ term the wrong sign.' },
      { latex: '-\\cos x + \\frac{1}{5}\\cos^5 x + C', expr: '-cos(x) + cos(x)^5/5', mistake: 'algebra-error', why: '(1 − u²)u² was expanded as 1 − u⁴ instead of u² − u⁴.' },
      { latex: '-\\frac{1}{3}\\cos^3 x + \\frac{2}{5}\\cos^5 x - \\frac{1}{7}\\cos^7 x + C', expr: '-cos(x)^3/3 + 2*cos(x)^5/5 - cos(x)^7/7', mistake: 'exponent-arithmetic', why: 'After saving sin x only sin²x = 1 − cos²x remains; (1 − cos²x)² belongs to sin⁵x.' },
    ],
    correct: 1,
    explanation: '$\\int (1 - \\cos^2 x)\\cos^2 x\\sin x\\,dx$, $u = \\cos x$: $-\\int (u^2 - u^4)\\,du = -\\frac{1}{3}\\cos^3 x + \\frac{1}{5}\\cos^5 x + C$.',
    check: { kind: 'antiderivative', integrand: 'sin(x)^3*cos(x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-019',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sin^2 x' },
    options: [
      { latex: '\\frac{x}{2} + \\frac{\\sin 2x}{4} + C', expr: 'x/2 + sin(2*x)/4', mistake: 'half-angle-wrong', why: 'That uses cos²x = (1 + cos 2x)/2; the sin²x identity has 1 − cos 2x.' },
      { latex: '\\frac{x}{2} - \\frac{\\sin 2x}{2} + C', expr: 'x/2 - sin(2*x)/2', mistake: 'inner-constant-factor-missing', why: '∫cos 2x dx = ½ sin 2x; the 1/2 from the inner 2x was dropped.' },
      { latex: '\\frac{x}{2} - \\frac{\\sin 2x}{4} + C', expr: 'x/2 - sin(2*x)/4' },
      { latex: 'x - \\frac{\\sin 2x}{2} + C', expr: 'x - sin(2*x)/2', mistake: 'half-angle-wrong', why: 'The 1/2 in sin²x = (1 − cos 2x)/2 was dropped, doubling everything.' },
      { latex: '\\frac{x}{2} - \\frac{\\sin x}{2} + C', expr: 'x/2 - sin(x)/2', mistake: 'half-angle-wrong', why: 'The angle was not doubled: sin²x = (1 − cos 2x)/2, not (1 − cos x)/2.' },
      { latex: '\\frac{\\sin^3 x}{3} + C', expr: 'sin(x)^3/3', mistake: 'u-choice-wrong', why: 'Power rule on sin x as if it were the variable; d/dx(sin³x/3) = sin²x cos x.' },
    ],
    correct: 2,
    explanation: '$\\int \\frac{1 - \\cos 2x}{2}\\,dx = \\frac{x}{2} - \\frac{1}{2}\\cdot\\frac{\\sin 2x}{2} + C = \\frac{x}{2} - \\frac{\\sin 2x}{4} + C$.',
    check: { kind: 'antiderivative', integrand: 'sin(x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-026',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\cos^2(2x)' },
    options: [
      { latex: '\\frac{x}{2} + \\frac{\\sin 4x}{2} + C', expr: 'x/2 + sin(4*x)/2', mistake: 'inner-constant-factor-missing', why: '∫cos 4x dx = ¼ sin 4x; the 1/4 from the inner 4x was dropped.' },
      { latex: '\\frac{x}{2} + \\frac{\\sin 4x}{4} + C', expr: 'x/2 + sin(4*x)/4', mistake: 'inner-constant-factor-missing', why: 'Divided by 2 (the constant inside the original cos 2x) instead of 4, the constant inside cos 4x.' },
      { latex: '\\frac{x}{2} + \\frac{\\sin 2x}{4} + C', expr: 'x/2 + sin(2*x)/4', mistake: 'half-angle-wrong', why: 'cos²(2x) = (1 + cos 4x)/2; the angle must double from 2x to 4x.' },
      { latex: '\\frac{x}{2} - \\frac{\\sin 4x}{8} + C', expr: 'x/2 - sin(4*x)/8', mistake: 'half-angle-wrong', why: 'Used the sine identity (1 − cos 4x)/2 for a cosine.' },
      { latex: 'x + \\frac{\\sin 4x}{4} + C', expr: 'x + sin(4*x)/4', mistake: 'half-angle-wrong', why: 'The 1/2 in the identity was dropped, doubling the result.' },
      { latex: '\\frac{x}{2} + \\frac{\\sin 4x}{8} + C', expr: 'x/2 + sin(4*x)/8' },
    ],
    correct: 5,
    explanation: '$\\cos^2(2x) = \\frac{1 + \\cos 4x}{2}$, and $\\int \\cos 4x\\,dx = \\frac{\\sin 4x}{4}$, so the result is $\\frac{x}{2} + \\frac{\\sin 4x}{8} + C$.',
    check: { kind: 'antiderivative', integrand: 'cos(2*x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-027',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sin^2 x\\cos^2 x' },
    options: [
      { latex: '\\frac{x}{8} - \\frac{\\sin 4x}{32} + C', expr: 'x/8 - sin(4*x)/32' },
      { latex: '\\frac{x}{8} + \\frac{\\sin 4x}{32} + C', expr: 'x/8 + sin(4*x)/32', mistake: 'half-angle-wrong', why: 'sin²(2x) = (1 − cos 4x)/2; using 1 + cos 4x flips the sine term.' },
      { latex: '\\frac{x}{8} - \\frac{\\sin 4x}{8} + C', expr: 'x/8 - sin(4*x)/8', mistake: 'inner-constant-factor-missing', why: '∫cos 4x dx = ¼ sin 4x; the 1/4 was dropped.' },
      { latex: '\\frac{x}{8} - \\frac{\\sin 2x}{16} + C', expr: 'x/8 - sin(2*x)/16', mistake: 'half-angle-wrong', why: 'Reducing sin²(2x) needs cos 4x; using cos 2x does not double the angle.' },
      { latex: '\\frac{x}{2} - \\frac{\\sin 4x}{8} + C', expr: 'x/2 - sin(4*x)/8', mistake: 'double-angle-wrong', why: 'This integrates sin²(2x), i.e. it used sin x cos x = sin 2x and lost the factor (1/2)² = 1/4.' },
      { latex: '\\frac{x}{8} - \\frac{\\sin 4x}{16} + C', expr: 'x/8 - sin(4*x)/16', mistake: 'inner-constant-factor-missing', why: 'Divided by 2 instead of 4 when integrating cos 4x.' },
    ],
    correct: 0,
    explanation: '$\\sin^2 x\\cos^2 x = \\frac{1}{4}\\sin^2 2x = \\frac{1 - \\cos 4x}{8}$, which integrates to $\\frac{x}{8} - \\frac{\\sin 4x}{32} + C$.',
    check: { kind: 'antiderivative', integrand: 'sin(x)^2*cos(x)^2' },
    difficulty: 2,
  },

  // ───────────── antiderivatives: tangent / secant ─────────────
  {
    id: 'ti-f-020',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\tan^2 x' },
    options: [
      { latex: '\\tan x + x + C', expr: 'tan(x) + x', mistake: 'tan-sec-identity-direction', why: 'tan²x = sec²x − 1, not sec²x + 1.' },
      { latex: '\\tan x - x + C', expr: 'tan(x) - x' },
      { latex: 'x - \\tan x + C', expr: 'x - tan(x)', mistake: 'pythagorean-wrong', why: 'tan²x was rewritten as 1 − sec²x; the identity is tan²x = sec²x − 1.' },
      { latex: '\\sec x\\tan x - x + C', expr: 'sec(x)*tan(x) - x', mistake: 'trig-antiderivative-swapped', why: 'sec x tan x is d/dx(sec x); ∫sec²x dx = tan x.' },
      { latex: '\\frac{1}{3}\\tan^3 x + C', expr: 'tan(x)^3/3', mistake: 'u-choice-wrong', why: 'Power rule with u = tan x, but du = sec²x dx is not in the integrand.' },
    ],
    correct: 1,
    explanation: '$\\int (\\sec^2 x - 1)\\,dx = \\tan x - x + C$.',
    check: { kind: 'antiderivative', integrand: 'tan(x)^2' },
    difficulty: 1,
  },
  {
    id: 'ti-f-021',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sec^4 x' },
    options: [
      { latex: '\\frac{1}{3}\\tan^3 x - \\tan x + C', expr: 'tan(x)^3/3 - tan(x)', mistake: 'tan-sec-identity-direction', why: 'sec²x = tan²x + 1; writing tan²x − 1 gives ∫(u² − 1)du.' },
      { latex: '\\tan x - \\frac{1}{3}\\tan^3 x + C', expr: 'tan(x) - tan(x)^3/3', mistake: 'pythagorean-wrong', why: 'sec²x was rewritten as 1 − tan²x, the cosine-style pattern.' },
      { latex: '\\sec x + \\frac{1}{3}\\sec^3 x + C', expr: 'sec(x) + sec(x)^3/3', mistake: 'back-substitution-wrong', why: 'u was tan x, so u + u³/3 must become tan x + ⅓tan³x, not secants.' },
      { latex: '\\tan x + \\frac{1}{3}\\tan^3 x + C', expr: 'tan(x) + tan(x)^3/3' },
      { latex: '\\tan x + \\tan^3 x + C', expr: 'tan(x) + tan(x)^3', mistake: 'power-rule-int-coefficient', why: '∫u² du = u³/3; the 1/3 was dropped.' },
      { latex: '\\frac{1}{5}\\sec^5 x + C', expr: 'sec(x)^5/5', mistake: 'u-choice-wrong', why: 'Power rule on sec x, but its derivative sec x tan x is not in the integrand.' },
    ],
    correct: 3,
    explanation: 'Save $\\sec^2 x$: $\\int (\\tan^2 x + 1)\\sec^2 x\\,dx$, $u = \\tan x$: $\\int (u^2 + 1)\\,du = \\tan x + \\frac{1}{3}\\tan^3 x + C$.',
    check: { kind: 'antiderivative', integrand: 'sec(x)^4' },
    difficulty: 1,
  },
  {
    id: 'ti-f-022',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\tan^3 x\\sec x' },
    options: [
      { latex: '\\frac{1}{3}\\sec^3 x + \\sec x + C', expr: 'sec(x)^3/3 + sec(x)', mistake: 'tan-sec-identity-direction', why: 'tan²x = sec²x − 1; using sec²x + 1 flips the sign of the u term.' },
      { latex: '\\sec x - \\frac{1}{3}\\sec^3 x + C', expr: 'sec(x) - sec(x)^3/3', mistake: 'pythagorean-wrong', why: 'tan²x was rewritten as 1 − sec²x, which reverses both terms.' },
      { latex: '\\frac{1}{3}\\tan^3 x - \\tan x + C', expr: 'tan(x)^3/3 - tan(x)', mistake: 'back-substitution-wrong', why: 'u was sec x, so u³/3 − u must become secants, not tangents.' },
      { latex: '\\sec^3 x - \\sec x + C', expr: 'sec(x)^3 - sec(x)', mistake: 'power-rule-int-coefficient', why: '∫u² du = u³/3; the 1/3 was dropped.' },
      { latex: '\\frac{1}{3}\\sec^3 x - \\sec x + C', expr: 'sec(x)^3/3 - sec(x)' },
      { latex: '\\frac{1}{4}\\tan^4 x + C', expr: 'tan(x)^4/4', mistake: 'u-choice-wrong', why: 'Power rule with u = tan x needs du = sec²x dx, but only one sec x is present.' },
    ],
    correct: 4,
    explanation: 'Save $\\sec x\\tan x$: $\\int (\\sec^2 x - 1)\\sec x\\tan x\\,dx$, $u = \\sec x$: $\\int (u^2 - 1)\\,du = \\frac{1}{3}\\sec^3 x - \\sec x + C$.',
    check: { kind: 'antiderivative', integrand: 'tan(x)^3*sec(x)' },
    difficulty: 1,
  },
  {
    id: 'ti-f-023',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\tan x\\sec^3 x' },
    options: [
      { latex: '\\frac{1}{4}\\sec^4 x + C', expr: 'sec(x)^4/4', mistake: 'exponent-arithmetic', why: 'Saving sec x tan x uses up one secant, leaving sec²x = u²; keeping sec³x gives u³.' },
      { latex: '\\frac{1}{2}\\sec^2 x + C', expr: 'sec(x)^2/2', mistake: 'exponent-arithmetic', why: 'Two secants were removed instead of one: tan x sec³x = sec²x·(sec x tan x).' },
      { latex: '\\frac{1}{3}\\tan^3 x + C', expr: 'tan(x)^3/3', mistake: 'back-substitution-wrong', why: 'u was sec x, so u³/3 must become ⅓sec³x.' },
      { latex: '-\\frac{1}{3}\\sec^3 x + C', expr: '-sec(x)^3/3', mistake: 'du-derivative-wrong', why: 'd/dx sec x = +sec x tan x; the minus sign belongs to csc x.' },
      { latex: '\\frac{1}{3}\\sec^3 x + C', expr: 'sec(x)^3/3' },
      { latex: '\\sec^3 x + C', expr: 'sec(x)^3', mistake: 'power-rule-int-coefficient', why: '∫u² du = u³/3; the 1/3 was dropped.' },
    ],
    correct: 4,
    explanation: '$\\tan x\\sec^3 x\\,dx = \\sec^2 x\\cdot\\sec x\\tan x\\,dx = u^2\\,du$ with $u = \\sec x$, giving $\\frac{1}{3}\\sec^3 x + C$.',
    check: { kind: 'antiderivative', integrand: 'tan(x)*sec(x)^3' },
    difficulty: 1,
  },
  {
    id: 'ti-f-024',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sec^4\\frac{x}{2}' },
    options: [
      { latex: '\\tan\\frac{x}{2} + \\frac{1}{3}\\tan^3\\frac{x}{2} + C', expr: 'tan(x/2) + tan(x/2)^3/3', mistake: 'inner-constant-factor-missing', why: 'With w = x/2, dx = 2 dw; the factor 2 was dropped.' },
      { latex: '\\frac{1}{2}\\tan\\frac{x}{2} + \\frac{1}{6}\\tan^3\\frac{x}{2} + C', expr: 'tan(x/2)/2 + tan(x/2)^3/6', mistake: 'inner-constant-factor-missing', why: 'Multiplied by the inner 1/2 instead of dividing by it (dx = 2 dw).' },
      { latex: '2\\tan\\frac{x}{2} - \\frac{2}{3}\\tan^3\\frac{x}{2} + C', expr: '2*tan(x/2) - 2*tan(x/2)^3/3', mistake: 'pythagorean-wrong', why: 'sec²w = 1 + tan²w, not 1 − tan²w.' },
      { latex: '2\\tan\\frac{x}{2} + \\frac{2}{3}\\tan^3\\frac{x}{2} + C', expr: '2*tan(x/2) + 2*tan(x/2)^3/3' },
      { latex: '\\frac{2}{3}\\tan^3\\frac{x}{2} - 2\\tan\\frac{x}{2} + C', expr: '2*tan(x/2)^3/3 - 2*tan(x/2)', mistake: 'tan-sec-identity-direction', why: 'sec²w = tan²w + 1; using tan²w − 1 flips the linear term.' },
      { latex: '2\\sec\\frac{x}{2} + \\frac{2}{3}\\sec^3\\frac{x}{2} + C', expr: '2*sec(x/2) + 2*sec(x/2)^3/3', mistake: 'back-substitution-wrong', why: 'u was tan(x/2); the answer must be in tangents.' },
    ],
    correct: 3,
    explanation: '$w = \\frac{x}{2}$, $dx = 2\\,dw$: $2\\int \\sec^4 w\\,dw = 2\\left(\\tan w + \\frac{1}{3}\\tan^3 w\\right) + C$.',
    check: { kind: 'antiderivative', integrand: 'sec(x/2)^4' },
    difficulty: 2,
  },
  {
    id: 'ti-f-025',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\tan^3 x' },
    options: [
      { latex: '\\frac{1}{2}\\tan^2 x - \\ln|\\cos x| + C', expr: 'tan(x)^2/2 - log(abs(cos(x)))', mistake: 'tan-antiderivative-wrong', why: '∫tan x dx = −ln|cos x|, so subtracting it gives +ln|cos x|; the sign of ∫tan x was flipped.' },
      { latex: '-\\frac{1}{2}\\tan^2 x - \\ln|\\cos x| + C', expr: '-tan(x)^2/2 - log(abs(cos(x)))', mistake: 'pythagorean-wrong', why: 'tan²x was replaced by 1 − sec²x, which reverses both pieces.' },
      { latex: '\\tan^2 x + \\ln|\\cos x| + C', expr: 'tan(x)^2 + log(abs(cos(x)))', mistake: 'power-rule-int-coefficient', why: '∫u du = u²/2 with u = tan x; the 1/2 was dropped.' },
      { latex: '\\frac{1}{2}\\tan^2 x + \\ln|\\sin x| + C', expr: 'tan(x)^2/2 + log(abs(sin(x)))', mistake: 'tan-antiderivative-wrong', why: '∫tan x dx was taken as −ln|sin x|; the logarithm must hold cos x, whose derivative −sin x appears.' },
      { latex: '\\frac{1}{4}\\tan^4 x + C', expr: 'tan(x)^4/4', mistake: 'u-choice-wrong', why: 'Power rule with u = tan x, but du = sec²x dx is not in the integrand.' },
      { latex: '\\frac{1}{2}\\tan^2 x + \\ln|\\cos x| + C', expr: 'tan(x)^2/2 + log(abs(cos(x)))' },
    ],
    correct: 5,
    explanation: '$\\int \\tan x(\\sec^2 x - 1)\\,dx = \\frac{1}{2}\\tan^2 x - (-\\ln|\\cos x|) + C$; the form $\\frac12\\sec^2 x + \\ln|\\cos x|$ differs only by a constant.',
    check: { kind: 'antiderivative', integrand: 'tan(x)^3' },
    difficulty: 2,
  },
  {
    id: 'ti-f-028',
    topic: 'trig-integrals',
    kind: 'antiderivative',
    prompt: { latex: '\\sec^3 x' },
    options: [
      { latex: '\\frac{1}{2}\\sec x\\tan x - \\frac{1}{2}\\ln|\\sec x + \\tan x| + C', expr: 'sec(x)*tan(x)/2 - log(abs(sec(x) + tan(x)))/2', mistake: 'tan-sec-identity-direction', why: 'Inside the IBP, tan²x = sec²x − 1; using sec²x + 1 flips the sign of the ∫sec x term.' },
      { latex: '\\sec x\\tan x + \\ln|\\sec x + \\tan x| + C', expr: 'sec(x)*tan(x) + log(abs(sec(x) + tan(x)))', mistake: 'ibp-cyclic-algebra', why: 'Moving ∫sec³x to the left gives 2∫sec³x; the division by 2 was skipped.' },
      { latex: '\\frac{1}{2}\\sec x\\tan x + \\ln|\\sec x + \\tan x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(sec(x) + tan(x)))', mistake: 'ibp-cyclic-algebra', why: 'Only sec x tan x was divided by 2; both terms must be halved.' },
      { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(sec(x)))/2', mistake: 'sec-antiderivative-wrong', why: '∫sec x dx = ln|sec x + tan x|; ln|sec x| is ∫tan x dx.' },
      { latex: '\\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x + \\tan x| + C', expr: 'sec(x)*tan(x)/2 + log(abs(sec(x) + tan(x)))/2' },
      { latex: '\\frac{1}{4}\\sec^4 x + C', expr: 'sec(x)^4/4', mistake: 'sec-odd-power-strategy', why: 'The power rule on sec x ignores du = sec x tan x dx; an odd power of secant alone needs integration by parts.' },
    ],
    correct: 4,
    explanation: 'IBP ($u = \\sec x$, $dv = \\sec^2 x\\,dx$) gives $I = \\sec x\\tan x - I + \\int \\sec x\\,dx$, so $I = \\frac{1}{2}\\sec x\\tan x + \\frac{1}{2}\\ln|\\sec x + \\tan x| + C$.',
    check: { kind: 'antiderivative', integrand: 'sec(x)^3' },
    difficulty: 2,
  },
  // @@END-FLASH@@
];

/** Parameterized generators (optional). */
export const generators: FlashGenerator[] = [];
