import type { FlashGenerator, FlashItem } from '../types';

/** Flash Drill items for topic "volumes-disks". Authored by content-author; verified by math-verifier. */
export const flash: FlashItem[] = [
  // ───────────── formulas, slice areas, concepts ─────────────
  {
    id: 'vd-f-001',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'A vertical slice of a region runs from $y = 2$ up to $y = 5$. The region is rotated about the line $y = -1$. What is the area of the washer this slice sweeps out?' },
    options: [
      { latex: '27\\pi', expr: '27*pi' },
      { latex: '21\\pi', expr: '21*pi', mistake: 'axis-shift-missing', why: 'This is $\\pi(5^2 - 2^2)$: the radii were measured from the x-axis; from $y = -1$ they are $5 + 1 = 6$ and $2 + 1 = 3$.' },
      { latex: '9\\pi', expr: '9*pi', mistake: 'washer-difference-squared', why: 'This is $\\pi(6 - 3)^2$: the difference of the radii was squared instead of subtracting the squares.' },
      { latex: '3\\pi', expr: '3*pi', mistake: 'radius-not-squared', why: 'This is $\\pi(6 - 3)$: the radii were subtracted but never squared.' },
      { latex: '15\\pi', expr: '15*pi', mistake: 'axis-shift-sign', why: 'This is $\\pi(4^2 - 1^2)$: subtracting 1 from each height measures distance to $y = 1$, not to $y = -1$.' },
      { latex: '36\\pi', expr: '36*pi', mistake: 'washer-as-disk', why: 'This is $\\pi \\cdot 6^2$: the gap between the axis and the bottom of the slice (a hole of radius 3) was ignored.' },
    ],
    correct: 0,
    explanation: 'Distances to $y = -1$: $R = 5 + 1 = 6$ and $r = 2 + 1 = 3$, so $A = \\pi(6^2 - 3^2) = 27\\pi$.',
    check: { kind: 'value', expected: 'pi*(6^2 - 3^2)' },
    difficulty: 1,
  },
  {
    id: 'vd-f-002',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'The region under $y = 3 - x$ for $0 \\le x \\le 3$ is rotated about the x-axis. What is the area $A(x)$ of the cross-section at $x$?' },
    options: [
      { latex: 'A(x) = \\pi(3 - x)^2', expr: 'pi*(3 - x)^2' },
      { latex: 'A(x) = \\pi(3 - x)', expr: 'pi*(3 - x)', mistake: 'radius-not-squared', why: 'The radius $3 - x$ must be squared: a disk has area $\\pi R^2$.' },
      { latex: 'A(x) = (3 - x)^2', expr: '(3 - x)^2', mistake: 'pi-missing', why: 'A disk of radius $R$ has area $\\pi R^2$; the factor $\\pi$ was dropped.' },
      { latex: 'A(x) = \\pi(9 - x^2)', expr: 'pi*(9 - x^2)', mistake: 'algebra-error', why: '$(3 - x)^2$ was expanded as $9 - x^2$; the cross term $-6x$ is missing.' },
      { latex: 'A(x) = 2\\pi(3 - x)', expr: '2*pi*(3 - x)', mistake: 'formula-swapped', why: '$2\\pi R$ is the circumference of the disk, not its area.' },
      { latex: 'A(x) = 2\\pi x(3 - x)', expr: '2*pi*x*(3 - x)', mistake: 'method-formula-swapped', why: '$2\\pi x (3 - x)$ is a shell (radius $x$, height $3 - x$) for rotation about the y-axis, not a disk perpendicular to the x-axis.' },
    ],
    correct: 0,
    explanation: 'The slice at $x$ is a disk whose radius is the distance from the x-axis to the line, $R = 3 - x$, so $A(x) = \\pi(3 - x)^2$.',
    check: { kind: 'value', expected: 'pi*(3 - x)^2' },
    difficulty: 1,
  },
  {
    id: 'vd-f-003',
    topic: 'volumes-disks',
    kind: 'formula',
    prompt: { text: 'A cross-section is an equilateral triangle with side length $s$. What is its area?' },
    options: [
      { latex: '\\frac{\\sqrt{3}}{4}s^2', expr: 'sqrt(3)/4*s^2' },
      { latex: '\\frac{\\sqrt{3}}{4}s', expr: 'sqrt(3)/4*s', mistake: 'formula-wrong-power', why: 'The side must be squared: an area scales with length squared.' },
      { latex: '\\frac{\\sqrt{3}}{2}s^2', expr: 'sqrt(3)/2*s^2', mistake: 'formula-missing-factor', why: 'Base times height is $s \\cdot \\frac{\\sqrt{3}}{2}s$; the $\\frac12$ of the triangle formula was dropped.' },
      { latex: '\\frac{1}{2}s^2', expr: 's^2/2', mistake: 'cross-section-area-wrong', why: 'This is $\\frac12 \\cdot s \\cdot s$, which takes the height equal to the side; the height is $\\frac{\\sqrt{3}}{2}s$.' },
      { latex: 's^2', expr: 's^2', mistake: 'cross-section-area-wrong', why: '$s^2$ is the area of a square with side $s$, not of a triangle.' },
      { latex: '\\frac{\\sqrt{3}}{2}s', expr: 'sqrt(3)/2*s', mistake: 'cross-section-area-wrong', why: '$\\frac{\\sqrt{3}}{2}s$ is the height of the triangle, not its area.' },
    ],
    correct: 0,
    explanation: 'The height is $\\frac{\\sqrt{3}}{2}s$, so the area is $\\frac12 \\cdot s \\cdot \\frac{\\sqrt{3}}{2}s = \\frac{\\sqrt{3}}{4}s^2$.',
    variable: 's',
    check: { kind: 'identity', lhs: 'sqrt(3)/4*s^2' },
    difficulty: 1,
  },
  {
    id: 'vd-f-004',
    topic: 'volumes-disks',
    kind: 'formula',
    prompt: { text: 'A cross-section is a semicircle whose diameter is a segment of length $s$ lying in the base. What is its area?' },
    options: [
      { latex: '\\frac{\\pi}{8}s^2', expr: 'pi/8*s^2' },
      { latex: '\\frac{\\pi}{2}s^2', expr: 'pi/2*s^2', mistake: 'diameter-as-radius', why: '$s$ is the diameter, so the radius is $\\frac{s}{2}$; $\\frac12\\pi s^2$ uses $s$ as the radius.' },
      { latex: '\\frac{\\pi}{4}s^2', expr: 'pi/4*s^2', mistake: 'cross-section-area-wrong', why: '$\\pi\\left(\\frac{s}{2}\\right)^2$ is the whole circle; a semicircle is half of it.' },
      { latex: '\\frac{\\pi}{4}s', expr: 'pi/4*s', mistake: 'radius-not-squared', why: '$\\frac12\\pi \\cdot \\frac{s}{2}$ leaves the radius unsquared; the area needs $\\left(\\frac{s}{2}\\right)^2$.' },
      { latex: '\\frac{\\pi}{2}s', expr: 'pi/2*s', mistake: 'formula-swapped', why: '$\\frac{\\pi}{2}s$ is the length of the semicircular arc, not the area.' },
    ],
    correct: 0,
    explanation: 'The radius is $\\frac{s}{2}$, so the area is $\\frac12\\pi\\left(\\frac{s}{2}\\right)^2 = \\frac{\\pi}{8}s^2$.',
    variable: 's',
    check: { kind: 'identity', lhs: 'pi/8*s^2' },
    difficulty: 1,
  },
  {
    id: 'vd-f-005',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'The base of a solid is the disk $x^2 + y^2 \\le 1$. Cross-sections perpendicular to the x-axis are squares with one side in the base. What is the area $A(x)$ of the cross-section at $x$?' },
    options: [
      { latex: 'A(x) = 4(1 - x^2)', expr: '4*(1 - x^2)' },
      { latex: 'A(x) = 1 - x^2', expr: '1 - x^2', mistake: 'coefficient-mishandled', why: 'The side is the whole chord from $y = -\\sqrt{1-x^2}$ to $y = \\sqrt{1-x^2}$; using the half-chord $\\sqrt{1-x^2}$ loses a factor 4.' },
      { latex: 'A(x) = 2(1 - x^2)', expr: '2*(1 - x^2)', mistake: 'algebra-error', why: '$\\left(2\\sqrt{1-x^2}\\right)^2 = 4(1 - x^2)$; the factor 2 was not squared.' },
      { latex: 'A(x) = 2\\sqrt{1 - x^2}', expr: '2*sqrt(1 - x^2)', mistake: 'cross-section-area-wrong', why: 'That is the side length; the area of a square is side squared.' },
      { latex: 'A(x) = \\pi(1 - x^2)', expr: 'pi*(1 - x^2)', mistake: 'formula-swapped', why: '$\\pi(1 - x^2)$ is a disk of radius $\\sqrt{1-x^2}$ (a slice of a sphere), not a square.' },
    ],
    correct: 0,
    explanation: 'At $x$ the base runs from $y = -\\sqrt{1-x^2}$ to $y = \\sqrt{1-x^2}$, so the side is $2\\sqrt{1-x^2}$ and $A(x) = 4(1 - x^2)$.',
    domain: [-0.9, 0.9],
    check: { kind: 'value', expected: '(2*sqrt(1 - x^2))^2' },
    difficulty: 1,
  },
  {
    id: 'vd-f-006',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'The washer area is $\\pi(R^2 - r^2)$, not $\\pi(R - r)^2$. Which reason is correct?' },
    options: [
      { text: 'A washer is a disk of radius $R$ with a disk of radius $r$ removed, so its area is $\\pi R^2 - \\pi r^2$.' },
      { text: 'A washer is a ring of width $R - r$, so its area is $\\pi$ times the square of that width.', mistake: 'washer-difference-squared', why: '$\\pi(R - r)^2$ is the area of a disk of radius $R - r$, which is much smaller than the ring.' },
      { text: 'Only the outer edge sweeps out area, so the area is $\\pi R^2$ and the hole does not matter.', mistake: 'washer-as-disk', why: 'The hole of radius $r$ is empty space; its area $\\pi r^2$ must be removed.' },
      { text: 'The ring is $\\pi$ times its width, so its area is $\\pi(R - r)$.', mistake: 'radius-not-squared', why: 'An area needs squared lengths; $\\pi(R - r)$ has units of length, not area.' },
      { text: 'The inner disk is the larger one, so the area is $\\pi(r^2 - R^2)$.', mistake: 'radii-swapped', why: '$R$ is the outer, larger radius; $\\pi(r^2 - R^2)$ is negative.' },
      { text: 'Unrolled, the ring is a strip of length $2\\pi r$ and width $R - r$, so its area is $2\\pi r(R - r)$.', mistake: 'method-formula-swapped', why: 'That is the thin-shell approximation $2\\pi \\cdot$ radius $\\cdot$ thickness; it underestimates a ring of finite width.' },
    ],
    correct: 0,
    explanation: 'Area of the washer = (outer disk) $-$ (hole) $= \\pi R^2 - \\pi r^2 = \\pi(R^2 - r^2)$.',
    check: { kind: 'none', reason: 'conceptual; options are explanations' },
    difficulty: 1,
  },
  {
    id: 'vd-f-007',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'Which rotation produces solid disks (no hole) when the slices are taken perpendicular to the axis of rotation?' },
    options: [
      { text: 'The region between $y = x^2$ and $y = 1$, rotated about the line $y = 1$' },
      { text: 'The region between $y = x^2$ and $y = 1$, rotated about the x-axis', mistake: 'washer-as-disk', why: 'The parabola touches the x-axis only at $x = 0$; every other slice starts $x^2$ above the axis, so it has a hole.' },
      { text: 'The region under $y = x^2 + 1$ on $[0, 1]$, rotated about the line $y = -1$', mistake: 'washer-as-disk', why: 'The bottom edge $y = 0$ is 1 unit above the axis $y = -1$, so every slice has a hole of radius 1.' },
      { text: 'The region between $y = x$ and $y = x^2$, rotated about the x-axis', mistake: 'washer-as-disk', why: 'For $0 < x < 1$ the lower curve $y = x^2$ stays above the axis, leaving a hole of radius $x^2$.' },
      { text: 'The region between $y = 2x$ and $y = x^2$, rotated about the y-axis', mistake: 'washer-as-disk', why: 'Horizontal slices run from $x = \\frac{y}{2}$ to $x = \\sqrt{y}$ and never reach the y-axis, so each has a hole of radius $\\frac{y}{2}$.' },
    ],
    correct: 0,
    explanation: 'Slices are disks exactly when they reach the axis: the line $y = 1$ is the top edge of that region, so each slice has radius $1 - x^2$ and no hole.',
    check: { kind: 'none', reason: 'conceptual; options describe regions and axes' },
    difficulty: 2,
  },
  {
    id: 'vd-f-008',
    topic: 'volumes-disks',
    kind: 'formula',
    prompt: { text: 'Suppose $0 \\le f(x) \\le 5$ on $[a, b]$. The region between $y = f(x)$ and the x-axis on $[a, b]$ is rotated about the line $y = 7$. Which integral gives the volume?' },
    options: [
      { latex: '\\pi\\int_a^b \\left[7^2 - (7 - f(x))^2\\right]dx' },
      { latex: '\\pi\\int_a^b \\left[(7 - f(x))^2 - 7^2\\right]dx', mistake: 'radii-swapped', why: 'The x-axis edge is 7 units from the axis and the curve only $7 - f(x)$, so 7 is the outer radius.' },
      { latex: '\\pi\\int_a^b 7^2\\,dx', mistake: 'washer-as-disk', why: 'The region stops at the curve, $7 - f(x)$ below the axis, so each slice has a hole of radius $7 - f(x)$.' },
      { latex: '\\pi\\int_a^b \\left[7^2 - f(x)^2\\right]dx', mistake: 'radius-is-function-value', why: 'The inner radius is the distance from the curve to $y = 7$, which is $7 - f(x)$, not the height $f(x)$.' },
      { latex: '\\pi\\int_a^b \\left[(f(x) + 7)^2 - 7^2\\right]dx', mistake: 'axis-shift-sign', why: 'Adding 7 measures distance to $y = -7$; the curve is below $y = 7$, so its distance is $7 - f(x)$.' },
      { latex: '\\pi\\int_a^b f(x)^2\\,dx', mistake: 'axis-shift-missing', why: 'This is the disk volume for rotation about the x-axis; the axis here is $y = 7$.' },
    ],
    correct: 0,
    explanation: 'The axis is above the region: the x-axis is farthest ($R = 7$) and the curve nearest ($r = 7 - f(x)$), so $V = \\pi\\int_a^b [7^2 - (7 - f(x))^2]\\,dx$.',
    check: { kind: 'none', reason: 'general f(x); compares setups, no numeric value' },
    difficulty: 2,
  },
  {
    id: 'vd-f-009',
    topic: 'volumes-disks',
    kind: 'formula',
    prompt: { text: 'The region between $y = f(x) \\ge 0$ and the x-axis on $[a, b]$ is rotated about the line $y = -1$. Which integral gives the volume?' },
    options: [
      { latex: '\\pi\\int_a^b \\left[(f(x) + 1)^2 - 1^2\\right]dx' },
      { latex: '\\pi\\int_a^b \\left[(f(x) - 1)^2 - 1^2\\right]dx', mistake: 'axis-shift-sign', why: 'The distance from $y = f(x)$ down to $y = -1$ is $f(x) - (-1) = f(x) + 1$.' },
      { latex: '\\pi\\int_a^b (f(x) + 1)^2\\,dx', mistake: 'washer-as-disk', why: 'The bottom edge (the x-axis) is 1 unit above the axis, so each slice has a hole of radius 1.' },
      { latex: '\\pi\\int_a^b f(x)^2\\,dx', mistake: 'axis-shift-missing', why: 'This is the disk formula about the x-axis; about $y = -1$ both edges are 1 unit farther away.' },
      { latex: '\\pi\\int_a^b \\left[1^2 - (f(x) + 1)^2\\right]dx', mistake: 'radii-swapped', why: 'The curve is farther from $y = -1$ than the x-axis is, so $f(x) + 1$ is the outer radius.' },
    ],
    correct: 0,
    explanation: 'Measured from $y = -1$: the curve is at distance $R = f(x) + 1$ and the x-axis at $r = 1$, so each slice is a washer $\\pi[(f(x)+1)^2 - 1^2]$.',
    check: { kind: 'none', reason: 'general f(x); compares setups, no numeric value' },
    difficulty: 2,
  },
  {
    id: 'vd-f-010',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'A washer integral for a volume came out negative. Which setup error causes that?' },
    options: [
      { text: 'The inner and outer radii were swapped, so $r^2 > R^2$ on the slices' },
      { text: 'The factor $\\pi$ was left out', mistake: 'pi-missing', why: 'Dropping $\\pi$ rescales the answer but cannot change its sign.' },
      { text: 'The radii were not squared, giving $\\pi(R - r)$', mistake: 'radius-not-squared', why: 'With $R \\ge r$, $\\pi(R - r)$ is still nonnegative; only $r > R$ flips the sign.' },
      { text: 'A disk was used where a washer was needed', mistake: 'washer-as-disk', why: 'Ignoring the hole makes the volume too large, never negative.' },
      { text: 'The slice area was written as $\\pi(R - r)^2$', mistake: 'washer-difference-squared', why: 'A square is never negative, so $\\pi(R - r)^2$ cannot produce a negative volume.' },
    ],
    correct: 0,
    explanation: 'Each washer area $\\pi(R^2 - r^2)$ is negative exactly when the inner radius is taken larger than the outer one.',
    check: { kind: 'none', reason: 'conceptual; options are error descriptions' },
    difficulty: 1,
  },
  {
    id: 'vd-f-011',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'The base of a solid is the region between $y = x^2$ and $y = 4$. Cross-sections perpendicular to the y-axis are squares. What is the side length of the square at height $y$?' },
    options: [
      { latex: 's = 2\\sqrt{y}', expr: '2*sqrt(y)' },
      { latex: 's = \\sqrt{y}', expr: 'sqrt(y)', mistake: 'coefficient-mishandled', why: 'At height $y$ the base runs from $x = -\\sqrt{y}$ to $x = \\sqrt{y}$; $\\sqrt{y}$ is only the right half.' },
      { latex: 's = 4 - x^2', expr: '4 - x^2', mistake: 'wrong-integration-variable', why: '$4 - x^2$ is the vertical chord for slices perpendicular to the x-axis; these slices are horizontal, so the side is a width written in $y$.' },
      { latex: 's = 2y^2', expr: '2*y^2', mistake: 'inverse-function-wrong', why: 'Solving $y = x^2$ for $x$ gives $x = \\pm\\sqrt{y}$, not $y^2$.' },
      { latex: 's = 4 - y', expr: '4 - y', mistake: 'wrong-integration-variable', why: '$4 - y$ is the vertical distance from the slice up to $y = 4$; the side of a horizontal slice is its horizontal width.' },
    ],
    correct: 0,
    explanation: 'At height $y$ the base spans $-\\sqrt{y} \\le x \\le \\sqrt{y}$, a width of $2\\sqrt{y}$.',
    variable: 'y',
    check: { kind: 'value', expected: '2*sqrt(y)' },
    difficulty: 1,
  },
  {
    id: 'vd-f-012',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'The base of a solid is the region between $y = 1 - x^2$ and the x-axis. Cross-sections perpendicular to the x-axis are squares with one side in the base. Which integral gives the volume?' },
    options: [
      { latex: '\\int_{-1}^{1} (1 - x^2)^2\\,dx', expr: 'integral((1 - x^2)^2, x, -1, 1)' },
      { latex: '\\pi\\int_{-1}^{1} (1 - x^2)^2\\,dx', expr: 'integral(pi*(1 - x^2)^2, x, -1, 1)', mistake: 'cross-section-area-wrong', why: 'A square of side $s$ has area $s^2$; the $\\pi$ belongs to circular slices.' },
      { latex: '\\int_{-1}^{1} (1 - x^2)\\,dx', expr: 'integral(1 - x^2, x, -1, 1)', mistake: 'cross-section-area-wrong', why: '$1 - x^2$ is the side length; the square has area side squared.' },
      { latex: '\\int_{-1}^{1} \\left(2(1 - x^2)\\right)^2dx', expr: 'integral((2*(1 - x^2))^2, x, -1, 1)', mistake: 'coefficient-mishandled', why: 'The side runs from $y = 0$ to $y = 1 - x^2$; doubling it (as for a base symmetric about the x-axis) quadruples the area.' },
      { latex: '\\int_0^1 (1 - x^2)^2\\,dx', expr: 'integral((1 - x^2)^2, x, 0, 1)', mistake: 'missing-intersection', why: 'The base spans $-1 \\le x \\le 1$ (where $1 - x^2 = 0$); starting at 0 drops the left half.' },
      { latex: '\\int_0^1 \\left(2\\sqrt{1 - y}\\right)^2dy', expr: 'integral((2*sqrt(1 - y))^2, y, 0, 1)', mistake: 'wrong-integration-variable', why: 'This stacks squares perpendicular to the y-axis (side $2\\sqrt{1-y}$); the slices here are perpendicular to the x-axis.' },
    ],
    correct: 0,
    explanation: 'The square at $x$ has side $1 - x^2$, so $A(x) = (1 - x^2)^2$, integrated over the base $-1 \\le x \\le 1$.',
    check: { kind: 'value', expected: '16/15' },
    difficulty: 1,
  },
  {
    id: 'vd-f-013',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'The base of a solid is the region between $y = x$ and $y = x^2$. Cross-sections perpendicular to the x-axis are semicircles whose diameters lie across the base. Which integral gives the volume?' },
    options: [
      { latex: '\\frac{\\pi}{8}\\int_0^1 (x - x^2)^2\\,dx', expr: 'pi/8*integral((x - x^2)^2, x, 0, 1)' },
      { latex: '\\frac{\\pi}{2}\\int_0^1 (x - x^2)^2\\,dx', expr: 'pi/2*integral((x - x^2)^2, x, 0, 1)', mistake: 'diameter-as-radius', why: '$x - x^2$ is the diameter; using it as the radius in $\\frac12\\pi r^2$ makes each slice 4 times too big.' },
      { latex: '\\frac{\\pi}{4}\\int_0^1 (x - x^2)^2\\,dx', expr: 'pi/4*integral((x - x^2)^2, x, 0, 1)', mistake: 'cross-section-area-wrong', why: '$\\pi\\left(\\frac{D}{2}\\right)^2 = \\frac{\\pi}{4}D^2$ is a full circle; a semicircle has half of that.' },
      { latex: '\\frac{\\pi}{4}\\int_0^1 (x - x^2)\\,dx', expr: 'pi/4*integral(x - x^2, x, 0, 1)', mistake: 'radius-not-squared', why: '$\\frac12\\pi r$ with $r = \\frac{x - x^2}{2}$ leaves the radius unsquared.' },
      { latex: '\\pi\\int_0^1 \\left[x^2 - (x^2)^2\\right]dx', expr: 'pi*integral(x^2 - (x^2)^2, x, 0, 1)', mistake: 'formula-swapped', why: 'This is the washer volume for rotating the base about the x-axis; here semicircles stand on the base instead.' },
      { latex: '\\frac{\\pi}{8}\\int_0^1 (x + x^2)^2\\,dx', expr: 'pi/8*integral((x + x^2)^2, x, 0, 1)', mistake: 'sum-instead-of-difference', why: 'The diameter is the distance between the curves, top minus bottom: $x - x^2$.' },
    ],
    correct: 0,
    explanation: 'Diameter $D = x - x^2$, radius $\\frac{D}{2}$, semicircle area $\\frac12\\pi\\left(\\frac{D}{2}\\right)^2 = \\frac{\\pi}{8}D^2$, integrated for $0 \\le x \\le 1$.',
    check: { kind: 'value', expected: 'pi/240' },
    difficulty: 2,
  },
  {
    id: 'vd-f-014',
    topic: 'volumes-disks',
    kind: 'concept',
    prompt: { text: 'The base of a solid is the region between $y = x^2$ and $y = 4$. Cross-sections perpendicular to the y-axis are squares. Which integral gives the volume?' },
    options: [
      { latex: '\\int_0^4 \\left(2\\sqrt{y}\\right)^2dy', expr: 'integral((2*sqrt(y))^2, y, 0, 4)' },
      { latex: '\\int_0^4 \\left(\\sqrt{y}\\right)^2dy', expr: 'integral((sqrt(y))^2, y, 0, 4)', mistake: 'coefficient-mishandled', why: 'At height $y$ the base runs from $x = -\\sqrt{y}$ to $x = \\sqrt{y}$, a width of $2\\sqrt{y}$, not $\\sqrt{y}$.' },
      { latex: '\\int_{-2}^{2} (4 - x^2)^2\\,dx', expr: 'integral((4 - x^2)^2, x, -2, 2)', mistake: 'wrong-integration-variable', why: 'These are squares perpendicular to the x-axis (side $4 - x^2$); the slices here are perpendicular to the y-axis.' },
      { latex: '\\int_0^4 2\\sqrt{y}\\,dy', expr: 'integral(2*sqrt(y), y, 0, 4)', mistake: 'cross-section-area-wrong', why: '$2\\sqrt{y}$ is the side; the square has area $(2\\sqrt{y})^2 = 4y$.' },
      { latex: '\\pi\\int_0^4 \\left(\\sqrt{y}\\right)^2dy', expr: 'pi*integral((sqrt(y))^2, y, 0, 4)', mistake: 'formula-swapped', why: 'This is the disk volume for rotating the region about the y-axis; squares standing on the base have area side squared, with no $\\pi$.' },
    ],
    correct: 0,
    explanation: 'At height $y$ the square has side $2\\sqrt{y}$ and area $4y$; heights run from $y = 0$ to $y = 4$.',
    check: { kind: 'value', expected: '32' },
    difficulty: 2,
  },
