import type { Card, CardSection } from '../types';

/** The nine filter groups, in whiteboard order, with their chip labels. */
export const CARD_SECTIONS: readonly { id: CardSection; label: string }[] = [
  { id: 'derivatives', label: 'Derivatives' },
  { id: 'antiderivatives', label: 'Antiderivatives' },
  { id: 'pythagorean', label: 'Pythagorean' },
  { id: 'double-angle', label: 'Double-angle' },
  { id: 'half-angle', label: 'Half-angle' },
  { id: 'trig-sub', label: 'Trig sub' },
  { id: 'area-volume', label: 'Area & volume' },
  { id: 'arc-length', label: 'Arc length' },
  { id: 'ibp', label: 'IBP' },
];

/** Flashcard deck (whiteboard formulas). Authored by content-author; verified by math-verifier. */
export const CARDS: Card[] = [
  // ── 1. Derivatives (front = f(x); the UI frames it as d/dx[f(x)]) ──
  {
    id: 'card-derivatives-01',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\sin x' },
    back: { latex: '\\cos x', expr: 'cos(x)' },
    check: { kind: 'derivative', of: 'sin(x)' },
  },
  {
    id: 'card-derivatives-02',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\cos x' },
    back: { latex: '-\\sin x', expr: '-sin(x)' },
    check: { kind: 'derivative', of: 'cos(x)' },
  },
  {
    id: 'card-derivatives-03',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\tan x' },
    back: { latex: '\\sec^2 x', expr: 'sec(x)^2' },
    check: { kind: 'derivative', of: 'tan(x)' },
  },
  {
    id: 'card-derivatives-04',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\cot x' },
    back: { latex: '-\\csc^2 x', expr: '-csc(x)^2' },
    check: { kind: 'derivative', of: 'cot(x)' },
  },
  {
    id: 'card-derivatives-05',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\sec x' },
    back: { latex: '\\sec x \\tan x', expr: 'sec(x)*tan(x)' },
    check: { kind: 'derivative', of: 'sec(x)' },
  },
  {
    id: 'card-derivatives-06',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\csc x' },
    back: { latex: '-\\csc x \\cot x', expr: '-csc(x)*cot(x)' },
    check: { kind: 'derivative', of: 'csc(x)' },
  },
  {
    id: 'card-derivatives-07',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\arcsin x' },
    back: { latex: '\\frac{1}{\\sqrt{1 - x^2}}', expr: '1/sqrt(1 - x^2)' },
    check: { kind: 'derivative', of: 'asin(x)' },
  },
  {
    id: 'card-derivatives-08',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\arccos x' },
    back: { latex: '-\\frac{1}{\\sqrt{1 - x^2}}', expr: '-1/sqrt(1 - x^2)' },
    check: { kind: 'derivative', of: 'acos(x)' },
  },
  {
    id: 'card-derivatives-09',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\arctan x' },
    back: { latex: '\\frac{1}{1 + x^2}', expr: '1/(1 + x^2)' },
    check: { kind: 'derivative', of: 'atan(x)' },
  },
  {
    id: 'card-derivatives-10',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\operatorname{arcsec} x' },
    back: { latex: '\\frac{1}{|x|\\sqrt{x^2 - 1}}', expr: '1/(abs(x)*sqrt(x^2-1))' },
    check: { kind: 'derivative', of: 'asec(x)' },
    // both signs of x are sampled; points with |x| < 1 are outside the domain and skipped
    domain: [-3, 3],
  },
  {
    id: 'card-derivatives-11',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: 'e^x' },
    back: { latex: 'e^x', expr: 'exp(x)' },
    check: { kind: 'derivative', of: 'exp(x)' },
  },
  {
    id: 'card-derivatives-12',
    category: 'Derivatives',
    section: 'derivatives',
    kind: 'derivative',
    front: { latex: '\\ln x' },
    back: { latex: '\\frac{1}{x}', expr: '1/x' },
    check: { kind: 'derivative', of: 'log(x)' },
  },

  // ── 2. Antiderivatives (front = integrand; the UI frames it as ∫ f dx) ──
  {
    id: 'card-antiderivatives-01',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\sin x' },
    back: { latex: '-\\cos x + C', expr: '-cos(x)' },
    check: { kind: 'antiderivative', integrand: 'sin(x)' },
  },
  {
    id: 'card-antiderivatives-02',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\cos x' },
    back: { latex: '\\sin x + C', expr: 'sin(x)' },
    check: { kind: 'antiderivative', integrand: 'cos(x)' },
  },
  {
    id: 'card-antiderivatives-03',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\sec^2 x' },
    back: { latex: '\\tan x + C', expr: 'tan(x)' },
    check: { kind: 'antiderivative', integrand: 'sec(x)^2' },
  },
  {
    id: 'card-antiderivatives-04',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\sec x \\tan x' },
    back: { latex: '\\sec x + C', expr: 'sec(x)' },
    check: { kind: 'antiderivative', integrand: 'sec(x)*tan(x)' },
  },
  {
    id: 'card-antiderivatives-05',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\tan x' },
    back: { latex: '\\ln|\\sec x| + C', also: '-\\ln|\\cos x| + C', expr: 'log(abs(sec(x)))' },
    check: { kind: 'antiderivative', integrand: 'tan(x)' },
  },
  {
    id: 'card-antiderivatives-06',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\cot x' },
    back: { latex: '\\ln|\\sin x| + C', expr: 'log(abs(sin(x)))' },
    check: { kind: 'antiderivative', integrand: 'cot(x)' },
  },
  {
    id: 'card-antiderivatives-07',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\sec x' },
    back: { latex: '\\ln|\\sec x + \\tan x| + C', expr: 'log(abs(sec(x) + tan(x)))' },
    check: { kind: 'antiderivative', integrand: 'sec(x)' },
  },
  {
    id: 'card-antiderivatives-08',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\csc x' },
    back: { latex: '-\\ln|\\csc x + \\cot x| + C', expr: '-log(abs(csc(x) + cot(x)))' },
    check: { kind: 'antiderivative', integrand: 'csc(x)' },
  },
  {
    id: 'card-antiderivatives-09',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\frac{1}{x}' },
    back: { latex: '\\ln|x| + C', expr: 'log(abs(x))' },
    check: { kind: 'antiderivative', integrand: '1/x' },
  },
  {
    id: 'card-antiderivatives-10',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\frac{1}{1 + x^2}' },
    back: { latex: '\\arctan x + C', expr: 'atan(x)' },
    check: { kind: 'antiderivative', integrand: '1/(1 + x^2)' },
  },
  {
    id: 'card-antiderivatives-11',
    category: 'Antiderivatives',
    section: 'antiderivatives',
    kind: 'antiderivative',
    front: { latex: '\\frac{1}{\\sqrt{1 - x^2}}' },
    back: { latex: '\\arcsin x + C', expr: 'asin(x)' },
    check: { kind: 'antiderivative', integrand: '1/sqrt(1 - x^2)' },
  },

  // ── 3. Pythagorean identities (front = left-hand side; the UI shows "LHS = ?") ──
  {
    id: 'card-pythagorean-01',
    category: 'Identities',
    section: 'pythagorean',
    kind: 'identity',
    front: { latex: '\\sin^2 x + \\cos^2 x' },
    back: { latex: '1', expr: '1' },
    check: { kind: 'identity', lhs: 'sin(x)^2 + cos(x)^2' },
  },
  {
    id: 'card-pythagorean-02',
    category: 'Identities',
    section: 'pythagorean',
    kind: 'identity',
    front: { latex: '1 + \\tan^2 x' },
    back: { latex: '\\sec^2 x', expr: 'sec(x)^2' },
    check: { kind: 'identity', lhs: '1 + tan(x)^2' },
  },
  {
    id: 'card-pythagorean-03',
    category: 'Identities',
    section: 'pythagorean',
    kind: 'identity',
    front: { latex: '\\sec^2 x - 1' },
    back: { latex: '\\tan^2 x', expr: 'tan(x)^2' },
    check: { kind: 'identity', lhs: 'sec(x)^2 - 1' },
  },
  {
    id: 'card-pythagorean-04',
    category: 'Identities',
    section: 'pythagorean',
    kind: 'identity',
    front: { latex: '1 - \\sin^2 x' },
    back: { latex: '\\cos^2 x', expr: 'cos(x)^2' },
    check: { kind: 'identity', lhs: '1 - sin(x)^2' },
  },

  // ── 4. Double-angle identities ──
  {
    id: 'card-double-angle-01',
    category: 'Identities',
    section: 'double-angle',
    kind: 'identity',
    front: { latex: '\\sin 2x' },
    back: { latex: '2\\sin x \\cos x', expr: '2*sin(x)*cos(x)' },
    check: { kind: 'identity', lhs: 'sin(2*x)' },
  },
  {
    id: 'card-double-angle-02',
    category: 'Identities',
    section: 'double-angle',
    kind: 'identity',
    front: { latex: '\\cos 2x' },
    back: { latex: '\\cos^2 x - \\sin^2 x', expr: 'cos(x)^2 - sin(x)^2' },
    check: { kind: 'identity', lhs: 'cos(2*x)' },
  },

  // ── 5. Half-angle identities ──
  {
    id: 'card-half-angle-01',
    category: 'Identities',
    section: 'half-angle',
    kind: 'identity',
    front: { latex: '\\sin^2 x' },
    back: { latex: '\\frac{1 - \\cos 2x}{2}', expr: '(1 - cos(2*x))/2' },
    check: { kind: 'identity', lhs: 'sin(x)^2' },
  },
  {
    id: 'card-half-angle-02',
    category: 'Identities',
    section: 'half-angle',
    kind: 'identity',
    front: { latex: '\\cos^2 x' },
    back: { latex: '\\frac{1 + \\cos 2x}{2}', expr: '(1 + cos(2*x))/2' },
    check: { kind: 'identity', lhs: 'cos(x)^2' },
  },

  // ── 6. Trig substitution: rows sin / tan / sec; each row = sub, dx, radical, why ──
  // sin row: the radical check needs cos θ ≥ 0, so θ stays in [-1.3, 1.3] ⊂ (-π/2, π/2)
  {
    id: 'card-trig-sub-01',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'Trig sub for $\\sqrt{a^2 - x^2}$?' },
    back: { latex: 'x = a\\sin\\theta', expr: 'a*sin(theta)', checkExpr: 'a*cos(theta)' },
    check: { kind: 'identity', lhs: 'sqrt(a^2 - (a*sin(theta))^2)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [-1.3, 1.3] },
  },
  {
    id: 'card-trig-sub-02',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'dx when $x = a\\sin\\theta$?' },
    back: { latex: 'a\\cos\\theta\\,d\\theta', expr: 'a*cos(theta)*dtheta', checkExpr: 'a*cos(theta)' },
    check: { kind: 'derivative', of: 'a*sin(theta)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [-1.3, 1.3] },
  },
  {
    id: 'card-trig-sub-03',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'With $x = a\\sin\\theta$, $\\sqrt{a^2 - x^2}$ becomes?' },
    back: { latex: 'a\\cos\\theta', expr: 'a*cos(theta)' },
    check: { kind: 'identity', lhs: 'sqrt(a^2 - (a*sin(theta))^2)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [-1.3, 1.3] },
  },
  {
    id: 'card-trig-sub-04',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'Why sin for $a^2 - x^2$?' },
    back: { latex: '1 - \\sin^2\\theta = \\cos^2\\theta', expr: 'cos(theta)^2' },
    check: { kind: 'identity', lhs: '1 - sin(theta)^2' },
    variable: 'theta',
    domain: { theta: [-1.3, 1.3] },
  },
  // tan row: sec θ > 0 on [-1.3, 1.3] ⊂ (-π/2, π/2)
  {
    id: 'card-trig-sub-05',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'Trig sub for $\\sqrt{a^2 + x^2}$?' },
    back: { latex: 'x = a\\tan\\theta', expr: 'a*tan(theta)', checkExpr: 'a*sec(theta)' },
    check: { kind: 'identity', lhs: 'sqrt(a^2 + (a*tan(theta))^2)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [-1.3, 1.3] },
  },
  {
    id: 'card-trig-sub-06',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'dx when $x = a\\tan\\theta$?' },
    back: { latex: 'a\\sec^2\\theta\\,d\\theta', expr: 'a*sec(theta)^2*dtheta', checkExpr: 'a*sec(theta)^2' },
    check: { kind: 'derivative', of: 'a*tan(theta)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [-1.3, 1.3] },
  },
  {
    id: 'card-trig-sub-07',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'With $x = a\\tan\\theta$, $\\sqrt{a^2 + x^2}$ becomes?' },
    back: { latex: 'a\\sec\\theta', expr: 'a*sec(theta)' },
    check: { kind: 'identity', lhs: 'sqrt(a^2 + (a*tan(theta))^2)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [-1.3, 1.3] },
  },
  {
    id: 'card-trig-sub-08',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'Why tan for $a^2 + x^2$?' },
    back: { latex: '1 + \\tan^2\\theta = \\sec^2\\theta', expr: 'sec(theta)^2' },
    check: { kind: 'identity', lhs: '1 + tan(theta)^2' },
    variable: 'theta',
    domain: { theta: [-1.3, 1.3] },
  },
  // sec row: tan θ ≥ 0 on [0.1, 1.3] ⊂ [0, π/2)
  {
    id: 'card-trig-sub-09',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'Trig sub for $\\sqrt{x^2 - a^2}$?' },
    back: { latex: 'x = a\\sec\\theta', expr: 'a*sec(theta)', checkExpr: 'a*tan(theta)' },
    check: { kind: 'identity', lhs: 'sqrt((a*sec(theta))^2 - a^2)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [0.1, 1.3] },
  },
  {
    id: 'card-trig-sub-10',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'dx when $x = a\\sec\\theta$?' },
    back: {
      latex: 'a\\sec\\theta\\tan\\theta\\,d\\theta',
      expr: 'a*sec(theta)*tan(theta)*dtheta',
      checkExpr: 'a*sec(theta)*tan(theta)',
    },
    check: { kind: 'derivative', of: 'a*sec(theta)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [0.1, 1.3] },
  },
  {
    id: 'card-trig-sub-11',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'With $x = a\\sec\\theta$, $\\sqrt{x^2 - a^2}$ becomes?' },
    back: { latex: 'a\\tan\\theta', expr: 'a*tan(theta)' },
    check: { kind: 'identity', lhs: 'sqrt((a*sec(theta))^2 - a^2)' },
    variable: 'theta',
    domain: { a: [1, 3], theta: [0.1, 1.3] },
  },
  {
    id: 'card-trig-sub-12',
    category: 'Trig Substitution',
    section: 'trig-sub',
    kind: 'trig-sub',
    front: { text: 'Why sec for $x^2 - a^2$?' },
    back: { latex: '\\sec^2\\theta - 1 = \\tan^2\\theta', expr: 'tan(theta)^2' },
    check: { kind: 'identity', lhs: 'sec(theta)^2 - 1' },
    variable: 'theta',
    domain: { theta: [0.1, 1.3] },
  },

  // ── 7. Area & volume (symbolic formulas; verified by math-verifier) ──
  {
    id: 'card-area-volume-01',
    category: 'Area & Volume',
    section: 'area-volume',
    kind: 'formula',
    front: { text: 'Area between curves' },
    back: {
      latex: 'A = \\int_a^b (\\text{top} - \\text{bottom})\\,dx',
      also: 'A = \\int_c^d (\\text{right} - \\text{left})\\,dy',
    },
    check: { kind: 'none', reason: 'symbolic formula' },
  },
  {
    id: 'card-area-volume-02',
    category: 'Area & Volume',
    section: 'area-volume',
    kind: 'formula',
    front: { text: 'Disk method' },
    back: { latex: 'V = \\pi \\int R^2\\,dx' },
    check: { kind: 'none', reason: 'symbolic formula' },
  },
  {
    id: 'card-area-volume-03',
    category: 'Area & Volume',
    section: 'area-volume',
    kind: 'formula',
    front: { text: 'Washer method' },
    back: { latex: 'V = \\pi \\int \\left(R_{\\text{out}}^2 - R_{\\text{in}}^2\\right)dx' },
    check: { kind: 'none', reason: 'symbolic formula' },
  },
  {
    id: 'card-area-volume-04',
    category: 'Area & Volume',
    section: 'area-volume',
    kind: 'formula',
    front: { text: 'Shell method' },
    back: { latex: 'V = 2\\pi \\int (\\text{radius})(\\text{height})\\,dx' },
    check: { kind: 'none', reason: 'symbolic formula' },
  },

  // ── 8. Arc length ──
  {
    id: 'card-arc-length-01',
    category: 'Arc Length',
    section: 'arc-length',
    kind: 'formula',
    front: { text: 'Arc length in terms of $x$' },
    back: { latex: 'L = \\int_a^b \\sqrt{1 + \\left(\\frac{dy}{dx}\\right)^2}\\,dx' },
    check: { kind: 'none', reason: 'symbolic formula' },
  },
  {
    id: 'card-arc-length-02',
    category: 'Arc Length',
    section: 'arc-length',
    kind: 'formula',
    front: { text: 'Arc length in terms of $y$' },
    back: { latex: 'L = \\int_c^d \\sqrt{1 + \\left(\\frac{dx}{dy}\\right)^2}\\,dy' },
    check: { kind: 'none', reason: 'symbolic formula' },
  },

  // ── 9. Integration by parts ──
  {
    id: 'card-ibp-01',
    category: 'Integration by Parts',
    section: 'ibp',
    kind: 'formula',
    front: { text: 'Integration by parts formula' },
    back: { latex: '\\int u\\,dv = uv - \\int v\\,du' },
    check: { kind: 'none', reason: 'symbolic formula' },
  },
];

export function cardsInSection(section: CardSection): Card[] {
  return CARDS.filter((c) => c.section === section);
}
